### ISSUE TITLE
Special ability "Klinge drehen" is not applied after a successful attack with enough Hitpoints

### ISSUE THREAD

**Issue by Fletcher0306** [Plushtoast/dsa5-foundryVTT#1012]
Hello,

my charakter has got the special ability "Klinge drehen". In a fight this has to be applied as soon as the enemy takes more than 2 Hitpoints damage. This is currently not the case but has been with elder versions.

Regards
Kristian

**Comment by Plushtoast** [comment]
I think the ability has an on use effect now. There is no reasonable way to implement the condition to do more DMG if a threshold is met. And it's the only ability like that. So check yourself after the hit if the condition is met and then press the on use effect (the die on the char sheet or better in the tokenbar on use menu)

**Comment by Plushtoast** [comment]
Closed - no feedback
