### ISSUE TITLE
Möglichkeit zum Verbergen von Eigenschaftswerten beim Hovern im Chat

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#1013]
Derzeit ist es so, dass jeder Spieler durch Hovern mit der Maus über einen Würfel im Chat angezeigt bekommt, was der Charakter in der jeweiligen Eigenschaft für einen Wert hat. Sprich wenn ich in diesem Wurf über die 10 hovere, poppt die 14 auf:

![2022-05-10_20-38-42](https://user-images.githubusercontent.com/79639045/167700919-e3036cd3-fd31-4e57-a647-e8ff88c884ff.jpg)

Das gibt sehr viel preis. Wenn ein Wurf geschafft ist, ist es schade, wenn sofort alle wissen, welchen Wert ein NSC oder SC in dieser Eigenschaft hat.

Gäbe es eine Möglichkeit, hier eine Option zu haben, dies für Spieler abzuschalten, wie man z. B. auch den Status am Token so wunderbar verbergen kann?

Natürlich kann man auch einfach alles privat würfeln, aber ein gewisses Mitfiebern beim Würfeln der Kollegen ist ja schon schön, nur eben nicht, dass man mit jedem Wurf automatisch die Charakter- oder Gegnerwerte auf diese Weise mit verrät.

**Comment by KnoepfchenFulla** [comment]
Eine Frage zur Möglichkeit, die Eigenschaftswerte im Chat für Spieler zu verbergen: Kann es sein, dass das mit V10 verschütt gegangen ist? Die Werte werden wieder angezeigt, und ich finde keine Möglichkeit mehr in den DSA-spezifischen Foundry-Einstellungen, diese erneut auszublenden.
Vielen Dank!

**Comment by Plushtoast** [comment]
Bitte keine geclosten Tickets mehr ausgraben. Das kann sehr leicht übersehen werden. Neues Ticket machen. Ich prüfe das für den patch nachher.

**Comment by KnoepfchenFulla** [comment]
Mache ich, danke schön!
