### ISSUE TITLE
Pressing Enter to send a message in chat should not confirm the roll if the dialog is already open

### ISSUE THREAD

**Issue by Rahjenaos** [Plushtoast/dsa5-foundryVTT#1017]
**Is your feature request related to a problem? Please describe.**
It is always frustrating that sending a chat message will activate all the prepared rolls.
For example: during a fight I will already prepare my next attack; if i then write a message in chat --> the attack is performed although I don't want to

**Describe the solution you'd like**
Do not "push a button" on pressing Enter when the focus isin the chat window.
Pressing Enter while the chat window is focused should **ONLY** send the respective chat message. The Enter-Event should not be pushed to any other possible recipients

**Describe alternatives you've considered**
Alternative 1: ask the user whether he wants to do this
Alternative 2: create a setting where the behavior can be defined

**Comment by Plushtoast** [comment]
Foundry version 12 löst das Problem (war auch ein foundry problem und kein dsa problem).
