### ISSUE TITLE
Zauber Hexenkrallen - Effekt funktioniert nicht.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1018]
**Describe the bug**
Wird nach dem Zauber Hexenkrallen der Effekt auf einen Actor übertragen, kommt es zu einer Fehlermeldung in der Console. Ein Effekt wird im Actor nicht erzeugt.

**To Reproduce**
1. Zauber erfolgreich ausführen
2. Effekt (selbst/Ziel)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/168876978-0e94951e-68ab-4113-95a2-7af6c4670377.png)
![grafik](https://user-images.githubusercontent.com/80099175/168877004-7bec26e1-5a98-4b61-acac-981078566c4f.png)

**Versions:**
- Foundry Version 9.269
- DSA/TDE version 3.3.3
- Related modules version 
- Core Regelwerk 3.3.1

**Additional context**

**Comment by RandomHero13** [comment]
mit der zaubererweiterung "scharfe krallen" wird die normale "waffe" erzeugt und nicht die verbesserte mit +1TP
