### ISSUE TITLE
Kampftalende des Heshthot im Pandämonium inkorrekt...und was ist mit Waffenlos bei den anderen?

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#1023]
Siehe Bild mit den drei Actors des Heshthots:
1. Kampfwerte bei der Pandämoniumvariante falsch
2. Waffenlos-Angriff bei der Pandämoniumvariante vorhanden
3. Nur bei der Pandämoniumvariante steht, dass Heshthotim nicht fliehen.
4. Nur bie der Pandämoniumvariante wird die "Empfindlichkeit gegenüber gesegneten/geweihten Objekten/Waffen" erklärt
![Hashthot](https://user-images.githubusercontent.com/87266660/170133812-0f28b7c2-3252-4046-beea-7831f73cf9bb.jpg)

**Comment by UralterMannII** [comment]
![Hashthot2](https://user-images.githubusercontent.com/87266660/170133996-8244650f-2847-4012-b0e1-03458313ecbe.jpg)

**Comment by Murm3lt13r** [comment]
Siehe Bild mit den drei Actors des Heshthots:

1. Kampfwerte bei der Pandämoniumvariante falsch - **korrigiert**
2. Waffenlos-Angriff bei der Pandämoniumvariante vorhanden - **korrigiert**
3. Nur bei der Pandämoniumvariante steht, dass Heshthotim nicht fliehen. - **korrigiert**
4. Nur bie der Pandämoniumvariante wird die "Empfindlichkeit gegenüber gesegneten/geweihten Objekten/Waffen" erklärt - **Ist in der Print Version nur im Pandämonium enthalten, daher auch nur in der Version aufgeführt. Hier sind wir an die Inhalte der Bücher gebunden.**
