### ISSUE TITLE
(Eng) 3.4.0 - 4 Conditions in the add condition dialogue need names,

### ISSUE THREAD

**Issue by Lambert-Behnke** [Plushtoast/dsa5-foundryVTT#1027]
To me it appears that the 4 of the conditions about specific creatures are referred to by the variable name rather than a label/title.

CONDITION.lykanthrop
CONDITION.minorVampire
CONDITION.childOfTheDark
CONDITION.wercreature

Also it should be: 
CONDITION.werecreature (with an extra e)

But seeing that this is an internal variable name the user should never see the typo does not matter.

![Status](https://user-images.githubusercontent.com/82769448/170725388-6dc866db-4f10-42d4-9e8e-776fcf1a6e2f.png)

**Comment by Plushtoast** [comment]
You've got a german module enabled right? Like bestiary 2?
Those aren't translated

**Comment by Lambert-Behnke** [comment]
My bad, a friend accidentally bought 2 copies of Bestiary II and gave me the code and in the new world I just enabled all Dark Eye modules without paying attention.
I thought that was coming from the new changes to the Core Module ... no problem.
