### ISSUE TITLE
Szenenspezifisch Aktivierung von DPS

### ISSUE THREAD

**Issue by Cthustra** [Plushtoast/dsa5-foundryVTT#1030]
Die Automatisierung DPS unter der Szeneneinstellung des Meister Menüs ist nicht szenenspezifisch. 
Führt dazu es dauernd zu Wechsel zwischen Übersichtszenen bzw. Landingpage und "normalen" Karten.
Gerade wenn Spieler sich frei zwischen Szenen bewegen dürfen führt dies schnell zu Umschaltorgien.

Könnte man diese Einstellung wie auch die Dunkelheit der Szene szenenspezifisch machen?

**Comment by Plushtoast** [comment]
Kannst du genauer beschreiben, was deine Spieler auf den anderen Szenen treiben und warum du das an- und abschalten musst?
Persönlich wäre mir die Einstellung pro Szene zu umständlich und meine Gruppen sind auch immer nur auf einer Karte.

Vlt. gibts auch eine andere Lösung.

**Comment by Cthustra** [comment]
Ich erlaube meinen Spielern frei auf manche Szenen zu wechseln, bsp. die Stadtkarte mit all den ihnen zugänglichen Händlern.

Aber mittlerweile habe ich schon eine andere Lösung gefunden ;D, nachdem ich erstmal diese Nachricht nicht mehr gefunden, bzw. vergessen hatte, da sich eine andere Lösung anbot.
