### ISSUE TITLE
SL-Willkür für Trefferzonen

### ISSUE THREAD

**Issue by Meckerdrache** [Plushtoast/dsa5-foundryVTT#1035]
Es wäre toll, wenn man auf die Trefferzonen, die aktuell automatisch gewürfelt werden, auch die SL-Willkür anwenden könnte. Noch besser wäre es, wenn man wie bei den RollTables bestimmte Zonen bei bestimmten Angriffen ausschließen könnte, weil sie manchmal einfach keinen Sinn ergeben. Dass beispielsweise ein Fußkämpfer den Kopf eines Reiters mit einem Kurzschwert trifft, ist ja ausgeschlossen.

**Comment by Plushtoast** [comment]
Also für Zonen ausschließen, fällt mir nicht ein wie man das sinnvoll im GUI machen sollte ohne dass es umständlich wird.
