### ISSUE TITLE
Traditionsartefakte nicht mit Domäne Geweiht eingetragen / Kategorie Heilig?

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#1037]
**Describe the bug**
Traditionsartefakte wie Rodrakamm oder Korspieß sind nicht als Geweiht zur Berechnung des Schadens eingetragen.
Heilige Talismane wie der Schwarze Speer auch nicht. Dieser ist darüber hinaus Heilig was weitere Sonderregeln mit sich bringt (Aventurische Götter S. 70) (Wobei man solche Waffen eher selten in der Hand hat)

**Comment by Plushtoast** [comment]
Also die Talismane sollten das noch bekommen.
Aber Traditionsartefakte sind ohne Weihe erstmal nicht geweiht. Die gibts über Sonderfertigkeiten.

**Comment by Xardai** [comment]
Bei Rodrakamm oder Korspieß steht in der Beschreibung Geweiht (gottheit). Da man sie auch nur als geweihter erhält, bin ich davon ausgegangen, das sie immer geweiht sind, bzw sie bei der eigenen Weihe mit geweiht werden.
Du meinst die Zeremonie Objektweihe? hab ich noch nicht gesehen und schau mir das mal an

**Comment by Plushtoast** [comment]
https://ulisses-regelwiki.de/allgemeine_karmale_sonderfertigkeit.html?sonderfertigkeit=Zeremonialgegenst%C3%A4nde+herstellen

**Comment by Plushtoast** [comment]
Aber so genau weiß ich das auch nicht, vor allem da die Fähigkeit n Attributswert von 17 verlangt, was schon bisschen hoch ist.

**Comment by Xardai** [comment]
Wie du schon sagtest, kann ein Startcharakter kein eigenes Artefakt herstellen und da das nicht wie bei Zauberern gebunden werden muss (Er also keine pKaP dafür brauch) bin ich davon ausgegangen, dass der Geweihte ein fertiges Artefakt überreicht kriegt (zur Weihe oder für Verdienste). Ich war nur Verwirrt, da in der Item-Beschreibung geweiht explizit drinsteht. Zum Vorbeugen, dass es anderen ähnlich geht, wäre mein Vorschlag, den Text anpassen oder die Weihe reintun.

**Comment by Plushtoast** [comment]
Ich bin mir nicht mal sicher was beabsichtigt ist. Müsste da erstmal noch nachfragen. Vlt sind Zeremonialgegenstände != geweiht?
