### ISSUE TITLE
[Wurf mit echten Würfeln] Option für leere Eingabemaske

### ISSUE THREAD

**Issue by Kallimeister** [Plushtoast/dsa5-foundryVTT#1040]
Bei aktivierter Option Wurf mit echten Würfeln habe ich immer das Problem, dass ich die Zahl im ersten Feld nur per Doppelklick VOR die Zahl markieren kann, um sie mittels Tastatureingabe einzutragen. Die anderen Felder lassen sich dann zwar per Tab markiert ansteuern, leere Felder wären jedoch auch angenehmer, um sie mit einem einfachen Klick befüllen zu können.
Diese Option müsste dann Lokal sein, oder besser noch die Option Wurf mit echten Würfeln in eine Lokale Einstellung umwandeln.

**Comment by Plushtoast** [comment]
Außerdem Wurf im Chat markieren, dass er manuell war.

**Comment by Plushtoast** [comment]
Es wird nun so sein, dass beim ersten click in das feld alles markiert wird und erst bei weiteren clicks das hoch und runterzählen aktiviert ist.
