### ISSUE TITLE
Phexgeweihter Char - Würfeln auf phexgefällige Talente unmöglich

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#1041]
Ein phexgeweihter Charakter von uns kann seit dem letzten System-Update nicht mehr auf phexgefällige Talente würfeln. Folgende Fehlermeldung tritt dabei auf:
![2022-06-02_14-13-23](https://user-images.githubusercontent.com/79639045/171626912-2402ff13-d1ae-4d8a-82d9-a91d03fc7406.jpg)

(aktuellste Version von Foundry und allen DSA-Modulen) 

Alle phexgefälligen Talente (für die ein Mirakel möglich wäre) sind betroffen:
Gaukeleien, Klettern, Sinnesschärfe, Taschendiebstahl, Verbergen, Gassenwissen, Überreden, Verkleiden, Brett- & Glücksspiel, Götter & Kulte, Rechnen, Rechtskunde, Sternkunde, Handel, Schlösserknacken

**Comment by Plushtoast** [comment]
Ich denke wenn die kap mindestens 4 sind müsste es vorläufig als workaround funktionieren
