### ISSUE TITLE
Ifirngefällige Talente - Entrückung / Sinnesschärfe

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#1045]
Das Talent "Sinnesschärfe" ist ein ifirngefälliges Talent, sollte also beim Zustand Entrückung für einen Ifirni einen Bonus erhalten und keinen Malus. Dem ist nicht so - es wird ein Malus gegeben. Die anderen ifirngefälligen Talente scheinen beim Ifirni alle zu funktionieren.

**Comment by KnoepfchenFulla** [comment]
Das scheint einfach an einem Typo zu liegen bei den göttergefälligen Talenten - dort steht "Sinnenschärfe".

**Comment by Plushtoast** [comment]
Hm, ich glaube das wurde früher schon gefixt. Meinst du in der Geweihten Profession?

**Comment by KnoepfchenFulla** [comment]
Stimmt, wenn ich einen neuen Ifirn-Geweihten anlege, ist der Typo nicht mehr da. Danke!
