### ISSUE TITLE
Kein Speichern von Tokens mit Zuchtgrube-Charakteren und Tokenizer möglich

### ISSUE THREAD

**Issue by yendors-vtt** [Plushtoast/dsa5-foundryVTT#1046]
Für Charaktere, die mit der Zuchtgrube erstellt wurden, kann mit dem Tokenizer kein Token erstellt bzw. gespeichert werden.

**To Reproduce**
1. Charakter mit Zuchtgrube erstellen
2. Tokenizer für den erstellten Charakter öffnen
3. Token erstellen
4. Tocken speichern.
5. Fehlermeldung: “You are attempting to upload a file with a disallowed extension“

**Expected behavior**
Der Token wird gespeichert.

**Screenshots**
Im Tokenizer wird für Charaltere aus der Zuctgrube auch ein vermeindlich falsches Target angezeigt: 115.115 statt tokenname.webp

<img width="906" alt="bug_tokenizer" src="https://user-images.githubusercontent.com/86227849/172119614-46ce8bd3-4999-4365-a753-f6c65b1f3678.png">

**Versions:**
- Foundry 9 Build 269
- DSA/TDE 3.4.0
- Tokenizer 3.6.8

**Comment by Plushtoast** [comment]
Also bevor ich mir das anschaue, kann ich auf jeden Fall schon mal sagen, dass die Token auch fertig mit im Modul enthalten sind.

**Comment by yendors-vtt** [comment]
Dieser Token war dann vllt. ein blödes Beispiel. Aber so im allgemeinen kann ich mit der Zuchtgrube keinen NSC erstellen und anschließend einen eigenen Token mit dem Tokenizer erstellen. Im Screen geht es auch eher um den Target Filename neben dem OK-Button.

**Comment by Plushtoast** [comment]
Wenn du diesen Haken wegmachst, geht es:
![grafik](https://user-images.githubusercontent.com/44941845/174736514-e9564401-6a43-4a6f-901d-f6f5a7dcc394.png)

Muss allerdings noch prüfen, ob  das ein Tokenizer oder dsa bug ist.

**Comment by Plushtoast** [comment]
Ich werde eine kleine Änderung am Masters Workshop demnächst releasen.
Aber ich glaube der zugrunde liegende Bug kommt entweder aus Foundry oder aus Tokenizer

**Comment by yendors-vtt** [comment]
Perfekt, danke für den Workaround.
