### ISSUE TITLE
AsP-Kosten, Wirkungsdauer und Volumen unter Details bei Traditionsartefakten hinzufügen

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#105]
**Is your feature request related to a problem? Please describe.**
Damit die AsP-Kosten für Effekte referenziert werden können müssen sie ein eigenes Feld im Details Reiter haben.

**Describe the solution you'd like**
Im Details Reiter von Traditionsartefakt-Sonderfertigkeiten die Felder AsP-Kosten, Wirkungsdauer und Volumen ergänzen.
Bei anderen Sonderfertigkeiten (z.B. Vertrautentricks) gibt es die Felder ebenfalls, warum also bei Traditionsartefakt-Sonderfertigkeiten bei denen es ebenfalls relevant wäre nicht?
Der Stabzauber "Flammenschwert" ist ein gutes Beispiel dafür.

**Comment by vt-tom** [comment]
Da ich gerade die Traditions-Artefakte kontrolliert habe hier nochmal n kurzer Push der Anfrage. Mir persönlich würde es schon reichen das Maximale Volumen in der Beschreibung der Items zu haben um sie dann manuell zu tracken.

Optimal wäre aber das Volumen im Item und der Fertigkeit und dann beim auf das Item ziehen verrechnen...
