### ISSUE TITLE
Macro "Show applications" returns an error.

### ISSUE THREAD

**Issue by br00n0** [Plushtoast/dsa5-foundryVTT#1054]
When trying executing the macro called "Show applications", an error message gets displayed:
"There was an error in your chat message syntax."

1. Open the (dsa5-core) Macros in the Compendium
2. Click on "Show applications" macro
3. Click on the "Execute macro" button

Applications by skill should by displayed.

- Foundry Version 9.269
- DSA/TDE version 3.4.5

The macro command sends "/apps" to the chat. This command does not exist in the chat.

**Comment by Plushtoast** [comment]
You Need the aventurian compendium for that to work. We will put all the macros in the Core module so They can be found and are visible at all

**Comment by br00n0** [comment]
Seeing the error message was concerning but I understand. Thank you!

**Comment by Plushtoast** [comment]
I can add a More meaningful error Message there

**Comment by br00n0** [comment]
Good idea. Something like "Aventurian Compendium required to execute this macro."
