### ISSUE TITLE
Waterskin cannot be dragged and dropped in equipment.

### ISSUE THREAD

**Issue by br00n0** [Plushtoast/dsa5-foundryVTT#1055]
The Waterskin from "dsa5-armory" cannot be dragged and dropped in equipment, it simply does not appear. The one from "dsa5-core" can but lacks details from the Armory.

1. Locate Waterskin (dsa5-armory)  equipment in LIbrary
2. Drag and drop it your hero's equipment

The waterskin should be added to the hero's equipment list. The waterskin from dsa5-core functions properly.

- Foundry Version 9.269
- DSA/TDE version 3.4.5

**Comment by Plushtoast** [comment]
You probably put it into a bag somewhere where it gets stacked

**Comment by br00n0** [comment]
Ok never mind my equipment ticket and the other one. Those can be quickly adjusted in-game. However we must be careful with equipment attributes as not everyone is able to edit items.

**Comment by br00n0** [comment]
Yes, item was dropped in a container. You can cancel this issue.
