### ISSUE TITLE
Sprache erlernen zieht keine AP ab

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#107]
Wenn man eine Sprache erlernt, wird diese zwar von den durch das Professionspaket freien AP abgezogen, aber darüber hinaus werden die Kosten nicht abgezogen. Beispiel: Professionspaket bietet 12 AP. Hat man bereits mehrere Sprachen erlernt für 10 AP und noch Bosperano dazu zieht, erhöht sich der Wert korrekt auf 12. Wenn man dann aber Bosperano II erlernt, bleiben Sprachen-AP und ausgegebene AP identisch.

**Comment by Plushtoast** [comment]
Duplicate of #109 

Bitte die +- Buttons zum Steigern verwenden. Das Input Feld ist nur als Fallback und für manuelle Anpassungen aus jeglichen Gründen gedacht.
