### ISSUE TITLE
DSA5: Hylailos Stil wird nicht berechnet

### ISSUE THREAD

**Issue by KiroGustavson** [Plushtoast/dsa5-foundryVTT#1072]
**Describe the bug**
Hi all,
just created a "Hylailer Krieger". He uses the "Kampf Sonderfertigkeit" "Hylailos-Stil". This advantage should increase AT and PA by one using "Stangenwaffen". Now the Warrior uses a Pailos 2H. Unlikely the engine does not increase the AT and PA values by its own.

**To Reproduce**

![Hylailer Krieg Pailos](https://user-images.githubusercontent.com/93646444/174623034-c5bb9c5f-50dd-4a8c-be59-b7ce7a7bab50.png)

Please refere to this screenshot.

**Expected behavior**
Used AT and PA values should 15 / 7 and not 14 / 6.

**Versions:**
- 9.269
- DSA/TDE version 3.4.5.39
- DSA Compendium I 3.2.1

Thank you for your support and a short reply
Best regards

Thomas

**Comment by Plushtoast** [comment]
Die Fähigkeit reduziert nur den Malus von Stangenwaffen und gibt nicht einen flachen Bonus.
Das ist derzeit und mittel- bis langfristig auch nicht möglich.

Du kannst im Effektfeld "+1 PA, +1 AT" eintragen dann ist es zumindest im roll dialog anwählbar

**Comment by KiroGustavson** [comment]
Hallo Plushtoast,
vielen Dank für Deine Rückmeldung.
Ich habe nun den Hylailos Kampfstil in das Itemverzeichnis kopiert, zu Hylailos Styl #2 umbenannt und einen Statuseffekt hinzugefügt, welche die AT und PA um einen erhöht (Ja, ich weiß, dass der Bonus nicht größer als 0 sein kann. Das regel ich mit dem Spieler bei Bedarf). Füge ich nun diese angepasste Kampfsonderfertigkeit dem Char hinzu, passiert nichts. Wechsel ich die Kategorie der Kampfsonderfertig von "Kampf" auf "Magisch" und lasse den Rest komplett, erscheint in der Statusübersicht der Styl! Ich kann bei der AT Probe nun auch "Statuseffekt" markieren und erhalte den Bonus.

Warum geht das nur leider nicht, wenn die Kategorie auf "Kampf" steht?

Grüße

Thomas

**Comment by Plushtoast** [comment]
Active Effects auf Kampfsonderfertigkeiten sind nur dazu da auf den Gegner übertragen zu werden.
Du musst im Effektfeld das oben genannte eintragen.

**Comment by KiroGustavson** [comment]
Hallo Plushtoast,
danke für Deine Geduld :) Jetzt habe ich gefunden, was Du meintest 👍 

Grüße 
Thomas
