### ISSUE TITLE
Creating custom macros?

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#1073]
I'm trying to create a custom macro for certain combinations of modifiers, rerolls, and limits, but I can't for the life of me find the correct keywords to get a nice skill card. I couldn't find the source code of the entire sheet either (otherwise I would've searched for it there), can someone help? 

My main issue is with figuring out the dice rolls on the card.

**Comment by Plushtoast** [comment]
You'll need to be more specific.
But my recommendation is to look at the macros in the official modules.

Programming lessons not included.

**Comment by ghost** [comment]
I want to write a skill roll; 
Stealth but with rerolls and modifiers included. When you click on the stealth skill in the character sheet you get something like this; 
![image](https://user-images.githubusercontent.com/107870094/174901864-7f7231c9-504b-464a-89a9-355e973502ac.png)

With the macro I want to roll the same card, but basically just change the math. I need to know what the dice are called so i can reference them (like idk stealth_attribute_1 or sth)

Ah fun.

**Comment by Plushtoast** [comment]
Is this roll20?

**Comment by Plushtoast** [comment]
The repository for roll20 is here: https://github.com/Plushtoast/TDE-Roll20-Official/issues

But the 3d20 roll is very complicated and difficult to do in roll20. It works via sheetworkers, so macros are barely possible

**Comment by ghost** [comment]
Yes, although it is possible that it's a different sheet from the one you're working on here, I had just assumed it was the same one as your project here as the two have the same names, and when I was looking through the sources of that sheet i got lead to this github site..

Thanks, i'll see if i can find something more.

I'll try my best ^^'
