### ISSUE TITLE
Dienstleistungen (Master Workshop)

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#1077]
Sämtliche Getränke, Gerichte als Dienstleistung hinterlegen (für  Master Workshop).
Aufnahme weiterer Dienstleistungen (siehe Dienstleistungen in https://www.ulisses-ebooks.de/product/208930/DSA5--Index-Monetaria-Aventuris) [möglicherweise weiteres Modul für Händler Erweiterung von Gegenständen Kutsche/Karren/Erze/ etc.]
Extra Haken in der Bibliothek Suchfunktion, um schneller nach speziellen Dienstleistungen suchen zu können.

**Comment by Plushtoast** [comment]
Wir werden keine Skriptorium Dinge umsetzen, das kann ich schon mal sagen.

**Comment by Neon82** [comment]
Ist im Basisregelwerk sind sie auf Seite 382. Im Core stehen die
Dienstleistungen Im Jornal unter Ausrüstung aber halt nich in der
Bibliothek. Auch fehlt die Möglichkeit gezielt nach Dienstleistungen zu
suchen.

Plushtoast ***@***.***> schrieb am So., 3. Juli 2022, 20:26:

**Comment by Plushtoast** [comment]
Das ist der Gehirnfilter:
![grafik](https://user-images.githubusercontent.com/44941845/177369447-484f74d9-dae2-4fc8-acc1-d83b218a7977.png)

Ansonsten haben wir das auf dem Schirm.
Dienstleistungen waren zu Beginn technisch nicht sinnvoll umsetzbar.

Siehe auch hier #1004

**Comment by Plushtoast** [comment]
Die nächste Version wird custom Lebensmittel unterstützen. 
Mit den Dienstleistungen geht ein bisschen was, allerdings nicht alles. Seh ich auch momentan nicht wie das zu regeln wäre, da die Dienstleistung zusätzlich noch eine Info bräuchte wo sie verfügbar ist (Schmied, Schreiber) etc

Ich schließe das Ticket erstmal und lege für diesen Fall ein neues an, das vermutlich nicht so bald mal angegangen werden kann

**Comment by Plushtoast** [comment]
Siehe #1686
