### ISSUE TITLE
TDE5e Core Rules displays wrong version number in Module Management

### ISSUE THREAD

**Issue by br00n0** [Plushtoast/dsa5-foundryVTT#1079]
**Describe the bug**
In Module Management, the TDE5 Core Rules shows version 3.4.0 when it's been updated to 3.4.5

**To Reproduce**
1. Update TDE5 Core Rules module to the latest (3.4.5) version
2. Create or open a new world using TDE5 Dore Rules
3. Open Module Management and locate TDE5 Core Rules module in the list

**Expected behavior**
Version displayed should be 3.4.5 and not 3.4.0

**Screenshots**
![image](https://user-images.githubusercontent.com/79856383/177834235-5fcabe84-4a4a-4cc8-9d82-03ecc07aa757.png)

**Versions:**
- Foundry Version 9.269
- DSA/TDE version 3.4.5

**Comment by Plushtoast** [comment]
Foundry, the tde system and the core module are three different things. They are allowed to have different versions
