### ISSUE TITLE
Removing token light source causes client-side error message

### ISSUE THREAD

**Issue by br00n0** [Plushtoast/dsa5-foundryVTT#1080]
**Describe the bug**
When removing a light source from a token using Token HUD for lights, players receive an error message.
"User XXX lacks permission to update Token [XXX] in parent scene [XXX]"
Light source does get removed for all players but error message is displayed.

**To Reproduce**
1. Assign a light source to a token using light HUD (ex: torch)
2. Remove the light source from the same toke using the light HUD (the empty circle)

**Expected behavior**
No error message should appear as the light source was removed successfully.

**Screenshots**
Lights HUD
![image](https://user-images.githubusercontent.com/79856383/177835223-ec7cbfd4-6347-477c-a37b-20efd4045f7f.png)

Error message
![image](https://user-images.githubusercontent.com/79856383/177834751-aa728786-a09b-4a9b-8867-f4c410a1d17a.png)

**Versions:**
- Foundry Version 9.269
- DSA/TDE version 3.4.5
- NO OTHER MODULE ACTIVE, only Core Rules is active

**Additional context**
- Only Core Rules is active and message still appears so it's not a module interference.
- Also, message does not appear when player is Owner of the token from which the light source is removed.

**Comment by hnsstrk** [comment]
Same issue over here. DSA Version 3.5.0.
Tested in a fresh world with only the DSA core module, local installation and server.
Log says: 

Error: User ***** lacks permission to update Token [*****] in parent Scene [*****]
    at ServerDatabaseBackend._updateEmbeddedDocuments (file:///var/www/vhosts/XXXXX/httpdocs/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:3611)
    at async Semaphore._try (file:///var/www/vhosts/XXXXX/httpdocs/foundryvtt/resources/app/common/utils/semaphore.mjs:99:17)
