### ISSUE TITLE
Fulminictus mit Verteidigungsmalus?

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#1081]
Ist es eigentlich Absicht, dass beim Fulminictus der Verteidigungsmalus -4 aufgeführt wird?
![image](https://user-images.githubusercontent.com/82062265/177995909-e0313585-1108-4b09-a9a2-710e410ccc8d.png)

Eigentlich ist bei diesem Zauber ausdrücklich kein Ausweichen möglich. Könnte etwas irreführend sein 
![image](https://user-images.githubusercontent.com/82062265/177996012-72501887-766d-4a94-ac2e-37c142c24ebb.png)

**Comment by Plushtoast** [comment]
Zauber haben kein Attribut dafür also ist es Absicht
