### ISSUE TITLE
Optional hitzone rules in Game-System

### ISSUE THREAD

**Issue by ImmaB** [Plushtoast/dsa5-foundryVTT#1082]
To play with hitzones you currently have to buy 3 modules:
- [The Core Module](https://www.f-shop.de/detail/index/sArticle/2157) (20 €) 
- [The Compendium](https://www.f-shop.de/virtual-tabletops/das-schwarze-auge-vtt/regel-module/2387/dsa5-aventurisches-kompendium-fuer-foundry) (18 €) 
- [The Armory II](https://www.f-shop.de/virtual-tabletops/das-schwarze-auge-vtt/regel-module/2644/dsa5-aventurische-ruestkammer-ii-fuer-foundry-vtt) (18 €)

Alternatively the hitzone rules could be moved to the base game-system.

**Comment by vt-tom** [comment]
I don't think that would be usefull. Only if you don't want to spend the money to the three modules, but for no other reason.
If you play on the table, you also need afaik all three books to play with the rules. So why should the mechanic be implemented in core, though the rules are in two other modules?

**Comment by Plushtoast** [comment]
I am not even going to explain or discuss this anymore. Offer your next employer to work for free and gift his intellectual property to everyone. Then see how well this works for you. https://youtu.be/royjo135P2Q
