### ISSUE TITLE
Zauberschaden Bug

### ISSUE THREAD

**Issue by Ben528491** [Plushtoast/dsa5-foundryVTT#1085]
Der Zauberschaden wird falsch berechnet, wenn mehrere Effekte vorliegen, die den Zauberschaden erhöhen. Wenn ein Magier den SCHOLAR DER HALLE DES VOLLENDETEN KAMPFES ZU BETHANA besitzt (+2 Zauberschaden) und nun einen Ring trägt, der den Zauberschaden um 1 erhöht, so wird der Schaden nicht um 3, sondern um 10.

1. Erstelle einen Magier mit der magischen SF SCHOLAR DER HALLE DES VOLLENDETEN KAMPFES ZU BETHANA
2. Erstelle einen weiteren Gegenstand, der unter Effekte data.spellStats.damage um 1 addiert und rüste diesen aus
3. Zaubere einen beliebigen Zauber
4. Beobachte den verursachten Schaden des Zaubers

Zauber mit Scholar Bethana:
![Unbenannt3](https://user-images.githubusercontent.com/74898509/179781200-e897c328-7e44-429e-92aa-5cb7cdd2216c.PNG)
Tooltip der Trefferpunkte zeigt folgendes an:
2d4+4*2
Statuseffekte 2

Ring:
![Unbenannt](https://user-images.githubusercontent.com/74898509/179781615-5846eb72-6136-452d-a4db-e4435fc1379d.PNG)

Zauber mit Scholar Bethana und magischem Ring:
![Unbenannt4](https://user-images.githubusercontent.com/74898509/179781735-992f6ea2-91ab-4fd6-baec-efc0155a9a3d.PNG)
Tooltip der Trefferpunkte zeigt folgendes an:
2d4+4*2
Statuseffekte 10

**Versions:**
- Foundry Version 9
- Das Schwarze Auge 3.5.0
- Problem trat auch auf, nachdem alle Module deaktiviert wurden

**Comment by Plushtoast** [comment]
Musst ein plus oder minus davor packen weil das nicht nur zahlen sondern auch wuerfel wie zb 1d6 erlaubt

**Comment by Ben528491** [comment]
Alles klar danke. Klappt so wunderbar bei mir :)
