### ISSUE TITLE
Steigern der Talente reduziert nicht die AP

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#109]
AP Berechnung erfolgt nicht beim Steigern der Talente

**Comment by Plushtoast** [comment]
Die Berechnung erfolgt nur über die Verwendung der +- Buttons. Das Input Feld direkt dient dazu, dass der Spieler die völlige Freiheit ohne Automatismen über den entsprechenden Wert hat. z.b. Bei der Charaktererschaffung oder wenn etwas falsch berechnet wurde, ein Bug im Spiel ist etc. Das Berechnen der AP über das Input Feld ist nicht vorgesehen und ist für das Design nicht vorgesehen.

**Comment by UrielMhezzek** [comment]
Wenn etwas vorhanden ist, sollte es auch funktionieren oder passend benannt werden. In die Falle werden viele rein laufen, wer es nicht weiß. Insbesondere beim Übertragen von Chars.

**Comment by Plushtoast** [comment]
Working as intended
