### ISSUE TITLE
Improvisierte Waffen regeltechnisch umsetzen

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#1095]
Laut Regeln bekommen alle improvisierten Waffen folgende Zusätze:
![image](https://user-images.githubusercontent.com/82062265/180971796-957d4d28-3b13-45d9-8cb7-a68fc44420fb.png)

Mit der erneuerten Spielmechaniken ist es möglich, diese Regeln bei den impro Waffen ebenfalls umzusetzen.
![image](https://user-images.githubusercontent.com/82062265/180971964-341af3bf-90e2-4bbe-8ed2-a2512a516eff.png)

Bei den aktuellen Modulen betrifft es folgende Gegenstände:
[Liste impro Waffen.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/9188423/Liste.impro.Waffen.txt)

**Comment by Plushtoast** [comment]
19 is automatisch drin wenn der Name mit (i) endet.
Das 2. könnte auch schon drin sien, weiß ich nicht.

**Comment by Nellkir** [comment]
Ah ist ja cool.
Dann teste ich das mal :-)

**Comment by Nellkir** [comment]
Ja, beide Regeln sind schon funktional implementiert.
Kannst schließen XD
