### ISSUE TITLE
Kein Ulmenwürgertee beim Ulmenwürger

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1104]
**Is your feature request related to a problem? Please describe.**

Hi, habe gerade den ersten fehlenden Link im Herbarium gefunden:
Beim Ulmenwürger fehlt unter Rezepte der Ulmenwürgertee.

**Comment by Murm3lt13r** [comment]
Der Würgetee ist unter Haltbarmachung genau wie im Buch enthalten.
Unter Rezepte ist der Tee laut Herbarium nicht aufgeführt - wurde dennoch ergänzt
