### ISSUE TITLE
Adding of adventure/campain marker to NCS´s / Hinzufügen von Abenteuer/Kampangenmarker zu den NSC´s

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1109]
Hallo,
Ich bin gerade dabei mein Foundry fit zu machen für eine Abenteuer- und Kampangenrunde. Dabei ist mir aufgefallen das ich leider keine Möglichkeit habe den NSC mit den Symbolen zu markieren um auch die wichtigkeit selbiger innerhalb des Plots im blick zu behalten. Aktuell geht es zwar auch über den Notizreiter aber es fühlt sich leider ein wenig wie eine Krücke an und gefällt mir nicht all zu gut aktuell. Seht ihr da eine Chance/Möglichkeit das zu implementieren?

LG und vielen dank für diese wundervollen Module

Sebastian

**Comment by Plushtoast** [comment]
Meinst du die garadansymbole? Die kannst du haben wenn du das hendlersheet aktivierst und dann die gardan option. Allerdings haben die Charaktere dann keine Talente mehr

**Comment by Chrosarius** [comment]
Ah okay, das ist natürlich auch suboptimal ohne talente, Aber ja meinen vermutlich dasselbe, hab zur vorsicht mal n screenshot gemacht von dem was ich genau meine (Hätte mir natürlich auch schon eher einfallen können) da steht zwar 3 aber für kampangen wurde wohl auch noch ein Turm etabliert
![Meisterpersonen](https://user-images.githubusercontent.com/110413260/182249688-23db09ea-6071-4477-a5db-89eeb0d2fe89.jpg)

**Comment by Plushtoast** [comment]
Es hat keine Talente weil diese Charaktere normalerweise in den Büchern auch nichts weiter haben.
Improvisieren lässt sich das mit dem /ch command zb

Ich glaub nicht, dass hier eine Änderung kommen wird

**Comment by Chrosarius** [comment]
Ah alles klar, weis dann bescheid :) Ich mach das dann hier zu ;)
