### ISSUE TITLE
Orks haben zweimal Dunkelsicht I zur Auswahl

### ISSUE THREAD

**Issue by hnsstrk** [Plushtoast/dsa5-foundryVTT#1110]
Bei der Erstellung eines Orks wird zweimal die Dunkelsicht I zur Auswahl angeboten. Bei den Vorteilen müsste das IMO Dunkelsicht II sein.

![Screenshot 2022-08-02 102627](https://user-images.githubusercontent.com/3907750/182329908-89ff1ed2-1c8a-4227-84f6-3ba80113ff49.png)

**Comment by Plushtoast** [comment]
Beide Stufen werden jetzt addiert mit Patch 3.5.2
Ork Modul auch updaten
