### ISSUE TITLE
Uncaught (in promise) TypeError: game.das5 is undefined in newPackages.js:25:8

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#1114]
**Describe the bug**
Fehlermeldung in der Konsole

**To Reproduce**
1. Deaktiviere alle anderen Module
2. Aktivieren des installiere das Modul "Ork - Hauer und Schwarzer Pelz"
3. Console nach Anmeldung als Gamemaster (sowohl in Firefox als auch Chrome)

**Expected behavior**
Keine Fehlermeldung auf der Konsole und - basierend auf der Fehlermeldung - dass das Modul geladen wird.

**Screenshots**
![1114_Uncaught (in promise) TypeError game das5 is undefined in newPackages js 25 8](https://user-images.githubusercontent.com/87266660/182477086-33e5e56d-ffd8-4ddd-83ec-2b799709f741.jpg)

**Versions:**
- Foundry Version V9.269
- DSA/TDE version 3.5.1
- Related modules version 3.5.0

**Additional context**
Cache in den Browsern gelöscht, Server neu gestartet, Updates ausgeführt --> Fehler bleibt

**Comment by Plushtoast** [comment]
Das Core Modul ist Bedingung für alle anderen Module.

**Comment by Plushtoast** [comment]
Ah nein typo
