### ISSUE TITLE
Geheime Informationen über QS im Beschreibungstext, Herbarium

### ISSUE THREAD

**Issue by MaxLaska** [Plushtoast/dsa5-foundryVTT#1117]
Hallo,

beim Herbarium ist mir aufgefallen dass geheime Informationen, die die Spieler besser nicht lesen sollten, 
im Beschreibungstext zu lesen sind. Der Abschnitt _Was meine Spieler über diese Pflanze wissen_ , mit anschließender Auflistung der QS1 bis QS3, sollte im Beschreibungstext der Pflanze nicht auftauchen, denn ansonsten kann man als Spielleiter das Wildwuchs Tool nicht richtig nutzen, so dass man die Spieler eine Pflanze identifizieren lässt und sie diese dann ins Inventar bekommen. Denn dort können sie dann zb die Informationen zu QS 3 nachlesen obwohl sie vielleicht eigentlich nur eine QS1 gewürfelt haben.

Lösung:
Ich stelle mir vor dass man das über eine CSS- Klasse löst und dem Abschnitt mit geheimen Informationen mit einer Klasse _dsa-sl-info_ oder sowas belegt und dann gibt es vielleicht eine Checkbox in den Spieleinstellungen _Verstecke geheime Informationen in Beschreibungstexten für die Spieler_

Sollte das zu schwierig sein bin ich dafür, solche sensiblen Informationen generell nicht in den Beschreibungen zu hinterlegen, dann muss eben der Meister gefragt werden.

Liebe Grüße
Paperplane

**Comment by Plushtoast** [comment]
Related #1049
