### ISSUE TITLE
Wissenstalent Brett und Glücksspiel fehlt

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#112]

**Comment by Plushtoast** [comment]
Bitte sicherstellen, dass die neuste Version installiert ist.
Letzte Woche war das Talent für zwei Tage nicht drin. Neue Charaktere sollten es aber automatisch haben. Falls du in dieser Zeit Charaktere angelegt hast, zieh das Talent bitte manuell aus dem Talente Kompendium auf deinen Charakter.

**Comment by UrielMhezzek** [comment]
Korrekt. In einen neuen Char ist das Talent dabei. Mein Wildschwein hatte es, der Charakter nicht :)
