### ISSUE TITLE
Schaltflächen für Wundeffekte unklar und anscheinend fehlerbehaftet

### ISSUE THREAD

**Issue by GenX187** [Plushtoast/dsa5-foundryVTT#1127]
**Describe the bug**
Ich verwende in meiner DSA Runde gerne die optionale Regel für "Wundschwelle und Wundeffekte" (DSA5 Aventurisches Kompendium - Seite 131-132). Doch leider scheint diesbezüglich irgendwie noch etwas nicht ganz korrekt zu sein.

**To Reproduce** & **Expected behavior**
In der beigefügten Grafik versuche ich einmal die Ungereimtheiten zu erläutern.

Die Schaltflächen für die Wundeffekte sind irgendwie verwirrend, da ich davon ausgehen würde, dass "Wunde (TP) widerstehen" grundsätzlich den höheren Modifikator bewirkt, da ja bei den TP der Rüstungsschutz noch nicht berücksichtigt ist.
Es scheint aber genau umgekehrt zu sein, denn bei meinem Beispiel von TP 13 und SP 10 wird bei einem Klick auf die jeweilige Schaltfläche zunächst korrekt eine Probe auf Selbstbeherrschung (Handlungsfähigkeit bewahren oder Störungen ignorieren) eingeblendet.

Doch der höhere Modifikator (in meinem Beispiel -2) wird nun aber bei der Schaltfläche "Wunde (SP) widerstehen" herangezogen!?
Ist das so beabsichtigt und ich verstehe nur die Logik dahinter nicht, oder ist dies ein Fehler?

Zudem scheint auch die hintergründige Berechnung noch nicht ganz korrekt zu sein:

In meinem Beispiel sollte das Opfer (Orestas) ja eine Wundschwelle von 7 besitzen (13/2 = 6,5, also 7). Ob das der Fall ist, kann ich nicht sagen, da es für die WS leider bislang noch keine Anzeige im Charaktersheet gibt (könnte man vielleicht auch mal ergänzen).
Ein Modifikator von -2 sollte demnach überhaupt erst ab einem Schadenswert von >= 14 (entspr. Zweifachem der Wundschwelle 7) genutzt werden.

**Screenshots**
![DSA-Thema Wundschwelle](https://user-images.githubusercontent.com/35866459/182822188-1b669787-2719-456b-82a3-f008a850e40e.jpg)

**Versions:**
- Foundry Version 9 - Build 269
- DSA/TDE version 3.5.1

- Related modules version
DSA Compendium I - Version 3.2.1

**Comment by Nellkir** [comment]
Alle Buttons mit (TP) bedeuten, dass der RS vom Würfelwert abgezogen wird.
Alle Buttons mit (SP) bedeuten, dass der RS nicht vom Würfelwert abgezogen wird.

**Comment by Nellkir** [comment]
Empfehle bei den Buttons die Beschriftung zu ändern, da scheinbar mehrere diesem Irrtum erliegen.

Vorschlag 1:
Wunde (SP abzüglich RS) widerstehen
Wunde (SP direkt) widerstehen

Vorschlag 2:
Wunde (X SP) widerstehen
Wunde (Y SP) widerstehen

X und Y sind die Zahlenwerte.

-------------
Falls eine Anpassung in Frage käme, sollte es natürlich gleichfalls auf die andere Auswahlmenüs gleichgezogen werden. Aus dem Kopf fällt mir nur die "Schaden anwenden" Funktion ein.

**Comment by Plushtoast** [comment]
SP bedeutet Schaden der die Rüstung ignoriert. Es ist also mehr Schaden als bei TP. Insofern ist das so korrekt. 
Ich kann da einen Tooltip dazu machen.

**Comment by GenX187** [comment]
Das erklärt aber dann dennoch nicht, warum der Modifikator dann bei "Wunde (SP) widerstehen" auf -2 gesetzt wird. 
Wenn der Schaden die Rüstung ignoriert, dann erreicht man mit 13 Schaden ja dennoch nicht die notwendige, zweifache Wundschwelle von min. 14 in diesem Fall.
Die Berechnung der Wundschwelle mit dem DSA regeltypischen Aufrunden scheint also dann dennoch nicht 100% zu funktionieren nach meinem Verständnis?

**Comment by mckee14** [comment]
Das wäre toll. Im GRW wird ja stets von den TP als Bruttowert und SP als
Nettowert gesprochen, also "TP - RS = SP".

Regulärer Kampfschaden hat das gleiche "Problem". Kann man sich einfach
merken, allerdings ist es nicht mit der DSA nomenklatur konsistent.

Plushtoast ***@***.***> schrieb am Fr., 5. Aug. 2022, 12:57:

**Comment by GenX187** [comment]
> Das wäre toll. Im GRW wird ja stets von den TP als Bruttowert und SP als Nettowert gesprochen, also "TP - RS = SP". Regulärer Kampfschaden hat das gleiche "Problem". Kann man sich einfach merken, allerdings ist es nicht mit der DSA nomenklatur konsistent. > 

Genau daher rührt eben auch meine Irritation

**Comment by Plushtoast** [comment]
Schaden anwenden als TP --> resultierender Schaden SP = TP -RS --> weniger Schaden
Schaden anwenden als SP --> resultierender Schaden SP = SP       --> Schaden entspricht Wurf
Erscheint mir konsistent genug.

**Comment by GenX187** [comment]
> Schaden anwenden als TP --> resultierender Schaden SP = TP -RS --> weniger Schaden Schaden anwenden als SP --> resultierender Schaden SP = SP --> Schaden entspricht Wurf Erscheint mir konsistent genug.

Stimme ich zu und ist nun auch verstanden. Es kam da halt durch die Formulierungen im GRW wohl bei mir etwas zu Verwirrung.

**Dann wäre nur noch die Frage offen, warum in meinem Beispiel nicht bei beiden Varianten der Modifikator auf -1 bleibt?**

Ob ich also 10 oder 13 Schaden erleide, ist für die Probe bzgl. dem Wundeffekt egal, denn beides liegt über 7 aber unter 14. Somit sollten doch beide Schaltflächen in diesem Beispiel zu einer identischen Probe mit gleichem Modifikator führen, oder stehe ich hier auf dem Schlauch? I**ch vermute, dass der Wert für die Berechnung der Wundschwelle abgerundet wird** . 
Also aus der 6,5 dann im Beispiel eine Wundschwelle von 6 gemacht wird. 
Dann wäre die doppelte WS nämlich bei 12 und die 13 Schaden würden dann einen Modifikator von -2 provozieren.

**Comment by Plushtoast** [comment]
ich schau nochmal nach

**Comment by Plushtoast** [comment]
Fehler in der Berechnung wird im nächsten Patch korrigiert. Rundungsfehler
