### ISSUE TITLE
Wusstest du schon meldung über eine option nicht von alleine verschwinden lassen können

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1136]
Halo,
Keine ahnung ob es einfach machbar ist, aber falls ja wäre es super eine möglichkeit zu haben das diese Meldungen nicht von alleine wieder verschwinden, aktuell hauen die mir immer zu schnell ab (alter mann und so xD) um sie voll nutzen zu können :)

LG

Sebastian

**Comment by Plushtoast** [comment]
Hab die Zeit auf 8s erhöht und es gibt einen Stopbutton im nächsten Patch (den man trotzdem rechtzeitig treffen muss)
![grafik](https://user-images.githubusercontent.com/44941845/183493684-dfd2a15a-75e5-4dbf-995a-d9ad2ec992be.png)

**Comment by Chrosarius** [comment]
Ah super, vielen lieben dank *freu*
