### ISSUE TITLE
falsche Leiteigenschaft bei Professionen (Magie 2-3)

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1138]
- Bei Rashduler Dämonologe - Pfad des Golembauers, Schwarzmagierin der Schule der variablen Form zu Mirham, Schwarzmagierin der Schule der variablen Form zu Mirham - Pfad des Golems & Schwarzmagierin der Schule der variablen Form zu Mirham - Pfad des Schattens Müssten die Leiteigenschaft Klugheit haben (Aktuell Mut)
- Auch die ganzen gildenlosen Professionen haben aktuell Mut als Leiteigenschaft (müsste bei Gildenmagier Tradition Klugheit sein)
- Bei den Brobim-Geoden Professionen müsste es Charisma sein (aktuell Mut)
- Bei den Diener der Erdmutter Professionen müsste es Charisma sein (aktuell Mut)
- Bei der Durro-Dûn Profession müsste es Intuition sein (aktuell Mut)
Also soweit ich es sehen kann scheint es fast alle (vielleicht auch alle hab aber nicht alle durchgesehen um es eindeutig sagen zu können) Professionen mit der Tradition Gildenmagier, Animisten, Geoden, Brobim-Geoden, Druiden, Zibiljas sind betroffen nach meiner Überprüfung.

**Comment by Chrosarius** [comment]
Achso die Traditionen selber sind aber passend in der textbeschreibung was ich soweit gesehen habe

**Comment by Plushtoast** [comment]
Murm dann bitte auch in r20

**Comment by Murm3lt13r** [comment]
Done in Foundry
