### ISSUE TITLE
Configure Permissions Acotr

### ISSUE THREAD

**Issue by Invisible303** [Plushtoast/dsa5-foundryVTT#114]
Die unterschiedlichen "Permission Configuration" (Limited, Observer, Owner) haben wir die Spieler keinen unterschied. Es können bei NSC´s  jeder Wert eingesehen werden.

Nachstellung:

1.Navigation in das Menü "Actor Directory"
2. Schaltfläche "Create Actor" nutzen
3. Name hinterlegen (z.B. Test) und unter Type "Nichtspielercharakter" (Zukünftig mit NSC abgekürzt) auswählen.
4. Mit der rechten Maustaste auf den NSC klicken und das Menü "Configure Permission" auswählen.
5.Unter All Players gibt es 3 Anwendungsmöglichkeiten (Limited, Observer, Owner)
Limited (Begrenzt) und Observer (Beobachter) können jeweils den vollständigen Charaktersheed einsehen.

**Comment by Plushtoast** [comment]
Duplicate of #115
