### ISSUE TITLE
Vorschlag zur implementierung der Schatzkarten

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1145]
Hallo,
Wollte einmal vorschlagen ob nicht vielleicht die Schatzkarten implementiert werden könnten als Modul ( Habe in einem Video gesehen das ihr ein ähnliches System ja in Savage worlds drinne habt, das man dafür vielleicht anpassen könnte) um dann auch in Foundry ggf. digital die Spieler eine ziehen lassen zu können die man dann im chat sehen kann

**Comment by Plushtoast** [comment]
ich weiß nicht was du mit schatzkarten meinst. auch mit savage worlds habe ich nichts zu tun (wir setzen dsa für foundry bzw ulisses um sind aber kein teil von ulisses.
Ansonsten gibt es im mastersworkshop einen schatzgenerator, der je nachdem was dir hier vorschwebt auch erweitert werden könnte.

**Comment by Chrosarius** [comment]
ah verstehe, schatzkarten ist eine kartensammlung die ulisses für dsa rausgebracht haben. hab mal eine solche angehangen, Stimmt mein fehler, den schatzgenerator hab ich tatsächlich vergessen, der erfülllt schon diesen zweck
![img_0053](https://user-images.githubusercontent.com/110413260/185922454-d7e7455b-090c-4031-ba05-85c6e3b1e474.jpg)
t
