### ISSUE TITLE
Bilder im Pflanzen sheet können nicht ersetzt werden bei aktiven Tokenizer modul

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1146]
Es istnur ein kleines Problem, aber bin da letztens zufällig drüber gestolpert. 
Wenn das modul aktiv ist in der welt, passiert bei linksklick auf das Bild in einem "plantsheet" nichts. Bin unsicher ob es an euch oder den entwickler von Tokenizer adressiert werden sollte, aber da alle anderen sheets dieses Problem nicht haben, dachte ich ich merke es zumindest einmal an damit man es auch mal gehört habt. 
Als Workaround ist das deaktivieren von Tokenizer vollkommen ausreichend um die Bilder setzen/ändern zu können.

**Comment by Plushtoast** [comment]
Also beim itemsheet geht das einwandfrei bei mir.
Beim actor plant sheet ist das bild primär abhängig von der ersten pflanze die hinzugefügt wurde und schaltet da auch abhängig ob es identifiziert wurde oder nicht um.
Von welchem sheet redest du?

**Comment by Chrosarius** [comment]
Ah entschuldige, muss mir angewöhnen mehr bilder zu machen, Hab einmal einen screenshot gemacht von dem Sheet den ich meine. 
![grafik](https://user-images.githubusercontent.com/110413260/186074099-ad5ab76a-30e1-4ff0-afc6-680724952ed9.png)

**Comment by Plushtoast** [comment]
Kann das nicht reproduzieren. Kannst du in v10 sobald du umgestiegen bist nochmal prüfen, ob das Problem noch existiert

**Comment by Chrosarius** [comment]
Ja, grade getestet, ist ein V9 spezifisches Problem. In V10 taucht es nicht mehr auf. Problem gelöst :)
