### ISSUE TITLE
Verschiedene und immer zufällige Ausrüstungspakete lassen sich nicht auf den Charakterbogen ziehen

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsa5-foundryVTT#1147]
**Describe the bug**
Die Ausrüstungspakete lassen sich nicht immer auf den Charakterbogen ziehen. Es unterscheidet sich von Character Sheet zu Character Sheet, welche Pakete nicht per Drag&Drop zugewiesen werden kann.

Im ersten Test war es nur das Reisepaket. Im zweiten Test funktionierten Räuber-. Magier- und Reisepaket nicht. Im dritten Test funktionierten Diebes-, Gardisten- und Magierpaket nicht. In der Konsole erscheint die beigefügte Fehlermeldung (siehe Screenshot).

**To Reproduce**
1. Gib im Chat /packages ein.
2. Ziehe ein Paket auf den Charakterbogen
3. Mit Glück erscheinen die Gegenstände im Ausrüstungstab oder es geschieht nichts.

**Versions:**
- Foundry Version: 9.269
- DSA/TDE version: 3.5.2
- Related modules version: 
TDE Core Rules 3.5.1
TDE Master´s Workshop 3.5.1
![Fehlermeldung](https://user-images.githubusercontent.com/78543670/186005836-a697c824-0844-4570-a273-3e35731fd0c2.PNG)

**Comment by Plushtoast** [comment]
Müsste an fehlenden Gegenständen liegen. Für v10 schon gefixt.
