### ISSUE TITLE
Alchimie im Charsheet geschrieben anstelle von Alchemie

### ISSUE THREAD

**Issue by Chrosarius** [Plushtoast/dsa5-foundryVTT#1148]
Version: 3.5.3 
![grafik](https://user-images.githubusercontent.com/110413260/186255984-183d78aa-a989-479c-8a3a-f10a9377f1b3.png)

**Comment by Plushtoast** [comment]
Beide Schreibweisen sind nahc deutscher Rechtschreibung korrekt. Und auch wenn Alchimie komisch aussieht, ist das die Schreibweise die DSA verwendet.

**Comment by Chrosarius** [comment]
ahhh okay, vielen dank. Kannte diese schreibweise tatsächlich noch gar nicht
