### ISSUE TITLE
Information about NSC´s for Player

### ISSUE THREAD

**Issue by Invisible303** [Plushtoast/dsa5-foundryVTT#115]
Bei dem einblenden von NSC´s sehen die Spieler jeglichen Information (Darüber gibts bereits ein Bugticket).

Wäres es ggf., sobald diese Bug behoben wurde, die Möglichkeit das die Spieler nur die Beschreibung (Aussehen, Alter etc.) sehen und dann für den NSC´s eigene Notizen anlegen können. Das die Spieler jegliche Information "Ausrüstung etc." sehen ist halt sehr ungünstig und sorgt unbewusst für Metagaming (z.B. aha der hat Boni in Ausweichen nutze ich eher Finte als Wuchtschlag).

Vielen Dank.

**Comment by Invisible303** [comment]
Guten Tag Zusammen,

wie in Discord besprochen genauer beschrieben :)

Im Bereich "Actor Directory" kann ein "Nichtspielercharakter" angelegt werden und über das Kontextmenü (Rechtsklick mit der Maus) mittels "Configure Permission" eine Berechtigung erhalten.

Es gibt dabei 3 Berechtigungsgruppen

![image](https://user-images.githubusercontent.com/79397897/108630819-1522fc80-7467-11eb-8107-c8e35261d314.png)

Ist es möglich, dass die Berechtigungsgruppe Limited ausschließlich den Reiter/Register Notizen des Charaktersheeds einsehen kann? Bisher kann jede Berechtigungsgruppe alle Information einsehen.

![image](https://user-images.githubusercontent.com/79397897/108630856-4f8c9980-7467-11eb-824f-8c4b95404acc.png)

Zusatz und Träume:
Ein Traum eines Spielleiters (Damit meine ich gerade ausschließlich mich) wäre unter dem Register Notizen ein Teilbereich den ausschließlich der Spielleiter/GM sieht oder einen separaten/es Reiter/Register Notizen für den GM.

**Comment by Nyhles** [comment]
Schau dir mal das Modul GM Notes an, kann aber sein, dass das nicht Kompatibel ist

**Comment by Invisible303** [comment]
> Schau dir mal das Modul GM Notes an, kann aber sein, dass das nicht Kompatibel ist

Hallo Nyhles,

vielen Dank für deinen Hinweis. Habe das Modul installiert und es scheint zu funktionieren. Frag ist halt immer, wie lange es kompatibel ist. Wir lassen es erstmal drauf und hoffen das es, bis es ggf. eine andere Lösung gibt, funktioniert :)

**Comment by mckee14** [comment]
Schliesse mich an. Die Rechte "limited" und "observer sind, soweit ich das beurteilen kann, identisch. 

limited sollte generell nur sehr wenig zeigen.
