### ISSUE TITLE
[Das Geheimnis des Drachenritters] Charaktersicht (Fog of War) verbugged

### ISSUE THREAD

**Issue by Decaprius** [Plushtoast/dsa5-foundryVTT#1164]
**Describe the bug**
In der Szene "Höhle im Dunkeltann" des Drachenrittermoduls ist die Charaktersicht der Tokens verbugged. Bei standardmäßig 360 Grad haben die Charaktere keine Sicht, und können keine Fog of War entdecken.

Kann man fixen, wenn man die Sicht auf 180 stellt - allerdings sehen die Charaktere dann sehr weit, bis sie die nächste Mauer treffen, können somit also über die gesamte Map schauen. Auch haben die Tokens nur die Sicht in gewissen Stellungen - in den meisten Stellungen sehen sie garnichts.

![image](https://user-images.githubusercontent.com/112828760/188333423-366141d1-57f8-41ec-bdab-17167a642bff.png)
**Versions:**
- Foundry Version: 10, Build 284
- DSA/TDE version: 4.0.3
- Related modules version 
![image](https://user-images.githubusercontent.com/112828760/188333352-21e8aef9-c418-4308-b97b-9e8602d93974.png)

**Comment by Plushtoast** [comment]
Drachenritter ist nicht für v10 bereit und das bleibt es auch noch ein bis zwei Wochen. Sollte aber auch dran stehen

**Comment by Plushtoast** [comment]
ist scheinbar auch ein v10 bug. also nicht dsa spezifisch

**Comment by Decaprius** [comment]
Danke für die schnelle Rückmeldung, wirklich toll!
Mit meiner Gruppe werde ich dann vorerst wohl auf Version 9 spielen :)

Liebe Grüße aus Österreich

**Comment by Plushtoast** [comment]
Alle umlaufenden Wände die das Spielfeld begrenzen zu entfernen, bzw die die Ränder überlappen, löst das Problem als workaround.
Allerdings arbeitet Foundry auch an einem Fix.

**Comment by Plushtoast** [comment]
https://github.com/foundryvtt/foundryvtt/issues/8097

**Comment by Xardai** [comment]
Ich hab einen Bug der sich evt mit dem deckt, ist allerdings nicht Drachenritterspezifisch:
Wenn ich einen Actor auf ein Canvas ziehe ist die Sichtreichweite immer leer und muss händisch nachgetragen werden
V10.284
DSA 4.0.6
Es sind nur DSA Module aktiv

**Comment by Plushtoast** [comment]
> Ich hab einen Bug der sich evt mit dem deckt, ist allerdings nicht Drachenritterspezifisch: Wenn ich einen Actor auf ein Canvas ziehe ist die Sichtreichweite immer leer und muss händisch nachgetragen werden V10.284 DSA 4.0.6 Es sind nur DSA Module aktiv

Das sollte kein bug sein, du musst entweder die Sichtautomatisierung von DSA verwenden den Token Prototyp editieren oder in den game settings den default token konfigurieren.

**Comment by Xardai** [comment]
Danke für den Hinweis

**Comment by Plushtoast** [comment]
Das letzte Foundry update hat diesen bug behoben
