### ISSUE TITLE
Größenkategorie von ausgewähltem Ziel automatisch berücksichtigen

### ISSUE THREAD

**Issue by olipool** [Plushtoast/dsa5-foundryVTT#1165]
Es ist sehr praktisch, dass Foundry im Nahkampf automatisch die Waffengröße/Reichweite des Gegners und im Fernkampf die Entfernung und Größenkategorie berücksichtigt, wenn man ein Ziel auswählt.

Wäre es möglich, so etwas Automatisches auch für die Größenkategorie "winzig" im Nahkampf zu ergänzen, damit die AT-Erschwernis von -4 automatisch berücksichtigt wird?

(siehe https://ulisses-regelwiki.de/Spezielle_Nahkampfregeln.html)

**Comment by Plushtoast** [comment]
ah dachte das ist nur bei fernkampf
