### ISSUE TITLE
[v10] Journals v2 Relative Links funktionieren nicht.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1166]
**Describe the bug**
Wenn ich einen Journal Eintrag habe, der auf seine eigenen Seiten verweist, werden die relativen Links nicht aufgelöst. In anderen Systemen (Simple World Building und DnD) konnte ich den Fehler aber nicht reproduzieren.

**To Reproduce**
1. Erstelle einen Journal Eintrag mit mehreren Seiten.
2. Ziehe Links auf die Seite in einen Eintrag
3. Speichern

**Screenshots**
<img width="736" alt="chrome_dgqaYTw1lH" src="https://user-images.githubusercontent.com/80099175/188453528-4b69d457-a336-496d-9a97-9d2e15d39932.png">

**Versions:**
- Foundry Version 10.284
- DSA/TDE version 4.0.4

**Comment by vt-tom** [comment]
Additional information from the Foundry Discord
`There were some changes we made quite late on I think. It may be necessary to supply the `relativeLinks: true` option if the sheet is not extending `JournalTextPageSheet` or is otherwise overriding `activateEditor`.`

**Comment by Plushtoast** [comment]
late :)

**Comment by vt-tom** [comment]
You know, I am not the fastest person 😁
