### ISSUE TITLE
Kultur Mohas fehlt

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#117]

**Comment by Plushtoast** [comment]
Mohas sind meines Wissens nicht Teil des deutschen GRW. Die sind im englischen.

**Comment by Nyhles** [comment]
Das ist so nicht Korrekt, deutsches GRW 3. Auflage S.107+108 Kultur Mohas ist vorhanden. Steht sogar so im Regelwiki

**Comment by Plushtoast** [comment]
In der vierten Auflage scheinen sie durch Waldmenschen und Utulus ersetzt worden zu sein.

**Comment by Nyhles** [comment]
Oh wow, wusste ich nicht.
