### ISSUE TITLE
[v10/4.0.6] NSC Sheets aktualsieren Prototype Tokens nicht, Reset von Einstellung

### ISSUE THREAD

**Issue by gendokun** [Plushtoast/dsa5-foundryVTT#1171]
Wenn ich einen NSC aus dem Bestarium (Hier am Beispiel Bürger) , in meine Actors ziehe, und Umbenne, wird der Token nicht umbenannt. Zusätzlich war sonst die Namensanzeige und LeP/AsP Anzeige eingeblendet by default,  zumindest bei Mouseover , eingeblendet. Das steht jetzt auf "Niemals".

Zusätzlich , sobald ich speichere und die Szene neu lade, ist die Einstellung der Prototyp Figur wieder zurückgesetzt auf der Config im Screenshot wieder auf dem Ursprungswert für die 
![grafik](https://user-images.githubusercontent.com/37953318/189224257-9033522d-973e-4eae-a13d-231e1203d1c0.png)

![grafik](https://user-images.githubusercontent.com/37953318/189224703-8f27b736-01b7-4014-8cb9-4c06af7113d3.png)

**Comment by Plushtoast** [comment]
Da ist foundry derzeit noch verbugt.

**Comment by gendokun** [comment]
Ist mit Foundry 10.285 gefixed
