### ISSUE TITLE
Default-Settings für Sichtbarkeit von Tokennamen und Energieleisten wird für Actors aus der Bibliothek nicht übernommen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1174]
**Describe the bug**
Fügt man einen Actor aus der Bibliothek in Foundry v10 hinzu, dann werden die default token settings aus Foundry nicht mehr übernommen. In v9 ging das noch.
Erstellt man selbst einen Actor neu, werden sie ordnungsgemäß gesetzt.
Wie das bei anderen default token settings aussieht (wie Sicht), habe ich nicht ausprobiert.

**Expected behavior**
Ich fände es intuitiv, wenn die default token settings wieder für Actors aus der Bibliothek übernommen werden. Das dürfte für die meisten Fälle sinnvoll sein.

**Versions:**
- Foundry Version 10 Build 285
- DSA/TDE version 4.0.7

**Comment by Plushtoast** [comment]
werde alle module nochmal updaten müssen wegen foundry bug deswegen

**Comment by Albinosheep** [comment]
Danke dir fürs Kümmern! :-)
