### ISSUE TITLE
Info-Item -> QS erhöhen SchiP -> keine Wirkung

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#1183]
**Describe the bug**
Wenn ein Spieler auf ein Infoitem im Chat gewürfelt hat und danach seine QS per Rechtsklick -> "QS erhöhen" erhöht, wird zwar ein SchiP abgezogen, aber die QS nicht angepasst. Da das außerhalb der Infoitems funktioniert, ist dies unerwartetes Verhalten.

**To Reproduce**
1. SL: Poste Infoitem in den Chat.
2. Spieler: Klicke auf roten Würfelbutton in der Infoitemchatmessage.
3. Würfel.
4. Rechtsklick auf das Ergebnis
5. Klicke auf "QS um eins erhöhen (1 SchiP)"

**Expected behavior**
Das Ergebnis des Würfelwurfs wird um 1 QS erhöht, wie es auch bei anderen Würfen der Fall ist. Die nachfolgende Nachricht mit dem erwürfelten Inhalt des Infoitems wird um 1 QS erweitert, oder es wird eine neue Nachricht mit dem jetzt neuen QS-Ergebnis gesendet.

**Versions:**
- Foundry Version 10.285
- DSA/TDE version 4.1.0

**Comment by Danii0206** [comment]
Nebenbei bemerkt: Die Infoitems sind ein cooles Feature, danke dafür! :)

**Comment by Plushtoast** [comment]
also bei mir geht das
![grafik](https://user-images.githubusercontent.com/44941845/191185432-5a757f02-36f3-41d4-ba4a-17056950f316.png)
unter welchen umständen läuft das bei dir nicht?

**Comment by Danii0206** [comment]
Unter allen, die ich getestet habe. Als GM, als Spieler, alle Module aus, Items aus Kreaturbeschreibungen, selbst erstellte Items.

Gerade gesehen: Fehlerlog in der Console
```
VM2581:1 Uncaught (in promise) ReferenceError: RequestRoll is not defined
[Detected 1 package: system:dsa5]
    at eval (eval at _callee25$ (dsa5.bundle.js:2), <anonymous>:1:1)
    at Function._callee25$ (dsa5.bundle.js:2)
    at tryCatch (dsa5.bundle.js:2)
    at Generator._invoke (dsa5.bundle.js:2)
    at Generator.next (dsa5.bundle.js:2)
    at asyncGeneratorStep (dsa5.bundle.js:2)
    at _next (dsa5.bundle.js:2)
eval @ VM2581:1
_callee25$ @ dsa5.bundle.js:2
tryCatch @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
Promise.then (async)
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
basicTest @ dsa5.bundle.js:2
_callee13$ @ dsa5.bundle.js:2
tryCatch @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
fateaddQS @ dsa5.bundle.js:2
_callee17$ @ dsa5.bundle.js:2
tryCatch @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
asyncGeneratorStep @ dsa5.bundle.js:2
_next @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
(anonymous) @ dsa5.bundle.js:2
useFateOnRoll @ dsa5.bundle.js:2
useFate @ dsa5.bundle.js:2
callback @ dsa5.bundle.js:2
#onClickItem @ foundry.js:55518
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```
