### ISSUE TITLE
Tokenhotbar zeigt Zauber / Liturgien auch außerhalb des Kampfes

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#1184]
Momentan zeigt die Hotbar die Zauber/Liturgien nur im Kampf an.
Da viele auch außerhalb des Kampfes gewirkt werden können wäre es schön wenn die auch außerhalb verfügbar sind.

Ist es Sinnvoll um ein weiteres Symbol für Rituale / Zeremonien zu erweitern, damit alles über die Hotbar verfügbar ist?

**Comment by Plushtoast** [comment]
rituale und zeremonien sehe ich nicht. benutzt man ja seltenst
