### ISSUE TITLE
[DSA 4.1.2] Probe bearbeiten produziert einen Fehler

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1187]
**Describe the bug**
Wenn eine Probe als GM im Nachhinein bearbeitet wird, kann dies nicht bestätigt werden und es erscheint ein Fehler in der Console.

**To Reproduce**
1. Würfle eine Probe
2. Bearbeite diese Probe als GM

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/191589531-1d22fdf4-09cc-49aa-9851-d6b6d6f32c15.png)
![grafik](https://user-images.githubusercontent.com/80099175/191589555-0ffeb6da-8346-43df-87ff-9690529c52ad.png)

**Versions:**
- Foundry Version 10.286
- DSA/TDE version 4.1.2

**Comment by Plushtoast** [comment]
Ist übrigens ein foundry bug. Kommt wahrscheinlich wieder
