### ISSUE TITLE
Hide Item Information not working if everything is hidden

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1190]
In items, you can hide tabs from players:
![image](https://user-images.githubusercontent.com/62849695/191937650-50db0a03-214f-46f1-8d15-9d3eaf29fca9.png)

When you select all tabs to be hidden, it still shows one tab to the player (It will show the latest tab you hid). 
> Foundry hides the tab itself, but not the page / information underneath it

Would be nice if it's posible to hide all the tabs. If not possible, the selcted hide-icons should represent the true state, ie: the last remaining un-selected mask symbol can't be selected.

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/191948638-f66b31ce-c8c4-4f14-9aa7-6015e3035590.png)

So sollte es aussehen wenn alles verborgen ist, sicher dass es so nicht aussieht?

**Comment by Plushtoast** [comment]
Falls es anders aussieht, bitte mehr details

**Comment by mckee14** [comment]
Alle Module aktuell
Foundry 10.286
Spieler nutzt Chrome, GM nutzt Firefox

Spielersicht, wenn nichts ausgeblendet ist:
![image](https://user-images.githubusercontent.com/62849695/191950073-822d1362-f239-4df0-a1b3-d61cbf114943.png)

Spielersicht, wenn "Beschreibung" ausgeblendet wird:
![image](https://user-images.githubusercontent.com/62849695/191950239-fed961cd-3aa1-4d94-8470-05087d6a8a56.png)

Spielersicht, wenn danach auch noch "Details" ausgeblendet wird:
![image](https://user-images.githubusercontent.com/62849695/191950336-9ab1d842-35fc-4d51-88b8-8f4d9c5fcf7e.png)

Spielersicht, wenn danach "Beschreibung" wieder zugänglich gemacht wird:
![image](https://user-images.githubusercontent.com/62849695/191950518-b2f0ef01-158a-40ce-aa56-e59f3f67b6cb.png)

Fehlermeldung Konsole als Spieler:
```
foundry.js:747 Error: An error occurred while rendering PlantSheet 260. ENOENT: no such file or directory, open '/data/Data/systems/dsa5/templates/items/obfuscateditem.html'
    at i.<anonymous> (foundry.js:6841:41)
    at i.value (socket.js:309:17)
    at i.value (socket.js:239:22)
    at x.emit (index.mjs:136:20)
    at s.value (manager.js:200:14)
    at x.emit (index.mjs:136:20)
    at a.value (index.js:119:51)
    at s.value (manager.js:192:22)
    at x.emit (index.mjs:136:20)
    at a.value (socket.js:323:26)
onError @ foundry.js:747
(anonymous) @ foundry.js:5028
Promise.catch (async)
render @ foundry.js:5026
render @ foundry.js:6352
render @ foundry.js:13220
_onUpdate @ foundry.js:13322
callback @ foundry.js:12711
(anonymous) @ foundry.js:12660
_handleUpdateDocuments @ foundry.js:12660
(anonymous) @ foundry.js:12310
x.emit @ index.mjs:136
value @ socket.js:278
value @ socket.js:265
value @ socket.js:235
x.emit @ index.mjs:136
value @ manager.js:200
x.emit @ index.mjs:136
value @ index.js:119
value @ manager.js:192
x.emit @ index.mjs:136
value @ socket.js:323
x.emit @ index.mjs:136
value @ transport.js:104
value @ transport.js:97
ws.onmessage @ websocket.js:79
```

**Comment by Plushtoast** [comment]
ah windows

**Comment by mckee14** [comment]
Client läuft auf Windows

Foundry läuft in einem [docker ](https://hub.docker.com/r/felddy/foundryvtt)auf einem Linux NAS
