### ISSUE TITLE
Plant search: result in chat

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1191]
When you succeeded in a plant search, you get the result posted into the chat. You can see the plant itself, which can be clicked to open the corresponding compendium entry.

The complete plant information is available to all the players immediately

Maybe there is a better way to present this to the players

Ideas:
- only post name and picture to the chat, unlinked to compendium entry
- import the plant as item first, hide all additional info, then post
- only post to GM and/or the player who did the plant search

These are only ideas, maybe you find better ways to implement something without causing much work.

All in all, THANK YOU for the feature, it's sensational! I should have gone the plant-ranger way instead of the hunter-ranger way :)

**Comment by Plushtoast** [comment]
also eigentlich sollte es so sein, dass der gm den link erhält und die spieler nicht

**Comment by mckee14** [comment]
Der Popuptext für den SL sagt 
![image](https://user-images.githubusercontent.com/62849695/191953083-ddfea4c5-c9ce-44a7-83f5-40cab1c1bc8d.png)

Der Spieler sieht danach auch alle infos
![image](https://user-images.githubusercontent.com/62849695/191953170-017b3230-b4dd-49ac-856c-dc4d33f1ce71.png)
