### ISSUE TITLE
Proben können nicht mehr in die Tokenhotbar gezogen werden.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1198]
**Describe the bug**
Aktuell kann ich keine Proben mehr in die Tokenhotbar ziehen, denn bei Klick öffnet sich direkt das Proben Fenster. 

Ausnahmen sind die Attacken und Paraden vom Kampfbogen.

Im Firefox öffnet sich zwar das Probenfenster aber da kann ich dann tatsächlich per Drag and Drop die Probe in die Marko Leiste ziehen.

**To Reproduce**
1. nimm Google Chrome
2. öffne Charbogen
3. versuche Probe von Charbogen auf Makro Leiste zu ziehen

**Versions:**
- Foundry Version 10.286
- DSA/TDE version 4.1.6
- Google Chrome 106.0.5249.62

**Comment by Plushtoast** [comment]
https://user-images.githubusercontent.com/44941845/193292513-95df7943-b498-4add-acc2-63551616475e.mp4

**Comment by vt-tom** [comment]
Oh man, so langsam komme ich mir echt doof vor... Irgendwie meine ich darüber schonmal mit dir gesprochen zu haben nach dem V10 Update und da ging das mit dem Talent draufziehen über den Namen tatsächlich nicht mehr...
Habe komplett verdrängt dass es darüber geht....
