### ISSUE TITLE
Meister Menü - LeP, KaP und AsP werden nicht angezeigt. 

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1202]
**Describe the bug**
Im Meister Menü werden AsP, KaP und LeP nicht mehr angezeigt. 

**Versions:**
- Foundry Version 10.286
- DSA/TDE version 4.1.6

**Comment by TarionT** [comment]
das selbe gilt für die erhaltenen und Gesamten Abenteuerpunkten im Meister Menü
