### ISSUE TITLE
Armor zone encumbrance not applied on initial load

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#1206]
Thank you for the speedy fix for https://github.com/Plushtoast/dsa5-foundryVTT/issues/1201 and https://github.com/Plushtoast/dsa5-foundryVTT/issues/1200

Amazing!

Now with that working, I noticed that the values are only applied when the character is modified in any way.

Equipping anything, changing armor values, changing health etc.

But if you only load a Character that should have 1BE -1GS -1INI only the 1BE is applied.
Since all other modifiers like LeP etc. are correctly applied I suspect this is a bug?
And this time it is not only a display error with the modifiers page. The values are actually not applied.

Just to be clear this was already a problem before these fixes, I just wanted to see if they are related before opening another issue

**Comment by Plushtoast** [comment]
Odd, I thought I fixed that, not entirely sure what's the problem here, but I guess I know how to fix this.

**Comment by Plushtoast** [comment]
Complicated fix, but I  think it's ok now
