### ISSUE TITLE
Verberge Token Namen - auch bei SCs

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1210]
**Describe the bug**
Aktuell greift die Einstellung "verberge Token Namen" auch bei SCs

**To Reproduce**
1. Stelle in den Einstellungen irgendeine Option bei "verberge Token Namen" ein
2. Ziehe SC auf die Szene.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/194526569-4d66e6fe-bf29-4061-b4c8-aaefc6bba541.png)

**Versions:**
- Foundry Version 10.687
- DSA/TDE version 4.1.9

**Comment by gendokun** [comment]
Ja, ist mir heute auch aufgefallen - würde das eher als Bug klassifizieren, da in der Einstellung steht:
"Generische Ersetzung des Namens unbekannter Kreaturen oder NSC"

Gleiches Problem bei Foundry 10.287
