### ISSUE TITLE
Anzeigefehler bei Zauber- und Liturgieerweiterungen

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1216]
Foundryversion: 10.286
DSA-Version: 4.1.9
keine Module aktiv

Es gibt einen Fehler in der Anzeige von vorhandenen Erweiterungen in den Zauber- und Liturgie-Sheets.

![unknown](https://user-images.githubusercontent.com/85822812/195420425-4d646cc3-5791-48f0-8b76-f40f3d772e81.png)

**Comment by Plushtoast** [comment]
Was ist der Fehler?

**Comment by sirgawain111** [comment]
Die Texte der Erweiterungen werden nicht angezeigt. So sah das in v9 noch aus:

![grafik](https://user-images.githubusercontent.com/85822812/195451696-be3d40f7-aad1-4146-a35d-a22553a043ba.png)

**Comment by Plushtoast** [comment]
Ah, kann mich schon gar nicht mehr dran erinnern :)
