### ISSUE TITLE
Fernkampfangriff Vorauswahl Ziel "bewegt sich leicht" statt "steht still" & Reihenfolge Zielmodifikator

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#122]
**Is your feature request related to a problem? Please describe.**
In einem Kampf kommt es häufiger vor, dass ein Fernkampfangriff auf ein sich leicht bewegendes Ziel ausgeführt wird. Da die Voreinstellung aber immer Ziel steht still (+2) ist, muss dies bei jedem Angriff korrigiert werden.
Wenn die Voreinstellung auf bewegt sich leicht (+-0) ist, besteht zudem der Vorteil, dass ein Angriff grundlegend ersteinmal unmodifiziert ist.

Zudem wäre es schön, wenn die Modifikatoren für Ziel in der gleichen Art dargestellt werden wie die anderen (also positive Modifikatoren oben in der Liste und negative Modifikatoren unten)
Veranschaulichung ist:
![FernkampfAngriffsprobe](https://user-images.githubusercontent.com/79369393/108687593-303d4d00-74f7-11eb-9ba9-d1f5aad86d01.png)
soll:
![FernkampfAngriffsprobe2](https://user-images.githubusercontent.com/79369393/108687911-92964d80-74f7-11eb-8187-60d7cb576574.png)

**Comment by Plushtoast** [comment]
Das hängt mit einem anderen Fehler zusammen, der für den Patch bereits behoben wurde.
