### ISSUE TITLE
Statuseffekte lassen sich nicht auf Akteure ziehen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1232]
**Describe the bug**
Status Effekte können nicht mehr aus dem Chat auf Akteure gezogen werden. Wird der Effekt per Drag and Drop auf dem Actor-Sheet
abgelegt, passiert nichts.
Kein Fehler in der Console.

**To Reproduce**
1. /conditions in den Chat eingeben
2. Actor-Sheet öffnen
3. Effekt auf Actor ziehen

**Versions:**
- Foundry Version 10.288
- DSA/TDE version 4.1.10

**Comment by Schorschus** [comment]
Ebenfalls bei Anwendungsgebiete der Fall.

**To Reproduce**
Steps to reproduce the behavior:

1. /apps in den Chat eingeben
2. Actor-Sheet öffnen
3. Effekt auf Actor ziehen


Versions:

Foundry Version 10.288
DSA/TDE version 4.1.10
