### ISSUE TITLE
[Bug/Content] SF Durchgezogener Tritt gibt Betäubung + wirkt auf Angreifer

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#1234]
**Describe the bug**
Die Kampf-SF Durchgezogener Tritt gibt Betäubung statt Liegend beim Gegner. Dafür erhält der Angreifer den Status Liegend. Der Verteidigungsmalus beim Angreifer wird aber korrekt gegeben.

**Expected behavior**
Der Gegner sollte nach misslungener Körperbeherrschungsprobe Liegend bekommen, nicht der Angreifer. Der Angreifer sollte nur den Verteidigungsmalus bekommen.

**Versions:**
- Foundry Version: v10
- DSA/TDE version: 4.1.10
- Kompendium 2: 4.1.0

**Additional context**
Soweit ich das durch Tests feststellen konnte, liegt das Problem beim Macro, das als Statuseffekt "Durchgezogener Tritt" bei der SF ausgeführt wird, wo dem sourceActor der status prone zugewiesen wird. Wenn ich diese Zeile rauslösche funktioniert es richtig:
"await sourceActor.addCondition("prone");"

Bei dem zweiten ausgeführten Statuseffekt "Durchgezogener Tritt (Betäubung)" muss nur der Effekt in Liegend geändert werden (und damit es besser im Chat aussieht auch die Bezeichnung in (Liegend).

Dann funktioniert es wie es soll.

Mal wieder ein ganz herzliches Dankeschön für all Eure Bemühungen, die das Spiel so sehr vereinfachen und die Immersion fördern!

**Comment by Plushtoast** [comment]
Danke und Gruß an aemberwyn
