### ISSUE TITLE
States not properly displayed

### ISSUE THREAD

**Issue by br00n0** [Plushtoast/dsa5-foundryVTT#1240]
**Describe the bug**
Adding State [Condition Name] in a journal displays the wrong icon beside the state.
Clicking on the state shows the wrong description.
Wrong description is displayed twice in the chat.

**To Reproduce**
1- In a journal page, type 'State Blind' and save
2- Display the journal page, a Blind state box will appear with the Deaf state icon
3- Click the state box, the Deaf description will be displayed TWICE

**Expected behavior**
The state box should properly display the Blind state with its proper icon.
Clicking the Blind state box should display the Blind state description in the chat.
A state description should be displayed once in the chat, not two times.

**Screenshots**
![image](https://user-images.githubusercontent.com/79856383/198129687-90c66c7e-7c4c-46c0-bb17-9fb18085f549.png)

**Versions:**
- Foundry Version : 10.288
- DSA/TDE version : 4.1.10

**Additional context**
- Clicking on a state from the /condition command displays the correct state description and only once.
- It also seems dragging and dropping states on an Actor does nothing. I think it used to apply the state to the Actor.

**Comment by Plushtoast** [comment]
I can not recreate the posting of wrong status but I fixed the double post.

**Comment by br00n0** [comment]
@Plushtoast 
After researching, the posting of the wrong status is caused by another module, Monk's Little Details. Setting status sorting order anything but None causes the problem. Probably due to an index value being used instead of a string value lookup.
![image](https://user-images.githubusercontent.com/79856383/199570277-a8c07d81-6314-417e-9569-3b28c3ab85d2.png)

Thank you!
