### ISSUE TITLE
[Content] Drachenritterbox - Die Räuber vom Dunkeltann (spoiler) fehlende Angaben auf der Karte für Meister

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#1247]
**Describe the bug**
Auf der Battlemap/Szene der Höhlenkarte sind die Hütten der Räuber nicht mit Notizpins oder anderen Markierungen versehen, die ihnen Nummern zuweisen. Im Text des zentralen Notizpins/Journaleintrags werden die Häuser nach Nummern beschrieben. Der Meister weiß aber nicht, zu welchem Haus welche Nummer gehört. Im gedruckten AB wurden den Häusern auf der Meisterkarte Nummern zugewiesen (die nicht zu den Beschreibungen der Häuser und ihrem Erscheinungsbild in der Karte passen, aber das ist ein Problem der DSA-Redaktion ;-) ).

**To Reproduce**
s.o.

**Expected behavior**
Da es sich gerade um ein Einsteigerabenteuer handelt und auch für erstmalige Meister zu leiten sein sollte, halte ich das schon für wichtig, dass es eine für den Meister erkennbare Nummerierung der Hütten gibt (zB durch Notizpins, wo man auch gleich die Beschreibung des Hauses hätte hinterlegen können).

**Versions:**
- Foundry Version: v10
- DSA/TDE version: 4.1.10
- Related modules version: Drachenrittereinsteigerbox

**Additional context**
Wie stets: Vielen Dank für Euren Einsatz!

**Comment by Plushtoast** [comment]
Das Drachenritter Modul unterscheidet sich in noch mehr Punkten vom Orginal tatsächlich.
z.b. haben wir darauf verzichtet einen reduzierten Regelersatz zu erstellen (schlichtweg unrealistisch).
