### ISSUE TITLE
Geste/Formel weglassen aufteilen in separate Felder

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#125]
**Is your feature request related to a problem? Please describe.**
Beim Modifizieren eines Zaubers / einer Liturgie kann man Geste und Formel beides weglassen.
Aktuell ist es nur möglich eines von beiden wegzulassen, aber nicht beides.

**Describe the solution you'd like**
Aufteilen von Geste/Formel weglassen (-2) bzw. Geste/Gebet weglassen (-2) in eigene Checkboxen.

**Comment by Plushtoast** [comment]
Duplicate to #87
