### ISSUE TITLE
Sammelprobe für NSCs

### ISSUE THREAD

**Issue by yendors-vtt** [Plushtoast/dsa5-foundryVTT#1251]
Aktuell können Sammelproben nur für Spielercharaktere angelegt werden.

Es wäre schön, wenn dies auch für NSCs möglich wäre.

Beispiel: Ein Handwerker soll eine Rüstung für einen Spieler anfertigen. Dadurch könnte der Mesiter im Hintergrund den Herstellungsprozess auswürfeln.

**Comment by Plushtoast** [comment]
Denke dafür reicht die sammelprobe im akteur unter den Talenten

**Comment by yendors-vtt** [comment]
Die finde ich eben bei den NSCs nicht, sondern nur bei SCs.
