### ISSUE TITLE
Curses not being found in library when creating Toad/Raven Witch character 

### ISSUE THREAD

**Issue by Kaiser-V** [Plushtoast/dsa5-foundryVTT#1253]
**Describe the bug**
When creating a Toad/Raven Witch (clean install with core rule book module only), a warning message concering curses pops up.

The toad witch message mentions missing curses for 12 AP
The raven witch message mentions missing curses for 8 AP

The issue is present in English and German instances of DSA5 Foundry

**To Reproduce**
1. open a fresh DSA5 world with core rulebook module
2. create a character
3. drag either toad witch or raven witch from the library onto the new character
4. select "experienced 1100" for ap

**Expected behavior**
Character setup works without warning message. I assume that the curses are not marked correctly or missing from the library.

**Screenshots**
![image](https://user-images.githubusercontent.com/115872770/199675230-fdab08e3-c297-4acb-9a78-9acf2f808ab5.png)

**Versions:**
- Foundry Version 10.288
- DSA/TDE version 4.1.13
- Related modules version "The dark eye - core rules" 4.1.3.

**Additional context**

**Comment by Plushtoast** [comment]
This is not a bug. It tells you that you should pick them yourself

**Comment by Kaiser-V** [comment]
Thank you for the quick reply, it would probably be more intuitive if there would have been another tab "curses" to select them during the pop up integration of the witch itself (like there is for magic, dis/advantages, general and description)

A search in the library -> character section of "curse" yields no result, are the marked as normal spells and you have to identify the curse by its name?
(Neither can "Fluch" or "Flüche" be found)

**Comment by Plushtoast** [comment]
Luckily I've got better things to do than building a DSA character generator for the rest of my live.
There is a clear no, for a advanced character generator. Also try /help in the chat.

To find curses enable the advanced searhc function:
![grafik](https://user-images.githubusercontent.com/44941845/199681602-9161ef9a-9bbd-4b10-a497-d78c0d0233ba.png)

select spells and use "Hexe" in Verbreitung

**Comment by Kaiser-V** [comment]
thanks for the feedback and the pointing towards the character creation support tool.
