### ISSUE TITLE
Kleine Änderung an dem GM-Feld in z. B. Items

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1254]
Zwei Vorschläge für das neue Layout des SL-Notizen-Bereichs bei (u. a. ?) Items:

1. Könnte man die Schrift schon beim Editieren weiß erscheinen lassen? Im Moment ist das Schwarz auf braunem Hintergrund sehr schwer zu lesen.
2. Könnte man das Einblenden der Info "Nur für den Spielleiter sichtbar" beim Hovern im Bearbeiten-Modus weglassen? Diese Info ist oft beim Tippen im Weg und wurde einem ja eigentlich schon vorher (spätestens beim Klick auf den Edit-Button) angezeigt.

![image](https://user-images.githubusercontent.com/85822812/199798450-ab4d4070-690b-408b-bd4f-0732a7698885.png)

**Comment by shadows-eye** [comment]
Zusätzliches kann das Feld darüber etwas größer sein?
