### ISSUE TITLE
Schips - Benutzername im Chatfenster

### ISSUE THREAD

**Issue by tomtec29** [Plushtoast/dsa5-foundryVTT#1258]
Wenn ein Spieler einen Schips einsetzt steht dann im Chatfenster nicht mehr der Heldenname sonder der Benutzername.

DSA 4.1.14
Foundry v10.288
nur DSA Module aktiv

**Comment by Plushtoast** [comment]
Is das wirklich ein Ticket wert?
Der Name steht da drin

**Comment by Plushtoast** [comment]
und man kann sehen ob der gm oder spieler den reroll ausgelöst hat

**Comment by tomtec29** [comment]
Naja  der Immersions wegen wäre es halt schön wenn es einheitlich wäre...
