### ISSUE TITLE
Eigene Profession wird nicht gespeichert

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#126]
Erst nach den X-ten Versuch wurde die eigene Profession gespeichert. Allerdings wurden jedes alle Werte eingefügt. Dadurch ist die AP-Berechnung jetzt vollständig durch einander. Gibt es irgendwo einen Trick die korrekt nach zu berechnen?

**Comment by UrielMhezzek** [comment]
Es wäre wünschenswert, wenn man Professionen ohne Werteveränderung hinterlegen kann. Helden in meiner Runde können ihre Profession im laufe des Spiels ändern, wenn sie Vorrausetzungen erreicht haben.

**Comment by Plushtoast** [comment]
Was genau soll das bewirken? Du kannst den Namen der Profession einfach im Inputfeld auf dem Charakterblatt ändern. Wenn keine Veränderungen damit verbunden sind, muss man auch keine Profession dafür anlegen.

**Comment by UrielMhezzek** [comment]
Vollständiger Bogen. Das mit der reinen Texteingabe habe ich nicht gewusst. Ich bin davon ausgegangen, das man einfügen muss.

**Comment by Plushtoast** [comment]
Es wird bald noch ein paar Tutorial Videos geben.
