### ISSUE TITLE
Einhändiger Kampf als Basismanöver

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#1267]
**Describe the bug**
Im Kampf kann die passive Fähigkeit Einhändiger Kampf nicht zusätzlich zu Finte oder Wuchtschlag ausgewählt werden.
Evt. als bedingter Modifikator besser zu nutzen.

**To Reproduce**
Starte einen Angriff
Wähle eine Manöver
Es ist nur eines auswählbar

**Expected behavior**
Einhändiger Kampf kann zusätzlich ausgewählt werden

Außerdem scheint der +1 TP Bonus nicht eingerechnet zu werden im Tooltip steht at:+1 tp:0 vm:0,
im Item ist im Effekt +1 AT,+1 PA, +1TP eingetragen, mit leerzeichen klappt es wieder

**Versions:**
- Foundry Version 10.288
- DSA/TDE version 4.1.16

**Additional context**

**Comment by Plushtoast** [comment]
Der Effekt wurde schon vor langer Zeit überarbeitet und hat "+1 TP". Ggf ab und an die Charaktermigration bemühen.

In den Optionen gibt es eine Einstellung um mehrere Basismanöver etc zu erlauben. 
Ich denke nicht dass diese speziele Sonderregel in absehbarer Zeit oder je umgesetzt wird.

**Comment by Plushtoast** [comment]
Außerdem kann sie zusätzlich eh schon ausgewählt werden, da sie als Kategorie "Passiv" hat
Scheint alles einwandfrei zu funktionieren
![grafik](https://user-images.githubusercontent.com/44941845/201051269-8298cf6d-2d03-4dd8-b7d1-368a9d5fc275.png)

**Comment by Xardai** [comment]
Ich hab zur Einführung für Einsteiger das Einstiegsabenteuer neu installiert. Das war bei Carolan Calavanti einem vorgefertigten Held, ich hatte gedacht das der auf die neuen Fertigkeiten zurückgreift und hatte es nicht an einem neuen Char probiert.
Durch das Migrieren passt es.
Danke.

**Comment by Plushtoast** [comment]
Die einfuehrungshelden sind nicht für normales spiel geeignet. Dazu sind sie viel zu sehr beschnitten. Wir updaten die auch nicht. Das ist die demo
