### ISSUE TITLE
Bibliothek - Filter Zaubersprüche zeigt auch Zaubererweiterungen an.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1268]
**Describe the bug**
Wird in der Bibliothek der Filter "Zaubersprüche" verwendent, werden auch Zaubererweiterungen angezeigt.

**To Reproduce**
1. Bibliothek öffnen
2. Auf Zaubersprüche Filtern

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/201050910-ab2c4877-ba60-4cc5-8277-a0c2e79b6765.png)

**Versions:**
- Foundry Version 10.288
- DSA/TDE version 4.1.16

**Comment by Plushtoast** [comment]
Duplicate of #797 
Den Detailfilter benutzen
Fix unwahrscheinlich
