### ISSUE TITLE
Erholungsprobe fügt LP und AsP nicht automatisch auf

### ISSUE THREAD

**Issue by Firehold** [Plushtoast/dsa5-foundryVTT#1271]
**Describe the bug**
Die Erholungsprobe (Mond-Button), fügt die LP und AsP nicht automatisch dem Charakter hinzu.

**To Reproduce**
1. Klicke auf den Helden
2. Klicke auf Eigenschaften
3. Klicke rechts, hinter Lebensenergie, auf den Mond-Button
4. Im geöffneten Fenster klicke auf "Wurf"
5. Die LP und AsP werden im Chatfenster angezeigt, aber nicht dem Charakterbogen hinzugefügt.

**Expected behavior**
Die Lebenspunkte und Astralpunkte sollten nach dem Wurf automatisch dem Charakterbogen (bei den Balken) hinzugefügt werden.

**Screenshots**
- https://i.imgur.com/frhhJIA.png
- https://i.imgur.com/TPLG235.png

**Versions:**
- Foundry Virtual Tabletop Version 9
- Build 269
- Das schwarze Auge 3.5.0

**Comment by Plushtoast** [comment]
Da DSA unendlich mögliche Modifikatoren für Proben hat und wahrscheinlich nie alle automatisch funktionieren werden, werden ressourcen in den meisten Fällen nicht automatisch abgezogen.
Möchtest du Astralenergie, Karmapunkte oder Regeneration anwenden, clicke mit der rechten Maustaste auf die entsprechende Chatkarte und wähle die entsprechende Option. Das gleiche gilt für Angriffswürfe bzw dem resultierenden Schaden.
Außerdem empfehlen sich VTTOMs DSA Videos oder das Wiki:
https://vttom.de/
