### ISSUE TITLE
Bibliothek

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#128]
Bitte die Bibliothek Checkboxen bissl Gruppieren. Z.B. Ausrüstung, Charakter-Sonderfertigkeiten und Erstellung. 
Des weiteren wäre es schön, wenn es eine Check-All und Uncheck All Funktion gäbe.

**Comment by Plushtoast** [comment]
Alles deaktivieren und aktivieren wird es erstmal nicht geben, weil das Schwierigkeiten mit der Performance geben könnte. Es müssen wirklich alle Objekte dann geladen werden und bei sehr großen Welten kann das zu Problemen führen. Wir beobachten erstmal wie sich das mit weiteren Büchern verhält und entscheiden dann erneut.

**Comment by mckee14** [comment]
Es gibt auch schöne module, mit denen man direkt ALLES gleichzeitig durchsuchen kann, quasi globale suche nachgerüstet.
Einfach mal nach den top10 foundry modules googlen.

**Comment by Plushtoast** [comment]
Ah das muss ich mir auch mal anschauen.

**Comment by Plushtoast** [comment]
https://gitlab.com/riccisi/foundryvtt-search-anywhere
