### ISSUE TITLE
Eigenschaftsmodifikatoren von Spezies werden nicht verwendet

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#129]
Eigenschaftsmodifikationen durch die Spezies werden nicht angewendet.

**Comment by mckee14** [comment]
Man bekommt nicht automatisch eine höhere Eigenschaft, wenn man die Modifikation für die Spezies wählt. Es erhöht sich nur das regeltechnische Maximum, die man erwerben kann.
Die Steigerung der Eigenschaft muss man aber nach wie vor normal mit AP bezahlen und selber steigern.

**Comment by Plushtoast** [comment]
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/FAQ#why-does-the-attribute-change-of-the-species-not-add-attribute-levels-on-the-character-sheet

Mckee hat Recht.
