### ISSUE TITLE
Improvisationszauberei - Erschwernis reduzieren

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1296]
Die Sonderfertigkeit "Improvisationszauberei" erlaubt es, die Erschwernis für "Formel weglassen" oder "Geste weglassen" zu reduzieren, von -2 auf -1.

Die SF ist in Foundry vorhanden, die Erschwernisse ebenfalls. Es wäre toll, wenn man die Erschwernisse durch die SF beeinflussen könnte.

Aktuell geschieht dies nicht und der Wurf erfolgt gegen die identischen Modifikatoren, egal ob mit oder ohne SF.

**Comment by Plushtoast** [comment]
Ist schon im nächsten Update drin. Bis die sonderfertigkeiten nachgezogen sind dauerts aber noch laengerVon meinem iPhone gesendetAm 13.12.2022 um 11:13 schrieb mckee14 ***@***.***>:﻿
Die Sonderfertigkeit "Improvisationszauberei" erlaubt es, die Erschwernis für "Formel weglassen" oder "Geste weglassen" zu reduzieren, von -2 auf -1.
Die SF ist in Foundry vorhanden, die Erschwernisse ebenfalls. Es wäre toll, wenn man die Erschwernisse durch die SF beeinflussen könnte.
Aktuell geschieht dies nicht und der Wurf erfolgt gegen die identischen Modifikatoren, egal ob mit oder ohne SF.
