### ISSUE TITLE
Reiterkampf

### ISSUE THREAD

**Issue by Salamandris** [Plushtoast/dsa5-foundryVTT#1299]
Guten Morgen,

nachdem wir jetzt eine schöne Runde DSA5 in Foundry zusammen haben und auch brav alle Module implementiert sind erst einmal ein Lob. So bekommt DSA eine ganz neue Ebene die einfach noch mehr Spaß macht auch wenn es das persönliche Treffen nicht ersetzt. Klar gibt es noch die eine oder andere Herausforderung, aber das muss ja auch so sein bei einem lebenden System.

Jetzt zur Herausforderung:

Können wir meine maulenden Hofritter irgendwie befriedigen, die Ihren geliebten Reiterkampf nicht finden oder sind die Kuschelritter einfach zu doof es zu finden? (ich finde auch keine Mechanik)

Kurze Antwort wie: "Ist noch nicht implementiert, steht aber ganz oben auf der TO-Do und kommt noch vor Weihnachten" reicht völlig aus.

Liebe Grüße 

Sala

**Comment by mckee14** [comment]
Basilio Kirschner aus Weidwehrshöften unterstützt diesen Antrag :-)

Salamandris ***@***.***> schrieb am Mi., 21. Dez. 2022, 07:05:

**Comment by Plushtoast** [comment]
Gibt es noch nicht und wird vor Weihnachten auch nichts.
Ganz oben auf der Liste steht was du hier findest:

https://github.com/users/Plushtoast/projects/1

Nach 4.2 hat Glühwein Priorität

**Comment by Salamandris** [comment]
Vielen Dank für die Info. Dann hoffe ich, das es irgendwann auf die Shortlist rutscht.

Dann bleibt mir nur Prost zu sagen.

**Comment by Plushtoast** [comment]
Duplicate of #798

**Comment by Plushtoast** [comment]
Gibts hier irgendeine Erwartungshaltung was das genau können soll?

**Comment by mckee14** [comment]
Ich mach mal Wunschkonzert, und Du sortierst dann selber nach "Utopie" und "Realistisch" :)

- Token Spieler & Token Pferd werden connected (Reiter mit höherem Z-Index). Movement von einem Token zieht den anderen mit
- Status für Reitend hinzufügen
  - Status Reitend gewährt "Vorteilhafte Position" gegenüber Nicht-Reitenden Token
- INI & GS des Reittieres zählen als INI & GS des Token im Kampf
- Lanzenangriff / Sturmangriff zu Pferd verursachen den Waffenschaden & GS/2 TP (oder so ähnlich, hab die Formel grad nicht auswendig im Kopf)
- Zugriff auf die im Reittier hinterlegten Manöver (der Char nutzt "Niederreiten", wenn das Reittier das hinterlegt hat)
- Nötige Probe auf Reiten (Kampfmanöver) des Chars wenn
  - Das Reittier > 5 SP erhält (erschwert gem. Regel)
  - Befehl erteilt wird
  - Die GS reduziert wird
- Anzeige & Berücksichtigung der Gangart
- Anzeige & Anpassung der GS je nach Gangart
- Anpassen der Modifikatoren bei Fernkampf vom Pferderücken je nach Gangart
- Berücksichtigung der Modifikatoren je nach Kampfstil / Kampfstil-SF. Diese referenzieren teilweise auf Berittener Kampf (Bsp. Ein Kämpfer erhält im berittenen Kampf einen Bonus von +1 auf "Vorteilhafte Position")
- Möglichkeit, Loyalität des Reittieres über Tierkunde Probe zu steigern
- Möglichkeit, aus dem Char heraus eine Loyalitätsprobe des Tieres zu starten
  - Char & Tier müssten quasi über eine Loyalität "verbunden" sein

Ist ja Weihnachten, da darf man sich ALLES wünschen :)

**Comment by Plushtoast** [comment]
Die Loyalitätsregeln sind so unfassbar "händisch". Ich sehe nicht wie sich die sinnvoll automatisieren lassen ohne dass man jedesmal nacharbeiten muss. Gegen die haben wir uns schon früher entschieden. 
Die Befehle sind nichts anderes als eine Aktion des reittieres und als solche möglicherweise auch gar nicht mal beim reiter zum auslösen gut aufgehoben.
Der Rest könnte gehen

**Comment by Plushtoast** [comment]
Vorschlag wie das aufgesattelt aussehen könnte?
Die Token einfach übereinander? Nebeneinander runterskaliert, dass beide token den gleichen Platz verbrauchen wie der größere Token? Kp

**Comment by mckee14** [comment]
Gute Frage...

Skalieren würde ich nicht.

Ein Reiter sollte einfach so den Status beritten setzen können (falls
random Gaul geklaut oder so).

Alternativ kann er das zusammen mit einem Tier setzen, dann werden sie
"connected". Da würde ich die Position so belassen wie vom Spieler gesetzt
und den Z Index des Reiters auf Pferd+1 setzen.

Sind grad spontan die Gedanken dazu. Was meinen denn weitere Interessenten
dazu?

Plushtoast ***@***.***> schrieb am Fr., 23. Dez. 2022, 18:12:

**Comment by Salamandris** [comment]
@mckee14 Also deine Auflistung finde ich ganz hervorragend, wobei ich mich frage ob die Loyalität nicht händisch lösbar ist. Finde persönlich die Kampfmechaniken mit den geschwindigkeiten am wichtigsten. Fernkampf vom Pferd?

Nun zum Token. Ich bin kein Freund von vielen Token auf dem Feld. Von seiten der Mechanik fände ich es cool wenn es wie Shapeshifting geregelt werden könnte. Dann ließe sich die ini/gs/ etc vom pferd übernehmen. Wenn talente und sf des Tieres dann im char bogen sind solange man beritten ist kommt man schnell an loyalitätswerte etc. Dann wären allerdings einige Proben auf die Eigenschaften des Tieres abzulegen und da frage ich mich ob man die über eine funktionalität wie shapeshifting integriert bekommt.

zuätzlicher Reiter begleiter im Heldendokument? Ließe sich für alle tierischen Begleiter inkl. Vertraute abbilden? Wobei die natürlich noch mehr mechaniken hätten.

**Comment by mckee14** [comment]
An Gestaltwandlung hatte ich gar nicht gedacht.

Es ist aber auch möglich, als Char auf einem Pferd zu sitzen und diesem den
Befehl Fass zu geben. Dann kämpft das Tier autonom und der Char kann
dennoch einen Angriff pro KR selber durchführen. Das ginge dann nicht mehr,
da bräuchte man 2 separate Token.

Da Pferde grösser sind als Chars, sollten sie auch eigens auf dem Spielplan
stehen. Auf meins wird regelmässig geschossen, da muss man es auch
anvisieren können.

Und ich kann ja von einem Pferd aufs andere springen, da brauche ich auch
die token :)

Loyalität kann man gerne ausser acht lassen. ich leider diesbezüglich
bloss, weil ich aktuell ein dr doollitte konzept spiele.

Salamandris ***@***.***> schrieb am Sa., 24. Dez. 2022, 07:41:

**Comment by Plushtoast** [comment]
ohne token wirds nicht gehen, foundry und auch dsa sind da total drauf ausgelegt.

**Comment by Plushtoast** [comment]
Wo steht, wie sich die Geschwindigkeit nach Gangart verändert?

**Comment by mckee14** [comment]
Tiergefährten

https://ulisses-regelwiki.de/RE_GangartenErschoepfungundGeschwindigkeit.html

Schritt 0.1 - 4 GS
Trab 4 - 2/3 der max. GS
Galopp 2/3 - max. GS

Plushtoast ***@***.***> schrieb am So., 25. Dez. 2022, 11:33:

**Comment by Plushtoast** [comment]
max gs in diesem fall gs*2?

**Comment by mckee14** [comment]
Max GS meint die reguläre GS aus der Kreaturenbeschreibung, zB 12.

Dann wären die Geschwindigkeiten
0.1-4
4-8
8-12

Und sprinten wäre dann max 12*2

Ob Sprint auch pro Gangart zählt, weiss ich nicht... kann man im Schritt
die freie Aktion und Aktion ausgeben um 4*2 zu gehen? Keine Ahnung, macht
wohl auch keiner :-)

Entgegen der Regeln würde ich die übergangsgeschwindigkeiten nicht
überlagern sondern scharf abgrenzen
> 0 < 1/3
>=1/3 < 2/3
>=2/3 < 3/3

Plushtoast ***@***.***> schrieb am So., 25. Dez. 2022, 13:55:

**Comment by Plushtoast** [comment]
Klingt im Vergleich zur normalen Geschwindigkeit die ein Char hat etwas merkwürdig langsam.
Bin mir nicht so sicher wie das eingebaut werden soll, ohne dass es fummelig wird.

**Comment by Plushtoast** [comment]
Das werden die patch notes
The rules for mounted combat (wiihiiihi) found their way into TDE/DSA for foundry. It's a more complex function and might require some time to learn it. So hope for a video by VTTom :)

Current possibilities include:
* Select two tokens, open the token HUD of the rider and press the mount button to jump on a horse
* Drag a horse onto the riders sheet to set it as horse
* The rider will have the speed and base initiative of the horse
* Archers on horse get the speed modifier set automatically
* Riders have the skill "Riding" and "Loyalty" of their horse always in their tokenhotbar if they are currently riding
* Riders gain the advantageous position against non riders automatically
* If your rider has a horse connected and is currently riding it, then the horse token will be placed on the map too, each time you create a new rider token.
* Make sure to mark the actorLink for named horses of your heros, as unlinked horses behave slightly different
* Move the rider token around the map and the horse will follow
* The Z-index sometimes might flip. In this case draw a select box around the rider-horse pair and both tokens swap their z-Index (other token comes to the front, currently no good fix known)
* Set the speed or gear of the horse via the token HUD of the rider or the character sheet. Setting the speed is intended for the automatic calculation of charged attacks and the like
* Some special abilities for mounted combat will be improved soon, so they do what they should do. Don't forget to migrate your actors at that time.

**Comment by Salamandris** [comment]
Das finde ich schon mal gut und cool das du da so schnell dran gehst.

 

 

Von: Plushtoast ***@***.***>
Antworten an: Plushtoast/dsa5-foundryVTT ***@***.***>
Datum: Montag, 26. Dezember 2022 um 15:47
An: Plushtoast/dsa5-foundryVTT ***@***.***>
Cc: Alexander Kirchner ***@***.***>, Author ***@***.***>
Betreff: Re: [Plushtoast/dsa5-foundryVTT] Reiterkampf (Issue #1299)

 

Das werden die patch notes
The rules for mounted combat (wiihiiihi) found their way into TDE/DSA for foundry. It's a more complex function and might require some time to learn it. So hope for a video by VTTom :)

Current possibilities include:
Select two tokens, open the token HUD of the rider and press the mount button to jump on a horse
Drag a horse onto the riders sheet to set it as horse
The rider will have the speed and base initiative of the horse
Archers on horse get the speed modifier set automatically
Riders have the skill "Riding" and "Loyalty" of their horse always in their tokenhotbar if they are currently riding
Riders gain the advantageous position against non riders automatically
If your rider has a horse connected and is currently riding it, then the horse token will be placed on the map too, each time you create a new rider token.
Make sure to mark the actorLink for named horses of your heros, as unlinked horses behave slightly different
Move the rider token around the map and the horse will follow
The Z-index sometimes might flip. In this case draw a select box around the rider-horse pair and both tokens swap their z-Index (other token comes to the front, currently no good fix known)
Set the speed or gear of the horse via the token HUD of the rider or the character sheet. Setting the speed is intended for the automatic calculation of charged attacks and the like
Some special abilities for mounted combat will be improved soon, so they do what they should do. Don't forget to migrate your actors at that time.
