### ISSUE TITLE
Kritischer Erfolg (Verteidigung)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#130]
![grafik](https://user-images.githubusercontent.com/62849695/108763687-ec2b6600-7551-11eb-8da4-6e6796ecbfe3.png)

It rolls against a value of 8.
The second roll misses, but the text output states it as kritischer Erfolg.

Offical wording is different, there are "bestätigter" and "unbestätigter" kritischer Erfolg/Patzer, with different actions/modifiers associated with it.

**Comment by mckee14** [comment]
maybe feature request, not a bug :)

**Comment by Plushtoast** [comment]
I don't know. I feel like the extra word only enlarges the already big chat messages again.
The effect of "bestätiger Erfolg/Patzer" are already shown, if there are any (for parry there is no extra effect for "unbestätigter kritischer Erfolg")

**Comment by mckee14** [comment]
Then leave the wording as-is, no problem.

But when you show the effects of bestätigte krits, you should show the effects of unbestätigte, too (f.e. bestätigter kritischer treffer = gegnerische Verteidigung halbiert und TP verdoppelt. Unbestätigter kritischer treffer = nur gegnerische Verteidigung halbiert.)
That's where my confusion came from, because it looks like a false positive when you don't now that an effect is posted when you have a true positive. So it's not really a bug, just inconsistent look&feel based on the chat.

**Comment by Plushtoast** [comment]
Well that's true. Parry is the only exception with no effect for an "unbestätigter Krit".
I was thinking though some groups might still like the notation for roleplaying effects.
Like "You parry the violent attack with almost no effort, while slicing a tiny scar during the blow into your opponents hand and thus drawing first blood."

**Comment by mckee14** [comment]
If you go the route with special RP text, please allow to roll for a table there, so users can create their own datapools for nice text elements, randomly selected ;-)

Would it be hard to change the coloring of the dice in the chat output? in the picture above, both dice are green, even if the second roll missed.

So 2 green dice, plus the text "Kritischer Erfolg" together implies that the system wrongfully counted it as real/bestätigter krit. Erfolg, instead it works as it should. So it's all fine, but looks wrong.

And/or just add "bestätigt" or "unbestätigt" directly behind the "Kritischer Erfolg" at Beschreibung, this shouldn't make the chatmessage that much longer.

**Comment by Plushtoast** [comment]
Changing the dice color depending on their result is contrary to the chosen color by attribute.
Parry has been chosen to be green, attack red.

RP text can be implemented by creating a table (at the tables tab) manually for each group individually.
