### ISSUE TITLE
Soundboard by Blizz

### ISSUE THREAD

**Issue by Xermen** [Plushtoast/dsa5-foundryVTT#1300]
Das Soundboard scheint mit dem DSA CSS nicht klar zu kommen. 
![image](https://user-images.githubusercontent.com/96532026/209005282-ef600db4-60cd-46cb-9786-e8a2327be9c9.png)
Vielen Dank fürs drüber schauen

**Comment by Plushtoast** [comment]
Related to #1237

**Comment by Plushtoast** [comment]
css fix kann über das modul hier bezogen werden
https://github.com/Plushtoast/dsa5-glueandhammer

Bald auch über den package installer verfügar
