### ISSUE TITLE
Offhand/Nebenhand in Kampf Tab abbilden

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1302]
**Is your feature request related to a problem? Please describe.**
Wird eine Waffe als Nebenhand geführt, dann ist dies im Charbogen aktuell nicht sichtbar. Ein optischer Indikator aller Nebenhand Waffen wäre durchaus nützlich.

**Comment by Salamandris** [comment]
Wäre auch für den Kampf mit 2 Waffen schön wenn man sie im char Bogen in main und Offhand trennen kann. Dann könnten Sachen wie Falsche Hand automatisch gezogen werden. So liegen bei zwei identischen Dolchen diese gestapelt im Inventar. 

Auch für den Schildangriff interessant wenn definierbar wäre, das das Schild in der falschen hand ist. 

Dies hätte glaube ich auch Einfluss auf die nutzbaren Kampf Sonderfertigkaiten. Zumindest beim beidhändigen Kampf dürfen meines Wissens nur Basismanöver eingesetzt werden.

**Comment by mckee14** [comment]
Das stimmt, aber beidhändiger Kampf bedeutet, dass man mit beidem aktiv
kämpft, nicht dass man in beiden händen etwas hält.

Das system kann nicht wissen, ob du nach einem ersten angriff nochmals
einen mit der anderen hand machst. somit lässt sich das nicht komplett
automatisieren.

(solange man in beiden händen etwas hält, ist jedoch der "einhändige kampf"
nicht möglich, welcher einen bonus gibt. das geht nur, wenn die nebenhand
leer ist)

Salamandris ***@***.***> schrieb am Mo., 2. Jan. 2023, 05:30:

**Comment by Plushtoast** [comment]
Um zwei dolche mit vordefiniertem
Nebenhand modifikator zu verwenden so vorgehen: strg gedrückt halten dolch im Inventar per drag and drop bewegen dann wird elne kopie erstellt. Ggf umbenennen. Item sheet öffnen und haken für nebenhand setzen.

**Comment by Plushtoast** [comment]
Das funktioniert schon so wie es soll

**Comment by frankyh75** [comment]
Hallo, die Mechanik der NebenHand  scheint in Foundry V 13 nicht mehr richtig funktionieren.
Das Feld ist im Kampfwurf ausgegraut und führt nicht mehr zu Abzügen. Ich mache gerne einen Screenshot, wenn gewünscht.
