### ISSUE TITLE
Reichweite im Nahkampf bei tierischen Gegnern

### ISSUE THREAD

**Issue by olipool** [Plushtoast/dsa5-foundryVTT#1303]
**Describe the bug**
Beim Angriff auf tierische Gegner mit mehreren Angriffsreichweiten wird die kleinste Reichweite für die Erschwernis herangezogen.

**To Reproduce**
1. Wähle Spieler im Kampf aus
2. Greife Gegner mit verschiedenen Reichweiten an (z.B. Tatzelwurm)
3. der Angriff wird mit der kleinsten Reichweite erschwert (bzw. erleichtert)

**Expected behavior**
Hat in tierischer Gegner Angriffe mit verschiedenen Reichweiten (z.B. Tatzelwurm kurz, mittel und lang), so sollte bei einem Angriff auf diesen Gegner die längste Kategorie als Erschwerniss für den Angriff gewählt werden, wie es auch bei kulturschaffenden Gegnern der Falls ist.

**Versions:**
- Foundry Version 10
- DSA/TDE version 4.1.20

**Context**
Kürzere Waffen erhalten ja im Nahkampf beim Angriff gegen Gegner mit längeren Waffen eine Erschwernis. Vgl. hier den Punkt “Nahkampfreichweite”. 

Foundry berücksichtigt dies bei kulturschaffenden Gegnern, die Waffen verschiedener Länge ausgerüstet haben (z. B. einen “kurzen” Dolch und einen “langen” Magierstab”) und wählt bei der Auswahl des Tokens automatisch die längste Waffenkategorie des Gegners aus, was klasse ist.

Bei tierischen Gegnern funktioniert dies scheinbar nicht. Beispielsweise hat der Tatzelwurm 3 verschiedene Angriffe mit unterschiedlichen Reichweiten: Biss (kurz), Klauen (mittel) und Schwanz (lang). Hier wählt Foundry automatisch die kürzeste Reichweite aus statt der längsten, also genau umgekehrt im Vergleich zu Kulturschaffenden mit Waffen. Sollte nicht auch der Tatzelwurm aufgrund seiner potenziell langen Reichweite einem Angreifer mit einer mittleren Waffe oder kurzer Waffe den Angriff schwerer machen? 

Selbiges ist der Fall bei Riesenamöbe, Perldrache usw. (möglicherweise bei allen Wesen, deren Angriffe über “Eigenschaft” laufen?)

Ist das absichtlich so gelöst, weil es da möglicherweise eine Regel zu Tieren gibt, die die allgemeine Reichweiten-Regel außer Kraft setzt? Oder könnte das sonst in Foundry geändert werden, dass auch bei Gegnern mit Biss, Klaue und Co jeweils die längste Reichweite vorausgewählt ist?

**Comment by Plushtoast** [comment]
Ist für den nächsten patch schon drin

**Comment by olipool** [comment]
Großartig, danke dir! :)

**Comment by olipool** [comment]
Ich habe es mal nachgetestet, sowohl in der 4.2.0 als auch 4.2.1 funktioniert es noch nicht.

**Comment by Plushtoast** [comment]
Die Angriffe der Tiere müssen auch einen parade Wert haben
