### ISSUE TITLE
SF Tiefe Wunde: Selbstbeherrschungsprobe

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#1313]
**Is your feature request related to a problem? Please describe.**
Die SF Tiefe Wunde aus dem Kompendium II setzt beim Ziel den Status Blutend - leider wird dabei im Gegensatz zum manuellen Hinzufügen des Effekts zum Ziel keine Selbstbeherrschungsprobe zur Ermittlung der Effektdauer ausgelöst.

**Describe the solution you'd like**
Es sollte eine Selbstbeherrschungsprobe ausgelöst und der Effekt Blutend mit einer Dauer versehen werden.

**Comment by zoidable** [comment]
Der Fix aus #1337 ist bei näherer Betrachtung eher ein Workaround, da die Effektdauer so nicht mehr überschrieben werden kann, was man mMn aber können sollte. Dafür müsste aber die Wirkungsdauer von Effekten aus Sonderfertigkeiten in der Funktion [`_parseEffectDuration`](https://github.com/Plushtoast/dsa5-foundryVTT/blob/f409ab1fc8e056d435e56334e51166a00428ed46/modules/status/active_effects.js#L335) ausgewertet werden, was aktuell nicht der Fall ist, es wird nur die _duration_ der _source_ (im Falle von SF die Waffe) ausgewertet.

**Comment by zoidable** [comment]
Hm, vielleicht habe ich aber auch nur die Funktionsweise der im "Erweitert"-Tab eines Effekts definierbaren Wirkungsdauer (effect.flags.dsa5.customDuration) noch nicht verstanden. Ich hätte erwartet, dass man hierüber z.B. auch eine eigene Wirkungsdauer (z.B. "10 KR") für einen Systemeffekt "Blutend" definieren kann, aber anscheinend bezieht sich das nur auf Zauber und geht von komma-separierten Werten für unterschiedliche QS aus...?

**Comment by Plushtoast** [comment]
jup

**Comment by zoidable** [comment]
Dann fehlt aber derzeit allgemein die Möglichkeit aus SF übertragenen Systemeffekten (weiteres Beispiel wäre Schmerz durch SF Klinge drehen) eine Wirkungsdauer zu geben oder?

**Comment by Plushtoast** [comment]
Das stellen die Macros ein. Es gibt keine 3 Sonderfertigkeiten die nach dem gleichen Schema funktionieren. Eine Verallgemeinerung wie bei Zaubern is hier schwierig bis unmöglich.

**Comment by zoidable** [comment]
Fair enough
