### ISSUE TITLE
Error: You are accessing the Actordsa5#data object which is no longer used

### ISSUE THREAD

**Issue by coffiarts** [Plushtoast/dsa5-foundryVTT#1314]
**Describe the bug**
Ich bekomme o.g. Fehlermeldung in Foundry v10.291 (latest) mit dsa5-foundryVTT v. 4.2.1 (latest). 
Sie kommt zwar aus aus commons.js, aber die monierten Objekte/Referenzen klingen eindeutig nach dsa5 ("Actordsa5#data", "DSAActiveEffect#data").
Ist das vielleicht ein bereits bekanntes Kompatibilitätsproblem mit Foundry 10?

**To Reproduce**
Es scheint, als trete dies v.a. auf, wenn ich Tokens markiere und in den "Kampfmodus" setze

**Expected behavior**

**Screenshots**
Volle Fehlermeldung (2 Beispiele):
Error: You are accessing the Actordsa5#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Function._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at retrieveItemLights (lib.js:752:28)
    at addLightsHUDButtons (lights-hud-ate-config.js:40:32)
    at Object.renderTokenHUD (module.js:57:9)
    at Object.fn (module.js:44:16)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenHUD._render (foundry.js:5153:13)
    at async TokenHUD._render (foundry.js:68578:5)

commons.js:1703 Error: You are accessing the DSAActiveEffect#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1692:19)
    at Function._logV10CompatibilityWarning (commons.js:6642:14)
    at get data [as data] (commons.js:6542:24)
    at lib.js:755:27
    at EmbeddedCollection.filter (commons.js:3244:14)
    at retrieveItemLights (lib.js:754:39)
    at addLightsHUDButtons (lights-hud-ate-config.js:40:32)
    at Object.renderTokenHUD (module.js:57:9)
    at Object.fn (module.js:44:16)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenHUD._render (foundry.js:5153:13)
    at async TokenHUD._render (foundry.js:68578:5)

**Versions:**
- Foundry Version: 10.291
- DSA/TDE version: 4.2.1
- Related modules version: keine

**Comment by Plushtoast** [comment]
Hast du irgendein Addon das etwas mit Lichtern macht. Das klingt nach einem Modul error.

**Comment by coffiarts** [comment]
Danke für den Hinweis. Ich habe diverse Lichtmodule, ja, aber unter diesem Blickwinkel vermute ich eher, dass das hier mit größerer Wahrscheinlichkeit das Problem sein könnte: https://github.com/kckaiwei/TurnMarker-alt/issues/108 [EDIT: Stimmt wohl doch nicht, siehe unten)
Zumindest ist bekannt, dass Turn Marker noch Kompatibilitätsprobleme hat. Dass es genau beim Starten eines Kampfes auftritt, würde noch mehr dazu passen.
Ich sollte erst mal weiter versuchen, TM sauber zu deinstallieren und die Abhängigkeit aus meiner Spielwelt rauszukriegen. Somit war meine Meldung hier sicher verfrüht (gerne schließen).

**Comment by coffiarts** [comment]
Kleine Korrektur: Es scheint eher LightsHUD zu sein (hätte ich eigentlich aus selbst der Fehlermeldung entnehmen können, wenn ich genauer hingeschaut hätte ;-): https://github.com/Malekal4699/LightsHUD
Keine Ahnung, was das Problem ist, aber hier ist es sicher am falschen Ort.

**Comment by Plushtoast** [comment]
Das Grundregelwerk Modul hat übrigens eingebaute Lichteffekte für Fackeln und Co.
Das kann man am HUD über die Licht Makro Einstellungen aktivieren.
https://www.youtube.com/watch?v=2WnYh1kpXrU&ab_channel=VTTom

**Comment by coffiarts** [comment]
> Das Grundregelwerk Modul hat übrigens eingebaute Lichteffekte für Fackeln und Co. ...

ja, das ist natürlich korrekt (und mir auch bewusst). Ich hatte LightsHUD schon länger im Einsatz, bevor diese Neuerung in dsa5 kam, und konnte mich bis jetzt nicht umgewöhnen. Danke trotzdem für den Hinweis. Werde dem dsa5-Feature jetzt aber mal wieder etwas Augenmerk schenken. Ein Modul weniger in meinem ganzen Wust wäre zur Abwechslung auch mal wieder nicht falsch... ;-)
