### ISSUE TITLE
Statuseffekt: Belastung

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1318]
**Describe the bug**
Ich habe versucht es bei einer Rüstung den Statuseffekt für Belastung (getestet mit Wert 1 und -1) einzustellen, allerdings ohne Erfolg. Getestet mit und ohne Zonen. Fehlermeldung in der Konsole: "You are accessing the DSAActiveEffect#Data object which is no longer used..."

**Comment by Plushtoast** [comment]
Ich vermute deine Fehlermeldung kommt aus einem anderen Modul, kannst du die komplett herkopieren?

Ansonsten scheint die Belastung aber korrekt zu funktionieren. Kann es sein dass der Charakter mit dem du getestet hast Belastungsgewöhnung hat?

**Comment by Plushtoast** [comment]
Bei Zonenrüstung wird die Belastung berechnet, das Feld is da nur noch rein kosmetisch.

**Comment by Ogrimgro** [comment]
Fehlermeldung kommt bei genauerer Betrachtung wirklich von einem anderen Modul - sorry dafür. Nochmal im Detail:

Hier der Effekt den ich der Rüstung hinzugefügt habe:
![image](https://user-images.githubusercontent.com/122533617/212309831-3e8e578f-4e91-4209-9ea7-9619dcfad536.png)

Im Status wird die Auswirkung korrekt angezeigt. Die Belastung wird kumuliert von 3 auf 2 gesenkt.
![image](https://user-images.githubusercontent.com/122533617/212309578-c24aedab-3628-41c2-9f37-d16b2aaa7b46.png)

Was allerdings nicht zu funktionieren scheint ist die Auswirkung der Reduktion. GS und INI stehen weiterhin auf 5, werden also um 3 reduziert (Basis 8). Mit einer Stufe weniger Belastung müsste es allerdings 6 sein. Komischerweise werden die Kampfwerte durch die Belastung überhaupt nicht beeinflusst.
![image](https://user-images.githubusercontent.com/122533617/212309659-0f8df2f0-a3cc-4b79-b6a5-f6f966d8e8ff.png)

**Comment by Ogrimgro** [comment]
Danke für den schnellen Fix. Was allerdings immer noch fehlt ist der Effekt der Belastung auf AT/PA. Da scheint es sich derzeit überhaupt nicht auszuwirken. Anbei Screenshots vom gleichen Helden. Trotz Belastung ist AT/PA unverändert.


![Screenshot_20230114-143359](https://user-images.githubusercontent.com/122533617/212474653-24dd8851-756a-428a-8506-ba06ba612fb4.png)
![Screenshot_20230114-143348](https://user-images.githubusercontent.com/122533617/212474655-79cf3e8d-b873-4582-8150-a3c3cdeeb694.png)

**Comment by Plushtoast** [comment]
Das erscheint wenn du den Angriffswurf machst in "Situationsbedingte Modifikatoren"

![grafik](https://user-images.githubusercontent.com/44941845/212475031-04ca8349-6e7d-407d-8e0e-7b4890df0590.png)
