### ISSUE TITLE
Adjustment Creature Sheet

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1319]
**Is your feature request related to a problem? Please describe.**
No proper space for several informations related to creatures. Quantity, size and weight can only be added to the description-box, where they don't really fit. Moreover (and more importantly) there is not space to add an information roll (@Info[]) for and information item.

**Describe the solution you'd like**
Add a header to the notes tab bases on the plants sheet with additional boxes for quantity, size, hight and a place for information roll tables.

**Describe alternatives you've considered**
Adding all information the description-textbox works, but doesn't look good.

**Additional context**

**Comment by Plushtoast** [comment]
info item can be added via drag and drop like all other items
rest is probably a no

**Comment by Ogrimgro** [comment]
I know that I can drag and drop the information. However, it doesn't look very nice adding it together with other information. I'd love to see a rework for the creature sheet with additional boxes for the info and the other things. Maybe think about and update for the Bestiarium with info items for the creatures and a reworked creature sheet. That would convince at least me to buy it

**Comment by Plushtoast** [comment]
Alle Kreaturen in allen Modulen sollten Info Items haben,
haben sie das nicht wäre das ein Bug. Das ist oben bei den Notizen zu finden und kann auch in den Chat gepostet werden zum würfeln. Das ist schon super luxuriös.

**Comment by Plushtoast** [comment]
Die Kreaturen haben auch Furchtimmunität extra Schadensempfindlichkeit gegen bestimmte Waffen etc.
Ich mach nachher noch nScreenshot

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/212378060-3e674da9-f1d7-4bfb-aa15-9d6f176c76bf.png)

Konstruktive kritik ist in Ordnung. Erpressung mit noch mehr Arbeit für Kauf von Modulen nicht.

**Comment by Ogrimgro** [comment]
OK, überzeugt. Das die Infos schon drin sind und auch einen eigenen Bereich haben ist mir entgangen, zumal der größte Teil der Tiere die bei mir aktuell drin sind aus den Götter- und Magiemodulen stammen (Vorlagen für Gestaltwandlung) und dementsprechend keine Information hinterlegt haben. Damit hat sich das im Endeffekt erledigt.
Ich finde den Ansatz aus dem Herbarium mit "aufgeklappter" Information und losgelöstem Info-Item zwar schöner, kann allerdings verstehen, dass man sich die Arbeit in dem Fall nicht doppelt macht, insbesondere da es sicher auch zwei Meinung dazu geben wird, was denn "besser" ist. Den Vorwurf der Erpressung hätte es dennoch nicht gebraucht.
