### ISSUE TITLE
Soundeffekte für Reaktionen/Kritische Treffer

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1326]
Derzeit ist es nicht möglich Soundeffekte und Animationen (Automated Animations) für Reaktionen (Parade/Ausweichen) und kritische Treffer zuzuweisen. Es wäre außerdem wünschenswert, dass man bei dieser Gelegenheit auch die Inventargeräusche anders anlegt, da man mit der aktuellen Lösung gezwungen ist alle 4 Audio Game Bundles zu installieren, was mehr als 2GB Speicher auf dem Server beansprucht. Hier würde ich mir eine flexible Lösung mit frei wählbaren Sounds wünschen.

![Screenshot_20230118-181147](https://user-images.githubusercontent.com/122533617/213249769-3e600d73-d160-4c74-b3d0-5e93c8a971fd.png)

**Comment by Plushtoast** [comment]
Die Inverntargeräusche können mit dem Code
```js
Hooks.once("setDefaultDSASounds",  (sounds) => {
    console.log(sounds)
})
```
im nächsten Patch angepasst werden. komfortabler wirds aber nicht mehr werden

**Comment by Plushtoast** [comment]
Der Rest muss warten bis automated animations mit v11 läuft

**Comment by Plushtoast** [comment]
Ab 5.1.0 kann man folgendes in Automated Animations einstellen:

```
Dolch
Dolch (Parade)
Dolch (Kritischer Erfolg)
Dolch (Patzer)
Kritischer Erfolg
Patzer
Parade
Parade (Kritischer Erfolg)
Parade (Patzer)
```
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/85f8774d-6bbe-4c59-a4eb-e843f7362693)
