### ISSUE TITLE
"keine Vergleichsprobe" dem Spielerzugriff teilweise entziehen.

### ISSUE THREAD

**Issue by Gunthgard** [Plushtoast/dsa5-foundryVTT#133]
Die Möglichkeit das Feld "keine Vergleichsprobe" zu klicken bzw. durch das "x" zu entfernen, sollte dem Spieler nur in bestimmten Situationen zur Verfügung gestellt werden. Sonst kann es passieren das bestimmte Handlungen vom SL nicht mehr durchgeführt werden können. 

Beispiel:
Wenn ein Spieler mit seinem Sc einen NSC angreift und dieser Angriff erfolgreich ist, kommt danach eine Chatmeldung mit den Token der Kontrahenten und einer Bemerkung unten, rechts im Chatfenster "keine Vergleichsprobe" mit einem "x" daran. Wenn der Spieler diese "x" drückt bevor die Aktion des NSC vom SL ausgeführt wurde, wird der Handlungsalgorithmus durchbrochen und es kann nachfolgend keine AT bzw. Ausweichen durch den SL in diesem Kontext durchgeführt werden. Nur die Chatmeldung mit den beiden Token bleibt dann bestehen, Schaden oder ähnliches kann nicht als Meldung ausgegeben werden und damit auch nicht auf den Token übertragen werden.

![Test 1](https://user-images.githubusercontent.com/31367391/108868853-e6d42700-75f6-11eb-93d2-aff590b1d495.png)

![Test 2](https://user-images.githubusercontent.com/31367391/108868875-ea67ae00-75f6-11eb-8a14-4394e9155c8e.png)

Vorschlag:
Die Möglichkeit auf das "keine Vergleichsprobe" zu klicken sollte der Spieler nur dann erhalten, wenn er bzw. sein Sc von dem Angriff betroffen ist und eine PA bzw. ein Ausweichen durchführen muss. Alle anderen Möglichkeiten sollten allein dem SL obliegen.

**Comment by mckee14** [comment]
Ich habe genau dieses Verhalten gestern als GM und Spieler gleichzeitig getestet. Wenn der Spieler keine Berechtigung für den involvierten Token hatte, konnte er den Ablauf NICHT durchbrechen.

Der Spieler konnte im Client zwar auf das X klicken, allerdings wurde eine Fehlermeldung angezeigt von Foundry, dass die Rechte nicht ausreichend sind.

Obwohl für den Spieler der Hinweis und das X danach ausgeblendet sind, kann der SL dies immer noch sehen und er kann immer noch die Vergleichsprobe ablegen.

**Getestet mit Firefox**, reiner Clientzugriff (Foundry läuft auf webserver in Docker)

Muss wohl genauer analysiert werden.

**Comment by Plushtoast** [comment]
Teilweise entziehen is leider kurzfristig zu aufwendig. In Zukunft kann das nur noch der GM.
