### ISSUE TITLE
Umsetzung Schmieden & Tränke brauen

### ISSUE THREAD

**Issue by Micangelus** [Plushtoast/dsa5-foundryVTT#1331]
**Is your feature request related to a problem? Please describe.**
Wir wünschen uns gerne eine Modulumsetzung der Herstellungsregeln für das Schmieden von Waffen und Rüstungen, und vielleicht auch das Brauen von Tränken.

**Describe the solution you'd like**
Schön wäre eine ähnliche Lösung wie im Elementatrium oder Nekromathäum, in dem Material, Herstellungstalente, Komplexität, Zeitintervall, Herstellungstechnik und Effekte aus dem gewählten Material berücksichtigt werden. 

Denkbar, dass man sich aus der Bibliothek ein zu erstellendes Objekt als Blaupause in das Fenster zieht und per Checkbox oder Schieberegler seine Materialauswahl usw. zusammenstellt, um am Ende ein fertiges Item zu bekommen.
Gerade die Waffen- und Rüstungserstellung wären interessant, aber auch das weniger Zeit in anspruchnehmende Brauen von Tränken.

Die Menge des Materials sollte selbstständig vom SL oder Spieler aus dem Inventar gestrichen werden.

Vielen Dank im Voraus für das Feedback!

**Comment by Plushtoast** [comment]
Schon in arbeit

**Comment by Micangelus** [comment]
> Schon in arbeit

Darf ich fragen in welchem Modul diese Features enthalten sein werden, um das auf der Roadmap nachzuverfolgen?

**Comment by Plushtoast** [comment]
Schmieden kompendium 
Alchimie System oder grundregelwerk
