### ISSUE TITLE
Panik-Regeln

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1332]
**Is your feature request related to a problem? Please describe.**
Die Panik-Regeln sind eine Fokusregel I aus dem Kompendium II S.22ff.
Diese an sich sehr schönen Regel, die bei der verteilung von Furchtstufen triggert, erfordert allerdings durchaus zusätzlichen Würfel- und Verwaltungsaufwand.

**Describe the solution you'd like**
Optimal wäre der automatische Vorschlag eine Panik Probe abzulegen, sobald eine Furchtstufe verteilt wird. Die Panikprobe an sich mit ergebnis ausspucken zu lassen wäre schon super. Noch toller wäre natürlich, wenn die Effekte dann auch implementiert wären.

**Describe alternatives you've considered**
Teillösungen oder Hilfen (Nur Panikproben oder nur vorbereitete Effekte) wären für sich genommen jeweils ebenfalls schon eine große Hilfe.

**Additional context**
Ich weiß und sehe, dass die Liste der Contentvorschläge gewaltig ist, dachte mir aber dies könne ich ja trotzdem mal eingeben. Gerade für Horror- oder Dungeonszenarien ist das eine so schöne Sache, die es ja vielleicht zumindest auf die evntuell irgendwann Liste schaffen könnte.

**Comment by Plushtoast** [comment]
Meine im Compendium 2 da schon was gemacht zu haben

**Comment by TarionT** [comment]
Ich hab zumindest die Rolltables und ein entsprechendes Würfelmacro mal beim Vorbereiten des Abenteuers "Gefangen in der Gruft der Königin" erstellt. Falls Interesse besteht bitte hier melden, dann kann ich das mal zur Verfügung stellen.

**Comment by TarionT** [comment]
![grafik](https://user-images.githubusercontent.com/85405731/213872785-60b0696b-7070-4426-9ce3-303ce9ecf911.png)
![grafik](https://user-images.githubusercontent.com/85405731/213872806-a1cca791-138c-4834-a26f-e559f8eaf54f.png)
![grafik](https://user-images.githubusercontent.com/85405731/213872826-35a6c3f9-9ebb-4750-bb2c-6f7ae8315f36.png)

**Comment by Plushtoast** [comment]
Ist in compendium 2 schon drin.
Änderungsvorshcläge dafür gerne in einem neuen ticket

**Comment by Zonenpenner** [comment]
Lol, euer Foundry-System kann bereits so viel, dass man implementierte Funktionen glatt übersieht.^^
Aber es sind tatsächlich bereits die Panik-Zustände implementiert! Toll! 
Aber die Panik-Probe, ob eine Panik zustande kommt, ist doch noch nicht drin, oder? Konnte ich zumindest nicht finden.
Dazu wie gewünscht ein neues Ticket: 
https://github.com/Plushtoast/dsa5-foundryVTT/issues/1334

@TarionT Genau für das Abenteuer dachte ich mir, wäre das super!
