### ISSUE TITLE
Conflict with the module "Monk's Little Details"

### ISSUE THREAD

**Issue by Scaby79** [Plushtoast/dsa5-foundryVTT#1345]
The transparency in the rounded corners of every window is replaced with a grey background if the module "Monk's Little Details" is active.
![Issue_MLD](https://user-images.githubusercontent.com/25106826/213797176-bf4e8d8c-8562-412e-b846-b0232785df01.png)

_Originally posted by @Scaby79 in https://github.com/Plushtoast/dsa5-glueandhammer/issues/1_

**Comment by CokaColaOase** [comment]
Hey @Scaby79,
I had the same issue and found these 2 settings in Monk's that are ON by default. Turning them OFF fixed the issue for me:


![Image](https://user-images.githubusercontent.com/98277990/215350551-573c056f-9252-433c-adbf-c57c3770f2f5.png)

**Comment by Scaby79** [comment]
> Hey @Scaby79, I had the same issue and found these 2 settings in Monk's that are ON by default. Turning them OFF fixed the issue for me:
> 
> ![Image](https://user-images.githubusercontent.com/98277990/215350551-573c056f-9252-433c-adbf-c57c3770f2f5.png)

Thank you very much @CokaColaOase !
This is fixing it for me, so I'm closing this issue.
