### ISSUE TITLE
Adding Adersin Wandering sword does not provide Principles II  

### ISSUE THREAD

**Issue by JanikBastien** [Plushtoast/dsa5-foundryVTT#1348]
**Describe the bug**
When opting for profession Adersin Wandering Sword, only one level of Principles show up. The second one is missing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**
- Foundry Version
- DSA/TDE version
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
@Murm3lt13r 
Need to compare with the german version and see if there is a translation problem

**Comment by JanikBastien** [comment]
Same happened with another character (Blessed one of Phex). Only one level of principles and one level of obligations appear, when this character should have II for both.
