### ISSUE TITLE
Spielerentscheid bei SL-Willkür

### ISSUE THREAD

**Issue by Deremus** [Plushtoast/dsa5-foundryVTT#1355]
**Describe the bug**
Bei den durch SL-Willkür ausgeführten Attacken, öffnet sich ein Fenster auf Spielerseite und lässt den Besitzer des Tokens (meist der Spieler) über die Trefferzone entscheiden, sprich den W20-Wurf bestimmen.

**To Reproduce**
Attacke durch GM-NPC -> erfolgreich
Parade durch Spieler -> nicht erfolgreich
Schadenswurf wird im Chat gezeigt
unabhängig von der Höhe des Schadens wird dann ein Fenster beim Besitzer des Tokens geöffnet, und dieser darf den W20 Wurf für die Trefferzone auswählen

**Expected behavior**
Das Fenster sollte sich ausschließlich auf Seite des GM öffnen.

**Screenshots**

![SL-Willkür](https://user-images.githubusercontent.com/96583392/216376051-12cf0d37-e89f-4772-aba9-32997f669626.PNG)

**Versions:**
- Foundry Version: 10.291
- DSA/TDE version: 4.2.9
- Related modules version "The Dark Eye 5th Ed. - Core Rules" 4.2.1 und "The Dark Eye 5th Ed. - Compendium I" - 4.2.1

**Additional context**

**Comment by Plushtoast** [comment]
Ich kann das nicht reproduzieren. Hast du allen Spielern GM Rechte gegeben?

**Comment by Plushtoast** [comment]
Kannst du genauer ´beschreiben, was ihr da macht. Bei mir geht das einwandfrei.

**Comment by Plushtoast** [comment]
Ah ne jetzt hab ichs
