### ISSUE TITLE
Schaden an SC selbst anwendbar

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#1356]
Es wäre cool, wenn die Spieler,  den von der SL ausgewürfelte Schaden, sie auch selbst auf ihre SCs anwenden könnten per rechtsklick aufs chatfenster. 
Das nimmt der SL etwas Arbeit ab.

**Comment by mckee14** [comment]
+1 

Durch das Häckchen ist auch transparent ersichtlich, ob es bereits angewendet wurde (genau wie bei der Regeneration).

**Comment by KnoepfchenFulla** [comment]
+1

Wäre super, wenn das genauso funktionieren würde wie beim Bezahlen von Astralpunkten via Chatklick durch die Spieler.
