### ISSUE TITLE
Fernkampfdropdown "gezielt" hinzufügen

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#136]
**Is your feature request related to a problem? Please describe.**
Zielen ist eine Handlung die im Kampf mit Fernkampfwaffen sehr nützlich ist. Entsprechend wäre es toll, wenn es hierzu ein dropdownmenü gäbe damit es nicht immer manuell verrechnet werden muss.

Regelteil:
Zielen
Jede zum Zielen genutzte Aktion erleichtert den folgenden Schuss um 2. Dieser Bonus kann bis zu einem Maximum von 4 erhöht werden. Zielen ist eine länger dauernde Handlung bis zum eigentlichen Angriff

**Comment by mckee14** [comment]
@Nyhles Füge als work-around "Zielen" als Kampfsonderfertigkeit hinzu, für 0AP Kosten und 2 Stufen. Dann kannst Du während des Angriffs mit links/rechtsklick auf die Sonderfertigkeit die Stufen wählen und automatisch die Erleichterung einfliessen lassen.
![grafik](https://user-images.githubusercontent.com/62849695/109147122-f1143380-7764-11eb-90af-2b2d2c35ba06.png)

**Comment by Nyhles** [comment]
@mckee14 Vielen Dank, gute Idee für einen Workaround 👍
