### ISSUE TITLE
Golemiden Herstellung kann nicht fertiggestellt werden

### ISSUE THREAD

**Issue by teliogeo** [Plushtoast/dsa5-foundryVTT#1362]
**Describe the bug**
Nachdem der Spieler die Beschwörungsanfrage über das Spielermenü für den Spielleiter gestellt hat, kann dieser nicht auf Fertigstellen klicken, um die Beschwörung zu erlauben. Es kommt eine Fehlermeldung in der Konsole.

**To Reproduce**
1. Spielermenü öffnen und die Beschwörungsschritte für Golemiden durchgehen.
2. auf fertigstellen klicken 
3. auf Fertigstellen klicken bei dem neu geöffneten Fester für Beschwürungsanfrage

**Expected behavior**
Das man einen Token bekommt, der den verbesserten Golemiden repräsentiert

**Screenshots**

![Screenshot 2023-02-15 114605](https://user-images.githubusercontent.com/56913886/219006881-a7b402d8-7081-4f13-aaf0-ceba26038720.png)

**Versions:**
- Foundry Version 10 Build 291
- DSA/TDE version 4.2.11
- Related modules version
- DSA/TDE Aventurisches Elementarium Version 4.2.2

**Additional context**

**Comment by Plushtoast** [comment]
Notiz an mich selbst: magie 3 gleicher bug
