### ISSUE TITLE
[compendium2] Berserkerangriff Bonus-TP fehlerhaft

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#1364]
**Describe the bug**
Der durch die Anwendung der SF Berserkerangriff aus dem Compendium 2 hinzugefügte Status weist bei den TP (system.meleeStats.damage) den Wert "+2" anstatt "2" auf, was dazu führt, dass der Modifikator nicht ausgwertet werden kann und als NaN angezeigt wird.

**Screenshots**
![image](https://user-images.githubusercontent.com/81991198/219087617-c71030ee-6275-4ff1-9e28-556b1f6566c2.png)
![image](https://user-images.githubusercontent.com/81991198/219087862-93ce2073-d538-47c1-9203-3c15182e4809.png)

**Comment by Plushtoast** [comment]
system.meleeStats.damage ist ein String. dadurch kann man dann da auch +1d6 für einen extra Würfel oder so eintragen. in diesem fall ist der string "0+2". das funktioniert beim schadenswurf der zusammen mit der angriffsprobe kommt auch einwandfrei.
beim reinen schadenswurf scheints aber einen bug zu geben.
