### ISSUE TITLE
Sort Initiative by [RolledInitiative].[BaseInitiative]

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#137]
**Is your feature request related to a problem? Please describe.**
In DSA, when combatants have the same calculated Initiative the cpmbatant with the higher Base Initiative goes first.
Currently there is no way to handle this case.

**Describe the solution you'd like**
By Adding the Base Initiative Value as a Decimal it should be no problem to handle this case.

From the Rules-Wiki:

> Der Beteiligte mit der höchsten Initiative darf als Erster im Kampf handeln. Haben zwei Beteiligte die gleiche Initiative, handelt der von ihnen zuerst, der den höheren Initiative-Basiswert hat. Sind diese ebenfalls gleich, würfeln beide einen W6. Derjenige mit dem höheren Ergebnis darf vor dem anderen handeln.

**Comment by mckee14** [comment]
This would be great, same handling as other platforms (R20). So INI 18.15 goes before 18.14
