### ISSUE TITLE
[Sammelprobe] Anzahl der Versuche

### ISSUE THREAD

**Issue by yendors-vtt** [Plushtoast/dsa5-foundryVTT#1370]
Es wäre schön, wenn neben dem Status der Sammelprobe, also den bereits gesammelten QS (z.B. 8/10), auch die bereits verwendeten Versuche sowie die Anzahl der erlaubten Versuche (z.B. 2/7) in der Übersicht der Sammelproben angezeigt wird.

**Comment by Plushtoast** [comment]
Du meinst auf dem Charakterbogen richtig?

**Comment by yendors-vtt** [comment]
Ja genau!
