### ISSUE TITLE
shrink riders if tokens equal size

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1372]

**Comment by mckee14** [comment]
Rider & Mount verbinden sich übrigens nur in der aktiven Szene, nicht in
einer aktivierten szene.

Reiter erhält höhe 1 beim aufsitzen, toll wäre reittier & 1.

...möchtest du reiter sachen gebündelt oder soll ich einzelne tickets
machen?

Plushtoast ***@***.***> schrieb am Di., 28. Feb. 2023, 19:04:

**Comment by Plushtoast** [comment]
gebündelt extra ticket vlt schaffts das dann noch in den patch

reittier + 1 sollte bereits so sein

**Comment by mckee14** [comment]
Kind Unfall Krankenhaus, komme grad nicht dazu

Plushtoast ***@***.***> schrieb am Mi., 1. März 2023, 14:26:

**Comment by Plushtoast** [comment]
Oje na dann alles gute.

* Reiter + 1 ist gefixt
* Reiter mit Pferd verbinden auf Szene die nicht aktiviert ist geht nicht, weil von Foundry der passende Hook fehlt. Vermutlich wird das so bleiben.
