### ISSUE TITLE
Eigenschaftswerte beim Hovern im Chat verbergen - nicht länger verfügbar in V10?

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#1379]
Da folgende Feature, das in 3.4.0 umgesetzt wurde, scheint in V10 nicht mehr zu funktionieren: https://github.com/Plushtoast/dsa5-foundryVTT/issues/1013

**Comment by Plushtoast** [comment]
Schon gefixt
