### ISSUE TITLE
Fehler/Probleme bei der AP-Berechnung

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#138]
Bei manueller Eingabe von Talentwerten über das Tippen von Zahlen (z. B. 5 Punkte auf Körperbeherrschung) werden keine AP abgezogen. Die Berechnung funktioniert nur bei der Eingabe über die +/-Tasten, nicht beim direkten Eintippen des Fertigkeitswertes. Aber wenn man nach manueller Zahleneingabe (nehmen wir Körperbeherrschung 5) anschließend 5x auf das Minus klickt, gewinnt man 5x4 = 20 AP hinzu, um den Körperbeherrschungswert wieder auf Null zu bringen. So kann man praktisch "gratis" AP generieren. Könnte entweder die manuelle Zahleneingabe gesperrt werden oder aber die Berechnung dafür aktiviert werden, um derlei Fehlern vorzubeugen?

**Comment by Plushtoast** [comment]
Das ist funktioniert so wie es beabsichtigt ist.
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/FAQ#changing-the-values-in-the-input-field-for-talentcombatskill-and-others-does-not-calculate-the-used-adventure-point-cost

Wenn ich das ein oder andere sperre, dann findet es der nächste Spieler überhaupt nicht.

**Comment by Plushtoast** [comment]
Davon abgesehen,sind auch keine Funktionen vorgesehen um Missbrauch vorzubeugen. Wer mit den ap bescheißen will, kann genauso gut die gesammelten und verbrauchten ap manipulieren.

**Comment by KnoepfchenFulla** [comment]
Ist es denn unmöglich, dass AP berechnet werden, wenn man die Zahl direkt ändert? Das würde das Problem ja sofort lösen.

**Comment by Plushtoast** [comment]
Nein, ist nicht unmöglich, aber dann fehlt der Fallback um den Wert ohne AP Kosten zu ändern. Das möchte aber dann jemand anderes machen und dann braucht man zwei modi. Quasi ein an und ausschalten,was es nur komplizierter macht.
Einfache Regel: +- Steigern. Input felder kein steigern. Man gewöhnt sich sehr schnell dran und nach der charaktererschaffung muss man da sowieso nicht mehr ran.

**Comment by mckee14** [comment]
Ich glaube, es ist an dieser Stelle wichtig zu betonen, dass das DSA5 Modul in Foundry explizit KEIN charaktergenerator sein soll.

Den Einwand kann ich insofern nachvollziehen: Wenn ich den Char fertig habe, kann ein Blick auf die AP zeigen, ob ich auch nichts vergessen habe.

Beim Anlegen eines Chars werde ich auch niemals die +/- Buttons verwenden, da klicke ich mir einen Finger weg (gerade eben 5 Chars aus der Kampagne eingepflegt. Tab, Zahl, Tab, Zahl etc. für die Talente).

Dass es die AP Kosten nicht übernimmt, wenn man direkt ins Feld einträgt, habe ich noch gar nicht bemerkt. Ich dachte, das wäre bloss, um die Limitierung zu umgehen, nicht die Berechnung. Gut zu wissen, dann ignorieren wir die AP Kosten in Foundry komplett und pflegen das extern im rechnenden PDF.

**Comment by UrielMhezzek** [comment]
> Ich glaube, es ist an dieser Stelle wichtig zu betonen, dass das DSA5 Modul in Foundry explizit KEIN Charaktergenerator sein soll.

Das schmälert leider sehr stark den Wert des Moduls. Dann sollte es über kurz oder lang einen Import für einen Charaktergenerator geben (z.B. Optolith oder das PDF).

**Comment by Plushtoast** [comment]
Naja ist jetzt auch nicht lange draußen.
Werden sehen wohin das noch führt. Momentan gibt es andere Themen.
