### ISSUE TITLE
[ActorSheets] Templates mit eindeutigen css-Klassen

### ISSUE THREAD

**Issue by yendors-vtt** [Plushtoast/dsa5-foundryVTT#1387]
Um die Actor-Sheet-Templates via css z.B. für eine mobile Ansicht robuster optimieren zu können, wären eindeutige, beschreibende Klassen an allen Elementen hilfreich.

**Comment by Plushtoast** [comment]
An allen Elementen ist vlt ein bisschen zu viel verlangt.
Etwas spezifischer musst werden.

**Comment by yendors-vtt** [comment]
Ja, da hast du wohl Recht! Ich sammle mal und schreib es dann hier rein.
