### ISSUE TITLE
Doppelte Chat-Nachrichten bei zwei angemeldeten Gamemastern

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1389]
**Describe the bug**
Wenn mehr als ein GM angemeldet ist, werden automatische Chatmeldungen mehrfach gesendet (einmal pro GM). Das betrifft neben den Chatmeldungen des Moduls "Health Estimate" auch automatisch angewendete Effekte wie z.B. von Sonderfertigkeiten und Zaubern

**To Reproduce**
1. Zwei GM gleichzeitig anmelden
2. Sonderfertigkeit "zu Fall bringen" einsetzen
3. Die Meldung, dass das Ziel den Status "liegend" erhält wird doppelt ausgegeben

Alternativ das Modul Health Estimate installieren, die Chatmeldungen einschalten und den Zustand eines Akteurs verändern. Weiß allerdings nicht, ob das ein DSA Problem ist.

**Expected behavior**
Chatmeldungen wird nur einmal ausgegeben

**Comment by Plushtoast** [comment]
Ist das mit dem letzten patch für zaubereffekte immer noch da? Meine das müsste schon erledigt sein

**Comment by Ogrimgro** [comment]
Wenn ihr die Bugs schneller behebt als ich Tickets erstellen kann ist das gemein 🤣 
Ich aktualisiere die Tage mal und gebe Bescheid

**Comment by Plushtoast** [comment]
Hab jetzt hier einiges nochmal geändert im letzten Patch. Bitte berichten, wo es noch hakt.

**Comment by Ogrimgro** [comment]
Bei Health Estimate klappt das es mit den Chat-Nachrichten noch nicht. Könnt ihr da was machen oder kommt das vom Modul selbst?

**Comment by Plushtoast** [comment]
Ich hab bei Health Estimate einen Pull request gemacht um den Fehler zu beheben:

https://github.com/mclemente/healthEstimate/pull/175

Das Problem liegt beim Modul.

Damit betrachte ich das Problem als erledigt. Falls die Änderungen angenommen wird, sollte sich das irgendwann demnächst geben.
