### ISSUE TITLE
Effekt Feld - Fertigkeitspunkte für Talente/Zauber/Rituale/Liturgien/Zeremonien modifizieren auch für Nahkampfwaffen, Fernkampfwaffen

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#1392]
Effekt Feld - Fertigkeitspunkte für Talente/Zauber/Rituale/Liturgien/Zeremonien modifizieren auch für Nahkampfwaffen, Fernkampfwaffen

Siehe dazu auch:
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/de-Effekt_Feld

**Comment by Plushtoast** [comment]
Das Effektfeld war der Vorläufer von Active Effects und ist nun primär nur noch für Kampfsonderfertigkeiten wichtig.
Wird nicht weiter ausgebaut.
Active Effects machens möglich
