### ISSUE TITLE
Breiterer bzw. variabeler Combattracker DSA

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1394]
**Is your feature request related to a problem? Please describe.**
Die Entwicklung eures sehr schönen, eigenen Combattrackers, macht es möglich, primär den Chat-Tab statt des Combattracker-Tabs angezeigt zu lassen und nicht ständig hin und her schalten zu müssen. Natürlich gibt es im Kampf ständig Fälle, in denen man dennoch in diverse Tabs und Fenster gehen muss, was in der Natur der Sache liegt.
Mir ist jedoch aufgefallen, dass der quantitativ mit Abstand häufigste Grund, den Chattab zu verlassen, für mich darstellt, eine Übersicht über de künftige Reihenfolge in der Kampfrunde innerhalb des orginalen Foundry-Kampftrackertabs ist, da ich im DSA-Kampftracker immer nur die nächsten vier Kämpfer sehen kann.

**Describe the solution you'd like**
Wäre die Anzahl der Kämpfer, die im DSA-Kampftracker dargestellt werden, in den Optionen variabel setzbar, könnte man eine für sein individuelles Set-Up sinnvolle Breite wählen. Dadurchkönnte man das herausgehen aus dem Chat-Tab weiter erheblich reduzieren und Kämpfe noch weiter beschleunigen. Besonders könnten Leute mit breiten Bildschirmen profitieren.

**Describe alternatives you've considered**
Sollte eine durch die Nutzer einstellbare Breite zu Aufwendig sein, könnte sich die Frage stellen, ob 5 Kämpfer im DSA-Kampftab tatsächlich die sinnvollste Größe ist, wobei ich eigentlich davon ausgehe, dass ihr diese Breite bereits als optimalen Kompromiss gewählt habt. 

**Additional context**

**Comment by Plushtoast** [comment]
Das soll er ja gerade nicht machen

**Comment by Plushtoast** [comment]
Würde höchstens bei hover ein kleineres fenster anzeigen, welches nochmal 10 züge zeigt. mit kleineren bildern und weniger information

**Comment by Zonenpenner** [comment]
> Das soll er ja gerade nicht machen

Was soll er nicht machen? In der Breite variabel sein? Ich nehme an, dass ein in der Breite variabler Kampftracker wieder andere Probleme nach sich zieht, an die ich schlicht nicht gedacht habe.

> Würde höchstens bei hover ein kleineres fenster anzeigen, welches nochmal 10 züge zeigt. mit kleineren bildern und weniger information

Da ich die Informationen sehr schätze, würde ich dies vermutlich nicht nutzen. Für mich müsstest du dir die Arbeit also bitte nicht machen.

Wenn die Breite des Combattrackers, so wie sie ist, fest gesetzt sein soll, habt ihr, so denke ich, schon eine gute Lösung und der Vorschlag könnte von mir aus dicht gemacht werden.

**Comment by Plushtoast** [comment]
vlt kannst du noch genauer beschreiben, was das problem ist
warum musst du immer zum combat tracker wechseln

**Comment by Zonenpenner** [comment]
Problem ist vielleicht etwas übertrieben...

In Kämpfen mit vielen Beteiligten, besonders wenn ein generischer Typ (sagen wir mal Sumpfranzen) etliche male dabei ist, verliert man (alos ich) als Spielleiter schnell die Übersicht, wo man sich innerhalb der Kampfrunde befindet, wenn man "nur" 5 Kämpfer im DSA-Tracker sieht. Dann kommt es vor, dass dort ausschließlich 7 Sumpffranzen, die alle INI 16 erwürfelt haben, zu sehen sind und ich nicht mehr 100% sicher bin, ob alles korrekt abgehandelt wird. Sollte bei korrekter Anwendung nicht vorkommen, ist in der Praxis zumindest bei mir aber öfter der Fall. Ich denk mir öfter auch Züge von NPCs etwas vorraus, damit ich nicht erst mit dem Denken beginnen muss, wenn diese dran sind. Dazu ist es ebenfalls praktisch einen größeren Überblick über kommende Züge und deren Reihenfolge zu haben. Dies sind die Gründe, aus denen ich öfters in den großen Standardtracker umschalte.

Daher dachte ich, dass es doch schön wäre, wenn man in den Optionen festlegen könnte, dass, sagen wir z.B. 15 Kämpfer angezeigt werden und der DSA Combattracker dann halt 3 mal so lang ist. Hat man wenig Platz auf seinem Bildschirm, lässt man halt weiterhin die 5 angezeigten eingestellt.

Dies sind aber tatsächlich kleinere Luxusproblemchen. Wenn eine in den Optionen einstellbare Größe des Trackers also einen großen Rattenschwanz anderer Probleme nach sich zieht oder einen großen Programmieraufwand bedeutet, tabe ich gerne bei großen Kämpfen gerne weiterhin ab und zu in den Standardtracker. In vielen Kämpfen reicht der DSA-Tracker auch vollkommen aus.

**Comment by Plushtoast** [comment]
Ne das wär relativ einfach möglich.

Die ursprüngliche Idee is aber genau das Gegenteil.
Es soll so viel wie möglich unnötige Infos ausgeblendet werden, da man sonst einfach nur ne ewige Liste hat, die den ganzen bildschirm versperrt, und es interessiert halt nicht was oder wann die was machen.

ich denk mal drüber nach

**Comment by mckee14** [comment]
Man kann den normalen kampftracker auch einfach per rechtsklick auf das
schwertsymbol im menü auskoppeln. dann ist er dauernd sichtbar und man kann
im menü wieder auf den chat stellen.

Zonenpenner ***@***.***> schrieb am Mi., 29. März 2023, 14:31:

**Comment by Zonenpenner** [comment]
> 

Stimmt, dann wäre es aber leider sinnvoll, den sehr, sehr geilen DSA-Combattracker auszuschalten, damit ich nicht zu viel quatsch auf dem gleichen Bildschirm habe. Und das wäre ja schade drum. Ist aber auch ne Lösung. 
Den DSA Combattracker fand ich mit mehr Kämpfern halt so geil, weil ich einen großen 21:7 Bildschirm habe und die Leiste der Kämpfer verläuft dann ja Horizontal und nicht Vertikal, wie der Standard-Tracker.
Ist wie gesagt ein Luxusproblem, dass nicht zwangsläufig nach einer Lösung durch die Entwickler schreit. Wenn es sich jedoch relativ leicht bewerkstelligen lässt, wäre es ja eigentlich ganz geil, die Wahl, wieviel Platz der Tarcker einnehmen und wie Breit dieser sein soll, den Usern zu lassen.
