### ISSUE TITLE
Umsetzung von Waffenvor- und Nachteilen als Automatisierung (Fokusregel)

### ISSUE THREAD

**Issue by ShiNoYuki5** [Plushtoast/dsa5-foundryVTT#1396]
**Is your feature request related to a problem? Please describe.**
Bei Charakteren die viele Waffen haben (Rondrageweihte etc.) wird öfters mal die Waffe gewechselt, jedoch werden die Waffenvor- und Nachteile nicht mit einberechnet was ziemlich störend ist :/

**Describe the solution you'd like**
Über Effekte oder Macros die Vor- und Nachteile miteinberechnen.

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by Plushtoast** [comment]
Duplicate of #658 

Haben wir vor, aber nicht s obald. Das ganze Geraffel ist teilweise irre aufwendig zum Umsetzen. da ist Rondrakamm noch die ausnahme
