### ISSUE TITLE
Journalbrowser öffnet in falscher Standardschriftgröße 

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1398]
**Describe the bug**
Seit dem die Schrift im Journalbrowser über den Button oben rechts in ihrer Größe änderbar ist (sehr geile Idee übrigens), öffnet sich der DSA-Journalbrowser mit den Regelwerken etc. bei mir standardmäßig in Schriftgröße 16, statt Default. 

**To Reproduce**
Öffne den Journalbrowser über das Macro oder direkt über das DSA-Menü oder sonstwie.

**Expected behavior**
Die Basiseinstellung sollte Default sein.

**Screenshots**

**Comment by Plushtoast** [comment]
Hm ehrlich gesagt ist die geplante Basiseinstellung der letzte Wert der eingestellt war, nicht default

**Comment by Zonenpenner** [comment]
> Hm ehrlich gesagt ist die geplante Basiseinstellung der letzte Wert der eingestellt war, nicht default

Das wäre auch noch sinnvoller als standardmäßiges Default. Leider öffnet er mir die Journals IMMER in Schriftgröße 16, egal welche Größe ich über den neuen Button zuvor ausgewählt hatte.
