### ISSUE TITLE
Adding Waffenlos as weapon

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#140]
So you can equip it and have modifiers working for these spectacular bar brawls.

**Comment by Plushtoast** [comment]
There are three buttons on the combat tab next to "Nahkampfwaffen/Meleeweapons".
Is this what you are looking for or is it about the modifiers.

**Comment by mckee14** [comment]
It just feels kinda wrong to not have the "waffenloser Angriff" as a weapon. And imagine *tension* - you play a char with no arms! ;-)

Your comment made me test it, and the modifiers are calculated, so it's not a must-fix. 

Personally, I would prefer to have it as a weapon, especially when you don't see that button and start searching the compendium. And you would be able to change it per character, for whatever reason.

Can be closed I guess.
