### ISSUE TITLE
Initiative-Sortierung

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#1400]
Hallo, 

Foundry scheint bei der Initiativeberechnung/Sortierung der Kampfteilnehmer einen Schritt zu überspringen.

Regeltext zur INI-Bestimmung (GRW) als Referenz: 

***
Um festzustellen, in welcher Reihenfolge die Beteiligten handeln, wird die Initiative bestimmt. Diese gilt bis zum Ende des Kampfes und nur besondere Situationen verändern den Wert noch (z.B. der Zauber Axxeleratus). Die Initiative erhält man, indem man einen W6 würfelt und den Initiative-Basiswert hinzuaddiert.

[...]

Der Beteiligte mit der höchsten Initiative darf als Erster im Kampf handeln. Haben zwei Beteiligte die gleiche Initiative, handelt der von ihnen zuerst, der den höheren Initiative-Basiswert hat. **Sind diese ebenfalls gleich, würfeln beide einen W6.** Derjenige mit dem höheren Ergebnis darf vor dem anderen handeln.

**Bei Gleichstand wiederholt man den Wurf so lange, bis eine Entscheidung gefallen ist.** Die Initiative gilt für den gesamten Kampf und wird nicht jede Kampfrunde neu ausgewürfelt. Nur besondere Situationen wie der Zustand Belastung kann die Initiative noch verändern.

***
 
Den fett markierten Teil scheint Foundry nicht umzusetzen – zumindest wirkt es von außen betrachtet eher so, als würden Charaktere mit gleichem INI-Basiswert und gleichem ersten W6 in der Reihenfolge sortiert werden, in der die INI gewürfelt wurde (oder potenziell alphabetisch?), ein zusätzlicher W6 zur Entscheidung bei Gleichstand ist nicht erkennbar.

Im Screenshot:

![2023-04-03_10-15-21](https://user-images.githubusercontent.com/79639045/229476626-03116c2f-575e-4a6a-8a78-2320a5a5bf4c.jpg)

**Versions:**
- Foundry Version: aktuell
- DSA/TDE version: aktuell

**Comment by Plushtoast** [comment]
Es gibt eine Grenze an Nebensätzen die wir abarbeiten können und wollen

**Comment by Zonenpenner** [comment]
> Es gibt eine Grenze an Nebensätzen die wir abarbeiten können und wollen

Total nachvollziehbar.

Wovon hängt die Reihenfolge denn in der jetzigen Umsetzung ab?

**Comment by Plushtoast** [comment]
Wie Foundry das handhabt, weiß ich selbst nicht.

Was möglich wäre ist es an den Wurf eine weitere Zufallszahl von 1-100 oder 1-1000 anzuhängen
also zb 18.13151 und die dann nur per hover anzuzeigen
die lösung mit den 1w6 ist total umständlich insbesondere je mehr token am kampf beteiligt sind.
mache ich das aber so, beschwert sich vermutlich jmd, dass das nicht korrekt ist

**Comment by KnoepfchenFulla** [comment]
Hm, verstehe. Ich verstehe auch völlig, dass DSA ein derartig kleinteiliges System ist, dass man da niemals alle Fokus-, Optional- und Sonstwiesubregeln umsetzen kann und will, weil der Aufwand-Nutzen-Faktor einfach nicht gegeben ist (irgendwelche obskuren Items aus Regionalrüstkammern, die einem bei Bedingung XY einen Teilbonus auf Eigenschaft ABC geben und solches Zeug). Bei so was "Normalem" wie der Initiative hat es mich einfach überrascht, dass Foundry das irgendwie anders als "normal" sortiert hat in unserem letzten Kampf (nachdem meine Spieler plötzlich hinterfragt haben, warum denn der Antagonist trotz exakt gleicher INI eigentlich vor ihnen dran ist, und wir nur den möglichen Bug als Erklärung identifizieren konnten). Das ist ja aber auf Nutzer- bzw. Meistersite verhältnismäßig einfach lösbar, dadurch, dass sich die Initiative nachträglich manuell anpassen lässt, wenn man um die Situation weiß. 

Deine Lösungsüberlegung ginge für mich problemlos, aber ja, vermutlich passt das nicht für alle.

An dieser Stelle noch mal danke für die Umsetzung der Grimorum-Zauberänderungen in Foundry, das hat meine Gruppen alle sehr glücklich gemacht.

**Comment by Zonenpenner** [comment]
Also ich denke das mit der Zufallszahl wäre absolut in ordnung, da es ja nur darum geht, dass bei Initiative-Gleichstand die Reihenfolge zufällig bestimmt wird.  Ob das jetzt mit einem W6 oder einem W1000 erfolgt ist eigentlich Hupe.

**Comment by Plushtoast** [comment]
Das macht sinn. Die w6 Methode ist mindestens umständlich
