### ISSUE TITLE
maybe split master menu tracked actors in players & dramatis personae

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1403]

**Comment by Zonenpenner** [comment]
Hi, wenn ich kurz kommentieren und eine eventuell sinnige Idee einbringen dürfte:

Falls das master Menu gesplittet wird wäre es irgendwann zukünftig toll, falls es einen dritten Reiter für tierische Begleiter geben könnte. Eine größere, berittene Gruppe hat echt oftmals nen waren Zoo aus Reit-, Pack, und Begleittieren dabei. Nimmt man diese jedoch in das tolle, sehr praktische Meistermenu auf, spammen die das unnötig zu, besonders da die in vielen Situation nicht direkt dabei oder irrelevant sind. Deswegen verzichte ich darauf, um die Übersichtlichkeit zu erhöhen. In anderen Situationen wäre es jedoch total super das Viehzeugs gesammelt direkt über das Master Menu erreichen zu können. 

Das hat echt nicht so eine hohe Prio, dass ich dafür ein eigenen Issue aufgemacht hätte, aber ich dachte ich bringe das hier ein, wenn eh die Möglichkeit geschaffen wird das Master Menu mit Unterkathegorien zu versehen.

**Comment by Plushtoast** [comment]
dann wäre die frage ob man gleich generell custom tabs die man selbst benennen kann dafür braucht

**Comment by Zonenpenner** [comment]
Das wäre natürlich der Oberhammer!

So könnte man z.B. die die Gruppe begleitenden NPC, die Dramatis Personae eines spezifischen Szenarios oder Ortes und noch eine in einem Abenteuer oder Kampagne agierende Antagonistengruppe getrennt über das Meistermenü überwachen und steuern. Wäre ziemlich geil.
