### ISSUE TITLE
Falsche AP-Anzahl für die Spezies Elf

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1411]
Für die Spezies Elf werden derzeit 60 AP veranschlagt, es dürften aber nur 30 AP sein (18 AP für die Spezies lt. GRW und 12 für die dringend empfolenen Vor-und Nachteile). Die zusätzlichen 30 AP resultieren aus der nochmaligen Berechnung für die automatischen Vorteile Zauberer (25 AP) und Zweistimmiger Gesang (5 AP).

- Foundry-Version 10.291
- DSA-System-Version 4.3.7
- DSA-Modul GRW 4.3.0 und Av. Magie 2 4.2.2

**Comment by Plushtoast** [comment]
Woher weißt du dass man das nicht extra bezahlen muss. Ich kann das der Beschreibung nicht entnehmen.

Spezies kostet
Vorteile ebenso

**Comment by Plushtoast** [comment]
Außerdem gibt es in der Beschreibung das hier.

Verbrauchte AP für Vorteile/Nachteile: Vorteile: 30 AP, 
Nachteile 0 AP

**Comment by sirgawain111** [comment]
Das "verbraucht" bezieht sich auf die Obergrenze von max. 80 AP für Vorteile.

Die automatischen Vorteile der Elf-Spezies im Wert von 30 AP bezahlt man durch die Spezies-Kosten von 18 AP und den gegenüber den kostenlosen Spezies Mensch und Halbelf um 3 geringeren LeP-Grundwert (was dem Nachteil "Niedrige Lebenskraft" und damit einem Gegenwert von 12 AP entspricht).

Siehe auch: Tabelle auf S. 49 des GRW.

**Comment by Plushtoast** [comment]
Ahja.. als ob elfen nicht schon op genug wären

**Comment by sirgawain111** [comment]
Aha... Glückwunsch zu dieser Antwort. Echt reflektiert.
