### ISSUE TITLE
"Mounted Charge" special ability has 0 AP-value and has "Mounted Combat Kampf" as a Requirements

### ISSUE THREAD

**Issue by JanikBastien** [Plushtoast/dsa5-foundryVTT#1416]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**
- Foundry Version
- DSA/TDE version
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Mounted Combat Kampf is wrong. The rest is working as intended

Mounted Charge is part of Mounted Combat and can only be obtained if you take mounted combat (it should also be added automatically then)
Had to separat this in multiple special abilities to make the automation work.
