### ISSUE TITLE
Gesundheitssteigernde Essenz - Item Text und Funktion falsch

### ISSUE THREAD

**Issue by ecosquirrel-dev** [Plushtoast/dsa5-foundryVTT#1417]
Item @UUID[Compendium.dsa5-armory2.armory2equipment.Loouqt2HNw0zdCEk]{Gesundheitssteigernde Essenz} ist al Heilmittel definiert, beschreibt aber eine Peraine Storchenmaske

**Comment by Murm3lt13r** [comment]
Gesundheitssteigernde Essenzen haben keine eigene Beschreibung und werden nur in Kombination mit der Storchenmaske verwendet.
Beschreibung angepasst.
