### ISSUE TITLE
Missing special abilities from "Kodex der Magie"

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-foundryVTT#1420]
**Is your feature request related to a problem? Please describe.**
I am missing special abilities like "Auxiliator" or "Gefäße der Macht" - I have not checked all but these are missing (at least)

**Describe the solution you'd like**
Please add these to the study room :)

**Describe alternatives you've considered**
Could be added to pother publications :)

**Additional context**
none

**Comment by Plushtoast** [comment]
ja kommt vermutlich in die studierstube
