### ISSUE TITLE
Wunsch: Geheimnisfunktion auch bei Akteur benutzbar

### ISSUE THREAD

**Issue by HenrikSonntag** [Plushtoast/dsa5-foundryVTT#1429]
Ich würde mir wünschen wenn ich die Geheimnisfunktion auch bei den Hintergundinformationen der Akteure benutzt werden kann.
So kann ich die Informationen welche in dem Kästen bei den fertigen Abenteuern sind aber den Spielern nichts angeht einfach markieren und als Geheimnis anlegen.

**Comment by Plushtoast** [comment]
Was genau soll da fehlen?
Die gm notes gibt es auch noch.

**Comment by HenrikSonntag** [comment]
Aktuell ist es ja nicht möglich den Text der bei z.B. Hintergrundinformationen steht zu kopieren und als Geheimnis zu markieren um ihn dann den Spieler "anzuzeigen" wenn er die Hintergrundinformationen erfahren hat.

Ich gebe meinen Spieler immer so sobald sie einen NPC gesehen haben Beobachterrechte an dem NPC. Wenn dann unter Hintergrundinfos schon sehr viel drinsteht was die eigentlich noch garnicht wissen können dann ist das schade.

Ja aktuell schneide ich den Text immer aus und packe ihn unter GM Notes. Das ist aber sehr umständlich und ich muss ihn so auch wieder einfügen wenn die Spieler den entsprechenden Hintergrund erfahren haben.
________________________________

**Comment by Plushtoast** [comment]
ah das hab ich eh schon für v11 geändert

**Comment by HenrikSonntag** [comment]
Ah vielen Dank.
________________________________
