### ISSUE TITLE
Rüstung bei Angriff und / oder TP (SP) ignorieren

### ISSUE THREAD

**Issue by Gunthgard** [Plushtoast/dsa5-foundryVTT#143]
Hallo.

Wäre es möglich das man ein Auswahlfeld beim Angriff schafft, dass der RS nicht schützt wenn TP erzeugt werden und somit direkt als SP abgezogen werden können ?

z.B. Bei der Fähigkeit "Angriff auf ungeschützte Stellen"

Grüße

**Comment by mckee14** [comment]
Generell eine Möglichkeit, die TP über SF zu modifizieren. Beispiel "Zu Fall bringen": Anstatt den regulären TP verursacht man 1d3 TP, zusätzlich den Status "liegend".

(Wenn durch geglückte Angriffe auch noch Stati verteilt werden können, kann man viele SF korrekt abbilden)

**Comment by Plushtoast** [comment]
Erstmal wird es nur die Möglichkeit geben per Contextmenü SP abzuziehen.
