### ISSUE TITLE
[v11] Token Rename unlinked Tokens erzeugt Fehler

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#1434]
**Describe the bug**
Wird die Einstellung "Prepend Adjective to name of Unlinked Tokens?" verwendet, kann der Token nicht auf die Szene gezogen werden. Es erscheint ein Fehler in der Console.

**To Reproduce**
1. Erzeuge einen Actor mit unlinked token
2. Aktiviere die Adjective Funktion
3. Ziehe Actor auf Szene

**Expected behavior**

**Screenshots**
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/44c4f5b8-c667-467c-b339-0eb35d68a4bf)
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/62cfd842-a3b0-4300-90c6-0f0e10ea68b8)

**Versions:**
- Foundry Version 11.299
- DSA/TDE version 5.0.1

**Comment by Plushtoast** [comment]
Sieht so aus, als ob das atm nur auf english geht. Ich schreib nen foundry error report

**Comment by Plushtoast** [comment]
Das geht in der neusten Foundry version jetzt. Allerding scheinbar nur mit Token neu aus nem Compendium...kp
