### ISSUE TITLE
"Blutend" führt zur Chatnachricht "CHATNOTIFICATION.applyBleeding"

### ISSUE THREAD

**Issue by Lyynix** [Plushtoast/dsa5-foundryVTT#1435]
**Describe the bug**
Das Hinzufügen von "Blutend" führt zur Chatnachricht "CHATNOTIFICATION.applyBleeding". Der Akteur bleibt ohne Statuseffekt.

**To Reproduce**
Einfach Statuseffekt "Blutend" hinzufügen. Wie ist nach meinen Tests irrelevant, ich habe es mit der Tokenhotbar versucht und übers Charaktersheet

**Expected Behavior**
Erwartet hätte ich den Statuseffekt "Blutend" auf dem Charakter, optimalerweise mit integrierter Funktion

**Versions:**
- Foundry Version: 11.299 (auch 10.291)
- DSA/TDE version: 5.0.3 (auch 4.3.8 & 4.3.9)

**Additional context**
Ich habe den Bug ursprünglich auf meiner Kampagne (FVT 10.291, DSA5 4.3.8) entdeckt. das Update 4.3.9 hat den Bug nicht entfernt.
Später habe ich den Bug auf einer Neuinstallation (FVT 11.299, DSA5 5.0.3) ohne Module (Außer die DSA5 Module Bestiarium, Kompendium I + II, GRW, Glue and  Hammer, Master's Workshop) reproduziert

**Comment by Lyynix** [comment]
Der Bug ist in 5.0.4 auch vorhanden

//nicht beachten, wenn das so sein soll

**Comment by Plushtoast** [comment]
module updaten

**Comment by Lyynix** [comment]
Oh man, kann man auch selber draufkommen... danke xD
