### ISSUE TITLE
FVTT v11 und Multilevel Tokens - Betrifft nicht den DSA Core aber div. Module

### ISSUE THREAD

**Issue by hnsstrk** [Plushtoast/dsa5-foundryVTT#1442]
**Not a bug nor a feature**
Bei den Multilevel Tokens hat sich halben bis dreiviertel Jahr auf Github scheinbar nichts mehr getan.
Keine Antworten auf Issues oder Commits, etc. 
Ob es eine Portierung auf FVTT v11 geben wird, lässt sich nicht erst einmal nicht erkennen.
Da es einige DSA5 Module die Multilevel Token nutzen könnte das ggf. zu Problemen führen.

Ich dachte, ich hätte auch eine Fehlermeldung gesehen. 
Deshalb hatte ich überhaupt erst auf Github nachgeschaut.
Allerdings bekomme ich nun keinen Fehler mehr angezeigt und kann es auch nicht nachstellen.
Es scheint also erst einmal alles zu funktionieren.

**Comment by Plushtoast** [comment]
Ja weiß jetzt nicht was ich darauf antworten soll.
Wenn es nicht aktualisiert wird, wovon ich nicht ausgehe, fliegt die Funktionalität raus.
WIr hatten schon mal ein Problem mit Dritt Modulen und es is einfach net drin bei jedem Foundry Sprung alles neu zu machen.

**Comment by hnsstrk** [comment]
> Ja weiß jetzt nicht was ich darauf antworten soll. Wenn es nicht aktualisiert wird, wovon ich nicht ausgehe, fliegt die Funktionalität raus. WIr hatten schon mal ein Problem mit Dritt Modulen und es is einfach net drin bei jedem Foundry Sprung alles neu zu machen.

Nachvollziehbar, bzw, IMHO sogar die richtige Entscheidung.

**Comment by Plushtoast** [comment]
Mit v12 sollte sich eine alternative ergeben.

**Comment by Plushtoast** [comment]
Die Alternative deckt das problem leider nicht ab, aber ich hab nen pull request für multilevel für v12 gemacht und werde wahrscheinlich selbst noch ein entsprechendes modul rauslassen.

es lebt weiter
