### ISSUE TITLE
Bogen / Keine Reaktion trotz treffer

### ISSUE THREAD

**Issue by Salamandris** [Plushtoast/dsa5-foundryVTT#1456]
Ich habe bei einem Elfenspieler das Prolem das ein erfolgreicher Angriff mit dem Elfenbogen / Bogen beim getroffenen keine Reaktionsmöglichkeit hervorruft. Schaden etc. kann nicht ermittelt werden. (Habe Bogen, Elfenbogen und Langbogen getestet.

Bediene ich den Char als GM funktionieren die Mechaniken ganz normal. Scheint im Spieler begrünet zu sein. 

LG

Alex

Problem scheint für den Augenblick gelöst zu sein. Tritt augenscheinlich nur Im Firefox auf. Im Chrome ist das Problem nicht mehr da.

**Comment by zoidable** [comment]
Wir haben das in unserer Runde auch schon öfter beobachtet: Angriff als GM ermöglicht Reaktion, Angriff als Spieler teilweise nicht. Leider kann ich das auch nicht konkretisieren oder eingrenzen, unter welchen Umständen das auftritt.

**Comment by Plushtoast** [comment]
Jo ich kanns auch nicht einkreisen.
Liegt nicht am Browser und kommt nur manchmal vor. Ich hab momentan keinen Verdacht woran es liegen kann.
Lässt sich nicht rekonstruieren.
