### ISSUE TITLE
DSA5 Commands wie /pay etc. aus dem Journal verfügbar machen

### ISSUE THREAD

**Issue by ecosquirrel-dev** [Plushtoast/dsa5-foundryVTT#1462]
[[/r 1d3]] im Jornal führt zu einem Wurf.

[[/pay 20]] wird im Journal nicht als Funktion erkannt

**Comment by Plushtoast** [comment]
Ich glaub das würde quasi niemand benutzen

**Comment by Miccolo02** [comment]
Das würde ich nicht sagen. Ich würde das sehr häufig einsetzen. Aus APs verteilen fände ich gut dann könnte ich ans Abenteuer ans ende schonmal was vorfertigen.
