### ISSUE TITLE
Kampfsonderfertigkeit mit + auf Ausweichen gibt immer permanenten Bonus.

### ISSUE THREAD

**Issue by Violettdragon** [Plushtoast/dsa5-foundryVTT#147]
Hiho, ich bins nochmal.

Es gibt Kampfsonderfertigkeiten die nur bei aktiven nutzen +PA oder +AW geben.

Beispiel: Fedorino-Stil bei nicht benutzen einer Kampfsonderfertigkeit +2 PA oder +2 AW.
Die +2 AW wird sofort auf den Charakterwert eingerechnet.

Wenn man auf den Parade-Würfel klickt, wird der Fedorino-Stil als Auswahlmöglichkeit angezeigt. 
Der Ausweich-Pfeil hat diese Auswahlmöglichkeit nicht.

Verteidigungshaltung ist im DSA5-CORE ohne Effekt. Vermutlich wegen diesem Problem.

**Comment by mckee14** [comment]
Workaround: Den Kampfstil oder Gegenhalten als Rüstung anlegen mit 0 RS. Dann die PA, AW usw. als Effekt in der Rüstung eintragen.

Für Gegenhalten würde ich z.B. +4 AW, +4 PA, - XY* AT hinterlegen  (*= Aktueller AT Wert des Charakters mit seiner Hauptwaffe)

Dann kann man die Werte einfach temporär aktivieren, indem man diese Rüstung anzieht (aktiviert).
Durch die Abzüge auf AT sieht man auch schnell, dass man gar nicht angreifen kann/darf, wenn man die Verteidigungshaltung aktiv hat.

Just my 2 cents

**Comment by Plushtoast** [comment]
Ab Patch kann man im Kampffertigkeit Feld der Sonderfertigkeit "Ausweichen" hinzufügen.
Dann wird der +PA Wert beim Würfeln auswählbar.

Der AW Wert bleibt permanent.
