### ISSUE TITLE
Fehler Charakterbogen öffnet sich nicht

### ISSUE THREAD

**Issue by TarionT** [Plushtoast/dsa5-foundryVTT#1470]
**Describe the bug**
Beim Klicken Anklicken eine Acteursim Verzeichnis oder dem Canvas geht das Charakterfesnter nicht auf.
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/85405731/a69d2aca-15ca-4082-a85d-4982f6344630)

**Versions:**
- Foundry Version V11 306
- DSA/TDE version 5.0.8

**Comment by Plushtoast** [comment]
Hast du die beta 5.1 installiert?

**Comment by Plushtoast** [comment]
Irgendwie?

**Comment by Plushtoast** [comment]
Ah kacke da ist ein teil des nächsten patch mitgekommen

**Comment by TarionT** [comment]
;) Soll vorkommen

Danke für die tolle Arbeit
