### ISSUE TITLE
Finish for character creation does not operate

### ISSUE THREAD

**Issue by JanikBastien** [Plushtoast/dsa5-foundryVTT#1472]
**Describe the bug**
When completing the character creation process, pressing the "finish" button has no effect. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![Difficulté Finish](https://github.com/Plushtoast/dsa5-foundryVTT/assets/92388150/7a6c3865-16ea-4661-8962-f7c22cc53688)

**Versions:**
- Foundry Version 11.307
- DSA/TDE version 5.0.9
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Can You open the console (F12) and Screenshot whatever error you can see when you press finish
