### ISSUE TITLE
Sturzschaden-Wurf aus dem Journal im Chat anfordern

### ISSUE THREAD

**Issue by yendors-vtt** [Plushtoast/dsa5-foundryVTT#1474]
Es wäre cool, wenn man ähnlich wie @Rq[Talent] einen Sturzschaden-Wurf im Chat anfordern könnte und dafür für das Journal einen entsprechenden Enricher hätte.

**Comment by Plushtoast** [comment]
Mit den ganzen enrichern is irgendwann das problem dass die meisten sinnlos Performance fressen und nie benutzt werden. Ich weiß jetzt net wie effizient regex da is, aber die möglichen enricher sind viele und auch leicht eingebaut. 
Deswegen bin ich mir nicht sicher ob es super klug is mehr einzubauen

**Comment by yendors-vtt** [comment]
Ah, an Performance hab ich gar nicht gedacht. Guter Einwand. Aber wäre es denn denkbar, den Rq-Enricher ggf. dahingehend zu erweitern? Also z.B. Rq[Sturzschaden]?

**Comment by Plushtoast** [comment]
Das hab ich wohl schon mal eingebaut (existiert schon):

@Rq[Sturzschaden  3]

**Comment by yendors-vtt** [comment]
Ahh, nice! Danke!
