### ISSUE TITLE
Wenn Ausrüstung verschoben wird .... wenn möglich automatisch löschen ?

### ISSUE THREAD

**Issue by Gunthgard** [Plushtoast/dsa5-foundryVTT#148]
Hallo, ich mal wieder ;)

Wenn ein Sc oder NSC Ausrüstung aus seinem Inventar an einen anderen Ort legt, z.B. einem Pferd, Wagen oder anderen Ort, wäre es wünschenswert wenn es eine Möglichkeit gäbe das sich die besagte Ausrüstung aus dem Inventar eigenständig (oder per Shift + Klick beim ziehen) löscht.

Liebe Grüße

**Comment by Nyhles** [comment]
Es wäre gut wenn diese Option dann in den Spieleinstellungen ein- oder ausschaltbar wäre.
Ich fände es nicht so gut, wenn immer beim Ausrüstung verziehen der Einträge automatisch gelöscht werden.
Aber wenn es in den Optionen ein-/Ausschaltbar ist oder über eine Tastenkombination (Shift+Drag&Drop) abläuft wäre es eine tolle Möglichkeit.

**Comment by Plushtoast** [comment]
Alt + Drag ab Patch
