### ISSUE TITLE
Improve mass add/remove condition dialog a little

### ISSUE THREAD

**Issue by theTPH** [Plushtoast/dsa5-foundryVTT#1482]
**Is your feature request related to a problem? Please describe.**
Einen Zustand auf mehrere oder alle Mitglieder einer Heldengruppe anzuwenden ist sehr umständlich.
Jeder Held muss einzeln ausgewählt und der Zustand aktiviert werden.

**Describe the solution you'd like**
Eine Integration in das Meister Menü ähnlich der Funktionen "Bezahlung erhalten", "Ausnehmen" etc. wäre ideal. Zustände könnten dann für einzelne Mitglieder oder die ganze Gruppe auf einmal aktiviert und deaktiviert werden.

**Describe alternatives you've considered**
Eine Implementierung als Makro wäre auch möglich aber nicht ganz so elegant. 

**Additional context**
None

**Comment by Plushtoast** [comment]
wenn du token hast kannst du alle markieren und über die tokenhotbar allen gleichzeitig einen status hinzufügen:

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/347b63ba-78ed-401e-83e7-79dab14476c4)

**Comment by theTPH** [comment]
AAAAAHHhhhh die Leiste hab ich zugegeben bisher größtenteils ignoriert :D 
Gut das ist auch ne vernünftige Lösung Danke :) 
Die Zustände wieder Entfernen kann ich darüber allerdings nicht oder?

**Comment by Plushtoast** [comment]
Nur einzeln. Das könnte man aber einbauen. Meistermenü is das aber glaub nicht notwendig
