### ISSUE TITLE
DSA Kampfträcker schaltet sich immer an 

### ISSUE THREAD

**Issue by HenrikSonntag** [Plushtoast/dsa5-foundryVTT#1485]
Der DSA Kampftracker schaltet sich immer von alleine in den Einstellungen an.
Neuste DSA Version ( war glaube ich aber vorher auch schon so)

**Comment by Plushtoast** [comment]
Kann ich nicht nachvollziehen. Unter welchen Umständen passiert das

**Comment by Plushtoast** [comment]
Ich denke du hast eher Problem mit den Client Settings.

Foundry speichert client spezifische einstellungen per Browser und PC ab, wenn du dor  die Cookies löscht oder einen anderen pc verwendest sind die Einstellungen auch weg und müssen neu vorgenommen werden.

**Comment by HenrikSonntag** [comment]
Ah tatsächlich lag daran das Firefox die Cookies immer automatisch löscht. Danke
