### ISSUE TITLE
iOS Anzeige Problem des Szenen Hintergrund

### ISSUE THREAD

**Issue by peikert** [Plushtoast/dsa5-foundryVTT#1487]
Liebe Devs,
Bei mir in der Runde haben die MacOS Nutzer Probleme bei der Anzeige der Szenen. Die Map werden einfach nicht geladen und der Hintergrund bleibt weiß. Ein eventuelle Grid wird angezeigt und die UI auch. Es wurde Safari wie auch Chrome ausprobiert und wurde mit iPad und Macbook beobachtet. Das Problem trat erst nach dem update auf DSA 5.1.0 und Foundry 11.3.0 aufgetreten. Habt ihr eine Idee ob das an der Einstellung liegen kann oder wurde euch so ein Bug schonmal berichtet?

Beste Grüße

![Bildschirmfoto_2023-09-08_um_23 25 01](https://github.com/Plushtoast/dsa5-foundryVTT/assets/14272065/060fed4d-7029-4785-9c1f-5816116a5a64)

**Comment by Plushtoast** [comment]
Die neuste foundry version ist da wohl nicht mehr mit Safari kompatibel. Es ist bei foundry gemeldet und sie wollten sich das auch anschauen, aber der Support von safari ist immer etwas schwierig.

Folgende zwei Möglichkeiten gibt es momentan soweit ich weiß:
Auf dem mac kann ein alternativer Browser verwendet werden zb chrome. Das hilft aber nicht auf dem ipad.

Ode den performance mode in den settings auf Minimum stellen, das sollte bei ipad und mac Funktionieren.
