### ISSUE TITLE
Zeitlich begrenzter Statuseffekt nach Migration nicht mehr löschbar

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1488]
**Fehlerbeschreibung**
Wenn zum Zeitpunkt der Migration ein zeitlich begrenzter Statuseffekt bei einem Akteur aktiv ist (z. B. Armatrutz oder Axxeleratus), kann dieser Effekt nach der Migration nicht mehr aus dem Charbogen entfernt werden.

**Versionen:**
- Foundry Version 11.308
- DSA-Version 5.1.1
- Core-Modul Version 5.1.1

**Comment by Plushtoast** [comment]
Kannst du mir den betroffenen char hier anhängen

**Comment by sirgawain111** [comment]
Sorry, hatte mich verguckt.
Es handelt sich nicht um einen aktiven, zeitlich begrenzten Statuseffekt, sondern um eine Zaubererweiterung (ohne Statuseffekt), die nach der Migration als nicht löschbarer Statuseffekt im Charbogen auftaucht und auch nicht verschwindet, wenn man die entspr. Zaubererweiterung aus dem Charbogen löscht.

(Dateiendung in txt umbenannt, weil json hier nicht akzeptiert wird)
**Char vor Migration**
[fvtt-Actor-vana-straininger-(copy)-foj5dQ9QM5DE08vy-vor-Mig.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/12567998/fvtt-Actor-vana-straininger-.copy.-foj5dQ9QM5DE08vy-vor-Mig.txt)

**Char nach Migration**
[fvtt-Actor-vana-straininger-HokY2sooYD7vC8mq-nach-Mig.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/12568001/fvtt-Actor-vana-straininger-HokY2sooYD7vC8mq-nach-Mig.txt)

**Comment by Plushtoast** [comment]
Denke mal 5.1.2 hat das schon geregelt. geht bei mir.
nochmal migrieren

**Comment by Plushtoast** [comment]
vor allem zauber migrieren

**Comment by sirgawain111** [comment]
Jou, funktioniert mit 5.1.2 tatdellos. Danke für das Update!
