### ISSUE TITLE
Talent Probe mit Erschwernis wird falsch berechnet

### ISSUE THREAD

**Issue by lWFDl** [Plushtoast/dsa5-foundryVTT#149]
**Describe the bug**
Bei einer Talent-Probe  mit einer Erschwernis, wird die Erschwernis nicht nur vom den Würfelwürfen abgezogen, sondern auch vom Talentwert. Dementsprechend werden die Proben falsch berechnet!

**Comment by Plushtoast** [comment]
Kannst du ein Beispiel liefern. Kann das nicht nachvollziehen.

**Comment by mckee14** [comment]
![image](https://user-images.githubusercontent.com/62849695/109412777-3e351700-79aa-11eb-9bb5-5f5512395052.png)

Bei Erleichterung passiert das gleiche. Siehe Screenshot Beispiel - auf den Talentwert haut es die Erleichterung drauf.

**Das gleiche Verhalten auch bei Zaubern**... ich vermute, es geschieht grundlegend bei allen 3er Würfen. Allenfalls ein Bug aus der Einführung des FP Modifikators auf den Roll? Davor ist mir das nie aufgefallen beim Testen...

@lWFDl Hast du weitere Module aktiviert, oder nur das DSA Modul?

@Plushtoast Ich habe viele Module aktiv, bei Bedarf kopiere ich die Welt und teste RAW. Kann Dir auch das ganze Welt Verzeichnis zum DL geben wenn du magst.

**Comment by Plushtoast** [comment]
Kannst du für den wurf mal die modifikatoren aufklappen und mir zeigen?

**Comment by Plushtoast** [comment]
Ah hab den Fehler gefunden.

**Comment by mckee14** [comment]
Wenn das möglich ist, könntest Du diesen fix als hotfix raushauen? Ist an so ner zentralen Stelle und kommt dauernd in den Weg ;-)
