### ISSUE TITLE
Heiltrank verursacht bei Migration einen nicht löschbaren Statuseffekt

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1490]
**Fehlerbeschreibung**
Wenn ein Akteur bei der Migration einen Heiltrank im Inventar hat, wird ein nicht löschbarer transferierter Statuseffekt erzeugt, der nicht löschbar ist. Auch wenn der Heiltrank aus dem Inventar entfernt wird, bleibt der Status bestehen.

**Versionen**
- Foundry-Version 11.308
- DSA-Version 5.1.1

**Comment by Plushtoast** [comment]
kannst du mir den betroffenen char hier anhängen

**Comment by sirgawain111** [comment]
(Dateiendung auf txt geändert, weil json hier nicht akzeptiert wird)

**Char vor Migration**
[fvtt-Actor-argo-schiefersand-(copy)-94GyDf0LScAT16HT-vor-Mig.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/12567980/fvtt-Actor-argo-schiefersand-.copy.-94GyDf0LScAT16HT-vor-Mig.txt)

**Char nach Migration**
[fvtt-Actor-argo-schiefersand-VNCwfEbgB5sKzPfU-nach-Mig.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/12567981/fvtt-Actor-argo-schiefersand-VNCwfEbgB5sKzPfU-nach-Mig.txt)

**Comment by Plushtoast** [comment]
Denke das sollte mit 5.1.2 auch passen

**Comment by sirgawain111** [comment]
Jou, funktioniert mit 5.1.2 tatdellos. Danke für das Update!
