### ISSUE TITLE
Improve Visibility of Library Toggles

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1496]
There are Toggles in the Library  (de-/activate full text search, browsing mode etc).

It's impossible to see if the toggle is on or off, either because there is no indication or because I'm color blind:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/62849695/ebb815f4-25ff-4a77-a195-3f4e8c9470c8)

It would be nice to see if a setting is on or off, especially since you have to reload the world to make them work.

If there is a colored code, I suggest to change it to a really good visible orange and light green.
Around 10% of the male population suffers from red/green color blindness, so it would be nice to have a non-color indiactor tough.

Thanks for considering,

**Comment by Plushtoast** [comment]
It s red. I ll change it. You ll have to tell me about those issues or i ll never notice, thanks

**Comment by mckee14** [comment]
Yeah thats what I reckoned, and color blind people are used to such things and usually just adapt. As I guessed this may be a small change, i made the request.Thanks a lotGesendet von unterwegsAm 14.09.2023 um 11:49 schrieb Plushtoast ***@***.***>:﻿
It s red. I ll change it. You ll have to tell me about those issues or i ll never notice, thanks

**Comment by Plushtoast** [comment]
that one ok?

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/ced4072a-2187-4ac5-a349-d069bc08009b)

**Comment by Zonenpenner** [comment]
This would be even better for non colorblind people too.

**Comment by mckee14** [comment]
Thats perfect! Thanks a lot :-)
