### ISSUE TITLE
Nahkampfwaffe erstellen auf Charakterbogen und Editieren nicht möglich

### ISSUE THREAD

**Issue by Violettdragon** [Plushtoast/dsa5-foundryVTT#150]
![image](https://user-images.githubusercontent.com/79411612/109401129-24b1b200-794d-11eb-8f22-03d268258a78.png)
Wenn man auf dem + Drückt kommt eine Nahkampfwaffe. Aber Editieren ist nicht möglich.
Bei einem Charakter ist sogar der Charakterbogen abgestürzt und konnte nachher nicht mehr geöffnet werden. Selbst als GM war es nicht mehr möglich.

**Comment by Plushtoast** [comment]
Bitte den fehlerhaften Charakter exportieren.
Rechtsklick auf den Charakter im Charakter Browser und exportieren.
Dann den Inhalt der Datei hier posten.

**Comment by Plushtoast** [comment]
Mh, so ist das doch etwas unpraktisch. Kannst du das File als Anhang platzieren?

**Comment by Plushtoast** [comment]
Also das Problem ist, dass du irgendwie englische Waffen gebaut hast.
Das sollte nicht gehen.

**Comment by Plushtoast** [comment]
Du kannst den Charakter reparieren, wenn du "daggers" mit "Dolche" ersetzt in dem File und dann das File neu auf den Char importierst.
Die neuste Version ist aber installiert?

**Comment by Violettdragon** [comment]
Wir haben jetzt Samstag die Update-Funktion genutzt.
Wie gesagt, besagter Spieler wollte seine Ausrüstung einpflegen. hat auf das Plus gedrückt und wollte dann editieren und er ist aus seinem Bogen geflogen und weder er noch ich als GM konnte den Charakterbogen wieder öffnen.
Habe deine Ratschlag befolgt und es funktioniert wieder.
Danke.
Brauchst du die Datei noch?

**Comment by mckee14** [comment]
Frage für mein persönliches Verständnis: Habt ihr den Char in Englisch erstellt und danach Foundry auf Deutsch umgestellt? Oder den Charakter aus einem Foundry exportiert und danach wieder importiert?

**Comment by Violettdragon** [comment]
Wenn ich jetzt darüber nachdenke, haben wir Foundry als erste mal mit den anderen Spielern getestet, nach dem ich alles eingerichtet habe. Ich wollte den Spielern zeigen was alles foundry kann.
Während ich den Leuten alles erklärt habe und gezeigt habe, wollte er seinen Charakter, den ich nur rudimentär eingerichtet habe, weiter vervollständigen. 
Ob es damit was zusammenhängt kann ich nicht sagen. 
Vielleicht hat ein anderes Modul, was ich zusätzlich installiert habe, dazwischen gespielt. Aber eigentlich nichts was auf das DSA5-System geht. 
Heute Abend kann ich euch die Module auflisten die ich benutze um Foundry noch besser zu machen.

**Comment by Violettdragon** [comment]
Hier die Liste meiner installierten Module

![Module](https://user-images.githubusercontent.com/79411612/109492956-09998c00-7a8c-11eb-9878-96f815638832.png)
