### ISSUE TITLE
Achaz: the module has no manifest URL provided

### ISSUE THREAD

**Issue by zarazandra** [Plushtoast/dsa5-foundryVTT#1501]
**Describe the bug**
Hi,

habe gerade die Achaz-Spielhilfe installiert über die Modulliste (gekauft direkt über Ulisses), aber beim Installieren bekomme ich die Meldung:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/79a47692-32a2-43cf-b930-61b594033f9a)
Es taucht auch nicht in meiner Modulliste in der Spielwelt auf. 
Neuinstallation des Moduls führt zu gleichem Fehler. 

**To Reproduce**
1. Modul runterladen

**Expected behavior**
Modul wird richtig installiert und ist nutzbar

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/2f93f541-8c9b-49e6-ab12-695a38babbb8)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/642285a0-7c36-4e07-952b-57059e3c9455)

**Versions:**
- Foundry Version 11 308
- DSA/TDE version 5 1 4
- Related modules version 5 1 1

**Additional context**
--

**Comment by zarazandra** [comment]
Edit: ich habs noch ein weiteres Mal neu installiert, die Fehlermeldung kam trotzdem, aber es taucht auf.

**Comment by Plushtoast** [comment]
Foundry v11 muss komplett neu installiert und nicht einfach nur aktualisiert werden, sonst funktioniert es nicht richtig.

Wie hast du aktualisiert?

Der Fehler lässt sich nicht nachstellen. Liegt vermutlich nicht an Dingen die mit DSA zu tun haben

**Comment by zarazandra** [comment]
Hä? Verstehe ich gerade nicht - Foundry 11 hab ich doch schon ne ganze Weile - ich hab versucht, die Achaz zu installieren. 
Damit hab ich Probleme. 

Mir fehlt gerade bisschen der Zusammenhang zwischen meinem Problem und deiner aussage - sorry.

**Comment by Plushtoast** [comment]
Ich will sagen dass viele leute probleme wegen einer fehlerhaften foundry version haben. Dein Problem hat eher nichts mit dem modul oder dsa zu tun. Vermutlich ist es noch nicht gecachet gewesen. Hier hilft nur ein bisschen warten.

**Comment by zarazandra** [comment]
Ahh ok - so wird ein Schuh draus. 
Danke dir!
