### ISSUE TITLE
Initiativewurf funktioniert nicht mehr?

### ISSUE THREAD

**Issue by Hijah82** [Plushtoast/dsa5-foundryVTT#1503]
**Describe the bug**

**To Reproduce**
1. Go to 'Kampf HUD nach Start eines Kampfes'
2. Click on 'Schwarzer Initiative Würfel im HUD oder System Tracker'
4. See error - Initiativewurf wird nicht ausgelöst

Gibt es dafür eine einfache Lösung, bzw was kann ich tun um das zu beheben?

**Expected behavior**
Ein Initiativewurf

**Screenshots**

**Versions:**
- Foundry Version
- DSA/TDE version
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Hi,
kannst du bevor du Initiative würfelst mal auf der Tastatur F12 drücken, dann in der Entwicklerkonsole auf den Tab Konsole wechseln. Anschließend Initiative würfeln und hier her kopieren, welcher Fehler kommt (in rot)? Außerdem bitte zusätzlich das Log der Konsole einmal bis ganz oben scrollen und unterwegs alle roten fehler ebenso hier her kopieren.

Tipp: mit windowstaste + shift + s lassen sich screenshots erstellen die man hier in github mit strg/ctrl + c einfügen kann.

**Comment by Hijah82** [comment]
Hey, habe mir das mal selbst in der Konsole angeschaut (danke für den Tip). Das scheint an den GoDice, bzw Unfullfilled Rolls App zu liegen. Beide Module braucht man um die GoDice Würfel in DSA zum laufen zu bekommen. Digitale Würfel, sehhhr cool für Präsenz Runden mit digitaler Unterstützung, oder Crossplay Präsenz/Digital. Auch schon getestet und bis dato lief es. Nach deaktivieren von beiden Modulen läuft auch die Initiative sauber. Wäre cool wenn ihr da eine Idee habt wie DSA5 (was ich sehr genial finde), und die GoDice Würfel (die ich sehr genial finde) koexistieren können. LG, Chris. PS: Screenshot anbei. 

![Screenshot (18)](https://github.com/Plushtoast/dsa5-foundryVTT/assets/137417695/f40e0936-de6a-41a2-b7fc-8962350e26e3)

**Comment by Plushtoast** [comment]
Ja die wollen wir unterstützen auf jeden fall

**Comment by Plushtoast** [comment]
Scheint ein Bug in den unfullfilled rolls zu sein.
Kann das aber über einen Umweg auch in DSA fixen:

https://github.com/foundryvtt/unfulfilled-rolls/issues/33
