### ISSUE TITLE
Bei der Fähigkeit "Gegenhalten" wird z.B. eine Finte nicht automatisch mitberücksichtigt.

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1506]
Bei der Fähigkeit "Gegenhalten" wird z.B. eine Finte nicht automatisch mitberücksichtigt. 

Da die (Gegen-)AT bei "Gegenhalten" als Verteidigung zählt, müsste hier der Verteidigungsmalus einer gelungenen Finte zur Anwendung kommen.

_Originally posted by @Goronius in https://github.com/Plushtoast/dsa5-foundryVTT/issues/1446#issuecomment-1721689527_

**Comment by zoidable** [comment]
Es ist ja wohl so, dass AT- und PA-Mods bei Gegenhalten miteinander verrechnet werden, also z.B. Berserkerangriff +4 AT / -4 VW sich aufheben. #1619 setzt dies zusätzlich zu PA-bezogenen situationalModifiern durch Finte etc. um, berücksichtigt aber sicherlich immer noch nicht alle Feinheiten und Eventualitäten.
