### ISSUE TITLE
Doppelte Attributs- und Angriffswürfe mit GoDice Würfeln, falscher Schaden

### ISSUE THREAD

**Issue by Hijah82** [Plushtoast/dsa5-foundryVTT#1507]
**Describe the bug**
Attributswürfe und Angriffswürfe werden mit aktivierten GoDice Würfeln doppelt abgefragt. 2fache Wurfanfrage über LED Feedback der Würfel selbst, und ingame Wurfaufforderung. Zweiter Wurf ist blinder Wurf taucht nicht in Chat auf (also unnützer Wurf?). Zudem wird der Schadenwürfel bei nachfolgender Schadensermittlung nicht korrekt aufgelöst, zeigt immer nur "1" an. Dies passiert nur bei d6 Wurf nach Angriffswurf mit GoDice. 

**To Reproduce**
1. Go to 'Attributswurf auslösen, Angriffswurf auslösen (mit GoDice aktiviert)'
2. Click on 'würfeln...'

**Expected behavior**
1. Bestätigungswurf GoDice über LED Feedback und Ingame Anfrage sollte nicht benötigt werden / erscheinen
2. Schadenswurf nach GoDice Angriffswurf sollte korrekten Wert anzeigen

PS: Danke für das zügige beheben des Initiativeproblems, ihr meintet das wäre ein Bug in Unfullfillable Rolls Module, soll ich das da nochmal melden?

**Screenshots**

![Screenshot (20)](https://github.com/Plushtoast/dsa5-foundryVTT/assets/137417695/c56affc7-173c-437d-b3f2-be91ecb6f23b)
![Screenshot (19)](https://github.com/Plushtoast/dsa5-foundryVTT/assets/137417695/7a24a520-c664-4528-8977-78ef3c906ba8)

**Versions:**
- Foundry Version
- DSA/TDE version
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Nein ist schon gemeldet

**Comment by Plushtoast** [comment]
Der 2. wurf ist der bestätigungswurf der prophylaktisch intern gleich mitgewürfelt wird

**Comment by Plushtoast** [comment]
und unfullfilled rolls hat einen weiteren bug, weswegen ich das hier kurzfristig nicht fixen kann
