### ISSUE TITLE
Custom Getränke / Essen für Tavernengenerator (Masterworkshop)

### ISSUE THREAD

**Issue by Corbana01** [Plushtoast/dsa5-foundryVTT#1508]
Ich würde es cool finden, wenn man die Möglichkeit hätte, im Tavernengenerator eigene Items zu hinterlegen. In unserer Gruppe haben wir beispielsweise eigene Essensgerichte, welche wir gerne in den Generator einfügen würden. 
Hab auch keinen Weg gefunden, dass Modul seit Foundry 11 dementsprechend zu editieren. ( Foundry 10 habe ich es selbst integriert)

**Comment by Plushtoast** [comment]
requires #799
