### ISSUE TITLE
Unterschiedliche Initiative-würfel

### ISSUE THREAD

**Issue by Invisible303** [Plushtoast/dsa5-foundryVTT#151]
Hallo,

wenn Token in den Combat Tracker gezogen werden, wird der Initiative-Wert + 1w6 genommen. Nun gibt es jedoch schon im Almanach und in einigen Abenteuern, dass die Kreaturen (z.b. Höhlenspinne) keinen Wurf von 1w6 sondern 2w6 haben. Hier wird dann nicht der korrekte Initiativewert berechnet. Wird es dafür eine Möglichkeit geben? Spätestens beim Kompendium werdet ihr mit der Sonderfertigkeit "Klingentänzer" auf das identische Problem stoßen. 

Screenshot aus Almanach
![image](https://user-images.githubusercontent.com/79397897/109402090-3e55f800-7953-11eb-9b32-ce8d7f013b28.png)

Würfelwurf in Foundry:
![image](https://user-images.githubusercontent.com/79397897/109402107-680f1f00-7953-11eb-8e0c-e12e04c91d1d.png)

Momentan passen wir dies natürlich händisch an.

Grüße und danke.

**Comment by Plushtoast** [comment]
Das wird erstmal warten, bis wir an den entsprechenden Büchern sind.
