### ISSUE TITLE
Wunsch: Weitere Filtermöglichkeit in der Bibliothek

### ISSUE THREAD

**Issue by zarazandra** [Plushtoast/dsa5-foundryVTT#1511]
**Is your feature request related to a problem? Please describe.**
Es kostet einfach nur Zeit, durch die verschiedenen Dinge zu suchen, wenn man Anregungen sucht.

**Describe the solution you'd like**
Ich würde mir eine tiefergehende Filtermöglichkeit für die Bibliothek wünschen. 
Beispiel: Sonderfertigkeit - Kampfsonderfertigkeit, Magische Sonderfertigkeit, Profane Sonderfertigkeit ... und so weiter. 
Die Dinge sind ja dank der Bilder schon recht gut ersichtlich, nur wenn die Liste lang und länger ist, hilft das auch nicht sonderlich. 

Eine andere/weitere Sortierebene wäre die Nutzbarkeit - zB für Professionen oder Rassen. Wenn ich also als Beispiel explizit Dinge für Zwerge suche, dass ich das einstellen kann und automatisch Dinge angezeigt bekomme, die ein Zwerg nutzen kann und vice versa - ein Mensch kann mit einem Spießgespann wenig anfangen, genausowenig wie ein Zwerg etwas mit einem Zweihänder anfangen kann. Also in der Regel. ;) 
Gleiches gilt für Professionen - Hexenzubehör zum Beispiel oder auch einfach etwas exotischere Dinge wie Dämonen beispielsweise. Dass ein Dämon keine Liturgie des Praios hat, ist klar. Der wird generell keine Liturgien haben. Aber ich hoffe, es kommt in etwa rüber, was ich meine. 

Ich könnte mir das entweder als Unterkategorie vorstellen oder in der Seitenleiste einfach eine Einschränkungsmöglichkeit nach verschiedenen Punkten (vll nach Tags?), mit denen man die angezeigten Ergebnisse weiter einschränken kann. Ich hab mal sehr dilletantisch in Photoshop was zusammengezimmert. 

**Describe alternatives you've considered**
Ich habe ein Addon, das in den Kompendien schon nach ein paar Rahmendaten suchen kann, aber das geht nur ganz knapp unter die Linie, die die Bibliothek führt. Hilft also auch nur bedingt weiter. 

**Additional context**
![Screenshot 2023-09-30 214057](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/9955dba2-566f-4d11-85dc-162903871da7)
![Screenshot 2023-09-30 214831](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/b770a546-b1d0-4144-8fb9-e69d50f59eb6)
So in etwa? Wäre jetzt nur mal ein ganz plumpes Beispiel, wie man sowas machen könnte. 
praise my photoshopskills. 

![Screenshot 2023-09-30 214831](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/b770a546-b1d0-4144-8fb9-e69d50f59eb6)

**Comment by zarazandra** [comment]
Edit: ich seh grade, dass man doch bissl filtern kann - das kommt aber erst, wenn man irgendwo tiefer drin ist. 
Eine Filterung nach Profession oder Rasse zB ist allerdings nicht so gut möglich.
Oder ganz einfach eine Mehrfachauswahl, sodass man einfach gewisse Sachen ausschließen kann.

**Comment by Plushtoast** [comment]
Den erweiterten filter hast du gesehen? Das is der button neben suche mit dem gehirn.
Welche filter schweben dir genau vor? Was willst du nach profession filtern. Die infos ob was nur für zwerge etc ist ist schon in den Büchern nicht vollständig verfügbar und eher nicht so wahrscheinlich

**Comment by Plushtoast** [comment]
Zusätzliche filteroptionen verbrauchen ausserdem Ressourcen

**Comment by zarazandra** [comment]
> Den erweiterten filter hast du gesehen? Das is der button neben suche mit dem gehirn. Welche filter schweben dir genau vor? Was willst du nach profession filtern. Die infos ob was nur für zwerge etc ist ist schon in den Büchern nicht vollständig verfügbar und eher nicht so wahrscheinlich

Ja, deswegen habe ich den Edit noch angehängt. 
Ich hab das das erste Mal aufgemacht und nur die Sortierung nach Modulen gesehen und das war nicht das, was ich gesucht habe. Hab erst später rausgefunden, dass sich das auffächert, wenn man auch was anklickt. :D 

Eine Professionssuche habe ich noch angeregt, das funktioniert auch, wenn man weiß, was man reinschreiben soll. Hex, Hexe, Hexen, oder sonstwas? Da wäre ein Dropdown nice. Und, wie gesagt, die Mehrfachauswahl. Ich habs mit Kommata versucht, hat nicht funktioniert. Wäre dann nützlich, wenn man Überschneidungen sucht. Das trifft auf alle Suchfelder zu. Gerade wenn man z.B Pflanzen nach Regionen sucht, hat man da ja doch keine Ahnung, in welchem scope man das eingeben soll. Soll ich "Wälder in Almada" eingeben oder "Wälder" oder doch "Almada"? Eine Möglichkeit, da Genaueres zu erkennen, ohne Dokus wälzen zu müssen, wäre famos. <3

Genauso wenn man im Zoo ist: Man kann die Tiere nach Größe sortieren, aber nicht etwa nach Dingen wie "Chimäre", "Wasserwesen", "Flugfähig" oder dergleichen. (Edit: Doch, geht teilweise, aber er erkennt da auch nicht alles) Oder nach Lokation - sowas wie "Wald" oder "Dschungel" beispielsweise würde schon sehr helfen.  
Ein weiteres gutes Beispiel: Gibt man bei den Tieren beim Typus "Dämon" an, bekommt man eine ziemlich lange liste von Viechern, aber wenn man bestimmte Domänen sucht, ist man hier auf dem Holzweg, da man es nicht z.B. nach Amazeroth filtern kann. Man muss jeden anklicken und durchlesen oder parallel über das Buch schauen, um zu wissen, was man nehmen soll. 

Hoffe, es wird ein bisschen deutlicher, was ich meine?

**Comment by Plushtoast** [comment]
Wenn du die volltextsuche aktivierst wird die ganze Beschreibung der Viecher angeschaut. Da sind die begriffe die du suchst normalerweise dabei. Mit erweiterter suche kannst du in typus auch nach dämonen aus domäne x suchen.

Achtung die Einstellung für volltextsuche verändert sich nur nach nem neuladen der welt

**Comment by Plushtoast** [comment]
Für sowas wie Wald oder Dschungel müsste man die daten der Viecher erweitern. Das gibt es ja auch nicht.

**Comment by zarazandra** [comment]
Alles klar, ich schau mal, wie weit ich komme. 

Die Auswahl zu Wald/Dschungel etc anzubieten, halte ich trotzdem nicht für falsch. Man kann ja auch eigene Items anlegen; falls man die da schon irgendwie taggen und sortieren könnte, oder bestehende verändern, das wär ziemlich sexy.

**Comment by Plushtoast** [comment]
Geht nicht und nach Domäne kann man auch schon suchen im Typus.
Ich sehe hier nicht was es nicht schon gibt oder machbar wäre deswegen 

closed
