### ISSUE TITLE
Das Geheimnis des Drachenritters - Audio-Import funktioniert nicht

### ISSUE THREAD

**Issue by Bellgarion** [Plushtoast/dsa5-foundryVTT#1517]
Das Geheimnis des Drachenritters

Der Import der Audio-Pakete über die Importfunktion des Journalbrowsers funktioniert nicht.
Der Import wird zwar angezeigt. Danach sind aber bei der Übersicht noch alle Häkchen rot.
Auch in den Szenen ist kein Sound zu hören und die Dateien werden auch in den Szenen-Einstellungen nicht gefunden.

'Journalbrowser' 'DSA5Das Geheimnis des Drachenritters' 'Readme' 'Vorbereitung' 'Import/Update'

Bitte um genaue Information wie die Soundpacks integriert werden. Vielen Dank!

Versions:
- Foundry Version: 11 Build 313
- DSA/TDE Version: 5.1.5
- Related modules version: 5.1.0

**Comment by Plushtoast** [comment]
Umgebungsgeräusche sind nicht teil des moduls. Im kapitel vorbereitung steht beschriewas zu tun ist. Im Prinzip muss man die kostenlosengame audio bundle module installieren dann funktioniert es

**Comment by Bellgarion** [comment]
Hab ich gemacht. Habe extra eine neue Welt angelegt. Nichts weiter gemacht, nur die Module installiert und direkt den Import/Update über das Journal gestartet.

Das Hinzufügen der Szene habe ich über das Journal gemacht.

Auch nach Neustart sind die Häkchen weiter rot und die Sounds finden sich nicht auf der Karte.

Das Hinzufügen einer Szene (als weiteren Test) habe ich über das Journal gemacht.

Zusätzlich kommt noch mehrere Meldungen 'The Actor does not exist in actors'

Doch dann gingen mir die Ideen aus...

![foundry_screen_221023](https://github.com/Plushtoast/dsa5-foundryVTT/assets/148696341/58e100ba-d0af-4b56-8410-74025f5018c5)

**Comment by Plushtoast** [comment]
Die Actors Nachricht hat keine Bedeutung. Kann aber leider auch nicht vermieden werden.

Die Game Audio Bundles müssen installiert sein wie hier:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/5c0f93e5-3621-458e-a40f-b4730b263e39)

Danach kannst du die Sounds auf der Map mit dieser Funktion testen:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/49543423-c602-4a4b-ad80-d176a3ac6abd)

Drauf achten, dass die User Volume Controls hier nicht auf 0 sind:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/6a61faca-13a7-49ee-88ac-d61a5aa5fe99)

Mehr muss man hier nicht machen.

Falls du Forge benutzt kann es auch sein dass die Soundpfade nicht mehr stimmen. Forge manipuliert gerne mal die Module. Da können wir aber nichts dagegen machen.

**Comment by Bellgarion** [comment]
Danke für die schnelle Antwort.

Das könnte es erklären, denn die Audio Bundles (Module) habe ich nicht. Wurden weder mit installiert, noch finde ich sie irgendwo auf der foundry Seite.

Installiert habe ich
die "DSA5-Welt",
das "DSA5 Grundregelwerk"
die "Drachenritter-Box"
das "German Core"-Modul
und die Drachenritter Einsteigerbox"

Die Anwendung der Audio-Dateien hab ich - Dank der guten Tutorials von VTTom - schon getestet und die grundsätzlichen Funktionen hab ich verstanden.

Forge benutze ich nicht

**Comment by Plushtoast** [comment]
Ganz unten "Return to Setup clicken"
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/e9d6e034-9445-48fb-8ce7-c9cb138d6857)

Zu den addons wehcseln und dort "install module" clicken
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/77c08f5c-9ba2-4990-977c-88e88313a43c)

Und dann game audio bundles suchen.
Wie es aussieht werden die derzeit aber nicht angezeigt

Man kann sie aber auch manuell installieren wenn man hier
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/0212d582-b4c9-432e-93e5-36be489ac78e)

manuell diese urls eingibt:
https://raw.githubusercontent.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/master/module.json
https://raw.githubusercontent.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-2/master/module.json
https://raw.githubusercontent.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-3/master/module.json
https://raw.githubusercontent.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-4/master/module.json

**Comment by Bellgarion** [comment]
... und genau so (über die manuelle Eingabe der Links) hat es funktioniert.

Vielen Dank für die Hilfe.
