### ISSUE TITLE
Falscher Schaden bei Zauber Corpofrigo mit Erweiterung Qualvolles Eis 

### ISSUE THREAD

**Issue by HalVonGareth** [Plushtoast/dsa5-foundryVTT#1519]
**Describe the bug**
Wird der Zauber Corpofrigo mit der Erweiterung Qualvolles Eis gezaubert, bekommt das Ziel nur 2 TP, statt 2 TP zusätzlich. Die eigentlichen TP fallen einfach raus.

**To Reproduce**
1. Heldendokument öffenen → Magie Reiter
2. Click on Würfel bei Corpofrigo
3. Qualvolles Eis auswählen

**Expected behavior**
Die TP sollten +2 bekommen

**Screenshots**
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/146668232/521b9959-d10c-499c-a446-02703cdf9756)
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/146668232/7f123df9-aca7-40a5-9c52-bfaab5d22d3f)

**Versions:**
- Foundry Version 11 Stable 309
- DSA/TDE version 5.1.5
- Related modules version

**Comment by Plushtoast** [comment]
Bis Patch kommt, kannst du das manuell beheben indem du den active effect der erweiterung anpasst und statt modus "override" modus "add" auswählst
