### ISSUE TITLE
DSA-Kampftracker: Rundenwechsel deutlicher hervorheben

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1528]
Der DSA-Kampftracker ist eine großartige Ergänzung im Kampf. In unserer Gruppe sticht er den "normalen" Kampftracker sogar meistens aus. Danke dafür! :-)
Meine Spieler verwenden die Möglichkeit, ihre Aktionen "zurückzustellen" relativ gerne. Leider übersehe ich in der Eile öfters den Kampfrundenwechsel und löse damit natürlich eine Welle der Empörung bei meinen Spielern aus (OK, ein wenig übertrieben).

Wäre es bitte möglich, den Token mit dem Kampfrundenwechsel ein wenig deutlicher hervorzuheben? Vielleicht hilft es schon, wenn man das blau etwas kräftiger macht. Alternativ wäre zusätzlich vielleicht eine optische Abtrennung für mich hilfreich (es würde sicherlich die Breite von 1/5 der normalen Breite reichen - ggf. ja optional?).

Wäre super, wenn du darüber nachdenken könntest. :-)

_Foundry Virtual Tabletop: Version 11 Stable, 11.308
Game System: dsa5, 5.1.5_

**Comment by Plushtoast** [comment]
Ich mach den end turn button blau und schreibe statt dessen "runde beenden"

**Comment by Albinosheep** [comment]
Danke! :-)
