### ISSUE TITLE
Wirkungsdauer Zauber elfischer Verbreitung bei Tradition Elf verdoppeln 

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1531]
Bei Zaubern mit elfischer Verbreitung ist für Zauberer der Tradition (Elf) die Wirkungsdauer verdoppelt. Das wird aktuell noch nicht berücksichtigt und hat bei unserem letzten Kampf dazu geführt, dass zwei Axxeleratus vorzeitig ausgelaufen sind.

Aus der Beschreibung:
_Die Wirkungsdauer aller Zauber der Verbreitung Elfen ist doppelt so lang wie beim Zauber angegeben._

Es wäre super, wenn dies automatisch berücksichtigt werden könnte. 

_Foundry Virtual Tabletop: Version 11 Stable, 11.308
Game System: dsa5, 5.1.5_

**Comment by Plushtoast** [comment]
welche sonderfertigkeiten, die die dauer modifizieren gibt es noch?

**Comment by Albinosheep** [comment]
Zumindest bei Scharlatanen ist die Wirkungsdauer von Illusionen doppelt so lange. Weitere Fälle sind mir nicht bekannt. 

https://dsa.ulisses-regelwiki.de/magische_tradition.html?tradition=Scharlatane
