### ISSUE TITLE
Posten von Fertigkeiten mit "&" im Text oder Titel

### ISSUE THREAD

**Issue by mhs2508** [Plushtoast/dsa5-foundryVTT#1532]
**Describe the bug**
Seit der Migration auf Foundry V11 ist das Posten von Sonderfertigkeitgen im Chat mit einem "&" im Titel oder Text nicht mehr möglich

**To Reproduce**
1.) Wähle eine Sonderfertigkeit mit einem "&" im Text oder Titel. 
Beispiele: Sonderfertigkeit "Haltegriff" ODER Anwendungsgebiet "Drücken & Verbiegen"
2.) Klicke auf die Chatblase um den Text im Chat zu posten
3.) Fehlermeldung erscheint: **"Cannot read properties of undefined (reading '0')"**

**Expected behavior**
Die gesamte SF sollte mitsamt Regeltext etc im Chat gepostet werden.

**Screenshots**
<img width="1496" alt="Error_Message_Console" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/aad95540-1f02-49fc-bb07-977263cfb487">
<img width="1577" alt="Error_Message_Canvas" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/899ae178-5adf-4163-9f87-15783f97e83d">

**Versions:**
- Foundry Version: V11.313
- DSA/TDE version V5.1.5
- Related modules version

**Additional context**
Siehe Screenshots

**Comment by Plushtoast** [comment]
Dein Fehler zeigt ein Problem mit dem Modul Tokenizer. 
Bei mir geht das Posten auch problemlos.

Kannst du schauen, ob in der Konsole noch andere Fehler weiter oben zu finden sind?

Außerdem hilft vlt den Tokenizer zu löschen und neu zu installieren.

**Comment by mhs2508** [comment]
Mhhh, ich habe jetzt mal eine neue Welt mit dem DSA 5 System erstellt, und auch wirklich nur die Ulisses Module aktiviert, also Tokenizer ist zwar installiert aber nicht aktiv. Und trotzdem wirft er diesen Fehler. Strange.....

**Comment by Plushtoast** [comment]
Hast du auf deinem Server NodeJS mit v11 aktualisiert und auch Foundry NEU installiert?

Das war bei v11 notwendig, hat nicht bei jedem geklappt und führt zu sehr vielen merkwürdigen Fehlern.

**Comment by mhs2508** [comment]
Sorry, auch mit Tokenizer löschen und neu installieren (Versuch 1) oder Tokenizer ganz löschen (Versuch 2) oder mal komplett ohne alle Module (Versuch 3) klappt das nicht bei mir. 

Jetzt wird es langsam haarig.
Ich hoste als node.js auf einem Raspberry Pi 4, mit Ubuntu Linux 22.04 Server drunter und node.js V18.17.1

Foundry habe ich NICHT neu installiert, sondern bin über die Foundry-eigene Update-Funktion gegangen.

**Comment by Plushtoast** [comment]
Dann wirst du Foundry neu installieren müssen. Das ist Pflicht mit v11, könnte man aber leider absichtlich oder unabsichtlich umgehen.

Davor Backups machen.

Der ganze Ordner muss gelöscht werden. Drüber installieren/entpacken führt evtl dazu dass ein paar alte Files über bleiben.
(nicht den Data Ordner löschen nur den Foundry Install)

Deine node version müsste passen

**Comment by mhs2508** [comment]
Ok ich teste das mal

**Comment by mhs2508** [comment]
Ok danke - du hattest Recht! Reinstall der Software war die Lösung. 😀

**Comment by Plushtoast** [comment]
top
