### ISSUE TITLE
Fehlermeldung bei funktionierender (?) Gestaltwandlung

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1533]
Wenn ich einen Schwarzbär (dsa5-bestiary) auf den angehangenen Charakter ziehe und mit den default-Einstellungen umstelle, dann kommt es dreimal zu folgender Fehlermeldung. Die Gestaltwandlung scheint aber reibungslos zu funktionieren. Der Charakter ist aus einer anderen Welt importiert worden.

<img width="1183" alt="Screenshot 2023-10-31 121745" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/41292141/cb56b95f-52bd-4bb3-91f2-fc517c865e33">
[fvtt-Actor-fanaion-teichlauf-o3aKXXhRJwbbjbKc.json](https://github.com/Plushtoast/dsa5-foundryVTT/files/13215920/fvtt-Actor-fanaion-teichlauf-o3aKXXhRJwbbjbKc.json)

**Comment by Plushtoast** [comment]
Das Charakter anhängen hat irgendwie nicht geklappt

**Comment by Albinosheep** [comment]
Ich weiß nicht, warum der Link nicht tut, was er soll. Aber wenn das eingebe:
https://github.com/Plushtoast/dsa5-foundryVTT/files/13215920/fvtt-Actor-fanaion-teichlauf-o3aKXXhRJwbbjbKc.json
kann ich den Char downloaden. :-)

**Comment by Plushtoast** [comment]
Bug kann ich nicht ohne massiven aufwand fixen
Bleibt wahrscheinlich länger

**Comment by Albinosheep** [comment]
Oh, scheinst ja doch einen fix gefunden zu haben. Wollte schon Fragen, ob es einen einfachen Workaround gibt. Danke fürs Kümmern! :-)
