### ISSUE TITLE
NSC-Generator: Item nach Kategorie

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1539]
**Is your feature request related to a problem? Please describe.**
Derzeit lässt sich nur der Typ des Items auswählen. Dadurch ist es kaum möglich einem NSC halbwegs spezifische Items zuzuordnen, was i.d.R. manuelle Anpassungen notwendig macht.

**Describe the solution you'd like**
Detaillierte Auswahlmöglichkeiten im NSC-Generator: 
Ausrüstung -> Kategorie
Rüstung -> Subkategorie
Waffen -> Kampftalent

**Comment by Plushtoast** [comment]
related to #736
