### ISSUE TITLE
Keine Vergleichsprobe bei Verteidigung

### ISSUE THREAD

**Issue by Invisible303** [Plushtoast/dsa5-foundryVTT#154]
MoinMoin,

wenn eine Kreatur angegriffen wird hat der Spielleiter, sobald der Spieler diese in den target genommen hat und getroffen hat, die Vergleichsprobe abzubrechen mit der Schaltfläche "Keine Vergleichsprobe" im Chat. Danach wird der Schaden berechnet. Die Spieler können, sobald sie im traget sind, diese Schaltfläche nicht benutzen, da diese nicht angezeigt wird.

Spielleiter:
![image](https://user-images.githubusercontent.com/79397897/109458317-dc81b500-7a5c-11eb-84cd-596bd0190e44.png)

Spieler:
![image](https://user-images.githubusercontent.com/79397897/109458345-e9060d80-7a5c-11eb-8d46-684e4ff16221.png)

Ist es so korrekt und kann nicht anders eingestellt werden? 

Grüße und Danke :)

**Comment by mckee14** [comment]
Das war früher leicht anders, und wurde extra auf Spielerwunsch so angepasst, [siehe hier](https://github.com/Plushtoast/dsa5-foundryVTT/issues/133).

Nur noch der SL kann via Button die Verteidigung ausschlagen (wodurch die AT automatisch gelingt und der Schaden berechnet wird).

Beim testen ist mir nicht aufgefallen, dass man eine Probe würfeln MUSS, man kann auch einfach den Zug beenden und der nächste ist an der Reihe.

**Comment by Plushtoast** [comment]
Ja das muss der  SL abbrechen, weil dazu Zieldaten auf dem Token gelöscht werden müssen und dafür braucht es Berechtigungen.
Das sollte gar nie anders funktionieren.

**Comment by Gunthgard** [comment]
@Invisible303 
It's not a bug it's a feature.

Ne, Spaß bei Seite. In vielen Testspielen kam es oft dazu das die Spieler eigenständig auf das "x" geklickt haben und somit die Möglichkeit der Reaktion des SL verschwand. Dieses Ereignis wurde auch mehrfach im Discord als "Bug" aufgefasst .... deshalb hatte ich den Vorschlag gemacht es dem Meister zu überlassen ob es die Spieler bedienen dürfen. Das zu Implementieren scheint aber sehr aufwendig zu sein (ich habe keine Plan vom Programmieren), so dass sich die Entwickler dazu entschieden haben es vorerst nur dem SL zu ermöglichen das "x" und damit das löschen der Vergleichsprobe zu klicken.

Also "mea culpa" ;)

Grüße Gunthgard / Michael

**Comment by Invisible303** [comment]
Moin,

danke für die Antwort/Hinweise :)

Ahhh ein Wikinger, weg da, lass meine nostrische Küste in Ruhe! ;)

bleibt Gesund!
