### ISSUE TITLE
Deaktivierter Effekt wirkt trotzdem nach Update auf v11

### ISSUE THREAD

**Issue by FranzBearwine** [Plushtoast/dsa5-foundryVTT#1543]
[fvtt-Actor-petrodur-BWBVKGq1v2iGay7k.json](https://github.com/Plushtoast/dsa5-foundryVTT/files/13323969/fvtt-Actor-petrodur-BWBVKGq1v2iGay7k.json)
**Beschreibung**
Nach dem Update auf v11 (DSA 5.1.5) und der vollen Migration mit Weltenzerstörer kommt es bei einem Charakter trotzdem noch zu seltsamen Konstellationen. Viele transferierte Effekte liegen noch auf dem Helden, u.a. ein selbsterstellter Effekt von einem Kraftgürtel (KK+3). Der Effekt ist allerdings deaktiviert - nur leider wirkt er trotzdem auf den Charakter.

**Reproduzieren**
1. Öffne den Charakterbogen von Petrodur
2. Gehe zum Tab "Ausrüstung"
3. Öffne den "Adawadt-Gürtel" in der Rubrik "Kleidung"
4. Im Reiter "Statuseffekte" befindet sich der deaktivierte Effekt (system.characteristics.kk.gearmodifier + 3)
5. Gehe zum Charakterbogen-Tab "Status"
6. Siehe dort unter "Transferierte Statuseffekte" den Effekt "Adawadt-Gürtel": Deaktiviert, aber wirkt (KK 21 statt 18)

**Versions:**
- Foundry Version: v11
- DSA/TDE version: 5.1.5

**Comment by Plushtoast** [comment]
Gürtel ausziehen hilft auch

**Comment by FranzBearwine** [comment]
> Gürtel ausziehen hilft auch

Das wär ein Workaround, aber sobald er den Gürtel wieder anzieht, hat er wieder KK+3, obwohl der Effekt deaktiviert ist. Auch Gürtel löschen und neu ins Inventar geben hilft nichts. Das ist schon seltsam, bei v10 ging es problemlos

**Comment by Plushtoast** [comment]
Jo geht mit nächstem Patch, bis dahin workaround
