### ISSUE TITLE
Kneipen & Tavernen Generator: Zufällig Auswahl

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1545]
Bei längerem Aufenthalt in einer Region finde ich es etwas langweilig wenn immer wieder die gleichen Getränke angeboten werden. Ich fände es schön wenn ein bisschen Abwechslung drin wäre, indem eine Zufällig Auswahl angeboten wird. Idealerweise auf Basis von Wahrscheinlichkeiten, eine einfacher Zufallsauswahl wäre aber schon schick.

**Comment by mckee14** [comment]
Du kannst alle items in einen rolltable ziehen in foundry und auf wunsch auch wahrscheinlichkeiten gewichten. Kannst den table auch kopieren und für regionen unterschiedliche gewichtungen hinterlegen.Dann nur noch rollen und den treffers in den Händler ziehen.Allerdings kann man auch gut speisen und getränke selbst erfinden, vom trüben grolmfeisser (bitterschnaps) bis hin zu meinen lieblingen aus Fasar, den Topfmoppen. Gesendet von unterwegsAm 11.11.2023 um 12:58 schrieb Ogrimgro ***@***.***>:﻿
Bei längerem Aufenthalt in einer Region finde ich es etwas langweilig wenn immer wieder die gleichen Getränke angeboten werden. Ich fände es schön wenn ein bisschen Abwechslung drin wäre, indem eine Zufällig Auswahl angeboten wird. Idealerweise auf Basis von Wahrscheinlichkeiten, eine einfacher Zufallsauswahl wäre aber schon schick.

**Comment by Plushtoast** [comment]
Im nächsten Patch wird die Anzahl pro Alkhol Zufall von 1-50 Stein

Beispiel: Premer Feuer 27 Stück verfügbar

Außerdem lässt sich die Anzahl der Alkoholika begrenzen

Beispiel: Für die gewählten Regionen sind 37 Alkoholsorten verfügbar

Daraus werden per Limit 5 ebensoviele Alkohol ausgewählt (jeder mit der gleichen Wahrscheinlichkeit)
