### ISSUE TITLE
Novadischer Kalender für Simple Calendar

### ISSUE THREAD

**Issue by MichaelBoe86** [Plushtoast/dsa5-foundryVTT#1546]
Für das Modul Simple Calendar gibt es bereits den offiziellen Aventurischen Kalender. In der Wüstenreich Regionalspielhilfe wird der Novadische Kalender beschrieben. Ich würde mir auch für diesen eine offizielle Umsetzung wünschen.

**Comment by Plushtoast** [comment]
Das wird nicht von uns gehandhabt. Denke ist auch nicht offiziell. Wird es nicht geben.

**Comment by Plushtoast** [comment]
Denke auf dem Ulisses discord kann am ehesten geholfen werden, beim Anlegen des Kalenders.

Zeug für fremde Module zu unterstützen hat neben dem Aufwand noch diverse andere Nachteile.

**Comment by MichaelBoe86** [comment]
Naja, original wurde damals von VTTom ein Feature Request bei den Machern von Simple Calendar gemacht in dem er sagte, dass er das offizielle okay von Ulisses hat den DSA Kalender in Simple Calendar einzubauen. Damals ist das wohl zwischen VTTom und denen gemacht worden. Daher meine Idee hier mal nachzufragen.
Link: https://github.com/vigoren/foundryvtt-simple-calendar/issues/296

**Comment by Plushtoast** [comment]
VTTom ist maximal hilfreich und freundlich, vlt hilft er hier auch nochmal.
Aber kein Thema für mich.

**Comment by MichaelBoe86** [comment]
Okay, danke euch für die Infos.
