### ISSUE TITLE
way to remove a talent

### ISSUE THREAD

**Issue by benaryorg** [Plushtoast/dsa5-foundryVTT#1548]
**Is your feature request related to a problem? Please describe.**
For story-related reasons there are a few custom talents in our campaign.
I did accidentally drag a talent *not* meant for me in my character sheet, and now I cannot remove it any more.
Considering that all the regular rule-book talents are added with 0 points at the start (as far as I can tell) it stands to reason that there may not be a way to remove those.?

**Describe the solution you'd like**
I would like to be able to remove a talent.
I can see no option, menu, or UI element for this.

**Describe alternatives you've considered**
I guess there would be alternative options to creating custom talents, however the ability to remove a talent in general would be appreciated for any edge-cases that arise.

**Additional context**
Items for instance have a trashcan icon next to them to delete them.

**Comment by Plushtoast** [comment]
Already in the next patch

**Comment by Plushtoast** [comment]
will be in the context menu (right click)

**Comment by benaryorg** [comment]
If anyone else stumbles across this, my workaround was to create the following macro:

```javascript
let actor = game.actors.find(x => x.name == "My Character Name Here");
let items = actor.items.filter(x => x.name == "My Skill Name Here");
await actor.deleteEmbeddedDocuments("Item", items.map(x => x._id))
actor.render(true);
```
