### ISSUE TITLE
Anteilige Umrechnung der lep bei gestaltwandlung

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1551]
Siehe zb zauber adlerschwinge

**Comment by mckee14** [comment]
Edgecase: Zielform hat nur 1 LeP und Zauberer < 50% LeP = Insta DeathGesendet von unterwegsAm 14.11.2023 um 11:48 schrieb Plushtoast ***@***.***>:﻿
Siehe zb zauber adlerschwinge
