### ISSUE TITLE
Makro: Heilkunde Wunden

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1555]
Eingeloggt als **Spieler**:

Char A macht Heilkunde Wunden auf Char B. Chatmessage alles OK. Wenn der Effekt angewendet werden soll über die chat-card, geschieht nichts (Dialog zur Auswahl Schmerzen lindern/Wunden heilen wird nicht gezeigt).
Die LeP zur Regeneration werden nicht gesetzt.

Getestet mit verschiedenen Rechten auf beiden Chars für den Spieler, bis zu Besitzer.

Eingeloggt als **GM**:
Heilung funktioniert

Eingeloggt als **GM und Spieler** in 2 Browsern:
Wenn der Spieler auf "Effekt Anwenden" klickt in der chat-card, rendert das Auswahl-Menü auf dem Screen des GM.
Der GM kann dann auswählen Schmerzen lindern / Wunden heilen, es geschieht jedoch nichts, LeP Regeneration wird nicht eingetragen.

**Comment by Plushtoast** [comment]
Ich habs eindeutiger gemacht. Spieler wird aber trotzdem kein Feedback bekommen ,da das macro beim GM laufen muss

**Comment by mckee14** [comment]
Oke, das ist ein wichtiger hinweis, danke.Also ist es by design dass der spieler die mechanik auslösen aber nicht anwenden kann.Solange man das als GM weiss ist alles gut 😊 Gesendet von unterwegsAm 17.11.2023 um 15:59 schrieb Plushtoast ***@***.***>:﻿
Ich habs eindeutiger gemacht. Spieler wird aber trotzdem kein Feedback bekommen ,da das macro beim GM laufen muss
