### ISSUE TITLE
Artefakt: Wurf für Zauber wird nicht ausgeführt

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#1556]
DSA 5.2.0

Ich habe ein Artefakt erstellt mit einem Ablativum als dauerhafter Effekt.

Wird der Zauber ausgelöst, erscheint eine Chatnachricht über den Verbrauch einer Ladung, es wird aber keine Probe ausgeführt:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/62849695/91c8523c-5399-441a-941e-931174992afd)

Die Konsole sagt dazu:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/62849695/33ebd217-cabd-45d9-a0e6-0e28058300d0)

**Comment by Plushtoast** [comment]
#1554
