### ISSUE TITLE
Widrige Umstände funktionieren nicht

### ISSUE THREAD

**Issue by Schorschus** [Plushtoast/dsa5-foundryVTT#1558]
**Describe the bug**
"Widrige Umstände" in der Meisterbar werden nicht getriggert.
In der Konsole werden Errormeldungen angezeigt

**Screenshots**

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/4883adb1-bd8d-42a9-8a76-5da6b176d7d4)

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/9e4d35de-8a6e-4273-8e64-0dff67ae804f)

**Versions:**
Foundry 11.315
- DSA/TDE version: 5.2.1.
- Related modules version

**Comment by Plushtoast** [comment]
core modul updaten
