### ISSUE TITLE
Kauf von Ausrüstung bei Charaktererstellung

### ISSUE THREAD

**Issue by RodiakWolfshain** [Plushtoast/dsa5-foundryVTT#1559]
**Describe the bug**
Beim Kauf von Ausrüstung während der Charaktererstellung wird kein Geld mehr abgezogen.
Das hat vor Version 5.2.x noch funktioniert

**To Reproduce**
1. Neuen Charakter erstellen
2. Alles erledigen bis Ausrüstung gekauft werden kann
3. Items aus der Bibliothek ins Ausrüstungsfenster ziehen

**Expected behavior**
Vor V 5.2.x wurden die entsprechenden Münzwerte korrekt vom Startbudget abgezogen

**Screenshots**

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.2.0 und 5.2.1
- Related modules version N.A.

**Additional context**
Wenn man bspw. ein Proviantpaket manuell in den Ausrüstungstab zieht, und dann dort die Anzahl hoch klickt, wird jede weitere Einheit korrekt abgerechnet. Refund über Rechtsklick klappt auch problemlos. Dafür ist die Berechnung über "Edit" und dann eine manuelle Menge eintragen wieder defekt.

**Comment by RodiakWolfshain** [comment]
Wichtig - Ich mein hier die Charaktererstellung mit Hilfe des Wizards, wo man Schritt für Schritt durch den Prozess geführt wird.

**Comment by Plushtoast** [comment]
core modul updaten
