### ISSUE TITLE
Ergebnisse der Erholungsprobe automatisch anwenden oder Zuweisen

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#156]
Nach einem Wurf zum regenerieren von LeP, AsP oder KaP wird es zwar gewürfelt, aber nicht mit den Werten des Charakters verrechnet.
Es wäre schön wenn die Ergebnisse der Probe automatisch verrechnet würden oder es zumindest (wie beim Schaden) die Möglichkeit mittels eines Kontextmenüs die Heilung zuzuweisen,

**Comment by Plushtoast** [comment]
Das Kontextmenü wird dazu kommen. 
Automatische Verrechnung ist zu fehleranfällig (man hat sich mit den Modifikatoren vertippt etc...).
