### ISSUE TITLE
Proben funktionieren nicht mehr, wenn Elfische Tradition mit doppelter Wirkungsdauer aktiviert ist

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1560]
Das aktuelle Update unterstützt, dass die Elfische Tradition eine doppelte Wirkungsdauer auf ihre Zauber haben. Vielen Dank, dast ist sehr cool! :-)
Leider wirft es mir für alle Akteure mit Tradition Elf (egal ob migriert oder neu erstellt)  seit dem Update auf 5.2.1 (Foundry 11.315) bei 
 allen Proben folgende Fehlermeldung in der Konsole. Im Chat erscheint daraufhin nichts.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/41292141/e3390a05-479f-4fe3-88f7-45cd890b1571)

Sobald ich bei "Tradition Elf" den Haken bei "doppelte Wirkungsdauer" herausnehme funktioniert alles fehlerfrei. :-)

_Foundry Virtual Tabletop: Version 11 Stable, 11.315
Spielsystem: dsa5, 5.2.1_

**Comment by Plushtoast** [comment]
core update nnochmal migrieren
