### ISSUE TITLE
Prügel-Punkte funktionieren bei einem Akteur nicht richtig.

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#1561]
Bei einem migrierten Charakter funktioniert das mit den Prügel-Punkten nicht (bei allen anderen schon). Sobald er dabei ist, kann ich den Kampf nicht mehr von einer Prügelei in einen normalen Kampf umwandeln. Wenn der Akteur im Kampf beteiligt ist, behalten nach Ende des Kampfes alle Akteure ihre Prügelpunkte. 
Sobald dieser eine Char nicht dabei ist, funktioniert alles fehlerfrei.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/41292141/9a6d33be-2388-4818-a7fe-b02b711a4dd0)

[Akteur mit Prügelpunkten-Bug.json](https://github.com/Plushtoast/dsa5-foundryVTT/files/13398111/Akteur.mit.Prugelpunkten-Bug.json)

_Foundry Virtual Tabletop: Version 11 Stable, 11.315
Spielsystem: dsa5, 5.2.1_

**Comment by Plushtoast** [comment]
Ich hab einen fix bereit.

Vorsicht allerdings mit dieser Einstellung:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/8ecba349-45e2-4de4-a6ec-8cb824af8f9c)

Ohne die automatische Ressourcenleiste wird der Token auf der Map die Leiste nicht auf Prügelpunkte umstellen
