### ISSUE TITLE
Heldenbogen Charakter Sheets Aussehen individualisieren

### ISSUE THREAD

**Issue by Foseti** [Plushtoast/dsa5-foundryVTT#1562]
Hallo,

es gibt ja mittlerweile verschiedene Heldenbögen varianten, wie den Heldenbogen des Widderordens, Swafnir, Rahja usw. Kann man den Style dieser Bögen vielleicht auch für die Heldendokumente in Foundry anapassen? Gerne auch als Module.

grüße

Foseti

**Comment by Plushtoast** [comment]
Nein, es gibt bereits genug sonstige Aufgaben. Das wird sicher nicht passieren.

Dafür wurde allerdings eine Funktion vorbereitet, die das Erstellen und Einbinden von Skins unterstützt.
Du kannst gerne selbst ein Modul, das das Design verändert, erstellen. Ulisses wird sehr wahrscheinlich da auch nichts dagegen haben.

Info hier: #1373

**Comment by Plushtoast** [comment]
Ansonsten kannst dir noch das Modul anschauen: https://foundryvtt.com/packages/yendors-ui
