### ISSUE TITLE
World Validation Error

### ISSUE THREAD

**Issue by ijuedt** [Plushtoast/dsa5-foundryVTT#1566]
**Describe the bug**
Versuch, "Rabenkrieg I" zu installieren, schägt fehl mit "World validation errors: system: may not ne undefined coreVersion: may not be undefined"

**To Reproduce**
Gehe zu "Install world"
Füge Pfad zum Manifest ein
Klicke auf "Install"

**Expected behavior**
Einfach nur installieren, bitte!

**Screenshots**

![screen_world-validation-error](https://github.com/Plushtoast/dsa5-foundryVTT/assets/8036098/ccfeea1f-edc3-40dd-acfb-bd126bd30e16)

**Versions:**
- Foundry Version: 11.315
- DSA/TDE version: 5.2.3
- Related modules version: > 5.0.0

**Additional context**
Komplette Neuinstallation von Foundry, Update aller Module. Selbst angelegte Projekte lassen sich starten, Kaufabenteuer lasseen sich nicht installieren.

**Comment by Plushtoast** [comment]
install world ist für komplett vorbereitete welten, das ist etwas anderes wie module die bestehende welten erweitern wie zb rabenkrieg

um rabenkrieg zu installern musst du auf den "add-on modules" tab wechseln, auf install module klicken, nach rabenkrieg filtern und anschließend (zusammen mit deinen anderen modulen) installieren

**Comment by Plushtoast** [comment]
anschließend kannst du die welt betreten und musst dort die module ebenfalls nochmal aktivieren (man kann je nach welt unterschiedliche aktiv haben)

hier unter manage modules:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/d94e8621-0396-4c10-8c60-605397d0b9b2)

**Comment by ijuedt** [comment]
Danke für den Hinweis! Ist denn vorgesehen, alle Rabenkrieg-Module in eine Welt zu laden, oder jedes Modul in eine eigene?

**Comment by Plushtoast** [comment]
Du kannst eine welt als eine spielgruppe betrachten, da aktivierst du alle module die du brauchst
Da du die kampagne vermutlich mit den gleichen leuten spielst kannst du auch alle rabenkrieg module in der gleichen aktivieren.
Allerdings lohnt sich ab und zu auch mal das aufräumen. außerdem kann man das jederzeit an- und abschalten.

ich würde für den anfang die module times-up, dicetray, dice so nice und alle dsa module die du hast aktivieren
für umgebungsgeräusche auf den maps von rabenkrieg brauchst du zusätzlich noch die game audio bundles

**Comment by Plushtoast** [comment]
ansonsten empfehle ich die videos auf vttoms youtube kanal
https://www.youtube.com/@VTTom

da habe ich auch eine detailliertere einführung für die rabenkrieg module gemacht:
https://www.youtube.com/watch?v=hMYbomT1bhE&ab_channel=VTTom

**Comment by ijuedt** [comment]
Ok, vielen Dank! Nach dem Versionssprung auf 11, kompletter Neuinstallation und Upgrades funktioniert es erst mal wieder.
