### ISSUE TITLE
Lichtquellenreichweite bei Änderung des Gitters

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1576]
Hallo,

ich nutze gerne das Programm Dungeon Alchemist um neue Karten zu erstellen und in Foundry zu importieren. Dungeon Alchemist nutzt standardmäßig die Einheit 5 ft pro Gitterkästchen. Nach dem Import in Foundry kann man sowohl die Einheit als auch die Größe auf 1 Schritt pro Kästchen ändern.

Dabei ist mir aufgefallen dass die Änderung des Gitters dazu führt, dass die Reichweiten aller Lichtquellen (in diesem Beispiel) verfünffacht werden und man jede Lichtquelle einzeln anpassen muss. Ich gehe davon aus, dass die Lichtquellen sich an der Einheit orientieren und nicht an den Kästchen selbst. Aus eine Lichtquelle, die vorher z.B. 2 Kästchen mit insgesamt 10 Schritt beleuchtet hat, wird eine Lichtquelle, die nun 10 Kästchen mit insgesamt 10 Schritt beleuchtet.

Sofern dieses Verhalten nicht gewollt ist, wäre ich froh, wenn man hier Abhilfe schaffen könnte.

Beste Grüße.

**Comment by Plushtoast** [comment]
Das ist eher von Foundry aus so und vermutlich auch so gewollt. (nicht von DSA)

Die Reichweite der Lichter bleibt ja die gleiche.
Viel mehr wie ein Macro um alle Lichter zu modifizieren is da nicht drin.

**Comment by Arolske** [comment]
Vielen Dank für die Antwort.
Leider bin ich nicht versiert beim Programmieren von Macros und muss wohl beim händischen Ändern bleiben.

Grüße

**Comment by Plushtoast** [comment]
Du kannst folgendes Macro verwenden:

```js
const factor = 0.2

updLight = async() => {

     const updates = canvas.lighting.placeables.map(light => ({
         _id: light.id,
         config: {

            dim: light.config.dim * factor,
            bright: light.config.bright * factor
         }
     }));

     await canvas.scene.updateEmbeddedDocuments("AmbientLight", updates);

 }
 updLight();
```

In der Hotbar unten rechte Maustaste auf einen freien Slot, Code reinkopieren, ggf den Faktor anpassen, Macro Modus auf 'Script' stellen, speichern, macro anclicken.

(Solltest du zu viele clicken geht mit ctrl+y ein Schritt zurück.

**Comment by Arolske** [comment]
Besten Dank für das Script. Es funktioniert nach meinen Wünschen und löst mein Problem.

Danke!
