### ISSUE TITLE
Zusätzliche Zaubererweiterungen aus Magie III 

### ISSUE THREAD

**Issue by Domenic19** [Plushtoast/dsa5-foundryVTT#1583]
Hallo,

die Effekte der zusätzlichen Zaubererweiterungen aus Magie III werden scheinbar aktuell nicht korrekt berechnet. Ich habe es bei den Faxius-Zaubern ausprobiert, wo zum Beispiel "Extremer Schaden" nicht als 2W6 + QS*3 Schaden, sondern weiterhin als 2W6 + QS*2 Schaden berechnet wird. Ebenso tritt der Fehler bei den  Zaubern "Atemnot" und "Blitz dich find" auf, bei dem der zusätzliche Zustandsmodifikator aus  "Beklemmung", bzw. "Starke Sinnesverneblung" nicht funktioniert. 
Die Zaubererweiterungen werden beim Zaubern korrekt angegeben und können angewählt werden, ebenso tauchen sie korrekt im Chatfenster nach erfolgtem Zauber auf. Nur die Berechnung des Schadens/Zustandes erfolgt weiterhin aufgrund der ursprünglichen Schadensformel/Zustandsmodifikator.
Ich kann das gerne noch bei weiteren Zaubererweiterungen testen, es scheint mir aber ein Muster erkennbar.

**Comment by Plushtoast** [comment]
hi, ich schau mir das an aber generell freuen wir uns über hilfe bei den zaubererweiterungen.

es sind einfach zu viele, dass wir sie selbst alle umsetzen und kontrollieren könnten (>5000).

dazu haben wir extra das hier aufgesetzt, wo auch schon fleissige helfer am werk sind: 
https://github.com/Plushtoast/dsa5-extensiondb

wo freiwillige helfen können, wenn sie möchten. fehler reporten hilft allerdings auch bereits

**Comment by Domenic19** [comment]
Hi,

grundsätzlich kein Ding, ich habe aber von Programmierung sowas von keinen
Plan 😏.
Beim Testen und Gegentesten würde ich mich aber gerne nützlich machen.

Lg
Domenic

Plushtoast ***@***.***> schrieb am Mi. 27. Dez. 2023 um 09:39:

**Comment by Plushtoast** [comment]
Extremer schaden sollte mit den modulen ab 5.3.0 funktionieren.
Für alles andere habe ich derzeit leider keine Zeit. Es ist Absicht, dass man auch Erweiterungen anwählen kann, ohne dass sie automatische Effekte bewirken.
Sonst kannst ja deine Wünsche nach speziellen Effekten in der extensiondb äußern, vlt erbarmt sich jemand.

**Comment by Domenic19** [comment]
Ok, danke dir!

Plushtoast ***@***.***> schrieb am Mo. 22. Jan. 2024 um 16:20:
