### ISSUE TITLE
Kann keine Anwendungsgebiete in chat posten

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#1587]
Um herauszufinden, ob ich z.B. vom Fehler in https://github.com/Plushtoast/dsa5-foundryVTT/issues/1532 betroffen bin habe ich das mal getestet.

Eigentlich geht alles, aber Anwendungsgebiete lassen sich gar nicht posten.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/74b609e4-ccee-4fc9-990d-1da2847b112f)

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/cd71db9c-4ee2-4cec-89fd-12cad53a8944)

e hat scheinbar gar keine system property.

**Versions:**
- Foundry Version 11
- DSA/TDE version 5.2.5

**Comment by Plushtoast** [comment]
der verlinkte fehler war ein system neu installieren fehler, der eben dadurch zustande kam, dass man foundry vor dem update nicht gelöscht hat. drüber installieren führt zu mergen von fehlerhaften dateien.
notwendig wegen nodejs update

**Comment by Plushtoast** [comment]
das hier ist unabhängig. das .system muss weg weils schon so in die funktion übergeben wird
