### ISSUE TITLE
Aktiver Effekt mit komplexer Wirkung wird nicht richtig verarbeitet (Bsp. Wildnisläufer)

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#1589]
Ich habe einen Charakter mit der Sonderfertigkeit Wildnisläufer dieser hat standardmäßig den folgenden Aktiven Effekt auf den Charakter.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/bd7e304a-ceaa-49a5-ac83-53662e26ef07)

Dieser Effekt scheint aber syntaktisch nicht ganz richtig zu sein, bzw nicht richtig geparsed werden. Beim Cast schaut es so aus:

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/b3c8a54e-b904-49ed-9afd-a039a57f86a5)

**Versions:**
- Foundry Version 11
- DSA/TDE version 5.2.6

**Comment by Plushtoast** [comment]
is da ein space vor der -1?

**Comment by Plushtoast** [comment]
ahja das komma muss raus

**Comment by Plushtoast** [comment]
so sollts gehen:

Zielkategorie (Pflanzen/Tiere)

Nächster patch erst im Januar

**Comment by Qowy** [comment]
> so sollts gehen:
> 
> Zielkategorie (Pflanzen/Tiere)
> 
> Nächster patch erst im Januar

Besser: 
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/c1250808-ebd4-40a0-88a5-c44b84809b27)

Aber sollte es für "step" nicht auch anzeigen dass Zielkategorie (Pflanzen/Tiere) die Bedingung ist, statt einfach nur den Namen des Effekts?

**Comment by Plushtoast** [comment]
Jup
