### ISSUE TITLE
SchiPs für NSC

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#159]
Nach Grundregelwerk, 4. Auflage, S. 31 können auch Meisterpersonen über SchiPs verfügen. Die sind aktuell leider nicht im NSC-Bogen enthalten. Wäre gut, wenn das nachgetragen werden könnte. :)

**Comment by Plushtoast** [comment]
Unlustigerweise war das urpsrünglich sogar schon mal drin und wurde wieder abgeschafft :)
