### ISSUE TITLE
Rüstungsbeschädigung wirkt sich bei Zonenrüstung nicht auf den angezeigten Rüstungswert aus

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#1590]
Man nehme einen Charakter mit Zonenrüstung. Z.B. 4 auf alles außer Kopf.
Jetzt beschädigt man diese Rüstung auf 3/4.

Da in actor-dsa5.js zeile 1081 immer nur mit `i.system.protection.value`  gerechnet wird, wird nur der Torso wert im UI angepasst:

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/3ef36406-975e-42c1-a696-bf4588835e79)

Im Kampf funktioniert es aber korrekt, (armorzone.js 150 rechnet nochmal den Rüstungswert für die Trefferzone neu aus) allerdings ist der Tooltip beim mouse over über die -3 immer kaputt:

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18251934/3ba29276-d716-462e-a89e-62f884d900ca)

Meine Idee wäre jetzt gewesen Zeile 1080ff so anzupassen:
```

if (i.system.worn.value) {
  i.system.protection.value = EquipmentDamage.armorWearModifier(i, i.system.protection.value);
  totalArmor += Number(i.system.protection.value);
  armor.push(i);
}

```

zu

```
if (i.system.worn.value) {
  for (let property in i.system.protection) {
    if (i.system.protection.hasOwnProperty(property)) {
        let value = i.system.protection[property];
        i.system.protection[property] = EquipmentDamage.armorWearModifier(i, value);
    }
  }          
  totalArmor += Number(i.system.protection.value);
  armor.push(i);
}

```

Das hat in meinen Tests die Anzeige behoben und auch nichts weiter bei der Kampfberechnung kaputt gemacht.
Da es im Kampf aber eh schon richtig berechnet wird, ist es evtl auch einfacher auf diese Werte zurückzugreifen?

Der Tooltip Fehler  bleibt aber natürlich unabhängig davon.

**Versions:**
- Foundry Version 11
- DSA/TDE version 5.2.6

**Comment by Qowy** [comment]
Ich merke auch gerade, es gibt hier noch ein anderes Problem.
Durch die Rüstungswertänderung bei Beschädigung wird auch die ausgerechnete Gesamtbelastung der Rüstung geringer, dass ist ja gerade nicht der Fall.

Ich habe nachgeschaut das war schon vor meiner Änderung so, aber da ist es nicht so schnell aufgefallen, da ja immer nur der Torso angepasst wurde.

Ich denke mal das beste wäre dann, da die Kampfberechnung wirklich schon passt, nur vor dem rendern des Templates diesem korrigierte Werte zu geben, und die Werte des Actors in Ruhe zu lassen?

Vermutlich müsste man in armorzone.js `renderArmorZones` nochmal einen pass über die Items machen und auf Beschädigung checken aber erst nachdem die encumbrance berechnet wurde.
Und dafür das in actor-dsa5 ganz weglassen, aber nur wenn armorzones enabled sind, sonst geht es ja für die ohne Armory2 kaputt.

Ob diese interdependencies so schön sind...

Evtl muss man einfach nochmal einen Propertiy block einfügen names OriginalArmor oder so der einfach immer die Werte der Rüstung ohne Beschädigungen hat, und Doch wieder die Lösung von oben nehmen und die Zone encumberance dann darauf berechnen.

Ich bin mir sicher dir fällt eine gute Lösung ein :D

**Comment by Qowy** [comment]
Ok 3. Versuch, bis jetzt denke ich der Beste

in armorzone.js ersetze ich renderArmorZones hiermit:
```

static renderArmorZones(elem, html, data) {
    const type = elem.object.type
    if (type == "character" || (type == "npc" && game.settings.get("dsa5-armory2", "enableArmorZonesNPC"))) {

        let totalEncumbrance = 0
        const armorZones = duplicate(ArmorZones.armorZones)
        const factors = duplicate(ArmorZones.factors)
        for (let key of Object.keys(armorZones)) {
            for (let armor of data.prepare.wornArmor) {
                if (armor.system.protection[key] != 0) {
                    // Calculate totalEncumbrance before modifying armor.system.protection[key]
                    totalEncumbrance += armor.system.protection[key] * factors[key]

                    // Modify armor.system.protection[key] with a call to game.dsa5.apps.EquipmentDamage.armorWearModifier()
                    let modifiedValue = game.dsa5.apps.EquipmentDamage.armorWearModifier(armor, armor.system.protection[key]);
                    armorZones[key].total += modifiedValue
                    armorZones[key].armors.push({ name: armor.name, val: modifiedValue })
                }
            }
            armorZones[key].total += data.actor.system.totalArmor || 0
        }
        mergeObject(data, {
            armorZone: {
                totalEncumbrance: {
                    value: ArmorZones.calcEncumbrance(totalEncumbrance).enc,
                    sum: totalEncumbrance
                },
                armorZones,
                bonusArmor: data.actor.system.totalArmor
            }
        })

        renderTemplate("modules/dsa5-armory2/templates/wornArmorItems.html", data).then(temp => {
            html.find('.wornArmorItems').replaceWith(temp)
            html.on('click', '.wornArmorItems .item-edit', ev => {
                ev.preventDefault()
                const itemId = elem._getItemId(ev);
                const item = elem.actor.items.get(itemId)
                item.sheet.render(true);
            });
        })
    }
}

```

Und actor-dsa5.js bekommt eine settingsabrage um das reduzieren der Rüstung wegzulassen, wenn armorzones aktiviert sind (evtl. braucht das noch eine abfrage, was mit npc armor zones ist?)

```
if (i.system.worn.value) {
  if(!game.settings.get("dsa5-armory2", "enableArmorZones"))
    i.system.protection.value = EquipmentDamage.armorWearModifier(i, i.system.protection.value);
  totalArmor += Number(i.system.protection.value);
  armor.push(i);
}
```

**Comment by Plushtoast** [comment]
Kannst du mich ggf. mal auf Discord kontaktieren (Huepfklotz)
