### ISSUE TITLE
Simularcum verursacht Fehlermeldung

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1593]
**Describe the bug**
Simularcum (groß und klein) lassen sich nicht verwenden

**To Reproduce**
Kreatur erstellen, Paktgeschenk geben und versuchen es anzuwenden

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/122533617/17772169-7399-4383-a052-084b3ab54c1f)

**Versions:**
- Foundry Version: 11.315
- DSA/TDE version: 5.2.7
- Related modules version: Pandemonium I & II Version 5.1.1

**Comment by Plushtoast** [comment]
const lang = game.i18n.lang == "de" ? "de" : "en"

im macro einfügen im Macros (internal) Kompendium ganz oben, oder auf Patch warten.

Patch dafür kommt erst im Januar

**Comment by Ogrimgro** [comment]
Funktioniert. Super. Danke
