### ISSUE TITLE
AP Kosten Berechnungen der Kampftalente fehlerhaft

### ISSUE THREAD

**Issue by ChrisFeedback** [Plushtoast/dsa5-foundryVTT#160]
Die AP, welche berechnet werden wenn man die Kampftalente per "+" steigert entsprechen nicht den erwarteten Kosten. Zudem werden nicht die gleichen AP wieder freigegeben, wenn man die selben Kampftalente per "-" wieder reduziert.

Vorgehen beim Test:

1. Namen für den Helden vergeben
2. 1100AP gesamt gesetzt
3. Eigenschaften gesteigert mit 540AP
4. Kampftalente Dolche 13, Hiebwaffen 12, Raufen 12, Wurfwaffen 12 gesteigert
--> Ausgegebene AP stehen auf 582, sollten aber 598 betragen
6. Kampftalente zurückgesetzt auf Dolche 6, Hiebwaffen 6, Raufen 6, Wurfwaffen 6
--> Ausgegebene AP stehen unter 540AP (genauen Wert hatte ich nicht notiert)

Anmerkung: Der Fehler tritt nur dann reproduzierbar auf, wenn alle Kampftalente zusammen gesteigert werden. Jedes Talent für sich führt zu den erwarteten AP Kosten und gibt die selbe Menge auch wieder frei.

 - OS: Win7
 - Browser Edge
 - Version Foundy 0.7.9
 - Version Active Modules 141.1.4

**Comment by Plushtoast** [comment]
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/FAQ#changing-the-values-in-the-input-field-for-talentcombatskill-and-others-does-not-calculate-the-used-adventure-point-cost

Nicht nachvollziehbar.
