### ISSUE TITLE
Gegenstände löschen sich aus dem Inventar

### ISSUE THREAD

**Issue by Dicio83** [Plushtoast/dsa5-foundryVTT#1614]
**Describe the bug**
Wenn man im im Charaktersheet unter "Ausrüstung" Gegenstände mit Linksklick anklickt, diese geklickt hält, leicht verschiebt und wieder los lässt, verschwinden sie komplett aus dem Inventar. Dies trifft auf alles zu, bis auf Behältnisse.

**To Reproduce**
1. Go to 'Charaktersheet'
2. Click on 'Beliebiges Item, geklickt lassen, verschieben, loslassen'

**Expected behavior**
Das Item sollte nicht verschwinden, sondern im Inventar bleiben.

**Screenshots**
https://youtu.be/7I2jJDiEVP4

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.2.8
- Related modules version Ich habe nur das Modul DSA 5 Core aktiviert.

**Comment by Plushtoast** [comment]
Das sollte so richtig sein.
Es passiert eins von zwei Dingen:

* Du hast das Item in eine Tasche gelegt
* Items die gleich sind werden gestackt (die Anzahl geht hoch), machst du das mit items die keine anzahl haben, sieht es aus als ob sie verschwinden

**Comment by Dicio83** [comment]
Moin, 

dem ist leider nicht so. Wie im Video zu sehen ist, ist im Lederrucksack weiterhin nichts vorhanden. (Es fehlt auch der DropDown Haken, welcher die Tasche aufklappt, wenn etwas drin ist - s. Bild - hier habe ich etwas per Hand reingepackt und der DropDown Haken erscheint) 

Mit manuell zugefügten Inhalt:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/116867654/8220deb2-3ace-4098-8e4c-f7b89f3b58d7)

Ohne Inhalt:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/116867654/c4e74e96-7dc3-4c03-969b-83db2f92fcce)

**Comment by vt-tom** [comment]
Ich kann das ganze auf Objekt Ebene bestätigen:
Hier der Actor Arbosch vor dem Verschieben:  
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/163a7002-fd3d-4614-be6f-6fe130f04372)  

Und hier danach:  
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/d177ce0a-0654-49fb-8ffd-25126d11bf65)

**Comment by vt-tom** [comment]
Es gibt keine Tasche:  
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/ab0163a1-664f-4f99-9083-e35a8b483d4e)  

Und auch keine Abgelegten Items als Actor:  
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/80099175/897a0145-dbb0-4ace-81f8-e4e8ec35dcf5)

**Comment by Plushtoast** [comment]
ok, erstaunlicherweise sollte dieser bug schon sehr lange unbemerkt da sein (> 1 jahr)
