### ISSUE TITLE
Automatisch hingezugefügte Betäubung wird direkt wieder gelöscht

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#1629]
**Describe the bug**
Wird `Betäubung` automatisch über eine SF wie Berserkerangriff oder Gegenhalten hinzugefügt, wird er direkt wieder gelöscht.

**Expected behavior**
`Betäubung` sollte bestehen bleiben.

**Additional context**
Die Ursache scheint in Actordsa5.postUpdateConditions()/Actordsa5.deferredEffectAddition() zu liegen.

**Comment by zoidable** [comment]
```
    const brawlingPoints = actor.woundPain(data, "temporaryLeP")
    if (brawlingPoints) {
      await this.deferredEffectAddition("stunned", actor, brawlingPoints)
    }
```
in https://github.com/Plushtoast/dsa5-foundryVTT/blob/foundry11/modules/actor/actor-dsa5.js#L284 würde das beheben. Oder soll sowas wie https://github.com/Plushtoast/dsa5-foundryVTT/blob/73e4b5180f908b05af45b0e2c23d7d031018eab3/modules/system/dice-dsa5.js#L779 mit auto=false erfolgen? Also z.B. `DSA5_Utility.getSpeaker(testData.extra.speaker).addCondition("stunned", 1, false, false)`

**Comment by Plushtoast** [comment]
Fast. Der optionale Parameter auto sollte per default false sein und nur für die automatischen dann true.
Das macht mehr sinn seit dem update mit dem kumulativen status effekten.
