### ISSUE TITLE
Eingenschaftswerte Orkenzombie: KO, KK, LeP

### ISSUE THREAD

**Issue by hnsstrk** [Plushtoast/dsa5-foundryVTT#1635]
Laut Nekromanthäum haben die Orkenzombies KK und KO von jeweils 17 und 22 LeP.
Im FVTT sind KK und KO bei 15 und die LeP bei 18.

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/55b4c0ca-3808-4530-84e1-a1f4155164cf)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/46eb1cf7-81d5-41ca-8e9c-0a09c6b4e451)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.3.2
- Related modules version
  - dsa5-necromantheum  5.1.0
  - dsa5-orcs 5.1.0

**Comment by Plushtoast** [comment]
necro aktuaalisiert,
orcs mit dem nächsten update in ~3 monaten
