### ISSUE TITLE
Kritischer Erfolg beim Angriff, die negativen Effekte werden auf den Angreifer angewendet

### ISSUE THREAD

**Issue by hnsstrk** [Plushtoast/dsa5-foundryVTT#1638]
**Describe the bug**
Kritischer Erfolg beim Angriff, die negativen Effekte werden auf den Angreifer angewendet.

**To Reproduce**
Normale Kampfrunde.
Kritischer Erfolg über SL-Willkür erzwingen.
Verteidigung ausführen
Effekt des kritischen Erfolgs anwenden.

**Expected behavior**
Die Effekte des kritischen Erfolges eines Angriffs sollen auf den Gegner angewendet werden.

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/9ef68d9c-57dd-49cf-9f06-c8e4a435ab82)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/b9b9a23f-7813-447a-84ed-d091ec1d9f1d)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.3.3

**Additional context**
[fvtt-log-Sat-Jan-27-2024.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/14073089/fvtt-log-Sat-Jan-27-2024.txt)

**Comment by hnsstrk** [comment]
Ich kann den Fehler ein bisschen weiter eingrenzen. Es hängt mit den Trefferzonen zusammen.
Der Kritische Erfolg wird soweit korrekt angerechnet. Der Effekt der Trefferzone wird aber auf den Verursacher und nicht auf das Ziel angewendet. 

Müsste also am Kompendium 1 oder 2 liegen.

**Comment by hnsstrk** [comment]
In einer neuen Welt, nur mit den Core Modul und den Kompendien kann man bei aktivierten Trefferzonen nicht angreifen:

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/eb77a728-f74d-4158-9197-4bfef79488e9)

Ich kann bei Bedarf gerne auch detailiert Testfälle durchführen. Ich weiß nur aktuell nicht worauf es ankommt.

**Comment by Plushtoast** [comment]
ich kann das nicht nachvollziehen.

welche schritte machst du genau?

was passiert wenn du in der console "game.dsa5.config.hitzones" eingibst?

**Comment by hnsstrk** [comment]
Ich habe eine Welt mit den folgenden Modulen erstellt:

- German [Core] v11.1
- TDE5 - Aventurian Armory v5.3.1
- TDE5 - Aventurian Armory II v 5.1.0
- TDE5 - Compendium I v5.3.1
- TDE5 - Compendium II v 5.3.0
- TDE5 - Core Rules 5.3.1

Ich verwende die folgenden Einstellungen:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/84e6e38b-8690-4b26-bca2-6fb2411aa1df)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/def500b6-1e41-4610-9a82-9d9b21fee4b2)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/7a84c288-3436-400d-9b32-7236c6a263db)

Dann erzwinge ich als SL einen bestätigten kritischen Erfolg bei einem Nahkampfangriff und wähle eine Trefferzone. Dann klicke ich auf "Kritischer Angriff" und der Effekt lässt sich anwenden.
Diese tut er nicht auf den Angegriffenen sondern auf den Angreifer.

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/3907750/84e5a560-2f96-49d8-a2cf-489c66f512a0)

In diesem Fall greift *Rashid al'Fasar* **Thallian** an. Zu Boden würde aber *Rashid al'Fasar* stürzen.

```game.dsa5.config.hitzones``` Hierfür gibt es auf der Konsole scheinbar keine Ausgabe.

**Comment by Plushtoast** [comment]
ok habs danke. 
das ganze crit system ist aber so kompliziert dass es leider noch mehr bugs haben wird oder unpräzise funktioniert.
falls du noch mehr findest und feedback hast gerne

**Comment by hnsstrk** [comment]
Immer gern.
Und Danke.
