### ISSUE TITLE
DSA5-CORE - Sturmangriff wird nicht angezeigt bei der Angriffsauswahl.

### ISSUE THREAD

**Issue by Violettdragon** [Plushtoast/dsa5-foundryVTT#164]
Habe aber schon den Fehler entdeckt: Die Berechnung "+2+GS/2 TP" funktioniert nicht. Selbst nur "+GS/2 TP" oder "+GS TP" wird nicht berechnet. 
Wenn ich eingebe: "+GS/2 TP, +2 TP" zeigt er Sturmangriff nur mit +2 TP an.
"+2+4 TP" funktioniert zB. auch nicht. Bei "+2TP, +4TP" wird zwar angezeigt, aber nur die letzte + TP berechnet.
Das selbe ist auch beim selbst erstellten "Schildstoß" Effekt: "TP/2" wird nicht angezeigt.

**Comment by Plushtoast** [comment]
Beliebige Formeln sind nicht möglich momentan.
Dazu muss das System erst noch massiv verbessert werden.
Sturmangriff sollte aber mit Patch (bald)  funktionieren.

**Comment by Violettdragon** [comment]
Ich danke dir vielmals für die ganzen mühen die du hier hast. 
Du machst eine tolle Arbeit. Wollte ich mal loswerden ;)
