### ISSUE TITLE
Dropping of items creates tile and actor

### ISSUE THREAD

**Issue by Scarjit** [Plushtoast/dsa5-foundryVTT#1641]
**Describe the bug**
When dropping an item from a character sheet or from the libary, it first creates a tile, and then asks if an actor shall be created too.
The tile cannot be interacted with as a player, and is therefore useless.

**To Reproduce**
1. Open the Libary or character sheet
2. Drop any item on the ground
4. A tile will be created and a popup will ask how many items to drop
5. If the popup is confirmed the actor will also be created.

**Expected behavior**
Only the actor should be created.

**Screenshots**
![firefox_YCwyp4OqAh](https://github.com/Plushtoast/dsa5-foundryVTT/assets/6317420/5eafd1fc-0231-471c-9304-02dae1ed72c2)

**Versions:**
- Foundry Version: `11.314`
- DSA/TDE version: `5.3.3`
- Related modules version

![firefox_kVi3Dag71U](https://github.com/Plushtoast/dsa5-foundryVTT/assets/6317420/d89621e8-27c4-4e92-8647-924201146c8d)
![firefox_NmIzd6kDOt](https://github.com/Plushtoast/dsa5-foundryVTT/assets/6317420/e3c136ba-b2fa-48bc-9ef8-adf8cb7189c1)

**Comment by Dicio83** [comment]
Guess it´s not a bug - it´s a feature. Dont know why. Maybe to show only the picture to your player, while you hide the actor(trader)

**Comment by Plushtoast** [comment]
Can you disable all modules except DSA and test again? That's not default behaviour but I think it's coming from another module.
DSA only should creater  an interactable actor (so others can loot the dropped stuff too)

In case you want t he tiles, there is a option in the settings to trun the item dropping off for DSA
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/e2e83827-55d8-4b64-96ca-b4b90f49479e)
