### ISSUE TITLE
Meister NSC Zuchtgrube alle Tokens

### ISSUE THREAD

**Issue by Ginkgo85** [Plushtoast/dsa5-foundryVTT#1644]
**Is your feature request related to a problem? Please describe.**
Ich finde Schade, das bisher immer nur die Standard Token zur Auswahl stehen. Kann man nicht wenn man Module erworben hat, das die Zuchtgrube alle Tokens der NSC anzeigt ? 

**Describe the solution you'd like**
Es sollten von allen Modulen die man erworben hat, die Tokens und Eigenschaften zur Auswahl stehen. 

**Describe alternatives you've considered**
Bisher ist es sehr mühsam die Tokens von anderen Modulen zu suchen. Man muss immer manuell alle Ordner durchsuchen, Ordner für oder. Besteht nicht die Möglichkeit, das automatisch alle Tokens angezeigt werden von allen erworbene Modulen ? Das wäre viel passender also nur die Standard Token in der Zuchtgrube. Vielleicht kann man dies bei Werkstatt des Meisters mal aktualisiert.

**Comment by Plushtoast** [comment]
schon über nehm jahr auf dem plan, scheitert aber an meiner verfügbaren zeit

**Comment by Ginkgo85** [comment]
Ja aber es ist wenigstens auf dem Plan. Dann ist es zumindest auf dem Schirm ;-)

**Comment by Ginkgo85** [comment]
Und es wäre dennoch sehr schön wenn es früher oder später erscheint .... ;-)
