### ISSUE TITLE
Verband mit unterschiedlichen Gewichtseinheiten

### ISSUE THREAD

**Issue by RodiakWolfshain** [Plushtoast/dsa5-foundryVTT#1645]
**Describe the bug**
Der Gegenstand "Verband" kann in unterschiedlichen Modulen gefunden werden. 
Core, Companions & Armory. 
In jedem Modul wird er mit einem anderen Gewicht & Preis gelistet. Korrekt ist jedoch nur die Info aus dem Core Modul. 

**To Reproduce**
Öffnen der Bibliothek
Suche nach "Verband"
Öffnen der Items 
- Verband (Core): Gewicht 0,005 bei 1.25 Silber
- Verband (Companions): Gewicht 0,5 bei 1 Silber
- Verbandszeug (Armory): Gewicht 0,05 bei 1,25 Silber

**Expected behavior**
Nach Regeln sollten 10 Verbände ein Gewicht von 0,05 haben und 12,5 Silber kosten. Daher sind nur die Angaben im Core korrekt.

**Versions:**
- Foundry Version: 11.315
- DSA/TDE version: 5.3.4
- Related modules version: Armory: 5.3.1, Core: 5.3.1, Companions: 5.3.0

**Additional context**
Für den Fall das der Verband aus dem Companions Modul für Tiere gedacht ist, und er deswegen andere Werte hat, so wäre eine gesonderte Hervorhebung dessen wünschenswert.
Aufgefallen ist mir das nur, als ich bei einem neuen Charakter bei der Erstellung ein Wildnispaket gekauft hab, und mich danach wunderte warum der Held 5 Stein an Verbänden mit sich herum schleppt. Hier wurden vom System (obwohl in der Info eindeutig der Verband aus dem Core verlinkt ist) einfach die Verbände aus dem Companion Modul "gekauft"

**Screenshots**
![Screenshot 2024-02-17 001309](https://github.com/Plushtoast/dsa5-foundryVTT/assets/65841447/2e59c0d6-44b3-48b8-af21-3b25558360f7)

**Comment by Plushtoast** [comment]
Ich denke sie unterscheiden sich, weil wir nirgendwo eine Angabe gefunden haben was korrekt ist. In der armory steht außerdem afaik beim verbandszeug dass zusätzliche materialien wie salben oder sowas dabei sind (deswegen der andere name)

**Comment by RodiakWolfshain** [comment]
Alles klar. Danke für das Feedback :)
