### ISSUE TITLE
Kann keine Macros in die neue Tokenhotbar ziehen

### ISSUE THREAD

**Issue by illowt** [Plushtoast/dsa5-foundryVTT#1647]
Überschrift spricht für sich ;-)
Siehe hierzu auch Screenshots im Discord // Die Gießerei // dsa // TWolli — 16.02.2024 16:06
https://discord.com/channels/749312958823268352/749321469590241383/1208066970432307271

**Comment by Plushtoast** [comment]
Funktioniert bei mir einwandfrei. kann es sein, dass du das macro auf nem höheren slot ablegst >10 und dann nicht scrollst?

**Comment by illowt** [comment]
ne, leider nicht

**Comment by illowt** [comment]
So gehts
<img width="317" alt="image" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/62432787/dc198f92-365b-41ea-8d9d-d1609d1eb57a">

**Comment by illowt** [comment]
So nicht
<img width="472" alt="image2" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/62432787/3b355a8a-647c-412f-8699-dd2420440b5f">
So auch nicht
<img width="469" alt="image3" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/62432787/21b7d8b4-d403-4b20-b399-81858cff7abe">

**Comment by Plushtoast** [comment]
Geht bei mir immer in jedem browser.
Öffne mal die konsole mit f12 und schau ob ein roter fehler angezeigt wird beim droppen
