### ISSUE TITLE
Anzeige des Ausweichen Werts im Kampfbogen

### ISSUE THREAD

**Issue by Kallimeister** [Plushtoast/dsa5-foundryVTT#1648]
Für mich als Spielleiter fände ich es praktisch den Ausweichenwert von Kreaturen etc. direkt im Kampfbogen angezeigt zu bekommen. (z.B. direkt in der Schaltfläche in Klammern z.B. "Ausweichen (7)").
Ich nutze Foundry beim spielen am Tisch und würfle dann per Hand, aber auch zur Nutzung in Foundry ist es praktisch um schneller entscheiden zu können ob man pariert oder ausweicht. So würde man sich das Wechseln auf den Eigenschaften Tab zum nachschauen welcher Wert der Höhere ist ersparen.
Selbes wäre wohl auch für Waffenloser Angriff und Waffenlose Verteidigung praktisch.

**Comment by mckee14** [comment]
sobald du in einem kampf bist und angriff oder verteidigung wirfst, siehst du doch direkt vor dem werfen schon, wie hoch der wert ist. da werden auch die ganzen modifikatoren bereits berücksichtigt. also genau das, was du möchtest...kann es sein, dass du ohne kampftracker und ziel wirfst in foundry?Gesendet von unterwegsAm 18.02.2024 um 10:39 schrieb Kallimeister ***@***.***>:﻿
Für mich als Spielleiter fände ich es praktisch den Ausweichenwert von Kreaturen etc. direkt im Kampfbogen angezeigt zu bekommen. (z.B. direkt in der Schaltfläche in Klammern z.B. "Ausweichen (7)").
Ich nutze Foundry beim spielen am Tisch und würfle dann per Hand, aber auch zur Nutzung in Foundry ist es praktisch um schneller entscheiden zu können ob man pariert oder ausweicht. So würde man sich das Wechseln auf den Eigenschaften Tab zum nachschauen welcher Wert der Höhere ist ersparen.
Selbes wäre wohl auch für Waffenloser Angriff und Waffenlose Verteidigung praktisch.

**Comment by Kallimeister** [comment]
Ich spiele am Tisch und nutze dann oft Kampftracker und Foundry Würfelfunktion nicht, da meine Spieler nicht in Foundry eingewählt sind, sonder habe nur die Bögen offen um mir die Werte anzeigen zu lassen. Deshalb komme ich gar nicht so weit, dass mir über das Reaktionsfenster die Werte dann angezeigt werden.
Bei den Waffen kann man ja die Werte direkt sehen, da ist es kein Thema, aber eben beim Ausweichen etc. muss man dann erst etwas umständlich sich die Werte raussuchen.
Wäre ein "Nice-to-have"-Feature um eben alle relevanten Werte auf einen Blick zu sehen.

**Comment by Plushtoast** [comment]
Btw die angezeigten Werte sind zb ohne Belastung. Man sieht auch hier den Endwert erst, wenn man drauf clickt.
