### ISSUE TITLE
Beschwörung (Golem) funktnioniert nicht

### ISSUE THREAD

**Issue by Schorschus** [Plushtoast/dsa5-foundryVTT#1651]
Sobald ich das Beschwörungsmenu benutze (in diesem Fall beim Golem) und dann im letzten Schritt auf "Fertigstellen" klicke, 
wird die beschworene Kreatur nicht  ins Akteurs Menu gezogen.

Die Ordner werden erstellt (Beschwörung / Golem) aber keine Kreatur taucht auf.

Folgender Fehler in der Console:

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/008705e0-8f17-4360-9097-89854a9b4225)

**Versions:**
- Foundry Version 3.1.5
- DSA/TDE version 5.3.4
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Kannst du eine liste der dsa kreaturen module die du verwendest hinzufügen?

**Comment by Schorschus** [comment]
Jo, klar :
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/6a9750ac-3abd-405d-b382-f3b554d79c6e)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/6b71effc-8307-47fc-8313-4fd843f77dc1)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/97557642/bb759bf2-0923-4b0b-973a-e88a55227911)

**Comment by Plushtoast** [comment]
Sollte mit update von magie-3 und elementarium ok sein
