### ISSUE TITLE
Alte Makrobar - Einstellung weg?

### ISSUE THREAD

**Issue by zarazandra** [Plushtoast/dsa5-foundryVTT#1659]
Mehr eine Frage, weil ich gerade echt überfordert bin: 

beim letzten Update konnte man noch wählen, ob man die neue oder die alte Makroleiste nutzen wollte - jetzt finde ich die Einstellung nicht mehr. Ich mag die neue Leiste gar nicht und würde mir lieber wieder die Alte wünschen. 

Jetzt die eigentliche Frage: ist die Einstellung weggefallen oder ist sie zu gut versteckt?

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/4d0095b1-dd95-4fd6-a5b9-ec22ab841473)

**Comment by Plushtoast** [comment]
Was du da zeigst ist nicht die leiste wie sie ausgeliefert wurde
In den optionen gibts tokenhotbar settings da kann mans austaucshen, ansonsten zeigt vttom das auch im changelog video

**Comment by zarazandra** [comment]
> Was du da zeigst ist nicht die leiste wie sie ausgeliefert wurde In den optionen gibts tokenhotbar settings da kann mans austaucshen, ansonsten zeigt vttom das auch im changelog video

Ja, die hab ich nicht mehr gefunden - die Optik kommt nur von nem Skin, aber die Unterteilung, die neuerdings da drin ist, mag ich nicht. 
Ich schaus mir mal an, danke.

**Comment by Plushtoast** [comment]
Magst du noch erklären was dich an der neuen Variante stört? Hast du die alten floating tokenbar verwendet?

**Comment by zarazandra** [comment]
> Magst du noch erklären was dich an der neuen Variante stört? Hast du die alten floating tokenbar verwendet?

Ja, kann ich gern machen. Zum Einen springt sie immer wieder zurück auf die Multiunterteilung, auch wenn man eine Kategorie ausgewählt hat (Edit: beim Ausprobieren ist es diesmal nicht weggesprungen, müsste nochmal schauen, wann genau das passiert). Das Scrollen ist damit aber auch nicht so wirklich hilfreich, weil er oft Zeilen überspringt und man dann nur mit dem Scrollbalken ganz fummelig die Zeile auswählen kann, die man möchte. Dabei verschwinden auch so gut wie immer Kontextmenüs. Inwiefern das ne Wechselwirkung mit anderen Modulen ist, kann ich nicht sagen. Da aber sonst alles funktioniert, möchte ich deswegen ungern umstellen. 

Ich mag es grundsätzlich lieber, mir die Leiste so zu bestücken, wie ich das gern für mich hätte. Bei der alten Leiste hatte ich einfach in einer Zeile eine gute Übersicht über zehn Buttons, die ich einfach anklicken konnte - in der neuen geht eigentlich nichts mehr wirklich ohne Scrollen. Beispielsweise habe ich mir die Charakterblätter meiner Spieler einfach draufgezogen. Ich wechsle die Leiste und habe alle Charaktere sauber aufgelistet und erreichbar, ohne erst in den Akteurtab zu müssen. Das ist ein Klick. 
In der neuen unterteilten Leiste ist das wesentlich komplizierter - Kategorie wechseln, scrollen, versuchen, die richtigen Zeilen zu erwischen ... Ich häng mal paar Bilder an, um das zu verdeutlichen. 

Hab die Einstellung zwischenzeitlich wiedergefunden. Manchmal sollte man einfach die Augen aufmachen, das hilft ungemein. :D

Edit: Eine Sache noch - da ich viele Sachen in der zweiten Makroleiste ebenfalls drin habe, ist mir da zu viel doppelt, was ich extra noch bearbeiten müsste. Und ich mag die zweite Leiste sehr - zum Einen weil sie beweglich ist und zum Anderen, weil sie dynamischer ist. 
Edit 2: Wenn man Kategorien abwählen könnte, wäre das ja auch schon hilfreich. 

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/4efd9475-3169-49c5-9de4-df783a50efe6)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/74f1f9d0-7f0a-4488-a6cc-4c70e5e528b9)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/c3a693ce-6de6-4639-a850-0d1e065b420b)
gegen:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/f90396b8-ebdc-41d2-8a69-7811317a6a3e) - eine Leerreihe mit verschwendetem Platz
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/07ef9b81-1f1a-4906-a396-16d463abafa2) - Kontextmenü ist nicht benutzbar. 
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/862e321a-0942-41ce-bb24-498d4eda0645) - doppelte Makros, die ich in der unteren Leiste auch nicht löschen kann (Rechtsklick löst aus)

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/a8fc40cf-023e-4174-a800-521063b76c02)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/23161e1f-177f-40b1-a638-4e8365ef891d)
Unterschied von ein Mal scrollen in der Bar

Also in Summe ist die neue Unterteilung unglaublich unübersichtlich und kaum sinnvoll nutzbar für mich. 
Wenn die alte Makrobar grundsätzlich auf zweizeilig erweitert werden würde - also einfach ohne die Kategorien, und so bestückbar, wie ich das will, dann wäre das für mich eher interessant.

**Comment by Plushtoast** [comment]
Das zurückspringen auf die multiunterteilung ist schon gepatcht. Das mit dem scrollen kann ich nicht nachvollziehen. Welcher browser ist das? Normalerweise snapt das automatisch. Liegt vlt auch an diesem skin

**Comment by Plushtoast** [comment]
Gibts auch probleme mit dem scrollen wenn keine Module aktiviert sind? In einer frischen welt?
