### ISSUE TITLE
Umwandlung von NPC zu PC und umgekehrt

### ISSUE THREAD

**Issue by zarazandra** [Plushtoast/dsa5-foundryVTT#1664]
Ich bin auf etwas ein Problem gestoßen, das ich bisher nicht lösen konnte - entweder, weil die Funktion zu versteckt ist oder es sie schlichtweg nicht gibt. 

Ich wollte einen neuen Charakter einstellen für einen Spieler. Da ich aber das Heldenerstellungsgedöns übergehen wollte, weil ich eh die Daten von der PDF übertrage, dachte ich mir, ich sei Schweinchen Schlau. Ich hab einfach in der NPC-Zucht einen entsprechenden Char erstellt und dann nur die Werte angepasst. Hab dann aber festgestellt, dass ich den Charakter nicht einfach in einen Spielercharakter umwandeln konnte. Bei der Sheetwahl konnte ich nur zwischen NPC, Merchant und Herbarium-Bogen wechseln 
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/8c2c229d-0d17-47fc-8025-044d260ed9c3)

Eine weitere Möglichkeit wäre, einfach einen neuen Helden zu erstellen und mit einem Klick die Heldenerschaffung zu übergehen, damit man einfach einen Übertrag machen kann, ohne erst alles durchklicken zu müssen, wenn man eventuell eh wieder die Hälfte davon rausschmeißen muss. Klar, wenn ich manuell dann Rasse und Profession reinziehe, muss ich das eh durchklicken, aber so Sachen wie die Vor- und Nachteile werden dann zumindest nicht durchgefragt. Ist immerhin paar Klicks schneller.

**Comment by Plushtoast** [comment]
sobald du ne profession ne spezies oder ne kultur hinzufügst ist der heldenerschaffungsbutton weg

npc in spieler wandeln is technisch nicht vorgesehen

**Comment by illowt** [comment]
**Tipp:** Erstell dir einen neuen SC-Bogen und dann überträgst du per Drag & Drop alles vom NPC auf den richtigen Bogen. Zahlenwerte wirst ohnehin selbst anpassen gehe ich von aus.
