### ISSUE TITLE
Tooltip so anpassen, dass er das Eingabefeld nicht überlappt

### ISSUE THREAD

**Issue by zarazandra** [Plushtoast/dsa5-foundryVTT#1665]
Keine Ahnung, ob das wirklich ein Bug ist, aber mir ist aufgefallen, dass manche Tooltips einen sehr behindern, wenn man einen Wert anpassen will. 

Beispiel: 
![Screenshot 2024-03-05 141814](https://github.com/Plushtoast/dsa5-foundryVTT/assets/70195103/923ae46b-323a-475e-b132-7ac7eef9a26a)
Will man die Anzahl der AsP, LeP etc ändern, kommt sofort der Tooltip, wenn man über der Zahl ist. Ich weiß nicht, ob ich jetzt richtig reingeklickt habe, ob der Inhalt bereits vormarkiert ist und ich einfach die neue Zahl eintippen kann oder erst die Alte wegmachen muss. 
Könnte man den Tooltip nicht an die Seite oder drunterpacken dafür?

**Comment by Plushtoast** [comment]
das macht foundry automatisch richtig normalerweise...

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/97a61f53-57e3-4e2c-a8cd-6778cfc8c368)

**Comment by Plushtoast** [comment]
Ich schätze da kann ich nicht helfen. Das liegt entweder an deinem browser oder an den drittmodulen die du verwendest

**Comment by zarazandra** [comment]
alles klar, danke!
