### ISSUE TITLE
Reihenfolge der Chatlogs im Kampf ändern

### ISSUE THREAD

**Issue by ChrisFeedback** [Plushtoast/dsa5-foundryVTT#167]
Wenn man einen Genger auswählt und einen AT Wurf würfelt erscheint aktuell folgendes in der Reihenfolge im Chat:
1. AT Wurf mit Details, ggf. Schadensberechnung
2. Info "Alrik gegen Ork"
3. PA Wurf mit Details
4. Info wer gewonnen hat und wie hoch der Schaden ist

Meiner Ansicht nach wäre es übersichtlicher, wenn die Meldungen 1 und 2 getauscht würden und somit folgendes Erscheint:
1. Info "Alrik gegen Ork"
2. AT Wurf mit Details, ggf. Schadensberechnung
3. PA Wurf mit Details
4. Info wer gewonnen hat und wie hoch der Schaden ist

Dies würde auch dem klassischen, offline Vorgehen entsprechen, bei dem erst angesagt wird wer angegriffen werden soll, bevor gewürfelt wird.

**Comment by Plushtoast** [comment]
Ich seh da nicht so den Mehrwert so Kleinigkeiten hinundherzuswitchen.
