### ISSUE TITLE
Herkunft der Errata zu "Zu Fall bringen" verwirrend

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1672]
**Is your feature request related to a problem? Please describe.**
Zu der SF "Zu Fall bringen" gab es offenbar ein Update mit Erörterungen. Jedenfalls wurde der Text deutlich verlängert und erwähnt z.B., dass gegen größere Gegner eine Erschwernis von -12 gilt. Das erscheint alles sehr sinnvoll, jedoch erschließt sich mir nicht woher dieser Text kommt. Im Grundregelwerk der 6. Auflage ist immer noch nur die alte, kurze Variante und auch auf der Regelwiki steht das so wie im Grundregelwerk. 
Die SF ist Teil des Core-Modules, also gehe ich davon aus, dass sie sich auf dieses Bezieht. 

**Describe the solution you'd like**
Ich würde super gerne irgendwie nachvollziehen können, worauf sich Änderungen beziehen, habe aber keine Pauschal Lösung.

**Comment by Plushtoast** [comment]
Wir sind auf den stand der herausgegebenen kodizes. Meist noch vor dem wiki. Alle Änderungen von dort kommen kostenlos in alle module

**Comment by Zonenpenner** [comment]
Also ist diese SF zusätzlich zum Grundregelwerk nochmal in den Kodex des Schwertes gewandert. Asoooooo....  Danke für die Antwort!
