### ISSUE TITLE
Boote & Schiffe dice roll broken

### ISSUE THREAD

**Issue by StudentESE** [Plushtoast/dsa5-foundryVTT#1674]
The **boote & Schiffe** dice roll has been broken since the last update.

**To Reproduce**
1. Go to 'Charakterbogen'
2. Click on 'three dices next to Boote & Schiffe'
3. after rolling dices there comes up the Warning 'cannot read properties of undefined (reading '0)'
4. See error also in the chat log: No diceroll is shown

**Expected behavior**
The result of diceroll should be shown in the chat

**Versions:**
- Foundry Version 11 Build 313 & 315
- DSA/TDE version 534 & 536

**Comment by Plushtoast** [comment]
Cant reproduce, also no changes there in the last patch

Is it happening in a new world?
Is it happening without modules enabled?
Is it happening on new actors?

Die you read this?
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/418a3193-c64c-4842-b42f-4b677c9867a1)

**Comment by StudentESE** [comment]
I have created a new World without active modules and only add one playercharacter which results in same behavior
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18450825/44b1c9de-3bd4-451d-8239-82e1487046cf)
Here you can see the console loggings:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18450825/a7f3fd1f-d967-4d7e-9af8-6966cf93dd60)
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18450825/28be088e-03dc-4af5-9d41-77d3f0b359f8)
after installing Foundry 11 new the problem is fixed:
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/18450825/ad3d687f-03c8-41d1-9ef1-3d0ffd6ebafb)
