### ISSUE TITLE
Regeneration - Die Regeneration wird nicht angewendet

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#168]
Die neue Funktion "Regeneration" wird anscheinend nicht auf den Charakter der sie gewürfelt hat angewendet. Selbst wenn ich den Charaktertoken als Ziel markieren nicht.

**Comment by Plushtoast** [comment]
Bitte das File in modules/hooks/chat_context.js mit dem file aus dem repository ersetzen oder auf den nächsten Patch warten (mindestens 2 Wochen)

**Comment by Gunthgard** [comment]
AsP sind ebenso betroffen.
