### ISSUE TITLE
Verhandlungst und Friedensschwur

### ISSUE THREAD

**Issue by Ginkgo85** [Plushtoast/dsa5-foundryVTT#1681]
**Describe the bug**
in der Weidergab kommt beim "Der Hai" kein Sound. Es wird nichts abgespielt.

**Screenshots**

![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/159688644/54933a8f-355c-4e72-8cd8-3a09ac1be101)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.3.6

**Comment by Plushtoast** [comment]
Um es kurzfristig selbst zu fixen kannst du folgendes tun:

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/77460fb4-367e-42c7-81bc-4ccc5824aa14)

Hier die Endung von mp3 zu ogg ändern
