### ISSUE TITLE
Statuseffekte --> Effekt Multiplizieren ohne Funktion

### ISSUE THREAD

**Issue by ToratosTarantula** [Plushtoast/dsa5-foundryVTT#1683]
**Describe the bug**

Wenn ich auf Leichte Plattenrüstung/ Statuseffekte klicke dann Effekt hinzufügen klicke und dann z.B. den Schlüssel Tragkraft eingebe und dann Addieren als Änderungsart nehme Funktioniert das nicht. Multiplizieren allerdings schon.

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/165499135/832c7b28-c726-4dbb-b48a-698654d585cd)

**Versions:**
- Foundry Version 11
- DSA/TDE version 1.0.6
- Related modules version

**Comment by Plushtoast** [comment]
Kann das so nicht nachvollziehen. Funktioniert einwandfrei mit addieren.
Hast du im Feld Wert auch etwas eingetragen und auf Änderungen übernehmen geclickt?

**Comment by ToratosTarantula** [comment]
Hey danke erstmal für deine Antwort :).

Ja addieren und subtrahieren Funktioniert einwandfrei . Wenn ich den Reiter allerdings umstelle auf Multiplizieren Funktioniert multiplizieren und dividieren.  Egal ob ich kein Zeichen rein mache ( so Funktioniert es ja auch beim Addieren ) oder ob  * oder / verwende nicht.

LG

**Comment by Plushtoast** [comment]
Die Werte sind meist Teil einer Formel und damit nur funktional mit dem voreignestellten Modus (hier addieren).

in diesem Fall ist das zb.

Tragkraft = Stärke * 2 + system.carrymodifer

Stellst du den Modus auf Multiplizieren multiplizierst du nur irgendwas mit system.carrymodifier

Das was du vorhast ist nicht vorgesehen

**Comment by ToratosTarantula** [comment]
> Stellst du den Modus auf Multiplizieren multiplizierst du nur irgendwas mit system.carrymodifier

Das ist ja rein theoretisch das was ich gerade will. Ob es nun Sinn macht oder nicht sei mal dahin gestellt.

Angenommen er hat eine Tragkraft von 32 und ich will diesen wert Multiplizieren x2  müsste es ja so sein wie du sagst. Sprich er multipliziert den Wert sytem.carrymodifier x2 welches dann ja eine Tragkraft von 64 ergeben sollte.

Vor allem verwundert es mich da es ja beim Addieren Funktioniert wenn ich dort den wert +2 eingebe nimmt er den wert system.carrymodifier und rechnet 2 dazu sprich es wird eine Tragkraft von 34 oder wenn ich es Subtrahiere  eine Tragkraft von 30. Das Klappt.

Sorry ich verstehe halt nicht ganz genau warum dieses mit Addieren und Subtrahieren geht aber nicht mit Multiplizieren und Dividieren geht. 

Was mich auch interessieren würde ob es irgendwo eine Kürzel liste gibt wie zum Beispiel das Kürzel MU für Mut steht. Gibt es diese Abkürzungen auch für die Talente ? 

LG

**Comment by Plushtoast** [comment]
Die Formel zur Berechnung der Tragkraft sieht mit multiplizieren so aus:

Tragkraft = Stärke * 2 + ( system.carrymodifier * 2)

und system.carrymodifier is per default 0

also kommt raus

Tragkraft = Stärke * 2 + (0 * 2)

Multiplizieren geht nicht, du kannst bei berechneten werten fast immer nur einfluss auf ein element der formel nehmen nicht auf die gesamte formel

ansonsten gibts nur die info im wiki:
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/de-Home

**Comment by ToratosTarantula** [comment]
Ahhh alles klar jetzt geht es auch in meine Birne rein . Vielen Dank :)
