### ISSUE TITLE
Steigern von Vertrauten und Begleitern falsche Steigerungskategorie

### ISSUE THREAD

**Issue by TarionT** [Plushtoast/dsa5-foundryVTT#1702]
Nach dem Regelwerk gilt folgendes:

"Tierische Begleiter bekommen eigene Abenteuerpunkte (ein Zehntel der Menge, die der Held nach der Heldenerschaffung bei Abenteuern etc. bekommt – diese Menge wird aber nicht von der Menge des Helden abgezogen).

Damit können sie ihre Eigenschaften und Talente, aber auch LE, AT und VW nach den gleichen Regeln wie Helden steigern (**jeweils Kategorie C**). Theoretisch können sie sogar Kampfsonderfertigkeiten erlernen. Das letzte Wort hierbei hat der Meister."

Für Vertraute gilt das selbe siehe GRW Seite 278

Im Foundry werden aber für Talente und Eigenschaften die Steigerungskatergorien für Helden herangezogen und nicht die Kategorie C wie oben im Regelwerk beschrieben.

Eventuell könnte das mal in einer späteren Version eingebaut werden, ebenso das die Begleiter und Vertrauten die korrekten Abenteuerpunkte automatisch erhalten wie im Regelwerk vorgesehen, also 1/10 bei Begleitern und 1/4 bei Vertrauten.

Danke für Eure super Arbeit weiter so.

**Comment by Plushtoast** [comment]
25% erhalten die Vertrauten bereits über die XP Funktion des Meistermenüs.

**Comment by TarionT** [comment]
Ahh das wusste ich nicht. TOP
