### ISSUE TITLE
system.rangeStats.damage rechnet falsch

### ISSUE THREAD

**Issue by mhs2508** [Plushtoast/dsa5-foundryVTT#1705]
**Describe the bug**
Ich spiele mit meiner Gruppe die Sternenträger Kampagne und habe die SF [Traumzauberei](https://dsa.ulisses-regelwiki.de/allgemeine_magische_sonderfertigkeit.html?sonderfertigkeit=Traumzauberei+I-III) selbst angelegt. Damit werden pro Stufe alle Eigenschaften sowie TP und RS um 1 erhöht. Um das abzubilden habe ich einen Effektcontainer Traumzauberei angelegt, der genau das abbildet (siehe Traumzauberei_Full_Buff.png).

Während **system.meleeStats.damage** +1 korrekt den Schaden einer Nahkampfwaffe um 1 erhöht, erhöht sich bei **system.rangeStats.damage** +1 der Fernkampf-Schaden um 11, anstatt auch um 1.

**To Reproduce**
1. Erstelle einen Effektcontainer mit aktivem Effekt system.rangeStats.damage +1
2. Würfele für eine Fernkampf-Waffe den Schaden aus und prüfe.
3. Erstelle zum Vergleich einen Effektcontainer mit aktivem Effekt system.meleeStats.damage +1
4. Würfele für eine Nahkampfwaffe den Schaden aus und prüfe

**Expected behavior**
FK-Schaden erhöht sich um 1 und nicht um 11.

**Screenshots**
"Traumzauberei_Full_Buff.png" zeigt den vollen Effektcontainer. Um das Problem isoliert darzustellen habe ich zwei Effektcontainer verwendet, die wahlweise **system.meleeStats.damage** +1  bzw **system.rangeStats.damage** +1 bewirken.

"Screen1.png" und "Screen2.png" zeigen den Fehler bei **system.rangeStats.damage** +1
"Screen3.png" und "Screen4.png" zeigen als Vergleich die korrekte Berechnung bei **system.meleeStats.damage** +1

<img width="1084" alt="Screen1" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/5d67cc7a-55f3-4279-bda0-04e2a59535f5">
<img width="1084" alt="Screen2" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/89e36a26-35fe-4e79-99d6-6498d39a7919">
<img width="1084" alt="Screen3" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/31bbaffe-b494-41a8-84c5-6cb124d5f4ad">
<img width="1084" alt="Screen4" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/7c05faf4-5ff3-43f2-b196-18b56d8119f2">
<img width="1027" alt="Traumzauberei_Full_Buff" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/60d58c16-b2d0-4b39-b33c-16a7428999ce">

**Versions:**
- Foundry Version: V11 stable build 315
- DSA/TDE version: 5.4.3
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Das Funktioniert wie beabsichtigt, bedarf aber eines kleinen Unterschieds. In diesem Feld ist es wichtig das Vorzeichen mit anzugeben, da das Feld auch Text erlaubt wie z.B. +1W6 extra Schaden.

Gibts du es ohne Vorzeichen an passiert folgendes, (Waffe hat z.B. 1d6+5 TP):

Neuer Schaden bei Bonus von 1

1d6+51 (Text wird einfach angehängt)

Neuer Schaden bei Bonus von +1

1d6+5+1 

Ich ändere den Platzhalter btw das Beispiel entsprechend ab. Die Funktion ist aber wie beabsichtigt.

**Comment by mhs2508** [comment]
Aber das wird ja ganz offensichtlich unterschiedlich bei den beiden Felden gehandhabt. Warum der unterschied bei Fernkampf und Nahkampf?

**Comment by mhs2508** [comment]
Und sorry, aber ich versuche das gerade mit deinem Tipp, den Bonus explizit mit Vorzeichen einzugeben, aber das funktioniert trotzdem nicht. Das System rechnet nach wie vor +11 Schaden. Entweder ich mache was falsch oder das ist ein Bug. Siehe Screen5.png
<img width="1084" alt="Screen5" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/2434ac93-0b94-43bb-bfbf-fb3e0b86587e">

**Comment by mhs2508** [comment]
So, mit diesem Workaround funktioniert es. Ist halt aus meiner Sicht fragwürdig, die unterschiedliche Behandlung. Aber immerhin, ich hab nen Workaround. Wäre interessant zu wissen, ob sich an der Funktion noch was ändert. :-)
<img width="577" alt="Screen6" src="https://github.com/Plushtoast/dsa5-foundryVTT/assets/84041748/24db23c5-e08c-484c-a775-a4104eb70903">
