### ISSUE TITLE
Foundry VTT V12 Support

### ISSUE THREAD

**Issue by a-nickol** [Plushtoast/dsa5-foundryVTT#1718]
Foundary VTT hat eine neue Version V12 veröffentlicht, gibt es Pläne und einen Zeitplan, die aktuelle Foundary VTT Version zu unterstützen?

**Comment by mckee14** [comment]
Ja, die DSA module werden auf v12 aktualisiert. Das dauert immer einen Moment. Und weil viele andere Module ebenfalls noch aktualisiert werden müssen, ist die allgemeine empfehlung immer erst ein paar wochen zu warten bevor man auf die neuste version migriert.Gesendet von unterwegsAm 24.05.2024 um 08:49 schrieb Alexander Nickol ***@***.***>:﻿
Am 22.05 wurde Foundary VTT V12 veröffentlicht, gibt es Pläne und einen Zeitplan, die aktuelle Foundary VTT Version zu unterstützen?

**Comment by Plushtoast** [comment]
wir warten mit dem update noch bis wir die änderungen aus dem kodex des götterwirkens in alle module eingebaut haben.
außerdem hat foundry direkt nach dem release meist noch einige probleme, weswegen wir auch warten wollen

theoretisch ist dsa für v12 aber schon vorbereitet

**Comment by tslays** [comment]
Für die User welche schon unter V12 testen möchten, könnte man hier ein Beta Release (manueller Install über JSON File) veröffentlichen?

**Comment by Plushtoast** [comment]
Das wär möglich, für die premium content module allerdings nicht

**Comment by tslays** [comment]
Ich nehme was ich kriegen kann aktuell. Ich habe sowieso nur Grundregelwerk und Drachenritter Einsteigermodul.

**Comment by Plushtoast** [comment]
Es ist nun eine Beta verfügbar:

https://github.com/Plushtoast/dsa5-foundryVTT/tree/foundry12

Auf eigenes Risiko, kein Support.

Die v11 Module werden von Haus aus nicht funktionieren, um sie angezeigt zu bekommen, muss im module.json des jeweiligen moduls diese Anpassung vorgenommen werden:

alt:
```json
"compatibility": {
        "minimum": "11",
        "verified": "11",
        "maximum": "11"
    },
```
    
neu:
```json
"compatibility": {
        "minimum": "11",
        "verified": "11",
        "maximum": "12"
    },
```

Auf keine fall funktionieren wird:

* Werkstatt des Meisters


Meine Empfehlung ist allerdings zu warten, bis v12 sich gesetzt hat und offizieller v12 support von DSA da ist.

**Comment by tslays** [comment]
"Unable to load valid system manifest data"
Und ich habe folgendes eingefügt: https://github.com/Plushtoast/dsa5-foundryVTT/tree/foundry12

**Comment by mckee14** [comment]
Er schreibt doch, es gibt keinen support :)Um das system zu installieren, muss du als manifest url das hier eingeben:https://raw.githubusercontent.com/Plushtoast/dsa5-foundryVTT/foundry12/system.jsonSteht direkt als erstes wenn du die github seite der beta durchliest.Gesendet von unterwegsAm 03.06.2024 um 14:24 schrieb tslays ***@***.***>:﻿
"Unable to load valid system manifest data"
Und ich habe folgendes eingefügt: https://github.com/Plushtoast/dsa5-foundryVTT/tree/foundry12

**Comment by tslays** [comment]
> Er schreibt doch, es gibt keinen support :)Um das system zu installieren, muss du als manifest url das hier eingeben:https://raw.githubusercontent.com/Plushtoast/dsa5-foundryVTT/foundry12/system.jsonSteht direkt als erstes wenn du die github seite der beta durchliest.Gesendet von unterwegsAm 03.06.2024 um 14:24 schrieb tslays ***@***.***>:﻿ "Unable to load valid system manifest data" Und ich habe folgendes eingefügt: https://github.com/Plushtoast/dsa5-foundryVTT/tree/foundry12 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Hatte den Kommentar schon wieder gelöscht und habe es zum Laufen gebracht. Alles gut also. Aber danke für die Nachricht.

**Comment by tslays** [comment]
> Es ist nun eine Beta verfügbar:
> 
> https://github.com/Plushtoast/dsa5-foundryVTT/tree/foundry12
> 
> Auf eigenes Risiko, kein Support.
> 
> Die v11 Module werden von Haus aus nicht funktionieren, um sie angezeigt zu bekommen, muss im module.json des jeweiligen moduls diese Anpassung vorgenommen werden:
> 
> alt:
> 
> ```json
> "compatibility": {
>         "minimum": "11",
>         "verified": "11",
>         "maximum": "11"
>     },
> ```
> 
> neu:
> 
> ```json
> "compatibility": {
>         "minimum": "11",
>         "verified": "11",
>         "maximum": "12"
>     },
> ```
> 
> Auf keine fall funktionieren wird:
> 
> * Werkstatt des Meisters
> 
> Meine Empfehlung ist allerdings zu warten, bis v12 sich gesetzt hat und offizieller v12 support von DSA da ist.

Reicht es wirklich maximum einfach auf 12 zu setzen?
Ich bekomme dann in V12 eine rote Fehlermeldung und das Modul erscheint gar nicht erst als installiert. ("Invalid module detected")

**Comment by Plushtoast** [comment]
Musst du foundry neustarten sonst erkennt es vlt die Änderung nicht
