### ISSUE TITLE
Token Image could not be saved

### ISSUE THREAD

**Issue by DSAKalle** [Plushtoast/dsa5-foundryVTT#172]
Token Image could not be saved 
yesterday fine
today not working anymore

**Comment by Plushtoast** [comment]
Das ist etwas ungenau formuliert und klingt eher nach einem Addon Problem.
Kannst du genauer beschreiben, wann und wie das passiert ist?

Falls du den Tokenizer verwendest schau mal in den Optionen, ob die Einstellungen korrekt sind.

Ggf. hat auch jemand oder etwas auf dem Server den Ordner, in dem die Token hochgeladen werden, gelöscht.
