### ISSUE TITLE
Verdeckte Proben anfordern

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1727]
Es ist sehr umständlich von den Spielern verdeckte Proben einzufordern. Daher wäre es schön wenn man Proben direkt verdeckt im Chat anfordern könnte, die unabhängig von den Einstellungen des jeweiligen Spielers immer verdeckt geworfen werden.

**Comment by Plushtoast** [comment]
im GM menu kannst du zumindest jetzt schon komplett verdeckte ausführen:

![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/7598c3f9-b402-4f5d-9d3e-7de93fafbdd0)

**Comment by Ogrimgro** [comment]
Ja, das stimmt. Aber es hat trotzdem nochmal einen anderen Effekt wenn die Spieler es selbst würfeln können, selbst wenn es nur ein Klick ist hat es trotzdem eine andere Wirkung als wenn man es verdeckt als SL würfelt.
