### ISSUE TITLE
Token Image

### ISSUE THREAD

**Issue by DSAKalle** [Plushtoast/dsa5-foundryVTT#173]
Ich erstelle einen Spielechar oder NPC
und lade ein eigenes erstelltes Image für den Token und es lädt in den Token.
Sobald ich den Token des Chars vom "Spielfeld" also Hintergrund nehme und in ein anders
Spielfeld setzte ist das Token image wieder auf default schwazweiß image gesetzt.
Das gleiche gilt auch für Namen. Ich ändere den Token-Namen. Alles gut solange der Token auf dem Spielfeld ist.
Sobald ich ihn vom Spielfeld entferne und neu draufziehe ist der Name wieder zurückgesetzt.
Dieser Fehler tritt erst seit dem heutigen update auf.

Lieben Gruß

Kalle

**Comment by Plushtoast** [comment]
Das ist das Standardverhalten von Foundry.

Stell sicher, dass du den Charakterbogen über das Actor Menü öffnest und dann den Token über das Menü oben rechts neben dem schließen Button anpasst und auch auf update Token klickst.

Wenn du den Bogen über das Spielfeld öffnest oder den Token über das Spielfeld änderst gilt das nur für die aktuelle Szene.
Generell sind Charbögen von NPCs und Kreaturen auf der Map immer nur Kopien.

Am besten schaust du ein paar youtube foundry videos an.

**Comment by DSAKalle** [comment]
@Plushtoast 
uff, das war´s vielen Dank!
