### ISSUE TITLE
Combat Effects in Combattracker

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1730]
**Is your feature request related to a problem? Please describe.**
Da euer Combattracker mittlerweile total super ist, nutze ich fast nur noch diesen anstatt des nativen.
Das einzige Feature, das ich gegenüber dem normalen Combattracker vermisse, ist dass dieser Statuseffekte anzeigt, was für mich wirklich hilfreich ist.
Ich weiß, dass des DSA-Combattracker nicht überladen werden sollte, aber die Möglichkeit Statuseffekte in diesem zu sehen wäre toll. 
Ganz megagroßartig wären Effekte mit Tooltip, ist aber nicht mein Hauptanliegen.

**Comment by Plushtoast** [comment]
Hm hab die damals absichtlich weggelassen. Weil auf den token icons auch schon on hover sachen sind.
Das geht nur mit einer kreativen Lösung sonst passt es wirklich nicht hin

**Comment by Zonenpenner** [comment]
Das ist natürlich ein starkes Argument. 

Was ist denn mit dem Raum zwischen den Zug-Buttons und der Initiative? Den könnte man doch für kleine Effektsymbole öffnen:
 
![Vorschlag Platz für Effekte](https://github.com/Plushtoast/dsa5-foundryVTT/assets/88042114/79dbede2-b5c1-44e3-ab06-432bae840ce5)

**Comment by Plushtoast** [comment]
Wär ok sieht man dann aber nur bei hover auf dem tracker

**Comment by Zonenpenner** [comment]
Stimmt, wäre aber vollkommen ausreichend, denke ich.

Könnte aber auch eine Option sein, sich INI und Effekte dauerhaft anzuzeigen zu lassen, wenn man meint einen ausreichend großen Bildschirm zu haben.
