### ISSUE TITLE
Zustand "Schmerz" bei LeP Verlust wird doppelt gesetzt

### ISSUE THREAD

**Issue by m1lklinG** [Plushtoast/dsa5-foundryVTT#1731]
Der Zustand "Schmerz" wird bei LeP Verlust (in den Stufen 3/4, 1/2, 1/4 max. LeP) statt 1 mal inzwischen 2 mal gesetzt. Das führt dazu, dass der betroffene Charakter schon bei Unterschreitung der 1/2 max. LeP Schwelle handlungsunfähig wird.

Installiert ist Foundry v12 sowie ausschließlich offizielle DSA Module.

**Comment by Plushtoast** [comment]
Kann ich nicht reproduzieren. Kannst du den entsprechenden char als json exportieren und hier hochladen?

**Comment by TarionT** [comment]
Hatten wir am vergangen Wochenende auch, muss es aber noch ohne Module nachstellen.

**Comment by m1lklinG** [comment]
Ich bekomme es aktuell nicht nachgestellt.
Gesehen habe ich es gestern bei diesen beiden SCs (seitdem ist ein Foundry Update gelaufen; weiss nicht, ob das was damit zu tun hat). 

[fvtt-Actor-talfan-vascagni-EKTWj2lApaqnG6ym.json](https://github.com/user-attachments/files/16033065/fvtt-Actor-talfan-vascagni-EKTWj2lApaqnG6ym.json)
[fvtt-Actor-ogrim-firnganger-ll1FGVKGH95vYhbP.json](https://github.com/user-attachments/files/16033068/fvtt-Actor-ogrim-firnganger-ll1FGVKGH95vYhbP.json)

Nachdem ich händisch die Zustände "Schmerz" einige Male gelöscht und auch den Spieltisch aktualisiert hatte, hat er es auch nicht mehr doppelt gesetzt.

Du brauchst für die Fehlersuche vermutlich einen IST-Zustand, wo noch beide Effekte drauf sind (also inkl. dem Unnötigen)? Das hab ich zZ leider nicht.

**Comment by TarionT** [comment]
Ich bekomme es leider auch nicht mehr nachgestellt.

**Comment by gwenethen** [comment]
Konnte den Fehler nachstellen, passiert mit allen Effekten wenn ein Besitzer außer der GM eingestellt wird und der besitzende Spieler online ist.
 
 Habe dazu mal direkt einen Issue aufgemacht, denke aber es wird auf das selbe Problem hinauslaufen.

#1733

**Comment by Maxwellus** [comment]
Nicht nur das es teilweise doppelt Schmerz gezählt hatte, sondern bei NPC oder Gegner werden die Schmerzstufen nicht angepasst, sobald diese den Wert unterschreiten, außer man fügt z.B. dann einen Status wie Fixiert dazu, dann werden auch die Schmerzstufen addiert.
