### ISSUE TITLE
Klingensturm AP stimmen nicht mit Regelwiki überein

### ISSUE THREAD

**Issue by AdeptusAngbar** [Plushtoast/dsa5-foundryVTT#1734]
**Describe the bug**
Die Sonderfertigkeit "Klingensturm" ist mit 30 AP im Modul "DSA5-armory" und "DSA5-compendium" hinterlegt. Laut Regelwiki sowie den Printquellen sollten es 25 AP sein.

**Versions:**
- V12.327
- DSA/TDE 6.0.3
- Related modules version 6.0

**Comment by Plushtoast** [comment]
Laut meiner Printquelle (Kodex des Schwertes) stimmt das so:
![grafik](https://github.com/Plushtoast/dsa5-foundryVTT/assets/44941845/c4970d1d-5767-4e2b-a34e-5c206669607a)

**Comment by AdeptusAngbar** [comment]
Interessant, dann wurde es wohl für die Kodexbände verändert. Wie gesagt Regelwiki, Rüstkammer des Dornenreiches und Kompendium I als Print sagen anderes. Ich melde es dann vielleicht mal an "Feedback" um die Regelwiki anpassen zu lassen. Vielen Dank für die prompte Antwort!

**Comment by Plushtoast** [comment]
Soweit ich weiß wurde klingensturm und noch ein paar andere mehrfachangriffe mit dem Kodex überarbeitet
