### ISSUE TITLE
Paradewurf Vorschau falsch bei "Hohe Klinge"

### ISSUE THREAD

**Issue by Rapunzel77** [Plushtoast/dsa5-foundryVTT#1737]
**Describe the bug**
Der Vorschauwürfel wird nicht durch "Hohe Klinge" beeinflusst, der Wurf danach allerdings schon.

**To Reproduce**
1. Bei der Parade Hohe Klinge auswählen
2. ---> keinen Effekt im Vorschauwürfel wahrnehmen

**Expected behavior**
Vorschauwürfel sollte den Effekt anzeigen

**Screenshots**
![image](https://github.com/Plushtoast/dsa5-foundryVTT/assets/9886526/6a250ef5-59be-4a6e-8243-e5544e8ccd3e)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.4.5

**Comment by RandomHero13** [comment]
der Hohe klinge malus bei der parade is nur bei der parade mit der waffe auswählbar nicht aber bei parade mit dem schild. kann natürlich sein dass nur die waffenparade gesenkt wird, aber ich/wir interpretieren das als "alle paraden"
