### ISSUE TITLE
Diverses

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#174]
Hallo,

die folgenden Dinge sind mir in den letzten Tagen aufgefallen:

- Der Status “Blutrausch” rechnet jetzt automatisch die +1 auf Nahkampf-AT mit ein (cool!), jedoch nicht die +2 TP (soweit ich sehen kann jedenfalls). Schmerz muss man auch noch manuell abwählen, wobei der Held alle Abzüge durch Schmerz ignoriert, wenn er erstmal im Blutrausch ist.

- Kann man den Zustand “Schmerz” irgendwie manuell ausschalten? Bisher entsteht der ja automatisch basierend auf verbleibenden Lebenspunkten, aber a) manche Kreaturen (wie Dämonen oder Riesenamöben) kennen buchstäblich keinen Schmerz (bekommen ihn aber derzeit automatisch zugewiesen, wenn die LeP sinken), und b) die Sonderfertigkeit “Schmerzen unterdrücken” erlaubt ja manchen Charakteren, die Auswirkungen von Schmerzen zeitweilig zu unterdrücken. Alternativ vielleicht für Monster eine Art “Immun gegen Schmerz”-Item, was, wenn equipped, Schmerz ausschaltet?

-  Beim Nachteil “Unfähig” würfelt Foundry automatisch den besten Würfel neu und berechnet das endgültige Ergebnis, was sehr cool ist. Beim Vorteil “Begabung” funktioniert das umgekehrt nicht und man muss manuell den schlechtesten Würfel neu würfeln. Ginge das ebenfalls automatisch?

- Bei Zaubern wird Belastung automatisch mit eingerechnet und muss zunächst manuell abgewählt werden. Meines Wissens/Regelverständnisses nach sind Zauber in erster Linie geistige Proben, auf die sich eine Belastung nicht automatisch auswirkt wie bei körperlichen Proben. Könnte hier die Voreinstellung so sein, dass Belastung nicht vorausgewählt ist?

- Tierische Sonderfertigkeiten scheinen nicht alle zu funktionieren. Zum Beispiel ist der “Schwanz- und Tentakelschwung” beim Karakil als tierische SF ausgerüstet, lässt sich aber, wenn man einen Angriff mit dem Schwanz machen möchte, nicht als SF auswählen. Dort kann man dann nur einen Flugangriff auswählen. Ähnliches scheint auf weitere Kreaturen und deren SFs im Kampf zuzutreffen.

- Kann es sein, dass das Token zwar eine Änderung der Größe/Anzeigenamen usw. speichert, jedoch keine Sicht? Diese scheine ich, auch wenn Token und Charakter (SC, kein NSC/Monster) fest miteinander verknüpft sind, auf jeder Karte neu anpassen zu müssen? 

Vielen Dank.

**Comment by Plushtoast** [comment]
zu
1. Ja im nächsten Update wirds mehr modifikatoren für zauber und nahkampfangriffe geben, dann geht das auch
2. Ja, wir wollen auch Fähigkeiten abhängig von der Kategorie irgendwann implementerien (also Dämonen, Feen etc). Aber das dauert noch
3. Nein. Nimm folgendes Beispiel an. Du hast die Attributeswert 14/16/10 und würfelst 10, 16 und 11? Vermutlich nicht 11 weil die Wahrscheinlichkeit mit der 16 zusätzliche FP zu erzielen viel höher ist und mit der 10 versaut man es nur ein weiteres mal. Außerdem hat der Spieler vlt ein Lieblingsglücksattribut und es gibt noch mehr Beispiele. Das würde eine komplizierte Formel benötigen. Darf jeder getrost selbst berechnen, was das beste ist.
4. Weiß ich nicht, aber wär machbar.
5. Es werden niemals alle fähigkeiten funktionieren. Der Tentakelschwung hat sehr spezielle Auswirkungen und wird derzeit und in naher Zukunft nicht unterstützt
6. siehe: https://github.com/Plushtoast/dsa5-foundryVTT/issues/173

**Comment by Plushtoast** [comment]
Bitte unterschiedliche Themen in unterschiedliche Issues packen, sonst muss ich jedesmal alles nochmal lesen und kann nichts abhaken, was wiederum dazu führt, dass a) entweder etwas übersehen wird oder b) diese Art der Issues ignoriert werden.

**Comment by Plushtoast** [comment]
Ich hab diesen Issue jetzt aufgedoppelt.
Wie erwartet, musste ich ihn mehrfach lesen, um zu wissen worum es geht.
Verschiedene Themen bitte in Zukunft in verschiedene Tickets mit einigermaßen aussagekräftigen Ticket.
Diese Art der Tickets werde ich ignorieren.
