### ISSUE TITLE
Dschinnenblut (Erzdschinn) macht Char unbrauchbar

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1745]
**Describe the bug**
Das Hinzufügen des Vorteils Dschinnenblut (Erzdschinn) führt dazu, dass der Charakter danach nicht mehr geöffnet werden kann.

**To Reproduce**
1. Neuer Aktor
2. Helden erstellen
3. Vorteil Dschinnenblut (Erzdschinn) hinzufügen

**Expected behavior**
Hinzufügen des Vorteils Dschinnenblut (Erzdschinn) ohne PRobleme

**Screenshots**

**Versions:**
- Foundry Version 328
- DSA/TDE version 6.0.7
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
hm vor dem hinzufügen den effekt editieren und "data.totalArmor" mit "system.totalArmor" ersetzen

bei bereits kaputten akteuren in der konsole eingeben (F12)

```js
actor = game.actors.find(x => x.name == "Thallian (Copy)");actor.deleteEmbeddedDocuments("Item", [actor.items.find(y => y.name =="Dschinnenblut (Erzdschinn)" && y.type=="advantage").id]) 
```

**Comment by Plushtoast** [comment]
oder 6.0.8 installieren
