### ISSUE TITLE
Reittier wird fehlerhaft hinzugefügt

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1749]
**Describe the bug**
Beim Hinzufügen eines Reittiers wird ein "unbekanntes" Reittier beim Helden hinzugefügt

**To Reproduce**
1. Beim Helen den Reiter "Kampf" öffnen
2. Ein Reittier aus der Bibliothek auf einen Helden ziehen
3. Unter Reittier wird nur ein "unbekannter" Eintrag erstellt

**Expected behavior**
Korrektes Einfügen des Reittiers

**Screenshots**

**Versions:**
- Foundry Version 328
- DSA/TDE version 6.0.8
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Das Reittier muss bereits importiert sein.
