### ISSUE TITLE
Präziser Schuss beim Elfenbogen

### ISSUE THREAD

**Issue by Ginkgo85** [Plushtoast/dsa5-foundryVTT#1751]
**Describe the bug**
Beim Prezisen Schuss elfenbogen wird immer -2 abgezogen obwohl ja bei Stufe 1 nur -1 sein sollte

**Versions:**
- Foundry Version 12.330
- DSA/TDE version 6.0.8
- Related modules version 6.0.0

**Comment by Plushtoast** [comment]
Waffen vor und Nachteile sind eine optionale regel die es derzeit in foundry nicht gibt
