### ISSUE TITLE
Editieren von neuen Nahkampfwaffeneinträgen nicht möglich

### ISSUE THREAD

**Issue by Elderneyms** [Plushtoast/dsa5-foundryVTT#176]
**Describe the bug**
Wenn eine neue Nahkampfwaffe mit über "+" hinzugefügt wird, kann diese nicht editiert oder angelegt werden.

**To Reproduce**
1. Nach dem eine Nahkampfwaffe per Drag n' Drop hinzugefügt wurde erscheint der Eintrag Nahkampfwaffen
2. Wenn auf das + Symbol oben rechts geklickt wird entsteht ein neuer Eintrag "Nahkampfwaffe"
3. Dieser Eintrag kann nicht bearbeitet werden.

Schön wäre es, wenn dieser Eintrag auch bearbeitet werden könnte.

**Screenshots**
![Nahkampfwaffe](https://user-images.githubusercontent.com/64350656/110236711-a601d980-7f37-11eb-8ccc-b65d9fe56c44.png)

![Nahkampfwaffehinzu](https://user-images.githubusercontent.com/64350656/110236718-ae5a1480-7f37-11eb-8c0d-0450e362bea4.png)

- OS: [macOS 10.15.7]
- Foundry VTT Version [0.7.9]
- Das Schwarze Auge - Grundregelwerk  [1.0.2]
- Dice So Nice! [0.8.1]

**Comment by Plushtoast** [comment]
Ist das System auf version 1.2 aktualisiert?

**Comment by Elderneyms** [comment]
Ich hab das Grundregelwerk auf Version 1.0.2. Eine Version 1.2 konnte ich nicht finden.

**Comment by Plushtoast** [comment]
Du musst unterscheiden zwischen "Modulen" und dem "System". Module sind zb das Grundregelwerk oder Abenteuer und beinhalten Content. Das System beinhaltet den ganzen Code, dass das alles zusammenspielt und ist je nach Pen Paper Spiel eben unterschiedlich.

Du kannst es hier updaten:

![grafik](https://user-images.githubusercontent.com/44941845/110246515-2c361400-7f68-11eb-892c-9ad717adfb0f.png)

**Comment by Elderneyms** [comment]
Oh, sorry ich hab nur die Module aktualisiert, nicht aber das System. Ja, nach dem Update auf 1.2 funktioniert das Editieren. Vielen Dank für deine Antworten.
