### ISSUE TITLE
Einstellung "Geld hat Gewicht" ist wirkungslos

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#1760]
**Describe the bug**
Die Aktivierung der Einstellung "Geld hat Gewicht" ist ohne Effekt. Das aktuell getragenen Gewicht von SCs ändert sich dadurch nicht.

**Versions:**
- Foundry Version: 12.334
- DSA/TDE version: 6.0.9

**Comment by Plushtoast** [comment]
Hast geprüft ob das geld auf den chars unter Gewicht was eingetragen hat?

**Comment by sirgawain111** [comment]
Nein, hatte ich nicht. Danke für den Tipp.

Issue kann geschlossen werden.

**Comment by Plushtoast** [comment]
Alles geld war früher komplett ohne gewicht. Sas ist jetzt erst seit dem patch in den kompendien drin. Heisst nur neue chars bekommen das neue geld. Alle anderen müssen das händisch eintragen oder die Geld tauschen Funktion verwenden
