### ISSUE TITLE
Status "reitend" lässt sich nicht entfernen

### ISSUE THREAD

**Issue by Meckerdrache** [Plushtoast/dsa5-foundryVTT#1763]
Status reitend bleibt erhalten, obwohl im HUD auf Absteigen geklickt wird. Wird der Status anderweitig entfernt, verschwindet er im HUD dennoch nicht und auch die Statuseffekte (-1 Belastung, vorteilhafte Position) bleiben erhalten. 

**To Reproduce**
1. Wähle Charakter und Reittier aus.
2. Klicke im HUD des Charakters auf "aufsteigen".
3. Klicke im HUD des Charakters auf "absteigen".
4. Der Status "reitend" verschwindet nicht mehr.

**Expected behavior**
Der Status sollte entfernt werden, die Belastung sollte angepasst werden, die Statuseffekte sollten aufgehoben werden.

**Versions:**
- Foundry Version v12 Stable 7 (Build 330)
- DSA/TDE version 6.0.9

**Comment by Plushtoast** [comment]
Im zweifelsfall gehts auchimmer hier:
![grafik](https://github.com/user-attachments/assets/4a6f7168-bb94-46bd-ad52-51c857a0c01e)

auf dem kampftab die mülltonne
