### ISSUE TITLE
Automatisierungen (Verzauberung / Lichtverhältnisse) in V12 gehen nicht mehr #1757

### ISSUE THREAD

**Issue by Foseti** [Plushtoast/dsa5-foundryVTT#1765]
gerade Bugfix 6.0.10 getestet Problem scheint noch da zu sein.

_Originally posted by @Foseti in https://github.com/Plushtoast/dsa5-foundryVTT/issues/1757#issuecomment-2290754333_

**Comment by Plushtoast** [comment]
hast den haken gesetzt:

![grafik](https://github.com/user-attachments/assets/9e3bacd5-4c05-46e1-adeb-3ec45452e5d1)

**Comment by Foseti** [comment]
ja ist gesetzt, habe es auch einmal den haken entfernt und wieder gesetzt.

**Comment by Plushtoast** [comment]
fehler in der konsole (f12)?

**Comment by Foseti** [comment]
gerade nochmal geschaut hatte heute früh keinen Gegner im Target daher nicht die Sicht, geht also.

Aber irgendwie geht der eigene Statuseffekt nicht zb Nahkampf erhöhen auf einer Waffe 
<img width="420" alt="Screenshot 2024-08-15 120849" src="https://github.com/user-attachments/assets/6352fb3c-9534-4544-b2b7-50533b6e221b">

Beim Anlegen kommt auch schon ein Fehler in der Konsole:
<img width="400" alt="Screenshot 2024-08-15 120955" src="https://github.com/user-attachments/assets/4e13e207-c0ef-4f83-a0c4-b29563869c52">

**Comment by Plushtoast** [comment]
auch das geht bei mir. die änderungsart für den key ist "add" btw

ist unter erweitert effekt auf den träger übertragen? sonst wird der effekt auf das ziel des angriffs übertragen. ist die waffe angelegt?

die fehlermeldung die du da zeigst ist weiß der geier woher. auf jeden fall nicht von dsa

**Comment by Plushtoast** [comment]
wenn du über content_script hoverst kannst anhand des pfades evtl rückschlüsse machen woher der code kommt

**Comment by Foseti** [comment]
ja es lag am effekt auf den spieler übertragen, eindeutiges Layer 8 Problem.

vielen Dank
