### ISSUE TITLE
HELP WANTED: 3d animation of dice so nice might not be properly hidden

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#177]

**Comment by Plushtoast** [comment]
Please provide me with detailed description if you encounter this issue.
I was'nt able to find any problems.

**Comment by tomsaath** [comment]
Ich kann diesen Fehler vermutlich nachvollziehen:
Ich würfel als Spielleiter einen Privaten Wurf:
Spielleiter: Sieht die 3D Würfel und den Chat
Spieler: Sieht die 3D Würfel
Ein Spieler sollte einen privaten Wurf ja aber garnicht sehen oder? Also ist hier das Problem, dass die 3D Würfel für die Spieler sichtbar sind.

**Comment by Plushtoast** [comment]
Bei was für würfen?

**Comment by tomsaath** [comment]
Bei Privaten Würfen - private rolls

**Comment by Plushtoast** [comment]
Also ich kann kein Problem feststellen. Hat sich wohl aus Versehen mal nebenher gelöst oder war nie ein Problem.
