### ISSUE TITLE
Charkatererstellung

### ISSUE THREAD

**Issue by logrimoth** [Plushtoast/dsa5-foundryVTT#178]
Bei der Erstellung eines Elfens werden weder durch die Kultur noch durch den Vorteil Zauberer Astralpunkte eingeblendet erschwert das Generieren ungemein!
2tens nach dem viele Vorteile und Nachteile nicht eingepflegt sind wäre es super einen dummy einzustellen mit dem sich der user die Modifikatioren und Kosten selbst einstellen kann -  besten Dank im vorraus

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nyhles** [comment]
Füge bei deinem Charakter einen Zauber hinzu, dann wird der Magie Tab korrekt angezeigt.

**Comment by Plushtoast** [comment]
Außerdem kannst du im Item Directory selbst alles anlegen was du benötigst:

![grafik](https://user-images.githubusercontent.com/44941845/110254818-1b4dc880-7f91-11eb-9581-1c2703677121.png)

Als Spieler muss der GM dir evtl die passenden Rechte geben.

**Comment by Plushtoast** [comment]
Passt das soweit oder hast du noch Fragen?

**Comment by logrimoth** [comment]
Danke funktioniert gut besten dank

Plushtoast ***@***.***> schrieb am Do., 18. März 2021, 15:59:
