### ISSUE TITLE
Sprache "Garethi III" kann nicht bei Kultur "Zyklopeninseln" gewählt werden

### ISSUE THREAD

**Issue by Guido-1970** [Plushtoast/dsa5-foundryVTT#1784]
**Describe the bug**
When I would like to create a char from the Zyklopeninseln" with language "Garethi III" and try to approve my election, the error "Missiong Options detected" occurs and the char-creation can't be finished. If I deselect the option the code continues to "choose prefession"

**To Reproduce**
1. Go to 'choose culture Zyklopeninseln'
2. Click on 'Allgemein' an choose "Garethi III"

**Expected behavior**
Continuing to "Chose Profession"

**Screenshots**
![image](https://github.com/user-attachments/assets/f04cdd61-28bb-4601-99eb-4338af189534)

**Versions:**
- Foundry Version 11.315
- DSA/TDE version 5.4.4
- Related modules version: DSA/TDE Core-Rules 
[dok1.docx](https://github.com/user-attachments/files/17233130/dok1.docx)
5.4.4

**Additional context**

**Comment by Plushtoast** [comment]
Die version 11 von DSA auf Foundry bekommt keine Updates mehr.
Funktioniert in v12.

Sobald DSA für eine neue Foundry version erscheint is es vorbei mit updates und bugfixes für die Vorgängerversion.
