### ISSUE TITLE
Wiedergabelisten: Titel in der Anzeige beim Hover scollen

### ISSUE THREAD

**Issue by TarionT** [Plushtoast/dsa5-foundryVTT#1785]
Wie im Bild zu sehen sind viele meiner Titelnamen zu lang um Rückschlüsse ziehen zu können bei größeren Listen.
Wäre es möglich in das Playlistenhancment Modul das noch einzubauen, dass wenn man den Titel mit der Maus hovert, dass er Anfängt seitwärts zu srcollen?

![grafik](https://github.com/user-attachments/assets/a7ae8465-0d7e-4270-b5db-d3caaa51afb1)

**Comment by Plushtoast** [comment]
das ticket würde zumindest zum völlig von dsa unabhänigen modul playlistenchantment gehören

**Comment by TarionT** [comment]
Soll ich es dort nochmals einstellen?

**Comment by Plushtoast** [comment]
Ne, aber in Zukunft wärs gut. Das signalisiert allen besuchern und bots dass das ding nicht tot ist
