### ISSUE TITLE
Error "JeAelterDestoSchlimmer" - The Dark Eye 5th Ed. - Havena, Sunken Secrets

### ISSUE THREAD

**Issue by Cthustra** [Plushtoast/dsa5-foundryVTT#1786]
**Describe the bug**
Das Makro "JeAelterDestoSchlimmer" funktioniert mit der aktuellen Version nicht.

**To Reproduce**
1. Go to the macro "JeAelterDestoSchlimmer"
2. Click on Ausführen
3. See error

**Expected behavior**
Werteänderungen am ausgewählten Token/Charakter

**Screenshots**
![image](https://github.com/user-attachments/assets/37076bfa-8107-406a-928f-4a183268e899)

**Versions:**
- Foundry Version V12.331
- DSA/TDE version 6.0.12
- Related modules version 6.0.0

**Comment by Plushtoast** [comment]
wie führst du das makro aus, bei mir gehts.

es is teil des panzerkrebs:
![grafik](https://github.com/user-attachments/assets/2966bd87-0d50-4ee8-8201-5d5e85b9d0f9)


auszuführen über den würfelbutton

**Comment by Plushtoast** [comment]
geschlossen in ermangelung von details
