### ISSUE TITLE
Show weapons Advantages and Disadvantages

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#1791]
**Is your feature request related to a problem? Please describe.**
Hi, in dem Update 6.1 wurde ja der Beschreibungstext in den Waffenitems um die Vor- und Nachteile gekürzt. Ich nehme an, die sollten nun irgendwo anders stehen (Effektfeld?), jedoch ist dort nichts zu sehen. Das Checkfeld für Ausrüstungsvor- und nachteile ist an, die Spielwelt ist nochmal neu gestartet, die betrachteten Waffen kommen direkt aus gerade geupdateten Kompendien, wie Rüstkammer 1 und die Konsole ist unauffällig.

**Describe the solution you'd like**
Die Ausrüstungs Vor- und Nachteile in der Plattform nachlesen zu können.

**Describe alternatives you've considered**
Nachhören mittels eines Autovorlesers ist denkbar, aber unpraktisch.

**Additional context**
-

**Comment by Plushtoast** [comment]
Ist jetzt ein welt setting das per default deaktiviert ist

**Comment by Zonenpenner** [comment]
Ja, ich weiß. Wie geschrieben, ich habe den Haken in den Settings aktiviert und Foundry danach sicherheilts halber neu gestartet.
![Beispiel](https://github.com/user-attachments/assets/e30e80c3-795e-4f7c-b209-11418cee09a4)

Hier noch drei Waffen aus dem geupdateten dsa-armory. Da steht nirgendwo etwas bezüglich der Vor- und Nachteile.
![Beispiel 2](https://github.com/user-attachments/assets/43c276c2-ff06-4a95-8803-ffdd72c11c16)

**Comment by Plushtoast** [comment]
Module nochmals updaten
