### ISSUE TITLE
Rüstungsvorteile und - Nachteile werden nicht korrekt umgesetzt

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1795]
**Describe the bug**
Beispielhaft:
Die Rüstungsvorteile und - Nachteile des Kettenhemdes sollten bei einem Schwertangriff dafür sorgen, dass eine RS von 5 und nicht von 4 angewendet wird. Wird z.B. mit eienr Axt angegriffen wird auch kein Zufallswurf auf den D6 ausgeführt, um zu bestimmen, ob RS 4 oder RS 5 gilt.
Der Zwergenhelm sollte gegen einen großen Gegner die RS 7 aufweisen. Es kommt jedoch nur der Standardwert von RS 6 zum Tragen.

Darüber hinaus wird der Nachteil (auch bei anderen Items) doppelt bei Talent- oder Angriffswürfen aufgeführt.

**To Reproduce**
1. Angriff auf einen Charakter mit entsprechender Ausrüstung
2. See error

**Expected behavior**
Korrekte Anwendung der Rüstungsvorteile und - Nachteile.

**Screenshots**
<img width="231" alt="fehler" src="https://github.com/user-attachments/assets/54be625c-a375-4371-a3d2-43800f9c60ce">
<img width="535" alt="fehler2" src="https://github.com/user-attachments/assets/e83bd405-9c53-4506-a446-e6dd099c50a2">

**Versions:**
- Foundry Version V12 331
- DSA/TDE version 6.1.1
- Related modules version

**Additional context**
Einen großen Dank an die Entwickler für die schnelle bearbeitung der Bugs! Ich hoffe ich melde nicht zu viele davon.

**Comment by Plushtoast** [comment]
Du kannst hier nachlesen wo die Automatisierung schon funktionieren sollte. Eine vollständige Abdeckung ist nicht möglich.

https://github.com/Plushtoast/dsa5-extensiondb/blob/master/summary.md

Der zwergenhelm ist jedoch nicht soweit, auch wenn das tatsächlich technisch schon möglich wäre.

Zufallsrüstubg und Rüstung gegen dolche etc funktioniert bei mir jedoch schon

**Comment by Arolske** [comment]
Vielen Dank für den Link zu der Abdeckung der Umsetzung.

Ich habe es vorhin nochmal in zwei verschiedenen Welten mit dem Kettenhemd, dem langen Kettenhemd und der leichten Platte probiert. Bei allen Rüstungen wird bei mir die RS nicht modifiziert. Der jeweilige Status wird zwar am Helden angezeigt, aber nicht umgesetzt. Wenn ich im Chatfenster mit der Maus auf die RS-Zahl (in dem Fall "4") gehe, erscheint ein Tooltipp mit "undefined Modifikator*undefined Modifikator"
Könnte es etwas mit der Zonen-Regel zu tun haben?

Mir ist auch aufgefallen, dass die Syntax im Vorteil des langen Kettenhemdes ein "," statt ";" als Trennung verwendet.

**Comment by Plushtoast** [comment]
habs nur 1x drin:

![grafik](https://github.com/user-attachments/assets/f678268a-7547-42ef-8217-3b58dd5240e3)

sind bei dir mehrere vorteile im status tab?

**Comment by Arolske** [comment]
Bei mir sieht es so aus
<img width="1523" alt="helm" src="https://github.com/user-attachments/assets/41821ba2-b94f-41a8-9309-9cc58a7215d1">

**Comment by Plushtoast** [comment]
und hier?

![grafik](https://github.com/user-attachments/assets/de7531c1-a20b-45a0-b645-5da425ed1335)

mit compendium 1 update sollte es auch mit zonenregel gehen

**Comment by Arolske** [comment]
Es steht nur 1x in dem Zwergenhelm.

Ich muss dann doch mal eine Runde ohne Module, nur mit Rüstkammer und Kompendium probieren.

**Comment by Arolske** [comment]
Der Test hat ergeben, dass die Rüstungsvor- und -nachteile nach wie vor bei mir nicht gehen, auch wenn nur mit den Modulen Rüstkammer I+II und Kompendium I+II gestartet wird.

Der doppelte Eintrag scheint etwas mit den Modulen "Optolith to Foundry Importer", "Havena" und "Magie III" zu tun zu haben. Wenn mind. eines davon aktiv ist, tritt der Fehler auf.

**Comment by Plushtoast** [comment]
Das klingt unwahrscheinlich

**Comment by Arolske** [comment]
Bei mir ist es definitiv so. Hier am Beispiel von Magie III

<img width="1168" alt="Fehler 2" src="https://github.com/user-attachments/assets/74762ee6-3c65-42b0-8c03-1b410c19f779">
<img width="1143" alt="Fehler 1" src="https://github.com/user-attachments/assets/b74a5ec3-7747-4fb0-b5b7-3303719d0115">

**Comment by Plushtoast** [comment]
kann das leider nicht nachstellen
magie 3 hat damit auch nichts zu tun. der grund muss irgendwo anders liegen

**Comment by Plushtoast** [comment]
kannst du mal den charakter exportieren und mir geben

**Comment by Arolske** [comment]
Das mache ich gerne. Ich habe cen Char mal recht "nackig" gemacht. Der Fehler tritt nach wie vor so auf.

**Comment by Plushtoast** [comment]
geht leider auch bei mir

![grafik](https://github.com/user-attachments/assets/6fc7b064-63e3-446f-a72e-a0a7b94fed93)

**Comment by Arolske** [comment]
Spannend, also wird es vielleicht etwas in meinen Einstellungen sein...Bin gerade etwas ratlos.

Klappt auch die Verwendung des Kettenhemdes mit der erhöhten RS gegen Schwerter etc bei dir?

**Comment by Plushtoast** [comment]
Ja. Ich habe treffer und rüstungszonen an

**Comment by Arolske** [comment]
Hmm, seltsam alles. Ist es möglich, dass du mir mal deine Enstellungen exportierst?

**Comment by Arolske** [comment]
In meiner Testwelt passiert es jetzt sogar, dass der Nachteil "Eingeschränktes Hören" durch das Anlegen des Kettenhemdes noch zusätzlich 2x eingefügt wird. Es steht also 4x im Helden. Lege ich den Zwergenhelm ab, werden alle 4 Einträge entfernt, beim Ablegen nur des Kettenhemdes nur 2. Der Vorteil des Kettenhemdes wird hingehend nicht eingetragen. Gleiches passiert, wenn ich den Zwergenhelm durch einen Topfhelm ersetze.
In meiner Hauptwelt besteht das alte Problem, dass es nur 2x eingetragen wird und die Ausrüstungsvorteile nicht gehen.

Ich besitze noch eine zweite DSA Welt mit einer unabhängigen Installation. Dort habe ich die gleichen Probleme. Daher scheint es ein systematisches Problem bei mir zu sein. Ich bin leider nicht Informatiker genug, um nachvollziehen zu können, welche Funktionen/Quellen etc. dafür verantwortlich sein könnten. 

<img width="1494" alt="Fehler 2" src="https://github.com/user-attachments/assets/9b830dda-8fe3-414a-b86a-4e70d0bbe5b7">
<img width="1920" alt="Fehler 1" src="https://github.com/user-attachments/assets/7ca85f45-9c50-4021-ac81-577a62f4543c">

**Comment by Schorschus** [comment]
> Vielen Dank für den Link zu der Abdeckung der Umsetzung.
> 
> Ich habe es vorhin nochmal in zwei verschiedenen Welten mit dem Kettenhemd, dem langen Kettenhemd und der leichten Platte probiert. Bei allen Rüstungen wird bei mir die RS nicht modifiziert. Der jeweilige Status wird zwar am Helden angezeigt, aber nicht umgesetzt. Wenn ich im Chatfenster mit der Maus auf die RS-Zahl (in dem Fall "4") gehe, erscheint ein Tooltipp mit "undefined Modifikator*undefined Modifikator" Könnte es etwas mit der Zonen-Regel zu tun haben?
> 
> Mir ist auch aufgefallen, dass die Syntax im Vorteil des langen Kettenhemdes ein "," statt ";" als Trennung verwendet.


Moin zusammen, ich hoffe, es ist in Ordnung, wenn ich mich hier kurz melden. Bzgl. der Rüstungsmodifikation:
Bei mir treten die gleichen Fehler auf, exakt wie oben beschrieben. Ich habe den Test mit einem Kettenhemd und einem Bogen gemacht, und der RS hat sich nicht erhöht.
Ebenfalls war der "undefined" Modifikator zu finden

**Comment by Plushtoast** [comment]
liegt tatsächlich an magie 3 und haven und ein paar anderen speziellen konditionen
mit dem baldigen update der beiden module sollte es ok sein

**Comment by Arolske** [comment]
> > Vielen Dank für den Link zu der Abdeckung der Umsetzung.
> > Ich habe es vorhin nochmal in zwei verschiedenen Welten mit dem Kettenhemd, dem langen Kettenhemd und der leichten Platte probiert. Bei allen Rüstungen wird bei mir die RS nicht modifiziert. Der jeweilige Status wird zwar am Helden angezeigt, aber nicht umgesetzt. Wenn ich im Chatfenster mit der Maus auf die RS-Zahl (in dem Fall "4") gehe, erscheint ein Tooltipp mit "undefined Modifikator*undefined Modifikator" Könnte es etwas mit der Zonen-Regel zu tun haben?
> > Mir ist auch aufgefallen, dass die Syntax im Vorteil des langen Kettenhemdes ein "," statt ";" als Trennung verwendet.
> 
> Moin zusammen, ich hoffe, es ist in Ordnung, wenn ich mich hier kurz melden. Bzgl. der Rüstungsmodifikation: Bei mir treten die gleichen Fehler auf, exakt wie oben beschrieben. Ich habe den Test mit einem Kettenhemd und einem Bogen gemacht, und der RS hat sich nicht erhöht. Ebenfalls war der "undefined" Modifikator zu finden

Vielen Dank für das schnelle Update !!
Das Problem mit den mehrfachen Einträgen beim Zwergenhelm sind gelöst. 

Allerdings besteht bei mir weiterhin das Problem mit der Rüstung. Ebenso machen z.B. Säbel nach wie vor keinen verringerten Schaden gegen Rüstungen ab RS 4.

Übersehe ich eine Einstellung?
@Schorschus Funktioniert es bei dir nach dem Update?

P.S.: Module und Rulset wurden geupdatet.

**Comment by Schorschus** [comment]
@Arolske 

Ich habe folgendes getestet: 

1. Test
Angriff mit Säbel gegen Kettenhemd (Torso)
TP vor Parade: 9 
TP nach misslungener Parade: 8 (-4)
Säbel Nachteil: TP -1 bei RS >=4
Das hat meiner Meinung nach schon mal geklappt.

![image](https://github.com/user-attachments/assets/f5d20d34-6db0-4ee9-b334-670f6d5045e2)


2. Bogen greift Kettenhemd an:
Kettenhemdvorteil: Gegen Bögen steigt RS +1
Nach erfolgten Angriff auf Torso, finde ich wieder den undefined Modifikator wieder.
Der RS ist immer noch 4
Test fehlgeschlagen
![image](https://github.com/user-attachments/assets/145b8dc6-6f5e-43ca-b36d-ff1d72417221)


Zusatz: Kettenhemd-Nachteil "Sinnesschärfe-Proben, um einen Kettenhemdträger zu bemerken, sind um 1 erleichtert." scheint bei einer Vergleichsprobe nicht zu funktionieren. Die Sinnenschärfe-Probe von Alacaya wird nicht erleichtert. Ob dies überhautp so umgesetzt wurde/wird, ist aber fraglich.

**Comment by Arolske** [comment]
Das mit dem Säbel ziehe ich zurück. Es war mein Fehler. Die Funktion macht genauso was sie soll.

**Comment by Arolske** [comment]
Hier scheint es noch mit den Waffennachteilen bei Zwergen Probleme zu geben, da sie doppelt angezeigt werden. Soll der Waffennachteil überhaupt bei Zwergen angezeigt werden?

<img width="1558" alt="fehler" src="https://github.com/user-attachments/assets/799d1e10-4f93-4725-a88b-882b86a1aaed">

**Comment by Plushtoast** [comment]
Das ist richtig so. die effekte haben unterschiedliche quellen. die einen kommen von waffennachteilen. die anderen kommen von elfen/zwergen regeln:

Elfen- und Zwergenwaffen

Elfen können alle Waffen benutzen, für sie gelten aber folgende Ausnahmen aufgrund ihre Körperbaus:

#Waffen der Kampftechnik Zweihandhiebwaffen und Zweihandschwerter können sie nur mit Abzügen von 2 auf AT, PA und TP verwenden.

#Zwergenwaffen erhalten (zusätzlich zu Abzügen aus der Fokusregel für Waffeneigenschaften) Abzüge von 1 auf AT, FK, PA und TP.

Für Zwerge sind viele Waffen einfach nicht zugeschnitten. Prinzipiell können auch sie alle Waffen benutzen, mit folgenden Einschränkungen:

#Waffen der Kampftechnik Fechtwaffen und Bögen können sie nur mit Abzügen von 2 auf AT, FK, PA und TP verwenden.

#Elfenwaffen erhalten (zusätzlich zu Abzügen aus der Fokusregel für Waffeneigenschaften) Abzüge von 1 auf AT, FK, PA und TP.

Menschen haben keine Probleme mit elfischen oder zwergischen Waffen, es sei denn, du spielst mit den Fokusregeln zu Waffeneigenschaften. Dann sind die Abzüge durch die jeweiligen Waffennachteile zu berücksichtigen.

 

Elfen- und Zwergenwaffen

Als Elfenwaffen gelten: Elfenbogen, Robbentöter, Wolfsmesser

Als Zwergenwaffen gelten: Drachenzahn, Eisenwalder, Lindwurmschläger, Felsspalter, Zwergenschlägel


Sie haben damit unterschiedliche quellen und funktionieren technisch anders. Waffennachteile können aktuell nicht unterscheiden von welcher Spezies sie ausgelöst werden.

**Comment by Arolske** [comment]
Ich verstehe.

Sollte ein Zwerg, dem ich einen Degen gebe, oder ein Elf mit Zwehänder dann nicht automatisch die Abzüge bekommen oder ist das etwas, was man händisch einträgt? Bei mir wird zumindest nichts automatisch abgezogen oder zu Auswahl gestellt.

**Comment by Plushtoast** [comment]
ja 
![grafik](https://github.com/user-attachments/assets/136de604-850d-4394-99b5-c2168e5588de)

**Comment by Arolske** [comment]
Ah, ich sehe woran es liegt. Mein Spieler hat seinen Zwerg wohl mit Optholit erstellt. Dort wird als Spezies "Zwerge" statt "Zwerg" eingetragen. Daher geht es wohl nicht. Vermutlich ist die Spezies ohne Neuanlegen des Heldens nicht mehr zu ändern.

**Comment by Arolske** [comment]
> @Arolske
> 
> Ich habe folgendes getestet:
> 
>     1. Test
>        Angriff mit Säbel gegen Kettenhemd (Torso)
>        TP vor Parade: 9
>        TP nach misslungener Parade: 8 (-4)
>        Säbel Nachteil: TP -1 bei RS >=4
>        Das hat meiner Meinung nach schon mal geklappt.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/97557642/377906611-f5d20d34-6db0-4ee9-b334-670f6d5045e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzc3MzgsIm5iZiI6MTczMDAzNzQzOCwicGF0aCI6Ii85NzU1NzY0Mi8zNzc5MDY2MTEtZjVkMjBkMzQtNmRiMC00ZWU5LWIzMzQtNjcwZjZkNTA0NWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEzNTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYzFkZDY4ZjI1NzM2YmJiNzE1ZGU1Mzg1OWI2YTYzMWEyMzhkNGVlYmQ5N2FkZjYyN2NlZmNjZDg1ZmFmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iV5ghJ1QlGtHU9XPn8zUmuO0hiF5omN-UIrVHE2FCSM)
> 
>     2. Bogen greift Kettenhemd an:
>        Kettenhemdvorteil: Gegen Bögen steigt RS +1
>        Nach erfolgten Angriff auf Torso, finde ich wieder den undefined Modifikator wieder.
>        Der RS ist immer noch 4
>        Test fehlgeschlagen
>        ![image](https://private-user-images.githubusercontent.com/97557642/377909379-145b8dc6-6f5e-43ca-b36d-ff1d72417221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzc3MzgsIm5iZiI6MTczMDAzNzQzOCwicGF0aCI6Ii85NzU1NzY0Mi8zNzc5MDkzNzktMTQ1YjhkYzYtNmY1ZS00M2NhLWIzNmQtZmYxZDcyNDE3MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI3VDEzNTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjY0NzRiNjUxOTkzNDBlZmFhZGQyZDg3OTU4ZjQ0ZTA2NzljOTBkMmIxNWFjMTBlZDczODRlODM5MDlmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9KY5RxQxXcLbK4_JNEIh-3-DCSek4A79eL48TKMlBFY)
> 
> 
> Zusatz: Kettenhemd-Nachteil "Sinnesschärfe-Proben, um einen Kettenhemdträger zu bemerken, sind um 1 erleichtert." scheint bei einer Vergleichsprobe nicht zu funktionieren. Die Sinnenschärfe-Probe von Alacaya wird nicht erleichtert. Ob dies überhautp so umgesetzt wurde/wird, ist aber fraglich.

Ich bin nach wie vor der Meinung, dass der Vorteil bei Rüstungen (wie unter 2 beschrieben) nach wie vor nicht korrekt funktionieren. Daher die Nachfrage, ob es hier aktuell noch eine Fehlersuche gibt, da das Topic ja "geschlossen" wurde?
