### ISSUE TITLE
Items aus Rüstkammer haben keine Effekte mehr 

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#1798]
Viele alltagsitems aus der Rüstkammer haben keine Effekte mehr nach dem migrieren der aktuellen Module.

Solche Sachen wie Zunder, Feuerstein & Stahl, Pergament usw. hatten für bestimmte Proben Erleichterungen gegeben.

Vielleicht vertue ich mich, weil manche Items hatte ich selbst nachgebessert, aber ich glaube, dass gerade diese Teilprobenmodifikatoren in den Alltagsgegenständen alle bereits umgesetzt waren.

**Comment by Plushtoast** [comment]
die sind nicht weg sondern bei der migration nimmt es manchmal items aus dem core modul, wo keine effekte drin sind
nach dem nächsten patch 6.1.3 nochmal migrieren dann sollte es bevorzugt items aus anderen modulen nehmen. kann hier aber trotzdem vorkommen dass es was migriert was noch nicht auf dem stand jenseits der ausrüstungsvorteile ist

**Comment by Nellkir** [comment]
> die sind nicht weg sondern bei der migration nimmt es manchmal items aus dem core modul, wo keine effekte drin sind nach dem nächsten patch 6.1.3 nochmal migrieren dann sollte es bevorzugt items aus anderen modulen nehmen. kann hier aber trotzdem vorkommen dass es was migriert was noch nicht auf dem stand jenseits der ausrüstungsvorteile ist

Das habe ich auch gedacht, aber die Beschreibung im item war definitv noch die aus der Rüstkammer.

**Comment by Plushtoast** [comment]
Beschreibungen werden nicht migriert. Nur effekte. Viele leute schreiben da sonst was rein, das wär dann weg

**Comment by Nellkir** [comment]
> Beschreibungen werden nicht migriert. Nur effekte. Viele leute schreiben da sonst was rein, das wär dann weg

Oh cool, das ist ja praktisch! 😃👍
