### ISSUE TITLE
Artefakte als Item nicht verfügbar/verwendbar

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#180]
Im Grundregelwerk gibt es Regeln zu den Artefakten (S267-270). In diesen Regeln werden auch zwei Beispielartefakte angegeben. Diese sind zwar als Items vorhanden, haben aber noch keine Effekte oder Ähnliches (nichtmal in der Beschreibung den Text).

Schön wäre es, wenn die Artefakte eine eigenen Item Kategorie bekommen bei der man sie auch korrekt anlegen kann. 
Attribute im GRW: 
NAME
BESCHREIBUNG
WIRKUNG
KOSTEN
PREIS

**Comment by Plushtoast** [comment]
duplicate to #43

**Comment by tomsaath** [comment]
Ups sorry. Dann bin ich wohl zu doof zum Suchen. Habe vorher nach Artefakten gesucht... Tut mir leid.

**Comment by Plushtoast** [comment]
duplicate of #43

**Comment by Plushtoast** [comment]
Eigene Kategorie wirds wohl nicht werden.
Es muss eher bestehenden Gegnständen eine Verzauberung geben können.
Dauert noch eine Weile.
