### ISSUE TITLE
Hintergrundvideos werden nicht mehr korrekt abgspielt

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1802]
**Describe the bug**
Wenn als Hintergrund für eine Szene eine Videodatei (MP3 oder webm) verwendet wird, werden nur die ersten paar Frames in Endlosschleife abgespielt. Auch Szenen, die im Kompendium abgelegt wurden und funktionierten, gehen nicht mehr.

**To Reproduce**
1. Szente erstellen
2. Als Hintergrundbild eine mp4- oder webm Datei auswählen.
3. Szene anzeigen

**Expected behavior**
Videos werden korrekt abgespielt

**Screenshots**

**Versions:**
- Foundry Version V12 3.31
- DSA/TDE version 6.1.3
- Related modules version

**Additional context**

**Comment by Plushtoast** [comment]
Das hat nichts mit DSA zu tun. Da musst du dir Hilfe bei Foundry suchen.
