### ISSUE TITLE
Attributschlüssel Zauberspruch/Liturgie - Trefferpunkte

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#1804]
Hallo ich habe gerade bemerkt das es nicht möglich ist diese Schlüssel hinzuzufügen. Damit könnte man einige Sonderfertigkeiten realisieren, die derzeit nicht funktionieren.

**Comment by Plushtoast** [comment]
was genau meinst du. zaubererweiterungen können den schaden bereits modifizieren. neben einigen anderen möglichkeiten

**Comment by Plushtoast** [comment]
closed in ermangelung von ausreichend information
