### ISSUE TITLE
Elixiere: QS Angabe fehlt im Feld Qualitätsstufen

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#181]
Bei den Elixieren (Antidot, Heiltrank, usw.) fehlt die QS im Feld Qualitätsstufen. 
Aktuell: 
Hebt Gifte bis zu einer Stufe von 1 auf.
Hebt Gifte bis zu einer Stufe von 2 auf.
Hebt Gifte bis zu einer Stufe von 3 auf.
Hebt Gifte bis zu einer Stufe von 4 auf.
Hebt Gifte bis zu einer Stufe von 5 auf.
Hebt Gifte bis zu einer Stufe von 6 auf.

Besser:
1: Hebt Gifte bis zu einer Stufe von 1 auf.
2: Hebt Gifte bis zu einer Stufe von 2 auf.
3: Hebt Gifte bis zu einer Stufe von 3 auf.
4: Hebt Gifte bis zu einer Stufe von 4 auf.
5: Hebt Gifte bis zu einer Stufe von 5 auf.
6: Hebt Gifte bis zu einer Stufe von 6 auf.

**Comment by Plushtoast** [comment]
Die haben wir absichtlich entfernt. Pro Zeile eine QS.
