### ISSUE TITLE
Fehlende Liturgien in Götterwirken II

### ISSUE THREAD

**Issue by frankyh75** [Plushtoast/dsa5-foundryVTT#1812]
**Describe the bug**
Es fehlen Tiersprache und  Jagdglück in Götterwirken II

**To Reproduce**
Kultur : Fjarninger
Proffession: Fjarningerschamaninen

**Expected behavior**
Lädt die Liturigen ohne Fehler

**Screenshots**
Anbei
![Fehler-Fjarninger-Schamane](https://github.com/user-attachments/assets/ca12cfe7-9d9f-46cf-94d1-ecb6871dfd3d)

**Versions:**
- Foundry Version 12 . 331
- DSA/TDE version 6.1.0
- Related modules version 6.0.1

**Additional context**

**Comment by Plushtoast** [comment]
Die sind in Götterwirken I

**Comment by Plushtoast** [comment]
Die sind in Götterwirken I
