### ISSUE TITLE
Wesensregeln Geister nicht richtig implementiert

### ISSUE THREAD

**Issue by frankyh75** [Plushtoast/dsa5-foundryVTT#1813]
**Describe the bug**
Ich glaube die Wesenregeln für Geistern sind falsch umgesetzt, zum Beispiel beim Schaden

**To Reproduce**
Ich habe versucht einen Erdgeist mit profaner Waffe anzugreifen und dann alternativ mit einer geweihten Waffe des Fjarningerschamane. Die Keule ist geweiht. Hab ich manuell in Domäne eingetragen. Ergebnis immer 0,5 also halber Schaden.

**Expected behavior**
Bei profanen Waffen ist der Schaden an Geistern 0, bei magischen und geweiten Waffen Faktor 0,5  und bei Waffen von Totengöttern normal also Faktor 1.

**Screenshots**

![elementat-schaden-0 5](https://github.com/user-attachments/assets/f99d620f-08fa-46db-a6f8-4e116ad9415d)

**Versions:**
- Foundry Version 12
- DSA/TDE version 6.1.5
- Related modules version Götterwirken II

**Additional context**
Regel zu Elementargeistern:

Vom Wesen der Geister
Als ruhelose Seele eines Toten verfügen Geister über keinen eigenen Körper. Sie mögen in manchen Fällen durch Besessenheit den Körper Lebender in Beschlag nehmen, der Tod oder die Zerstörung dieses Leibes vernichtet sie jedoch nicht. Daraus und aus ihrer Herkunft ergeben sich einige Besonderheiten:

Geister können nur durch die Zustände Furcht, Schmerz und Verwirrung beeinträchtigt werden.
Durch einen niedrigen LeP-Stand erleiden Geister keine Zustandsstufen Schmerz (siehe Regelwerk Seite 34).
Geister sind körperlos. Sie können durch feste Materie wandern, schweben oder im Boden versinken, auch wenn manche dies aus Gewohnheit nicht tun.
Werden Geister getötet, bleibt nichts Körperliches zurück.
Angriffe mit profanen Waffen verursachen keinen Schaden.
Angriffe mit geweihten Waffen von Totengöttern (z. B. Boron oder Tairach) erzeugen normalen Schaden.
Angriffe mit magischen und geweihten Waffen aller anderen Götter, sowie Zauber und Liturgien, erzeugen halben Schaden. Die Trefferpunkte werden ausgewürfelt, dann halbiert, anschließend der Rüstungsschutz abgezogen.
Geister sind immun gegen Zauber mit den Merkmalen Heilung, Illusion, Telekinese und Verwandlung.
Geister sind immun gegen Gifte und Krankheiten.
Geister können üblicherweise aus Liturgien keinen Nutzen ziehen. Hier mag es jedoch einige wenige Ausnahmen geben (Meisterentscheid).
Geister nehmen die Welt durch ihren Magiesinn wahr. Sie brauchen dafür weder Licht noch Sinnessorgane wie Augen oder Ohren. Die Reichweite beträgt etwa 200 Schritt.
Geister regenerieren durch Regenerationsphasen wie üblich, wobei sie nicht im üblichen Sinne schlafen müssen.

**Comment by Plushtoast** [comment]
Das problem ist dass ich keine liste finden konnte was totengötter alles sein soll

**Comment by frankyh75** [comment]
Sorry, Elementaregeister sind bei DSA wohl keine Geister sondern nur Elementare. Welche Regeln hast Du bei Elementaren umsetzen können, bzw. nicht umsetzen können?

**Comment by Plushtoast** [comment]
Sollte komplett sein

**Comment by frankyh75** [comment]
Danke, hat sich also erledigt, ich teste mal richtige Geister.
