### ISSUE TITLE
Effekte werden mehrfach angezeigt 

### ISSUE THREAD

**Issue by Ogrimgro** [Plushtoast/dsa5-foundryVTT#1821]
Im Probenfenster werden bei mir alle Effekte, egal ob durch Ausrüstung (z.B. Wundnähzeug), Nachteile oder aus anderen Quellen, mehrfach angezeigt. I.d.R. sind sie doppelt, vereinzelt habe ich aber auch schon dreifach gesehen.

**Comment by Plushtoast** [comment]
Kannst du einen betroffenen char anhängen. Passiert weder bei mir noch sonst wem in meinen runden.

**Comment by Ogrimgro** [comment]
[fvtt-Actor-goblin-Cbf2MTHBGbNZZo61.json](https://github.com/user-attachments/files/17788067/fvtt-Actor-goblin-Cbf2MTHBGbNZZo61.json)

Hier mal beispielhaft ein Goblin, den ich frisch aus dem Kompendium gezogen haben und mit einem Nadel&Zwirnset aus der Rüstkammer ausgestattet haben. Bei einer Probe auf Stoffbearbeitung habe ich den Effekt jetzt doppelt zur Auswahl. Das betrifft bei mir alle Effekte aus Vor-/Nachteilen und Ausrüstung. Effekte aus Status (z.B. Schmerz) scheinen nicht betroffen zu sein.

![image](https://github.com/user-attachments/assets/6aaa0bad-7b65-48e0-a670-99f0323b5268)

**Comment by Plushtoast** [comment]
Funktioniert bei mir einwandfrei.
Kannst du alle module deaktivieren und wieder aktivieren und nacheinander schauen ob eines daran schuld ist.
