### ISSUE TITLE
Fehlender Inhalt aus "Kodex der Magie" (Animisten)

### ISSUE THREAD

**Issue by Goronius** [Plushtoast/dsa5-foundryVTT#1824]
**Describe the bug**
Einige magische Handlungen (Animistenkräfte) als auch ein Waffenzauber der Animistenwaffe sind nicht implementiert. Desweiteren sind einige Kleinigkeiten falsch bzw. nicht korrekt hinterlegt. 

Im Detail handelt es sich um folgende fehlenden Animistenkräfte (Kodex der Magie; S. 38 - 43):

- Mächtiger Patronruf (Tierart) I/II
- Tiergeistsprache
- Tierkräfte I-III

Weiterhin ist aufgefallen, dass die Animistenkraft "Tierverwandlung (Tierart)" mit dem KdM (Seite 40 - 41) ein Update in der Beschreibung erhalten hat, welches noch nicht eingepfegt ist. 

Bei der Animistenwaffe fehlt folgender Waffenzauber (KdM; S. 48):

- Wut des Odûn

Bei der "Volumenerweiterung der Waffe" (KdM; S. 47) fällt auf, dass die permanenten Kosten pro Stufe (1 AsP) nicht korrekt hinterlegt sind. Stattdessen ist der Waffenzauber aktivierbar und kostet bei Verwendung 1 AsP. 

Die gleiche (falsche) AsP-Berechnung bzw. AsP-Zuordnung trifft auch auf die Krallenkettenzauber "Bindung der Krallenkette" (KdM; Seite 48) und "Volumenerweiterung der Krallenkette" (KdM; S. 50) zu. 

**To Reproduce**
Suche in der Bibliothek nach den fehlenden Animistenkräften bzw. Erstellung einer Animistenwaffe / der Krallenkette. 

**Versions:**
- Foundry Version 12
- DSA/TDE version 6.1.6

**Comment by Plushtoast** [comment]
kommt in thorwal
