### ISSUE TITLE
Angriff von hinten

### ISSUE THREAD

**Issue by Arolske** [Plushtoast/dsa5-foundryVTT#1825]
Kürzlich wurden die Vor- und Nachteile bei Waffen und Rüstungen eingeführt. Bei der leichten Platte ist der Nachteil, dass sie bei Angriffen von Hinten nur RS 1 geben. Hierfür ist auch ein Statuseffekt angelegt worden. Derzeit ist bei Angriffen keine Möglichkeit gegeben, einen Angriff von hinten auszuwählen.

**Describe the solution you'd like**
Es es ist wünschenswert, dass im Angriffsfenster eine zusätzliche Funktion für einen Angriff von hinten eingefügt wird, so dass bei einem Torsotreffer die RS 1 angewendet werden kann.

**Comment by Plushtoast** [comment]
Der Verteidigungswurf hat eine Checkbox dazu
