### ISSUE TITLE
Initiative Basiswert Berechnung

### ISSUE THREAD

**Issue by TCzerny** [Plushtoast/dsa5-foundryVTT#185]
Der Initiative Basiswert wird falsch berechnet. (Version 1.2.0)

Im actor-dsa5.js wird in der Zeile 81 der ursprüngliche Initiative Basiswert des Actors mit dem Gearmodifier neu berechnet.
Dies führt zu Nachkommastellen (initiative.value * 0.01) im Combat Encounter.

data.data.status.initiative.value += data.data.status.initiative.gearmodifier + data.data.status.initiative.value * 0.01

**Comment by Plushtoast** [comment]
Siehe hier: #137 

Funktioniert wie beabsichtigt

**Comment by Plushtoast** [comment]
Siehe hier: #137 

Funktioniert wie beabsichtigt.
Allerdings sollte die nachkommastelle erst einen Schritt  später dazu kommen.

**Comment by TCzerny** [comment]
Ok. Thx for the explanation.
