### ISSUE TITLE
Wie AsP Kosten bei Zaubern erhöhen?

### ISSUE THREAD

**Issue by ChrisFeedback** [Plushtoast/dsa5-foundryVTT#187]
Es ist keine Möglichkeit auffindbar, wie die AsP kosten vor dem Würfeln auf Zauber wie z.B. für den Balsam hochgesetzt werden können.
Dieses Feature sollte doch entsprechend Changelog in der 1.0.2 eigentlich enthalten sein. Falls die Funktion drin ist und funktioniert, aber ggf. nur schwer aufzufinden ist wäre eine ergänzende Anleitung im Wiki hilfreich.

MacOS, Chrome, DSA 1.0.2, Foundry 0.7.9

**Comment by Plushtoast** [comment]
Ah und darauf achten, dass du dein System auch auf 1.2 aktualisierst. Du hast nur die Core Modul Version von 1.0.2 angegeben.

https://github.com/Plushtoast/dsa5-foundryVTT/issues/176#issuecomment-792302983

**Comment by ChrisFeedback** [comment]
General Information Active Modules steht auf 141.2.0. Also sollte das System auf 1.2 laufen, oder?
Der Workaround mit den "Variable Basiskosten" funktioniert aber.

**Comment by Plushtoast** [comment]
Wiki komplett überarbeitet und in Tsaath's Händen.
Obsolet.
