### ISSUE TITLE
Lästige Mindergeister verschwinden nicht wieder

### ISSUE THREAD

**Issue by lorion1985** [Plushtoast/dsa5-foundryVTT#188]
Wenn bei einem Zauber die Lästigen Mindergeister erschienen sind, ist danach (fast) jede Probe dauerhaft um 1 erschwert. Die Mindergeister findet man nicht als Status und es scheint keine Möglichkeit zu geben, sie wieder zu entfernen. Sie sollten eigentlich nach 10 Minuten verschwinden.

**Comment by UrielMhezzek** [comment]
Wie soll das Programm den Wissen, wann Intime 10 Minuten rum sind. Wird Beispielsweise gekämpft, dann können 10 IT Minuten mehrere Spielabende bedeuten, wenn man erzählerisch die Tageabhandelt, sind die 10 Minuten sofort wieder vorbei. Das kann man nicht wirklich verskripten.

**Comment by lorion1985** [comment]
Nein das sollte auch nicht verskriptet werden. Aber ein Status oder etwas ähnliches wäre sinnvoll, sonst ist der Held für sein Leben lang an die Mindergeister gebunden.

**Comment by Plushtoast** [comment]
Die Mindergeister werden momentan immer dann als Option angezeigt, wenn der Charakter de Nachteil dazu besitzt.
In naher Zukunft sollten beliebe Stauseffekte möglich sein, dann lässt sich der Mindergeistnachteil im Status Tab anzeigen und entfernen.
