### ISSUE TITLE
Angaben bei den Kampfsonderfertigkeiten fehlen

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#189]
Es fehlt noch eine Angabe bei den Kampfsonderfertigkeiten. Diesen enthalten hinter dem Namen die Kategorien: passiv, Basismanöver und Spezialmanöver. Das ist in soweit relevant, da man je AT nur ein Basis und ein Spezialmanöver ansagen kann.

**Comment by mckee14** [comment]
momentan kann man so viele manöver wählen beim angriff, wie man will.

wenn man kampf-SF deklarieren kann als Basismanöver / Spezialmanöver / Other, könnte man die 3 Gruppen in eigenen Spalten anzeigen. Basis und Spezial darf nur je 1 gewählt werden, Others so viele wie man möchte (für eigene Einträge/Sonderfälle).
