### ISSUE TITLE
Zauber Dunkelheit - Beschreibung falsch

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#190]
Die Beschreibung beim Zauber Dunkelheit ist falsch. Dieser Zauber hat nichts mit Verwirrung oder ähnlichem zu tun. Der Zauber wird unter anderem beim Heshtod verwendet. Der Zauber steht aber nicht im GRW sondern im AM 1 obwohl der Heshtod im GRW steht... DSA halt :)

**Comment by Plushtoast** [comment]
Der Zauber steht auf Seite 355 im Grw.
Allerdings ist die Beschreibung tatsächlich die von große Verwirrung.

**Comment by Murm3lt13r** [comment]
Fixed
