### ISSUE TITLE
Enhance Blutrausch

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#191]
Der Status “Blutrausch” rechnet jetzt automatisch die +1 auf Nahkampf-AT mit ein (cool!), jedoch nicht die +2 TP (soweit ich sehen kann jedenfalls). Schmerz muss man auch noch manuell abwählen, wobei der Held alle Abzüge durch Schmerz ignoriert, wenn er erstmal im Blutrausch ist.

**Comment by mckee14** [comment]
Blutrausch should trigger +4AT*, +2TP, -99 pain, -99 defense**

*) only close combat, no range attacks
**) or completely forbid defense rolls at all, otherwise a crit would still be possible
