### ISSUE TITLE
Implement auto pain modifiers dependent on creature type or ability

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#192]
Kann man den Zustand “Schmerz” irgendwie manuell ausschalten? Bisher entsteht der ja automatisch basierend auf verbleibenden Lebenspunkten, aber a) manche Kreaturen (wie Dämonen oder Riesenamöben) kennen buchstäblich keinen Schmerz (bekommen ihn aber derzeit automatisch zugewiesen, wenn die LeP sinken), und b) die Sonderfertigkeit “Schmerzen unterdrücken” erlaubt ja manchen Charakteren, die Auswirkungen von Schmerzen zeitweilig zu unterdrücken. Alternativ vielleicht für Monster eine Art “Immun gegen Schmerz”-Item, was, wenn equipped, Schmerz ausschaltet?

**Comment by mckee14** [comment]
es gibt doch innerhalb des status schmerz bereits den modifikator, womit sich zb. schmerzen unterdrücken lassen, oder zusätzliche schmerzsstufen hinzufügen (giftwirkung usw.)

schmerzen sind in DSA5 recht komplex, musste ich schon feststellen, als ich die automatische schmerz-berechnung für den R20 heldenbogen implementiert hatte

wichtig: schmerzsstufe und auswirkung sind verschiedene dinge. manchmal kriegt man schmerz, hat aber keine auswirkung. mit unterdrücken und zäher hund kann man u.U. ohne abzüge kämpfen, bis man stufe 4 bekommt und (bei misslungener KBH probe) direkt aus den latschen kippt...

Könnten das auch mal bequatschen im discord o.ä., falls da etwas unklar ist. wobei du ja direkt an der quelle sitzt, die sollten das noch besser erklären können ;-)

**Comment by Plushtoast** [comment]
Geht viel mehr darum dass manche Kreaturen überhaupt kein Schmerz bekommen sollten. Wie zb Dämonen oder Untote.

**Comment by mckee14** [comment]
Auch da machts Ulisses komplex. Untote kriegen keinen Schmerz, sie können aber welchen erhalten, als Ausnahme. Es muss also weiter möglich sein, nur nicht basierend auf LeP.

Man muss quasi die Schmerzquellen unterschiedlich behandeln: Durch LeP-Verlust / direkt als Status
Zudem Modifikatoren: Automatisch (Vorteile etc) / Manuelle Korrektur
Zudem Unterscheidung: Stufe mathematisch korrekt / Stufe berücksichtigt für Auswirkung

Ein Charakter kann auch unterschiedlich geheilt werden. Es ist ein Unterschied, ob ich eine Stufe Schmerz verliere, oder nur die höchste Auswirkung ignorieren darf. Das müsste getrennt erfassbar sein.

Eigentlich viel zu kompliziert das Ganze :)
