### ISSUE TITLE
implement a merchant

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#195]
A merchant should

*Own stuff
*Have price selling factor
*Have price buying factor
*Filter accepted categories
*Have limited or unlimited money
*Be able to barter
*Have randomized goods
*Random availability
*Limited or unlimited quantity
*Also be usable as loot sheet
*Have image
*Maybe have chat lines?
*Should connect actordata or not to token?

**Comment by mckee14** [comment]
Factors like "selling, buying, availability" could be rolled upon. GM sets a range for the rolls, tough (f.e. merchant in the desert: availability [1-2], pricing [3-5],...)

Actor Data should not be connected for an archetype IMHO. (For a persistent merchant, just copy the Char, rename it and link the token.)

Maybe this merchant will be part of a possible "NPC generator", see #198 ?

**Comment by Plushtoast** [comment]
Version 1 is ready for the next patch.
We'll see what else we need for an improvement.

**Comment by mckee14** [comment]
I see, I have to get rid of my wife, so I can marry you instead.
Thx a lot :)
