### ISSUE TITLE
overhaul combat system

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#196]
It s still too slow
Add quickbuttons for default defense actions
Add death status on token
Somehow find current actor faster

**Comment by mckee14** [comment]
Finding current actor faster, plus highlight it, plus open its char-sheet, is already possible with **"next up" module**. It works wonders and makes fighting a lot better, GM management reduced by 75%.

Death status could be toggled when you reach 0 LeP, or alternatively if the GM sets the char to "dead" in the round tracker. Rules allow to save a dead person even when they drop to 0 or lower.

A real helper would be the possibility to quickly declare targets as a GM. Switching between "moving token" and "declare target" is a pain, and go via right-click is a pain, too. It would be fantastic to be able to use a shortcut.

**Comment by Nyhles** [comment]
> A real helper would be the possibility to quickly declare targets as a GM. Switching between "moving token" and "declare target" is a pain, and go via right-click is a pain, too. It would be fantastic to be able to use a shortcut.

Try the module T is for Target

**Comment by mckee14** [comment]
Module number 64, here we come!

Nyhles ***@***.***> schrieb am Mi., 17. März 2021, 22:01:

**Comment by Plushtoast** [comment]
Hm diese beiden Module lösen das Problem schon recht gut.

Die sollten wohl als Empfehlung irgendwo notiert werden.

**Comment by mckee14** [comment]
Auf jeden Fall.

Fragt sich, wie es mit langfristiger Kompatibilität aussieht (zumal Foundry
0.8 ja recht viel umkrempelt).

Plushtoast ***@***.***> schrieb am Do., 18. März 2021, 18:45:
