### ISSUE TITLE
Initiativewerte mit zwei Nachkommastellen angegeben

### ISSUE THREAD

**Issue by ChrisFeedback** [Plushtoast/dsa5-foundryVTT#197]
Im Combat Tracker wird die Initiative der einzelnen Helden neuerdings mit zwei Nachkommastellen angegeben. Bei DSA wird aber gerundet, weswegen das an der Stelle befremdlich aussieht:

<img width="297" alt="Bildschirmfoto 2021-03-15 um 19 47 02" src="https://user-images.githubusercontent.com/79937134/111289831-d4716a00-8645-11eb-88d4-59e77ec0c388.png">

MacOS, Chrome, Foundry 0.7.9, DSA 1.2.0

**Comment by Plushtoast** [comment]
See #137

**Comment by ChrisFeedback** [comment]
Die Regel, dass bei gerundet gleichem Ini Basiswert erneut ein Vergleich mit dem W6 gewürfelt wird, wird durch die aktuelle Umsetzung ausgehoben. Das passt, wenn das wie im verlinkten Ticket gewünscht ist. Allerdings wäre es schöner, wenn diese Detailberechnung im Hintergrund passiert und man als Spieler nicht mit den Nachkommastellen konfrontiert wird.

**Comment by tomsaath** [comment]
Ich glaube was er damit meint ist, dass das keine Nachkommastelle ist. Es ist der INI Basiswert. Damit dann bei gleicher INI nach dem Basiswert sortiert werden kann. Also INI.INIBASIS

**Comment by mckee14** [comment]
Der Rundenzähler sortiert nach Zahlenwert. Wenn man den Basiswert als Nachkommastelle anhängt, dann kommt bei Gleichstand automatisch der Charakter zuerst, der die höhere Basis-INI hat. Anders lässt sich das nicht lösen, und dieses Prinzip hat sich schon lange auf anderen Plattformen etabliert. 

Was noch fehlt, ist die Dokumentation dazu, dann ist das auch verständlich für den user. Nach einem Release kommen aber meist so viele Changerequests und Bugmeldungen, dass man damit erst mal ne ganze Weile beschäftigt ist :).

**Comment by Nyhles** [comment]
Vielleicht sollte das mal angepinnt werden, es wird ja oft genug angemerkt.

**Comment by tomsaath** [comment]
Es wird bald n Wiki Eintrag dazu geben
