### ISSUE TITLE
Random char generator (low prio)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#198]
Erstellen von NPC mit wenigen Klicks, mit zufälligen Werten.

Angabe Erfahrungsgrad und freie Auswahl aus den hinterlegten Berufen, Spezies, Regionen. Erstellt einen NPC Bogen mit zufälligen Werten. Keine hohe Komplexität nötig - Archetyp des Berufs, restliche AP zufällig auf Talente verteilen (mit höherer Gewichtung in Talenten, die der Beruf mit sich bringt).

**Alternative: Einige wenige Archetypen anbieten** (Dorfbewohner, Gardist, Seefahrer, Händler...), in den vorhandenen Erfahrungsgraden. So entfällt das "generieren" komplett. [(Beispiel Gardist)](https://ulisses-regelwiki.de/index.php/Best_Gardist.html)

Optional:
 - Namen generieren, basierend auf Geschlecht und Herkunft (Implementierung "Aventurische Namen")
 - Angabe von Verzeichnis, aus welchem Zufällig ein Token gezogen wird, so dass der user eine Bibliothek anlegen kann.

**Comment by Plushtoast** [comment]
Leider ziemlich aufwändig.
Aber das steht auf dem Plan.

**Comment by mckee14** [comment]
Wenn Du schon eine Idee hast, wohin / wie sich das entwickelt - bei reinen fleissaufgaben bin ich dir gerne behilflich.
zB die Archetypen erstellen mit den Werten gemäss DSA5 wiki oder sowas.

Den ganzen Aufwand nur für meine persönliche Installation finde ich halt sinnfrei, wenn es später dann über das modul kommt.

(also ich will keinen code anfassen, aber innerhalb foundry Chars erstellen und dir den export schicken - was halt zeit kostet, aber eigentlich jeder kann mit 2 augen, einem finger und bisschen qualitätskontrolle)

**Comment by Violettdragon** [comment]
Kommen nicht zu jeden Buch eh nicht noch Archetypen? Götterwirken, Magie usw usf.

**Comment by Plushtoast** [comment]
Man kann nie genug NPCs haben :)

**Comment by Plushtoast** [comment]
Man könnte sich mal überlegen wie eine Zufalls NPC Generierung aussehen könnte.

z.b. Angabe 100 punkte für Attribute, 100 punkte für Talente und 2 zufällige Vor/Nachteile und 5 sonderfertigkeiten oder so
Wahrscheinlich ohne Berechnung der AP, das das eher langsam und aufwendig wäre.

Oder ein Char als Vorlage und alle Werte etwas modifizieren. 

Oder jeden Wert random von x bis y.

Dazu bräuchte man vermutlich eben die o.g. Liste an Namen, sowie ein Ordner mit Bildern, den jede Gruppe aber selbst anlegen muss.

Irgendwie muss es dann auch noch so schnell gehen, dass man den einfach platzieren kann und keiner der Spieler merkt, dass das improvisiert war.

**Comment by mckee14** [comment]
Eine echte Generierung auf Kopfdruck stelle ich mir viel zu komplex vor für DSA. Jede SF, Vorteile etc. haben ja etliche Voraussetzungen.

In der Praxis sollte es reichen, wenn man gewisse Archetypen erstellt, auf verschiedenen AP-Levels.
Darauf basierend können dann zufällige Abweichungen verteilt werden, zufällige Vor-/Nachteile und SF. Dabei sollten einzelne Talente für bestimmte Archetypen ein absolutes Minimum haben, sonst kriegt man Händler ohne Handeln-Talent.

Dieses Modul alleine dürfte ja schon einen rechten Aufwand generieren.

Wie es sich mit Namen, Beschreibungen und Porträts / Token verhalten soll, ist eine Frage des Aufwands und der Produkte, die released werden sollen.

Wenn Ulisses "Aventurische Namen" als Modul veröffentlichen möchte, könnte man hier eine optionale Anbindung einbauen (wobei da wohl bei vielen die Schmerzgrenze für mehrfach bezahlte Inhalte erreicht wäre, quasi "nur für Namen" nochmals zahlen). Ansonsten müsste man einen separaten Namens-Generator coden. Je nach Rohformat der Daten kann das sehr viel Arbeit bedeuten... Wäre aber schon total cool, wenn NSCs automatisch einen passenden Namen kriegen.

Zu den Bildern, das sehe ich auch so: Die user müssen sich ihre Vorlagen selber organisieren. Gut wäre aber, wenn man dafür eine vordefinierte Ablagestruktur erhält, (Bsp: Händler ...\novadi\portraits und ...\novadi\token. 
In den Ordnern legt man die Bilder ab, nach Namensschema "namename-001-m.webm", "namename-002-f.png" usw.

Durch f/m/d kann man das Geschlecht definieren (d oder sonstwas könnte man verwenden, falls man nebst menschlichen NSCs auch einmal auf viecher ausweiten möchte).
Alternativ ein Interface innerhalb Foundrys, in welchem man bilder hochladen und token erstellen kann, ähnlich tokenizer. Dabei sollte die dateibenennung automatisch geschehen, und durch auswahl von spezies und kultur wird der entsprechede ordner verwendet.

Ganz toll wäre es, wenn die Werte / Abweichungen beim Erstellen des NSC nicht hardcoded wären, sondern veränderbar in einer GUI via Optionsmenü.

Usecase:
Button über den Charakteren "Generate NSC"
PopUp: Auswahl von Spezies / Geschlecht / AP / Kultur / Beruf (alternativ "Random")
NPC wird generiert und als Charakter abgelegt, mit vollen LeP, KaP, AsP. Inklusive Portraitbild, Namen und Token (sofern vorhanden)

So ungefähr hätte ich mir das vorgestellt...

**Comment by UralterMannII** [comment]
Als minimaler erster Schritt würde mir eine NSC-Token- (und Namen-)"Mixer" reichen, der mir die Token von (Szenen-)Actors ändert (Token z.B. aus einem Verzeichnis, in dem ich diese hineinkopiert/gesammelt habe). Wenn man da per Hand arbeitet und mal 20 NSCs haben will (um die Szene Markplatz etwas belebter zu gestalten) fallen einem die Finger ab. (Den Spieler lernen dazu: Der Archtype X hat das Token Y...und der Token ist neu...das muss der wichtige NSC sein...)...
--> Gibt es schon von Foundryvtt selber :) https://foundryvtt.com/article/tokens/ Abschnitt Wildcard Token Images

Nächster Schritt: Eine "Generator" der mir dann 1-n Actors (inkl. random-Token, Namen wobei Werte egal) erzeugt. 

Nächster Schritt: Der "Generator" verwendet (auch) die Archetypen aus den DSA-Modulen als Basis für die Werte...
