### ISSUE TITLE
Question: Only GM can reduce the damage point?

### ISSUE THREAD

**Issue by Violettdragon** [Plushtoast/dsa5-foundryVTT#212]
Here the view of the GM:
![Meister](https://user-images.githubusercontent.com/79411612/111978230-fe260780-8b03-11eb-887f-92278882339e.png)
and here the view of the player:
![Spieler](https://user-images.githubusercontent.com/79411612/111978331-126a0480-8b04-11eb-8b8e-ca4ce5e7354f.png)

Is this correct?
it would be a lot less work for the game master if the players could do it themselves.

however, it works with regeneration.

**Comment by Plushtoast** [comment]
That's the intended behaviour right now.
A player should easiliy have the time to change that value on the token or the character sheet...

**Comment by Plushtoast** [comment]
This will be restricted a little more. Only the gm can see the final damage value in the future. But maybe there will be a setting to change this,
