### ISSUE TITLE
Vorteilhafte Position als Status

### ISSUE THREAD

**Issue by Zamino** [Plushtoast/dsa5-foundryVTT#213]
Aktuell kann ich keine Möglichkeit entdecken, eine vorteilhafte Position einzutragen. Wäre es möglich, diese als Status zu ermöglichen?

**Comment by Plushtoast** [comment]
Das wird jetzt erstmal als Modifikator vorhanden sein. Status vlt im Zuge der Automatisierung irgendwann.
Bzw sobald man Rolldialog speichern kann bzw die letzte Einstellung übernommen werden kann, is das eh obsolet.

**Comment by Zamino** [comment]
Ok, vielen Dank
