### ISSUE TITLE
Actordsa5.create() should return actor

### ISSUE THREAD

**Issue by ntfoster** [Plushtoast/dsa5-foundryVTT#216]
While I don't think this is causing a bug at the moment, it is causing a problem for module development, and doesn't match the expected behaviour.

I am working on a module to import characters into Foundry, and have an issue that when calling:
```javascript 
CONFIG.Actor.entityClass.create({name:"Foo",type:"character"}) 
``` 
which resolves to ``Actordsa5.create(...)``, it does not return an actor object. If you call ``Actor.create(...)``, then an actor object *is* returned, but doesn't have all of the features (skills, image, etc.) that are created by the Actordsa5 constructor.

Would it be possible to change line 41 of ``modules/actor/actor-dsa5.js`` (in v1.2.1) from
```javascript 
super.create(data, options); 
```
to 
```javascript 
return super.create(data, options);
```
?
Many thanks for your work on this system!

**Comment by Plushtoast** [comment]
Schön zu hören,dass das Erste externe Modul in Arbeit ist. 
Kannst du beschreiben,was genau du da bauen willst?

**Comment by ntfoster** [comment]
> Nice to hear about the development of the first external module. Can you describe what you plan to create there?

I am working on a module to import characters from [Optolith](https://optolith.app/) by reading the exported JSON files, but it is still very early and as I am still quite new to Foundry development it will take a while to be fully ready, but the basics of attributes, skills and Advantages/Disadvantages seem to be working ok.

**Comment by Plushtoast** [comment]
Once you are ready we would love to look at it and see if we can incorporate that into the system.
We were planning to improve the character generation in the future with things like that.
