### ISSUE TITLE
Sicht und Dunkelheit

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#221]
Setzen von Sichtbehinderung und Dunkelheitsmodifikator (Stufe 0 - 4)
(Pro Szene, Global oder pro Kampf)

Total Sichtmodifikator = Dunkelheit & Sichtbehinderung (Nebel, Schnee...)
Dunkelsicht reduziert "Dunkelheit" für den Char, aber nicht die Sichtbehinderung.

Angriff/Verteidigungswürfe sollten einen Modifikator zulassen, für Ausnahmen.

**Comment by Plushtoast** [comment]
Hm, szenenbasierte Modifikatoren...das ist wahrscheinlich ein größeres/aufwendiges Feature.

**Comment by mckee14** [comment]
Globale Modifikatoren auf Charakterbasis reichen ja auch.

Char 1 hat Dunkelheit 2 und Sichteinschränkung 1 (Nebel), Char 2 hat nur
Sichteinschränkung 1 (dank Dunkelsicht), manuell gesetzt.

Kann auf der Kampfseite platz haben im charbogen, oder direkt im popout
talent/angriffswurf.
Wäre toll, wenn das zuletzt gewählte automatisch gesetzt bleibt, damit man
das nicht bei jedem wurf neu eingeben muss.



Plushtoast ***@***.***> schrieb am Fr., 9. Apr. 2021, 20:25:

**Comment by Plushtoast** [comment]
Also bis auf "zuletzt gewählt" haben wir das jetzt so oder nicht?

**Comment by Plushtoast** [comment]
Duplicate of #252
