### ISSUE TITLE
NSCs, die bereits verteidigt haben markieren

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#225]
Gerade bei mehreren Gegnern muss überblickt werden, ob der Betreffende bereits verteidigt hat. NSCs dürfen ja meistens nur einmal verteidigen pro Runde.

Ein Symbol, dass anzeigt, wenn der NSC bereits seine Verteidigung gewürfelt hat.

**Comment by Violettdragon** [comment]
Das NSC nur 1 mal verteidigen können, kann man Optional aber aufheben (siehe RGW S. 232 Graues Kästchen).

**Comment by Plushtoast** [comment]
Geplant ist, den Wert in # Verteidigungen automatisch hochzuzählen und nach jeder Runde zu resetten.

**Comment by mckee14** [comment]
Es wäre toll, wenn die [n-1]te Verteidigung automatisch als Anzahl im Popup Fenster eingetragen wird.

Viecher mit einem Verteidigungs-Wert (anstatt Ausweichen / Parieren), dürfen so oft Verteidigen wie sie möchten pro Runde, und bekommen keine Abzüge dafür. Hier müsste das Modul erkennen, ob es ein Viech ist.

Ob NSC mehr als 1 mal pro KR Verteidigen dürfen, ist eine Optionalregel. Wäre toll, wenn man das generell in den Optionen einstellen könnte, aber im Charsheet übersteuern.

Das Modul könnte dann 
jedem Char 1 AW/PA erlauben
wichtigen NSC weitere AW/PA erlauben, mit Reduzierung der AW/PA Werte
Nicht-Humanoiden weitere Verteidigungen erlauben, ohne Reduzierung des VT Werts.
