### ISSUE TITLE
Sammelproben automatisieren

### ISSUE THREAD

**Issue by Ben528491** [Plushtoast/dsa5-foundryVTT#228]
Der Befehl /rq [Probe] fragt momentan eine Probe von allen Spielern ab. Das funktioniert jedoch nicht als Chatmakro. Gibt es eine Möglichkeit, das zu automatisieren, z.B. mit einem Skriptmakro?

Am besten wäre natürlich eine GUI-Erweiterung, damit der SL Proben schnell abfragen kann, falls es eure Zeit zulässt daran zu arbeiten.

Danke für die bisherige Arbeit :)

**Comment by Plushtoast** [comment]
Als Macro gehts übrigens seit 1.3.0 über game.dsa5.macro.requestRoll("Betören", 1);

**Comment by Ben528491** [comment]
Funktioniert super das Makro. Herzlichen Dank!
