### ISSUE TITLE
Bibliothek->Zoo hat keine Suchkriterien zum auswählen 

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#231]
Talente (z.B. Loyalität)
Vorteile
Eigenschaften
Vertautentricks
Sonderfertigkeiten
Kampffertigkeiten
Region/-en wo man sie findet

**Comment by Plushtoast** [comment]
Diese Filterkategorien sind aufgrund der Datenstruktur eher ungeeignet zum Suchen.

**Comment by Plushtoast** [comment]
Duplicate of #209
