### ISSUE TITLE
Vorteil " Zauberer" alleine angewendet auf Bogen funktioniert nicht

### ISSUE THREAD

**Issue by Stobili** [Plushtoast/dsa5-foundryVTT#232]
Zieht man den Vorteil Zauberer auf einen Charakterbogen, NPC- Bogen. oder Kreatur werden keine Astralpunkte Hinzugefügt Weder als ASP-Leiste noch als genereller Wert
<img width="534" alt="Bugreport" src="https://user-images.githubusercontent.com/77391908/113183477-5d96bc80-9254-11eb-8894-b9601b24d36c.PNG">

**Comment by Plushtoast** [comment]
Schau dir mal das an:
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/Spellcaster--and--Blessed-One-Creation
