### ISSUE TITLE
Kritischer Angriff - halbe Parade

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#235]
also soweit ich das nachvollziehen kann wird aktuell ein kritischer Erfolg noch nicht automatisch auf die Verteidigung des Gegners angewendet. So wie der Kampf aktuell abläuft sollte es doch aber möglich sein dies zu programmieren?

Es wäre zumindest schön wenn das System das irgendwie automatisch berücksichtigt.

**Comment by Plushtoast** [comment]
Duplicate to #184

**Comment by Plushtoast** [comment]
duplicate of #184

**Comment by tomsaath** [comment]
Ach sorry, ich bin irgendwie zu blöd zum Suchen... Habe aber auch nicht auf Englisch gesucht.
