### ISSUE TITLE
Fehler beim Öffnen der Charaktere aus AG I

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#237]
Bei einigen der Charaktere aus dem AG I kommt es beim öffnen des Chars im Kompendium zu einer Fehlermeldung: Uncaught (in promise) Error: Cannot read property 'effects' of null.

Ist der Charakter importiert, erscheint die Fehlermeldung nicht mehr.

Ich habe alle Module einmal deaktiviert, der Fehler tritt trotzdem noch auf.

**Comment by Plushtoast** [comment]
Der Fehler passiert, weil Charaktere in Kompendien nicht aktualisiert werden können. Insbesondere bei eingebetteten Eigenschaften wie Gegenständen geht das nicht. Beim Charsheet öffnen werden ein paar Dinge berechnet, die dann nicht aktualisiert werden können. Der Fehler ist bedeutunglos. Einfach die Chars importieren, dann geht das. Generell sollten Kreaturen und Chars nicht aus Kompendien heraus benutzt werden.
