### ISSUE TITLE
Active Effects: Duration

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#238]
There is a section for duration settings for self created active effects. But in my tests, it does nothing at all.
There is also a field to reference a combat tracker, but it's inactive.

Is this supposed to work (buggy)?
Is it working, and I'm using it wrong (may be worth a wiki entry)?

In case this should work or is planned to work one day, it would be very nice to choose if an effect gets de-activated only, or completely deleted, once it runs out.

**Comment by Plushtoast** [comment]
That is not yet supposed to work.

**Comment by mckee14** [comment]
thx, therefore can be closed

**Comment by Plushtoast** [comment]
So my researches found this:
 Foundry does at this point not support automatic expiry.

The modules about-time and times-up cover this topic already very well.
times-up is good for combat rounds and about-time is good for normal times (like hours)

If you want to use the duration you should use those modules. We will add a wiki section on how to do this too.
