### ISSUE TITLE
Ausrüstung der Kategorie "Behältnis" sollte es möglich sein weiter Items hineinzutun. 

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#239]
Idealerweise kann man einstellen wie groß bzw. wieviel Platz /Anzahl Plätze max. Gewicht Eines oder aller Gegenstände es aufnehmen kann. 
Oder was für Gegenstände man hinein tun kann (Verbrauchsgegenstände/Rüstung/Waffen etc).
Als Beispiel: eine Geldkatze sollte jetzt nicht in der Lage sein einen Zweihänder aufzunehmen weder Gewicht noch Größe.
UND das man mit einer (Select-box auswählen kann ob man den Gegenstad grad trägt ober abgesetzt hat. (Wen der Held den Viel zu schweren Rucksack vor dem Kampf ablegt damit die BE nicht so hoch ist)

**Comment by Plushtoast** [comment]
Duplicate to #207 

Wir werden allerdings nicht abprüfen, was die Spieler da in ihre Taschen packen. Das kann jeder mit ein bisschen Verstand selbst regeln.
