### ISSUE TITLE
Es gibt Talente/Sonderfähigkeit die nach gebessert werden könnten

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#240]
Als bei spiel die tierische Sonderfertigkeit "Vertrauter" gibt laut Beschreibung: 
Boni für Vertraute
+10 LeP
+1 RS
+1 SK
+1 ZK
15 AsP
dies kann an bei den Detais unter Effekt gleich eintragen: "+10 LE, +1 RS, +1 SK, +1 ZK, +15 AsP,"
dadurch würde automatisch wenn man einem Tier die Sonderfertigkeit gibt die wert richtig gesetzt werden.
Das gleich habe ich bei dem Sonderfertigkeit/Kampftalent für Tiere gesehen "Anspringen" dies macht: 
-4 AT 
+1d3 TP
das kann man auch so eintragen : "-4 AT, +1d3 TP"
so wird hier bei erfolgreichem Angrif mit der Kampffähigkeit gleich der d3 mit gewürfelt.

**Comment by Plushtoast** [comment]
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/Familiar

**Comment by Plushtoast** [comment]
Soweit ich das weiß gilt für Anspringen, dass der Schaden nicht zusätzlich ist, sonder anstelle des normalen Schadens.
