### ISSUE TITLE
Sonderfertigkeit "Begleiter" hinzufügen (ähnlich wie "Vertrauter")

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#241]
Wenn man z.B. einen Hund (oder jedes Andere Tier das man Abrichten möchte) als Begleiter haben möchte brauch man wie bei "Vertrauter" die Möglichkeit Exp dem Tier geben zu können.
Dadurch sollte dann auch Ausbildung Stats dem Tier geben können.

**Comment by mckee14** [comment]
Das wäre in der Tat fein. Kommt allenfalls separat als Modul "Tiergefährten"? ;-)

Tipp: Vertrauter erstellen, und manuell die Vertrauten-Boni wieder abziehen. Dann hast Du ein normales Tier und die Möglichkeit, XP auszugeben dafür / damit.

**Comment by Plushtoast** [comment]
Schauen uns das an, wenn wir am entsprechend en Buch sind.

**Comment by mckee14** [comment]
Der angehängte Nachteil kann als item importiert werden. Einfach einem Vertrautentier geben, dann entsprechen die Werte einem normalen Begleiter.

[fvtt-Item-Begleiter.json.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6284044/fvtt-Item-Begleiter.json.zip)
