### ISSUE TITLE
Merchant feature suggestions

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#246]
* Lifeenergy bar for lootsheets
* Lock loot shields similar to doors

**Comment by Nyhles** [comment]
- Make it possible to transfer more than one coin at once. Right now it is very tedious if there is a treasure with e.g. 100 coins, therfore needing 100 clicks.

**Comment by Plushtoast** [comment]
Try holding "strg" for moving 10 at a time. Maybe I#ll add another button.
This works on other locations too.

**Comment by Coldor** [comment]
- Would be nice to be able to give seperate / exclusive player permissions for each token that is placed on different scenes. 
- A special permission that let's players interact with that token (like limited permission right now) on that specific scene, but are not able to see it under the items-tab, when permissions are given. That would prevent Story-Spoilers when a GM is setting up scenes. Right now, GMs must give permissions under the item-tab for each merchant / treasure-Token and those can be seen by all players, even if they have not reached that scene yet.

**Comment by Coldor** [comment]
No weight for Items when in Merchant / Treasure-Window. Tokens are always overburdend because of so much stuff "in them". Alternatively merchants / treasures have super high KK (Strength) or status effects can be disabled for NPC-Tokens.

**Comment by Plushtoast** [comment]
> 
> 
>     * Would be nice to be able to give seperate / exclusive player permissions for each token that is placed on different scenes.
> 
>     * A special permission that let's players interact with that token (like limited permission right now) on that specific scene, but are not able to see it under the items-tab, when permissions are given. That would prevent Story-Spoilers when a GM is setting up scenes. Right now, GMs must give permissions under the item-tab for each merchant / treasure-Token and those can be seen by all players, even if they have not reached that scene yet.

That's impossible. That is not allowed by the default Foundry settings and would require a unresonable amount of messing around with the code. Hiding the trader's inventory in the sidebar might be possible, but the actor will still be visible to the players at any time, once the permissions are set.
