### ISSUE TITLE
General Modifiers in active effects?

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#248]
I couldn't find some **general modifiers (AT, TP, PA)** when looking trough the actor data.

My guess is that modificators (from gear etc) like "+1 PA" are processed by code outside of the character data objects?

**It would be helpful to have these modificators adressable via active status effects.** Most effects change something in general, influencing all weapons / attacks / defenses.

**Comment by Plushtoast** [comment]
Maybe those modifiers have to be removed in favor of a better system first... We'll see.

**Comment by mckee14** [comment]
OK, so currently its
 - specific modifiers possible via active effects
 - general modifiers via gear as a work around

Thanks for clarification.

Plushtoast ***@***.***> schrieb am Di., 6. Apr. 2021, 11:40:

**Comment by Plushtoast** [comment]
This will be possible with 1.3.1 via:

data.meleeStats.attack
data.meleeStats.parry
data.meleeStats.damage

data.rangeStats.attack
data.rangeStats.damage

**Comment by mckee14** [comment]
Thanks a bunch!!
