### ISSUE TITLE
Proben können aktuell nicht um 2 oder 4 erschwert werden

### ISSUE THREAD

**Issue by Zamino** [Plushtoast/dsa5-foundryVTT#249]
Aktuell können Proben nur um 1,3 und 5 erschwert oder eleichtert werden.

zB: Talentprobe, Schwierigkeit

Bitte auch eine Modifikation um 2 und 4 ermöglichen. Vielen Dank und macht weiter so

**Comment by Plushtoast** [comment]
Du solltest über das Modifikatorfeld eintragen können,was auch immer du möchtest. Die Schwierigkeiten sind aus dem grw vorgegeben.

**Comment by mckee14** [comment]
![Screenshot_20210409-100016_Firefox](https://user-images.githubusercontent.com/62849695/114148815-7b31e900-991a-11eb-9d3e-10ddb39211a5.jpg)

1. Modifikator für die ganze Probe. Hier kannst du frei Erleichterungen oder Erschwernisse eintragen (das, was du suchst)
2. Teilmodifikatoren, wenn zB nur die FF Probe erleichtert ist, kannst du hier  eintragen
3. Hier kannst du zusätzliche FP für die Probe mitgeben. Nützlich, wenn du Spezialisierungen hast, oder für gewisse SF und Vorteile.
4. Hier kannst du Bonus QS mitgeben, damit du zB die Probe um 1QS höher besteht, wenn du sie bestehst. Wird also nur bei bestandener Probe nachträglich addiert.

**Comment by Zamino** [comment]
Vielen Dank für deine Rückmeldung. Das hilft mir sehr weiter. 

Eine Frage noch: In deinem Screenshot gibt es das Feld mit „Anspruchsvoll (+0)“. Wofür ist dieses Feld gedacht, wenn es oben das erste Feld (Zahl 1) gibt? Intuitiv nahm unsere Runde an, dass dort die Modifikatoren einzutragen sind, wenn ich als Meister eine um 2 erschwerte Probe verlange. 

Ich konnte im GRW keine Limitierung auf -1 -3 -5 finden. Lediglich auf Seite 24 entdeckte ich eine Tabelle mit Modifikatoren als Beispiele. Da dort "Beispiele" steht interpretiere ich das nicht als einzig erlaubte Auswahl. Eine Probe erschwert um -2 wäre für mich nach der Tabelle noch immer eine "schwierige Probe". Auf Seite 19 werden sogar runde Zahlen als Beispiele für Modifikatoren angegeben. Das stärkt mein Gefühl, dass alle Ganzzahlen als Modifikatoren erlaubt sein dürften, oder irre ich und es steht irgendwo explizit? 
Wie auch immer, vielen Dank, dass ihr euch um die Umsetzung dieses großartigen Tools kümmert. Ich freue mich sehr über jedes Update. :-)

**Comment by mckee14** [comment]
Das Dropdown Menü mit den vorgegebenen Modifikatoren ist quasi
gleichbedeutend mit dem Feld Nr. 1. Das Dropdown ist ein schnellzugriff auf
vordefinierte Modifikatoren, das Feld erlaubt freie Eingaben. Sie tun aber
das Gleiche.

Teste mal: dropdown auf +5, Feld 1 auf -5 :)

Zamino ***@***.***> schrieb am Fr., 9. Apr. 2021, 10:52:
