### ISSUE TITLE
Zauberbarden falsche AsP Berechnung

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#250]
Zauberbarden bekommen aktuell die ganze Leiteigenschaft auf ihre AsP drauf gerechnet.
Korrekt bei dieser Tradition wäre die halbe Leiteigenschaft

**Comment by Plushtoast** [comment]
Du musst manuell hier den Multiplikator eintragen im Magie Tab (0.5):

![grafik](https://user-images.githubusercontent.com/44941845/113822816-33765a80-977e-11eb-83b9-f5cfd2c0c12b.png)

Das geht leider nicht automatisch, beim hinzufügen der Tradition.

**Comment by Nellkir** [comment]
Das Feld habe ich wohl übersehen. 
Dankeschön :-)
