### ISSUE TITLE
Frage: Teilprobe modifizierbar in SF oder Items?

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#251]
Bei Sonderfertigkeiten oder Gegenständen (oder anderen Items) ist es möglich die  Fertigkeitsprobe über die Effektleiste zu beeinflussen. 
Bisher kenne ich aber nur die Möglichkeit die Probe komplett zu erschweren/erleichtern und/oder nur die FP zu erhöhen/senken.
Gibt es aber auch die Möglichkeit nur eine oder zwei Eigenschaften dieser Probe über die Effektleiste zu beeinflussen?
Wenn ja, welcher Befehl wäre das? 

Wäre auch gut, wenn man in dieser Leiste die QS beeinflussen könnte. Momentan schummeln ich das über FP+3 rein, anstatt QS+1

**Comment by Plushtoast** [comment]
Gibts noch nicht.

**Comment by RondraLion** [comment]
Das geht doch oder sehe ich falsch.

**Comment by Nellkir** [comment]
> Das geht doch oder sehe ich falsch. https://ibb.co/z89d1qN

Ja, das man das manuell eingeben kann, weiß ich. Hätte das aber gerne als Auswahlmenö gehabt, wie die anderen Effekte, damit man nicht dran denken braucht ^^

**Comment by Nellkir** [comment]
> Gibts noch nicht.

Ok, danke

**Comment by Plushtoast** [comment]
Duplicate of #73
