### ISSUE TITLE
Sight modifications for meele attacks

### ISSUE THREAD

**Issue by TheFrazer** [Plushtoast/dsa5-foundryVTT#252]
When fighting in darkness the AT should be halved, which is quite tedious to calculate and then input as a modifier.
An additional option in the attack sheet, similar to the ranged attacks would be quite helpful!

Like the ranged attacks the melee attacks are also affected by sight modifications.
According to _Regelwerk (4. überarb. Aufl.), Seite 239_ the modifications are as follows:
Sight modification 1: -1 AT/VW
Sight modification 2: -2 AT/VW
Sight modification 3: -3 AT/VW
Sight modification 4: AT is halved (unknown - to me - if additional modifications are subtracted/added beforehand or afterwards); Defense only on an 1 on a d20.

Edit: It seems, that the AT is first halved and then the modifications get added/subtracted. But I couldn't find the text passage where that is written down.
The halving of the damage for deamons with armor is calculated that way too. First the damge is halved and the the armor is deducted.

**Comment by TheFrazer** [comment]
The current implementation seems to also simply uses a modification of -5000. But unlike with ranged attacks, that only hit on a 1, meele attacks are only halfed at sight 4: AT12 -> AT6.

**Comment by TheFrazer** [comment]
Thanks for the quick fix! But its still not quite right.
The attack seems to work like intended, but the parry should only work on a 1 at sight 4.

Sorry for all the work.

**Comment by Plushtoast** [comment]
Vielleicht ja dieses mal...

**Comment by TheFrazer** [comment]
Jetzt passts :)
