### ISSUE TITLE
Anregung für bessere Übersicht der Zaubererweiterungen

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#256]
Die bereits erlernten Zaubererweiterungen sind in der allgemeinen Zauberaufstellung des Charaktersheets nicht ersichtlich, erst bei detaillierter Auswahl des Zaubers. Wünschenswert wäre zumindest ein Hinweis, dass bei diesem Zauber eine Erweiterung gelernt wurde.

**Comment by Plushtoast** [comment]
Is zwar jetzt drin. Aber vielleicht noch nicht ganz perfekt.
