### ISSUE TITLE
Diverse Chars aus Götterpaket nicht vollständig nutzbar

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#267]
Amaziella Bosvani: Roter Schleier. Cannot read item propertys von  undefined
Belemanias: Analen des Götterzeitalters.  Cannot read item propertys von  undefined
Caya: Cannot read property "effects" of null
Delgado Rochas: Fehlerfrei
Eshila: Cannot read property "effects" of null
Fadime:  Mondamulet.  Cannot read item propertys von  undefined
Golgoran:  Cannot read property "effects" of null
Haldar Garulfson:  Cannot read property "effects" of null

Roter Schleier und Mondamulett konnte ich in der Bibliothek finden. Die Analen nicht.

**Comment by Plushtoast** [comment]
Der Fehler passiert, weil Charaktere in Kompendien nicht aktualisiert werden können. Insbesondere bei eingebetteten Eigenschaften wie Gegenständen geht das nicht. Der Fehler ist bedeutunglos. Einfach die Chars importieren, dann geht das. Generell sollten Kreaturen und Chars nicht aus Kompendien heraus benutzt werden.

Annalen mit zwei n schreiben, dann kann man es finden.

![grafik](https://user-images.githubusercontent.com/44941845/114263013-5190c480-99e3-11eb-9e87-fbb9d39c9ffa.png)

**Comment by Plushtoast** [comment]
Duplicate of #237
