### ISSUE TITLE
Ap berechnung von Vertrauten/Tierbegleitern automatisieren

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#268]
Hallo ist es möglich die AP von Vertrauten und Tierbegleitern zu automatisieren. Denn derzeit werden diese wie Scs behandelt wo man die Erfahrungsstufe wählen muss. Aber eigentlich bekommen die Tiere nur 25% bzw. 10% der Ap die der besitzende Held hat.---> Nach der Heldenerstellung

**Comment by Plushtoast** [comment]
Nein, du musst die AP manuell eintragen unter Eigenschaften.
