### ISSUE TITLE
Buggy Character (INI, GS & BE)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#269]
[fvtt-Actor-Gerambalosch.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6292009/fvtt-Actor-Gerambalosch.zip)

With his armor eqipped, he shows INI 13 (correct).
With his armor unequipped, he shows INI 11 (incorrect).

My char should have calculated INI of 13.5 -> rounded up to 14.
This is modified by -1 encumbrance from his armor (+3 encumbrance armor / -2 encumbrance Belastungsgewöhnung 2)

I exported my char and attached it. What is kaputt? :)

EDIT: GS does the same thing - when I unequipp, the max GS goes from 5 down to 3.

**Comment by Plushtoast** [comment]
The Pantherrüsung has a weight of 23. If you don't equip it, you get an additional encumbrance of 3 which is not modified by the Belastungsgewöhnung.
See your carrying capacity in the inventory.
The weight of equipped armor does not count towards the carrying capacity limit

**Comment by mckee14** [comment]
OMG, sometimes its so simple... You wouldnt believe how long i thought
about that.

Well, i'm in my shaming corner.

Thanks for the clarification.

Plushtoast ***@***.***> schrieb am So., 11. Apr. 2021, 16:59:
