### ISSUE TITLE
Item "Begabung ()" aus der ItemSubclass advantage (Vorteil) ist unzureichend implementiert, neesAdaption() gibt nicht alle Fertigkeiten zur Auswahl

### ISSUE THREAD

**Issue by kaspagious** [Plushtoast/dsa5-foundryVTT#275]
Der Fehler tritt auf bei der Selektion des Vorteils "Begabung ()". Mit der momentanen Implementierung wird die Zuweisung abgefangen mit der Funktion needsAdoption(actor, item, typeClass) aus "modules\system\advantage-rules-dsa5.js". Die Funktion wird auch erfolgreich ausgeführt und gibt ein Dialog Fenster zurück. 
In diesem Dialogfenster kann ein Talent ausgewählt werden und der Begabung zugewiesen werden. 

Hier liegt jedoch das Problem. 
Laut Regelwerk wird dem Vorteil Begabung eine "Fertigkeit" zugewiesen. .
Diese Fertigkeiten sind eine abstrakte Klasse, welche alle 3W20 Proben inkludiert. 
Bei den Talenten handelt es sich um eine der Unterklassen welche die Fertigkeiten implementiert. Jedoch gibt es weitere. So sollte es möglich sein, wie im Beschreibungstext vom Vorteil angegeben, auch Zauber, Liturgien und Rituale auszuwählen. 
Das ist momentan jedoch nicht möglich und kann von der Seite des Nutzers aus nicht behoben werden und die Mechanik der Begabung ist dadurch stark eingeschränkt.

**Comment by kaspagious** [comment]
Habe den Vorteil nochmal in der Version 1.3.2. getestet und der Fehler besteht weiterhin. 
Zauber können nicht als Fertigkeit ausgewählt werden.

**Comment by Plushtoast** [comment]
Ah sorry, da muss das core modul erst noch einen Patch bekommen für das Dialog window.

Es müsste aber gehen, wenn du nach dem Hinzufügen den Namen der Fähigkeit manuell zum Namen des Zaubers änderst:
Begabung (Armatrutz)
