### ISSUE TITLE
Abspeichern manueller Effekte

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#278]
Es wäre toll, wenn erstellte manuelle Effekte abspeicherbar sind, damit man sie nicht bei jedem Token neu anlegen muss

**Comment by Nyhles** [comment]
Alternativ ist es ja möglich die Zustände auch über ein Macro anzulegen oder?

Da müsste man nur wissen was genau da alles gesetzt werden muss.
Meinem Verständnis nach wird das als effect eingetragen in den Actordata

**Comment by Plushtoast** [comment]
`const actor = game.actors.getName("Delgado Rochas");
console.log(actor);
actor.addCondition({
    label: "Zustandsname",
    icon: "icons/svg/aura.svg",
    origin: actor.uuid,
    changes: [
        { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 1 },
        { key: "data.status.speed.gearmodifier", mode: 2, value: -1 }
    ],

    flags: {
        dsa5: {
            value: null,
            editable: true,
            customizable: true,
            description: "Beschreibung des Effekts",
            custom: true
        }
    },
    id: `${Math.random()}`
});`

**Comment by Plushtoast** [comment]
Das kommt aber mit den folgenden Updates auf eine einfachere Art und Weise.

**Comment by Nyhles** [comment]
Besten Dank, dann werde ich das übergangsweise so nutzen :)

**Comment by Nyhles** [comment]
Ich probiere auch gerade ein wenig herum, du hast mir schon sehr geholfen.
Lässt sich so ähnlich auch ein schon bestehender Status entfernen, z.B. Betäubung?

Ist die Art wie die Effekte implementiert sind so ähnlich wie in anderen System?
Damit ich ggf. mal im entsprechenden Discord nachfragen kann, ohne dass es zu DSA spezifisch ist.

Aktuell versuche ich ein Makro zu erstellen, das direkt die Duration mit übergibt.
Klappt leider noch nicht so recht, es wird zwar eine Startzeit erzeugt, aber keine Dauer wie gewünscht.

Lässt sich sicher auch eleganter lösen:
```
main ()

async function main(){
  //is token selected
  if(canvas.tokens.controlled.length != 1){
    ui.notifications.error("Wähle dein Token aus.");
    return;  
  }

  let actor = canvas.tokens.controlled[0].actor
  
  let wieselflink = `<option value=${1} selected>1</option><option value=${2}>2</option><option value=${3}>3</option><option value=${4}>4</option><option value=${5}>5</option><option value=${6}>6</option>`;

  let dialogTemplate = `
  <div style="display:flex; flex-direction: column">
    <div  style="flex:1">QS:<select id="wieselflink_qs" style="float:right">${wieselflink}</select></div>
    </div>
  `

  new Dialog({
    title:"Wieselflink",
    content: dialogTemplate,
    buttons: {
      Wieselflink: {
        label: "Wiesel!",
        callback: (html) => {
          let wieselflink_qs = Number(html.find("#wieselflink_qs")[0].value);

          let chatTemplate = ""
          
          //add condition
          if (wieselflink_qs == 1){
            chatTemplate += `<p>Für 4.5 Minuten wieselflink.</p>`
            chatTemplate += `<p>+1 GE</p>`
            actor.addCondition({
              label: "Wieselflink QS 1",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                  { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 1 },
                  { key: "data.rangeStats.damage", mode: 2, value: 1 }
              ],
              duration: {
                seconds: 10
              },
              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          } else if (wieselflink_qs == 2){
            chatTemplate += `<p>Für 9 Minuten wieselflink.</p>`
            chatTemplate += `<p>+1 GE, +1 GS</p>`
            actor.addCondition({
              label: "Wieselflink QS 2",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                  { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 1 },
                  { key: "data.rangeStats.damage", mode: 2, value: 1 },
                  { key: "data.status.speed.gearmodifier", mode: 2, value: 1 }
              ],
          
              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          } else if (wieselflink_qs == 3){
            chatTemplate += `<p>Für 13.5 Minuten wieselflink.</p>`
            chatTemplate += `<p>+2 GE, +1 GS</p>`
            actor.addCondition({
              label: "Wieselflink QS 3",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 2 },
                { key: "data.rangeStats.damage", mode: 2, value: 2 },
                { key: "data.status.speed.gearmodifier", mode: 2, value: 1 }
              ],
          
              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          } else if (wieselflink_qs == 4){
            chatTemplate += `<p>Für 18 Minuten wieselflink.</p>`
            chatTemplate += `<p>+2 GE, +1 GS, +1 AW</p>`
            actor.addCondition({
              label: "Wieselflink QS 4",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 2 },
                { key: "data.rangeStats.damage", mode: 2, value: 2 },
                { key: "data.status.speed.gearmodifier", mode: 2, value: 1 },
                { key: "data.status.dodge.gearmodifier", mode: 2, value: 1 }
              ],
          
              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          } else if (wieselflink_qs == 5){
            chatTemplate += `<p>Für 22.5 Minuten wieselflink.</p>`
            chatTemplate += `<p>+3 GE, +1 GS, +1 AW</p>`
            actor.addCondition({
              label: "Wieselflink QS 5",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 3 },
                { key: "data.rangeStats.damage", mode: 2, value: 3 },
                { key: "data.status.speed.gearmodifier", mode: 2, value: 1 },
                { key: "data.status.dodge.gearmodifier", mode: 2, value: 1 }
              ],

              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          } else if (wieselflink_qs == 6){
            chatTemplate += `<p>Für 27 Minuten wieselflink.</p>`
            chatTemplate += `<p>+3 GE, +2 GS, +1 AW</p>`
            actor.addCondition({
              label: "Wieselflink QS 6",
              icon: "icons/svg/aura.svg",
              origin: actor.uuid,
              changes: [
                { key: "data.characteristics.ge.gearmodifier", mode: 2, value: 3 },
                { key: "data.rangeStats.damage", mode: 2, value: 3 },
                { key: "data.status.speed.gearmodifier", mode: 2, value: 2 },
                { key: "data.status.dodge.gearmodifier", mode: 2, value: 1 }
              ],
          
              flags: {
                  dsa5: {
                      value: null,
                      editable: true,
                      customizable: true,
                      description: "Beschreibung des Effekts",
                      custom: true
                  }
              },
              id: `${Math.random()}`
            });
          }
          
          ChatMessage.create({
            speaker: {
              alias: actor.data.token.name
            },
            content: chatTemplate,
          })
        }
      },
      Abbruch: {
        label: "Abbruch"
      }
    }
  }).render(true)
}
```

**Comment by Plushtoast** [comment]
würde das vlt so macheb: 

<pre>
main()

async function main() {
    //is token selected
    if (canvas.tokens.controlled.length != 1) {
        ui.notifications.error("Wähle dein Token aus.");
        return;
    }

    let actor = canvas.tokens.controlled[0].actor

    let wieselflink = [1, 2, 3, 4, 5, 6].map(x => `<option value=${x}>${x}</option>`);

    let dialogTemplate = `
  <div style="display:flex; flex-direction: column">
    <div  style="flex:1">QS:<select id="wieselflink_qs" style="float:right">${wieselflink}</select></div>
    </div>
  `

    new Dialog({
        title: "Wieselflink",
        content: dialogTemplate,
        buttons: {
            Wieselflink: {
                label: "Wiesel!",
                callback: (html) => {
                    const wieselflink_qs = Number(html.find("#wieselflink_qs").val());
                    const duration = 270 * wieselflink_qs;
                    let chatTemplate = `<p>Für ${(duration / 60).toFixed(1)} Minuten wieselflink.</p>`;
                    const geAndDamage = Math.round(wieselflink_qs / 2);
                    const speed = [0, 1, 1, 1, 1, 2][wieselflink_qs - 1];
                    const dodge = wieselflink_qs > 3 ? 1 : 0;
                    let modifiers = [`+${geAndDamage} GE`]
                    if (speed > 0) modifiers.push(`+${speed} GS`)
                    if (dodge > 0) modifiers.push(`+${dodge} AW`)
                    chatTemplate += `<p>${modifiers.join(", ")}</p>`
                    let condition = {
                            label: `Wieselflink QS ${wieselflink_qs}`,
                            icon: "icons/svg/aura.svg",
                            origin: actor.uuid,
                            changes: [
                                { key: "data.characteristics.ge.gearmodifier", mode: 2, value: geAndDamage },
                                { key: "data.rangeStats.damage", mode: 2, value: geAndDamage },
                                { key: "data.status.speed.gearmodifier", mode: 2, value: speed },
                                { key: "data.status.dodge.gearmodifier", mode: 2, value: dodge }
                            ],
                            duration: {
                                seconds: duration,
                                startTime: game.time.worldTime
                            },
                            flags: {
                                dsa5: {
                                    value: null,
                                    editable: true,
                                    customizable: true,
                                    description: "Beschreibung des Effekts",
                                    custom: true
                                }
                            },
                            id: `${Math.random()}`
                        }
                        //add condition

                    actor.addCondition(condition);
                    ChatMessage.create({
                        speaker: {
                            alias: actor.data.token.name
                        },
                        content: chatTemplate,
                    })
                }
            },
            Abbruch: {
                label: "Abbruch"
            }
        }
    }).render(true)
}
</pre>

**Comment by mckee14** [comment]
Ohhhh... ich kann zu wenig coden, um sowas selber anzulegen. Aber es reicht, um zu sehen, wohin das geht. Freude herrscht :).
Ich kann nicht genug loben, wie dieses Projekt betreut wird.

Für Laien wäre es sicher toll, wenn man eigene Effekte in einem Zauber(/Liturgie/Amulett/...) hinterlegen kann, welcher dann beim Wirken auf die Targets angewendet wird.

**Comment by Plushtoast** [comment]
Das ist der Plan.

**Comment by Nyhles** [comment]
Vielen dank.

Leider klappt es mit der Zuweisung der Dauer eines Effekts immer noch nicht.
Da muss ich noch weiter rumprobieren.

**Comment by Plushtoast** [comment]
Hab da leider einen Fehler eingebaut, dass es die duration nicht übernimmt.
Entweder auf Patch warten oder das File ersetzen: 
https://github.com/Plushtoast/dsa5-foundryVTT/blob/master/modules/hooks/scene.js

**Comment by Nyhles** [comment]
Wunderbar damit klappt alles wie gewünscht

**Comment by Plushtoast** [comment]
Effekte werden gemäß Foundry Intentionen auch in Zukunft an Items gebunden sein.
