### ISSUE TITLE
Drag&Drop der Spezies auf Charakterbogen nicht möglich

### ISSUE THREAD

**Issue by KaiderWeise** [Plushtoast/dsa5-foundryVTT#28]
Während ich alles per Drag&Drop auf den Charakterbogen ziehen kann (eigens erstellte Waffen, Vor- und Nachteile, Sonderfertigkeiten) kann ich jedoch keine Spezies auf den Charakterbogen ziehen, weder die vier mitgelieferten noch eine eigen erstellte Spezies. Es passiert nichts. Charaktererschaffung wie im Wiki aufgeführt ist nicht möglich.
Ich habe dies sowohl ohne ausgewählte  Module als auch mit sowie auf Englisch und auf Deutsch versucht. Es geschieht leider nichts. Auch wenn ich mich mit einem Browser (Chrome und Firefox wurden getestet) einklinke, gelingt dies nicht. 
Ich weiß leider, was ich noch beitragen kann, um den Fehler nachzuvollziehen...Aber lasst es mich wissen!
![dsa5test](https://user-images.githubusercontent.com/78543670/106895902-1d520c80-66f1-11eb-9719-4447f42b998a.PNG)

**Comment by KaiderWeise** [comment]
Liegt am deutschen Foundry. Soll wohl bald auch für Deutsch möglich sein.

**Comment by Plushtoast** [comment]
Mit dem letzten Patch sollte das behoben sein.
Du kannst das Modul für die deutsche Foundry Übersetzung nun verwenden.

**Comment by Alfa0815** [comment]
Ich habe leider, exakt das selbe Problem. Hab es nun sowohl auf Englisch als auch auf Deutsch versucht. Alles mögliche lässt sich auf den Charakter ziehen, nur bei der Spezies passiert leider nichts.
(Habe heute Foundry frisch installiert und verwende das DSA 5 Core Rules Modul.)

Edit: Fehler wurde am Tag darauf mit einem Patch behoben, danke. :)
