### ISSUE TITLE
Add Almanach creatures to Bestiarium 1

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#282]

**Comment by faddoMA** [comment]
Ok, I guess it was me that brought up this issue on FB. Thanks for taking it up.

**Comment by Albinosheep** [comment]
Danke, dass ihr die Kreaturen aus dem Almanach nachreicht. :-)
Es stellt sich dann trotzdem die Frage, wie man an die restlichen Inhalte des Almanach rankommt. 
Wäre es nicht sinniger, den kompletten Almanach-Band dem Regelwerk beizulegen? 
Mario Truant meinte seinerzeit, dass diese beiden Bände als Einstiegsbände sowieso zusammengehören würden und man es rückblickend wohl anders gestalten würde. Die beiden sind also sehr eng verzahnt.

Das fände ich mal sehr Fan-freundlich und einen guten und niedrigschwelligen Einstieg in die Welt des DSA-VTT. :-)
