### ISSUE TITLE
Item Verband - falsches Gewicht

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#287]
Wie bei der Kerze ist auch beim Verdand das Gewicht falsch.
Richtig wäre hier ebenfalls 0,05 pro Verband und nicht 0,5.

**Comment by tomsaath** [comment]
Es ist sogar ein Gewicht von 0,005 richtig damit man bei 10 Stück auf ein Gewicht von 0,5 kommt

**Comment by Gunthgard** [comment]
Das kommt darauf an was Du nutzt.
Meinst Du den Verband aus dem GRW S.364, stimmt Deine Meldung ... der mit der Bemerkung "core" müsste geändert werden, so wie Du es beschrieben hast.
Der aus der Rüstkammer hat korrekt ein Gewicht von 0.5, da damit das Verbandszeug gemeint ist und nicht der klassische Verband.

**Comment by Plushtoast** [comment]
Würde allerdings vermuten, dass hier in beiden Büchern das gleiche gemeint ist...
