### ISSUE TITLE
Fehlende +/- Funktion bei den Eigenschaften (Charaktererstellung)

### ISSUE THREAD

**Issue by Zettgeschehen** [Plushtoast/dsa5-foundryVTT#290]
Hej! 

Seid dem letzten Update fehlen bei mir, die +/- Zeichen neben den Eigenschaften (Actor Sheet). Ist das ein allgemeiner Bug oder ist da bei mir etwas krumm?

<img width="545" alt="Screenshot 2021-04-16 103412" src="https://user-images.githubusercontent.com/82644012/114996665-551ec280-9e9f-11eb-9996-f535ae780f0b.png">

**Comment by Plushtoast** [comment]
Duplicate of #284

**Comment by Zettgeschehen** [comment]
Vielen Dank und an dieser Stelle einfach mal ein großes Lob! Ihr macht einen fantastischen Job und es macht unglaublichen Spaß mit Eurem Modul!
