### ISSUE TITLE
Zaubererweiterung - wie?

### ISSUE THREAD

**Issue by faddoMA** [Plushtoast/dsa5-foundryVTT#291]
I cannot find a way to add "Zaubererweiterung" to my spells. At the spell level tab "Erweiterungen" ist says "noch nichts freigeschalten", however, there's no special magical ability "Zaubererweiterung" - is that feature already implemented? If yes, documentation on how to add a "Zaubererweiterung" at the "Erweiterungen" tab might be handy.

**Comment by Plushtoast** [comment]
Go the the itemsfolder and create a new extension. Make sure the spell name is spelled correctly. Then drag it to your character sheet.

**Comment by faddoMA** [comment]
Got it, Thank you!
