### ISSUE TITLE
Scenes Package

### ISSUE THREAD

**Issue by faddoMA** [Plushtoast/dsa5-foundryVTT#292]
As of now, only the Introductory Scenario scene is available as a DSA specific map. I did scan and import some scenes from e.g. "Hexe vom Schattenwasser", however, I had to do some crude photoshop work to delete room names, secret passages etc.

I'd happily pay for a package with DSA VTT scenes, maybe from the Dungeons GM screen or other non-adventure related sources.

**Comment by Plushtoast** [comment]
We are working on that.
