### ISSUE TITLE
UI Inkompatibilität mit Vance's sidebar resizer

### ISSUE THREAD

**Issue by elkowar** [Plushtoast/dsa5-foundryVTT#300]
**Describe the bug**
[Vance's sidebar resizer](https://github.com/VanceCole/vance-sidebar-resizer) streckt das Bild der sidebar einfach in die breite. Die aktuell genutzten Assets laufen so sehr schnell in einen Zustand über, in dem es nicht mehr schön anzusehen ist, und Text teilweise sehr unlesbar ist.

**Expected behavior**
Es sollte eine Möglichkeit geben, das UI so einzurichten dass dieses gemeinsam mit dem Sidebar resizer nutzbar ist - das könnte bedeuten, dass man den Skin für die Sidebar anpassbar macht bzw. auf defaults stellbar macht, oder eine andere Lösung findet die hier das strecken der Bilder weniger problematisch macht.

**Screenshots**
![image](https://user-images.githubusercontent.com/5300871/115086265-360a4a00-9f0c-11eb-9a9b-163198b8483b.png)

**Additional context**
-

**Comment by Plushtoast** [comment]
Der Titel lässt sich ausrichten.
Besser auflösende Texturen habe ich nicht.
Das Problem scheint aber auch so minimal, dass großer Aufwand nicht gerechtfertigt ist.
