### ISSUE TITLE
Automatisches Ausrüsten von Waffen und Rüstung wenn Combat-tab ausgewählt ist

### ISSUE THREAD

**Issue by elkowar** [Plushtoast/dsa5-foundryVTT#302]
**Is your feature request related to a problem? Please describe.**
Wenn ich NPCs oder SCs erstelle, und dort Waffen hinzufüge, erwarte ich für gewöhnlich, dass diese dort direkt als Waffen angezeigt werden. Das sie per default als nicht ausgerüstet eingestellt sind ist eher unintuitiv, und erfordert beim einrichten von NPCs unnötiges hin und her wechseln.

**Describe the solution you'd like**
Wenn der Combat-tab im Charactersheet ausgewählt ist, und man ein Ausrüstbares Item auf den Charactersheet zieht, sollte dieses automatisch Ausgerüstet werden. Ist man im Equipment-tab kann es hingegen als nicht-ausgerüstet bleiben.

**Additional Context**
Wenn dies aktzeptiert wird, würde ich gerne versuchen, dies selbst in einer PR beizutragen :D

**Comment by Plushtoast** [comment]
Sorry auf PR warten is net so mein Ding. Die Lösung ist aber ein Einzeiler.
Kannst ja mal versuchen.

**Comment by elkowar** [comment]
So geht's auch, hatte den move in `To Do` nicht gesehen :P Danke!
