### ISSUE TITLE
keine Kritischen Erfolge oder Patzer bei Passierschlägen

### ISSUE THREAD

**Issue by Realheimi** [Plushtoast/dsa5-foundryVTT#305]
Beim Passierschlag ist es noch möglich kritische Erfolge zu erzielen - dies sollte aber nicht gehen (GRW 237)
(Keine Verteidigung funktioniert aber schon!)

**Comment by scheribold** [comment]
"Es gibt keine Kritischen Erfolge oder Patzer bei Passierschlägen." GRW Seite 237.
