### ISSUE TITLE
Prägungen

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#307]
Hallo ist es möglich die Prägungen vorallem aus Magie 1 einzufügen, da diese nicht nur reiner fluff sind sondern einige Boni und Mali haben. 

https://ulisses-regelwiki.de/fdgfdgdfg.html

**Comment by Plushtoast** [comment]
Prägungen haben sehr spezielle Boni und Mail, die so im Moment sowieso nicht umsetzbar sind.
Bevor die Effekte nicht ausgebaut sind, werden wir uns das nicht anschauen.
