### ISSUE TITLE
SF Astrale Meditation, Regeltext nicht auf neusten Stand

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#310]
Hallo der Regeltext Sf Astrale Meditation ist nicht auf neusten Stand, der 4 Auflage von magie 1. Zudem ist da noch mehr was nicht aktuell ist.

https://ulisses-regelwiki.de/asmed.html

... die 24 Stunden Regel wurde erratiert.

**Comment by Murm3lt13r** [comment]
Updated
