### ISSUE TITLE
Chat-Log Einträge können Bibliothekseintrag öffen

### ISSUE THREAD

**Issue by UrielMhezzek** [Plushtoast/dsa5-foundryVTT#311]
Wenn eine Probe oder ein Zauber usw. gewürfelt wurde, wäre es schön, wenn man mit einem Klick auf den Namen direkt in die Bibliothek käme und sich dort die Regeln noch am durchlesen kann. Vor allen als Meister oder anderer Spieler relevant.

**Comment by Plushtoast** [comment]
Bei Zaubern wird doch schon die ganze Regel im Chat gepostet?

**Comment by mckee14** [comment]
Er meint nicht das post-to-chat eines Items, sondern die Probe. In der Chatausgabe stehen dann die Würfel, die QS usw.

Da möchte er (meinem Verständnis nach) gerne, dass die Bezeichnung verlinkt wird auf zugehörige Regeleinträge.

Meiner Meinung nach ist das ein Zweischneidiges Schwert. Automatischer Lookup kann falsche Einträge bringen, 1:1 Verlinkung bringt einen Haufen Arbeit mit geringen Mehrwert. Und dann sind ja die Einträge in den Charakteren allenfalls individualisiert mit Sonder-/Hausregeln, weshalb die post-to-chat Funktion besser geeignet ist.

**Comment by Plushtoast** [comment]
Mckee hat da meine Bedenken recht präzise formuliert.

**Comment by mckee14** [comment]
Tipp: Wenn gewünscht, einfach im Zauber/Item etc. einen link hinterlegen auf das DSA Wiki. Dann kann man die Erklärung und Wirkung mit der Chatbubble posten und user können für weitere Regelmechaniken auf den link klicken.

Macht auch mehr sinn, manchmal will man ja nicht die regel zu dem zauber per se, sondern zB Dämonen-Regeln, wenn sich ein Zauber auf Dämonen bezieht etc.
