### ISSUE TITLE
Zauberdauer bei Liturgien/Zeremonien/Ritualen

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#312]
Bei Liturgien/Zeremonien/Ritualen steht in den Details jeweils der Begriff Zauberdauer. Es wäre schön wenn hier zwischen Liturgiedauer, Zeremoniedauer und Ritualdauer unterschieden wird.

**Comment by Plushtoast** [comment]
Manchmal hat die Wahl der Bezeichnung etwas mit dem Layout zu tun. Wenn ich das so mache wie du vorschlägst, gäbe das z.b. im englischen ein Problem mit "Liturgical chant duration". Das ist ein sehr langes Label und führt wahrscheinlich zu einem Zeilenumbruch und damit zu Layoutproblemen und damit zu Arbeit. Dann ist das was klein erscheinen mag, gar nicht mal so schnell zu erledigen...

**Comment by mckee14** [comment]
Allenfalls umstellen auf ein neutrales Dauer / Duration? Dann ist es weniger präzise, aber niemals falsch :)

**Comment by Plushtoast** [comment]
Das wäre mir lieber, allerdings gibt es ja auch noch die Wirkungsdauer... Mir erschien Zauberdauer als bester Kompromiss zwischen langem Text und Klarheit, was gemeint ist.

**Comment by mckee14** [comment]
Dauer der Aktion, Dauer der Wirkung.
Duration of action, duration of effect.

Wenn das platz hat.

**Comment by Plushtoast** [comment]
Das würde gehen.

**Comment by tomsaath** [comment]
Ich finde die Vorschläge gut als Kompromiss absolut akzeptabel. Ich habe überhaupt nicht an die englische Version gedacht.
