### ISSUE TITLE
Implementierung von Routineproben

### ISSUE THREAD

**Issue by Algor0113** [Plushtoast/dsa5-foundryVTT#313]
**Is your feature request related to a problem? Please describe.**
Kein Problem, eher fehlendes Feature aus dem GRW

**Describe the solution you'd like**
In den Talenten eines Spielercharakters könnte eine weitere Spalte eingeführt werden für Routineproben (s. Regelwerk S. 184f). Ein "N/A" oder ähnliches, wenn keine Routineprobe möglich ist. Ansonsten ein +/0/-, das anzeigt, bei welchem Modifikator eine Routineprobe möglich ist.

**Describe alternatives you've considered**
Mir würde keine Alternative zur Lösung einfallen.

**Additional context**
Kein weiterer Kontext. Bis auf: Vielen Dank für die Arbeit, ihr macht das super :)

**Comment by mckee14** [comment]
Man könnte die Routineprobe auch im Popup-Fenster abfragen, basierend auf dem Fertigkeitswert und den eingestellten Modifikatoren. So werden zentral alle Einflussparameter geprüft und man kann die Regelmechanik inkl. Optionalregel ziemlich schlank einfügen.

**Comment by Algor0113** [comment]
Ja klar, das ginge auch. Das würde auch ins Auge fallen, wenn dann noch automatisch der Ausgangs-QS ausgegeben werden kann? (max QS / 2)

**Comment by RondraLion** [comment]
Oder einfach ein R hinter den Drei würfelfarben plazieren

**Comment by Algor0113** [comment]
> 
> 
> Oder einfach ein R hinter den Drei würfelfarben plazieren

Du meinst wie im Optolithen? Ja, das war ja die Idee, die ich anfangs hatte. Eine weitere Spalte rein und dann ggf. den zutreffenden Modifikator.

**Comment by RondraLion** [comment]
Aber das Pop up ist vielleicht besser. Sonst sieht das dann später so aus wie bei Roll20
