### ISSUE TITLE
Liturgie Magiesicht nicht steigerbar

### ISSUE THREAD

**Issue by annonym1313** [Plushtoast/dsa5-foundryVTT#314]
Die Liturgie bleibt bei 6 Punkten. Jeder höher notierte Wert wird auf 6 zurückgesetzt. Tritt definitiv bei NSCs auf

**Comment by Plushtoast** [comment]
Editierst du Kreaturen oder NPCs in einem Kompendium?

**Comment by annonym1313** [comment]
Ich erstelle NSCS in der Welt im Akteure Reiter

**Comment by Plushtoast** [comment]
Ist das System auf Version 1.3.2 und das Core Modul auf 1.1.0?

**Comment by Plushtoast** [comment]
Bitte F12 drücken, die Konsole aktivieren und schauen ob beim Ändern des Talentswerts eine Fehlermeldung auftaucht.

**Comment by annonym1313** [comment]
Okay, der Bug scheint sich erledigt zu haben. Beim öffnen des Charakterbogens stand der Wert plötzlich auf 14 (von mir gewünschter Wert) und ließ sich wieder ändern. Konsole gab auch keinerlei Fehlermeldung aus.
Danke übrigens für den schnellen Support :)
