### ISSUE TITLE
Condition "Berauscht"

### ISSUE THREAD

**Issue by TheFrazer** [Plushtoast/dsa5-foundryVTT#315]
I wanted to know if it is possible to add the condition "Berauscht"?

Each level of "Berauscht" adds a malus of 1 to the "Zechen"-Skill.

At level 4 the 4 levels of "Berauscht" get converted into 1 level of stupor (Betäubung). (should not be a priority - I would be happy with the two above only)

**Comment by Plushtoast** [comment]
We only add status from books on which we have worked on.
Otherwise we would jump eternally between the infinite content of dsa and never be able to finish anything.

So far I did not see this condition in the finished books.

**Comment by TheFrazer** [comment]
Its from the booklet that comes with the "Meisterschirm". It also goes by the name "Kneipen & Tavernen".

Since it's not a full publication like the other ones I hoped it would be possible to add it somewhere else. But I can see that that could create a lot of chaos with partialy adding parts of different sources.

I already tried looking and couldn't find anything. Is it possible to define conditions that modify skills? Or is there a rough ETA for that if thats planned for the future?

**Comment by Plushtoast** [comment]
In one of the next three patches probably.

**Comment by mckee14** [comment]
@TheFrazer Workaround ist sonst über Ausrüstung möglich. Für die 3 Stufen Berauscht je einen Gegenstand anlegen, als Effekt Zechen-1 / -2 / -3. Wenn man Stufen bekommt, einfach das entsprechende Item ausrüsten. Stufe 4 wird ja in 1 Betäubung umgewandelt, somit braucht man Stufe 4 nicht als Item.

![grafik](https://user-images.githubusercontent.com/62849695/115989541-33b88780-a5bf-11eb-8a31-44369d7dbcef.png)

**Comment by Plushtoast** [comment]
So kleinere Dinge die wir wahrscheinlich wie das Booklet könnt ihr auf jeden Fall gerne vorschlagen.
Die lohnen sich nicht als eigenes Modul, aber Ulisses wird vermutlich dem zustimmen das anderswo hinzuzufügen, wenns mehr oder weniger passt.

**Comment by TheFrazer** [comment]
@mckee14 Ne, Deutsch passt. Ich bin mir nur nie sicher, welche Sprache hier vorherschen soll und da es am Anfang Englisch war, bin ich einfach dabei geblieben :)

Die Idee Gefällt mir (zumindest als temporäre Lösung). Auf sowas bin ich bisher noch gar nicht gekommen. Danke!
