### ISSUE TITLE
SF im Token werden nicht mit dem Bogen Synchronisiert

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#316]
Hallo mir ist gerade aufgefallen wenn ich einen Kreaturen/Charakterbogen über Doppelklick über den Token öffne und dort dann eine SF hinterlege. In meinem Fall war es über Fähigkeit+, dann wurde das nicht auf den Bogen des Akteurs übertragen.

**Comment by Plushtoast** [comment]
Das ist so Absicht. Token von npcs und creatures sind immer Kopien. Im Akteurverzeichnis ist die source.  Änderungen an Tokens ändert nicht die source. Sonst hätten zb die Fünf orks auf der map den gleichen HP pool

**Comment by mckee14** [comment]
https://foundryvtt.com/article/tokens/ oder spezifisch
https://foundryvtt.com/article/tokens/#tokentypes

**Comment by RondraLion** [comment]
ah okay dann schließt das hier
