### ISSUE TITLE
Immunität gegen Schmerz

### ISSUE THREAD

**Issue by Ben528491** [Plushtoast/dsa5-foundryVTT#318]
Momentan finde ich keine Möglichkeit eine Eigenschaft "Immun gegen Schmerz" selbst zu bauen.

Deswegen funktionieren die ca. 5 Dämonen (und paar Untote) aus dem Bestiarium 1 nicht zu 100%

**Comment by CommanderAlex98** [comment]
Kannst du zeigen wie du es gelöst hast?

**Comment by Plushtoast** [comment]
Man muss ein Trait namens "Immun gegen Schmerzen" hinzufügen.
Ist im nächsten Patch. Ben hat die betaversion von dem Patch...
