### ISSUE TITLE
Attacks of a specific actor don't hit the selected target

### ISSUE THREAD

**Issue by m4nuel-github** [Plushtoast/dsa5-foundryVTT#319]
**Describe the bug**
One actor (player character) can't properly attack enemies. The attack is not applied to the selected target and the automated follow up steps like "reaction" and "apply damage" etc cannot be used. The target is also not lost after the attack, although this option is activated in the settings. Macros doent help either.
This happens only with one of the player characters, all the other actors are working fine.
There is an error in the console, when attacking with this specific character (see screenshot).

**To ### Reproduce**
1. Open character sheet
2. Select target
3. Click on attack roll dice
4. Attack is rolled (although not against the selected target and it's values) and the chat message "attack test" appears
5. The attack is not applied on the target and the usually following chat message "reaction" does not appear

**Expected behavior**
The attack has to be applied to the selected target. The values of the target (e.g. range) must be taken into account. The chat message with "reaction" has to appear. The target has to be lost after the attack (if the option is selected in the settings).

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/83171304/115996283-f8c64c00-a5de-11eb-8b47-3b261cf527df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Fireforx
 - Version: 88.0

**Smartphone (please complete the following information):**
 - 

**Additional context**

**Comment by Plushtoast** [comment]
If you don't finish opposed checks or attacks properly some stale data might remain and mess up future tests.
The tool can not see wether you decided to not finish a test or not unless you click the right buttons.

Make sure you've got the newest version installed 1.3.2.
Then delete the chat data and place the tokens again on the map.

**Comment by mckee14** [comment]
I found several similar behaviours already, too, and reckoned that it has to do with the players behaviour and wrong use of commands, buttons etc.

We just went along with it and rolled the needed tests separately.

But with 6 enemies and 5 players in a battle, it's almost guaranteed to happen, especially when you have people playing with (almost) no IT experience - they click left and right and all over the place, all the time.

Would it be hard to implement a "reset" function? just clearing all the possible stuck / wrong data, so you dont have to clear the chat and place new token? would make a GMs life a lot easier :)

**Comment by Plushtoast** [comment]
Most likely nobody would neither know about this function nor use it and the problem would remain the same.
And it's also rather tedious to catch every "all over the place" click.

Removing the latest attack messages is usually already sufficient. I never had to replace tokens myself.

**Comment by Plushtoast** [comment]
My players DDOSed our server last time with spell effect spam and it didnt restart for quite some time.
But I will not do anything about it.
Can't prevent every user error and also I won't.

**Comment by mckee14** [comment]
OK, so we just go along with chat clearing, should do the trick for most
cases.
Thx for the heads up

Plushtoast ***@***.***> schrieb am So., 25. Apr. 2021, 20:13:

**Comment by m4nuel-github** [comment]
I tested the following without any result:
- deleting the whole chat history
- deleting and addding the token of the actor
- switching to other maps
- all of this combined

I guess, something is wrong with the actors data and we'll have to recreate the character. I'll just hope, this won't happen again.

**Comment by Plushtoast** [comment]
Please export the character as json and attach it to this thread.

**Comment by mckee14** [comment]
Does it happen with all weapons?

Maybe renaming the sword, so you dont have any brackets in the name.

The script will likely go trough all the targeted chars and fetch their
stats. The parsing of the values may get thrown off rails when it finds
special characters used in programming (round and square brackets,
semicolon, commmas...) with unexpected values.

The name field should be relatively safe, but you never know, worth a try.

m4nuel-github ***@***.***> schrieb am Mo., 26. Apr. 2021,
10:28:

**Comment by m4nuel-github** [comment]
> 
> Does it happen with all weapons? Maybe renaming the sword, so you dont have any brackets in the name. The script will likely go trough all the targeted chars and fetch their stats. The parsing of the values may get thrown off rails when it finds special characters used in programming (round and square brackets, semicolon, commmas...) with unexpected values. The name field should be relatively safe, but you never know, worth a try.
.

Yes, it does. I even tested it with unarmed attacks.
I also suspect the name to be a problem. All player tokens show only the first name of the actor, to reduce text on the map. The full name is only shown on the actor sheet. And this specific character has "three" names (Abu ibn Kasim). But I lack the programming skills to analyze this problem properly.

**Comment by mckee14** [comment]
Thats not a problem, my friends char has about 6 Names :)

When you test its important to completely unequip items, or remove them
from character. The script doesnt care if you are not USING a weapon - when
you have it equipped, it goes trough it. For the defense, it must read all
items and create the selection for you.

But like mentioned before, please upload the JSON of the char.

m4nuel-github ***@***.***> schrieb am Mo., 26. Apr. 2021,
11:34:

**Comment by m4nuel-github** [comment]
> Please export the character as json and attach it to this thread.

Thanks, this got me on the right track and I solved the problem!
After exporting the actor (Abu ibn Kasim) I browsed through the file and stumbled upon the name of a different actor (Gerion), which seemed odd. So I compared this part of the file with an export of an actor that works fine and as it turns out there are several additional lines in the bugged actor (starting from line 221 in the json).
[fvtt-Actor-Abu_ibn_Kasim.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/6376173/fvtt-Actor-Abu_ibn_Kasim.txt)




Bugged actor:
![Character_bugged](https://user-images.githubusercontent.com/83171304/116065580-747bd380-a687-11eb-8ec3-d08eb1a811f5.png)

Working actor:
![Character_working](https://user-images.githubusercontent.com/83171304/116065596-78a7f100-a687-11eb-8fab-6b9f160b9e28.png)

After replacing and deleting these lines and importing the actor back into the game the problem is gone. I also discovered the problem within another actor, which we only didn't recognice because he has never rolled an attack so far :)

I still don't know the root of the problem. Perhaps I copied an actor to create the others which were bugged. This might be an explanation, but I can't remember if I did that.

Thank you guys for all the support!

**Comment by Plushtoast** [comment]
That's the opposing message data which doesn't get cleared if you dont finish the check.
You convinced me :) ... I am going to create an automatic fallback.

**Comment by m4nuel-github** [comment]
Ok, now it sems to be a virus and starts jumping to the other actors, the more I test it :) 
I can't reproduce 100% it yet, but you seem to be right. If you dont finish the check, the name of the opposed actor stays written in the actors file.

**Comment by Plushtoast** [comment]
Make sure you don't accidentally target multiple enemies at once.
You can right click on the token hud on the target icon to only select one target at a time.

I created an automatic fallback too for the next patch.

**Comment by mckee14** [comment]
Oh wow - what about real multiple target attacks? Sometimes it makes sense
to target several enemies, especially when it comes to spells and liturgies.

Should we go trough the different targets one by one manually in this case?
Sounds like you only intended single targets.

Thx for clarification :)

Plushtoast ***@***.***> schrieb am Mo., 26. Apr. 2021, 12:34:

**Comment by Plushtoast** [comment]
You can do multiple targets already but only the last one's attributes are taken into consideration (f.e. weapon length or soulpower) as it is only one roll dialog which is appearing.

Different modifiers for multiple target doesn't exist.

**Comment by mckee14** [comment]
Thank you for the quick reply!

So multiple weapon attacks are best handled one by one (which makes sense
anyways).

For spells and the like: is the last targeted enemy considered "last", or
does it sort targets within the script? Would be necessary to check against
the target with the highest value (of soulpower etc), so last selected =
last would be perfect.


Plushtoast ***@***.***> schrieb am Mo., 26. Apr. 2021, 12:52:
