### ISSUE TITLE
Anzeige "Spieler x gegen NPC y" komplett für Spieler verstecken

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#328]
Während eines Kampfes können die Spieler mit doppelt Rechtsklick einen gegnerischen Token auswählen. Zwar kann der Schadenswurf verborgen werden, jedoch sehen die Spieler bei einer Attacke, Verteidigung, Vergleichsprobe etc. "Spieler x gegen NPC y". Dadurch ist natürlich auch ein gewisses meta-gaming möglich, wenn man den Name des Gegners sieht. Die umständliche Lösung ist hier: Token gezielt umbenennen, was aber bei vielen Gegnern aufwendig sein kann

Anzeige "Spieler x gegen NPC y" soll durch Option in Einstellungen komplett verborgen werden, wenn gewünscht. Im Turn Tracker ist das ja schon möglich, indem man z. B. die Tokens vorher unsichtbar macht, sodass diese für die Spieler verborgen sind.

**Comment by mckee14** [comment]
Kann man die Würfe nicht verbergen, wenn man als SL die Chatausgabe umstellt?

Die Option zu haben wäre cool. Ganz allgemein, dass alle Chatausgaben auf SL-Only umgestellt werden können.

Zusatztipp: Das Modul "Token Mould" ermöglicht es, definierte Token automatisch umzubenennen, wenn man diese in die szene zieht. Ebenfalls kann man generelle settings für Tokens einstellen (zb. keine Namensanzeige bei Mouseover, keine LeP Anzeige, Sicht...), die dann immer angewendet werden.

Erspart ziemlich viel Klickerei und hilft, Ruck Zuck mehrere Token im Spiel zu haben.
