### ISSUE TITLE
NSC-Charakterbogen lässt sich nicht mehr öffnen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#331]
Ich habe einen NSC-Charaktersheet erstellt. Darin habe ich diverse Werte eingetragen. Ich habe dann eine Hellebarde hinzugefügt, umbenannt und mit anderen Werten versehen. Ich konnte die Waffe dann komischerweise nicht ausrüsten. Dann habe ich die Anzahl dieser neuen Waffe erhöht und wieder gesenkt. Leider gab es dann keine Reaktion mehr. Ich bin mir nicht mehr sicher, ob ich das Charakterblatt dann beendet habe, oder ob es abgestürzt ist.
Seitdem kann ich das Chrakterblatt des NSC nicht mehr öffnen (alles andere funktioniert einwandfrei). Ich kann sogar einen Token auf die Map ziehen - darüber komme ich leider auch nicht in sein Charakterblatt.
[Charaktersheet.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6397935/Charaktersheet.zip)

**Comment by Plushtoast** [comment]
[fvtt-Actor-Ruadh,_der_Rote_Hirsch.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6398018/fvtt-Actor-Ruadh._der_Rote_Hirsch.zip)


Die Waffe Pailos hatte als Schadenswürfel 2W+2 statt 2W6+2.
Der angehängte Charakter ist gefixt.

Im nächsten Patch wird dieser Fehler auch abgefangen.

**Comment by Albinosheep** [comment]
Vielen lieben Dank!
Gut, dass es einen doofen gibt, der es herausgefunden hat. ^^
