### ISSUE TITLE
Token - default-Tokeneinstellung für Namen und Energiebalken

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#332]
Beim Hinzufügen von SC, NSC oder Kreaturen aus der Bibliothek werden die Einstellungen am Token "Display Name" und "Display Bars" automatisch auf "Hovered by Owner" gesetzt. Ich schätze, dass genau mit dieser Einstellung aber die wenigsten Gruppen arbeiten werden.
Ich fände es einen Gewinn...
- wenn sie per defaullt auf "Hovered by Anyone" stehen würden oder
- wenn sie indiviuduell vom SL bei den Modul-Konfigurationen eingestellt werden könnten, was der Standard beim Hinzufügen aus der Bibliothek sein soll.

Ich würde mich freuen, wenn diese Verbesserung in ein kommendes Update mit reingepackt werden würde. :-)

**Comment by Plushtoast** [comment]
Ich glaub eher die wenigsten wollen, dass man die HP und sonstige Balken der NPC sehen kann.

**Comment by mckee14** [comment]
@Albinosheep Schau Dir mal das Modul "Token Mold" an. Da kannst Du einstellen, was für Standard-Settings auf einen Token angewendet werden, wenn er in die Szene gezogen wird (für alle Token, oder nur unlinked token). Bars, Namen, Sicht etc. alles einstellbar.

**Comment by Plushtoast** [comment]
Das wird in foundry 0.8 automatisch dabei sein. D.h. ich werde hier nichts ändern.
Ist aktuell noch in der Testphase aber kommt bestimmt.

**Comment by Albinosheep** [comment]
Vielen herzlichen Dank mckee14 für den Hinweis zu dem Modul und Plushtoast für deine Recherche! Das ist natürlich optimal. :-)
