### ISSUE TITLE
offenseMalus analog zum defenseMalus

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#334]
**Is your feature request related to a problem? Please describe.**
Manche Zauber/Effekte wie beispielsweise Favilludo verursachen einen Attackemalus beim Gegner.

**Describe the solution you'd like**
Es wäre schön, wenn analog zum defenseMalus auch ein attackMalus/offenseMalus integriert werden würde.

**Comment by Plushtoast** [comment]
Zauber werden anders behandelt wie Nahkampfangriffe.
