### ISSUE TITLE
Waffeneffekt - VM funktioniert nicht

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#336]
Bei Waffen wie Fechtwaffen und Kettenwaffen wird die Verteidigung des Gegner um -1 respektive -2 modifiziert.

Dies ließe sich mit dem neu eingeführten Verteidigungsmodifikator als Effekt (z.B. -2 VM) gut darstellen ohne das Kampffenster weiter mit neuen Auswahlmöglichkeiten zu überladen.

Leider ist es aktuell nicht möglich den VM effekt bei Waffen zu nutzen.

**Comment by Plushtoast** [comment]
Duplicate of #32

**Comment by Nyhles** [comment]
Da der positive Modifikator funktioniert, dachte ich es sei eine eigene Meldung wert.

**Comment by Plushtoast** [comment]
Ich hätte das jetzt auf die Kampftechnik draufgepackt.

**Comment by Nyhles** [comment]
Geht natürlich auch.
Wäre aber trotzdem gut wenn der Verteidigungsmodifikator funktioniert, damit man Waffen anlegen kann, die genau diesen Effekt nutzen

**Comment by Plushtoast** [comment]
Jetzt gibts demnächst übertragbare Effekte für Zauber. Danach kann man mal drüber nachdenken übertragbare Effekte für Waffen zu machen. Da wäre das dann ggf. auch eine Option (+ extra Schmerz oder sonst was)

**Comment by Nyhles** [comment]
Das wäre echt super, tolle Sache
