### ISSUE TITLE
Ammunition damage / effects

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#337]
You can already choose different ammunition types and use them.

It would be nice to allow damage modification and maybe even effects for it (so war arrows do +1TP etc.)

**Comment by Plushtoast** [comment]
That will be part of Armory 2 I guess.

**Comment by mckee14** [comment]
Lovely

Plushtoast ***@***.***> schrieb am Fr., 30. Apr. 2021, 14:45:
