### ISSUE TITLE
Compendiums missing after language change

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#339]
**Describe the bug**
When you change the language from DE to EN, several compendiums vanish.
When you change the language back to DE, they re-appear.

_(Can you make something kaputt when switching languages, or is that no problem and you just initialize the module again?)_

**Comment by Plushtoast** [comment]
You can not use mixed language compendiums.
Only compendiums supporting the current language will be shown.

Different languages are not compatible with each other and will break existing characters.

We won't support that.

**Comment by mckee14** [comment]
OK. I added a "important information" page to the de wiki and included that information. Important to avoid importing entries from a different language setting in this case.
