### ISSUE TITLE
Texteditor in Journal-Einträgen wird nicht geladen

### ISSUE THREAD

**Issue by spriggan02** [Plushtoast/dsa5-foundryVTT#341]
Der kleine Edit-Button bei Text-Journal Entries etc. ruft den Texteditor nicht auf. Bereits im Entry angelegter Text wird nicht mehr angezeigt
Vermutung: Texteditor UI kann nicht geladen werden

Browser Konsole zeigt folgende Fehlermeldung an:
http://[....IPv6]:30000/themes/silver/theme.min.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).

**Screenshots**
1: vor klick 
![image](https://user-images.githubusercontent.com/83521569/116798052-40236f80-aaec-11eb-9741-85074dad33e0.png)

2: nach klick

![image](https://user-images.githubusercontent.com/83521569/116798065-621cf200-aaec-11eb-91e0-9e8c24bc0876.png)

 
 - Device: Lenovo Thinkpad
 - OS: Windows 10
 - Reproduziert in
Chrome 90.0.4430.93
Edge  90.0.818.51
Firefox 87.0 & 88.0

aktivierte Module:
DSA5_core
Magie
Götterwirken
Pings
Tokenizer
Dice So Nice
T is for Target

**Comment by Plushtoast** [comment]
Das klingt eher nach einem Firewall oder Virenscanner Problem.
Versuchst du in einem Kompendium zu editieren?

**Comment by spriggan02** [comment]
Hast Recht! Das Problem tritt nicht auf, wenn ich direkt auf dem Server arbeite. Irgendwie kommt also das Modul nicht ganz zu den clients durch.

Es sind wirklich alle Stellen betroffen wo der Foundry Text Editor aufgerufen werden soll. Egal was man bearbeiten will.

Danke für die Antwort.
