### ISSUE TITLE
Fehlermeldung bei der Parade über den Reaktionsbutton

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#342]
**Describe the bug**
Ein Spieler wurde mittels Target-funktion von einem erfahrenen Maru-Kämpfer angegriffen. Als er mittels Reaktion parieren wollte, kam eine Fehlermeldung:
_"TypeError: Cannot read property 'combatskill' of undefined_
Einige Zeit später bei den Angriffen ging es wieder.

**To Reproduce**
Angriff mit Maru, Parade über Reaktionsbutton. SC hatte mehrere Waffen zur Auswahl. Ging sowohl für den SC als auch für den SL nicht. Es hatte davor immer geklappt. Der Spieler hatte einige Zeit zuvor mal einen Disconnect. Hängt das vielleicht zusammen?

**Screenshot**
![Bug](https://user-images.githubusercontent.com/41292141/116809008-59eca300-ab3c-11eb-88ca-a0eea3a0adc2.png)

**Desktop (please complete the following information):**
 - Windows 10
 - chrome
 - Foundry 0.79
 - Core 1.3.2

**Comment by mckee14** [comment]
Disconnects oder abgebrochene (Re)aktionen können dazu führen, dass noch Reste von alten Angriffsaktionen im Token und Chat vorhanden sind, siehe #319.

Es sollte sich beheben lassen, wenn der Chat gelöscht und ggf. der Token neu auf die Szene gezogen wird.

Ich hatte kürzlich das Phänomen, dass mein Charakter keine Gegner mehr angreifen konnte, auch wenn diese als Target ausgewählt waren, währen das mit allen anderen Charakteren noch funktioniert hatte. In der charakterdatei war auch "oppose": null eingetragen. Es liess sich nur fixen, indem ein anderer Char meinen Char erfolgreich angegriffen hat. Nachdem der code einmal diesen angriff einmal durchgerödelt hatte, gings wieder.

Also: Chat löschen, Token neu auf die Szene ziehen, Token einen Angriff abkriegen lassen. Wenns dann nicht geht, muss plushtoast ran :)

**Comment by m4nuel-github** [comment]
Wenn ein Actor keine Angriffe mehr gegen ein gewähltes Target ausführen kann, könnte das gleiche Phänomen (und der gleiche Workaround) wie [hier](https://github.com/Plushtoast/dsa5-foundryVTT/issues/319) vorliegen.
Der Bug ist wohl mit dem nächsten Patch gefixt.

**Comment by Plushtoast** [comment]
Wenn die combatskill fehlermeldung kommt, ist in deiner Waffe etwas falsches eingestellt. Vermutlich weil zuerst Englisch aktiviert gewesen ist.
Ändere die Kampftechnik der Waffe auf irgendwas und wieder zurück, dann sollte es funktionieren.

**Comment by Albinosheep** [comment]
OK danke, eigentlich hatten wir nichts an der Waffe verändert und später ging es dann auch von alleine wieder.

**Comment by Plushtoast** [comment]
Wahrscheinlich wurde in der Zwischenzeit der Eintrag der Waffe geöffnet und wieder geschlossen. Dabei wird der Combatskill auch von Englisch auf Deutsch gewechselt.
