### ISSUE TITLE
Finte I wird nicht korrekt bei der Verteidigung verrechnet

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#344]
**Describe the bug**
Wir haben die SF Finte I genutzt. Leider wurde der Malus auf die Parade nicht richtig verrechnet.

**To Reproduce**
Angriff eines Tokens mit Target und Finte I. Dann Parade über die Reaktion. Für die Finte wird ein Malus von 0 angezeigt.
Wie es sich mit Finte II oder III verhält, haben wir nicht getestet.

**Expected behavior**
Ein Abzug von -2 für Finte I, -4 für Finte II und -6 für Finte III.

**Screenshots**
![Finte-Bug](https://user-images.githubusercontent.com/41292141/116810857-5bbb6400-ab46-11eb-911d-f248b1d324e1.png)

**Comment by mckee14** [comment]
Füge den Verteidigungsmalus manuell hinzu, in der SF Finte im Charaktersheet:

![grafik](https://user-images.githubusercontent.com/62849695/116812141-7d6c1980-ab4d-11eb-825c-1f5c0ce748bb.png)
Pro Stufe wird dann die Finte um 1 erschwert, die Verteidigung um 2. 
Wird bei einem Update sicher einmal direkt in der Bibliothek so eingetragen sein, aktuell einfach von Hand anpassen.

**Comment by Albinosheep** [comment]
OK danke, das hilft natürlich schon mal als vorläufiger Workaround für uns! :-)

**Comment by Plushtoast** [comment]
Hm, Werte mit Modifikator von 0 sollten auf jeden Fall nicht angezeigt werden.

Leider werden Fähigkeiten nicht rückwirkend aktualisiert, wenn sie im Kompendium ein Update erhalten. Den Verteidigungsmalus gibt es erst seit kurzem. Charakter vor der Einführung haben das normalerweise nicht.

Ein Update für die Effekte in fertigen Charakteren ist noch geplant, wird aber noch dauern.
Das ist leider auch etwas problematisch, weil man nicht sagen kann, ob die User manuell etwas angepasst haben und das dann evtl. gelöscht werden würde, bei so einem Update.

**Comment by mckee14** [comment]
@Plushtoast Ohne Eintrag zum Verteidigungsmodifikator wird bei der Verteidigung automatisch 0 als Wert angezeigt, im Gegensatz zu anderen Wirkungen.

**Comment by Plushtoast** [comment]
Ja das soll so nicht sein, das kommt weg.

**Comment by Albinosheep** [comment]
Ich glaube es wäre schon viel geholfen, es für die Zukunft in der Bibliothek zu ergänzen. 
Kann man es auch bei den NSC/Kreaturen/Archetypen in der Bibliothek anpassen?

Ja, es bei den aktiven SC, NSC und Kreaturen zu ändern ist natürlich schwierig. Vielleicht einfach in die Patchnotes den hinweis aufnehmen, dass man es neu hinzufügen soll, wenn man von dem Bug betroffen ist?  :-)

**Comment by mckee14** [comment]
Du KANNST den Eintrag in der Bibliothek ändern. Es wird nur nicht empfohlen in der Regel.
Sobald der Autor das Modul aktualisiert, wird alles in den Kompendien gelöscht und neu heruntergeladen. Dabei gehen alle gemachten Änderungen verloren.

In einem Fall wie diesem hier, kannst Du aber:
 - den Schreibschutz auf dem entsprechenden Kompendium entfernen, via Rechtsklick auf das Kompendium (Toggle Edit-Lock)
 - den Eintrag im Kompendium ändern
 - den Schreibschutz wieder setzen

So hast Du dann die Finte korrekt hinterlegt, bis das nächste Update eingespielt wird.

**Comment by Albinosheep** [comment]
Da haben wir uns jetzt glaube ich falsch verstanden. Das war mir bewusst. Ich meinte jetzt seitens Plushtoast mittels update. :-D
Aber danke für deine Klarstellung mckee14. :-)
