### ISSUE TITLE
Trennung der Sprachen und Schriften im Charakterbogen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#345]
Ich fände es übersichtlicher, wenn Sprachen und Schriften im Charakterbogen getrennt aufgelistet wären (wie im eigentlichen Heldenbogen ja auch).
Möglicherweise könnte man in der Darstellung dann auch auf den Zusatz "Sprachen" bzw. "Schriften" verzichten, der das ganze doch etwas aufbläht (bei Kampf-SF steht das auch nicht vor jeder-SF: Kampfsonderfertigkeit (Wuchtschlag)).

<img width="208" alt="Sprachen-Schriften" src="https://user-images.githubusercontent.com/41292141/116811035-6296a680-ab47-11eb-965b-a7619cb6ef88.PNG">

<img width="210" alt="Sprachen-Schriften PDF" src="https://user-images.githubusercontent.com/41292141/116811049-80640b80-ab47-11eb-8152-81a9bc6c61d5.PNG">

**Comment by Plushtoast** [comment]
Der Name dient bereits der Identifizierung der Fähigkeiten z.b. in dem Modul Polyglot. Das nachträglich noch zu Ändern führt zu anderen Problemen, die die Änderung dann wahrscheinlich nicht mehr rechtfertigen.
Außerdem benutzen wahrscheinlich nur sehr wenige Spieler die Sprachen und Schriften wirklich aktiv. Ich habe das noch in keiner Gruppe in keinem Spiel jemals benutzt.
Wahrscheinlich wirds hier keine Änderung geben :)

**Comment by Albinosheep** [comment]
OK danke für dein Feedback, das verstehe ich.
Unabhängig davon fände ich trotzdem eine Trennung in Sprachen und Schriften sinnvoll, da sie ja trotzdem den Überblick verbessert. :-)
Ich benutzte das jetzt auch nur, weil ich Polyglot nutze. :-D
