### ISSUE TITLE
Trennung von Zauber- und Liturgieerweiterungen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#348]
In der Bibliothek sind Zauber/Liturgieerweiterungen unter Magie/Religion zusammengefasst. 
Ich fände es besser und übersichtlicher, wenn man die beiden Sachen trennt (genauso wie ansonsten karmales und astrales wirken ja getrennt sind).

**Comment by Plushtoast** [comment]
Duplicate of #209
