### ISSUE TITLE
Trennung der verschiedenen SF in der Bibliothek in einzelne Grupen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#349]
In der Bibliothek werden unter den Sonderfertigkeiten wirklich alle SF angezeigt.
Ich fände es übersichtlicher, wenn man Kampf, allgemein, Schicksalspunkt-SFs, Sprachen & Schriften sowie magische und karmale SF aufteilen könnte.
Bei magischen und karmalen SF kann man sich überlegen, sie in Magie/Religion zu packen.

**Comment by Plushtoast** [comment]
Duplicate of #209
