### ISSUE TITLE
Status Effekt hervorrheben und verlinken

### ISSUE THREAD

**Issue by LaKai-dot** [Plushtoast/dsa5-foundryVTT#351]
Hallo, ich finde eure Module großartig, vielen Dank dafür. Ich habe aber eine Frage zu Abenteuren die ich selbst erstellen will.
Wenn in euren Texten, z.B. in der Zauberbeshcreibung, ein Status Effekt genannt wird, ist dieser mit einer Statusbeschreibung verlinkt, die im Chat Fenster gepostet wird. Ich habe nirgendwo einen Link o.ä. gefunden? Wie wird das gemacht?

Danke für eine Antwort,
Kai

**Comment by Plushtoast** [comment]
Musst einfach nur "Zustand Schmerz" etc. schreiben und es wird automatisch ersetzt.

**Comment by LaKai-dot** [comment]
So einfach kann das Leben sein. Vielen Dank, Top!
