### ISSUE TITLE
Ceoladir ASP Berechnung nicht korrekt

### ISSUE THREAD

**Issue by AdeptusAngbar** [Plushtoast/dsa5-foundryVTT#352]
*Beim Ceoladir wird zur Berechnung des ASP Wertes nur die 1/2 Leiteigenschaft als Bonus gerechnet.Siehe AM1 Seite 41

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Plushtoast** [comment]
Du musst bei solchen Professionen das leider manuell angeben:

![grafik](https://user-images.githubusercontent.com/44941845/116933169-78998980-ac63-11eb-8b24-4bbbea49f20c.png)

Leiteigenschaft Multiplikator.

Vlt geht's irgendwann mal noch automatisch.

**Comment by AdeptusAngbar** [comment]
Wow, danke für die schnelle Antwort. Könntet Ihr das vielleicht in der Heldenerschaffungswiki aufnehmen? Vielleicht habe ich es aber auch einfach übersehen ;-)

**Comment by mckee14** [comment]
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/Spellcaster--and--Blessed-One-Creation

Steht schon drin ;)

AdeptusAngbar ***@***.***> schrieb am Di., 4. Mai 2021, 08:56:
