### ISSUE TITLE
Belastungsgewöhnung steigern

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#355]
Hallo,

ein Spieler von mir spielt einen Kor-Geweihten. Diese bringen die SF Belastungsgewöhnung mit. Nun wollte er die auf Stufe 2 steigern, aber das geht nicht. Weder nochmals auf den Charakter ziehen, noch direkt die SF im Bogen per Hand ändern funktioniert. Löschen kann ich sie auch nicht.

**Comment by DerGreif** [comment]
Unter Details ganz unten sollte Stufe stehen mit + und - daneben. Da drauf klicken sollte die Stufe erhöhen bzw. senken. Hast du das mal probiert? Bei mir funktioniert es.

**Comment by Danii0206** [comment]
Ja hab ich probiert. Nein, geht nicht. Da passiert nichts.

**Comment by Plushtoast** [comment]
Klingt eher nach nem Serverdisconnect oder so.

Charakter an den Thread anhängen.

**Comment by Danii0206** [comment]
Nach F5 beim Spieler geht es jetzt. Spannend find ich, dass auch ich als GM das nicht ändern konnte. Danke für die schnelle Hilfe!
