### ISSUE TITLE
QS wird trotz Patzer angezeigt

### ISSUE THREAD

**Issue by TheFrazer** [Plushtoast/dsa5-foundryVTT#356]
Bei uns hat heute einer einen Patzer gewürfelt und es wurde trotzdem eine QS von 1 angezeigt:
![grafik](https://user-images.githubusercontent.com/16038255/117225345-6c076380-ae12-11eb-8ed0-253b6101a016.png)

Beim Testen hab ichs reproduzieren können: Wenn man nach der Probe immer noch positive FP hat, wird eine QS angezeigt. Als Beispiel hier mit Eigenschaften 13/13/14 mit einem FW von 19 kommt folgendes raus:
![grafik](https://user-images.githubusercontent.com/16038255/117225590-f780f480-ae12-11eb-8b3d-84fdaab0f229.png)

Die Qualitätsstufe sollte in beiden Fällen nicht angezeigt werden. Also genau so, wie bei einem normalen Patzer.

**Comment by Plushtoast** [comment]
Ich seh hier kein Problem. Aber meinetwegen...

**Comment by mckee14** [comment]
Die Antwort eines Entwicklers, wenn die issues die 100er Marke übersteigen
hehe...

Solange sichtbar ist, dass es ein Patzer ist, finde ich es auch OK. Dinge
ausblenden ist auch immer so ne sache - mehr infos sind besser IMHO. Wenn
der spieler nun einen Talisman hat, der einmalig einen patzer verhindert?
Dann hilft die QS angabe bereits wieder...

Plushtoast ***@***.***> schrieb am Do., 6. Mai 2021, 17:32:

**Comment by TheFrazer** [comment]
Naja, da mag man sich drüber streiten. Uns hats nur ziemlich verwirrt, da Patzer ja eigentlich heißt, dass es nicht geht. Egal was sonst ist. Patzer und QS 2 wiederspricht sich da mMn.

Wollte nur Bescheid geben ;)

**Comment by mckee14** [comment]
Ist ja auch legitim, und keine Lösung ist hier "richtig".

Oft nehmen Entwickler Software ganz anders wahr als die Nutzer - und oft verstehen die Nutzer nicht, warum etwas ist, wie es ist. Darum ist wichtig, dass man transparent kommuniziert und ggf. erklärt und begründet.

Für Entwickler ist es eh immer fies - jemand will eine Änderung, er/sie investiert Zeit, setzt es um, und dann kommen 3 mal mehr Leute und wollen es wieder zurück :)

Persönlich habe ich lieber mehr Infos als zu wenig, und wenn sie schon hier stehen fände ich es schade, diese mit Aufwand wegzumachen. Allenfalls könnte man den Hinweis zu Patzer fett machen, und/oder in roter Schrift.

Stell Dir vor, aufgrund einer SF oder Items etc. darfst du einen Patzer negieren. Dann geht das Rechnen los, obwohl Foundry das eigentlich schon erledigt hat.

**Comment by TheFrazer** [comment]
Ok, wollte da vor allem Bescheid geben, da ich dachte, dass das nicht so gedacht ist (und wie ich oben geschrieben habe auch anders für besser halte). Ich habe aber selbst auch kein großes Problem, wenn es bleibt. Ich finde es anders halt einfach schöner.

Das Argument mit der Sonderfertigkeit/Item finde ich ein wenig Banane. 1. gibts so was meines Wissens nicht (zumindest offiziell) und 2. wird das in den meisten Fällen (mal weit fortgeschrittene Helden außen vor - also viel AP) nichts bringen, da man meistens die Patzer trotzdem nicht schafft, wenn die Würfel gleichbleiben. Aber darum solls auch gar nicht gehen. Wie du schon schreibst, jeder wird da ne eigene Meinung zu haben.

Nur noch zu dem mit den möglichst alle Infos. Das kann halt auch mal schnell zu Verwirrung führen. Vor allem bei nicht ganz erfahrenen Gruppen. Wenn jetzt zB eine solche anfängt über Foundry zu spielen und sich deshalb mit den (Würfel) Regeln weniger auseinandersetzt als andere, dann kann es schwer werden. Zumindest mMn. Ich meine, auch unser Spieler war erstmal sichtlich verwirrt. 

Am Ende vom Tag liegt die Entscheidung aber ja eh nicht bei mir. Ich kann für das plädieren, was ich für besser halte und andere für ihre Meinung :)
