### ISSUE TITLE
Schmerzstufen werden nicht korrekt berechnet

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#36]
**Describe the bug**

Bei 5 LeP sollte ein Actor eine weitere Schmerzstufe bekommen. Dem ist nicht immer so. Das Wildschwein zb aus dem Schnellstartabenteuer bekommt erst bei LeP 0 Schmerz 4.

**To Reproduce**
1. Installiere und initialisiere Schnellstartabenteuer
2. Ziehe Wildschweintoken auf Karte
3. Klicke auf Token
4. Gib für LeP einen Wert von 5 oder weniger ein.

**Expected behavior**
Schmerz 4

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Foundry App
 - Version 0.7.9

**Comment by Plushtoast** [comment]
Should be ok in the current patch
