### ISSUE TITLE
Bar 2 Attribut nicht mehr händisch änderbar, wenn ein Actor KaP/AsP besitzt

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#361]
**Describe the bug**
Grundsätzlich zeigen wir in unserer Gruppe die Energiebalken an ("Hovered by Anyone"). Wir haben einen Geweihten Charakter. Wir wollen seine KaP im Gegensatz zu seinen LeP nicht anzeigen. Darum stellen wir **Bar 2 Attribute** im Prototype-Token auf "None" um und speichern "Update Token" 
Allerdings nimmt er die Speicherung nicht an bzw. stellt wohl automatisch wieder zurück.

**To Reproduce**
Öffne die Prototype-Token-Configuration bei einem actor mit KaP/AsP (egal ob SC, NSC oder Kreatur)
Stelle Bar 2 Attribute auf "none"
Klicke auf Update Token
Die Änderung wird nicht übernommen.

**Expected behavior**
Bei Charakteren mit KaP/AsP werden diese nur einmalig als Bar-2-Attribut eingetragen, sobald überhaupt KaP/AsP dazukommen. Alle späteren händischen Änderungen von Bar 2 Attribut bleiben erhalten.

**Additional context**
Bar-1-Änderungen bleiben allem Anschein nach gespeichert.
Bar-2-Änderungen bei profanen Actors auch.

**Comment by mckee14** [comment]
@Albinosheep
- Workaround
  - Token auf eine Szene ziehen
  - Token in der Szene öffnen und in dessen Einstellungen die KaP/AsP Leiste umstellen auf "none".
  - Speichern und *Token ausgewählt lassen*
  - Charaktersheet über das Charakter-Menü öffnen
  - Einstellungen für den Prototype Token öffnen
  - Auf "Assign Token" klicken. Damit wird der aktuell ausgewählte Token inkl. Konfiguration als Prototype-Token hinterlegt

So bleibt die Änderung gespeichert.

**Comment by Albinosheep** [comment]
Danke mckee14 für deinen Workaround-Vorschlag. Leider funktioniert er nicht dauerhaft. Im ersten Schritt funktioniert das. Sobald man den AsP/KaP-Wert des Charakters ändert, wird der Bar 2 Prototype-Token wieder geändert. Ein späteres hinzufügen des Tokens führt wieder dazu, dass der Bar 2 da ist.

**Comment by mckee14** [comment]
Erneut auf die szene ziehen hat bei mir funktioniert. Wenn es beim ändern
der werte aber wieder zurückgesetzt wird, muss der coder ran :)

Albinosheep ***@***.***> schrieb am Sa., 8. Mai 2021, 10:01:
