### ISSUE TITLE
DSA5-Core: Verteidigungshaltung hat leeres Effekt feld

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#362]
Hallo,

bei der Sonderfertigkeit Verteidigungshaltung ist aktuell das Effektfeld leer, wodurch man die SF beim Würfeln nicht automatisch berücksichtigen lassen kann. Wäre gut, wenn da die Erhöhung der Verteidigungswerte eingetragen wird.

**Comment by Plushtoast** [comment]
Die system updates sind langsamer als die module. Aber das ist schon drin im patch
