### ISSUE TITLE
Vorteil Visonär hat Karmalpunkte

### ISSUE THREAD

**Issue by RondraLion** [Plushtoast/dsa5-foundryVTT#363]
Hallo dieser Vorteil generiert Karmalpunkte im Heldenbogen, wenn man eine "Vision des XYZ"  als SF gewählt hat. Das dürfte nicht passieren.

**Comment by mckee14** [comment]
Der Vorteil aktiviert keine KaP, allerdings geschieht es über die SF (Vision des ...). Dies, weil die Kategorie in den SF als "klerikal" definiert ist.

@Plushtoast: Allenfalls die Anzeige von KaP Leiste an den Vorteil "Geweihter" koppeln? Den Reiter "Religion" muss ein einblenden, sonst sieht man die SF nicht im Char...

@RondraLion: Du kannst in der Sonderfertigkeit (im Charaktersheet) die Kategorie von "klerikal" umstellen auf "Allgemein" oder "Schicksalspunkte". Dann taucht der Eintrag im Reiter "Eigenschaften" auf und die KaP Leiste verschwindet wieder aus dem Char.

**Comment by mckee14** [comment]
Das war die info für plushtoast und funktioniert anders rum... Man kann die
SF wählen, ohne geweihter zu sein. Aber die KaP Leiste soll nur angezeigt
werden, wenn man den Vorteil Geweihter hat.

So kannst du die SF wählen, ohne KaP angezeigt zu bekommen. Momentan prüft
es wohl, ob klerikale SF im char sind, hier könnte man eine UND bedingung
für den Vorteil einfügen.

Also das, was du wolltest. Für dich war ja nur der andere textteil.

Und wieso bekommst du 0/15KaP? Da sollten 0/0 sein. Hast du bei Religion
eine Leiteigenschaft ausgewählt?


RondraLion ***@***.***> schrieb am Sa., 8. Mai 2021, 10:01:

**Comment by RondraLion** [comment]
sry der Bogen hat doch 0/0 Kap. Entschuldigung...

**Comment by Plushtoast** [comment]
Das bleibt alles so, sonst sind leute verwirrt, wenn sie eine Liturgie auf den Bogen ziehen und nix passiert. Die Kategorie der Sonderfertigkeit zu ändern ist ein workaround.
