### ISSUE TITLE
Stufenanzeige mit I, II, III, ... bei Vor- und Nachteilen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#365]
**Is your feature request related to a problem? Please describe.**
Bei stackenden Vor- und Nachteilen (wie Glück oder Pech) wird im Namen nicht I, II oder III angezeigt. Man kann den Stack nur über die Details auslesen.

**Describe the solution you'd like**
Analog zu SF die verschiedenen Stufen durchnummerieren; z.B. SFs: Glück I, Glück II, Glück II

**Comment by Plushtoast** [comment]
Ich weiß nicht, was du meinst.
![grafik](https://user-images.githubusercontent.com/44941845/117582909-a881da80-b104-11eb-8c0b-c3c3dfd804a1.png)
Is doch da.

**Comment by Albinosheep** [comment]
OK ich habe es nochmals geprüft. Es scheint ein Bug bei der Darstellung von NSC-Actors zu sein. Bei NSC und Kreaturen klappt es. Ich habe trotzdem mal den entsprechenden Aktor in den Anhang gepackt..

<img width="1069" alt="Glück Bug" src="https://user-images.githubusercontent.com/41292141/117583468-97869880-b107-11eb-90dc-8bd0f69f48e8.PNG">

[Ruadh.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6448225/Ruadh.zip)
