### ISSUE TITLE
Mehrfache Verrechnung von Modifikationen bei einem Angriffswurf mit Target-Funktion

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#366]
**Describe the bug**
Gleiche Modifikatoren wurden doppelt verrechnet.

**To Reproduce**
Der Fehler trat an dem Abend zwei- oder dreimal auf. Allerdings kann ich die Bedingungen, wann er auftritt, noch nicht genauer eingrenzen. Zwischen den Würfen wurde im Actor allerdings nichts umgestellt.

**Expected behavior**
Keine doppelte Verrechnung des gleichen Modifikators.

**Screenshots**
<img width="210" alt="Maru bug" src="https://user-images.githubusercontent.com/41292141/117584067-f1d52880-b10a-11eb-9ab7-0397570387d8.PNG">

**Comment by Plushtoast** [comment]
Das müsste ein Überbleibsel aus einem alten Patch sein. Auf dem Status Tab per Rechtsclick alle Status entfernen.

**Comment by Plushtoast** [comment]
Nochmal aufgetreten?

**Comment by Albinosheep** [comment]
Nein. Vielen Dank deiner Nachfrage. Allerdings hatten wir seitdem auch keine größeren Kämpfe mehr. 
Ich melde mich auf jeden Fall, falls es nochmals auftritt.
