### ISSUE TITLE
Compatibility with Foundry VTT 8.0.X

### ISSUE THREAD

**Issue by lorion1985** [Plushtoast/dsa5-foundryVTT#367]
If you install the new beta version of Foundry VTT, you can't create an actor. It seems that the version is not compartible with the breaking changes.

**Comment by Plushtoast** [comment]
DSA/TDE is not supposed to be compatible at this point.

No system is going to be compatible. 0.8 is by default incompatible to 0.7.

TDE/DSA will only be available for 0.8 after a stable 0.8 release.

ALSO KEEP IN MIND THAT A MIGRATION NOW MIGHT BREAK STUFF.
Backup your world before migration.

**Comment by lorion1985** [comment]
Other systems use two different module.json for the different versions so they can afford a smooth update.

**Comment by Plushtoast** [comment]
I am super stupid and lazy. I don't do that.

**Comment by Plushtoast** [comment]
Next week last DSA/TDE patch for 0.7.

Then with the stable release which is announced for the beginning of june probably DSA/TDE for 0.8
