### ISSUE TITLE
Magische Sonderfertigkeiten addieren keine FP zu Zaubern

### ISSUE THREAD

**Issue by RheoPreussler** [Plushtoast/dsa5-foundryVTT#368]
Es gibt noch eine Reihe von magischen Sonderfertigkeiten (u.a. "Erfahrener Antimagier", "Scholar der Halle der Antimagie zu Kuslik"), die FP bei Zaubern einer bestimmten Schule (z.B. Antimagie, Bannzauber) addieren, bei bestandener Probe. 

Diese tauchen aber im "Zauberprobe" Fenster unter "Bedingte Modifikatoren", anders als z.B. "Lieblingszauber", nicht auf und werden auch ansonsten nicht automatisch eingerechnet.

**Comment by Plushtoast** [comment]
Wirds so schnell nicht geben.
Ich empfehle alle Zauber die davon betroffen sind händisch im Effektfeld einzutragen.

**Comment by mckee14** [comment]
Kannst Du ggf. kurz erläutern, WAS genau WO eingetragen werden muss?

z.B: Bei gelungenem Ignifaxius bekommt der Char +1 FP für die Berechnung der QS.

Bonusfrage: Kann man mit der gleichen Mechanik auch reduzierte Kosten für den Spruch abbilden, zB: Ignifaxius kostet immer 1AsP weniger?

**Comment by Plushtoast** [comment]
Da gibt es zwei Methoden.
Man kann zb der Sonderfertigkeit ActiveEffects hinzufügen (in 0.7 nur vor dem hinzufügen zum Actor) und dort als key:data.skillModifiers.FP, mode: custom, value: "Armatrutz 2,Axxeleratus 1" angeben. Dann bekommt man das beim Rolldialog als Option. Alternativ geht es auch im Effektfeld der Sonderfertigkeit mit "Armatrutz FP2,Axxeleratus FP2".

Für Zauber die immer eins weniger kosten, empfehle ich das im Charakterblatt bei den AsP Kosten anzupassen.
Außerdem gibt es noch die Möglichkeit einen Effekt zb auf einen Stab mit Kraftfokus zu legen der die AsP Kosten (für alle Zauber) reduziert, wenn getragen.

**Comment by mckee14** [comment]
Super, danke! Dann trage ich es schon mal als active effect ein, 0.8
updates stehen ja bald ins haus :)

Plushtoast ***@***.***> schrieb am Di., 18. Mai 2021, 15:03:
