### ISSUE TITLE
Fehlendes "Immun gegen Schmerzen" trotz Update

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#371]
Der Trait "Immun gegen Schmerzen" ist nicht zu finden. Weder im Kompendium Vorteile noch bei Sonderfertigkeiten?

Core Version sollte ja mit 1.4 das für Kreaturen möglich machen.

**Comment by Plushtoast** [comment]
Einfach selbst eintragen. Das muss nur so heißen. War nicht geplant den fertig zu liefern

**Comment by CommanderAlex98** [comment]
Habe das jetzt ausprobiert, auch mit verschiedenen Schreibvarianten: die Kreatur bekommt trotzdem den Schmerzstatus.

**Comment by Plushtoast** [comment]
Es muss exakt "Immun gegen Schmerzen" heißen.
Bestehender Schmerz wird nicht entfernt und muss manuell gelöscht werden (rechte Maustaste auf dem Bogen).

![grafik](https://user-images.githubusercontent.com/44941845/118650111-603d7900-b7e4-11eb-839e-b325a50085da.png)

**Comment by mckee14** [comment]
Ha, da war er schneller...

Aber wenn ich den Screenshot schon gemacht habe, hänge ich ihn auch an :)

![grafik](https://user-images.githubusercontent.com/62849695/118650397-b4485d80-b7e4-11eb-8d97-12a0c2710963.png)

**Comment by CommanderAlex98** [comment]
Danke funktioniert :)
