### ISSUE TITLE
Statuseffekte: Aktivieren/Deaktivieren Haken hat aktuell augenscheinlich keine Funktion 

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#373]
**Describe the bug**
Der Aktivieren/Deaktivieren im Statustab des Charakterbogens ist aktuell ohne Funktion. Es veerschwindet weder das Icon am Char, noch der Effekt bei den Proben. 

**To Reproduce**
1. Effekt Paralyse hinzufügen
2. Effekt deaktivieren
3. Probe auf Körperbeherrschung durchführen und Token kontrollieren

**Expected behavior**
Funktion des Hakens wieder herstellen :)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/118645606-6bda7100-b7df-11eb-9ebf-37824a47e7e3.png)

**Desktop (please complete the following information):**
Chrome Browser

**Comment by Plushtoast** [comment]
Hat bei Systemeffekten bis dato nur keine Funktion.
War bis jetzt nur für custom effects gedacht.

**Comment by tomsaath** [comment]
Joa, ich habe das bisher auch nur bei den custom effects gebraucht. Wenn es also nur da wieder geht ist das okay... Aktuell fliegen meine Kreaturen dadurch halt permanent, was etwas unglücklich ist.
