### ISSUE TITLE
Sichtmodifikator und -weite abhängig vom Tageslicht

### ISSUE THREAD

**Issue by Zamino** [Plushtoast/dsa5-foundryVTT#375]
1) Die Sichtmodifikatoren sind von vielen Faktoren abhängig und sicherlich nie voll automatisch implementierbar. Aber zumindest eine hilfreiche Funktion wäre es aus meiner Sicht, wenn die Sichtmodifikatoren sich automatisch passend zum Licht der jeweiligen Szene voreinstellen würden. z.B.:

-1 in der blauen Stunde, z.B. zwischen 50% und 70% Dunkelheit
-2 zwischen 71% und 85% Dunkelheit
-3 zwischen 86% und 99% Dunkelheit
-4 bei 100% Dunkelheit

Die Schwellen könnte man in den Optionen individuell anpassen oder ausschalten.

2) Außerdem wäre es aus meiner Sicht eine sehr große Erleichterung, wenn man ab einem einstellbaren Schwellenwert die Sichtreichweite für Dämmersicht und helle Sicht umstellen könnte. z.B. ab 70% Dunkelheit von 20 und 10 Schritt auf 4 und 2 Schritt.

Ich bin euch sehr dankbar, dass ihr DSA für Foundry umsetzt und will es schon jetzt nicht mehr missen. :-)

**Comment by mckee14** [comment]
Persönlich wäre mir das zu gimmicky, ich wäre wohl öfter die automatische
stufe am korrigieren.

Allenfalls eine standard sichtstufe pro szene wäre nicht schlecht.

Wir wollen ja kein pc spiel, sondern ein tabletop... Oder? :)

Zamino ***@***.***> schrieb am Mi., 19. Mai 2021, 11:19:

**Comment by Zamino** [comment]
Ich habe ein bisschen das Problem, dass meine Runde seeeehrr gern Modifikatoren wie Sicht schlicht vergisst. Daher wäre ein bisschen Unterstützung durch das Programm für meine Runde schon hilfreich. ;-)

**Comment by Plushtoast** [comment]
Also das beleuchtungsdingens stößt auf jeden Fall auf verschiedene Meinungen. Ich würde es einbauen, wenn das Konzept etwas detaillierter ist.
Zb braucht es auch ein Makro oder eine Funktion um schnell sichtweiten einzustellen inklusive leuchtquellen. Diese zb wenn man im Inventar die fackel anlegt. Das ist sonst immer sehr fizzlig. Und dazu müsste man festlegen, welche sichtweiten default sinn machen, ob und wie man die konfigurieren kann. Inklusive zauber und Dunkelsicht. Und dann noch alles irgendwie komfortabel steuerbar, so dass es nicht alles komplizierter macht sondern vereinfacht.

**Comment by Zamino** [comment]
Für Fackeln hilft das Modul Torch sehr. Es fügt jedem Token einen Fackel-Button hinzu. Wird der geklickt, emittiert der Token selber Licht. Dies kann in den Token-Einstellungen unter Vision komplett selbst editiert werden. Für D&D wird sogar beim Klick auf den Button eine Fackel aus dem Inventar verbraucht.

Was hältst du von der Idee: In den Token-Einstellungen unter Vision macht man ein Ausklappmenüpunkt für unterschiedliche Lichtstimmungen (Tag, Dämmerung, Nacht, Dunkelheit). Je nachdem, was man auswählt, wechseln die Werte unter Dämmersicht und Helle Sicht automatisch. So kann für jeden Helden die Sicht für jede Lichtstimmung individuell voreingestellt werden. Das würde Fähigkeiten wie Dunkelsicht Rechnung tragen.
Im Optionsmenü könnte man einstellen, bei welcher Prozentzahl der globalen Beleuchtung einer Karte welche Lichtstimmung erreicht wird. (siehe mein Beitrag oben)

Somit würde sich für jeden Token die Sichtweite ändern, sobald sich die globale Beleuchtung eine Karte ändert. Für Zauber weiß ich nicht ob das möglich ist aber wäre es eine Idee, dass als Effekt des Zaubers die Werte für Sichtweite von Dämmersicht und Helle Sicht erhöht werden?

Übrigens: Im Spielleiterschirm Katakomben und Ruinen gibt es Regeln für Sichtweite mit Fackeln. Vielleicht helfen die für Default-Werte?

Vielen Dank für dein Feedback.

**Comment by Plushtoast** [comment]
Also so mega easy oder gut ist das auch nicht.
Man müsste dann z.b. wenn jemand gerade im Licht steht, den Modifikator wieder weglöschen.

Dann müsste man zusätzlich noch abfragen, ob der Token das Ziel gerade sehen kann und in welcher Art von Licht das steht + noch obendrauf ob man dämmersicht hat etc.

Ich weiß nicht, ob sich das sinnvoll lösen lässt.

**Comment by Plushtoast** [comment]
Die Sicht hängt ja nicht nur von der aktuellen Szenendunkelheit ab.

**Comment by Plushtoast** [comment]
Na egal, jetzt ist es drin.

**Comment by Plushtoast** [comment]
Im nächsten core modul update ist auch ein einigermaßen angenehmes Makro zum Sichtweiten ändern.
Siehe #584
