### ISSUE TITLE
BHK mit identischen Waffen

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#377]
**Describe the bug**
Wenn man die gleiche Waffe zweimal in den Character Sheet zieht, wird diese im Ausrüstungstab gestackt und man hat keine Möglichkeit, diese je einmal in Haupt- und Nebenhand auszurüsten.

**To Reproduce**
Die gleiche Waffe zweimal auf einen Charakter ziehen.

**Expected behavior**
Bei vielen Items ist stacken sinnvoll, insbesondere bei Waffen sollte dies aber nicht der Fall sein.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 90

**Comment by Plushtoast** [comment]
Auf deinem Charakterblatt im Ausrüstungstab strg gedrückt halten und die Waffe auf das eigene Sheet Drag & Dropen um sie zu kopieren.

**Comment by zoidable** [comment]
Oh...danke :)

**Comment by mckee14** [comment]
Du brauchst nur 1 waffe auszurüsten, damit greifst du 2 mal an. Die
modifikatoren für 2. angriff und falsche hand sind im popup nach dem
angriff zu finden.

zoidable ***@***.***> schrieb am Mi., 19. Mai 2021, 20:31:
