### ISSUE TITLE
Haircolor and Eyecolor switched

### ISSUE THREAD

**Issue by christian-gruenwied** [Plushtoast/dsa5-foundryVTT#378]
In the actor entity, the haircolor and eyecolor is switched - the hair color is stored in Data.details.eyecolor.value, the eye color in Data.details.haircolor.value.

**Comment by Plushtoast** [comment]
I don't know to what location you are refering. Seems fine to me.
Make sure your system version is at 1.4.2.

There are multiple versions you have to keep track of.
* Foundry version (currently 0.7.9)
* TDE/DSA System version (currently 1.4.2)
* And versions for different modules including the core rules for dsa (which is not the system)

**Comment by christian-gruenwied** [comment]
Jup, you're right. When I created my character, I was on a version pre 1.4.0. It seems, that between the versions haircolor and eyecolor switched. Or that I was unattantive when created my character. Whatever the reason, now it's working as expected. Setting the issue to closed. 

Thank you for the fast answer!
