### ISSUE TITLE
BETATEST Foundry 0.8 - Feel free to join

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#379]
We've got a beta version for Foundry 0.8.x ready now. The migration to the new version broke a lot of stuff. That's why it would be very helpful to have some voluntary testers, so we can release a bugfree version with the arrival of stable Foundry 0.8.6. Make sure to backup your worlds to prevent loss of data or test in an entirely different foundry installation. To test you need the current Foundry Beta version (0.8.5). The TDE installation can be done by using this link in the system installation section:
https://raw.githubusercontent.com/Plushtoast/dsa5-foundryVTT/foundry08/system.json . The same link will be used to update the system while in beta test. Feedback via Github or in this channel. Thanks!

**Comment by mckee14** [comment]
You want all the feedback in this thread? Or just in the general issues where the non-beta feedback is?

One thing I found, first start of freshly installed DSA core with Foundry 0.8.5:
 - you get a message to choose DE or EN as language.
 - I chose DE
 - restarted the docker container, and my world was set to EN. I had to manually switch to DE again.

**Comment by Plushtoast** [comment]
Feedback in Discord or here. In this thread or separate doesnt matter.

**Comment by tomsaath** [comment]
ist nur schwer nachzustellen, aber ich habe gerade im Kampf einen Patzer gewürfelt und beim Ergebnis stand: Schadenspunkte: undefined
![grafik](https://user-images.githubusercontent.com/80099175/119500238-deab9500-bd67-11eb-9fec-036b2ced8471.png)

**Comment by tomsaath** [comment]
Bei Schmerz 4 wird nicht mehr der Effekt Handlungsunfähig hinzugefügt:
![grafik](https://user-images.githubusercontent.com/80099175/119500776-75785180-bd68-11eb-8ba4-8f3854b4a8ba.png)

**Comment by tomsaath** [comment]
Beim Löschen einer Fähigkeit im Kreaturenbogen kommt es zu einem Fehler:
`Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at ActorSheetdsa5Creature._cleverDeleteItem (creature-sheet.js:32)
    at Object.callback (actor-sheet.js:730)
    at Dialog.submit (foundry.js:20302)
    at Dialog._onClickButton (foundry.js:20265)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:`

**Comment by Plushtoast** [comment]
Neue Funktionen sind btw hier in der Beta zu finden:
https://github.com/Plushtoast/dsa5-foundryVTT/projects/22

**Comment by tomsaath** [comment]
Ich kann den Händler als Spieler nicht öffnen. Ich habe das Recht beschränkt gegeben, es kommt beim Spieler immer folgender Fehler:
`ReferenceError: An error occurred while rendering MerchantSheetDSA5 87: wep is not defined
    _itemPreparationError actor-dsa5.js:689
    prepareItems actor-dsa5.js:577
    prepareTradeFriend merchant-sheet.js:301
    getData merchant-sheet.js:262
    _render foundry.js:2041
    _render foundry.js:2728
    _render actor-sheet.js:22
    render foundry.js:2003
    render foundry.js:3219
    _onUpdateBaseActor foundry.js:16553
    _onUpdate foundry.js:12312
    callback foundry.js:8850
    documents foundry.js:8802
    _handleUpdateDocuments foundry.js:8802
    activateSocketListeners foundry.js:8441
    emit index.js:145
    value typed-events.js:46
    value socket.js:270
    value socket.js:257
    value socket.js:222
    emit index.js:145
    value typed-events.js:59
    value manager.js:214
    emit index.js:145
    value index.js:120
    value manager.js:206
    emit index.js:145
    value socket.js:416
    emit index.js:145
    value transport.js:107
    value transport.js:100
    onmessage websocket.js:112
foundry.js:2005:14`

**Comment by lorion1985** [comment]
Wir spielen gerade und einer der Helden (ein Elf) kann nicht mehr auf Zauber oder Talente würfeln. Ein Klick auf die Würfel führt zu keiner Reaktion. Ich habe das entsprechende JSON angehängt. Alle anderen klappen. 

[fvtt-Actor-Diundriel_Sternensinn.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6556572/fvtt-Actor-Diundriel_Sternensinn.zip)
