### ISSUE TITLE
Add system support for whisper autocomplete

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#381]

**Comment by Rahjenaos** [comment]
Thanks!!!

**Comment by Plushtoast** [comment]
It#s only a very basic implementation

**Comment by Rahjenaos** [comment]
How does it work? I assume that as soon as I write "/w " I will either see some kind of popup that shows the available whisper-targets or shows "shadow text" fitting to the available whisper-targets and maybe gives me a way to state "yes, that's the one I want to whisper to, take this!"

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/119810896-c746e600-bee6-11eb-949d-5ab5cabb955f.png)

**Comment by Rahjenaos** [comment]
that is awesome and I guess everything we need regarding that feature. Really looking forward. Just one more question: this will only be available when I upgrade to foundry 0.8.x, right?

**Comment by Plushtoast** [comment]
Yes, system for 0.7 will not receive new features anymore
