### ISSUE TITLE
Falscher AP Wert bei Nachteil Prinzipientreue und Verpflichtungen

### ISSUE THREAD

**Issue by Teribos** [Plushtoast/dsa5-foundryVTT#382]
**Describe the bug**
Wenn man die Profession Rondrageweihter per Drag-and-Drop einem Charakter hinzufügt werden die Nachteile "Prinzipientreue" und "Verpflichtungen" jeweils mit einem AP-Wert von "-20" erstellt, statt wie im Kompendium angegeben mit "-10". Dadurch erhält der Charakter zu viele AP.
Im Auswahlfenster der Profession sind die AP Werte korrekt.

**To Reproduce**
Siehe Fehlerbeschreibung

**Expected behavior**
Siehe Fehlerbeschreibung

**Screenshots**
Fehlerhaft aus Charakterblatt:
![grafik](https://user-images.githubusercontent.com/51129571/119345442-2e6f5b00-bc99-11eb-8f5e-142ae4afd3a8.png)
Korrekt aus Kompendium:
![grafik](https://user-images.githubusercontent.com/51129571/119345489-3deea400-bc99-11eb-8c68-457cc6e41ca8.png)

**Desktop (please complete the following information):**
- Foundry 0.7.9
- DSA5 Core 1.4.2
- Gods of Aventuria 1.0.2

**Additional context**
Nicht das selbe wie #279 , dort ging es um doppelte Nachteile. Hier geht es um falsche AP-Werte.

**Comment by Violettdragon** [comment]
Laut Regelwerk S. 159 hat ein Rondrageweihter Verpflichtung II sowie Prinziptreue II kostet je -20 AP
