### ISSUE TITLE
Fernkampf: Nachladen in den Kampfrunden abbilden

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#385]
**Is your feature request related to a problem? Please describe.**
Die Ladezeit ist ja direkt im Charakterbogen bei der jeweiligen Waffe mit angegeben. Es wäre cool, wenn im Kampf die Ladezeit abgebildet werden könnte. 

**Describe the solution you'd like**
Wird im Kampf ein Schuß mit einer Fernkampfwaffe mit Ladezeit abgegeben, soll am Charakter ein Kennzeichen abgebildet werden, welches anzeigt, dass er lädt. Das System soll dieses Kennzeichen nach Ladezeit KR entfernen. Es muss aber auch manuell entfernt werden können, falls es Sonderregeln zur Ladezeit in der Gruppe oder im Regelwerk gibt.
Ich könnte mir gut vorstellen, dass dies im Zusammenhang mit einem Effekt klappt.

**Describe alternatives you've considered**
Keine Alternativen. Wenn das oben genannte nicht klappt, werde ich manuell Effekte dafür anlegen.

**Comment by Plushtoast** [comment]
Geht in die Richtung von #320

**Comment by tomsaath** [comment]
Ach man sorry, ich komme anscheinend mit dem Suchen nach doppelten Issues irgendwie noch nicht klar... Ich beobachte dann den von dir genannten issue. Meinetwegen kann dieser dann geschlossen werden, wenn das geht.

**Comment by Plushtoast** [comment]
Kein Problem. Kann ich beim Lösen zwei Tickets schließen und hab doppelt so viel gearbeitet 🥇
