### ISSUE TITLE
Effekte: Einfluss auf die Regeneration (LeP. AsP, KaP)

### ISSUE THREAD

**Issue by tomsaath** [Plushtoast/dsa5-foundryVTT#389]
Es wäre gut, wenn man durch einen Effekt Einfluss auf die Regeneration des Charakters nehmen könnte. Dies wäre zum Beispiel bei einer Heilkunde Wunden Probe oder speziellen Heilkräutern nützlich.

Wunsch:
Im Dropdown bei den Effekten einen Regenerationsbonus auswählen zu können.

Optimal:
Angabe wie oft dieser Effekt angewendet werden können (Bsp. Heilkunde - nach einem mal ist der Effekt weg.

**Comment by mckee14** [comment]
Würde es nicht reichen, einfach ein Wertefeld zu haben, in das man händisch
den gewünschten Wert eingibt? Man würfelt ja eh jede Regeneration einzeln
aus...

Was aber toll wäre: wenn man anstatt fixe Werte auch würfe mitgeben kann,
also "+1w3 LeP" usw.

tomsaath ***@***.***> schrieb am Do., 27. Mai 2021, 07:36:

**Comment by tomsaath** [comment]
Stimmt, das kann man auch schon jetzt. Nur teilweise vergehen bei uns zwischen den Sitzungen einige Wochen und ein Effekt kann direkt nach der Heilkunde Probe angelegt werden. Das wird dann nicht so schnell vergessen wie eine Notiz irgendwo anders.

Würfel wären aber auch cool.

**Comment by mckee14** [comment]
Ich lege für das verwenden von Würfeln einen separaten Feature Request an.

Zu den Modifikatoren - das müsste ja transparent im Charaktersheet hinterlegt werden. Ich wüsste gerade nicht, an welcher Stelle dies gemacht werden soll... höchstens, den Button für die Regeneration anpassen, dass dieser eine Übersicht über die Regeneration bietet, inkl. Modifikatoren, einmalige Boni/Mali, und die Möglichkeit von da aus den Wurf auszulösen.

Für 98% der Fälle wird es dadurch aber unübersichtlicher anstatt besser.

**Comment by tomsaath** [comment]
Naja, als Status-Effekt könntest du es beim Regenerationswurf so einblenden wie auch bei den Talenten?
![grafik](https://user-images.githubusercontent.com/80099175/119803508-cf4f5780-bedf-11eb-935b-52c04d79feaa.png)

**Comment by Plushtoast** [comment]
Also problematisch ist hier, dass es ein Effekt wäre, der bei Gebrauch verbraucht wird.
Einmalige Anwendung. Das erfordert erst noch ein bisschen Grübelei und vielleicht Anmerkungen, wo dies noch entscheidend sein könnte.

**Comment by vt-tom** [comment]
Also, ich wüsste jetzt nur von der Heilkunde Wunden Probe. Magie und Liturgie wirkt ja in der Regel direkt, es sei denn ich habe irgendwas unter den drölfzig Sprüchen übersehen.
Vielleicht steckt auch noch in dem ein oder anderen Kraut oder Trank derselbe effekt?

**Comment by mckee14** [comment]
ZB ruhe körper aus AMA 1:
https://www.ulisses-regelwiki.de/ritual.html?ritual=Ruhe+K%C3%B6rper

Da müsste man QSx2 LeP zusätzlich regenerieren in der nächsten
Erholungsphase.

Wie das von der reihenfolge her ist mit weiteren modifikatoren, keine
ahnung.

Schlechte Umgebung:
(1w6/2)+QSx2 Lep?
(1w6+(QSx2))/2 LeP?
Usw.

tomsaath ***@***.***> schrieb am Sa., 5. Juni 2021, 13:24:

**Comment by Plushtoast** [comment]
Ich würde für den nächsten Patch zwei fixe Felder hinzufügen.
Einmal "permanenter Regenerationsbonus", und dann "temporärer Regenerationsbonus" - wird beim nächsten Wurf auf 0 gesetzt.
Ersteres lässt sich über active effect modifizieren.
Ob es einen active effect für temporäre boni geben wird, muss ich mal schauen, ob sich das einigermaßen sinnvoll programmieren lässt

**Comment by vt-tom** [comment]
Das klingt gut und nach einer passenden Lösung. 

Was mir dabei noch einfällt, es sollte getrennt Einfluss auf LeP, AsP und Kap nehmen. Also je Ressource einstellbar sein. Aktuell beeinflusst der Mod den man setzen kann ja auch immer alle Ressourcen oder?

**Comment by Plushtoast** [comment]
Hm, noch ne gute Idee wie das ins GUI passt, ohne alles klobig zu machen?
