### ISSUE TITLE
Using Roll Syntax in value-fields

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#390]
Allow to use the Foundry roll syntax (or a limited part thereof) in fields for damage and effects.

f.e: special ability "augenstecher", effect "-2 AT, **+1w6 TP**"
calculation would be handy, too: "-2 AT, **+(1-1w3) TP**"

(could be linked to #391)

**Comment by Plushtoast** [comment]
Hum?
Where?

**Comment by mckee14** [comment]
in the effects field, f.e. special ability "zu Fall bringen":
![grafik](https://user-images.githubusercontent.com/62849695/119794589-f2760900-bed7-11eb-933d-8a8a1274a7b8.png)

**Comment by Plushtoast** [comment]
Is there any other effect except damage, that would benefit from this solution?

**Comment by mckee14** [comment]
It could be used everywhere, but without changing the whole data structure, it's limited to values which are rolled upon every time (attacks, checks, spells, liturgies...) and nothing constant (equipped items, effects...).

There are spells who use dice to determince the outcome, but AFAIK you have them covered via scripts.

Best efford/benefit would certainly be combat abilities influencing damage rolls.
And it only makes sense together with "replace the original value" #391.
