### ISSUE TITLE
assign status via special abilities

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#394]
allow to assign pre-defined stati (like "liegend", "vergiftet", etc) via special abilities
(same functionality like it currently exists within spells, Sondereffekt / Effekt)

![grafik](https://user-images.githubusercontent.com/62849695/119826654-88ba2700-bef8-11eb-8c34-5024320938c8.png)

**Comment by Plushtoast** [comment]
Only for combat special abilities, right?

**Comment by mckee14** [comment]
I only see it for combat special abilites, yes.



Plushtoast ***@***.***> schrieb am Di., 1. Juni 2021, 08:20:
