### ISSUE TITLE
[BETA 0.8.x Foundry] Itemrules not referencing new data model properly

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#397]
Wir spielen gerade und einer der Helden (ein Elf) kann nicht mehr auf Zauber oder Talente würfeln. Ein Klick auf die Würfel führt zu keiner Reaktion. Ich habe das entsprechende JSON angehängt. Alle anderen klappen. 

[fvtt-Actor-Diundriel_Sternensinn.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6556572/fvtt-Actor-Diundriel_Sternensinn.zip)

_Originally posted by @lorion1985 in https://github.com/Plushtoast/dsa5-foundryVTT/issues/379#issuecomment-849914019_

**Comment by lorion1985** [comment]
So wie es aussieht hat es etwas mit den "Lästigen Mindergeistern" zu tun

**Comment by Plushtoast** [comment]
Ist schon erledigt. Musst das system über das erneute einfügen des installinks überschreiben. Der update button reicht nicht. Danke für s finden.
