### ISSUE TITLE
Fehlende Zaubererweiterungen in Aventurische Magie II

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#400]
**Describe the bug**
Es fehlen Zauber- und Ritualerweiterungen in Aventurische Magie II, deren Zauber enthalten sind.

- Wasserpfeil
- Wellenlauf
- Wogenform
- Zauberpferd herbeirufen

Die Auswahl ist nur, was mir aufgefallen ist und nicht zwingend abschließend.

**Comment by Murm3lt13r** [comment]
ToDo: Check Extensions in package
