### ISSUE TITLE
Kreaturen aus dem Almanach

### ISSUE THREAD

**Issue by faddoMA** [Plushtoast/dsa5-foundryVTT#405]
**Is your feature request related to a problem? Please describe.**
Es ist schade dass die Kreaturen aus dem Almanach nicht komplett dem neuen Bestiarium 2 hinzugefügt wurden. So bleibt die "Monsterbibliothek" ein Patchwork. 

**Describe the solution you'd like**
Die Kreaturen des Almanachs (2Ed) sollten dem Bestiarium hinzugefügt werden, oder in einer anderen Weise in Foundry zugänglich sein. Da wären: Oger, Troll, Höhlenspinne, Gruftassel, Krakenmolch, Tatzelwurm, Waldschrat, Grimwolf, Schwarzbär, Wolfsratte. Gut wäre zu wissen ob das geplant ist, oder ob einzelne Tiere dann z.B. nur separat (z.B. in der Drachenritter FoundryVTT Erweiterung) zu bekommen sind.

**Comment by Plushtoast** [comment]
Die sind im Bestiarium 1 im nächsten Patch.
Siehe: https://github.com/Plushtoast/dsa5-foundryVTT/releases/tag/1.4.0

**Comment by faddoMA** [comment]
Yeah! Danke!
