### ISSUE TITLE
Items verzaubern: permanent oder wiederaufladbar

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#406]
**Is your feature request related to a problem? Please describe.**
Wird ein Gegenstand mit einem Zauber *verzaubert*, verschwindet der Zauber nach einer Anwendung komplett aus dem Gegenstand. Es gibt ja aber Artefakte die sich selbst aufladen oder sogar permanent sind. Es wäre gut wenn dies irgendwie einstellbar ist.

**Describe the solution you'd like**
Ein Kennzeichen am Zauber, dass dieser sich nach Zeit X (Monat, Woche, Tag...) oder permanent bleibt. Es muss mit der Zeit nicht zwingend automatisch abgewickelt werden.

**Describe alternatives you've considered**
Es wäre schon ein guter Anfang, wenn eine Anwendung den Zauber nicht komplett vom Gegenstand entfernt. Sondern dieser nur deaktiviert wird, So könnte man ihn manuell wieder aktivieren und muss ihn nicht neu auf den Gegenstand ziehen.

**Comment by Plushtoast** [comment]
Einer der Buttons müsste den zauber schon permanent machen

**Comment by vt-tom** [comment]
Jap, hast recht. Da muss es dann einfach nur ne Anleitung zu geben und fertig. Von mir aus kann das hier zu.
