### ISSUE TITLE
Add effects to arrows

### ISSUE THREAD

**Issue by Corelich** [Plushtoast/dsa5-foundryVTT#408]
Ist es möglich, Pfeilen Effekte zu geben?

Is there a possibility to add effects to arrows like FK+1 or TP/SP+1?

**Comment by Plushtoast** [comment]
No. We don't add rules of books that we didn't include as a module yet.
DSA is too big and we would never be able to finish anything.

**Comment by Corelich** [comment]
Sad, but ok.

**Comment by Plushtoast** [comment]
Keep track of the patch notes. I am sure this will be added at some point
