### ISSUE TITLE
Character cannot be clerical and magical at the same time

### ISSUE THREAD

**Issue by philhoefer** [Plushtoast/dsa5-foundryVTT#41]
**Describe the bug**
According to TDE rules, a character **can** have a magical *and* a karmal tradition. While the combination is rare, it is possible.

**To Reproduce**
1. Create a character
2. Add a spell, ritual or cantrip
3. Add a liturgy, ceremony or blessing
4. Character sheet displays "Magie" tab but no "Religion" tab

**Expected behavior**
Character sheet displays "Magie" tab and "Religion" tab.

**Additional context**
The main culprit is in line 446-447 of actor-dsa5.js:
<pre><code>//CHAR cannot be clerical and magical at the same time
magic.hasPrayers = magic.hasPrayers && !magic.hasSpells</code></pre>
Apart from that, the character sheet will probably have to be changed to allow for the display of both tabs.

**Comment by Plushtoast** [comment]
Will be part of the next patch

**Comment by Plushtoast** [comment]
Should be ok in the current patch
