### ISSUE TITLE
[DSA 2.0.0 - Foundry 0.8.6] Token Vision bei import zurückgesetzt

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#410]
**Describe the bug**
Ich kann unter Einstellungen - Systemeinstellungen die Sichtweite wage/klar festlegen. In Foundry 0.7.10 und DSA 1.4.3 wurde das beim Importieren von Akteueren aus den Kompendien auch übernommen. 
In Foundry 0.8.6 und DSA 2.0.0 (Beta) wird das immer durch die Standards 20/10 nach dem Import überschrieben unabhängig von meiner Einstellung unter Systemeinstellungen. 

**To Reproduce**
1. Systemeinstellungen - Sichtweite anpassen.
2. Akteur aus dem Kompendium importieren.
3. Sichtweite kontrollieren.

**Expected behavior**
Es wäre gut, wenn die Systemeinstellungen für alle Akteuere gleich gelten. Wie in Foundry 0.7.10.

**Comment by Plushtoast** [comment]
Joa, aber das gilt dann für alle Actors oder? Ich habs noch nich ausprobiert. 
Die DSA Einstellung ist nur für Helden/Charaktere. Deswegen ist das überhaupt noch drin.

**Comment by vt-tom** [comment]
Also in 1.4.3 übernimmt er das bei allen Akteuren. Egal was ich aus dem Kompendium ziehen. Bei 2.0.0 ignoriert er meine Einstellungen komplett wenn ich was aus dem Kompendium hole. Erstelle ich neue Akteuere, dann klappt es bei allen Typen.

**Comment by Plushtoast** [comment]
Tjo würde sagen, die Kompendium viecher haben schon eine Einstellung und die wird nicht überschrieben.
Ist evtl von Foundry nicht konsequent durchgeführt oder ein Bug.
Ich mach da nix.

**Comment by vt-tom** [comment]
Alles klar, kein Thema. Ich muss mich dann ja auch nur n bisschen umstellen ist ja eigentlich kein Thema. Danke trotzdem.
