### ISSUE TITLE
Effekte auch auf Status wie Schmerz oder Belastung anwendbar machen

### ISSUE THREAD

**Issue by Micha-Mo** [Plushtoast/dsa5-foundryVTT#412]
Wir haben einen Magier in der Gruppe der ein Artefakt mit dem Zauber "Schmerz lindern" herstellen will. Über Effekte eines Gegenstands gibt es allerdings keine Möglichkeit in die Schmerzberechnung einzugreifen. 

Über Effekte bei Items etc. die Möglichkeit hinzufügen Statuseffekte zu beeinflussen.
Also eine ähnliche Funktion wie beim Vorteil "Zäher Hund" jedoch über den Effekt eines Gegenstands.

**Comment by Plushtoast** [comment]
In Version 2.0.1 kann man Artefakte herstellen.
Der Zauber Schmerzen Lindern ist mit dem korrekten Macro in Magie 1 hinterlegt.
