### ISSUE TITLE
Patzertabelle für Zaubersprüche und Liturgien noch im System hinterlegen

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#413]
so wie auch schon die Patzertabellen für AT und PA und FK

**Comment by Plushtoast** [comment]
Sind drin.
/tables im Chat eingeben oder Patzer würfeln.

![grafik](https://user-images.githubusercontent.com/44941845/120685634-54b6a700-c4a0-11eb-9ce8-bb2863fffe31.png)
