### ISSUE TITLE
Roll for self-control @pain IV

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#421]
When you reach pain level 4, you become unconscious automatically.

According to the basic rules, you have to roll a check for self-control (stay conscious) -4. 
Should you succeed, you keep pain IV but stay conscious.

It would be nice if this check would be rolled automatically with a info to the chat and the status dependent on the result.
For special abilites not covered by the basic rules, it would be cool when one could change the roll in the chat output afterwards (same behaviour as with other rolls already).

**Comment by Plushtoast** [comment]
I think for some people an automatic check is not desired. But a chat message could appear with a roll button.

**Comment by mckee14** [comment]
editet long answer.

yeah, chat message would be nice

**Comment by Plushtoast** [comment]
Can you point me to the rules text location?

**Comment by mckee14** [comment]
https://www.ulisses-regelwiki.de/Sta_Schmerz.html


Plushtoast ***@***.***> schrieb am Sa., 4. Dez. 2021, 15:47:
