### ISSUE TITLE
Default-Token-Settings von Foundry wird nicht auf die Kreaturen übernommen.

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#423]
**Describe the bug**
Die Default-Token-Settings auf Foundry 0.86 werden nicht auf Wesen überragen, die man frisch aus der Bibliothek zieht.

**To Reproduce**
Stelle die Default-Token-Settings Display Name und Display Bars jeweils auf "Hovered by Anyone"
Öffne die Bibliothek und ziehe z.B. einen Baumdrachen auf die Map. Die Einstellung von Foundry wird ignoriert.

**Expected behavior**
Die Foundry-Einstellungen sollten die DSA-Default-Einstellungen stechen und überschreiben.

**Comment by tomsaath** [comment]
ist dieses Problem nicht vielleicht mit #410 verwandt?

**Comment by Albinosheep** [comment]
Ich habe auf 2.0.3 geupdatet und die Funktion erneut ausprobiert. Leider werden die default-Token-Settings bei mir nicht angewandt.

**Comment by Plushtoast** [comment]
Tjoa, DSA setzt ein einziges mal die bisheringen Einstellungen in den neuen Settings. Das wars dann aber auch.
Vermutlich sind die Einstellungen in den Kompendien jetzt schon vorbelegt wie ich sie eben generiert habe.
Kann sein, dass Foundry das beim nächsten generieren nicht mehr mitspeichert, weil nicht festgelegt. Aber vielleicht auch doch.
Ich seh hier nichts mehr was ich machen kann oder will.

**Comment by Albinosheep** [comment]
OK also wenn ich es richtig verstehe, ist das aber seitens Foundry wohl so beabsichtigt, oder?
Wenn ein Modul Settings vorgibt, bleiben sie bestehen?
Ansonsten würde ich das Verhalten bei Foundry mal als bug melden, vielleicht können Sie ja noch was umstellen (nämlich dass default sticht oder dass man einstellen kann "Modul/Kompendium-Settings"?

**Comment by Albinosheep** [comment]
Also kann es auch an Foundry liegen? Lohnt es sich, dass ich es dort melde? 
Ich kann das leider gar nicht beurteilen. xD

**Comment by Plushtoast** [comment]
Nein, lohnt sich nicht.
Es funktioniert. Nur wenn die Kreaturen schon vordefiniert wurden, wie in diesem Fall durch Einstellungen beim generieren, dann wird die neue foundry Einstellung überschrieben.

**Comment by Albinosheep** [comment]
Lieber Plushtoast,
ich weiß nicht warum, aber inzwischen nehmen Wesen aus der Bibliothek die Default-Token-Configuration an.
Nur die Token Disposition wird nicht übernommen.
War das eine Einstellung deinerseits die zu der Änderung beigetragen hat, oder Foundryseitig? 
Falls es von dir ausging wäre es cool, wenn du das ggf. noch für die Token Disposition freischalten könntest. :-)

**Comment by Plushtoast** [comment]
Token disposition?

**Comment by mckee14** [comment]
![grafik](https://user-images.githubusercontent.com/62849695/128595407-3b21be28-8ebb-4f62-86c6-a1620e8a427f.png)
