### ISSUE TITLE
0.8.6 error with new install / world

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#424]
Installed Foundry 0.8.6 fresh, installed DSA system, then all the modules (except starterbox).
Created a new world, first login shows error: "ENOENT: no such file or directory, open '/data/Data/systems/dsa5/packs/skillsen.db~'"

It was vanished too quickly, so I can only provide console screenshot, but it was visible in the GUI.

I had the same issue once when setting up the german world. When restarting, the error is gone and it doesn't break anything for what I saw.

Bonus Info: This happens BEFORE you choose the default language in the pop up window. And all the modules are still de-activated in the settings menu.

![grafik](https://user-images.githubusercontent.com/62849695/120893663-bdbf2b80-c614-11eb-86c2-91291472891b.png)

**Comment by Plushtoast** [comment]
This is a foundry problem, which is getting reported all over the place.
Nothing to do with TDE.

Restarting usually fixes this. Also some suggest this will help:

Try launching Foundry as admin (right-click the exe, Run as Administrator), load your world, open up all the SRD compendiums, and let it sit for like 5 minutes. Then quit, and re-launch normally

**Comment by Plushtoast** [comment]
Foundry is now working on this.
