### ISSUE TITLE
node server crash while search for items to add on character sheet, only happens when the world is running.

### ISSUE THREAD

**Issue by Talaren** [Plushtoast/dsa5-foundryVTT#428]
**Describe the bug**
the node server crash when the world is active and load the images from the 'Bibliothek' search.
when i kill and restart the server and scroll in the client i can load all images without errors.
important! only happen with the linux node server, windows server all fine

**To Reproduce**
Install the DSA5 system + Premium modules
Create new world
Start new world
Create new Actor
Show 'Bibliothek' and search, the first search is ok, when you search for different item, the server crash on second+ search

**Expected behavior**
the server not crash
i must kill the server with signal 9

**Server:**
Debian Server 10.9
Running on Node.js - Version 16.3.0
Foundry Virtual Tabletop - Version 0.8.6

**Comment by Plushtoast** [comment]
Most likely your node instance did run out of memory.

You should not import everything in your world. Instead use all items from the compendiums.
If you were using your world for a longer time, make sure to remove the chatlog from time to time.
Also with the arrival of the journal browser you do not have to import journals anymore and you should delete already imported rulebooks.

Moreover if you haven't done so yet, you might want to create a swap file to extend your memory for your server.

**Comment by Talaren** [comment]
![Screenshot 2021-06-05 212915](https://user-images.githubusercontent.com/3872571/120903234-45249300-c645-11eb-8f3d-7c31cc5cb75e.jpg)
server memory is ok, chatlog is empty, i use the journal browser and drop the items direct to the character sheet not import.
will check the memory settings.
add "--max-old-space-size=8192" to the start parameter
![Screenshot 2021-06-05 214139](https://user-images.githubusercontent.com/3872571/120903521-d5170c80-c646-11eb-9eac-adc89587b680.jpg)
server crash also, have 8GB Swap-Space

**Comment by Talaren** [comment]
when i open the compedium the images load perfect, no problem, but when i open the journal browser and search for items the server crash after two or three seach strings i tried also 25GB, but the server crash also. :(

**Comment by Plushtoast** [comment]
That's a lot of memory. You might want to look into the logs in your foundry data folder.

**Comment by Talaren** [comment]
Es scheint vermutlich mit dem neuen Journal Browser zusammen zu hängen?
Folgender Ablauf um es jedes Mal zum crash zu bekommen:
Starte die Welt (es gibt darin nur einen neuen Actor einen Held den ich gerade nachbaue, ansonsten ist da absolut nichts anderes darin)
Öffne den Charakter und suche das erste Item, füge es hinzu (Ausrüstung)
Suche das zweite Item, wenn ich mehr Arbeitsspeicher gebe hat er das dann unter Umständen noch geschafft, ist aber schon sehr langsam, füge das dann hinzu und beim dritten Item ist endgültig Schluss und der Server crasht und reagiert nicht mehr.

debug.log
{"message":"Vended World data to User [VtmtGj7HK1E85ABM] in 300ms","level":"info","timestamp":"2021-06-05 22:22:27"}
{"message":"FoundryVTT | Created Item with id [udz9yPISiXNAwC4X] in parent Actor [MSeEY7qaPWpD9DQW]","level":"info","timestamp":"2021-06-05 22:26:50"}

error.log ist leer.

**Comment by Plushtoast** [comment]
Vielleicht ist die client side auch das Problem, weil sie irgendeine zu lang dauernde Anfrage macht.

Versuch mal das hier zu ersetzen: 
https://github.com/Plushtoast/dsa5-foundryVTT/blob/foundry08/modules/system/itemlibrary.js

Das sollte client side weniger Speicher verbrauchen.
Aber das scheint nicht das Problem zu sein.

Vielleicht ist node 16 problematisch. Offiziel wurde wohl nur mit 14 getestet. Node 16 "sollte" funktionieren, aber ka.

**Comment by Talaren** [comment]
Bekomme den Server gut ausgelastet, in dem ich einfach versuche so schnell wie möglich im Kompendium alle Einträge öffne.
Dann sehe ich im Network das er schon länger braucht, aber der Journal Browser ruft die noch viel schneller nacheinander auf, aber das sollte der doch verkraften?

Running on Node.js - Version 14.17.0 den Nodeserver neu installiert und die 14er Version.
https://raw.githubusercontent.com/Plushtoast/dsa5-foundryVTT/foundry08/modules/system/itemlibrary.js ersetzt und dann gestartet, hat aber leider auch nichts gebracht.

**Comment by Plushtoast** [comment]
Ggf würde noch helfen einen nginx davor zu schalten. Wir spielen auf nem 2gb RAM digitalocean droplet ohne Probleme.
Ansonsten mal im foundry discord nachfragen. Weiß nicht ob das unbedingt ein DSA Thema ist.

**Comment by Plushtoast** [comment]
Die wissen wahrscheinlich auch eher wo man Fehlermeldungen auslesen könnte.

**Comment by Talaren** [comment]
Vielen Dank für den Tip, habe nochmals den Apache Proxy neu eingerichtet und darüber geht es.
Vielen Dank für deine Hilfe.
Vermutlich ein Bug in Foundry stimme ich zu.

**Comment by Plushtoast** [comment]
Hier dürfte übrigens der Grund dafür liegen:
https://gitlab.com/foundrynet/foundryvtt/-/issues/5267
