### ISSUE TITLE
Aventurische Rüstkammer fehlende Gegenstände

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#431]
Hi,
im Rüskammer Modul, scheinen die Waffen und co. zu fehlen, die aus dem Kompedium sind, aber trotzdem mit werten (und neuen Vor-Nachteilen) in der Rüstkammer gelistet sind.
Ist das so gewollt?

**Comment by Plushtoast** [comment]
welche sollen das sein

**Comment by Qowy** [comment]
Pailos (2H) Zum beispiel

**Comment by Plushtoast** [comment]
Tendenziell ist das so gewollt. Sonst noch was?
Mal sehen, ob sich da was machen lässt.

**Comment by Qowy** [comment]
Die 8 Waffen S. 139 - 140 in ARK1 "Waffen des Aventurischen Kompendiums"

**Comment by Plushtoast** [comment]
Werden das nicht mehr ändern.
