### ISSUE TITLE
Fehler: Statuseffekte hinzufügen

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#432]
Wenn ich im Charaktersheet auf + bei den Liturgiehen gehe und eine so erstellte Liturgie dann öffne, bekomme ich einen Fehler in der Konsole, wenn ich auf das + bei Statuseffekte drücke

"Error: Managing embedded Documents which are not direct descendants of a primary Document is un-supported at this time"

Wenn ich es dann in die Item Sidebar ziehe (oder direkt dort erstelle) und von dort öffne, geht es.

**Comment by Plushtoast** [comment]
Jup Foundry untersützt das nicht im Moment. Geht nur über die Sidebar.
