### ISSUE TITLE
Armatrutz Beschreibung

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#435]
In der Beschreibung des Zaubers Armatrutz, also dem Ding was in den Chat gesendet wird, fehlt der Hinweis auf die Unterschiedlichen Stufen und daraus resultierende unterschiedliche AsP-Kosten. Wäre cool, wenn das ergänzt werden könnte.

**Comment by Murm3lt13r** [comment]
Ergänzt
