### ISSUE TITLE
Migration von Zaubersprüchen funktioniert nicht korrekt

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#437]
**Describe the bug**
Wenn ich über "Akteur konfigurieren" Zauber migrieren verwende, scheint das nicht zu funktionieren.

**To Reproduce**
1. Gehe in ein SC-Actorsheet.
2. Ändere eine Zauberbeschreibung händisch; z.B. indem du "test" dazuschreibst.
3. Öffne im gleichen Sheet "Akteur konfigurieren".
4. Wähle "Zauber migrieren" und bestätige.
5. Öffne den Zauber - es hat sich nichts verändert.

**Expected behavior**
Der bestehende Zauber wird wieder auf die offiziellen Vorgaben geändert.

**Additional context**
Ich bin darauf gestoßen, weil ich die mehrfach-Effekte, die sich in einer alten Version bei den Zaubern eingeschlichen hatten, damit bereinigen wollte. In der damaligen Version hatte es ordnungsgemäß geklappt. In der jetzigen wird es nicht mehr geändert.
Wenn ich dagegen händisch den Zauber lösche und dann wieder einspiele, passt es.
Für Sonderfertigkeiten/Vor-/Nachteile bzw. Kampftechniken habe ich es nicht eigenständig getestet.

**Comment by Plushtoast** [comment]
Es werden nur die Effekte aktualisiert. Sonst Nichts.
Manche Leute haben hier sehr viel arbeit in zusätzliche Erweiterungen wie zauberformeln oder sonstiges zeug gesteckt, das ich nicht überschreiben will.
Steht aber auch dran, was migriert wird.

**Comment by Albinosheep** [comment]
OK, die Effekte werden bei mir leider auch nicht korrekt aktualisiert - darum bin ich überhaupt darauf gekommen. Die Mehrfacheffekte bleiben erhalten.

**Comment by Albinosheep** [comment]
Ich habe es gerade noch einmal geprüft, bekomme es leider nicht hin.

**Comment by Plushtoast** [comment]
Ja Foundry mag das nicht. Es ist quasi nicht erlaubt. Aber ich hab einen anderen Workaround im nächsten Patch.

**Comment by Albinosheep** [comment]
Super, danke lieber Plushtoast! :-)
