### ISSUE TITLE
[8.6 - 2.0.3] Zauber Armatrutz - Effekt (Ziel) klappt nicht.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#438]
**Describe the bug**
Wenn ich den Zauber Armatrutz anwende, und Effekt (Ziel) anklicke, passiert auf den Oberfläche nichts. In der Console kommt es zu einer Warnmeldung:
`Unable to apply advanced effect`
`yntaxError: await is only valid in async functions and the top level bodies of modules
    at Function.applyAdvancedFunction (active_effects.js:65)
    at Function._applyEffect (dice-dsa5.js:1180)`

**To Reproduce**
1. Ziel markieren 
2. Armatrutz würfeln
3. Bei gelungener Probe: Effekt (Ziel) anwenden

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/121300821-9fe51580-c8f7-11eb-860c-6822fdfba7fd.png)

**Desktop (please complete the following information):**
- System 2.0.3
- Foundry 0.8.6

**Comment by mckee14** [comment]
EN, 0.8.6, Core 2.0.3

Tested and confirmed. I even get the chat messages confirming the transfer, but console shows errors and no status is applied to chars.

First error is applied to self, second error is applied to target

![grafik](https://user-images.githubusercontent.com/62849695/121323141-dd559d00-c90f-11eb-940d-00e264e218a7.png)
![grafik](https://user-images.githubusercontent.com/62849695/121323196-e8a8c880-c90f-11eb-95f8-fc44065f5dba.png)
