### ISSUE TITLE
Irinja: encumbered

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#439]
Poor girl Irinja (dsa5-core characters) has an archaic labor in her items list.

Thats 30 stones, so she starts with encumbrance 4 & incapacitated.
Maybe change the weight to 0 in this case? I dont think she has it on her back...

**Comment by Plushtoast** [comment]
Yes, that's not a bug. Keeping different versions for items is already annoying enough given TDE has every item in every book.
Won't change this.

**Comment by mckee14** [comment]
OK
Is there a way to have it nested in a "bag" and not equipped, on a per-char level? That would solve it, too (in a way).

On the other hand, it is what it is :)
