### ISSUE TITLE
Neue Tokenbar unter 0.8.X funktioniert mit Card Support (Unofficial) nicht

### ISSUE THREAD

**Issue by Algor0113** [Plushtoast/dsa5-foundryVTT#447]
**Describe the bug**
Sofern das Modul "Card Support (Unofficial)" aktiv ist, funktioniert die neue Popup-Tokenbar nicht. 

**To Reproduce**
1. Aktiviere das Modul "Card Support (Unofficial)"
2. Keine Leiste da, wenn man ein TOken anklickt.

**Expected behavior**
Es wäre schön, wenn beide Elemente Koexistieren könnten :)

**Desktop (please complete the following information):**
 - OS: Windows 10/Forge VTT (beides funktioniert nicht)
 - Chrome
 - Version 2.0.3

**Comment by Plushtoast** [comment]
Hm, ich fürchte da gibt es im Moment keine gute Lösung.

**Comment by Plushtoast** [comment]
Würde mal sagen mit der baldigen v9 Version is das hier gelöst bzw durch ein anderes Problem abgelöst.
