### ISSUE TITLE
Optionen, die Standardverhalten ändern, sollten standardmäßig deaktiviert sein

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#450]
Ich wurde jetzt schon mehrmals durch neu hinzugekommene Optionen überrascht, die Standardverhalten von Foundry oder Regeln das Grundregelwerkes veränderten.

Es geht da um die Standard-Sichtwerte, die jedem Spieler in völliger Dunkelheit Sicht im Wert eines FlimFlam QS5 geben. Zum anderen werden die Zustandsmarker auf NSC-Token für Spieler ausgeblendet.

Das mag für manche Spieler die präferierte Option sein. Aber es sollte genau das sein: eine Option, die man bei Bedarf anschalten kann. Aktuell ist das für alle standardmäßig aktiviert. Das sorgt für Verwirrung.

Daher bitte ich, solche Standardverhalten-ändernden Optionen standardmäßig deaktiviert zu lassen.

**Comment by Plushtoast** [comment]
Die Optionen sind so gesetzt, dass sie für Neulinge am ehesten dem Erwartungswert entsprechen.
Mit der Weiterentwicklung von Foundry und den DSA Modulen werden manchmal manche Einstellungen allerdings obsolet oder schlichtweg kontraproduktiv oder unsinnig.
Z.b. die Sichtfeldeinstellungen sind mit 0.8 aus DSA komplett verschwunden.

Das bleibt ein best guess und rein "willkürlich".

**Comment by Plushtoast** [comment]
Die andere Möglichkeit wäre es nicht mehr weiterzuentwickeln.
Wenn sich Dinge ändern, muss man eben anpassen.

**Comment by Plushtoast** [comment]
Und wir hatten die Diskussion schon mal.
Das ist die Geschichte warums 10000 Wiki Buttons braucht. Die Leute fragen immer wieder das gleiche Zeug und das lässt sich nur durch Standardeinstellungen abfangen.
Darunter fällt auch: Wieso sieht mein Token nichts?
Wieso sehen die Spieler wieviel Schmerz der Feind hat usw usf

Die Standardeinstellungen dienen meinem Seelenfrieden.

**Comment by mckee14** [comment]
Standardeinstellungen sind OK finde ich, und das problem wurde schon besprochen.

Hilfreich wäre es, wenn man nach einem system update einen hinweis bekommt (chat/popup):
 - release notes oder
 - link auf das github projekt mit den enthaltenen punkten oder
 - genereller hinweis, die einstellungen zu überprüfen
 
 @Danii0206 Als Nutzer kann ich dir nachfühlen. Aus Entwicklersicht ist es aber ein grosses NoNo, dass man features entwickelt und diese dann quasi im standard deaktiviert lässt. Da die meisten Nutzer faul sind und weder patchnotes noch handbücher lesen, wird der grösste teil dann niemals darauf stossen und lässt es ungenutzt liegen. das schmälert die UX und mindert den cost/benefit faktor immens.

**Comment by Danii0206** [comment]
Entschuldigt bitte, falls ich da einen wunden Punkt erwischt habe. Natürlich habt ihr Recht, dass es bei einer Weiterentwicklung immer Neuerungen geben wird. Bei neuen Features ist es auch logisch, dass die für alle aktiviert werden. 

Mir geht es hier nur um die Features, die es schon in Foundry gibt und bei denen sich durch das DSA-Modul das Verhalten dieser Features ändert. Insbesondere dann, wenn sie nur die Spieler betreffen und man als Spielleiter gar nicht direkt mitbekommt, dass sich was geändert hat.

Wenn man diese Einstellungen an die Neulinge anpasst, würde ich mir für alle alten Hasen eine deutlichere Kommunikation solcher Änderungen wünschen. Dann können wir uns auch anpassen. Sonst sitzt man da und fragt sich, warum Foundry schon wieder neue Bugs hat. Auch keine gute UX. Bin nu mal leider kein Hellsichtmagier. ;)

**Comment by Plushtoast** [comment]
Also in diesem Fall kommt noch dazu,dass es das Standardverhaltrn bzw Funktion in foundry gar nicht gab.
Am Tisch sagt man den Spielern ja auch nicht unbedingt wieviel Schmerz die Gegner haben.
Aber die info kommt ins changelog und das changelog wird auch exponierter positioniert. Zb durch tsaaths neuen YouTube Channel.

**Comment by Danii0206** [comment]
Danke dir / euch!
