### ISSUE TITLE
Apply damage from botches via chat

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#453]
Currenty, you can't apply SP from botches. 
![grafik](https://user-images.githubusercontent.com/62849695/122521305-f4ce0d80-d014-11eb-9c45-ff1884086300.png)

It would be nice to do so, like it's implemented for combat damage already.
(Sidenote: botches aren't allowed to be re-rolled with FatePoints according to rules)

**Comment by Plushtoast** [comment]
Are you sure about the reroll? I thought someone told me that it's possible and that's why I didn't already restrict this.

**Comment by scheribold** [comment]
Nur mit dem Vorteil Waffenbegabung kann der Bestätigungswurf wiederholt werden (RW Seite 169). Patzer können nicht mittels Einsatz von SchiPs wiederholt werden. Dies gilt für Talente und Angriff, Parade etc. (RW Seite 29).

**Comment by mckee14** [comment]
Ich weiss, steht ja auch so da als hinweis, weil die option "wurf
wiederholen" angezeigt wird, obwohl man das nicht dürfte.

Das hauptanliegen ist aber, die SP aus patzer anwenden zu können. Gefühlt
meinte ich auch, dass das schon mal ging, bin aber nicht sicher.

scheribold ***@***.***> schrieb am Fr., 18. Juni 2021, 13:09:
