### ISSUE TITLE
Fehlermeldung bei der Migration von Kampftechniken

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#454]
**Describe the bug**
Nutzt man die Funktion "Kampftechniken migrieren" erscheint eine Fehlermeldung. Die genaue Fehlermeldung variiert von Charakter zu Charakter. Die Auswirkungen kann ich nicht beurteilen.

Beispielsweise Fehlermeldung:
![Bug Kampftechnik](https://user-images.githubusercontent.com/41292141/122621600-48347000-d096-11eb-9d31-a23288be9821.jpg)

**To Reproduce**
Öffne einen Akteur
Gehe auf "Akteur konfigurieren"
Gehe auf "Kampftechniken migrieren" 
Es erscheint die Fehlermeldung

**Additional context**
Foundry 0.87
DSA Game-System 2.0.4
Der Bug kam mit dem Fix des Tickets #437.

**Comment by Plushtoast** [comment]
Keine Auswirkung.
Da foundry das aktualisieren von active effects in Akteuren nicht erlaubt, muss das entsprechende item gelöscht und neu hinzugefügt werden. Die waffen haben dann kurzzeitig keine Kampftechnik

**Comment by mckee14** [comment]
Kannst Du dieses Issue anpinnen? Bin da nämlich auch drüber gestolpert, sicher gut wenn man das sichtbar hat.

**Comment by Plushtoast** [comment]
Hab eine Möglichkeit gefunden die Meldung zu verstecken im nächsten Patch
