### ISSUE TITLE
[8.7 - 2.0.4] Verbrauchsgegenstand: Effekt ohne Zeit lässt sich nicht manuell entfernen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#457]
**Describe the bug**
Wenn ich einen Verbrauchsgegenstand (Beispiel: Stärketrank) mit einem Effekt benutze, dann kann dieser nicht manuell aus dem Statustab entfernt werden. Ich muss erst den Gegenstand aus dem Actor löschen damit der Effekt verschwindet. Das ist aber ungünstig, sollte der Char mehrere dieser Items haben.

**To Reproduce**
1. Gegenstand Typ Alchemie anlegen
2. Effekt Bsp. Körperkraft +2
3. Item verbrauchen
4. Effekt versuchen unter Status zu entfernen

**Expected behavior**
Unabhängig davon ob ich die Dauer des Effekts verwende oder nicht, möchte ich ohne den Gegenstand aus dem Ausrüstungsmenü zu entfernen, den Effekt löschen können.
Er kann zwar deaktiviert werden, wird dann aber nicht wieder aktiviert, wenn ich den Gegenstand erneut einsetze.

**Comment by Plushtoast** [comment]
Hm geht bei mir. Löscht du den Effekt mit rechter Maustaste?
