### ISSUE TITLE
Doppelte Zustände - 0.8.7.

### ISSUE THREAD

**Issue by Meckerdrache** [Plushtoast/dsa5-foundryVTT#458]
Im Kampf werden die Zustände Schmerz und Handlungsunfähigkeit zweimal vergeben, also nicht zwei Stufen, sondern zwei separate Zustände.

 - OS: Windows
 - Browser Firefox 89.0

**Comment by Plushtoast** [comment]
Das dürfte nur passieren, wenn du Schaden am Token HUD anwendest. Überall sonst nicht, korrekt?

**Comment by mckee14** [comment]
Ja, bestätige (EN 0.8.7): Am Token abziehen gibt den Status mehrfacht, über Chat oder Charsheet gibt es den status nur einfach.
