### ISSUE TITLE
Rüstungen ziehen falsche Werte bei INI und GS ab

### ISSUE THREAD

**Issue by Cyda76** [Plushtoast/dsa5-foundryVTT#459]
Diverse Rüstungen ziehen mehr  INI und GS Punkte ab, als im Grundregelwerk Seite 374beschrieben.

zB.  
Stoffrüstung, Gambeson und Tuchrüstung: -1 INI, -1GS  (laut Regelwerk nichts)
Kettenrüstung: -2 INI, -2GS (laut Regelwerk nichts)
Plattenrüstung: -3INI, -3GS (laut Regelwerk nichts)

möglicherweise stimmen diese Werte auch bei anderen Rüstungsteilen nicht.

**Comment by CommanderAlex98** [comment]
Schuppenrüstung zieht gar keine INI und GS ab, beim Hinzufügen erhält der Charakter den Status Handlungsunfähig obwohl er nur eine Belastung hat (mit Belastungsgewöhnung I getestet)

**Comment by Plushtoast** [comment]
Ich vermute du bekommst Handlungsunfägi eher beim Ausziehen, weil da dann das Gewicht zählt.

**Comment by Plushtoast** [comment]
Also soweit ich das sehen kann, ist hier alles in Ordnung.
Die Abzüge entstehen durch die Belastungsstufe. Stoffrüstung hat z.b. Belastungsstufe 1. Das macht ohne Rüstungsgewöhnung -1 INI und -1 GS durch den Zustand Belastung (Seite 32).

**Comment by Cyda76** [comment]
Dann müsste demnach aber die Lederrüstung jeweils 2 Abzug auf INI und GS haben. Also einmal für die BE 1 und einmal die Abzüge der Lederrüstung. Und das hat sie aber im VTT nicht. Es addiert die beiden Werte scheinbar nicht, da es sich bei der Schuppenrüstung genau so verhält. 
Diese müsste ja korrekterweise jeweils 3 Abzug haben, VTT gibt aber nur 2. Laut den Eigenschaftswerten im Charakterbogen....

heißt also, dass man aktuell mit Stoff/Tuchrüstung zwar gleich viel Abzüge wie mit Lederrüstung/Lederharnisch hat, aber 1 Punkt weniger RS.

**Comment by Plushtoast** [comment]
Das ist noch ein anderes Problem siehe #466 
Die Werte sind zumindest korrekt hinterlegt.

**Comment by Nellkir** [comment]
Also früher wurden die Effekte von den Rüstungen (sprich -1GS, -1 INI) automatisch als Transferierte Effekte übertragen.
Das ist zumindest beim Schuppenpanzer nicht mehr der Fall.
![image](https://user-images.githubusercontent.com/82062265/124598566-0c0a5900-de65-11eb-8737-27eb6ea9b2bf.png)

Andere Rüstungen habe ich noch nicht geprüft.

**Comment by Nellkir** [comment]
Lederrüstungen ebenfalls nicht. Und ich denke mal, alle anderen Gegenstände auch, die früher einen Statuseffekt aus der Gegenstandseffektleiste automatisch transferiert haben.

Muss man die nun alle händisch als eigenen Statuseffekt nachjustieren?

**Comment by Plushtoast** [comment]
Auf den Patch warten. Siehe #466
