### ISSUE TITLE
Fight - defense value after crit

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#46]
**Describe the bug**
v1.1
When you hit a critical attack, the text states that the enemies defense is halved.
The tooltip text indicates that it rolls agains the original value, not the halved value.

**To Reproduce**

1. Start Combat via combat tracker, roll INI
2. Declare a token as target
3. Attack with the token according to combat tracker
4. Hit a critical confirmed hit
5. Use Parade with the token declard as target, chat shows it rolls against original value (in this case 8, for the ork with his säbel)

**Expected behavior**
Roll against the halved value, or change the tooltip text if that is the problem.

**Screenshots**
![krit](https://user-images.githubusercontent.com/62849695/107652768-37579600-6c81-11eb-8906-82073d5e8c91.jpg)

**Desktop (please complete the following information):**
win10

Sidenote:
The presented information for rolls in the chat are wonderful, but the damage rolls only show the dice roll values. technically, this makes sense, but for a user it's a bit confusing - you see a rolled 2 and the crit damage ends up 20.
Maybe change it later on and separate the attack roll and the damage roll, and in the damage roll print the dice roll plus weapon base damage plus additional modifier (schadensschwelle, sonderfertigkeiten etc). very low priority.

**Comment by Plushtoast** [comment]
Automatically altering the defense roll is currently not possible. You have to include modifiers on the defense manually. It is not trivial to implement nd will be a feature for future versions.
The modifiers on the damage will be shown in detail probably on the next patch. Those modifiers will include damage alterations caused by special abilities like "Wuchtschlag" too.
Since DSA is very complicated and there is an infinite amount of modifiers, not everything will be considered automatically...also not in the near future.

**Comment by mckee14** [comment]
OK, so maybe alter the Text after a crit so the user knows that he must
modify the defense roll.

I worked a bit with DSA sheets for R20, and i know it is a pain with 1000
cases and specials. Not everything must work automatically, but it helps
massively if you KNOW wheter it does or not.

Also, documentation about implementing own stuff helps a LOT to get users
on board, ending up with good feedback and ideas from them (and many dumb
ones, too hehe)

Plushtoast <notifications@github.com> schrieb am Do., 11. Feb. 2021, 16:56:

**Comment by Plushtoast** [comment]
Ok, I changed the chatmessage to reflect that the user has to do something.
Also I added a tooltip on the damage to show what parts have been included in the calculation.

But this will be overhauled/improved anyway soon, to enable modifiers for the opposed roll and to edit the damage values.

Thanks for your input.
