### ISSUE TITLE
Paradewert von Leiteigenschaften

### ISSUE THREAD

**Issue by Ben528491** [Plushtoast/dsa5-foundryVTT#460]
Wird eine andere Leiteigenschaft ausgewählt, als in den Regeln angegeben (zum Beispiel Körperkraft statt Gewandheit für Dolche), so wird zwar die TP richtig berechnet, aber nicht der Paradewert (die Boni ab Attributswert von 11, 14, 17, etc.).

**Comment by Plushtoast** [comment]
Für den Paradewert wird die Leiteigenschaft der Kampftechnik verwendet.
Für den Schaden wird die Leiteigenschaft der Waffe verwendet.
Müsste stimmen.

**Comment by Ben528491** [comment]
Auszug aus dem Regelwiki: "Die Leiteigenschaft der jeweiligen Kampftechnik beeinflusst sowohl den Paradewert als auch den Schadensbonus".
Nachzulesen hier https://ulisses-regelwiki.de/kampftechniken.html
Für mich sieht es daher danach aus, als gäbe es nur eine Leiteigenschaft der Kampftechnik und keine Leiteigenschaft von der individuellen Waffe.

**Comment by Plushtoast** [comment]
Wozu ist dann die Angabe der Leiteigenschaft bei Waffen?

**Comment by mckee14** [comment]
Für die Berechnung der Schadensschwelle. Macht irgendwie null Sinn, ich schau mal ob ich da heute mehr / genauere Infos dazu finde...

EDIT:
Also, gem. GRW wird tatsächlich der Schadensbonus UND der Paradewert aus dem gleichen Wert abgeleitet. Man kann sich bei gewissen Waffen entscheiden, entweder GE oder KK als LE zu verwenden, dann werden aber beide Werte (Bonusschaden und PA) daraus abgeleitet.

Die Kampfwerte für eine Waffe sind also (Kampfwert der Kampftechnik) + (Boni aus der Leiteigenschaft, die in der Waffe ausgewählt wurde) + (Bonus/Malus der Waffe selbst)

**Comment by Plushtoast** [comment]
Das würde heißen man kann den Leitwert aus der Waffe komplett entfernen?

Es wird btw momentan automatisch der höhere Wert bei 2 Werten verwendet.

**Comment by mckee14** [comment]
Man kann ja pro Waffe die Leiteigenschaft wählen, mit der man sie führen möchte. Daher würde ich die LE schon in der Waffe lassen.
Und für Sonderfälle kann es ja auch sein, dass ein Superduperdolch mit KL geführt wird.

**Ich würde die Grundwerte** (so wie sie aktuell schon sind) **im Tab bei den Kampftalenten lassen:**
![grafik](https://user-images.githubusercontent.com/62849695/123145937-a3cb7880-d45d-11eb-9239-6e2fca1d3c72.png)

**Zusätzlich den Eintrag in der Waffe auch so lassen wie es ist.**

Ändern könnte man:
 - Für die Berechnung des Bonusschadens und des PA Werts wird immer die Leiteigenschaft aus der Waffe verwendet (Waffeneinstellung überschreibt Grundeinstellung aus dem Kampftalent)  
![grafik](https://user-images.githubusercontent.com/62849695/123146376-163c5880-d45e-11eb-8ed2-e82a5d4b3b92.png)

Dann stimmen die Werte für jede Waffe automatisch, auch wenn man Anpassungen in der Waffe vornimmt. Sogar dann, wenn man für Sonderfälle vom GRW Standard abweicht.

**Comment by Ben528491** [comment]
Genau das was mckee14 sagt:
Ich bin drauf gestoßen, weil ich ein ganz besonderes Bannschwert für meinen Magier bauen wollte, dass KL als Leiteigenschaft verwendet. Das ist schon gut so, dass man das in der Waffe ändern kann, sonst müsste ich für mein Vorhaben eine eigene Kampftechnik bauen.

**Comment by Plushtoast** [comment]
Hm das ist eine ziemlich umfangreiche Codeänderung. Muss warten.
