### ISSUE TITLE
"/w " funktioniert nicht

### ISSUE THREAD

**Issue by Niemand-001** [Plushtoast/dsa5-foundryVTT#461]
Das Whisperkommando "/w " funktioniert nicht.

Bei Eingabe von "/w " als Chatkommando erscheint das Auswahlmenü mit den Namen. Wird ein Name ausgewählt/angeklickt, verschwindet das Kommando und zeigt keine weitere Wirkung.
Das Kommando "/whisper [Name]" funktioniert.

![grafik](https://user-images.githubusercontent.com/83836835/123063424-ae5e2180-d40d-11eb-90c0-9aac4e74bdf7.png)

Win10 Pro
Chrome und Desktop-App
Foundry 0.8.7
DSA5 2.0.4
Ausschließlich DSA-Module aktiv

**Comment by Plushtoast** [comment]
Pfeiltasten Name wählen. Tab drücken. Kann man aber ggf noch verbessern.

**Comment by Niemand-001** [comment]
Ah, danke!
Da es optisch wie das Menü bei "/rq" aussieht, nahm ich an, dass auch hier ein Klick funktioniert.

Dann habe ich hier noch einen Verbesserungsvorschlag für die "irgendwann/vielleicht"-Liste: "Whisper" liefert foundryseitig bei der:dem Empfänger:in eine Nachricht, die sich nicht von einer "leuten" Nachricht unterscheidet. Es wäre klasse, wenn sich das "Flüstern" optisch irgendwie vom normalen Chat unterscheiden würde.
