### ISSUE TITLE
Hit points of spell Aeolito have no effect on target

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#468]
**Describe the bug**
A successful Aeolito does not reduce the health points of the target.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry version: 0.8.8
 - DSA system: 2.0.4

**Comment by Plushtoast** [comment]
The effect seems to have an error. The damage can be applied via right click on the results chatmessage (same as melee fights).
