### ISSUE TITLE
Shapeshifting does not change affected token

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#469]
**Describe the bug**
Shapeshifting does not change affected token in scene.

Error message on desktop and in console: "Required field "x" not present in TokenData"

**Screenshots**
![image](https://user-images.githubusercontent.com/85822812/123796000-eb7e5400-d8e4-11eb-97fa-5bd5663a24e7.png)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry version: 0.8.8
 - DSA system: 2.0.4

**Remarks**
I'm not sure if it's important but it might be worth to mention that the actor was converted from Foundry 0.7. to Foundry 0.8

**Comment by Plushtoast** [comment]
Was this an already transformed actor?

**Comment by Plushtoast** [comment]
Already transformed Tokens are problematic. Foundry 0.8 changed to much. The shapeshifting from 0.7. is very different. So your remark is probably right.
Does this error also occur if you start a new transformation?

**Comment by sirgawain111** [comment]
Tried shapeshifting in 0.8. the first time, but there seems to be an issue with the (self-created) creature I used for it. All works well when using a creature coming with one of the modules. Will try to figure it out.
