### ISSUE TITLE
issue with reducting spell costs

### ISSUE THREAD

**Issue by Gornoka** [Plushtoast/dsa5-foundryVTT#47]
**Describe the bug**
Reducing Spell costs increases spell costs 

**To Reproduce**

1. create spell
2. use spell
3. select "Kosten reduzieren -1"
4. Costs increase instead of reducing

**Expected behavior**
Costs reduce when costs are supposed to be reduced

**Screenshots**

**Desktop (please complete the following information):**

![vtt_test](https://user-images.githubusercontent.com/45569834/107689178-d04dd780-6ca8-11eb-91c2-4149f188c8a0.png)
![vtt_test2](https://user-images.githubusercontent.com/45569834/107689184-d17f0480-6ca8-11eb-9d2c-6b4bf106b22b.png)

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser Chrome
 - Version latest as of 11.02.2020

**Additional context**

**Comment by Plushtoast** [comment]
Thanks, will be fixed on the next patch (probably Sunday).

**Comment by Plushtoast** [comment]
Actually this is already fixed. Did you update the dsa5 system to version 1.1.0?

**Comment by Gornoka** [comment]
thnks for the quick fix
