### ISSUE TITLE
Status effects break NPCs

### ISSUE THREAD

**Issue by Verdemis** [Plushtoast/dsa5-foundryVTT#470]
**Describe the bug**
Wenn ich einen NPC einen Status verpassen, z. B. Schmerz, dann kann ich anschließend nicht mehr die Seite auf dem Charakterbogen wechseln, also z. B. auf Eigenschaften, Kampf usw.
Ebenso kann man die Buttons beim Token (rechtsklick) nicht mehr benutzen. Ich kann den Status dann entsprechend auch nicht mehr entfernen.

**To Reproduce**
Ich habe versucht einen eigenen Statuseffekt hinzufügen. Der Effekt wurde zwar hinzugefügt, aber ich bekam eine Fehlermeldung, die leider zu schnell weg war, als das ich sie lesen konnte. Nachdem ich den Status Effekt wieder entfernt habe trat das Problem auf, bei allen NPCs. Spielercharaktere sind davon scheinbar nicht betroffen. Ich hab auch mal alle Module deaktiviert, das Problem blieb aber bestehen. Wenn ich einen Token eines NPCs, der einen Status hat dann lösche, bekomme ich folgende Fehlermeldung:

"The key RjrqsGUeaQ4JrfPT does not exist in EmbeddedCollection Collection"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 89.0.2
 - Version: Foundry 8.8.0, DSA 2.0.4

**Comment by Plushtoast** [comment]
Prüfe ob alle deine Spieler die gleiche Sprache verwenden und die Sprache auch dem NPC entspricht.

Englisch und Deutsch sind nicht miteinander kompatibel.

**Comment by Verdemis** [comment]
Ich habe es bisher nur alleine getestet. Also Spieler waren bisher nicht beteiligt. Die Sprache ist auf Deutsch gestellt.

**Comment by Plushtoast** [comment]
Kann ich Zugriff auf die Welt bekommen?

**Comment by Verdemis** [comment]
Klar, wo kann ich dir den Zugang schicken?

**Comment by Plushtoast** [comment]
Falls du auf einem der TDE Discords bist, da bitte mal Huepfklotz anpingen.
https://discord.gg/foundryvtt

**Comment by Verdemis** [comment]
Alles klar das mache ich nachher. Ich muss jetzt leider erstmal kurz zum Arzt wegen Impfung. Ich melde mich im Anschluss sofort via Discord.

**Comment by Plushtoast** [comment]
Das Problem scheint im nächsten Patch schon gar nicht mehr zu bestehen.
