### ISSUE TITLE
Nach Anlegen eines NSCs kommt Endlosschleife

### ISSUE THREAD

**Issue by Florindel** [Plushtoast/dsa5-foundryVTT#471]
**Describe the bug**
Es kann kein NSC mit Foundry unter dem DSA Ruleset angelegt werden.

**To Reproduce**
Unter Actors:
1. Create
2. Type "Nichtspielercharakter"
3. beliebiger Name
4. klicke Create New Actor

**Expected behavior**
NSC kann erstellt werden

**Screenshots**

**Desktop (please complete the following information):**
   Chrome; NodeJS 14, Foundry 8.8

**Additional context**
Debug Log schreibt:
{"message":"FoundryVTT | Created ActiveEffect with id [2pCK4Ufw1l7DtHJE] in parent Actor [NyhJRlCT8M1trFYI]","level":"info","timestamp":"2021-06-29 21:55:50"}, wobei die EffectId sich jeweils immer ändert.

**Comment by Florindel** [comment]
Auch ein Downgrade auf Found 0.8.6 behebt das Problem nicht. Nach Anlegen eines NSC versucht das System hunderte von ActiveEffects auf den NSC zu legen, was zu einem komplett blockierten Foundry führt, was nur durch Abschiessen behoben werden kann. Das System ist bis zu einem Löschen aus der Actor-Datei komplett unbrauchbar!

**Comment by Plushtoast** [comment]
Sind alle Module deaktiviert? Kann ich Zugriff auf die Welt bekommen? Bist du auf einem der foundry tde discords?

**Comment by Florindel** [comment]
Welche Module genau sollen deaktiviert werden? Alle DSA-Module? Alle DSA-fremden Module? Okay, den Weg auf den Foundry Discord habe ich auch gefunden. Zugriff auf die Welt geht grundsätzlich, per PN kann ich eine IP kommunizieren.
Irgendetwas ist ganz komisch. Ich kann auch keine Actors mehr anklicken und die Bibliothek stürzt ab.
Alles seit dem Update auf 0.8.8

**Comment by Florindel** [comment]
Wenn ich eine neue Welt anlege, funktioniert beispielsweise auch der Import der Drachritterbox nicht mehr. Da scheint ein grundlegendes Problem mit dem System und Version 0.8.x zu existieren: Szenen werden nicht mehr erstellt, Akteure sind nicht mehr in entsprechenden Ordnern, Fehlermeldungen laufen endlos auf dem Schirm, werden aber nicht geloggt...

**Comment by Plushtoast** [comment]
Kannst du auf dem Foundry Discord mich mal anpingen:
https://discord.gg/foundryvtt

**Comment by Florindel** [comment]
versuch lieber Du mich anzupingen. ich kenne Deinen Usernamen auf discord nicht. Meiner ist Jens#0867

**Comment by Plushtoast** [comment]
Hm kann den User nicht finden. Ich bin Huepfklotz im Ulisses oder Foundry Discord.

**Comment by Florindel** [comment]
Danke nochmal - das Problem ist gelöst: wenn man das Spielsystem nebst den Modulen beim Foundry Update ebenfalls aktualisiert, ist das sehr vorteilhaft
