### ISSUE TITLE
Schwarzmagier Profession Fasar Zauber Memorabia 6 nicht  gefunden

### ISSUE THREAD

**Issue by StudentESE** [Plushtoast/dsa5-foundryVTT#472]
**Describe the bug**
Die Profession **Schwarzmagierin der Akademie der Geistigen Kraft zu Fasar - Pfad der harten Hand** wirft einen Fehler:
*Folgende Einträge können nicht umgesetzt bzw. in der Datenbank gefunden werden. Bitte manuell anpassen/hinzufügen.*

- Zauberspruch/Ritual: Memorabia 6

**To Reproduce**
1. Go to 'Bibliothek'
2. Click on 'Charakter'
3. Suche nach 'Schwarzmagierin der Akademie der Geistigen Kraft zu Fasar - Pfad der harten Hand'
4. Ziehe die Profession auf deinen Charakterbogen

**Expected behavior**
Der Name des Zaubers ist in der Profession falsch angelegt.
Der richtige Name lautet 'Memorabia Falsifir' welche auch vorhanden ist.

**Screenshots**
![ProfSchwMagFasarMemorabia](https://user-images.githubusercontent.com/18450825/123932152-76b52380-d991-11eb-8d47-89c08461d643.png)

**Quick Fix**
Bis der Fehler behoben ist, können Anwender folgendes tun:

1. Suche die Profession 'Schwarzmagierin der Akademie der Geistigen Kraft zu Fasar - Pfad der harten Hand'
2. Doppelklick auf die Profession
3. Kopiere die Profession ('Element Importieren'-Symbol oben rechts - das mittlere)
4. Ändere mit Rechtsklick auf 'Rechte anpassen' für Alle Spieler auf 'Besitzer'
4. Doppelklicke auf die Kopie der Profession
3. Wechsel von Reiter 'Beschreibung' auf den Reiter 'Details'
4. Scrolle bis 'Zaubersprüche'
5. Ändere 'Memorabia 6' in 'Memorabia Falsifir 6'
6. Verwende diese bearbeitete Kopie der Profession für deinen Charakter

**Comment by Plushtoast** [comment]
Danke. Hilfreich wäre noch das Modul anzugeben. KA in welchem Magiebuch das ist.
Aber wir werdens finden.
