### ISSUE TITLE
Begabung: Erneutes Würfeln bleibt ohne Auswirkung

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#478]
Das erneute Würfeln eines Würfels aufgrund von Begabung ändert das ursprüngliche Ergebnis nicht.

 - OS: Windows10
 - Browser: Chrome
 - Foundry Version:  0.8.7 und 0.8.8
- DSA System: 2.0.4

**Comment by Plushtoast** [comment]
Würfel zum neu würfeln angeklickt?

**Comment by sirgawain111** [comment]
Jupp.
Es wird auch neu gewürfelt, aber das Ergebnis wird nicht "angerechnet".
