### ISSUE TITLE
Charsheet - State - Condition: Send to Chat creates double entry

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#485]
When you click on a status / condition to post it to chat, it creates a double message.
![grafik](https://user-images.githubusercontent.com/62849695/124890937-d1293200-dfd8-11eb-88bc-e54832ccfc6a.png)

**Comment by Plushtoast** [comment]
Yeah it has to be twice there, so deaf people can understand.

Also seems like Sweety is treated like a slave.

**Comment by mckee14** [comment]
We need a text to speech function for blind chars, too!

Plushtoast ***@***.***> schrieb am Do., 8. Juli 2021, 23:56:
