### ISSUE TITLE
Ability: Familiar -> Protection -> Solution for own entries

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#486]
When you create an own "Creature" type character, you can add the "Familiar" ability to give special boni.

The "Protection +1" only works when the creature has "Natural Protection" as an ability, which must be copied from another entry or correctly created by hand.

Recommendations (either/or):
 - Change behaviour of "Familiar" to directly influence the protection value instead of the "Natural Protection" item.
 - Create new Creature Sheets with "Natural Protection" pre-set, with a value of 0.

First option may be sleeker, but not sure which is easier to implement.

**Comment by Plushtoast** [comment]
First solution would be preferable. Unfortunately this breaks existing familiars....

**Comment by mckee14** [comment]
migration function? removes "familiar", adds "familiar" again. should do the trick?

(Maybe it would be smart to add variables to the sheets which collect the date or version when the last migration happened. then you could check against that value and inform players via pop-up if a migration is needed.)

**Comment by Plushtoast** [comment]
Yeah, I love complicated migrations

**Comment by mckee14** [comment]
or just a patchnote that you have to remove and re-add the familiar trait.
I reckon that there aren't THAT many familiars. Wurst case: familiars have 1 protection more, so nothing game breaking.
