### ISSUE TITLE
Ressources of actors get lost when imported from compendia

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#488]
**Describe the bug**
Ressources settings of actors' tokens get lost when imported from compendia into the actors list.

**Screenshots**
On the left: Ressources tab of original actor in the dsa5-bestiary compendium
On the right: Ressources tab of the newly imported actor in the actors list
![image](https://user-images.githubusercontent.com/85822812/125170313-d7710700-e1ae-11eb-8605-45905267aac6.png)

**Additional context**
I've tried it with different kind of actors (characters as well as creatures) and different compendia, always with same result.

**Comment by Plushtoast** [comment]
I don't see a problem here.

Please refer to: #423 

If you want to use your own settings check this menu 
![grafik](https://user-images.githubusercontent.com/44941845/125680513-3b74d4a4-6f6c-4865-a55f-cf129a9dc61f.png)

And disable the default DSA token ressources here: 
![grafik](https://user-images.githubusercontent.com/44941845/125680578-b55b3029-6b90-48da-b791-2f32c331f053.png)

Your token's should have reasonable settings If you leave this option enabled.
