### ISSUE TITLE
Conflict with modul shared token visibiliy

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#489]
When the module shared token visibility is activated the menu of the dark eye is not working.
See picture:  
![grafik](https://user-images.githubusercontent.com/87266660/125194566-2a4fca80-e252-11eb-9540-fa8bbc157132.png)
I am login as gamemaster.
Foundryvtt installed on an linux server.
Issue is available on chrome and firefox.

**Comment by Plushtoast** [comment]
This module isn't compatible to foundry 0.8.x
You can create another ticket once the module has been updated and the problem persists.
