### ISSUE TITLE
Incompatible modules

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#49]
Hi,

I found some modules interfere with the dsa5-system.

- Autocomplete Whispers: Rolls from Chat are executed twice while this module is active.
- Clocks: The whole actor-sheet is a clock. Not possible to access it's data.

**Comment by Plushtoast** [comment]
For Clocks:
Clocks changes the looks of the character sheet. You seem to have changed the default character sheet.
Open a character while clocks is enabled and click on the sheet configuration button (the cogs next to the close button). Then change the "default sheet" back to "dsa5.ActorSheetDsa5Character" and change the value of "this sheet" to whatever you need --> clock or actor
![grafik](https://user-images.githubusercontent.com/44941845/107741467-821eef80-6d0d-11eb-85be-d38b0bede11b.png)

**Comment by Plushtoast** [comment]
Autocomplete Whispers overrides the same default chat behaviour as the dsa5 auto completion for skills etc.

Won't support that, sorry.
