### ISSUE TITLE
Manifest-Conflicts odl "systems" vs "new "system"

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#491]
Found in debug.log

foundryvtt up to date, dsa-modules up to date.

{"message":"Package dsa5-armory is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-bestiary is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-bestiary2 is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-core is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-drachenritter is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-godsofaventuria is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-introduction is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-magic-1 is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}
{"message":"Package dsa5-magic-2 is using the old \"systems\" manifest key where a \"system\" key is expected","level":"warn","timestamp":"2021-07-11 14:15:02"}

**Comment by Plushtoast** [comment]
Thats already resolved for the module updates this week.

**Comment by UralterMannII** [comment]
thx
