### ISSUE TITLE
[Foundry 8.8 DSA 2.1.0] Sonderfertigkeit Haltegriff nicht auswählbar

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#493]
**Describe the bug**
Die Sonderfertigkeit Haltegriff kann nicht für den aktiven Angriff verwendet werden. Die Funktion, die Effekte auf den Verteidiger anwenden zu können, wäre aber sehr nützlich.

Problem: Nur SFs die einen Eintrag im Effekt Feld haben werden in die Angriffsprobe gezogen. Diese SF hat aber keinen Effekt oder so.

**Expected behavior**
Sonderfertigkeit durch das Setzen eines Platzhalters im Effekt Feld, für den Angriff nutzbar zu machen.

**Comment by mckee14** [comment]
Schreib ins effekte Feld +0 TP als workaround.

tomsaath ***@***.***> schrieb am Mo., 12. Juli 2021, 13:57:

**Comment by vt-tom** [comment]
Das klappt nicht. Das +0 Fängt er leider ab... Habe schon einiges mit 0 und +0 versucht. Da geht nichts.

**Comment by vt-tom** [comment]
Was aber geht ist: `+1 TP,-1 TP` :)

**Comment by mckee14** [comment]
Stimmt, hast recht, im Ergebnis im Chat steht dann die 0 TP.

**Comment by Dada1981** [comment]
Dem sollte noch hinzugefügt werden, dass standardmäßig kein Statuseffekt beim Haltegriff dabei ist. Laut Regelwerk sollten "Eingeengt" und "Fixiert" ausgelöst werden.
