### ISSUE TITLE
GM Menu Blind GM Roll Modifiers applied to wrong characters [2.1.0 - 0.8.8 EN]

### ISSUE THREAD

**Issue by Lambert-Behnke** [Plushtoast/dsa5-foundryVTT#496]
**It did a Bling GM Roll for my group**
All negative modifiers are applied to each roll. Please have a look at this screen-shot:

![Screen shot Group Check](https://user-images.githubusercontent.com/82769448/125506871-364e3d3b-d44f-42c8-89d2-ce2f5d43578c.png)

So Skalgrim (who has no negative modifiers), rolled first, but all the negative effects which should to anyone in the part apply by default applied to him and everyone else as well. I left the three different characters who have those dice conditions on screen, so you can see where they came from.

If you need anything more let me know, but my Tuesday game is starting 9 minutes ago :)

Good luck.

**Comment by Plushtoast** [comment]
What's up with Odin's raven? Does he have a healthpool tjat is larger than his max hp?
Or is there something else?

**Comment by Lambert-Behnke** [comment]
Ich glaube als Vertrautentier bekommt der mehr Lebenspunkte. Weil sowieso eigentlich keiner einen Raben angreift ist das eigentlich egal. Ich glaube der hat gerade 15 von 5 weil ich das noch nicht hingebogen habe sonder einfach einen Raben rübergeworfen habe.

**Comment by Plushtoast** [comment]
Es gibt im Core Modul den Trait/Eigenschaft Familiar/Vertrauter. 
Der sollte das regeln mit den Werten.
Allerdings gibt's für den ne Änderung im nächsten Patch und ich würde bis dahin warten.
