### ISSUE TITLE
Die Anwendung von SP/TP wird nicht im Chat protokolliert.

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#500]
**Is your feature request related to a problem? Please describe.**
Wenn ich als Meister SP/TP z.B. nach einem erfolgreichen Angriff + misslungenem Ausweichen anwende, wird dies im Chat nicht angezeigt. Hier kommt es immerwieder (bei uns) zur Diskussion. Hat das der Meister schon gemacht oder muss ich Spieler (per Hand) das auch pflegen?

**Describe the solution you'd like**
Minimal: Im Chat wird die Nachricht mit der Schadensermittlung um die Information erweitert, dass die SP/TP angewendet wurden bzw. wenn man dies mehrmals andwendet, dass dies dann auch mehrmals protokolliert wird. 
Nächste Stufe: Die LE vorher / nachher werden mit im Chat protokolliert
Nächste Stufe: Ein Rollback / Löschen des Schadens führt zum automatischen Rollback auch der LE.

**Comment by Plushtoast** [comment]
Hm, man hat eh schon so viel Chatspam. Ich weiß nicht, ob ich das gut finde.

**Comment by UralterMannII** [comment]
Stimmt. Es gibt viel (zuviel) Chatspam und machen kann man auch (im Modul) deaktivieren. 
Das hier ist für mich eine Info, die verloren geht und (bei uns) ab und zu Diskussion/Verwirrung führt.

Und das hier soll kein Issue sondern ein enhancement sein...scheine ich falsch angeklickt zu haben..tut mir leid.

**Comment by Plushtoast** [comment]
Werde da vermutlich maximal n Icon setzen, dass es durchgeführt wurde.

**Comment by UralterMannII** [comment]
Wäre die Minimallösung und - aus meiner Sicht - ok. D.h. würde mich freuen, wenn das so werden würde.
