### ISSUE TITLE
Spieler können auch den SP/TP anwenden

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#501]
**Is your feature request related to a problem? Please describe.**
Es ist ja nett, dass der Meister die Anwendung der SP/TP auf die Spieler-Actors kontrolliert. Es ist aber eine Entlastung, wenn das die Spieler auch selber machen können.

Bei Charakteren auf dem Papier machen das die Spieler auch selber...da wird den Spielern auch vertraut...

**Describe the solution you'd like**
Minimal: Spieler können auch die SP/TP auf sich selber anwenden.
Nächste Stufe: Die Anwendung wird im Chat Protokolliert.
Nächste Stufe: Die LE vorher / nachher werden mit im Chat protokolliert
Nächste Stufe: Ein Rollback / Löschen des Schadens führt zum automatischen Rollback auch der LE.

**Comment by Plushtoast** [comment]
Ja das haben schon mehr Leute angefragt und die Antwort ist nein.
Als Spieler kann man sehr leicht über das Token HUD (Rechte Maustaste auf den eigenen Token) die Ressourcen anpassen.
Außerdem ist es für Spieler auch zumutbar ihren eigenes Char Sheet zu öffnen.
Rollback Features sind an Aufwand selten zu übertreffen.

**Comment by UralterMannII** [comment]
:(

\<offtopic\>Stimme dir zu: Fachliche Rollback ja, technischen nein, die sind in solchen Kontexten dann eher trivial...
Barrierefreiheit ist da nochwas, was so richtig viel "Spass" macht...\</offtopic\>

**Comment by Plushtoast** [comment]
Viele triviale Dinge auf einem Haufen, ergeben wenig trivialen Aufwand. Vor allem wenn es anderes zu tun gibt.
Die HP am Token zu ändern ist auch trivial :)

**Comment by UralterMannII** [comment]
Sorry...hatte deine Entscheidung schon traurig akzeptiert
Wie ich sehe, kam mein offtopic falsch rüber....tut mir leid.

**Comment by vt-tom** [comment]
Kleiner Tipp, im Kontextmenü des Tokens kann auch -5 eingegeben werden und dann werden die 5 Punkte von den aktuellen Lebenspunkten eingegeben. Das macht es für Spieler noch einfacher.
![grafik](https://user-images.githubusercontent.com/80099175/125801546-9e81a8b4-aa4a-4232-ac1c-013e1f532feb.png)
