### ISSUE TITLE
Enable use of third party dice like those from rollsmith

### ISSUE THREAD

**Issue by Mgiepz** [Plushtoast/dsa5-foundryVTT#502]
In the current system the settings for the different attributes are hardcoded. They set the background color of the standard dice to match the colors to those on the charsheet. In the current implementation it is not possible for the user to use the more realistic looking dice models from rollsmith or their own 3d models with textures.

The requested feature would allow the user to map individual dice settings to the different DSA dice. 
For example one could map "Mut" to "trs-black-marble-dice-set" and "Klugheit" to "trs-purple-marble-dice-set"

The new feature should leverage the possibility to pass the appearance of the dice to the roll in dice-so-nice 4
example:
`let r = new Roll("d20").roll();
r.dice[0].options.appearance = {
    system: "trs-black-marble-dice-set" //or something
};
r.toMessage();`

**Comment by Plushtoast** [comment]
Hab noch kein Feedback vom DsN Entwickler.
Bis dahin keine Dice Systeme möglich.
Von meiner Seite ist es eingebaut, ich warte darauf und dann nächster Patch.
Ticket schließe ich trotzdem schon.
