### ISSUE TITLE
Tiergefährten Compendium 

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#503]
Hi, ich habe bereits alle Tiergefährten samt Beschreibung, Images, Sonderfähigkeiten und Talente bei mir eingepflegt gibt es ne Möglichkeit das ich die Kompendiums zukommen lassen kann so das ihr das vielleicht bereits nutzen könnt? 

Mit dem Modul "Easy Export" wäre das eine Kleinigkeit für mich.

**Comment by mckee14** [comment]
Huiiii, das hört sich super an. Darf ich das auch als privater bekommen?

Du kannst für Massenexport/Import auch einfach ein eigenes Kompendium nutzen. Ich habe Dir dafür eine Vorlage erstellt wenn du Interesse hast: ([Tiergefaehrten.zip](https://github.com/Plushtoast/dsa5-foundryVTT/files/6815851/Tiergefaehrten.zip)).

Den Ordner entpacken und speichern unter [Foundry Verzeichnis]/Data/modules
Nach einem Foundry Neustart wird "Tiergefaehrten" als Modul sichtbar in der Welt. Einfach aktivieren, und schon kannst Du alle deine Tiere da rein exportieren:
  - Das Compendium in Foundry Rechtsklicken und den Schreibschutz entfernen
  - All Tiere unter "Actors" in einen Ordner schieben falls nicht schon gemacht
  - Rechtsklick auf den Ordner, "Export to Compendium"
  - Das Compendium "Tiere" anwählen

Dann sind alle Einträge im Kompendium gespeichert. Vorteil: Du kannst die nicht gebrauchten Tiere in der Welt nun löschen, wodurch sie VIEL weniger Ressourcen verbrauchen. Bei Bedarf kannst Du Sie aus dem Kompendium wieder in die Welt importieren.

Um die Daten zu tauschen, kannst du einfach die Datenbank-Datei teilen, oder alternativ den ganzen Ordner:
 - [Foundry Verzeichnis]/Data/modules/Tiergefaehrten >> ganzer Ordner in ZIP packen. Empfänger kann entpacken, fertig.
 - [Foundry Verzeichnis]/Data/modules/Tiergefaehrten/packs/tiere.db >> Datei versenden. Empfänger, die das Modul schon installiert haben, können einfach diese Datei einfügen.

So ein eigenes Modul eignet sich perfekt, um alle möglichen Dinge zentral zu speichern und in jeder Welt darauf zugriff zu haben.

**Comment by Plushtoast** [comment]
@Neon82  Danke für dein Angebot. Wir sind aber inzwischen schon mehr oder weniger fertig mit den Tiergefährten.

@mckee14 Das wäre eine Copyright Verletzung.

**Comment by mckee14** [comment]
Oh, sorry, ich dachte selber erstellte inhalte dürfen geteilt werden. Bin
grad unterwegs, kannst du den eintrag löschen?

Plushtoast ***@***.***> schrieb am Mi., 14. Juli 2021, 14:39:
