### ISSUE TITLE
Handwerksgegenstände und improvisierte Waffen zusammenfassen

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#504]
Ich würde gerne das Thema der Trennung von (Handwerks-)Gegenständen und improvisierten Waffen in Frage stellen.

Momentan ist für beides jeweils ein Gegenstand angelegt. Das eine ist ein Gegenstand, welcher mit dem neuen Patch auch die Vorteile des Gegenstandes nutzt (in diesem Fall eine Teilprobenmodifikation in Holzbearbeitung), und das andere ist eine Waffe mit den dementsprechenden Werten.
![image](https://user-images.githubusercontent.com/82062265/125926916-341bbcff-08d5-433d-93db-0e22611a294d.png)

Was ich schade finde ist, dass ich, wenn ich den Gegenstand für beides nutzen möchte, auch beide Items im Inventar haben müsste. Wäre es da nicht sinnvoller, beide Eigenschaften auf ein und den selben Gegenstand zu geben?
Ich habe zum Beispiel manuell der improvisierten Waffe einfach den passenden Statuseffekt verpasst. (und der Schönheit halber auch beide Beschreibung zusammen gefasst^^)
![image](https://user-images.githubusercontent.com/82062265/125927422-ad2a8ab6-44fc-477b-be08-11bdf874f239.png)

Oder gibt es einen technischen Sinn, warum die Gegenstände getrennt wurden?

**Comment by Plushtoast** [comment]
Das hat zwei Gründe.
Der eine ist, dass diese Gegenstände meist zuerst in den Büchern als Gegenstand auftauchen und erst später als improvisierte Waffe. Der andere ist, dass sich diese zwei Kategorien im technischen Verhalten unterscheiden.
Es gibt zb auch Waffen die fern- und Nahkampfwaffe gleichzeitig sind und somit doppelt vorhanden sein müssen. Das alles in einem Bogen unterzubringen ist technisch aufwendig und eher nicht mehr wahrscheinlich. Außerdem wird dsa eh irgendwann an der datenfülle platzen und Performance Probleme bekommen. Auch hier wären Universalgegenstände auf grund größerer Dummydatenmengen ungünstig.
Hier wird es also in absehbarer Zeit keine Änderung geben.

**Comment by Nellkir** [comment]
Ja schon. Aber wenn man die Gegenstände zusammenfasst, halbiert sich doch die Datenmenge...zumindest bei diesen Gegenständen.

**Comment by Plushtoast** [comment]
Hm, prinzipiell hast du Recht. Wir schauen mal nebenher ob sich das vereinfachen lässt.
