### ISSUE TITLE
Merchant Sheet auch für SC's zulassen?

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#505]
Es gibt NSC's, die sind mir manchmal so wichtig, dass ich für diese einen Charakter über Optolith erstelle, wie ich es auch jedem SC empfehlen würde. Beispielsweise ständige Begleiter der Heldengruppe oder dergleichen. Das gibt mir die Möglichkeit den NSC auf Spielerniveau mit zu steigern und zu entwickeln.
Diese NSC's, welche technisch aber als SC's laufen, würde ich gegebenenfalls gerne den Merchant Sheet (mit dem Typus Normale Person) verpassen, damit die Spieler wie bei anderen NSC's den abgespeckten Sheet sehen können (mit Bild, Beschreibung und Notizfeld) einsehen kann.
Momentan umgehe ich das mit einer für alle einsehbaren Journal-Notiz, aber elegant wäre es, wenn ich da alle NSC's gleich ziehen könnte :-)

Wäre es möglich diese Funktion auch auf SC's zu erweitern?

**Comment by Plushtoast** [comment]
Hm, das sollte theoretisch schon möglich sein, wenn du den Spielern als Permission Limited für den Spieler gibst.

**Comment by Nellkir** [comment]
Jo, funzt.
Da habe ich mich etwas von der "normale Person" Funktion verwirren lassen^^
