### ISSUE TITLE
Begleiter + Vertrauter wrong values

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#507]
Begleiter und Vertrauter sind noch nicht ganz korrekt:

 - Vertrauter gibt 28 AsP (bei Kriegshund und Alligator getestet). Nebst den 15 AsP aus "Vertrauter" wird noch der CH(arisma) Wert addiert, so als wäre CH als Leiteigenschaft für die magische Tradition aktiviert. 
 - Alle Eigenschaften sind noch 1 zu hoch, die +1 aus "Vertrauter" werden nicht wieder reduziert

![grafik](https://user-images.githubusercontent.com/62849695/125960064-7d697841-0646-4f3b-926f-a221cc042c9e.png)

**Comment by Plushtoast** [comment]
Wie versprochen, sind alte Vertraute nicht mit dieser Änderung kompatibel und behalten ihre Attributsupgrades.
Ich hatte da "CH" als Leitwert eingestellt. Das ist komisch, wo hab ich das her..?

**Comment by mckee14** [comment]
Das war ein neu aus dem compendium gezogenes tier, mit vertrauter &
begleiter frisch über die library hinzugefügt.



Plushtoast ***@***.***> schrieb am Sa., 17. Juli 2021, 19:03:
