### ISSUE TITLE
Ammunition: Add Effect(s)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#510]
It would be nice to be able to have different ammo types with different changes in how they work, fe: -1 TP, +1 FK or =1w3 TP etc.

For special arrows, it would also be nice to be able to transfer effects, fe. stunning arrows, or added poison and the like

**Comment by Plushtoast** [comment]
Ah finde das duplicat grad nicht
Sobald armory 2 dran ist

**Comment by Plushtoast** [comment]
Duplicate of #408
