### ISSUE TITLE
Reaktions Button scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by Verdemis** [Plushtoast/dsa5-foundryVTT#511]
**Describe the bug**
Wenn ich den Reaktions Button bei einem Angriff klicken möchte passiert nichts. Das Problem besteht seit ich das Aventurische Kompendium installiert habe. Das deaktivieren des Moduls hat nichts bewirkt.

Folgende Fehlermeldung tauch in der Konsole auf:
![grafik](https://user-images.githubusercontent.com/4998682/125973092-3dd44256-bccc-45ae-8883-30d6531d5168.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Getestet in Firefox und Edge
 - Version Foundry 0.8.8

**Comment by mckee14** [comment]
Hast Du das Spielsystem auch aktualisiert? Bei mir funktioniert die Reaktion, auch mit aktiviertem Kompendium.
(@Plushtoast gestestet mit aktueller core beta von heute nachmittag)

**Comment by Verdemis** [comment]
@mckee14 Hi, ja das Spielsystem ist auf dem aktuellen Stand.

**Comment by Verdemis** [comment]
Ok das Problem scheint sich von selbst gelöst zu haben. Nachdem ich Foundry 3-4 mal neugestartet habe ging es irgendwann wieder. Keine Ahnung was die Ursache war.
