### ISSUE TITLE
Wunschwelle wird falsch berechnet

### ISSUE THREAD

**Issue by Verdemis** [Plushtoast/dsa5-foundryVTT#513]
**Describe the bug**
Wenn ich das richtig sehe wird die Wundschwelle aktuell nicht korrekt berechnet.
Ich habe einen Charakter mit KO 13, also eine Wundschwelle von 7. 
Wenn dieser Spieler z. B. 4 SP bekommt, muss er trotzdem auf den Widerstand gegen Wunde würfeln.
![grafik](https://user-images.githubusercontent.com/4998682/125988297-813d9ec4-d669-4dbb-8f89-34ef2842e3d0.png)

Sobald er einen SP weniger bekommt, muss er nicht mehr auf den Widerstand würfeln.
![grafik](https://user-images.githubusercontent.com/4998682/125988370-19ba8cbd-9ecc-4004-8fed-9f0cb7be5f39.png)
 
 Wenn ich nicht total falsch liege sollte der Charakter erst bei 7 SP auf Widerstand würfeln müssen.
 Ich vermute, dass aktuell für die Berechnung die TP und nicht SP verwendet werden, kann das sein?

**Comment by mckee14** [comment]
Sieht aus, als würden die TP abgefragt und nicht die SP, sprich Rüstung
ignoriert. Wenn dem so ist, müsste es korrekt rechnen wenn du die rüstung
ausziehst?

Sascha Hopstein ***@***.***> schrieb am Fr., 16. Juli 2021,
19:47:

**Comment by Plushtoast** [comment]
Ja du hast sonst zwei Buttons zusätzlich einen für TP. Du musst hier nur klicken wenn du den schaden als sp ,also ohne Rüstung anwenden willst. Falls nicht einfach nicht würfeln

**Comment by Verdemis** [comment]
> 
> 
> Ja du hast sonst zwei Buttons zusätzlich einen für TP. Du musst hier nur klicken wenn du den schaden als sp ,also ohne Rüstung anwenden willst. Falls nicht einfach nicht würfeln

Jo genau das wäre jetzt auch meine Lösung. Ich war nur nicht sicher ob das so gedacht war oder ob es ein versehen war, daher wollte ich es zumindest mal melden.

**Comment by Plushtoast** [comment]
Jo daa ist für den Moment absichtlich so

**Comment by Plushtoast** [comment]
Verbesserungsvorschläge sind aber gern gesehen.

**Comment by mckee14** [comment]
ändert sich dann der Text auf dem Button? Also "Wunde (SP) widerstehen" und "Wunde (TP) widerstehen"?

**Comment by Verdemis** [comment]
Also wenn der Charakter keine Rüstung trägt, tauchen wie @Plushtoast sagt zwei Buttons auf... einmal "Wunde (SP) widerstehen" und "Wunde (TP) widerstehen". Mit Rüstung taucht nur ein Button auf.... "Wunde (SP) widerstehe"....

**Comment by Plushtoast** [comment]
Der zweite Button würde auch auftauchen wenn die wundschwelle mit rüstung überschritten ist.

**Comment by Verdemis** [comment]
> 
> 
> Der zweite Button würde auch auftauchen wenn die wundschwelle mit rüstung überschritten ist.

Ah ich verstehe. Danke für die Klarstellung :)
