### ISSUE TITLE
Schwarmregeln implementieren?

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#515]
Wäre es möglich die Berechnungen zu den Schwarmregeln zu implementieren? Also die AT, VW, TP-Boni für kleine und große Schwarmwesen, sobald eine bestimmte Anzahl überschritten wird. Das Feld für die Schwarmgröße gibt es ja schon.

**Comment by mckee14** [comment]
Die Frage ist, wie willst du das automatisch abbilden? Foundry kann ja
nicht wissen, welche schwarmteile wen angreifen, ob die in angriffsdistanz
stehen usw.

Wenn du gruppierung einführst, wird der grossteil der spieler damit nicht
klarkommen vermute ich.

CommanderAlex98 ***@***.***> schrieb am Fr., 16. Juli 2021,
22:10:

**Comment by vt-tom** [comment]
Was genau meinst du denn mit automaisch @mckee14? 
Wir brauchen theoretisch folgendes:
- Wenn Kreatur winzig, dann Schwarm möglich.
- Angaben Grundgröße und Schwarmgröße
- Wenn Schwarmgröße doppelte, dreifache... der Grundgröße = AT +1, TP -1 und PA (Gegner) -1
- Wenn TP auf Schwarm angewendet: ((LEP*Schwarmgröße)-TP)/Schwarmgröße = Rest Schwarmgröße
Der Schwarm wird als 1 Token behandelt. Bei einem Angriff auf mehrere Spieler, teilt sich der Schwarm halt auf. Maximal so klein wie die Grundgröße beträgt, weil er sonst laut Regeln nicht mehr als Schwarm gilt.
Der SL muss halt aufpassen, dass die Spieler nicht mit normalen Waffen angreifen, sondern Waffenlos.

Das alles klingt für mich ganz gut umsetzbar oder?

**Comment by mckee14** [comment]
Ah sorry, habe das mit "Meute" verwechselt.
Ja, wenn man nur 1 Token hat für den ganzen Schwarm, dann ginge es. Allerdings können sich Teilschwärme ja auch zusammenschliessen und Schwärme neu aufteilen. Könnte schon knifflig werden :)

**Comment by vt-tom** [comment]
Das würde ich aber nicht verlangen, dass das System das abbildet. Da muss der Meister dann tun für was er da ist: meistern 😉.
Aber die Umsetzung der von mir genannten Punkte würde mir schon erheblich helfen... *hust* Fauler Frühling 😁
