### ISSUE TITLE
More icons for map notes

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#516]
**Requested Feature**
Would it be possible to expand the collection of icons for map notes?

**Describe the solution you'd like**
I suggest to add the following icons for map notes:

- Griffin shield (https://game-icons.net/1x1/delapouite/griffin-shield.html)
- River (https://game-icons.net/1x1/delapouite/river.html)
- Trail (https://game-icons.net/1x1/delapouite/trail.html)
- Medieval gate (https://game-icons.net/1x1/delapouite/medieval-gate.html)
- Neutral position marker (https://game-icons.net/1x1/delapouite/position-marker.html)
- Lake (https://game-icons.net/1x1/lorc/at-sea.html)

**Comment by Plushtoast** [comment]
Hm I could maybe expand this with TDE icons. But we don't want to use external graphics.

**Comment by sirgawain111** [comment]
I've looked up icons on this specific web site because the ones that are already available from the system came from this source. But TDE specific icons would be way better, of course :)

**Comment by Plushtoast** [comment]
If you want those icons specifically it might be a better idea to propose them for foundry in general.
For dsa I put this on low priority...whenever I stumble upon a adequate icon.

**Comment by Plushtoast** [comment]
I'll add those now for the next patch.
If you want more icons...tell me.
