### ISSUE TITLE
[Magie/GRW] Fremdzauber hervorheben/Erschwernis

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#517]
**Is your feature request related to a problem? Please describe.**
Es besteht ja die Möglichkeit Zauber anderer Traditionen als Fremdzauber zu erlernen. Diese unterliegen aber gewissen Einschränkungen:
- nicht modifizierbar (GRW S.256)
- erschwert um 2 (AMA I S10)
- ausgenommen 1 Zauber der von Gildenmagiern in die eigenen Tradition umgewandelt werden kann (für Foundry nicht wichtig)

**Describe the solution you'd like**
1. Zauber soll vom User selbst als Fremdzauber markiert werden können.
2. Dieser Zauber soll sich optisch von den anderen in dem Zaubertab abheben.
3. Im Probenfenster soll die Erschwernis auswählbar sein. Außerdem wäre eine Anmerkung, dass der Zauber nicht modifiziert werden kann hilfrreich.

Es wäre meiner Meinung nach nicht zielführend hier alles automatisch abzuwickeln. Vor allem da zum Beispiel die Erschwernis im GRW nicht steht, aber in AM I schon. Ist die Erschwernis optional, kann sie ab oder angewählt werden.

**Comment by Plushtoast** [comment]
1: wäre sehr einfach umsetzbar
2: wie?
3: ok

Allerdings stellt sich mir die Frage, ob das nicht besser wäre, den Zauber automatisch als Fremdzauber zu markieren, wenn die Tradition nicht in der Verbreitung aufgelistet ist. Das ist allerdings mehr Aufwand und erfordert sorgfältige Datenführing.

Leute die die AMA Regel benutzen kennen ihren Zauberer wahrscheinlich sowieso gut genug um den Modifikator automatisch zu verwenden,

Also wäre der Mehrwert hier nur gegeben, wenn es automatisch 2 und 3 macht aber 1 anhand der Daten entscheidet.

**Comment by vt-tom** [comment]
Je nachdem was du für machbar hältst. Ich habe bewusst was geschrieben dass ich für leichter umsetzbar halte.
Am Ende entscheidest aber du 😉

**Comment by argentorum** [comment]
Habe nochmal nachgeprüft und auch im GRW die Erschwerung um 2 für Fremdzauber gefunden. " Entsprechend sind die Zauber der verschiedenen Traditionen in ihrer Anwendung sehr unterschiedlich. Zauber fremder Traditionen (Fremdtradition) lassen sich zwar theoretisch erlernen, jedoch ist ihr Wirken um 2 erschwert und es ist nicht möglich, an ihnen Modifikationen vorzunehmen." (S.274 Zauberertraditionen) Sprich die die Nicht-Modifizierbarkeit und die Erschwerung sollten automatisch gesetzt werden, sowohl für GRW als auch für AMA[1-3]. Von der Umsetzung würde ich dann folgendes vorschlagen:

- Automatische Einstufung und (farbliche) Markierung von Fremdzaubern sowie generelle Nicht-Modifizierbarkeit und Erschwerung -2
- Ausnahme des einen Zaubers, den Gildenmagier als Eigentradition setzen können, das sollte dann auch optisch markiert werden.

Was haltet Ihr davon?

VG Elos

**Comment by mckee14** [comment]
Achtung, andere magische SF erlauben mehrere Zauber aus Fremdtraditionen,
ebenso kann die Zauberwerkstatt hier noch reinspielen bei AMA3.

Ich würde einen automatismus einbauen, der prüft ob die Tradition im Zauber
zur Tradition des Chars passt.
Wenn ja, alles so lassen wie es ist.
Wenn nein, Zauber als Fremdzauber markieren, erschwernis im würfelfenster
mit -2 vorbelegen und modifikatoren verbieten.

Im zauber selbst sollte man einen zauber als "überführt" o.ä. markieren
können (bool). Wenn gesetzt, zählt er als zauber der eigenen tradition.

Traditionen im zauber textuell nachführen führt zu datenchaos, die user
werden das mannigfach falsch machen :)

argentorum ***@***.***> schrieb am So., 29. Aug. 2021, 18:59:

**Comment by Plushtoast** [comment]
Ja klingt gut so.
