### ISSUE TITLE
Journal /Ch implementieren 

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#518]
**Is your feature request related to a problem? Please describe.**
Es wäre hilfreich, wenn der Befehl /ch auch im Journal verfügbar gemacht wird. Dies wäre eine gute Lösung für Personen für die sich kein eigener Token lohnt. 
Makros wären auch cool, aber nicht zwingend notwendig. 

**Describe the solution you'd like**
Beispiel: @ch[Willenskraft 13/13/13 -3] (finde ich besser, weil weniger geklickt danach) oder @ch[Willenskraft -3]

**Comment by Plushtoast** [comment]
Das war schon mal auf der Liste, wurde aber wieder gescrapt.
Mit jeder neuen Funktion in foundry scheint man nochmal etwas fauler zu werden.
