### ISSUE TITLE
Gezielter Angriffsmodifikator wird bei der Auswahl fehlerhaft angezeigt

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#525]
Wenn man die SF gezielter Angriff hat, wird ja die Erschwernisse auf gezielte Schläge halbiert.
Im Dropdown Menü wird das nicht angezeigt.
![image](https://user-images.githubusercontent.com/82062265/126356008-1fd2fd2b-6685-4523-adc3-fba850bee697.png)

Aber die Würfelprobe wird trotzdem korrekt modifiziert. Also nur kosmetischer Makel, der zu Verwirrung führen kann. :-)
z.b. Attacke auf Torso:
![image](https://user-images.githubusercontent.com/82062265/126356399-ec1736c8-cd9a-42a6-b8c1-be469887b9b2.png)

**Comment by Plushtoast** [comment]
Duplicate of #524
