### ISSUE TITLE
Gift automatisch anwenden

### ISSUE THREAD

**Issue by Verdemis** [Plushtoast/dsa5-foundryVTT#526]
Feature Vorschlag: Es wäre ganz praktisch wenn man Attacken direkt mit einem Gift kombinieren könnte. z. B. bei Kreaturen die mit einem Biss vergiften oder wenn ein Charakter seine Waffe vergiftet hat. Vielleicht das man das Gift im Würfelfenster wie ein Manöver an und abwählen kann. Und wenn der Angriff SP verursacht, hat man einen Button um den Gift Effekt auszuwürfeln.

**Comment by Plushtoast** [comment]
Duplicate of #506

**Comment by Plushtoast** [comment]
Kreaturen können das schon btw.

**Comment by Verdemis** [comment]
Ach echt? Wie funktioniert das denn? Geht das auch bei selbsterstellten Kreaturen?

**Comment by Plushtoast** [comment]
Das Gift dem Inventar der Kreatur hinzufügen.
Dann bei einer Attack ins Effektfeld "poison|Name des Gifts" eingeben oder Beispiel anschauen von einer Kreatur die's schon hat (zb Palmviper, Höhlenspinne).

**Comment by Verdemis** [comment]
Ah interessant. Danke für den Hinweis. Ich schaue es mir an.

**Comment by Verdemis** [comment]
Ok irgendwie stehe ich auf dem Schlauch. Das Gift im Inventar hinzufügen, dass hatte ich auch bei meiner Kreatur gemacht. Wenn ich mir z.B. die Höhlenspinne anschaue, sehe ich aber nirgendwo einen eingetragenen Effekt. Ich vermute Du meinst beim Biss dann unter Statuseffekte? Oder suche ich an der völlig falschen stelle?

**Comment by Plushtoast** [comment]
Ok Höhlenspinne war ein schlechtes Beispiel. Da fehlt der Effekt.
Außerdem scheint es, als ob das zur Zeit bugt.

**Comment by Verdemis** [comment]
Ok ich verstehen. Danke. Dann warte ich einfach erstmal ab :)
