### ISSUE TITLE
Waffen- und Rüstungsbeschädigungen

### ISSUE THREAD

**Issue by Verdemis** [Plushtoast/dsa5-foundryVTT#533]
Falls es diese Funktion schon gibt, dann habe ich sie bisher übersehen. Aber falls noch nicht, möchte ich folgendes gerne als Vorschlag einbringen.

Bruchfaktortests bei Waffen und Rüstungen, sobald man einen kritischen Treffer einstecken muss, bzw. man einen kritischer Treffer pariert.

Hinzufügen von Beschädigungsstufen (bei Waffen) bzw. Verschleißstufen (bei Rüstungen) ermöglichen.

**Comment by Plushtoast** [comment]
Was wäre hier die beste Möglichkeit, um das möglichst einfach zu gestalten/handhaben.

Button bei kritischem Angriff im Chat zum draufklicken?
In welchem Buch stehen die Regeln dazu.

**Comment by Verdemis** [comment]
Ich denke ein Button wäre eine gute Möglichkeit. Die Regeln finden sich in der Aventurischen Rüstkammer. 
Oder hier: https://www.ulisses-regelwiki.de/Beschaedigungen.html

**Comment by Zonenpenner** [comment]
Wenn ich an dieser Stelle einen Vorschlag machen dürfte:

Ein eigener Wert für die Beschädigungsstufen ist gar nicht notwendig, da im Prinzip jeder Gegenstand bereits Strukturpunkte hat. Die Beschädigungsstufen wurden nur als Alternative eingeführt, da sich das Nachhalten der Strukturpunkte als aufwendig erwieß. Für Foundry sollte das Problem jedoch kleiner sein.

Da eine Beschädigungsstufe dem Verlust von 1/4 der Strukturpunkte entspricht, müssten diese überwacht werden, um die Beschädigungsstufen nachzuhalten:

Verlust von 1/4 StP = 1 Beschädungsstufe = Leicht beschädigt (AT und PA-1 bzw. RS-1)
Verlust von 2/4 StP = 2 Beschädungsstufen = beschädigt (ATund PA-2 bzw. RS-1 und BE+1)
Verlust von 3/4 StP = 3 Beschädungsstufen = schwer beschädigt (nicht mehr nutzbar/ keine Vorteile (RS))
Verlust von 4/4 StP = 4 Beschädungsstufen = zerstört

Effekte, die eine Beschädigungsstufe zufügen, müssten dementsprechend 1/4 der maximalen Strukturpunkte des Gegenstandes abziehen.

Damit würde man auch das große Problem umgehen, dass man für Schilde sowohl Strukturpunkte als auch Beschädigungsstufen nachhalten müsste, da der Schildspalter gegen Strukturpunkte geht, während der Schild dennoch von Patzern, kritschen Treffern etc. beieinflusst wird und daher die Beschädigungsstufen nachgehalten werden müssten.

**Comment by Plushtoast** [comment]
Das klingt nach einer guten Idee und ist auch relativ einfach umsetzbar.
Fraglich ist nur wie es sich möglichst störfrei integrieren lässt ohne zu viel gefummel beim Einsatz.

**Comment by Verdemis** [comment]
irgendwie müsste man ja auswählen welche Waffe oder welches Rüstungsteil betroffen ist um Strukturschaden hinzufügen

**Comment by Plushtoast** [comment]
Eine Sammlung von Fähigkeiten, die Strukturschaden verursachen würde helfen.

Wahrscheinlich gibts dann an der Chatcard ein Kontextmenü mit "Strukturschaden anwenden", woraufhin ein Popup aufploppt, wo man den betroffenen Gegenstand auswählen kann.

**Comment by Verdemis** [comment]
Klingt gut 👍

**Comment by Zonenpenner** [comment]
So, hier eine Auflistung Strukturschaden verursachender Fähigkeiten, für die bereits in Foundry implementierten Regelwerke. Es sind viel mehr magische und karmale Fertigkeiten aufgeführt, da diese nur Strukturschaden anrichten, wenn dies explizit aufgeführt ist.

Basisregelwerk:
Strukturschaden (generell)	        S.349
Schildspalter					S.249
Hexengalle					S.292
Ignifaxius					        S.293

Kompendium I:
Rammen mit Streitwagen		S.140
(aber Streitwagen noch nicht implementiert)	
Hammertfaust-Stil				S.158

Magie I:
Energiestrahl					S.21
Hammer des Adepten			S.22
Hammer des Magus			S.22
Brechender Fels				S.50
Zerspringendes Glas			S.52
Destruktor					S.101
Archofaxius					S.117
Archossphaero				S.117
Desintegratus					S.124
Eisenrost					        S.126
Ignisphaero					S.132
Orcanosphaero				S.133
Caldofrigo					S.149


Magie II:
Zagibu Ubigaz					S.34
Zersetzende Schale				S.43
Kulminatio					S.113
Alchimistensäure				S.219
Hylaier Feuer					S.220

Götterwirken I:
Kontrolle der Welle				S.20
Schlag der Zerstörung			S.44
Erdbeben					        S.119
Pech und Schwefel				S.134


Aus den bereits umgesetzten Quellenbüchern:

Rüstkammer I:
Waffen- und Rüstungsbeschädigung     S.114

Bestiarium I:
nix

Bestiarium II:
Holzwurmverhalten		S.53
Auflösung			S.73

Tiergefährten I:
nix

Pandämonium I:
Zerplatzen			S.95
Auflösung			S.121
Aquafaxius			S.154
Frigosphaero			S.154
Ignisphaero			S.155
Kulminatio			S.156

**Comment by Plushtoast** [comment]
Danke, ich schau mir das mal an und überleg dann, was zu tun ist.

**Comment by Plushtoast** [comment]
Hm Rüstungen und Waffen scheinen gar keine Werte für Strukturpunkte zu haben...

**Comment by Verdemis** [comment]
Laut Fokusregeln läuft das über Bruchfaktor und Stabilitätswert. S. Link weiter oben

**Comment by Plushtoast** [comment]
Ja, leider ist das dann nicht mit Zonenpenners guter Idee kombinierbar...

**Comment by Plushtoast** [comment]
So für den Patch wirds erstmal so sein:

Waffen und Rüstungen bekommen per Default 4 Strukturpunkte, die kann man dann noch beliebig ändern.
Pro 25% verlorene StruPu gibts eine Stufe Beschädigung.

Existierende Waffen aus Modulen werden das Update nicht sofort bekommen. D.h. man muss erstmal manuell StruPu eintragen.

Abzüge werden daraus automatisch berechnet.

Ob der Bruchfaktortest und Strukturschaden per Zauber und Co noch diesen Patch kommt ist fraglich.
Das dauert vermutlich noch etwas länger.

**Comment by mckee14** [comment]
Wow, super, danke.

Es wird aber nix automatisch abgezogen an den Punkten, das führt man
manuell nach?

Und wer mit Bruchfaktortests spielen will, der würfelt das händisch aus und
zieht ggf eifach 1/4 der max Strukturpunkte ab...

Plushtoast ***@***.***> schrieb am So., 31. Okt. 2021, 11:10:

**Comment by Plushtoast** [comment]
Also Strukturpunkte muss man manuell editieren im Moment, die Modifikatoren die das nach sich zieht, sind aber automatisch.

**Comment by Plushtoast** [comment]
Für  die Rüstungsbruchfaktorprobe müssen alle Rüstungen auch erstmal das Rüstungsart Attribut bekommen.

**Comment by mckee14** [comment]
Solange man es händisch nachführen kann über die Strukturpunkte ist ja
alles da, finde das super.
Endlich können wir das mal spielen, der Verwaltungsaufwand am tisch war mir
stets zu hoch dafür :)

Plushtoast ***@***.***> schrieb am So., 31. Okt. 2021, 11:22:

**Comment by Plushtoast** [comment]
Jemand ne Ahnung was der Bruchfaktor von Fächern und Spießwaffen ist?
Nehme jetzt mal 10 bzw 6 an...

**Comment by Zonenpenner** [comment]
Fächer | 13
Spießwaffen | 12

laut Regelwiki, keine AHnung wo die es herhaben, in der Rüstkammer II sehe ich es nicht.

https://ulisses-regelwiki.de/Beschaedigungen.html

**Comment by Plushtoast** [comment]
Ok denke kommt alles in den Patch, bis auf das notwendige Rüstungsupdate bestehender Module...

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/139584046-dd8381ea-da8e-4660-a8a5-a1b82bad0245.png)

Aufwendiger als gedacht.

**Comment by Plushtoast** [comment]
Wer mag kann schon mal die Beta vorab testen über dieses install link:
https://raw.githubusercontent.com/Plushtoast/betaLink/master/system.json

(reinkopieren bei system install)

Hat sehr viele Änderungen dieses mal und ggf noch ein paar bugs.
Geplant ist hier aber nur noch ein kleines Icon für beschädigte Waffen und ein bisschen Feintuning.

Feedback wieder hier.

Vorläufige Patchnotes kann man bei mir im Discord per pm bekommen.

**Comment by Verdemis** [comment]
Ich bin nicht sicher ob ich vielleicht etwas falsch mache, aber wenn ich einer Waffe 3/4 Strukturpunkte gebe, wird zwar das Icon angezeigt, dass die AT und PA um 1 erschwert ist, aber es wird beim Wurf nicht berücksichtigt.
