### ISSUE TITLE
neues Notizfeld nur für sheet-owner sichtbar

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#536]
Wäre es möglich ein zusätzliches Feld auf dem Charakterbogen-Notizenblock zu erschaffen, welches nur für den jeweiligen Owner sichtbar wäre?

Ich denke da insbesondere an die SC-Charakterblätter, da ich diese als Limited für alle sichtbar machen möchte (um Bild und Beschreibung der SC-Charaktere zu sehen), aber nicht unbedingt die Hintergrundgeschichte oder sonst welche Notizen für alle sichtbar sein sollen.

**Comment by Plushtoast** [comment]
Das GM Notes Feld entspricht nicht dem, was du möchtest?

**Comment by Nellkir** [comment]
naja, die sheet owner spieler können das GM-Feld ja nicht nutzen.
Dachte halt an ein Plätzchen, wo sie ihre persönliche Hintergrundgeschichte oder ähnliches rein schreiben könnten, die nicht unbedingt die anderen einsehen sollten.
Aber wenn das zu umständlich/speziell ist, lässt sich das auch mit Journal Notizen erledigen. ;-)
