### ISSUE TITLE
Proben - Anzeige aktueller Wert mit Modifikationen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#537]
**Is your feature request related to a problem? Please describe.**
 Es wäre schön, wenn im Proben Fenster angezeigt wird, wie die Probe mit allen dort eingestellten Modifikationen aussieht. 

**Describe the solution you'd like**
Am liebsten würde ich das für alle Proben umgesetzt haben. 

**Describe alternatives you've considered**
Zumindest die 1d20 Proben. Gerade AT und PA wenn man nicht über den Char Bogen geht. Da verliert man schnell den Blick darauf, wie hoch der Wert ist den man hat und wie er ist wenn die Modifikationen eingerechnet werden. 

**Additional context**
Ja, das ist ein Wunsch der auf hohem Niveau meckert, loswerden musste ich es trotzdem 😉

**Comment by Plushtoast** [comment]
Ich halte das generell nicht für eine gute Idee das Probenfenster noch weiter zuzuspamen.
Überschlagen kann mans insbesonders bei ner 1d20 Probe auch sehr einfach.

Denke nicht, dass ich mir das dieses Jahr noch anschaue.

**Comment by vt-tom** [comment]
Als Spieler ist das auch überhaupt kein Problem. Als SL habe ich aber fest gestellt, dass ich durch den Weg über Reaktion und der Angriff über den Combat Tacker, teilweise überhaupt nicht im Blick habe auf was für Werte ich Würfel.

Ist aber wie gesagt ein Luxus Problem und völlig zu Recht niedrig aufzuhängen.
