### ISSUE TITLE
chat command /ch mit Name ausstatten

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#538]
Wäre es möglich beim Würfelfenster von Chat Command "/ch (Probe)" noch ein zusätzliches Feld zu erstellen, wo der Name des probenden Charakters bei Bedarf noch handschriftlich hinein editierbar wäre?
Also wenn der Meister z.b. für mehrere NSCs ohne Charakterbogen würfelt, dass er die auseinander halten kann, und auch generell für alle Beteiligten etwas informativer aussieht :)

**Comment by Plushtoast** [comment]
Ich bin da generell nicht so der Freund davon die Rolldialoge aufzublähen. Insbesondere wenn es ein Feature ist, das sehr wenige benutzen werden.

**Comment by Plushtoast** [comment]
Außerdem muss ich dazu am Chat auch was umbauen. 
Nach einiger Überlegung komme ich zu dem Schluss, dass sich das nicht trivial ohne Murks umbauen lässt --> vlt. wenns mal anderswo dazu passt.

**Comment by Nellkir** [comment]
> Ich bin da generell nicht so der Freund davon die Rolldialoge aufzublähen. Insbesondere wenn es ein Feature ist, das sehr wenige benutzen werden.

also ich meine nur die würfelproben OHNE Charakterblatt Zuweisung.
Nicht alle Würfelproben^^

Aber ok, wenn das zu umständlich ist, macht das auch keinen Sinn. Wird schon so gehen :-D

**Comment by Plushtoast** [comment]
Im nächsten core module update gibts ein Makro, das das kann.
Für das Chatcommand sehe ich das momentan nicht.
