### ISSUE TITLE
Deduction of LeP after damage roll (Chat)

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#54]
**Describe the bug**
When you request damage rolls from the players via Journal, the roll works fine. But the option to automatically assign the damage doesn't work.

**To Reproduce**
Open journal entry as GM. 
Send a roll request to the chat (i.e. damage roll on the first bridge, pinned journal entry)
Click on the chat entry to roll damage
Right-click on the damage, select to deduct the damage from health.

Tested options, same behaviour
- as GM and as player
- with and without selecting a token
- with and without declaring a token as target
- with and without activating a battle

**Expected behavior**
deduct the damage from health, either from selected or targeted token

**Comment by Plushtoast** [comment]
This is not a damage roll. It is just a normal inline roll, which can appear in any circumstance. F.e. for a random roll for amount of silver to loot.
There is no option planned or intended to add this automatically or replace this with a damage roll (or at leaset with priority close to zero).
Click on the token on the map to edit the healtbars in place.

Updating the health bar is only intended for opposed combat rolls (more specifically for the results chat card)
