### ISSUE TITLE
Ausrüstungs-Unterkategorie "Dienstleistung" - Item verschwindet aus dem Inventar des Verkäufers

### ISSUE THREAD

**Issue by Zettgeschehen** [Plushtoast/dsa5-foundryVTT#542]
Hallo!

Beim testen der neuen Unterkategorie "Dienstleistung" ist mir folgendes aufgefallen:

- Anzahl verringert: Hat man z.B. ein Item in höherer Anzahl, verringert sich diese beim Kauf. 
- Hat man ein einmaliges Item, verschwindet dieses nach dem Kauf.

Ich denke, mit Blick auf angedachte statische Items, ist das noch nicht ganz richtig oder?! 

Die Chatnachrichten erscheinen ohne Probleme. 

Liebe Grüße
Lars

**Comment by Plushtoast** [comment]
Das ist erstmal schon so gedacht gewesen. Vlt gibt's nur 10 Bier oder drei Pferde zu kaufen

**Comment by Zettgeschehen** [comment]
Nur 10 Bier... Du kennst meine Gruppe nicht :-) 

Ok, bei einigen Dienstleistungen (z.B. zahnreissen, baden, Haare trimmen.ä.) wäre ein "Platzhalter"-Item schon nicht schlecht!

**Comment by Plushtoast** [comment]
Hm ich würde sagen nur zehn Bier ist ein perfekter Startpunkt für ein ziemlich gefährliches Abenteuer

**Comment by Plushtoast** [comment]
Wird indirekt verbessert durch eine einfache erhöhung der anzahl der items
