### ISSUE TITLE
Journalbrowser, Meistermenü, Bibliothek als Makros?

### ISSUE THREAD

**Issue by CommanderAlex98** [Plushtoast/dsa5-foundryVTT#543]
Hat wahrscheinlich lowprio, aber würde immerhin einen Klick sparen wenn man sich die Sachen auch in die Makroleiste ziehen könnte

**Comment by Plushtoast** [comment]
Kann man beides bereits als macro öffnen.Müsste irgendwiegame.dsa5.journalbrowser.render(true)Und game.dsa5.apps.mastermenu.render(true) seinOder so ähnlich

**Comment by Plushtoast** [comment]
game.dsa5.apps.gameMasterMenu.render(true)
bzw.
game.dsa5.apps.journalBrowser.render(true)

Auf dem Plan steht nochmal ein Kompendium mit DSA Macros. Das hat aber grad keine Prio.
Da kommt das dann vorbereitet rein.
