### ISSUE TITLE
Unterstützung von .Webm Tokens für die Anzeige im Chat

### ISSUE THREAD

**Issue by Coolmander** [Plushtoast/dsa5-foundryVTT#545]
VTT unterstüzt für Tokens das Webm dateiformat.
Also Animierte Tokens.

Diese werden im Chat jedoch Fehlerhaft angezeigt
![2021-07-23 10_19_46-Foundry Virtual Tabletop Fall 1](https://user-images.githubusercontent.com/26301740/127669158-7e6db690-a68c-498f-aa98-a4d9d8111f7d.png)

![2021-07-23 10_19_46-Foundry Virtual Tabletop Fall 2](https://user-images.githubusercontent.com/26301740/127669245-bd320fc7-ce42-42c6-a01c-ef5d73045046.png)

Da im Chat für die Anzeige das Img-Tag verwendet wird und dies nur maximal .webp Unterstüzt.

**Describe the solution you'd like**
Mir würden Zwei Alternativen einfallen.
Möglichkeit 1:
wenn ein .webm Token verwendet wird, wird statt dem Token-Bild das Akteur-Bild verwendet, da hier .webm nicht unterstützt wird.
Möglichkeit 2: 
Bei .webm wird das Video tag verwendet, Dadurch wird auch der Alpha wert verwendet..

**Describe alternatives you've considered**
Alternativ aber nicht so sauber wäre die Lösung das im string webm durch png ersetzt wird und als gm dafür gesorgt werden muss das eine alternative Datei in den assets sind.

**Comment by Plushtoast** [comment]
Das wird wohl dann noch an ein paar anderen Stellen nicht richtig dargestellt.
Ich mach jetzt erstmal für den Chat das video tag.

**Comment by Coolmander** [comment]
Super danke, im Übrigen mal ein Riesen lob für deine/eure Arbeit.
Das Modul und der Support ist echt super.
