### ISSUE TITLE
[Enhancement]Gruppenschicksalspunkte

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#551]
**Is your feature request related to a problem? Please describe.**
Gruppenschicksalspunkte sind nur eine Optionalregel, aber falls es möglich wäre, diese wie die Schips zu implementieren, wäre das sehr nett, da meine Gruppe damit gerne spielt. Ich verstehe aber, dass das schwierig zu implementieren ist und als Optionalregel eine geringe Priorität hat.

**Describe the solution you'd like**
Es könnte einen Dummy-Actor oder an anderer Stelle ein Item geben, wo der Spielleiter die Gruppenschips einstellen kann. Spieler, die keine Schips haben, sollten dann die Option haben, Gruppenschips zu verwenden.

**Additional context**
Wie stets: Herzlichen Dank für Eure unermüdlichen Mühen!

**Comment by Plushtoast** [comment]
Kannst du mir sagen, in welchem Buch die Regeln dazu beschrieben sind?

**Comment by DerGreif** [comment]
Sehr gerne!

 

Aventurisches Kompendium, S. 172 f.

 

Hier ist der Link zum Regelwiki, aber ohne Gewähr, dass die die regeln richtig kopiert haben. Ich  habe das nicht überprüft.

Gruppen-Schicksalspunkte - DSA Regel Wiki (ulisses-regelwiki.de)

 

Vielen Dank nochmals für Eure tolle Arbeit! Kann man nicht genug betonen! Da sind sich alle in der Gruppe einig! Weiterhin viel Erfolg!

 

Herzliche Grüße,

Gunther

 
 

Gesendet: Mittwoch, 15. September 2021 um 13:46 Uhr
Von: "Plushtoast" ***@***.***>
An: "Plushtoast/dsa5-foundryVTT" ***@***.***>
Cc: "DerGreif" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Plushtoast/dsa5-foundryVTT] [Enhancement]Gruppenschicksalspunkte (#551)


 

Kannst du mir sagen, in welchem Buch die Regeln dazu beschrieben sind?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
