### ISSUE TITLE
[Enhancement]Statuseffekte als abspeicherbares Item selber anlegen

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#552]
**Is your feature request related to a problem? Please describe.**
Bisher kann man zwar Statuseffekte selber anlegen, aber nur für einen konkreten Actor oder indem man den Effekt an zB einen Gegenstand koppelt. Es wäre schön, wenn man Statuseffekte selber als Item anlegen könnte wie auch SF, Gegenstände, Zauber etc. und diese dann immer wieder als Statuseffekt einsetzen könnte, ohne den Umweg über einen ausrüstbaren Gegenstand gehen zu müssen oder ohne die bei jedem Actor neu anlegen zu müssen, zB die Raserei beim Zant.

**Describe the solution you'd like**
s.o.

**Describe alternatives you've considered**
s.o.

**Additional context**
Herzlichen Dank für all Eure Mühen! Wir sind im April von Roll20 auf Foundry umgestiegen und bereuen nichts! Ihr legt ein großartiges Entwicklungstempo vor! Das und Euer Umgang mit der Community sucht seinesgleichen!

**Comment by Plushtoast** [comment]
Das ist eigentlich etwas das von Foundry so nicht gewünscht ist.

**Comment by DerGreif** [comment]
Vielen Dank für die Info und dass Du es Dir angeschaut hast! Es gibt ja auch workarounds. Derzeit verwende ich Nachteile mit entsprechenden Statuseffekten. Das Ausrüsten im Kampf ist halt etwas umständlicher, als einen vorgefertigten Status zu verwenden, aber auch kein Beinbruch.

Nochmals herzlichen Dank!
