### ISSUE TITLE
Ausweichen -4/-2 im FK

### ISSUE THREAD

**Issue by Corelich** [Plushtoast/dsa5-foundryVTT#553]
Aus den Regeln:
 _Das Ziel kann Fernkampfangriffe nicht mit einer Waffe parieren, dafür aber den Schuss oder Wurf mit einem Schild parieren oder ausweichen. Auszuweichen oder mit dem Schild parieren, ist bei Angriffen mit Schusswaffen um 4 erschwert, bei Wurfwaffen um 2._
Wäre praktisch, wenn Bögen und Wurfwaffen diesen Effekt automatisch drin hätten.

**Comment by mckee14** [comment]
Haben sie doch? Wenn das ziel vorher ausgewählt wurde, hat die verteidigung
einen malus beim wurf...

Corelich ***@***.***> schrieb am Di., 3. Aug. 2021, 12:49:

**Comment by Corelich** [comment]
Wurde bei mir noch nie angezeigt. Ich werde bei Gelegenheit mal Bilder machen.

**Comment by Plushtoast** [comment]
Die Charaktere müssen ab und zu manuell aktualisiert werden. Dazu im char bogen rechts oben, das Link symbol finden, die Warnungen berücksichtigen und mal migrieren.
In diesem fall wären das die Kampftalente

**Comment by Corelich** [comment]
Ok, hab alle Charaktere migriert und nun funktionierts. Danke!
