### ISSUE TITLE
Token-Größe von Bibliotheks-Wesen wird auf 1/1 gesetzt, wenn ich den Token mit dem Aktor verlinke

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#556]
**Describe the bug**
Wenn ich einen Token aus der Bibliothek einem Wesen auf die Map ziehe, dann ist die Token-Größe für das Wesen passend. Wenn ich das Wesen aus dem Actors Directory auf die Map ziehe, passt die Größe auch.
Sobald ich bei dem Wesen im Actors Directory unter [Prototype Token] "Link Actor Data" anklicke, wird die Größe auf 1/1  gestellt. Es fehlt der Default-Wert für das Wesen.

**To Reproduce**
1. Öffne die Bibliothek
2. Zieh eine Seeschlange auf die Map (Größe passt)
3. Ziehe einen Token von der Seeschlange aus dem Actors Directory auf die Map (Größe passt).
4. Aktiviere für die Seeschlange im Actors Directory im [Prototype Token] "Link Actor Data".
5. Ziehe nochmals einen Token der Seeschlagne aus dem Actors Directory auf die Map (Größe passt nicht).

**Expected behavior**
Die Größe sollte auch für den Prototype-Token per Default so eingestellt sein, dass sich die Größe des Tokens nicht ändert.

**Comment by Plushtoast** [comment]
Das ist so beabsichtigt. Die tokengröße wird erst beim platzieren auf die map angepasst. Setzt du das actorlink allerdings, gilt der token Prototyp und du musst die Größe und alles andere tokenbezogene selbst konfigurieren

**Comment by Plushtoast** [comment]
Ich ändere jetzt das Verhalten, weil ich vergessen habe, warum ich es ursprünglich so gelöst habe...

**Comment by Albinosheep** [comment]
Ich sage ein herzliches Dankeschön! :-)
