### ISSUE TITLE
Doppelte/Dreifache/Vierfache Einträge in der Bibliothek

### ISSUE THREAD

**Issue by Meteox** [Plushtoast/dsa5-foundryVTT#560]
In der Bibliothek sind mittlerweile mit dem heranschreiten des Releases von Modulen einige Einträge Doppelt/Dreifach/Vierfach Ich hab mal zwei Bilder als Beispiel angehängt.

Ein Feature Duplikate auszublenden, und bei Items den Rüstkammer Eintrag zu bevorzugen wäre gewünscht

Ich weiß ich könnte die einzelenenn einträge selber manuell löschen, das müsste ich dann aber auch jedes mal wenn ich ein Update mache neu machen, daher keine Lösung.
 

![image](https://user-images.githubusercontent.com/1143467/128698634-eb0caebd-f469-4c76-8096-763b7beb3dd6.png)
![image](https://user-images.githubusercontent.com/1143467/128698874-a28f9474-0802-455d-8f93-d74ffa843bd6.png)

**Comment by Plushtoast** [comment]
Ich glaube nicht dass wir das Grund DSA Problem lösen werden oder wollen. Mal sehen. Keine prio

**Comment by Plushtoast** [comment]
Closed ...unlösbar
