### ISSUE TITLE
Ausrüstung (Gift - Kelmon) lässt sich nicht ausrüsten

### ISSUE THREAD

**Issue by Sgt-Pepper** [Plushtoast/dsa5-foundryVTT#562]
Kelmon lässt sich nicht per drag and drop einem NPC Charakter zuweisen. Andere Gifte hingegen schon.

Bibliothek -> Ausrüstung -> Filter auf Gift -> Kelmon per drag and drop auf Charsheet -> kein Effekt

Keine  Fehlermeldung in der Chrome Console sichtbar...

Versionsinfo:
Foundry 8.8, DSA Modul aktuell. (Foundry läuft auf NodeJS on Linux.)

Frontend: Chrome 92.0.4515.131

**Comment by Plushtoast** [comment]
Kannst du das nochmals ausprobieren?
Bei mir funktioniert das problemlos. Vielleicht hattest du einen Disconnect oder bereits ein Gift in ner Tasche und es wurde dort gestackt ohne direkt sichtbar zu sein.

**Comment by Sgt-Pepper** [comment]
Ich habe es noch mal getestet.

Bei dem existierenden NPC kann ich nach wie vor kein Kelmon ausrüsten - andere Gifte aber schon.
Ich habe auch alle Gifte aus der AUsrüstung des NPC entfernt und von vorne angefangen - mit dem gleichen Ergebnis.

Bei einem neu erschaffenen NPC hingegen kann ich Kelmon ausrüsten. 



Es gibt im ersten Fall weder eine Fehlermeldung im Browser, noch eine Reaktion im Serverlog. Die Ursache scheint also  komplex zu sein und nicht unbedingt ursächlich im Item "Kelmon" zu liegen. Falls ich noch mehr rausfinden kann, melde ich es nochmal, aber ich schätze es ist kompliziert den Fehler nachzustellen, von daher gerne erstmal schließen oder on-hold...

**Comment by Plushtoast** [comment]
Du kannst maximal noch den betroffenen Char mal exportieren und hier anhängen.
