### ISSUE TITLE
Bibliothek - Index Fehler!

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#564]
Dies Passiert nach dem ich Tiegefährten und das Pademonium installiert habe.
Beim öffnen der Bibliothek wird versucht beim Versuch den Index zu erstellen 2 Fehlermeldungen angezeigt (siehe Screenshot) und läuft dann endlos.
![image](https://user-images.githubusercontent.com/68306267/128726578-0e4f99d9-365c-4c25-a2c3-4a69ea6f0151.png)

**Comment by Plushtoast** [comment]
Die Fehlermeldung seh ich ständig und immer ist die Quelle ein Modul Dritter. Du wirst erst alle Module nacheinander deaktivieren müssen und rausfinden welches das ist. Dann kann ich vlt was machen.

**Comment by Plushtoast** [comment]
Geschlossen in Ermangelung von weiteren Details.
