### ISSUE TITLE
Item Sets Broken

### ISSUE THREAD

**Issue by Muwak77** [Plushtoast/dsa5-foundryVTT#569]
We discussed this issue a while ago on discord and you gave me a nice and working fix. But it seems, this fix has never been applied to the Ruleset. (Ich patched the last two updates myself and they still contained the old code). 

Probably this is because i missed writing an issue :) 

So here is the ting (which i lazily copied from Discord): 

I have an issue with one of my DTE-Game-worlds where i can't add equipment-packages to characters anymore (the world was created prior to 0.8.) i get an error message in the console whoch reads: 

```
actor-sheet.js:967 Uncaught (in promise) TypeError: Cannot set property 'value' of undefined
    at ActorSheetdsa5Character._handleLookup (actor-sheet.js:967)
    at async ActorSheetdsa5Character._manageDragItems (actor-sheet.js:941)

```
in a newly created world on the same Server  it works fine. is this a known thing or should i open an issue on git?

**You came up with this solution:** 

ou would have to replace the "let lookup" line with this
let lookup = await (await DSA5_Utility.findAnyItem(item.items)).map(x => x.toObject())

**Comment by Plushtoast** [comment]
Braucht noch core update. aber ich schließe das jetzt mal schon.
