### ISSUE TITLE
Animierte Token im Combatracker sorgen für Absturz des Combattrackers in der Sidebar

### ISSUE THREAD

**Issue by Coolmander** [Plushtoast/dsa5-foundryVTT#575]
**Describe the bug**
Verwendet man ein animates Token und fügt diesen dem Combatrakter hinzu, funktioniert alle normal bis ein Refresh durchgeführt wird (F5, Szenenwechsel usw.)
Lädt der Combattracker der Side Bar nicht mehr.

Entfernt man den Teilnehmer wieder und Lädt neu funktioniert alles wieder.

![2021-08-19 13_13_09-Window](https://user-images.githubusercontent.com/26301740/130059346-3280bc3f-cde1-4b21-97b5-9d0026a43fc2.png)

Das Fenster was durch Rechtsklick geöffnet werden kann funktioniert noch.
![2021-08-19 13_14_17-Window](https://user-images.githubusercontent.com/26301740/130059443-ca5bfe0e-6bb5-460f-a1f0-43a9522bc311.png)

Folgende Fehler erscheint in der Console
![Fehler Combatracker_webm](https://user-images.githubusercontent.com/26301740/130059493-5b8e281d-49c0-4169-842a-98292eb9de16.png)

Durch den Fehlenden Combattracker kommt es auch beim Mouse Hover über Tokens zu einen Fehler:
![2021-08-19 13_17_46-Window](https://user-images.githubusercontent.com/26301740/130059942-f7bce635-2167-44a2-b401-0c2a2169464d.png)

Der Mouse Over funktioniert nur nicht bei den Teilnehmern die auch im Combattraker vorhanden sind.

Der Fehler betrift auch die ALT-Funktion um sich alle Token-Namen anzeigen zu lassen.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**

**Comment by Plushtoast** [comment]
Klingt eher nach einem generellen Foundry Problem oder einem Modul.

**Comment by Plushtoast** [comment]
Das passiert auch bei anderen Spielsystemen nach meinem Test (Earthdawn & DnD5). Also ist es ein Foundry Problem.
D.h. warten bis es von Foundry gefixt wird (oder dort einen Bug report starten).
