### ISSUE TITLE
Feature Request bei der SL Willkür

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#579]
Hallo ich habe gerade die neue Funktion der SL Willkür gesehen.

Ich hätte hier noch eine bitte. Könnte man es hier noch möglich machen das man dort eine Erschwerniss bzw. Erleichterung eintragen kann damit der Wurf für die Spieler, glaubwürdiger aussieht.

**Comment by Plushtoast** [comment]
Ich versteh nicht was du meinst. Im roll Dialog kann man doch schon alle möglichen Modifikatoren eingeben.

**Comment by ghost** [comment]
Ich sollte nicht mitten in der Nacht ein Feature Request starten. Du hast recht.
