### ISSUE TITLE
Status Trance erzeugt unerwünschte Abzüge

### ISSUE THREAD

**Issue by argentorum** [Plushtoast/dsa5-foundryVTT#581]
Bei Anwendung des Status Trance (Aventurisches Götterwirken 1, S.11) wird ein genereller -1 Malus pro Stufe in in Foundry angewendet. Bei Stufe 4 tritt Status Handlungsunfähig nicht ein. 

**Regeln** (https://www.ulisses-regelwiki.de/Sta_Trance.html)
Bei der Trance handelt es sich um eine Form der leichten Entrückung. Sie tritt meistens bei der Nutzung von Zeremonialgegenständen oder dem Einsatz von einigen Sonderfertigkeiten auf. Trance baut sich alle 24 Stunden um 1 Stufe ab.
Trancestufen	Auswirkung
Stufe I	Der Held spürt die Nähe seines Gottes, eine potenzielle AsP-Regeneration fällt in der nächsten Regenerationsphase
aus.
Stufe II	Alle Proben, außer auf Liturgien und wohlgefällige Talente, sind um 2 erschwert, eine potenzielle AsP-Regeneration
fällt in der nächsten Regenerationsphase aus.
Stufe III	Alle Proben (auch wohlgefällige) sind um 3 erschwert, eine potenzielle AsP-Regeneration fällt in der nächsten Regenerationsphase aus.
Stufe IV	Handlungsunfähig; eine potenzielle AsP-Regeneration fällt in der nächsten Regenerationsphase aus.

**Vorschlag Umsetzung**
- Keine situationsbedingten Modifikatoren für Stufe 1
- -2 für Stufe 2 (Spieler/Meister bestimmen Wegfall/Ausgleich des Modifikators für Liturgien/wohlgefällige Talente selbst)
- -3 für Stufe 3
- Triggert Status Handlungsunfähig für Stufe 4.
(Wegfall AsP Regeneration kann von manuell von Spieler / Meister geregelt werden)

**Screenshot (für Reproduktion)**
https://cdn.discordapp.com/attachments/812254122022928384/881574955882532874/unknown.png

**Comment by Plushtoast** [comment]
Hm, komisch. Dachte das hatte ich schon erledigt.
Muss ich mir nochmal anschauen. 

Wohlgefällige Talente gehen dann btw. automatisch (wie bei Entrückung)

**Comment by argentorum** [comment]
Alles klar, danke für die Überprüfung.
