### ISSUE TITLE
Makro Sicht und Licht 

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#584]
**Is your feature request related to a problem? Please describe.**
Wir im Discord besprochen hier mal meine persönlichen Sicht und Licht Einstellungen für Foundry:
Empfehlen tue ich lieber nichts upside_down , aber ich spiele mit:
Fackel 2/4
Kerze 1/2
Öllampe 2/4
FlimFlam 4/8
Für Dunkelsicht I ist es 8, heißt für II 16

**Describe the solution you'd like**
Ein Makro mit dem sich das Pro Token schnell umstellen lässt. Beispiel hier:
(folgt wenn ich am PC bin)

**Comment by JWinsen** [comment]
on behalf of @tomsaath 
[fvtt-Macro-token-sicht_licht-1.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/7175644/fvtt-Macro-token-sicht_licht-1.txt)
rename to *.json

**Comment by Zonenpenner** [comment]
@tomsaath
Laut der Spielhilfe "Katakomben und Ruinen" S.10  hat die Öllampe (wohl so eine kleine Tonlampe) mit 1 Schritt Basisreichweite die selbe Helligkeit wie eine Kerze, während eine richtige Laterne sogar 3 Schritt Basisreichweite hat.

**Comment by vt-tom** [comment]
Da ich das Regelwerk nicht habe, habe ich die oben genannten Werte genommen, auch weil sie für Foundry deutlich praktischer sind.

**Comment by Zonenpenner** [comment]
Erscheinen mir ja auch sinnvoll, wollte nur darauf verweisen, dass dazu ein DSA5 Regelwerk und Werte existieren. Wenn man das als Grundlage nehmen möchte, wären die Werte fast wie von dir vorgeschlagen nur halt mit Öllampe 1/2 und Laterne 3/6.

**Comment by vt-tom** [comment]
Ah okay, alles cool. So wie der Huepfklotz es aktuell baut, könnte man die Werte ggf auch noch manuell an seine Runde anpassen. Also mal sehen was wir dann bekommen. Danke für den Hinweis.
