### ISSUE TITLE
Regeneration Modifikator

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#590]
Wenn man bei der Probe auf Regeneration einen Modifikator angibt, zählt der sowohl für LeP als auch für AsP (und vermutlich auch KaP). Es gibt allerdings einige Modifikatoren, die sich nur auf das eine oder andere auswirken - zB Heilkunde Wunden Probe nur auf LeP. Das kann man so leider nicht über den Modifikator berücksichtigen.

**Comment by Plushtoast** [comment]
Duplicate of #389
