### ISSUE TITLE
Beschreibung Zwergennase bei Zwerg ruft zäher Hund herbei

### ISSUE THREAD

**Issue by Corelich** [Plushtoast/dsa5-foundryVTT#597]
![image](https://user-images.githubusercontent.com/85258154/134767742-dd14ac5e-9d84-4fec-b633-830bf1661ab8.png)
![image](https://user-images.githubusercontent.com/85258154/134767754-10d23fa1-98f4-4fd7-b4f7-c01aba4be471.png)

Nach klicken auf Zwergennase bei Spezies Zwerg erscheint die Beschreibung für zäher Hund.

Gruß
Corelich

**Comment by Plushtoast** [comment]
Du hast vermutlich den Button auf der falschen Seite des Namens geklickt.

**Comment by Plushtoast** [comment]
Kannst du das nochmal checken? Bei mir läuft es einwandfrei.

**Comment by Corelich** [comment]
Ich hab tatsächlich in die falsche Zeile geschaut, tut mir leid

Gruß
Corelich
