### ISSUE TITLE
Kleiner Verbesserungsvorschlag: Bei der Regeneration auch einen Hakem im Chatfenster wenn bereits angewendet wurde?

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#598]
**Is your feature request related to a problem? Please describe.**
Kleiner Verbesserungsvorschlag: Bei der Regeneration auch einen Hakem im Chatfenster wenn bereits angewendet wurde? (Lösung siehe Schaden anwenden Häkchen nach Patch 2.3.0)

**Comment by Plushtoast** [comment]
Regeneration kann sowieso nur 1x angewendet werden.

**Comment by Albinosheep** [comment]
Erst einmal lieber Plushtoast sage ich dir ein herzliches Dankeschön für deine prompte Reaktion! :-)

Ich persönlich sehe doch einige Vorteile fürs Spiel, die durch "herumprobieren ob es geht" nicht gleichwertig ersetzt werden kann. Man hat einfach auf einen Blick, ob eine Regeneration angewendet wurde. Außerdem hat es bei meinen Spielern gestern tatsächlich auch etwas zu Verwirrung beigetragen. Das zeigt mir, dass das unterschiedliche Verhalten wohl allgemein als nicht ganz intuitiv empfunden wird.

Außerdem frage ich mich, wieso man TP/SP bzw. AsP-/KaP-Kosten jeweils mehrfach anwenden kann, die Regeneration nicht? Eigentlich finde ich es in den ersten beiden Fällen elegant gelöst. 

Ich würde mich freuen, wenn du es dir noch einmal durch den Kopf gehen lassen würdest. Mir ist klar, dass du auch Arbeitszeit und Ertrag gegenseitig abwägst. Aber ein paar "good to haves" sehe ich schon auf der Haben-Seite. :-)

schönen Sonntag!

**Comment by Plushtoast** [comment]
Ich halte generell nix von forcierten Beschränkungen.

**Comment by Albinosheep** [comment]
Lieber Plushtoast,
dann sind wir ja einer Meinung?
Ich habe gerade gesehen, dass der Haken bei Regenerationsproben nun schon von dir eingebaut und sogar für die Spieler sichtbar geschaltet wurde. Vielen Dank! :-)

Vielleicht kannst du ja mittelfristig überlegen, auch die Regeneration mehrfach anwendbar zu erlauben.

**Comment by Plushtoast** [comment]
Irgendjemand hatte sich bereits gewunschen dass es nur 1x möglich ist und ich werde das jetzt nicht jeden Patch ändern. Ich brauche auch persönlich die Haken überhaupt nicht und halte deren nutzen für gering

**Comment by Albinosheep** [comment]
Ich bin mir gerade nicht ganz sicher, ob wir aneinander vorbei reden.

Ich persönliche bevorzuge, wenn diese Sachen _mehrfach_ anwendbar ist und es für alle sichtbar mittels Haken "dokumentiert" wird. Damit sind die Gruppen weniger eingeschränkt.
Grundsätzlich finde ich es sinnvoll, wenn alle drei Typen gleich funktionieren würden. Im Moment kann man bei zweien die Sache mehrfach anwenden. Bei der Regeneration ist es dagegen nur einmal anwendbar.

Du sagst irgendjemand hat sich gewünscht, dass es bei der Regeneration nur einmal geht. Vielleicht wäre der Person mit dem Haken aber auch schon geholfen gewesen? Dann hätte man es ja direkt gesehen ohne die Möglichkeit der mehrfachen Regeneration für alle grundsätzlich zu unterbinden.

Selbstredend änderst du das nun nicht jeden Patch auf Zuruf die Mechaniken dahinter. Das ist für mich sowieso klar. Ich hatte nur das Gefühl, dass ein paar Gesichtspunkte zu dem Thema noch nicht ausgesprochen waren. 

Und klar verstehe. So haben wir alle unsere Schwerpunkte. Ich finde die Haken hilfreich und eine tolle Sache! :-)
