### ISSUE TITLE
Collection of possible end of combat round events

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#601]
If this list grows long enough, it will be implemented

* Poison
* Vampir Regeneration
* Schattenfessel

**Comment by Ben528491** [comment]
Falls das Issue noch aktuell ist:
- Brennend

**Comment by Plushtoast** [comment]
Brennend geht doch schon

**Comment by Ben528491** [comment]
Stimmt, mein Problem war, dass ich die KRs über "Nächste Runde" beende (darüber funktioniert das Event momentan nicht). Was klappt, ist das Betätigen der nächsten Runde über "Nächster Zug", wenn ich alle Akteure durchklicke. Das Problem ist, dass ich den Combattracker nicht exakt so benutze, wie es vorgesehen ist. 5 Goblins beispielsweise habe ich nur einmal im Combattracker angelegt und handele diese durch Massenwürfe ab um Zeit zu sparen.

Es wäre super, wenn die End-of-Combat-round-events auch über den Button "Nächste Runde" getriggert werden würden.

Zu möglichen End-of-Combat-round-events noch:
- Vampirische Kräfte (Marboliturgie) - ähnlich wie die Vampir Regeneration, die du schon gelistet hast. Jedoch wird nicht die gleiche Regeneration angenommen wie bei Vampiren, sondern nur 1W6.
