### ISSUE TITLE
Implementierung d. Besonderheiten, Typus: Dämonen / Elemntare

### ISSUE THREAD

**Issue by elmer-github** [Plushtoast/dsa5-foundryVTT#619]
Genannte mit dem Typus einhergehende Eigenschaften sind nicht integriert, beispielsweise Halbierung von TP bei Angriffen mit profanen Waffen, Immunität durch Verwandlungszauber etc. (https://ulisses-regelwiki.de/Best_D%C3%A4monen.html). EIne Intergration wäre sehr praktsich

**Comment by Plushtoast** [comment]
Duplicate of #586
