### ISSUE TITLE
Auslaufende Effekte im Kampf

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#623]
**Is your feature request related to a problem? Please describe.**
In Anbetracht der oftmals zahlreichen wirkenden Effekte im Kampf, wäre es super, wenn Effekte im Kampf automatisch auslaufen könnten, wenn ihre Zeit gekommen ist. Eine kurze Chatbenachrichtigung, dass der Effekt hinfort sei, wäre auch cool.

**Describe alternatives you've considered**
Ich habe Times Up ausprobiert. Leider kann das Modul beim DSA-Kampf anscheinend nicht Zug und Runde auseinanderhalten und beendet einen Zaubereffekt, der 10 Runden dauern sollte, leider immer nach den Zügen der nächsten 10 AKteure, unabhängig von den Runden. Würde Times Up das "verstehen" wäre auch geholfen.

**Comment by Plushtoast** [comment]
Sollte mit times up im kürzlich verfügbaren hotfix wieder richtig funktionieren.
