### ISSUE TITLE
Gegenstände aus Ausrüstungspaketen haben teilweise keinen Effekt

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#624]
Einge der Gegenstände aus den Ausrüstungspaketen haben keinen Effekt, obwohl es "Versionen" dieser Gegenstände aus der Rüstkammer 2 gibt, die einen haben.

Wie das Ganze zu Stande kommt, ist mir schon klar, ist halt nur etwas unschön, wenn man sich überlegen sollte, ob man jetzt den "richtigen" Zunder (aus der Rüstkammer) oder dummerweise den falschen (aus dem Basisregelwerk) dabei hat.

Ist ein ähnliches Thema wie in #504  und die Frage, inwiefern man solche Gegenstände zu einem einzelnen zusammenfassen könnte.

**Comment by Plushtoast** [comment]
Ich geb den Items die nicht aus dem Grundregelwerk sind Priorität beim Hinzufügen. Hatte ich sowieso noch vor.
Mit einer Zusammenfassung würde ich nicht rechnen, das ist zu aufwendig.

**Comment by Plushtoast** [comment]
Ist im nächsten Hofix drin.
Leider gibts noch ein paar Items die nicht unbeding gleich heißen je nach Buch (Verband bzw Verbandszeug).
Falls dir solche Dinge auffallen, gib gern Bescheid, dann seh ich wie sich das noch verbessern lässt.
Allerdings habe ich keine Zeit das aktiv zu suchen.

**Comment by Zonenpenner** [comment]
Super! Ich melde mich, falls ich solche Gegenstände finde!
