### ISSUE TITLE
Error im Log beim Start: Falsche URL zum Bild des Amazonensäbel?

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#625]
Error im Log:
modules/dsa5-armory/icons/weapons/Amazonensaebel.webp:1 Failed to load resource: the server responded with a status of 404 ()

Soweit ich das Verstanden haben sollte der so lauten:
modules/dsa5-armory/icons/**melee**weapons/Amazonensaebel.webp

Dort ist die Datei auch vorhanden.

**Comment by Plushtoast** [comment]
Wir haben die ersten Module noch nicht so gestreamlined gebaut. Soll heißen, da sind die Pfade noch eher zufällig. Inzwischen folgen sie aber einem stricten Schema.  Für grob n halbes Jahr gabs jetzt an beiden Pfaden die Icons. Beim letzten Update sind die alten aber (absichtlich) rausgeflogen.
Du solltest du korrekte Grafik wieder angezeigt bekommen, indem du die Ausrüstung migrierst (Kettensymbol rechts oben am Charblatt).
Migration empfiehlt sich sowieso immer mal wieder. Hier wird nichts automatisch auf die neuen Daten umgestellt, da man nie wissen kann, was der User alles manuell geändert hat.
Ein Backup davor schadet aber auch nicht unbedingt.

**Comment by UralterMannII** [comment]
Vielen Dank für den Hinweis. Habe jetzt den gesamten Server durchsucht, da kein actor diesen Amazonensäbel hatte.
Schliesslichh habe habe ich die URL im Chat gefunden. Dort dann im db-file die URL korrigiert UND foundryvtt neu gestartet (reload im Browser hat nicht gereicht), dann war der Fehler weg. D.h. das Migrationsscript für actors ist - in diesem Fall - nicht hinreichend (gewesen).

Unabhängig davon, gibt es ein Macro mit dem ich "alles" migrieren zu lassen? Ein Backup muss ich sowieso vorher machen, falls ich ein fallback haben möchte...

**Comment by Plushtoast** [comment]
Der Chat ist ein volatiles Element und sollte sowieso ab und zu gelöscht werden.
Für den wird es bestimmt keine Migration geben.

Ein Macro für alles sehe ich im Moment auch nicht, weil damit bestimmt der ein oder andere seine Welt irgendwie grillt und ich mich nicht darum kümmern will.
