### ISSUE TITLE
Händlerinventar partiel sperren

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#629]
Wäre es möglich, dass Händlerinventar partiell zum Verkauf zu sperren? Oder ein getrenntes Verkaufsinventar anzulegen?

Also wenn ich ein Händler Token habe, dass ich auch mit Ausrüstung für eventuelle Kämpfe ausgestattet habe, sollte der Händler diese Waffen/Rüstungen aber nicht zum Verkauf anbieten.

Momentan löse ich dies mit zwei getrennten Charaktersheets, einer ist zum Handeln da, der andere um für eventuelle Kämpfe bereit zu stehen.

**Comment by Plushtoast** [comment]
Hm eigentlich dachte ich, dass ich das schon so geregelt hab.
Angelegte Sachen dürften nicht verkauft werden.

Das generell für jeden Gegenstand festzulegen, halte ich aber für zu aufwendig sowohl beim Programmieren, als auch beim Benutzen.

**Comment by Nellkir** [comment]
Also bei mir werden angelegte Waffen angezeigt:
![image](https://user-images.githubusercontent.com/82062265/136705767-b45eac93-996a-432e-8dad-a72cc34fd1bd.png)
![image](https://user-images.githubusercontent.com/82062265/136705783-85042f23-fdbc-4bc2-a98c-a4e5ae978e58.png)
und lassen sich erwerben
![image](https://user-images.githubusercontent.com/82062265/136705817-894ac067-a866-4984-a235-29b53602173d.png)
