### ISSUE TITLE
Wuchtschlag wird bei Gezieltem Angriff nicht angewendet

### ISSUE THREAD

**Issue by Meckerdrache** [Plushtoast/dsa5-foundryVTT#630]
Wenn bei der Angriffsprobe Gezielter Angriff und Wuchtschlag ausgewählt werden, wird zwar der Angriff entsprechend erschwert, allerdings werden die Trefferpunkte durch den Wuchtschlag nicht erhöht. Klappt man die Modifikatoren auf, wird die Erschwernis des Wuchtschlags zwar angezeigt, allerdings auch nicht als Wuchtschlag spezifiziert.

**Comment by Plushtoast** [comment]
Sieht bei mir so aus, als ob die Trefferpunkte richtig berechnet werden, der Tooltip aber nicht stimmt.
