### ISSUE TITLE
Actor auswählen, die im Meistermenü angezeigt werden

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#638]
Zurzeit werden alle Actors im Meistermenü angezeigt, die einem Spieler zugeordnet sind.
Damit werden "wichtige NSCs", die keinem Spieler zugeordent sind nicht angezeigt.
Damit werden "unwichtige SCs" (z.B. Reittiere) die einem Spieler zugeordent sind, angezeigt.

**Describe the solution you'd like**
Es kann am Actor ein Attribut gesetzt werden, ob dieser im Meistermenü angezeigt werden soll.

**Additional context/Describe alternatives you've considered**
Die Liste der Actors scheint zufällig zu sein und nicht z.B. alphabetisch sortiert. Dadurch sind Actors, die dem gleichen Spieler gehören (z.B. "Alrik" und "Alrik's Pferd" irgendwo im Menü verteilt (wenn diese nicht unmittelbar nacheinander erstellt wurden...)
Ein alphabetischen Sortierung ermöglicht einen "Zwischenschritt", der die Actors, die über den Namen verbunden sind, zusammen in der Liste stehen...

**Comment by Plushtoast** [comment]
Attribut ist irgendwie meh...
was ich aber machen könnte ist sortieren per drag & drop + beliebige actors per drag and drop aufs meister menü ziehen, dass diese "gepinnt" sind.

**Comment by UralterMannII** [comment]
Das dag&drop hört sich so passend an. 
Falls ich auch dann acotrs aus dem meister menü wieder löschen kann...denn dann kann ich mir das Menü so aufbauen, wie ich es benötige. Wäre super.
