### ISSUE TITLE
Munition in einem Köcher und dann gleiche Munition in der Ausrüstung nicht möglich

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#639]
Zurzeit gibt es, trotz der textuellen Beschreibung, keine Beschränkung der Anzahl der Munition im Köcher.
Hinzu kommt, das es nicht mögich ist z.B. Bolzen auf mehr als einer Position in der Ausrüstung zu haben. Beim Hinzufügen weiterer Bolzen aus z.B. der Lilbrary wird die Anzahl der Bolzen im Köcher erhöht. Es ist nicht möglich eine weitere Position mit Bolzen zu haben.
Wenn ich nun mit strg-Taste eine Kopie anlege und ich die Kopie "zurückschiebe", dann werden 1. die "Orginalpfeile" auch aus dem Köcher zurück in die Ausrüstung geschoben UND im Köcher verbleiben die ursprünglichen "Orginalpfeile".
Wenn ich nun mit dem Migrationsskript die Ausrüstung aufräumen lasse, dann ist der Köcher leer und die "beiden" Pfeilpositionen (orginal und kopie) in der Ausrüstung-Munition...

**Comment by Plushtoast** [comment]
Ne Munitionsbeschränkung für Köcher bau ich bestimmt nicht ein :) Irgendwo is auch mal Schluss.

**Comment by mckee14** [comment]
Aber eine Köcherbeschränkung für Chars!
Und bitte mit Halfbelfentragkraftmodifikator :)

Plushtoast ***@***.***> schrieb am So., 17. Okt. 2021, 19:53:

**Comment by UralterMannII** [comment]
Sorry...mehrere Dinge rund um Munitioin hier reingepackt.
1. Köcherbeschränkung ist das gleiche wie Behälterladungsbegrenzung...liegt in der Verantwortung der Spieler/GMs...schade, aber nach vollziehbar.
2. gleiche Munition gleichzeitig eine Position in Ausrüstung und in Behältern ist nicht möglich.
3. Buggy Verhalten beim Kopieren von z.B. Munition und das sich daraus ergebenden Verhalten beim drag&drop

**Comment by UralterMannII** [comment]
> Aber eine Köcherbeschränkung für Chars! Und bitte mit Halfbelfentragkraftmodifikator :) Plushtoast ***@***.***> schrieb am So., 17. Okt. 2021, 19:53:

Wieso? Du kannst doch eine beliebige Anzahl an Köcher haben? Wird halt wie bei der Muni der eine (!) Counter des Köchers hochgezählt...
