### ISSUE TITLE
Bitte einen itemtyp für Pflanzen hinzufügen

### ISSUE THREAD

**Issue by Xeon2003** [Plushtoast/dsa5-foundryVTT#643]
Hilfreiche Felder neben Name und Preis wären:

- Landschaftstyp
- Region
- Suchschwierigkeit
- Bestimmungsschwierigkeit
- Pflanzenverbreitung nach Landschaftstyp? bzw. das wäre dann ehr die Gewichtung in der Tabelle...

Ich würde gerne ne Tabelle haben mit der ich würfeln kann und meinem Spieler sagen kann, welche Pflanzen er gefunden hat.

**Comment by Plushtoast** [comment]
Kommt mit dem Release des Herbariums alles. (Bis dahin nochmal die itemtypen durchgehen)

**Comment by Xeon2003** [comment]
Super, danke für die Info.
Gibt es fürs Herbarium einen Zeitrahmen?

**Comment by Plushtoast** [comment]
Ich fürchte vor Januar wird das nichts mehr, aber spätestens Februar.
