### ISSUE TITLE
Moorwurm hat zuviele ASP

### ISSUE THREAD

**Issue by Corelich** [Plushtoast/dsa5-foundryVTT#647]
**Expected behavior**
Laut Wiki Sollen Moorwürmer 16 ASP haben, in Foundry haben sie 20

**Screenshots**
Aus Foundry VTT:
![image](https://user-images.githubusercontent.com/85258154/138589563-8ff22c28-7488-4289-869b-21ad0a2b27cb.png)
Aus DSA Wiki:
![image](https://user-images.githubusercontent.com/85258154/138589583-650b39f0-48f5-4fb7-b55c-006865f99312.png)

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/138591952-a5e35f74-1c15-4f25-acce-5badef353cc9.png)

Bestiarium 2 - dritte Auflage sind es 20

Sollte also passen, vermutlich ein Delta zwischen den Auflagen

**Comment by Corelich** [comment]
Ah, gut. Tut mir leid für sie Störung.

Plushtoast ***@***.***> schrieb am So., 24. Okt. 2021, 13:24:

**Comment by ghost** [comment]
Im Regelwiki wurde das jetzt auch auf 20 ASp gesetzt.
