### ISSUE TITLE
Makro: Light and Sight - Flim Flam 5 fehlerhaft

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#648]
**Describe the bug**
Im Makro Light and Sight ist das Licht für Flim Flam 5 falsch eingestellt. es fehlt doch die Farbe für das Licht.

Fehlerhafter Ausschnitt aus dem Makro:
`    5: {
        "dimLight": 12,
        "brightLight": 6,
        "lightAnimation": flim,
        "lightColor": "",
        "lightAlpha": 1
    },`

Screenshot:
![grafik](https://user-images.githubusercontent.com/80099175/138701499-3bb7f69d-32a8-4b2e-acaf-734b529e4a13.png)

**Comment by Plushtoast** [comment]
Das ist kein Fehler sondern Absicht.
Der Flim soll bei 5 noch nicht alles in grelles Licht tauchen.

**Comment by mckee14** [comment]
Ne, da ist wirklich ein falsches Setting hinterlegt für Stufe 5. 

Stufe 4: bisschen Licht
Stufe 5: nix
Stufe 6: wandelnde Sonne

![grafik](https://user-images.githubusercontent.com/62849695/139204399-ac121a06-6f8d-463a-9050-3196fc949606.png)

**Comment by Plushtoast** [comment]
flim 5 
![grafik](https://user-images.githubusercontent.com/44941845/139205654-c2fd5ba9-ec53-460e-be61-827a6870f494.png)
 flim 6

![grafik](https://user-images.githubusercontent.com/44941845/139205696-b931f300-c075-420e-bd58-f690b3d9e135.png)


Sieht gut aus...

**Comment by Plushtoast** [comment]
Da ist absichtlich keine Lichtfarbe.
Habt ihr evlt n Lichtmod?
