### ISSUE TITLE
Begleiter: Loyalität Werte & Kosten

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#657]
Begleiter haben das Talent Loyalität bekommen (Danke dafür!).
Gemäss Regelwerk können Tiere einen Wert für mehrere Charaktere haben, um unterschiedliche Loyalitäten abzubilden.
Die Kosten für das Steigern von Loyalität bezahlt derjenige, auf den sich die Loyalität bezieht - nicht das Tier selbst.

Requests:

1. Loyalität erweitern auf Loyalität ()
   - Angabe der Person, auf welche sich die Loyalität bezieht
   - Manuelles anpassen des Talents funktioniert nur eingeschränkt; der Beschrieb wird dabei gelöscht und kann nicht wieder hergestellt werden (lässt sich nicht editieren).

2. Abbildung der Kosten im Char
   - Eintrag im Char, für welchen Begleiter wie viel AP bezahlt wurden für die Steigerung von Loyalität

3. Verknüpfung zwischen 1. und 2.
   - Super luxuriös wäre es, wenn im Talent auf einen Charakter verwiesen werden könnte und bei diesem Char dadurch automatisch die verschiedenen Loyalitätswerte gelistet werden, inkl. Talentwert und der Möglichkeit, eine Probe zu werfen.

Nein, das braucht niemand, ausser man spielt einen Dr. Doolittle Char.
Ja, ich spiele gerade einen Dr. Doolittle Char :)

**Comment by Plushtoast** [comment]
Ich weiß nicht....mir fallen 100 Dinge ein die hier Prioriät kriegen würden....

* Beschwörungen
* Chimärengenerator
* Rüstungsvorteile/-nachteile
* Waffenvorteile/-nachteile
* Verfügbarkeit von Ausrüstung nach Regionen
* Kaffee trinken...

Oder auch für das Tiergefährtenmodul ein Upgrade um Pferde zu unterstützen (inklusive schnellem aufsteigen mit stat wechseln, token und sonstigen Funktionen)

Oder einfach nur ein genereller Abenteuerpunkte Ausgabe Tracker (aber Foundry hat hier bereits in einem Video etwas sehr geiles zukünftiges zu vorgestellt)

**Comment by mckee14** [comment]
Verständlich.
Könntest Du dann wenigstens beim Talent Loyalität die Bearbeitung der
Beschreibung erlauben?

So kann man den verlorenen Text rekonstruieren, nachdem man die Bezeichnung
geändert hat auf "Loyalität (Charname)"

Plushtoast ***@***.***> schrieb am Sa., 30. Okt. 2021, 11:24:
