### ISSUE TITLE
Rüstungs- und Waffenvorteile und -nachteile

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#658]
Rüstungs- und Waffenvorteile und -nachteile

Da es in einem anderen Thread bereits angesprochen wurde mache ich den hier mal auf. Besonders die unterschiedlichen Rüstungen "leben" ja von den Vor- und Nachteilen.  Ist aber offensichtlich, dass das echt ne Menge Arbeit wäre.

**Comment by mckee14** [comment]
Man könnte ggf einen Reiter in Waffen und Rüstungen erstellen, und da die
Einträge einfügen: Effektfeld und Beschreibung.

Bei Angriff und Verteidigung taucht der Eintrag im Rollfenster auf, so dass
man ihn auswählen kann, genau so wie zB. Spezialmanöver...

Falls es umgesetzt würde, sollte man pro Char festlegen können, ob man mit
Vor/Nachteilen spielt.

Zonenpenner ***@***.***> schrieb am Sa., 30. Okt. 2021, 17:47:

**Comment by Plushtoast** [comment]
Warum pro Char?

Größter Aufwand ist, dass quasi jedes Modul nochmal angefasst werden muss...

**Comment by mckee14** [comment]
Erfahrungsgemäss wollen das nie alle spieler gleich halten, darum :)



Plushtoast ***@***.***> schrieb am Sa., 30. Okt. 2021, 18:05:

**Comment by Plushtoast** [comment]
Bisher gibt es keine Einstellungen, die nur per Charakter gelten.
Ich möchte so viel wie möglich Excel DSA vermeiden.

**Comment by mckee14** [comment]
Ok, dann formuliere ich es anders.
FALLS da was umgesetzt wird, könntest du den code so gestalten, dass er auch noch läuft, wenn man mit den vor/nachteilen spielt und einzelne spieler die texte/werte einfach manuell rauslöschen aus dem item/tab/wasauchimmer.

dann ist der toggle gesamthaft in den optionen für alle, und man kann sich sein excel händisch basteln wenn nötig :)

wobei wir bisher auch ganz gut ohne diese implementierung gespielt haben.

**Comment by Plushtoast** [comment]
Jo, so würde ich das machen.

**Comment by Plushtoast** [comment]
Ich schätze Foundry releast um Weihnachten die 9er Version. Dann wird es da vorraussichtlich schon genug zu tun geben. Also wandert das hier sowieso ins nächste Jahr.

**Comment by Plushtoast** [comment]
Hm ist glaub auch mal Zeit für ein bisschen Hybris.
Das System wird irgendwann alles können MUHAHaHa *irres lachen*
