### ISSUE TITLE
Sickness + Poison: enemy modifier 

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#66]
When you roll for a sickness / poison, you can enter the enemy modifier manually, but you have to invert the value.
Input field says "Zähigkeit", and the target has a value of 2, you have to enter -2 to work correctly.

When you declare a token as target, it automatically does it right, but regular users may get incorrect results without noticing.

**Comment by Plushtoast** [comment]
I'll add a tooltip.
Also at some point both categories should probably be droppable on the charcter sheet as a temporary effect.
