### ISSUE TITLE
Apply Botch Table effects directly

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#662]

**Comment by Xardai** [comment]
Macht es Sinn Gifte und Krankheiten in dem Zusammenhang mit zu behandeln, die werden ja auch über den Chat ausgegeben und nicht automatisch angewendet

**Comment by Plushtoast** [comment]
Eher nicht. Die Patzertabellen haben allein schon ~100 Einträge und da brauchts nicht noch Krankheiten dazu.
Außerdem verhalten die sich auch anders.
