### ISSUE TITLE
Statuseffekte löschen - auch aus schreibgeschützten Kompendien leider möglich

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#663]
Es ist möglich aus schreibgeschützten Kompendien die Statuseffekt von Items zu löschen.

Das Deaktivieren und aktivieren des Moduls hat den gelöschten Effekt nicht zurückgebracht.
Erst das deinstallieren und installieren des Modules bringt dies zurück.

Gewünschtes Verhalten:
1. Es soll nicht mögich sein, dass z.B. Items/Actors etc., die sich in schreibgeschützten Kompendien befinden, verändert werden können. Dies schliesst die Effekte ein.
2. Unabhängig von "schreibgeschützt": Wenn ich Effekte lösche, dann kommt ein Dialogfenster, in dem das Löschen bestätigt werden muss.

**Comment by Plushtoast** [comment]
2. Nein - Die meisten Effekte sind so volatil, dass die extra Abfrage alles nur ausbremst.
