### ISSUE TITLE
Experience points not reduced for skills while using the number field

### ISSUE THREAD

**Issue by KiroGustavson** [Plushtoast/dsa5-foundryVTT#667]
**Describe the bug**
I am using DSA 5 Core, Compendium, Magic I.
I am creating a new character and increase the entry for a skill. I am not using the + or - buttons. I am entering directly the new value e.g. "body control" from 0 to 10. In my version the number of free exprience points are not reduced for that!

**To Reproduce**
-create new charater
- add human 
- add one point to COU (to gain the window for starting experience points -> choose 1100 EP)
- now you have used 15 EP from 1100
- change to skills tab
- set value for e.g. climbing to 18 ab choose tab to leave the value field (do NOT use the +- buttons)
- switch back to attributes
- you have still 15 / 1100 EP used!
- when you are trying to increase the value using the +- buttons you will not be able to  increase the value more then 11

**Expected behavior**
Needed experience points will be reduced as definied in DSA5

**Screenshots**
![image](https://user-images.githubusercontent.com/93646444/140035281-34705b48-8c75-4080-bbe6-10792b853422.png)
![image](https://user-images.githubusercontent.com/93646444/140035340-66874e8e-2372-4e73-94a7-8b00238710cf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - using the administrators console

**Comment by Plushtoast** [comment]
Your attributes need to be high enough to allow +- to go to higher levels.
Manually editing the input field and automatically updating the ap is neither intended nor will this be implemented.
If you edit the value manually, you have to calculate by yourself.
This is intended to overcome the rules (in your case 18 FW is not allowed for cou 9 only), quickly edit sth or circumvent possible bugs.

**Comment by Plushtoast** [comment]
see also https://github.com/Plushtoast/dsa5-foundryVTT/wiki/de-FAQ

**Comment by KiroGustavson** [comment]
Hi, thank you so much for your fast answer!
