### ISSUE TITLE
Vorteile Zauberer und Geweihter werden nach Login nicht mehr auf AsP und KaP angerechnet

### ISSUE THREAD

**Issue by GMMarkus** [Plushtoast/dsa5-foundryVTT#67]
**Describe the bug**
Vorteile Zauberer und Geweihter werden nach Login nicht mehr auf AsP und KaP angerechnet

**To Reproduce**
Include Vorteile Geweihter und Zauberer
Maximum festlegen mittels Modifikator
Neuer Login
20 AsP und 20 KaP der Vorteile Zauberer und Geweihter tauchen im Statusbalken nicht mehr im Maximum auf

**Expected behavior**
20 AsP und 20 KaP tauchen im Statusbalken doch im Maximum auf

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Plushtoast** [comment]
Hi,

stell sicher, dass du die neuste Version installiert hast und dass du auf dem Magie/Religionstab einen Leitwert eingestellt hast.

Außerdem gab es eine Vereinfachung wie die Vorteile funktionieren. Lösche den Vorteil und ziehe ihn erneut auf den Bogen aus den Kompendien (sofern du das Grundregelwerk hast) oder überprüfe ob ihm Effekt Feld "+20 AsP" bzw. "+20 Kap" steht.

Mehr dazu auch hier:
https://github.com/Plushtoast/dsa5-foundryVTT/wiki/Spellcaster--and--Blessed-One-Creation

**Comment by GMMarkus** [comment]
Hi,

funktioniert leider trotzdem nicht. Immer nach dem reconnect ist es weg. Wenn man dann was irgendwo am Charakter ändert, so taucht es wieder auf.

**Comment by Plushtoast** [comment]
Kannst du mal direkt nach dem Einloggen F11 drücken auf die Konsole wechseln und schauen, ob da ein Fehler kommt.
Falls ja hierher kopieren.
Ich kann das bei mir nicht reproduzieren.

**Comment by GMMarkus** [comment]
In der Konsole kam eine Warnung, dass die Sprache Englisch nicht unterstützt ist. Die habe ich in den Core Settings auf Deutsch umgestellt, jetzt funktioniert es. Im übrigen auch ohne Vorgabe von Spezies, Leiteigenschaft oder eines Zaubers/Liturgie/...

DANKE für die Hilfe!

**Comment by Plushtoast** [comment]
Ok, das sollte trotzdem nicht passieren. Gut, dass wir die Ursache finden konnten. Jetzt kann ich es beheben.
