### ISSUE TITLE
Vorauswahl der Größenkategorie bei Fernkampfangriffen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#675]
Bei Fernkampfangriffen mit ausgewähltem Ziel wäre es prima, wenn die Größenkategorie des Ziels automatisch bei den Einstellungen vorausgewählt wären.

**Comment by Plushtoast** [comment]
Ah das war schon mal drin. Funktioniert nur g erade nicht mehr,

**Comment by Albinosheep** [comment]
Super, dankeschön! :-)
