### ISSUE TITLE
Vergiftete Waffen: Gift wird in Ausrüstung und auf Waffe nicht korrekt verbraucht.

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#676]
**Describe the bug**
Bei der Verwendung von vergifteten Waffen wird das Gift nach dem Auftragen auf die Waffe nicht automatisch verbraucht.
Außerdem wird das Gift nach einem Treffer der Waffe nicht automatisch verbraucht. Es wäre gut, wenn es "Ladungen" hätte.

**To Reproduce**
1. Füge das gewünschte Gift ins Heldeninventar hinzu.
2. Vergifte damit die Waffe. Das Gift im Inventar wird nicht verbraucht.
3. Treffe erfolgreich ein Ziel, füge SP hinzu und wende die TP an. Das Gift auf der Klinge wird nicht verbraucht.

Foundry 0.8.9
DSA Core 2.3.0

**Comment by Plushtoast** [comment]
Das Gift wird erst verbraucht, wenn du auf diesen Button clickst:
![grafik](https://user-images.githubusercontent.com/44941845/141672237-276a525a-7475-4280-9925-5a4232fab1b4.png)

Soll dabei helfen, dass das Gift nicht einfach so immer verschwindet.
Es wird aus dem Inventar eine Ladung des Giftes abgezogen.
Wenn du das Gift auf der Waffe auf "permanent" setzt, wird kein Gift verbraucht.

Funktioniert so wie beabsichtigt. (Siehe auch Tom's changelog video)
