### ISSUE TITLE
Regeneration-angewendet-Haken bei Erholungsproben

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#678]
Wenn man als SL "Schaden anwenden als TP/SP" nutzt, wird inzwischen ein (oder sogar mehrere Haken) angezeigt. Tolles Feature!

Ich fände es sinnvoll, wenn dies auch für Anwendung der Regeneration übernommen werden könnte - und das am besten für SL und Spieler sichtbar! :-)
Dass man dort grundsätzlich nur einmal anwenden kann, steht dazu in meinen Augen in keinen Widerspruch.

**Comment by Plushtoast** [comment]
Duplicate of #598
