### ISSUE TITLE
Regeneration und Eigenschaften über Meister-Menü "Probe anfordern"

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#679]
Ich finde das neue Feature "Probe anfordern" super!
Ich würde mich freuen, wenn man Erholungs- und Eigenschaftsproben samt Modifikator damit ebenfalls anfordern könnte (wie es schon jetzt über die Chat-Kommandos machbar ist)! :-)

**Comment by Plushtoast** [comment]
Kann man im Meistermenü Proben anfordern?
Da kann man doch nur Blind Rolls machen? Meinst du das?

**Comment by Albinosheep** [comment]
Lieber Plushtoast,
danke für deine Nachfrage. Ja das meinte ich. :-)
