### ISSUE TITLE
Bruchfaktor bei Geweihten und Magischen Waffen entfernen

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#682]
Hallo ich habe gerade gesehen das derzeit noch ein Bruchfaktor bei Magischen und Geweihten Waffen und Rüstungen gewürfelt werden kann. Die sind eigentlich unzerbrechlich. Deswegen würde ich das hier gerne als Feature Request einreichen.

**Comment by Plushtoast** [comment]
Einfach nicht auf den Button druecken

**Comment by Plushtoast** [comment]
Das wird drin bleiben. So kann jeder selbst Entscheiden, ob der Erzdämon nicht doch irgendwas zerstört.
Außerdem gibt es bestimmt irgendwo in DSA eine Regel, die das dann trotzdem erlaubt...
Eine Warnung kann ich dazu schreiben.
