### ISSUE TITLE
Doppelter Schaden bei Untoten mit Hiebwaffen

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#683]
Hallo es ist ja möglich die Waffen geweiht und magisch zu machen, mit sie bei Dämonen regulären Schaden verursachen. Wäre es noch möglich eine abfrage einzubauen die bei Untoten( Skeletten) den doppelten Schaden macht? Bei der Waffengattung Hiebwaffen und eine Immunität für Pfeile und Fechtwaffen?

**Comment by Plushtoast** [comment]
Wo steht diese Regel? Prinzipiell kein Problem

**Comment by ghost** [comment]
Hier bitte bei Sonderregeln. https://ulisses-regelwiki.de/Best_Skelett.html das durch das Nekromanthäum kommen ja bald mehr Skelette.
