### ISSUE TITLE
Kein Magisch und Geweiht bei Magischen/Geweihten Wesen

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#684]
Hallo man kann Wesen nicht Magisch oder Geweiht zuteilen, wie zb.: bei einem Elementar oder Dämon. Es wird nicht Blau hinterlegt.

**Comment by Plushtoast** [comment]
Ich weiß leider nicht was du meinst

**Comment by Plushtoast** [comment]
Gechlossen in Ermangelung von Details
