### ISSUE TITLE
Aktiver Effekt: Zauber/Liturgiemodifikatoren haben effekt auf alle!

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#687]
**Describe the bug**
Wird als Effekt einer der Effekte für Zauberssprüche (vermutlich auch bei Liturgien, aber das habe ich nicht getestet) verwendet, wird der Effekt leider bei allen Zaubersprüchen angezeigt und kann verwendet werden.

**To Reproduce**
1. Effekt anlegen
2. Z.B. Zauberspruch Teilprobenmodifikator auswählen
3. Eigen und Fulminictus 1|1|1 eingeben
4. Andere Zauberspruch Probe öffnen: Der Modifikator kann überall gewählt werden

**Expected behavior**
Wenn der Modifikator nur bei dem Eingegebenen Zauber (Liturgie usw.) ausgewählt werden kann, wie es bei den Talenden ja schon funktioniert.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/141996619-25c9b46e-d35a-4897-be31-41d8421fe7fd.png)

**Comment by Plushtoast** [comment]
Das ist auch tatsächlich so gedacht. Text im Wertfeld einzutragen, ist nicht vorgesehen. Einen Modifikator pro Zauber gibt es nur über das Effektfeld mit FW.
