### ISSUE TITLE
Magie ist stackbar

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#690]
Hallo ich habe gerade herrumprobiert und es ist möglich  Statusse die von einem Zauber(oder mehrere) kommen zu stacken das geht laut Regelwerk nicht.

https://ulisses-regelwiki.de/Magie_Spezielle-Regeln-fuer-Spruchzauber_Gestapelte-Zaubereffekte.html

In meinem Falls habe ich zweimal Paralyse auf einen Gegner gewirkt und er hatte die zweite Stufe Paralyse ohne das ich die nötige Qs erreicht zu hatte.

**Comment by Plushtoast** [comment]
Das ist kein Bug. Es bleibt dir frei überlassen so viel schindluder mit den Regeln zu treiben wie du möchtest.
Generell hat das System so wie es ist, keine Beschränkungen. 
Außerdem ist das programmiertechnisch schwer zu lösen. Wird kaum den Aufwand wert sein
