### ISSUE TITLE
/ch Chat-Befehl wird immer als "Alrik" gewürfelt

### ISSUE THREAD

**Issue by TheFrazer** [Plushtoast/dsa5-foundryVTT#694]
**Describe the bug**
Wenn über den /ch Chat-Befehl eine Probe gewürfelt wird, wird die immer von einem Alrik mit 12/12/12 und FW 0 ausgewürfelt.

**To Reproduce**
1. Einem Spiel als Spieler mit einem zugewiesenen Charakter beitreten
2. Im Chat zB "/ch Kraftakt" eingeben und den Wurf ausführen.

**Expected behavior**
Sollten nicht die Werte des eigenen Spielers benutzt werden? Vielleicht verstehe ich das Feature auch falsch?!

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16038255/142511756-f8dd342a-90c6-4cae-af5a-c0e86be786e1.png)

**Comment by Plushtoast** [comment]
Jau du verstehst das Feature falsch.

/ch ist immer dann zu benutzen, wenn es gar keinen token gibt. Für eine zufällige unerwartete Bekanntschaft.
Was du suchst ist /sk

Auch hilfreiche der /help Befehl, denn da gibt es noch mehr: /at /pa etc.

**Comment by TheFrazer** [comment]
Ups. Über /help hatte ich es überhaupt erst gefunden, aber scheinbar ganz gekonnt das "ohne Charakter" überlesen...
