### ISSUE TITLE
Masters Workshop: The Forge Assets Library nicht kompatibel

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#695]
**Describe the bug**
Beim hosten über The Forge hat das Modul Masters Workshop das Problem, dass der Tokenordner nicht gefunden wird. Das liegt daran, dass Forge automatisch bei der Installation der Module die Assets im Modul in die Assets Library von Forge schickt.
Dabei wird ein Pfad erzeugt der so aussieht: https://assets.forge-vtt.com/FORGEID/modules/dsa5-mastersworkshop/icons/characters/token.
Das kann nach dem Start eines Tools des Moduls dann zwar ohne Probleme angepasst werden, sobald eines der Tools dann aber beendet und neu gestartet wird, zeigt es wieder keine Bilder an und der Pfad muss einmal geöffnet und neu ausgewählt werden.

Außerdem ist die Auswahl des Pfades anders. Lokal reicht es den Ordner auszuwählen. In Forge muss man im Ordner ein Bild anklicken und dann den Ordner auswählen.

**Screenshots**
Fehler beim Start des dsa5-mastersworkshop
![grafik](https://user-images.githubusercontent.com/80099175/142648125-c9b2565f-efb7-4a35-b3f4-99accf955caa.png)

Ansicht nach dem neu Öffnen eines Tools:
![grafik](https://user-images.githubusercontent.com/80099175/142648943-555c703b-7e88-45bf-b574-40a876a17aba.png)

**Comment by argentorum** [comment]
Hierzu sei noch ergänzend gesagt, wenn es nicht sowieso schon klar ist: Davon sind natürlich auch alle anderen Module, bei denen Sachen dann in Assets gesteckt werden, betroffen, z.B. auch die Icons von dsa-core.

**Comment by Plushtoast** [comment]
Ist das Problem neu?
Bzw die Bilder funktionieren nur in der Werkstatt nicht aber überall sonst normal?

**Comment by argentorum** [comment]
Das Problem scheint neu zu sein, betrifft aber anscheinend z.B. nur Items/Actors etc., die vor dem großen Forge Strukturupdate in Welten importiert wurden (importierte Bilder existieren aber noch, die Fehlermeldung tritt nur beim Pfadwechsel auf). Frisch importierte Items etc. zeigen mit ihren Icons auf den korrekten Pfad. Von daher also Korrektur: Aktuell scheint sich das Issue tatsächlich nur auf die Werkstatt zu beschränken, auch wenn die Fehlermeldungen von der Art her identisch sind.

**Comment by Plushtoast** [comment]
Den "Anfangspfad" bekomme ich evtl nicht gefixt. Der Rest passt aber glaub dann.
