### ISSUE TITLE
GM Menu: receive payment

### ISSUE THREAD

**Issue by Nostros-BE** [Plushtoast/dsa5-foundryVTT#696]
**Describe the bug**
With the GM Menu, the option "Receive payment" even applied tor a selection of players makes a button to appear in the chat. Then **all the other players can click and collect** money on their own.

**Expected behavior**
Make appear in the chat only a text message confirming payment to the selected players. Without button.

**Screenshots**
![image](https://user-images.githubusercontent.com/64594454/142704235-af5c1e46-c10e-4484-b8d6-e010d1f6927a.png)

**Comment by Plushtoast** [comment]
Honestly I don't want to invest time in things just because players have to click on everything everywhere all the time.
Do you not talk with your players? Can they not control their impulses?

**Comment by Plushtoast** [comment]
The implications for this feature are too big for such a small improvement.
