### ISSUE TITLE
Cumulative check: modification affecting the success of a roll does not modify the total number of success

### ISSUE THREAD

**Issue by Nostros-BE** [Plushtoast/dsa5-foundryVTT#698]
**Describe the bug**
It is possible to improve the result of a roll, for instance in the case of a luck blessing, and then transform a failed roll in a success,
If we edit the roll to adapt the result and make it a success, the number of collected QL is not updated. 

**Expected behavior**
Update the number of collected QL after edit and change of the result of a roll in a cumulative check.

**Screenshots**
![image](https://user-images.githubusercontent.com/64594454/142705427-bcbaf67c-03e1-47ac-9de2-7f065de1100c.png)

**Comment by Plushtoast** [comment]
You can edit the QL on the character sheet in the cumulative check directly

**Comment by Plushtoast** [comment]
This is a very complicated fix with various dependencies (already complicated enough for the combat system).
I am not sure, when and if I am going to change this.
