### ISSUE TITLE
Neue Kampfsonderfertigkeiten bei Angriff nicht nutzbar.

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#699]
**Describe the bug**
Hi,
die neuen Kampfsonderfertigkeiten aus Katakomben und Ruinen sind bei einem waffenlosen bei Angriff leider nicht auswählbar.

![Kein kneipenkopfstoß](https://user-images.githubusercontent.com/88042114/142717892-de450d1d-f573-4bea-94b7-7c27e0165d1c.jpg)

**Comment by Nellkir** [comment]
Ich schätze mal, du meinst den Kneipen-Kopfstoß aus dem SL-Meisterschirm Begleitheft.
Nein, da diese sich ausschließlich auf die Prügelpunkte-Schlägereien beziehen, und diese Prügel-Mechanik (noch?) nicht ins System implementiert wurde (siehe Ticket 701), kann man sie bei den Kämpfen auch noch nicht auswählen.
Das muss man erstmal manuell erledigen.
