### ISSUE TITLE
Prügelpunkte implementieren

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#701]
**Is your feature request related to a problem? Please describe.**

Hi,
das nachhalten von Prügelpunkten ist kein Problem, wenn eine komplett frischer Held in eine sehr kontrollierte Schlägerei (z.B. Boxkampf) geht. Am Ende einfach verlorene LeP mal Tabelle nehmen, zurückerstatten, fertig. Geht jedoch eine bereits verletzte Gruppe in eine wilde Schlägerei, bei der auch noch Unfälle passieren und zwischendurch normaler Schaden, z.B. durch einen Sturz vom Balkon oder ein gezücktes Messer entsteht, müssen die Prügelpunkte akribisch nachgehalten werden. Dies ist eine Aufgabe für die Foundry prädestiniert ist.   

**Describe the solution you'd like**
Um es nicht unnötig kompliziert in der Entwicklung zu machen, könnte das Anrichten von Prügelpunkten eine Option oder zusätzliches "Manöver sein", das nur bestimmten Waffen zur Verfügung steht. Die neue Ressource (Prügelpunkte) speist sich 1:1 aus den angerichteten SP solcher Angriffe. Neben der neuen Ressource befindet sich ein Button mit dem man auf der Tabelle zur Wiedererlangung der LeP würfelt. Die Prügelpunkte werden mit dem Faktor der Tabelle verrechnet, das Ergebnis auf die LeP angerechnet und der Wert der Prügelpunkte auf 0 gesetzt.
Die speziellen Prügel-Kampfsonderfertigkeiten könnten bei Anwahl die Prügelpunktoption direkt mitauswählen, dann müssen die Spieler nicht darauf achten. Ich würde auf jeden Fall den Sonderfertigkeiten nicht Beibringen von vorneherein Prügelpunkte anzurichten. 

**Describe alternatives you've considered**
Etwas einfacher könnte es sein, die Möglichkeit Prügelpunkte anzurichten an Kampftechniken (Raufen, (Einhand-)Hiebwaffen, evt. Wurfwaffen) statt Waffen zu binden. Damit würde man sich natürlch spätere aAsdifferenzierungsmöglichkeiten nehmen, aber vielleicht den Entwicklungsaufwand reduzieren.

**Additional context**
Dank der schnellen und doch tiefen Abwicklung durch die DSA-Foundry Module erfreuen sich bei uns Aufwärmkämpfe, Zwischenkämpfe, Nebenkämpfe und Vorfinalkämpfe endlich wieder großer Beliebtheit. Für Kneipenschlägerei und Boxkampf gilt ähnliches, jedoch wird durch den erhöhten Verwaltungsaufwand zumindest bei ersterer die Freude etwas getrübt. Eine implementierung von Prügelpunkten würde der guten alten RP-Kneipenschlägerei sicherlich zu einer wahren Renaissance verhelfen, nachdem die Abschaffung der (problembehafteten) Ausdauer aus DSA 4 ihr vorerst ein unrühmliches Ende bereitete.

**Comment by Plushtoast** [comment]
Die Tavernen und Prügelsachen sind nur eine Dreingabe im Modul.
Die Prügelregeln sind viel zu aufwendig und wären ein riesiges Feature für etwas sehr periphäres.
Da sehe ich für geraume Zeit keine Möglichkeit das umzusetzen.

**Comment by Zonenpenner** [comment]
Oki, danke für die Info.
