### ISSUE TITLE
GM Menu: Bars&Taverns - alcohol field not updated after selection of regions

### ISSUE THREAD

**Issue by Nostros-BE** [Plushtoast/dsa5-foundryVTT#706]
**Describe the bug**
In the module Master's toolbox, with the tavern generator, there is a possibility to chose the regions for the alcohol field.
By default, the entire list of regions is displayed. 
But after a selection of regions and validation (click on "ok'), the info reported in that field remains unchanged.

**Expected behavior**
Update the alcohol field with the list of selected regions

**Screenshots**
![image](https://user-images.githubusercontent.com/64594454/142755780-a1aa09f6-d71c-4737-8ae4-da64d2e573ab.png)

**Desktop :**
-self hosting server

**Comment by Plushtoast** [comment]
It should still take effect. It's only the visual cue that is missing.
