### ISSUE TITLE
Aventurische Namen

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#710]
**Is your feature request related to a problem? Please describe.**

Hi,
ich habe mich gefragt, ob jetzt, wo der wichtigste Inhalt des Quellenbandes "Aventurische Namen" - nämlich die Namen -  in Form des Namensgenerators implementiert wurde, eine seperate Veröffentlichung von Aventurische Namen für Foundry überhaupt noch im Ramen des Möglichen liegt.
Falls doch ist dieser Content Request hinfällig.
Falls tatsächlich nicht, wäre es total super, wenn die Besitzer des Meistermoduls das Werk irgendwann auch als Journaleintrag bekommen könnten, damit das wie die anderen Quellenbände über Foundry aufrufbar wäre. Außerdem gibt es darin noch 3 Vorteile, 5 Nachteile und 2 Sonderfertigkeiten.

**Comment by Plushtoast** [comment]
Mit Journals ist auf keinen Fall mehr zu rechnen.
Die Fähigkeiten könnten aber ggf. noch auftauchen.

**Comment by Zonenpenner** [comment]
Schade
Sollte es an Datengröße, Autoren- oder Verlagsrechten, Implementierungsaufwand oder anderen, von mir nicht beadachten Gründe liegen, kann man da nichts machen. Bevor es an reiner Editierarbeit scheitert, würde ich mich freiwillig melden. Wäre ja nett, wenn man für die Quellenbände in Foundry dereinst nicht mehr auf .pdfs angewiesen wäre.

**Comment by Plushtoast** [comment]
Also im Moment und in mittlerer Zukunft sind dafür auf keine Fall Kapazitäten vorhanden.
Außerdem gibts auch noch andere damit verbundene Probleme.

**Comment by Zonenpenner** [comment]
Oki, danke für die Erörterung.
