### ISSUE TITLE
Schadenspunkte

### ISSUE THREAD

**Issue by DSAKalle** [Plushtoast/dsa5-foundryVTT#711]
Sicher ein Anfänger-Fehler. Im Cobat kann ich als GM nicht die "Schadenspunkte" auswürfeln. was mache ich falsch? Und ja, die Gegner wurden anwiesirt, die Reaktion ausgewürfelt, aber bei Erfolg kann ich trotzdem keine SP zuweisen.

Bi dankbar über jeden Tip

Gruß

Kalle

**Comment by Plushtoast** [comment]
Also ich würde vermuten, dass du statt mit der Waffe mit dem Kampftalent gewürfelt hast.

Korrekter Vorgang:
Ins Ziel nehmen:
![grafik](https://user-images.githubusercontent.com/44941845/142774602-82243513-e80e-444c-9f8b-a6687a45d317.png)

Angriff würfeln (da gibt es mehrere Möglichkeiten den Angriff auszulösen):
![grafik](https://user-images.githubusercontent.com/44941845/142774608-b9152792-470d-439f-965f-62af45d1269e.png)

Jetzt sieht es so aus:
![grafik](https://user-images.githubusercontent.com/44941845/142774636-b33225b3-2908-4e8d-875d-cd4fe3181939.png)

Dann Reaktion durchführen und der Schadenswurf erscheint bei der ursprünglichen Nachricht und das Ergebnis am Ende.
![grafik](https://user-images.githubusercontent.com/44941845/142774662-96985b25-e98b-47f0-a526-0ef6143bf495.png)

**Comment by Plushtoast** [comment]
Und hier gibts noch ein Erklärvideo von Tom
https://www.youtube.com/watch?v=ptDNhjR7f78&ab_channel=VTTom
