### ISSUE TITLE
Rüstungsschutz falsch: Kombinierte Rüstungen ohne Rüntungszonen führt zu falsches RS und kaputten Rüstungen.

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#713]
**Describe the bug**
Sobald ein Actor 2 Rüstungen trägt, kommt es erstmal grundsätzlich zu einer falschen Berechung des RS (siehe auch #705, Screenshot 1). Wenn ich aber dann eine der beiden Rüstungen manuell anpasse, dann kann beim Kampf nicht mehr "keine Reaktion" ausgewählt werden, es kommt dann zu einer sehr langen Fehlermeldung in der Console (Screenshot 2). Außerdem ist beim Schaden kein Rüstungsschutz mehr vorhanden (Screenshot 3).

Ich habe versucht das irgendwie zu dokumentieren, tue mich da absolut schwer.

**To Reproduce**
1. 2te Rüstung zu einem Actor hinzufügen.
2. Angriff auf Actor durchführen und RS beim Schaden prüfen
3. Rüstungsschutz und/oder BE in einer der beiden Rüstungen anpassen
4. Angriff auf Actor durchführen und dann Reaktion "keine Reaktion" benutzen. Danach kommt es in der Console zu ner ewig langen 

**Expected behavior**

**Screenshots**
Falsche Rüstungsberechnung (Screenshot 1):
![grafik](https://user-images.githubusercontent.com/80099175/142776083-28279ff1-3aee-4c43-b855-523fdf2c044d.png)

Fehlermeldung in der Console (Screenshot 2):
![grafik](https://user-images.githubusercontent.com/80099175/142776661-e6f0a6ad-d687-4af3-bae8-43bdb0e30e84.png)
Und hier komplett als txt: 
[Fehler Console.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/7576961/Fehler.Console.txt)

Falsche Rüstung bei modifizierter (Screenshot 3):
![grafik](https://user-images.githubusercontent.com/80099175/142775896-832f5e9e-9b51-466b-8153-5ad8d737c09b.png)

**Comment by UralterMannII** [comment]
Bei mir habe ich ein ähnliches Verhalten (Reproduzierbar) ohne Fehler auf der Console:

Erste Variante:
1. Lederrüstung führt zu 3 RS bei der TP berechnung 
2. Lederrüstung + normale Kleidung: RS 0 bei der TP berechnung 

Zweite Variante: 
1. Lederrüstung führt zu 3 RS bei der TP berechnung 
2. Lederrüstung + schwere Kleidung: RS 6 bei der TP berechnung 

Keine Fehler auf der Console, im Log-File auch kein Fehler protokolliert.

**Comment by Plushtoast** [comment]
Fix is raus.
Könnte aber noch ein Problem mit Armory 2 und Rüstungszonen geben.
