### ISSUE TITLE
Zauberschaden

### ISSUE THREAD

**Issue by Ben528491** [Plushtoast/dsa5-foundryVTT#723]
Manche Sonderfertigkeiten erhöhen den Schaden von Zaubern. Beispiele:
Scholar von Bethana; https://ulisses-regelwiki.de/scholar-der-halle-des-vollendeten-kampfes-zu-bethana.html
Destruktor: https://ulisses-regelwiki.de/Destruktor.html

Aus dem Grunde wäre es sehr hilfreich, wenn bei den Effekten eine Option "Zauberschaden" implementiert werden könnte, um solche SFs abbilden zu können.

**Comment by Plushtoast** [comment]
Also die Bedingung von Destruktor sehe ich erstmal nicht kommen.
