### ISSUE TITLE
Combat Tracker: Mark Defeated als eigener Status in DSA einbinden

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#727]
Aktuell kann man im Combat Tracker den "Mark Defeated"-Status setzen. Das führt u.a. dazu, dass ein Akteur im Combat Tracker transparent dargestellt wird und beim Klicken auf "weiter" übersprungen wird. Das ist praktisch.

<img width="777" alt="Mark-Defeated-bug" src="https://user-images.githubusercontent.com/41292141/144712978-96b36365-c259-40bd-b0bd-4722d7ec5da7.PNG">

Für DSA gibt es zudem den Status "Handlungsunfähig", der automatisch ab 5 LeP gesetzt wird. Dieser hat aber sonst keinen Einfluss auf den Combat Tracker.

Soweit so gut. 

Wenn ich in einem Kampf den Status "Mark Defeated" setze und den Kampf später beende, bleibt bei einem Akteur der Status "Mark Defeated" weiterhin gesetzt. Ich habe keine Möglichkeit ihn über die Statusanzeige oder das Charaktersheet wieder abzuwählen. Ich kann ihn auch außerhalb eines Kampfes nicht anwählen. 

Als **Workaround** kann ich den Akteur lediglich wieder zum Combat Tracker hinzufügen. Beim ersten Klick auf "Mark Defeated" wird der Akteur in dem Combat Tracker dann transparent dargestellt, behält aber noch seinen Status. Beim nächsten Klicken auf "Mark Defeated" wird der Status aufgehoben.

Vorschlag:
Ergänzen des Status "Mark Defeated" bei den DSA-Akteuren, der auch mit dem im Combat Tracker verknüpft ist. Damit könnte man den Status auch über den Akteur setzen bzw. aufheben. 
Den Status "Handlungsunfähig" mit seinen Mechaniken kann man unabhängig davon erhalten.

Foundry 0.8.9
Game System DSA 2.4.1

**Comment by Plushtoast** [comment]
Das ist in der Tat etwas was mich selbst schon lange nervt.
Als extra  Status erscheint es mir irgendwie auch unpraktisch.
Am naheliegendsten ist es, im Token HUD ein Button einzufügen, aber auch nicht super praktisch.

**Comment by Albinosheep** [comment]
Danke Plushtoast fü deine schnelle Rückmeldung!
Bisher ist es halt so, dass man alle andere Statussachen sowohl über den Actor und über den Token setzen kann. Ich weiß nicht, ob es für casual-gamer intuitiv wäre, warum das bei diesem Status nicht der Fall ist.
Andererseits ist der "Status" auch gelöscht, wenn man einen Token von einem Charakter frisch auf die Map zieht. Das kann vor- als auch nachteilig sein. Ich selbst bin mir nicht sicher, wie ich es am besten finden soll.
