### ISSUE TITLE
Verbesserungsideen Vorauswahl NSC Zucht

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#728]
Die NSC-Zucht ist sehr praktisch!
Ich fände es sinnvoll, wenn die Vorauswahl bei Aventurische Namen, Spezies und Kultur aufgrund der letzten Auswahl gespeichert bleiben würden. Aktuell muss man die jedes Mal neu auswählen - außer man spielt in Al'Anfa. 

Außerdem fände ich eine "Schloss-Funktion" sinnvoll, die eine Auswahl vor Veränderung durch "alles zufällig" schützt. So könnte das ganze auch per Ausschluss zufällig generieren.

Siehe auch ##729

Foundry 0.8.9
Game System DSA 2.4.1
Master's Workshop: 2.4.0

**Comment by Plushtoast** [comment]
Schloss - nein. Dazu kann man schon jede Zeile einzeln auswürfeln.
