### ISSUE TITLE
[Effekte von Sonderfertigkeiten] Einiges scheint hardcoded oder versteckt zu sein?

### ISSUE THREAD

**Issue by Matt-Ceb** [Plushtoast/dsa5-foundryVTT#730]
Hi, hier geht es speziell um die Machtvolle Meisterparade. Einer meiner Spieler besitzt diese für seinen SC, also wollte ich sie in Foundry einbinden. Da Kompendium 2 nicht veröffentlicht ist, wollte ich einfach die Meisterparade kopieren und verändern, aber... Nun... In Foundry selbst tut sie nichts. Es gibt keiinen Effekt und keinen Statuseffekt den ich von -2 auf -1 setzen könnte. (Dieses 'Problem' gibt es auch bei einigen anderen SFs, aber hier fältt es wieder akut auf.)

Daher der Request: Wäre es möglich alle Effekte von SFen 'sichtbar' zu machen, so dass man daraus eigene SF bauen kann? (Wäre auch nützlich wenn man eine SF für seinen Tisch abändern aber trotzdem 'automatisiert' halten möchte.)

Sorry wenn das zu wirr war. Daher mal ganz knapp: Was sorgt bei Meisterparade dafür, dass nur -2 anstatt -3 bei multiplen Paraden berechnet wird, und wie kann ich es auf -1 setzen, falls überhaupt? Wäre es möglich diese Effekte für den user sichtbar/veränderbar zu gestalten?

**Comment by Plushtoast** [comment]
Wir befassen uns nicht mit problemen aus Büchern die wir nicht umgesetzt haben. Sonst springen wir ständig vom hin und her ohne jemals etwas fertig bekommen zu können. Viele sonderfertigkeiten müssen zudem hardcoded sein, weil deren Funktion kaum angemessen abzubilden sind.
Insofern ist die Antwort: nein, auf Kompendium 2 warten

**Comment by Plushtoast** [comment]
Wird übrigens dann ohne modul funktionieren und is hoch auf unserer Liste. Aber dauerte halt noch
