### ISSUE TITLE
[Zauberzeichen fehlen]

### ISSUE THREAD

**Issue by Matt-Ceb** [Plushtoast/dsa5-foundryVTT#731]
Man kann zwar die SF Zauberzeichen wählen und hinzufügen, aber de Sonderfertigkeit von core, magic-1 und compendium hat kein Zauberzeichen in sich enthalten. (Oder ich bin MASSIVST blind.)

**Comment by Plushtoast** [comment]
Ich weiß ehrlich gesagt nicht was Zauberzeichen sind. Regelverweise und Ideen würden helfen.
Davon abgesehen können wir nur mehr über Zeit anbieten aber halt nicht alles.

**Comment by TheFrazer** [comment]
Aus dem Grundregelwerk vor allem die Schutz- und Bannkreise (GRW S.266)
Herbarium (weil es bei euch auf der Liste steht): Zeichen der Haltbarkeit (Herbarium I S.144)

Dann gibt es noch einige in den Streitenden Königreichen, aber das steht ja vermutlich noch nicht so schnell an (S. 171: Ahnenzeichen)

Kurze Zusammenfassung:
Man malt das Zeichen (Malen&Zeichnen) oder es existiert bereits. Danach kann man das Zeichen mit AsP aufladen (erfordert keine Probe). Das ganze muss nicht direkt aufeinander erfolgen. Das Aufladen wird als (Kurz-)Ritual gewertet; kann nicht gesteigert werden. Das Aktivierungsritual/Aufladen bekommt man mit der SF Zauberzeichen automatisch.

Da die Zeichen selbst AP Kosten, ist es, denke ich, eine passende Lösung diese wie (magische) Berufgeheimnisse zu Werten. Vielleicht mit einem "Auslösen" Button oben, ähnlich zu Zaubertricks, die dann aber halt die passende Menge AsP abzieht.
