### ISSUE TITLE
Meister Menü: Geld auszahlen an Actor ohne Besitzer

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#732]
**Describe the bug**
Wird ein Actor ohne Besitzer ins GM Menü gezogen und diesem Actor dann Geld ausgezahlt, erscheint das Auszahlen bei allen Spielern. Klicken diese dann auf Aufzahlen landet das Geld im Actor der ihnen als Spieler zugeordnet ist. Dies kann jeder Spieler für sich ausführen.

**To Reproduce**
1. Actor ohne Besitzer ins GM Menü ziehen
2. Geld an diesen Actor auszahlen
3. Als Spieler im Chat auf "Auszahlen" klicken

**Expected behavior**
Entweder sollte es nicht möglich sein an Akteuere ohne Besitzer etwas auszuzahlen oder bei denen sollte das Geld direkt in den Actor gehen ohne dass im Chat etwas erscheint.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/144806197-55587a72-6b49-4569-8c24-92e2d911ec35.png)

**Comment by Plushtoast** [comment]
Duplicate of #696

**Comment by Plushtoast** [comment]
Hab das eben erst anderswo abgelehnt.
Ich müsste das komplette Feature neu schreiben und seh das nicht passieren.
Mir fällt auch nicht ein warum man NSCs Geld geben müsste.

**Comment by vt-tom** [comment]
Sorry fürs Duplikat, ich gebe die Antwort an den Ticketersteller weiter. 
Danke
