### ISSUE TITLE
Kauffaktor bei Händlern wirkt sich nicht auf die Preise aus

### ISSUE THREAD

**Issue by Marvball** [Plushtoast/dsa5-foundryVTT#735]
Leider wirkt sich eine Änderung des Kauffaktors bei Händlern nicht auf die Preise aus.

Zum Testen wurden jegliche andere Module abgeschalten.

![händler_dsa_foundry](https://user-images.githubusercontent.com/22493894/144909075-5b0a2b84-cadb-4afd-a31d-d81ebd166a17.png)
n.

**Comment by Plushtoast** [comment]
Kann da kein Problem entdecken
![grafik](https://user-images.githubusercontent.com/44941845/145002517-37594830-58ed-41cb-9bca-37bbda2df889.png)

Kann es sein, dass du Kauf- und Verkaufsfaktor verwechselst?

Das Schweinchen multipliziert sich mit dem Preis, wenn der Händler Dinge verkauft und wird dann im unteren Kreis als Zahl nach dem Slash angezeigt. Die Münzen multiplizieren sich mit dem Preis wenn der Händler Dinge von den Spielern kauft.
Änder die 1 neben dem Schweinchen und du hast was du suchst.

**Comment by mckee14** [comment]
So rein theoretisch, wie gross wäre der Aufwand, die Felder oben zu
tauschen, damit sie die gleiche Reihenfolge haben wie unten im sheet? Frage
für einen Freund! :)

Plushtoast ***@***.***> schrieb am Di., 7. Dez. 2021, 10:27:

**Comment by Marvball** [comment]
Den Unterschied und die Funktionsweise habe ich schon verstanden. Wenn ich beim Schweinchen den Faktor ändere, dann funktioniert es auch und die Preise für die Waren ändern sich.
Eine Änderung des Faktors daneben bewirkt allerdings nichts. Die Preise bleiben dieselben.
Auf meinem Bild siehst du, dass ich zwei unterschiedliche Werte oben gewählt habe, 1 und 0.1
Die Preise unten sind aber identisch, die Produkte Kosten im Verkauf genausoviel wie im Ankauf obwohl sie im Ankauf nur 1/10 des Verkaufspreises sein sollten. Oder verstehe ich da was falsch?

**Comment by Plushtoast** [comment]
Die Felder sind Listenpreis/Verkaufspreis in der Inventarliste

Einkaufspreise sieht man nur wenn man als Spieler mit dem Händler handelt.
Die Einkaufspreise beziehen sich auf das, was der Spieler im Inventar hat. Händler kaufen generell alles...einen Filter was sie exklusiv kaufen sollen gibt es nicht.

**Comment by Plushtoast** [comment]
So: 
![grafik](https://user-images.githubusercontent.com/44941845/145013663-36afea33-8098-429a-8562-c02f01895baf.png)

Links is der Einkaufsfaktor eingerechnet.

**Comment by Plushtoast** [comment]
Ich seh jetzt hier nicht so Handlungsbedarf, aber ihr könnt gerne mal etwaige Änderungswünsche hier anhängen #736

**Comment by Marvball** [comment]
Ah perfekt. Dann entschuldige ich mich für die unnötige Störung. Danke für die Hilfe! Echt toll, was ihr hier auf die Beine stellt! Weiter so

**Comment by Plushtoast** [comment]
#736 werden händleränderungen aufgelistet/gesammelt
