### ISSUE TITLE
Kampf: Angriff über Kampffertigkeit triggert keine Reaktion

### ISSUE THREAD

**Issue by Niemand-001** [Plushtoast/dsa5-foundryVTT#741]
Voraussetzung: Ein Ziel ist ausgewählt

Würfe auf Talentfertigkeiten triggern eine Reaktion (Reaktionsbutton im Chat).
Würfe auf die Kampffertigkeiten tun dies nicht. (Also NICHT der Wurf über die Probe im Kampfmenü und auch nicht über die Probe direkt hinter den Waffen, sondern die direkt hinter der Kampffertigkeit.) Stattdessen wird auch bei erfolgreicher Attackeprobe das Ergebnis als gescheitert gewertet.

![grafik](https://user-images.githubusercontent.com/83836835/145185539-b109a43c-6885-4618-98da-898665800627.png)

![grafik](https://user-images.githubusercontent.com/83836835/145185668-c2954fd4-1a25-4bbc-b848-89b57fa598bc.png)

**Comment by Plushtoast** [comment]
Ja das ist jetzt nicht wirklich ein Bug. Wenn man den opposed hier würfelt fehlen einfach die ganzen modifikatoren und Datensätze.
Du drehst hier mit nem Hammer ne Schraube rein.

**Comment by Plushtoast** [comment]
Ich kann das natürlich ändern, aber wozu habt ihr das überhaupt so gemacht?...

**Comment by Niemand-001** [comment]
Da hast Du Recht. Allerdings sieht es so aus als würde es funktionieren, also denken Spieler:innen, dass es funktioniert. ;-)

Zudem gab es in früheren DSA-Editionen deutlich mehr als ein waffenloses Kampftalent. Die alten Spieler:innen kommen also nicht unbedingt drauf, dass mit dem waffenlosen Angriff auch zuverlässig das Talent Raufen gemeint ist.  

Aber wichtiger: Manchmal wird am Strand eine Krabbe aufgehoben und als improvisierte Wurfwaffe genutzt, im nächsten Moment vielleicht eine Miesmuschel. Da ist es einfach praktisch, wenn man schnell eine Probe auf die Fertigkeit einschieben kann und die Reaktion getriggert wird. (Klar alternativ kann man diese "Waffen" als Item erstellen oder manuell die Verteidigungsaktion aufrufen. Das ist aber weniger komfortabel.)

Ich denke also daran, dass wie bei den Talentfertigkeiten der Reaktionsbutton kommt. Dann kann man fix die Verteidigungsaktion machen und muss nur noch den Schaden manuell regeln. (Nagut..und die Modifikationen..trotzdem bequemer. :-) )

**Comment by Niemand-001** [comment]
> Ich kann das natürlich ändern, aber wozu habt ihr das überhaupt so gemacht?...

Aufgefallen ist es mir, als ein Spieler eine Raufenattacke machen wollte und dachte, er müsse dann bei _Raufen_ klicken und nicht bei _waffenloser Angriff_ .
