### ISSUE TITLE
[v9 Beta] - Armatrutz wirft einen FEhler in der Console

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#744]
**Describe the bug**
Bei Anwenden des Armatrutz Effekts, gibt es einen Fehler in der Konsole:
Der Effekt scheint aber korrekt übertragen zu werden!

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/145191270-4b20ad97-79f8-4d6c-98b6-c2ad185ae753.png)

**Comment by Plushtoast** [comment]
Kann ich nicht reproduzieren. Brauch ich mehr Info.

**Comment by Plushtoast** [comment]
Ah im Combat k habs
