### ISSUE TITLE
[v9 Beta] Fehlermeldung bei Import "Geheimnis des Drachenritters"

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#748]
**Describe the bug**
Beim Import vom Abenteuer "Geheimnis des Drachenritters" erscheint in der Console eine Fehlermeldung. Es scheint auf den ersten Blick aber alles importiert worden zu sein.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/80099175/145198660-0acd8aa9-3d98-4bc2-a5ca-16f4a3ba6369.png)

**Comment by vt-tom** [comment]
Bei Rabenkrieg genau dasselbe:
![grafik](https://user-images.githubusercontent.com/80099175/145198967-c53069cd-1f0d-4293-be7f-cee4753f0c22.png)

Plus noch ein Fehler:
![grafik](https://user-images.githubusercontent.com/80099175/145199014-91739984-24bf-487b-b0d5-8a6145b5e43c.png)

**Comment by Plushtoast** [comment]
Ja das sind Fehler die bleiben.
Haben keinen nachteiligen Effekt
