### ISSUE TITLE
Bruchfaktor Rundungsfehler

### ISSUE THREAD

**Issue by TheFrazer** [Plushtoast/dsa5-foundryVTT#751]
Wenn bei, zum Beispiel, einem Großschild mit 30/30 Strukturpunkten der Bruchtest gewürfelt und nicht geschafft wird, werden 7 Strukturpunkte abgezogen. Damit hat man 23/30, was noch nicht als Beschädigung gewertet wird. Erst bei 22/30 hat man eine Beschädigung.

**Comment by Plushtoast** [comment]
Ja da passen die 2 Systeme die DSA hat, die auch noch von Foundry unverschämterweise anders umgesetzt wurden nicht so zusammen.
Mein Vorschlag wäre die Strukturpunkte des Schildes einfach um 2 zu erhöhen.

**Comment by TheFrazer** [comment]
Gute Idee!
Ja, anders Runden ist hier dann natürlich auch doof, wenn man mit Schildspalter arbeitet und hier die Strukturpunkte relevant sind. Ich denke, dass es dann ab jetzt bei uns einfach immer ein bisschen bessere Schilde gibt :)
Die Alternative wäre ein eigenes Feld für die Beschädigung, aber da die Strukturpunkte schon da sind, kann ich verstehen, wenn du da bleiben willst. Ich bin so zumindest zufrieden.
