### ISSUE TITLE
Verteilung Zustände über Meistermenü

### ISSUE THREAD

**Issue by argentorum** [Plushtoast/dsa5-foundryVTT#752]
Wäre es möglich, im Meistermenü die Möglichkeit einzubauen, Zustände an die gelisteten Charaktere zu verteilen?

**Comment by Plushtoast** [comment]
Hm nur, mit guter GUI Idee sinnvoll. Schon mal im Chat /conditions und drag and drop versucht?

**Comment by Zonenpenner** [comment]
Das mache ich auch so. Damit ich das nicht jedesmal in den Chat eingeben muss , habe ich mir ein Macro gebastelt. Vielleicht wäre ein Macro um die Zustände im Chat zu öffnen, statt zu tippen, im DSA-Core Macro-Kompendium sinnvoll.

**Comment by argentorum** [comment]
Chat Conditions Drag & Drop verwende auch ausgiebig, es wäre nur eleganter, das über das Meistermenü einsteuern zu können. Kann natürlich Aufwand bei der GUI bedeuten, wie Du sagst. Es wäre halt ein Nice To Have. Vielleicht hat hier jemand noch eine andere gute Idee.

**Comment by Plushtoast** [comment]
Ich denke es ist nur sinnvoll, wenn das gui mäßig clever gelöst ist. Falls ihr da kreative Ideen habt, wie das aussehen könnte gerne her damit.

**Comment by Plushtoast** [comment]
Also was ist das Ziel hier? Möglichst schnell bestimmte Zustände an irgendwen zu geben?
Warum über das Meistermenü? Gibt es da einen speziellen Grund?
Was ist mit dem TokenHud`? Auch dort kann man Zustände hinzufügen? Ist das nicht genau das richtige? Ich könnte das Hud auch umdesignen, dass die Zustände leichter zu erkennen sind (größere Buttons + Text).
Eine weitere Möglichkeit wäre ein Macro für die Hotbar ähnlich dem Lichtmakro, dass eine übersichtliche Liste aller Zustände hat und diese dann auf den markierten Token übertragen kann.

**Comment by Plushtoast** [comment]
Wandert erstmal in die token hotbar
