### ISSUE TITLE
[v9 Beta] Neue Keybindings nutzen für Funktionen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#753]
**Is your feature request related to a problem? Please describe.**
Ab v9 gibt es für Entwickler neue Funktionen für Keybindings. Ich könnte mir da auch ein paar DSA Funktionen vorstellen:
- Angriffs Menü aktueller Actor laut Ini im Combat Tracker (A) 
- Library (L) 
- Meister Menü (M) 
- Journal Browser (J) 

Anmerkung: jetzt könnte der Angriff vielleicht wie die anderen auch per Hotkey bereit gestellt werden?

**Comment by Plushtoast** [comment]
(A) kollidiert mit "Pan left". Würde sagen pan left ist unnütz aber naja...

**Comment by vt-tom** [comment]
Ach stimmt, wasd sind ja zum Token schubsen.
Hmm K oder B für Kampf oder Battle?
