### ISSUE TITLE
Automatisch vergebene Fertigkeitsspezialisierung funktioniert nicht

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#756]
Die automatisch vergebenen SF Fertigkeitsspezialisierung (z.b. über Professionen) funktionieren nicht, und müssen manuell gelöscht und neu vergeben werden.

**Comment by Plushtoast** [comment]
Ahja Charaktererschaffungsprobleme. Mein Lieblingsthema
