### ISSUE TITLE
List of automatable Special Abilities

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#759]
Hi,
please provide suggestions for rules for special abilties to provide further automation.
Special Abilities which seem to be automatable are also worth mentioning.

**Comment by Zonenpenner** [comment]
1. Effektcontainer für 

a) diverse Traditionsartefakte
Beispiel: "Gjalskerknochenkeule" mit Tierische Kraft (AG2 S.31) 
"Der Schamane kann sich selbst Kraft verleihen. Er erhält einen Bonus von +2 KK und +4 Kraftakt-FW. Die Wirkungsdauer beträgt 5 Minuten. Der Einsatz dieser Fähigkeit kostet 1 Aktion und am Ende der Wirkung verursacht sie 1 Stufe Trance und 1 Stufe Betäubung."

b) Zauber- und Liturgieerweiterungen
Beispiel: "Kriegsfarben" mit Erweiterung "Stärke des Tiers 1" (AG2 S.83)
"Der Schamane erhält zusätzlich +1 TP."

Generell wäre es supertoll, wenn die Erweiterungen den Zauber oder Liturgie anpassen würden. Ließe sich bei den meisten Erweiterungen bewerkstelligen, ist aber viel Arbeit.

**Comment by Ben528491** [comment]
Automatisierte Begabungen könnten auf zweierlei Arten implementiert werden:
- der höchste Würfel wird automatisch neu gewürfelt
- die höchste Differenz zwischen Wurf und Wert wird neu gewürfelt

Zudem wäre eine Option sinnvoll, ein "Standardziel" für Zauber/Liturgien auswählen zu können. Zum Beispiel wird ein Zauberer den Brennend-Effekt eines Ignifaxius oder Incendio in den seltensten Fällen auf sich selbst wirken.

**Comment by Plushtoast** [comment]
Also ich hatte schon einmal Incendio auf sich selbst um ein so ne Art "Scheune" anzuzünden...weil das nur auf Kulturschaffende geht...

Bei der Begabung ist das so eine Sache... das wurde schon mehrfach vorgeschlagen, hier aber zwei Beispiele, warum das nie kommen wird:

-  z.b. aberglaubische Leute werfen immer gern den roten Würfel oder
- viel entscheidender wenn deine Attribute sehr unterschiedlich sind. Nehmen wir an du hast einmal extrem einmal 8 und einmal 18. Jetzt würfelst du mit ersterem eine 10 und mit letzterem eine eine 19. Welchen würdest du neu würfeln (und beliebig andere Beispiele)? Außerdem darf man ja auch mehrere neu würfeln. Insofern darf das Gerechne gerne der Spieler selbst übernehmen.


Generell wollte ich hier aber nicht Dinge die schon automatisiert sind verbessern, sondern Dinge finden die noch fehlen und hilfreich wären.

**Comment by DerGreif** [comment]
Würde mich @Zonenpenner anschließen und auf die Traditionsartefakte verweisen, insbesondere die Stabzauber, zB die Fähigkeit ASP einzusparen.

Besonders zentral finde ich auch die Fähigkeit, den Magierstab in ein Flammenschwert zu verwandeln, wen man den entsprechenden Stabzauber hat. Hier wäre es ideal, wenn das Flammenschwert dann im Inventory auftaucht und ausgerüstet wird und der Stab verschwindet. Idealerweise per Button. Wenn das Flammenschwert dann noch automatisch pro KR ASP abziehen würde, wäre das perfekt. Kann natürlich sein, dass das extrem aufwendig ist zu programmieren. ME sollte aber zumindest das Flammenschwert als normales ausrüstbares Schwert im Core-Modul angelegt sein.

Weitere mE umsetzbare Stabzauber-SF:
- Bannstab des XXX (als Bonus für den Stab im Kampf gegen entsprechende Wesen)
- Energiestrahl (als Schusswaffe hinterlegt)
- Flammenschwert (zumindest als Schwert hinterlegt, 1w + 7 TP, Werte wie Langschwert,  idealerweise mit Umwandlung und ASP-Kosten-Abzug)
- Kraftfokus (Zauber kosten 1 ASP weniger, nur wenn Stab ausgerüstet ist)
- Seilpeitsche (zumindest als Peitsche hinterlegt, AT 14/PA 0 (fixe Werte!), 1w6 + 2 TP, magisch)

**Comment by Plushtoast** [comment]
Na dann wird der nächste Patch gefallen.

**Comment by Plushtoast** [comment]
Ich fuehre hier inzwischen eine interne Liste. Einiges wurde auch schon umgesetzt. Deswegen closed
