### ISSUE TITLE
[v9 Beta] Keybinding - Combat Tracker - nächster/vorheriger

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#761]
**Is your feature request related to a problem? Please describe.**
Eine weitere Idee für ein Keybindung: in der INI Reihenfolge vor und zurück springen. So kann das neue Angriffs Keybinding noch effektiver mit der Tastatur genutzt werden.
Ideen: v (vorheriger) und n (nächster) weil sie dicht beim b liegen und soweit ich sehen kann nicht genutzt werden

**Comment by Plushtoast** [comment]
Das dacht ich mir auch schon. Bzw dass das in core foundry drin sein sollte...
