### ISSUE TITLE
Wundschwelle bei Trefferzonen falsch berechnet

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#762]
Egal ob die Konstitution gerade oder ungerade ist, diverse Versuche haben eine falsche Erschwernis für die Selbstbeherrschungsprobe bei einer Wunde vorgegeben.

Bei einer Konstitution von 11 (und keinen modifizierenden Vor- und Nachteilen) ist die Wundschwelle 6.
Bedeutet bei folgenden Schadenspunkten gibt es entsprechende Erschwernisse laut Regeln.
6 - 11SP -> -1
12 - 17SP -> -2
ab 18SP -> -3

Tests haben aber das ergeben
-1  bei 6 bis 8SP
-2 bei 9 bis 14SP
-3 ab 15SP

Auch Tests mit anderen Konstitutionen boten ähnliche Ergebnisse

**Comment by Plushtoast** [comment]
Das ist mit aktivierten Rüstungszonen oder?

**Comment by Nellkir** [comment]
Ich glaube, ich habe es ohne aktivierte Rüstungszonen probiert.
Nur trefferzonen hatte ich aktiviert.

**Comment by mckee14** [comment]
Das sind immer 3 Differenz im MAX value. Hatte der Char zufällig 3 RS?

Nellkir ***@***.***> schrieb am Do., 16. Dez. 2021, 21:31:

**Comment by Nellkir** [comment]
Nein, beim oberen Test hat der char keine RS.

Aber auch chars mit RS (Selbstbeherrschung wurde dann als SP getestet) haben Unregelmäßigkeiten in der Wundschwelle

**Comment by mckee14** [comment]
Tja, im schlecht Raten war ich schon immer gut

Nellkir ***@***.***> schrieb am Fr., 17. Dez. 2021, 07:15:
