### ISSUE TITLE
Companions/Tiergefährten: AP-Berechnung durch fehlerhafte Einträge blockiert

### ISSUE THREAD

**Issue by Medsmiley** [Plushtoast/dsa5-foundryVTT#763]
**Describe the bug**
In dem Modul Tiergefährten/Companions gibt es Vor- & Nachteile sowie Sonderfertigkeiten für Tiere. Allerdings gibt es einige darunter, deren Feld "AP-Wert" nicht nur mit z.B. "10" gefüllt haben, sondern "10 Abenteuerpunkte". Das führt zu einer Fehlermeldung, wenn man diese Fähigkeit aus der Bibliothek in den Charakter zieht (siehe Bild). Zudem wird der AP-Wert nicht abgezogen von den Verfügbaren AP

**To Reproduce**
1. Erstelle/Öffne ein importiertes Tier (Actor)
2. Öffne die Bibliothek & gehe zu z.B. Wunderbeutel Krötenleib oder Ruhepol
3a. Öffnen und im Tab Details unter AP-Wert sieht man den Fehler schon
3b. Ziehe eine solche Fähigkeit ins Tier -> Fehlermeldung

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49515328/146570168-814b04e3-98da-4ab0-94b7-d3f26a0e566c.png)

**Comment by Plushtoast** [comment]
Duplicate of #653
