### ISSUE TITLE
Sammelprobe mit eigenen Talenten

### ISSUE THREAD

**Issue by KempaLars** [Plushtoast/dsa5-foundryVTT#768]
Wenn man eigene Talente anlegt und diese einem Akteur zuweist kann man zwar normale Proben auf dieses Talent würfeln. Leider ist es jedoch nicht möglich dieses Talent auch für eine Sammelprobe auszuwählen

Es wäre ideal, wenn alle Talente, die dem Akteur zugewiesen sind, auch im Dropdown für Sammelproben auswählbar wären.

**Comment by Plushtoast** [comment]
Wenn du willst dass das funktioniert musst du das entsprechende Talent dem Talente Kompendium hinzufügen. Das wirst du aber nach jedem Patch neu machen müssen. Das generell zu unterstützen ist umständlich und mir fehlt der Grund. Wenn du einen guten hast hoere ich mir den gern an

**Comment by KempaLars** [comment]
Naja in unserem Fall haben wir halt eine Hausregel mit einem neuen Talent „Sprachen und Schriften“ mit Sammelproben auf dieses Talent kann man dann Sprachen oder Schriften lernen, weil uns das einfache „kaufen“ für AP zu trivial war. 

Grundsätzlich macht die Funktion sehr wahrscheinlich nur für „Hausregeln“ Sinn und ich verstehe, wenn es zu aufwendig ist. Was würde denn passieren, wenn man das Talent zum Kompendium hinzufügt, eine Sammelprobe im Akteur „offen“ ist und man dann ein Update durchführt? Wird die Sammelprobe im Akteur gelöscht? Oder kann man das einfach wieder „fixen“ indem man das Talent erneut zum Kompendium hinzufügt?


Vielen Dank schon mal für Dein Feedback und den möglichen Workaround!

**Comment by Plushtoast** [comment]
Man kann es einfach wieder fixen indem man das Talent erneut dem Kompendium hinzufügt.
So in der Theorie...nie getestet.

**Comment by KempaLars** [comment]
Vielen Dank für das Feedback!
