### ISSUE TITLE
Add linebreaks or resizeable window for Rolls

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#77]
When you have a trait influencing your roll (ie. Nachteil "Persönlichkeitsschwäche: Vorurteile (Adlige)"), you can't read the whole name in the window with the roll modificators (the pre-roll pop-out window).

Making that window resizeable would help.

Additional consideration: For certain traits like Persönlichkeitsschwäche, the GM must decide if the roll gets the -1 modificator or not. Currently, this modifier is always considered true. 

 - Instead of just showing all the modificators, make them as a list with tickboxes to de-/activate them when needed (in the pre-roll window)
 - Make the trait itself "optional" with a tickbox. If such traits are affecting a roll, ask the user via promt if they should be considered. 
 - Currently, you have to correct a "wrong" modifier via manual values. If it stays like that, it should be mentioned in the wiki or manual.

**Comment by Plushtoast** [comment]
The modifiers are based on a best guess, so new players won't have to think too much.
Most modifiers are positive, thats why it is selected by default.
I'll leave that for now.
You can already deselect them by clicking on the corresponding line. Checkboxes take too much space and there are already so many mofidiers to adjust...

**Comment by Plushtoast** [comment]
There is now also an option in the configuration to set the default behaviour of talent modifiers (selected or not)
