### ISSUE TITLE
[v9 - 3.0.1] Scrolling Status Effekts - LeP/AsP/KaP Veränderungen größer

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#770]
**Is your feature request related to a problem? Please describe.**
Bei den Scrolling Status Effekts von LeP/AsP/KaP Veränderungen wäre es besser wenn diese etwas größer dargestellt werden könnten. So gehen sie recht schnell unter. Ich vermute dass hier ein DnD scaling angesetzt wird, da dort ja deutlich höhere LeP Veränderungen stattfinden.

Prio Melder: Low

**Comment by Plushtoast** [comment]
Das hat nix mit dnd zu tun. Ich glaube das wirkt vor allem bei hohen Auflösungen so mickrig. Muss vlt an einen Einstellungsschieber. Da fehlt aber eh noch die Möglichkeit das zu verbergen entsprechend der Option in den Einstellungen zu stati

**Comment by vt-tom** [comment]
Hmm, ich finde sie halt im Vergleich zu den Statuseffekten recht klein. Deshalb dachte ich, dass es an dem Wert liegt.
