### ISSUE TITLE
Ist eine Unterstützung "Automated Animations" möglich / geplant

### ISSUE THREAD

**Issue by GenX187** [Plushtoast/dsa5-foundryVTT#772]
Guten Tag,
erstmal kurz ein Lob an alle aktiven Entwickler, die FoundryVTT mit DSA 5 voranbringen (Träume wurden wahr!).

Ich würde gerne das Erlebnis in FoundryVTT durch die Verwendung automatischer Animationen bei Nahkampfangriffen und natürlich bei Zaubern/Liturgien noch auf eine weiteres Level heben.

Dazu gibt es auch bereits ein entsprechends Modul "Automated Animations" ( https://foundryvtt.com/packages/autoanimations ), welches wiederum auf Animationen von Modul "JB2A - Jules&Ben's Animated Assets" zurückgreift.

Leider wird DSA5 ("The Dark Eye") vom Entwickler akt. als nicht unterstütztes System gelistet. Wenn ich es richtige verstehe, hängt dies vor allem damit zusammen, dass das Modul die erforderlichen Daten nicht aus den Chat-Nachrichten oder "System-Hooks" erhalten kann.

Informationen dazu, und der Hinweis die Anfrage zur grundsätzlichen Unterstützung im jeweiligen Spielsystem zu platzieren (was ich hiermit einmal tun wollte), findet man in folgendem Entwicklereintrag auf github
>> https://github.com/otigon/automated-jb2a-animations/issues/166

Gibt es eine realistische Chance, die Unterstützung dieses Moduls auch für das DSA5-System in Zukunft zu etablieren?

**Comment by Plushtoast** [comment]
Muss mir erstmal anschauen wie das funktioniert. Aber das steht mittelfristig auch auf der Liste.

**Comment by Plushtoast** [comment]
Also was ich jetzt drin habe ist eine animation bei einer erfolgreichen Angriffsprobe.

Was für Funktionen stellst du dir so vor?

**Comment by GenX187** [comment]
Generell wäre es super wenn Nah-, Fern- und Zauberangriffe durch das Modul mit einer passenden Animation hinterlegt werden können.

Soweit ich das Modul verstanden habe, liegt auch eine Stärke darin z.B. bei einem Zauberspruch zunächst eine Anfangsanimation (also z.B. eine magische initiale Aufladung), darauffolgend eine weitere Animation (der eigentliche magische Effekt in Richtung eine Ziels) und dann sogar noch einen dritten Effekt am Ziel (z.B. der finale magische Einschlag) darzustellen. 
Alles passiert dann nach der Einstellung automatisch, sobald jemand den so konfigurierten Zauberspruch auf ein Ziel anwendet. Ich hatte also vor, die gängigen Zauber und Nahkampfangriffe, welche die Helden im Einsatz haben nacheinander alle entsprechend mit passenden Animationen und Sounds zu hinterlegen.

Also folgende Unteransicht:
![AA_Extra_Effects_Konfigurationsansicht](https://user-images.githubusercontent.com/35866459/150693243-43c0bd42-392c-4206-9e8c-1e49fdcc2446.JPG)

**Comment by Plushtoast** [comment]
Oh, ich meinte eher in welchen Situationen eine Animation abspielbar sein müsste.
Ich habe jetzt im Moment ausschließlich für erfolgreiche Angriff das drin.

Fangen wir mal damit an.

Denkbar wäre z.b. noch.
* Nicht erfolgreicher Angriff auch
* Erfolgreiche Parade/Nicht erfolgreiche Parade
* Ausweichen

Wobei dann immer mit der Animation der entsprechenden Waffe gearbeitet werden würde.

**Comment by GenX187** [comment]
Ach so. Na also, wenn Du mich persönlich fragst, sollte eine Animation auch nur im Erfolgsfall greifen.
Denn letztendlich wird die Animation ja dann später an die Waffe, bzw. den Zauberspruch (bzw. die Liturgie) gebunden und wenn dieser Aktionsversuch nicht erfolgreich ist, sehe ich eine Animation als wenig sinnvoll an. So hätte man im positiven Fall auch direkt ein optisches Feedback.
Denke also das passt erstmal so wie Du es beschreibst. 
Ich nutze z.B. die Animationen aus dem Modul von https://www.jb2a.com/Library_Preview/#video-container
Da sind für viele Nahkampf-, Fernkampfangriffe und Zauberaktionen geniale Animationen enthalten (habe die Patreon Unterstützer Version)
Würden Deine Anpassungen somit zunächst "nur" Nah- und Fernkampfangriffe betreffen?
Bin schon ganz neugierig auf die neuen Möglichkeiten :-)

**Comment by Plushtoast** [comment]
Das geht mir jeder Vergleichsprobe. Also immer wenn du ein token ins Ziel nimmst. Zb auch für schwimmen Probe oder dergleichen. Zauber natürlich auch
