### ISSUE TITLE
Cards Frontface Dateiauswahl

### ISSUE THREAD

**Issue by Deremus** [Plushtoast/dsa5-foundryVTT#774]
**Describe the bug**
Das Auswählen einer Datei für das CardFrontface ist nicht möglich

**To Reproduce**
1. Card Stacks öffnen
2. belibigen Card Stack auswählen
3. beliebige Karte über "Edit Card" öffnen
4. Reiter "Card Faces" auswählen
5. In der Zeile Face Image "Durchsuche Dateien"
6. Datei auswählen
7. Datei wird nicht übernommen

**Expected behavior**
der Dateipfad wird bei Face Image eingetragen

**Screenshots**

**Desktop (please complete the following information):**
Foundry Virtual Tabletop: Version 9, 9.238
Spielsystem: dsa5, 3.0.1
Aktive Module: 0
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) FoundryVirtualTabletop/9.0.0 Chrome/89.0.4389.128 Electron/12.0.9 Safari/537.36
GPU: ANGLE (NVIDIA GeForce RTX 2070 Direct3D11 vs_5_0 ps_5_0)
Max Texture Size: 16384

No viewed scene

Actors: 0 | Items: 0 | Journal: 0 | Rollable Tables: 0 |
Wiedergabelisten: 0 | Kompendium-Pakete: 4 | Chat Messages: 4

**Comment by Plushtoast** [comment]
Das DSA System hat an den Kartendecks noch nichts verändert.
Das wäre dann wohl ein Bug in Foundry 9. Den musst an Foundry melden.

Was aber scheinbar funktioniert ist, den Pfad manuell einzutragen:

Im Filebrowser kopieren:
![grafik](https://user-images.githubusercontent.com/44941845/147267366-a2c6915f-b980-444a-a9a7-b304c955ba48.png)

Dann bei Face Image einfügen.

**Comment by Plushtoast** [comment]
NVM ich leite es and Foundry weiter

**Comment by Plushtoast** [comment]
Ah, nein liegt doch an DSA
