### ISSUE TITLE
Titel Module zu lang

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#775]
Die DSA Modul-Titel können in der Modulübersicht nicht ganz gelesen werden, da sie zu lang sind.

Somit hat man keine Ahnung, was man nun genau aktiviert.

Vor allem bei Abenteuern kann das stören, den Rest hat man idR. ja sowieso aktiv...

Wenn man die Titel selbst nicht ändern kann, dann bitte die erste Zeile der Beschreibung, so dass man zumindest in der Detail-Ansicht erkennt, was es ist.
![screenshot](https://user-images.githubusercontent.com/62849695/147413996-98c703b9-7ec9-4ebd-82e6-ed0aff2f1280.jpg)

**Comment by Plushtoast** [comment]
Ich würde das eher als Foundry Poblem einstufen.
Den Titel zu ändern ist Harakiri - geht nicht.

**Comment by Plushtoast** [comment]
Das einzige was ich hier tun werde, ist dafür zu sorgen, dass das Compatibility Risk Label verschwindet
