### ISSUE TITLE
Fehlermeldung Profession Ceoladir: Eintrag nicht in DB gefunden

### ISSUE THREAD

**Issue by allekai** [Plushtoast/dsa5-foundryVTT#777]
**Describe the bug**
Beim Hinzufügen der Profession Ceoladir nach dem Bestätigen kommt folgende Fehlermeldung:

Folgende Einträge konnten nicht umgesetzt bzw. in der Datenbank gefunden werden. Bitte manuell anpassen/einfügen.
Nachteil/Vorteil/Sonderfertigkeit: Kultur: Mittelreich (aus Alverbernia)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19758353/147513321-9c21bff6-632d-4cef-acaf-922c18a1d759.png)

**Desktop (please complete the following information):**
 - OS: Windows / The Forge
 - Browser Firefox
 - Version 0.8.9

**Comment by Plushtoast** [comment]
Das ist ein Hinweis, dass  du selbst aktiv werden sollst.
Kulturen werden auch in Zukunft nicht automatisch hinzugefügt.

**Comment by allekai** [comment]
Ok. Ist damit dann also gemeint, dass man im Notizen Tab unter Kultur manuell diesen Wert eintragen soll? Oder bezieht sich der Hinweis auf etwas anderes?

Die Kultur ist ja soweit ich weiß weder Nachteil/Vorteil/SF.

**Comment by Plushtoast** [comment]
Entweder das oder wenn du das Kulturpaket mit allen dazugehörigen Talenten und Vor-/Nachteilempfehlungen haben willst. Dann solltest in der Bibliothek noch die entsprechende Kultur finden und auf den Charakterbogen ziehen.

Allerdings ist dir freigestellt die Regeln zu ignorieren und eine beliebige andere Kultur zu verwenden :)

**Comment by allekai** [comment]
Alles klar, danke für die schnelle Antwort. Keep up the amazing work 👍
