### ISSUE TITLE
Axxeleratus - Gegenerisch Erschwernis wird "nur" um 1 verändert

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#780]
Laut Regel-Wiki (https://ulisses-regelwiki.de/zauber.html?zauber=Axxeleratus)](https://ulisses-regelwiki.de/zauber.html?zauber=Axxeleratus) bewirkt der Zauber auch, dass , Zitat, "...Gegner können Attacken und Fernkampfangriffe des Beschleunigten schlechter abwehren und erhalten auf Verteidigung eine Erschwernis von 2..."

Der aktuelle Axxeleratus modifiziert 
   data.rangeStats.defenseMalus addieren 1
   data.meleeStats.defenseMalus addieren 1

Ich vermute, dass hier jeweils um 2 der Wert verändert werden müsste.

**Comment by Plushtoast** [comment]
Duplicate of #702

**Comment by Plushtoast** [comment]
Ich glaube das war im letzten Patch schon aktuell.
Zauberspruch migrieren schon versucht?

**Comment by UralterMannII** [comment]
Steht so im Compendium (read-only) drin. Ist mir aufgefallen, als ich den rausgeholt habe. Ich hatte ihn bis gestern nicht in Verwendung.
Ich vermute, dass ich nur dann migrieren muss, wenn ich die Zauber an einem Actor habe.
Und sorry für Duplikat...hatte nur in "open issues" gesucht.
