### ISSUE TITLE
Combat not working with functionality of multilevel-tokens module

### ISSUE THREAD

**Issue by drehatlas** [Plushtoast/dsa5-foundryVTT#781]
**Describe the bug**
First of all and important site note: I know that this is a compatibility problem between the dsa5 game system and a certain module. But I would really like to encourage you to take a closer look, as a solution to this issue would in my honest opinion strongly improve the possible game scenarios of the dsa5 system not just for my maps, but for all other map creators.

Here comes the problem:
I create and share several maps (e.g. module "drehatlas-maps") to the foundry community and especially to the DSA5 community, as not that many "adventure" maps are available (only classical "battle" maps).
To reach a high complexity of the maps, I make use of the module "multilevel-tokens". This module allows to teleport tokens (e.g. for stairs or traps) and to generate multilevel maps based on this feature.
However if I use the "Figuren Klonen" ("clone tokens") function, the DSA5 combat system is no longer working if either the actual token or the cloned token is selected. When trying to attack or perform any talent with focus on another token that is either being cloned or is the cloned token itself, nothing is happening - no error is returned, but the system is just not reacting. If the same token is outside the cloning area, everything works as it should.

Problem seems to be, that the system automatically focuses both the original token as well as the cloned one.
So (I did quite some open source c++ programing before, but had no idea where to look in your code :-/, so just my idea): maybe the used value from the "get_focused" function is assumed to be a unique token id by the dsa5 system and instead based on the two selected tokens (original and cloned) "get_focused" returns an array which confuses the system? -> in that case the fix could be easy via a check whether "get_focused" is an id or an array and if it's an array, the correct id is used?

**To Reproduce**
1. I tried it on three different maps, so reproduction should be fairly easy. However easiest might be to install the module "drehatlas-maps" and "multilevel-tokens"
2. Import and open the map "[BM] Tower and Bridge" from "Drehatlas' Maps" Scene Compendium
3. Place a SC and a NSC token somewhere in the cloning region below the tower (so that the cloned tokens appear on the right side of the map)
4. Focus either the cloned ot the original NSC and try to attack from the SC (or the other way round)

**Expected behavior**
Expected behaviour of course would be that the combat functionality is working as it should.

**Screenshots**
See attached screenshots
![0001](https://user-images.githubusercontent.com/96789661/147593847-52a2afa3-a1b4-49bf-b81b-2de605a24b02.jpg)
![0001_double_focus](https://user-images.githubusercontent.com/96789661/147593853-c3085503-373d-4e09-874c-aa4d56b5aa39.jpg)

**Version (please complete the following information):**
 - Version 0.8.9 and Version 9
 - Tested with Chrome and Edge - same behaviour

**Comment by Plushtoast** [comment]
Wird für 0.8 nicht mehr gefixt und für v9 ist das Modul irgendwie noch problematisch.
