### ISSUE TITLE
[Token Bar] - Verbesserungsvorschläge

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#785]
**Is your feature request related to a problem? Please describe.**
Aktuell nutze ich die Token Bar recht gerne, deshalb hier mal ein paar Ideen wie man diese meiner Meinung nach verbessern kann:
- Token bar als Rad direkt um den markierten Token einblenden können. Wenn das mödlich ist, sollte sie über einen Hotkey oder einen Button über das Token Menü (rechtsklick auf Token) ein und ausblendbar sein.
- Wenn der vorherige Punkt unlogisch oder nicht lösbar ist: Tokenbar manuell verschiebbar. Durch einen Griffpunkt die Tokenbar an eine selbst bestimmte Stelle schieben zu können wäre sicher auch hilfreich.
- Icon Größe selbst einstellen. Da reichen dann drei größen: klein, mittel, groß.

Das sind alles nur Ideen, nichts davon muss umgesetzt werden, sollte es enormen Aufwand bedeuten.

**Comment by Plushtoast** [comment]
Warum?

**Comment by vt-tom** [comment]
Weil ich die Tokenbar unglücklich platziert finde. Gerade bei größeren Monitoren ist es angenehm die Werkzeuge da zu haben wo sich gerade die Maus befindet oder wo man sonst noch werkzeuge hat. Unten ist so gut wie nichts, was angeklickt werden muss.

Aber wie gesagt das sind nur Ideen. Wenn du sagst dass es sich nicht lohnt, dann gilt wie immer, dass du dies hier gerne schließen darfst.

**Comment by Plushtoast** [comment]
Ich denke, dass das andere Nach- und Vorteile hat, was es nicht mehr als gleichwertig macht... aber Arbeit kostet

**Comment by Plushtoast** [comment]
Hab auch schon darüber nachgedacht das wir ein Kreismenü ala Playstation zu gestalten. Aber ich glaube da fehlt noch die Idee für den besten Weg. Persönlich benutze ich eh immer den combattracker oder das Charaktersheet.

**Comment by vt-tom** [comment]
Vielleicht kann man das ja auf einen Tastendruck ein und ausblenden um den Token?
Aber was soll das enthalten? Entweder das was in der Token leiste liegt, oder sogar selbst belegbar? 🤔
