### ISSUE TITLE
[Flüsterabkürzungen] - Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Niemand-001** [Plushtoast/dsa5-foundryVTT#786]
Prio: Niedrig

Manchmal hat man kleine Notizen vorbereitet, die man seinen Spieler:innen gerne zukommen lassen möchte.

Das Flüsterkommando _/w_ funktioniert gut, könnte bei längeren vorbereiteten Nachrichten aber noch etwas fixer gehen.

Bisher mache ich es so, dass ich eine Notiz vorbereite, in welcher ich zum einen _/w [Spielername]_ für aller Spieler:innen hinterlege und 
zum anderen die Textbausteine. Wenn Spielerin X dann etwas bestimmtes herausfindet, copypaste ich erst den entsprechenden Whisperbefehl in die Konmsole und dann den Text.
An der Stelle wäre eine kleine Abkürzung cool. Vielleicht Rechtklick auf die Notiz und dort eine entsprechende Option oder ein Hotkey, wenn Text selektiert ist o.ä.

**Comment by Plushtoast** [comment]
Meines wissens kann foundry einfach macros für whipser nachrichten. das hier is schon ein ziemliches luxusproblem :)

**Comment by vt-tom** [comment]
Aber das Thema ist größer und tatsächlich unter Spielleitern oft Diskutiert.
Es geht hier um das Oberthema: wie kann ich möglichst einfach einem Spieler Informationen zukommen lassen ohne dass die anderen diese direkt mitbekommen. 
Sonst kommt es zu den Situationen: SL erzählt Spieler was er durch die Probe herausfindet, der Spieler braucht dann aber kein Rollenspiel mehr machen, denn die anderen wissen ja jetzt schon die Infos...

**Comment by mckee14** [comment]
dafür gibts doch schon separate module. damit kann man journals an einzelne
spieler teilen bzw auf dem screen einblenden.

mir kommt der name nicht in den sinn, aber frag mal im foundry discord nach.

Niemand-001 ***@***.***> schrieb am Do., 30. Dez. 2021, 14:03:

**Comment by Niemand-001** [comment]
Du meinst sowas wie _Permission Viewer_? Ja, das ist gut und nützlich, aber hier nicht gemeint. Es geht wirklich mehr darum, schnell mitzuteilen, was jemand in einem Raum sieht, wenn ich die Beschreibung vielleicht schon in meinen Notizen habe, aber eben keine eigene Notiz mit ausschließlich diesen Zeilen, oder wenn jemand eine QS2 auf Tierkunde bei der Tier XY gewürfelt hat, ihm dann schnell die QS2-Zeilen dazu rüberzuschicken. [Es wäre ein fürchterlicher Aufwand und unübersichtlich, für all diese kleinen Dinge eigene Journalnotizen anzulegen.]

"das hier is schon ein ziemliches luxusproblem :)"
Ja, da hast Du nicht ganz Unrecht, @Plushtoast , aber dies ist ja auch ein grandioses Luxusfoundrymodul. ;-)

Ich sehe die Prio wie geasgt als niedrig an. Es ist aber schon - wie Tom schrieb - ein sozusagen alltäglicher Usecase, der so häufig auftritt, dass jeder gesparte Klick ein Komfortgewinn wäre.

**Comment by mckee14** [comment]
Wäre ein "whisper to" Button im GM Menü eine Lösung? Da hat man ja schon
alle wichtigen Chars.
Klick, CTRL+V, Enter.

Niemand-001 ***@***.***> schrieb am Do., 30. Dez. 2021, 20:06:

**Comment by Niemand-001** [comment]
Ja, das wäre schon cool!

Meine erste Idee, um mir das Leben da zu erleichtern, waren Chatmakros in der Makroleiste. Das scheiterte aber wenig überraschend direkt daran, dass das Chatmakro _/w [spielername]_ beim Auslösen direkt eine leere Nachricht an den Spieler schickt und nicht auf meinen Inhalt wartet.

**Comment by gendokun** [comment]
@Niemand-001  ich glaube du suchst das hier:
https://github.com/foundry-vtt-community/macros/blob/main/misc/whisper_players.js

**Comment by Niemand-001** [comment]
@gendokun Danke für den Tipp! Leider finde ich das Modul nicht in der Modulliste. (Möglicherweise kann man es direkt installieren. Das habe ich noch nicht getestet.)
Bei der Suche danach bin ich aber über dieses - die neuen V9-Keybindings nutzende - Modul gestolpert:
https://foundryvtt.com/packages/sweetnothings

Das kommt meinen "Wünschen" schon sehr nahe!

(Was mich betrifft, kann dieser Thread damit geschlossen werden. :-) )

**Comment by gendokun** [comment]
@Niemand-001 , Das ist ein Macro kein Modul :)
Einfach in der Hotkey Bar unten neues Macro erstellen, auf Script stellen und den Code hier unter dem Link einfügen
https://raw.githubusercontent.com/foundry-vtt-community/macros/main/misc/whisper_players.js?_sm_au_=ivV2j0Vt0Fr2f7F5Mj4TVK7JNV48C
(Copy+Paste)

Dann läufts

**Comment by Niemand-001** [comment]
ahh..ok, bin doof! ;-)

**Comment by Plushtoast** [comment]
Bevorzugt hier noch jemand eine andere Lösung oder kann das geschlossen werden?

**Comment by vt-tom** [comment]
Am coolsten wäre halt die Möglichkeit irgendwie abhängig von der QS einer Probe dem Spieler der die Probe ausführt die Informationen irgendwie zukommen zu lassen. Aber bisher ist mir auch nichts eingefallen.
Ich hab da aktuell n Makro geschrieben was das Ergebnis einer Rolltable in eine Notiz für den Spieler ausgibt.

**Comment by Niemand-001** [comment]
Mit dem Makro, welches gendokun vorgeschlagen hat, und mit _sweetnothings_ komme ich gut zurecht.

In dem von Tom beschriebenen Usecase muss ich zwar mit C&P arbeiten, aber soo oft kommt das nicht vor.

Meinethalben kann das also geschlossen werden.
