### ISSUE TITLE
Individuelle Würfel als Modul für "Dice so Nice" scheinen den Aufruf/Verwendung im Gamemodul zu verhindern

### ISSUE THREAD

**Issue by GenX187** [Plushtoast/dsa5-foundryVTT#788]
**Describe the bug**
Since I have already opened the following ticket at the "Dice so Nice" module developement...
https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/280
...and there the problem can not be reproduced (not even with the latest version 4.3.0), I now suspect that the problem lies in the embedded function of the DSA 5 module.

**To Reproduce**
FVTT version:
Version 9 - Build 238

Dice so Nice version:
Version 4.2.2 & 4.3.0

System:
"The Dark Eye (5th Edition)" Gamesystem Version 3.0.2

Step to reproduce:
I bought additional dices from the "The Rollsmith (Black Marble Dice Set)" and installed them as a seperate module according to the instructions and then activated them.
As soon as I selected these dices for myself as a gamemaster under "Gamesettings" >> "Modulesettings" >> "Dice so Nice!" and then want to call up the "DiceSoNice Settings" under "Gamesettings" >> "Systemsettings" (for the DSA 5 specific settings), the menuebutton for selecting the dices for the gamesystem no longer opens.

Only after I have deactivated the module, the menu can be opened again.

**Expected behavior**
A selectionmenue for the colorset of dices for DSA5 specific dices should open to select different dice-colour sets

**Screenshots**
Menue doesn´t open:
![Fehler 23 12 2021](https://user-images.githubusercontent.com/35866459/147769973-ef2ccf07-39fd-43e2-a84b-a3059fe3bdc0.JPG)
Errormessage from console:
![Fehlermeldung_30 12 2021](https://user-images.githubusercontent.com/35866459/147769969-bade6af4-3c03-41cb-be02-d962308fabbe.JPG)

**Comment by Plushtoast** [comment]
I don't own any rollsmith sets and I also don't plan to buy any.

Open the file modules/hooks/dicesonice.js

and change line 191 from
```
data.systems = duplicate(game.dice3d.DiceFactory.systems)
```

to

```
data.systems = game.dice3d.DiceFactory.systems
```

and provide feedback whether this fixes your issue. 

Also DSA currently does not really support custom dice set.

**Comment by Plushtoast** [comment]
Also ich hab inzwischen von Rollsmith ein Model erhalten und es funktioniert mit oben genannter änderung.
Kannst auf den Patch warten oder selbst die Zeile ändern.

**Comment by Plushtoast** [comment]
DSA wird im nächsten Patch auch custom dice set unterstützen.

**Comment by GenX187** [comment]
Also ich bin mal wieder erstaunt darüber, was die Community alles bewegt! 
Die Anpassung am Code funktioniert, das Problem ist dadruch behoben.
Wäre schon cool, wenn man für das DSA System zukünftig auch individuelle Würfel einstellen kann.
Vielen Dank und einen guten Übergang ins neue Jahr.
Möge die Macht mit Euch sein!

**Comment by GenX187** [comment]
Hallo,
vielen Dank für die Mühe und die Möglichkeit in der neusten Version 3.1.0.

Auch wenn ich mir vorstellen kann, dass ihr Wichtigeres zu tun habt, als die individuellen Würfel für DSA zum Laufen zu bekommen, wollte ich kurz zurückmelden, dass irgendwie das Laden der Würfelgrafiken nicht korrekt funktioniert.

Die Würfel bleiben schwarz (siehe Screenshot).

![Würfel_bleibt_schwarz](https://user-images.githubusercontent.com/35866459/149101729-e02c3214-888f-4902-8e51-295ecd5599aa.jpg)

Nachdem man in den Einstellungen für die individuellen DiceSoNice-Settings die Custom-Würfel einmal ausgewählt hat, funktioniert es zunächst anscheinend. ABER> Das Problem betrifft auch jeden Spieler.
Leider bleiben die Einstellungen dann über den Browser auch nicht beständig. Bei der nächsten Anmeldungen wurden die Würfel, welche ich mit den individuellen Einstellungen versehen hatte (z.B. für Ausweichen, Parieren, Trefferpunkte) wieder nur schwarz angezeigt.

Bei den Colorsets wie z.B. im Screenshot bei der Einstellung für den Angriff-Würfel zu sehen ("Blutmond") funktioniert es hingegen problemlos!?

Ich wollte somit nur bescheid geben, dass es so wie es aktuell umgesetzt wurde leider nicht funktioniert da irgendwie der "preload" für die Würfelsysteme (bzw. Würfelskins) leider irgendwie nicht greift. 

Ich erhalte auch keine Fehler in der Console.

**Comment by Plushtoast** [comment]
Bitte keine nekromantie für Tickets, sondern ein neues aufmachen.
Die Wahrscheinlichkeit, dass es sonst nicht wahrgenommen wird, ist hoch. 

Ich Check das nochmal. Ggf probierst du nochmal strg+F5 für den Bug der in den Patch notes beschrieben wurde und stellst sicher, dass du auch die allerneuste foundry Version hast. 
Aber ich schau es mir nochmal an.

**Comment by GenX187** [comment]
Entschuldigung, ich dachte es wäre einfacher den Sachverhalt im alten Ticket weiterzuführen. 
Keine Nekromantie mehr, ich gelobe Besserung bei der Kraft der 12 Götter.

Also ich habe alles noch mal versucht (Strg+F5) und nutze immer die neusten Versionen.
Derzeit:
- FoundryVTT Version 9 - Build 242
- DSA Gamessystem Version 3.1.0
- Dice So Nice Modul Version 4.3.1

Anbei noch mal ein Beispiel aus einem anderen System (aus einem anderen, kostenlosen Dice-Customzing-Modul). 
Es scheint also nicht nur an den Rollsmith-Würfeln zu liegen, sondern Grafiken/Skins aus Dice-Customizing-Modulen zu betreffen, die über reine Farbcodierungen hinaus gehen. 
So fehlt bei diesem Beispiel wohl die Grafik für die "20" auf dem Würfel, was ihn durchsichtig macht:
![Würfel_fehler_anders_System](https://user-images.githubusercontent.com/35866459/149127194-d5f2061e-e31a-41bd-b63e-3e7529e58235.jpg)

**Comment by Plushtoast** [comment]
Kannst du mir den Modulnamen nennen?

**Comment by GenX187** [comment]
> Kannst du mir den Modulnamen nennen?

Selbstverständlich.
Ich habe folgende Zusatzmodule für "Dice so Nice" im Einsatz:
"Nice more Dice" in Version 1.0.3 mit Kompatibilitätsrisiko ab V 0.8.8 >> https://github.com/LyncsCwtsh/fvtt-module-Nice-more-Dice

"Lordu's Custom Dice for Dice So Nice!" in Version 0.33 mit Kompatibilitätsrisiko ab V 0.8.8>> https://github.com/LorduFreeman/foundry-lordudice

Der "Dragon20 (d20, 20 best)" Eintrag aus meinem letzten Beispiel kommt aus dem Modul "Nice more Dice"
