### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by M-Mueller** [Plushtoast/dsa5-foundryVTT#79]
Hi,
does this project accept contributions in the form of pull requests? If so, it would be nice to have something like a CONTRIBUTING.md file that e.g. explains how to set up a development environment. My group is currently considering switching to Foundry and being able to fix bugs ourselves or add missing features would be a huge plus.

I was a bit confused by this project at first, because it's not really clear that this corresponds to the official Ulisses module announced [here](https://ulisses-spiele.de/virtual-tabletop-dsa-vtt/). I'm still not 100% certain if the whole thing is open source or if there are some required proprietary parts.

**Comment by Plushtoast** [comment]
Der Code wird im Zusammenspiel mit Ulisses entwickelt und ist mit verschiedenen offiziellen Produkten verknüpft. Code Änderungen durch Dritte können daher zu Schwierigkeiten mit der Kompatibilität der Module führen, daher möchten wir aktuell kein code sharing betreiben. Wir sind für Verbesserungsvorschläge offen, behalten uns aber vor wann und ob wir die einfügen, damit sie mit der restlichen Planung nicht kollidieren.
Der code wird zudem durch uns beständig überarbeitet und weiter entwickelt und eine Abstimmung mit zusätzlichen Beiträgen würde unsere Prozess aktuell überfordern und erschweren.

**Comment by M-Mueller** [comment]
Alles klar, kann ich verstehen. Ich freue mich auf jeden Fall das Ganze mal auszuprobieren. Die Screenshots sehen sehr vielversprechend aus :+1:
