### ISSUE TITLE
Vergift-/verzauberbare Traits

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#792]
Manche Kreaturen haben Giftattacken - es wäre schön, wenn Eigenschaftsitems/Traits analog zu Waffen vergiftet werden könnten.

**Comment by Plushtoast** [comment]
Geht von Anfang an.
In den Kompendien sind Beispiele.

**Comment by zoidable** [comment]
Hmm, dann steh ich auf dem Schlauch...könntest du vielleicht ein Beispiel aus Core, Armory1/2 oder Kompendium nennen? Also Drag&Drop wie bei einer Waffe sollte funktionieren?

**Comment by Plushtoast** [comment]
Höhlenspinne oder Ghul im Bestiarium sollten das richtig eingestellt haben.

**Comment by zoidable** [comment]
Schau ich mir mal an, danke
