### ISSUE TITLE
Foundry v9 / Light & Sight Macro , Licht funktioniert nicht

### ISSUE THREAD

**Issue by gendokun** [Plushtoast/dsa5-foundryVTT#794]
Durch die Änderung der Lichtvariablen in v9 funktioniert das Makro "Light&Sight" nicht mehr vollständig. Nur Sicht funktioniert, Licht funktioniert nicht mehr.

**Comment by vt-tom** [comment]
Das ist ein Duplikat zu #746

**Comment by gendokun** [comment]
Oh sorry, danke! Ich schließe
