### ISSUE TITLE
Status "bleeding" lässt sich nicht hinzufügen

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#795]
Wenn ich versuche, über actor.addCondition("bleeding") einem Akteur den Status hinzuzufügen, kommt im Chat nur die Meldung CHATNOTIFICATION.applyBleeding und nichts passiert. Die CHATNOTIFICATIONS mit Bezug zu bleeding scheinen auch nicht in der Language-Datei angelegt zu sein...sind die überhaupt Teil des Systems oder sollen die über ein Modul integriert werden?

**Comment by Plushtoast** [comment]
Götterwirken 2 und Kompendium 2 (sobald es kommt vermutlich)

**Comment by zoidable** [comment]
Alles klar :)
