### ISSUE TITLE
Übertragung von Statuseffekten aus Kampfsonderfertigkeiten funktioniert nicht

### ISSUE THREAD

**Issue by zoidable** [Plushtoast/dsa5-foundryVTT#796]
Die Übertragung von Statuseffekten wie Betäubung aus der SF Betäubungsschlag auf das Ziel scheint aktuell nicht zu funktionieren: bei einem Treffer erscheint kein Button zur Effektübertragung.

**Comment by Plushtoast** [comment]
Funktioniert bei mir einwandfrei.
Ich brauch mehr Infos unter welchen Umständen das nicht klappt.

**Comment by zoidable** [comment]
Umgebung:
aktuellste Version von Foundry und vom System, Foundry Browser

Zum Reproduzieren:

1. Ein Held hat die SF Betäubungsschlag
2. Ziel auswählen und Waffenwurf mit aktiviertertem Betäubungsschlag ausführen
3. Ziel wählt "Keine Reaktion"
4. Vergleichsprobe gelingt, aber kein Button zum Übertragen des Effekts erscheint

![image](https://user-images.githubusercontent.com/81991198/148647726-f30ead61-11c0-4bf4-b3b0-b4716b799e9e.png)

Meine Vermutung ist, dass die Funktion `DiceDSA5.addApplyEffectData(testData)` nach dem ersten Schritt false zurückgibt und die specAbs gar nicht erst ausgewertet werden...? Oder ist die Anwendung von Effekten aus SFs anders gedacht?

**Comment by zoidable** [comment]
Hm könntest du vielleicht erläutern inwiefern meine Erwartungshaltung falsch war? Oder lässt sich das nicht reproduzieren?
