### ISSUE TITLE
Bibliothek Suchfilter fehlerhaft

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#797]
Wenn man bei der Bibiolethek Vorteile anhakt, werden beim weiter runterscrollen auch Nachteile aufgeführt.
![image](https://user-images.githubusercontent.com/82062265/148119569-65865ad0-f1e9-4847-849b-0c7da24df3d2.png)

**Comment by karabiberym** [comment]
Meine Vermutung ist, dass die Suche falsche Ergebnisse liefert, da intern beim filtern "advantage" ein Substring von "disadvantage" ist. Dadurch gibt bei Zeile 407 in itemlibrary.js der Aufruf von `result = index.search(...)` die falsche Ergebnisse.
