### ISSUE TITLE
Some support for riding companions including modifiers and mounted combat

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#798]

**Comment by mckee14** [comment]
ohhh, da machst du n fass auf. reiterkampf... ich liebe es!

Plushtoast ***@***.***> schrieb am Do., 6. Jan. 2022, 18:50:

**Comment by Plushtoast** [comment]
Das ist jetzt erstmal nur ne Notiz.
Sind noch ein paar andere Fässer offen...
