### ISSUE TITLE
Meister der improvisierten Waffen

### ISSUE THREAD

**Issue by foschmitz** [Plushtoast/dsa5-foundryVTT#80]
**Describe the bug**
Hi, ich finde den Meister der Improvisation (Erschwernisse durch
fehlendes Werkzeug um 2 senken) aber nicht den Meister der improvisierten Waffen  (keine Nachteile bei Nutzung improvisierter Waffen). Eventuell verwirre ich aber auch die Regeln und das gilt als eins?

**To Reproduce**
Fähigkeit nicht bei den items vorhanden

**Comment by mckee14** [comment]
Meister der improvisierten Waffen stammt aus dem Aventurischen Kompendium und ist daher nicht im GRW Paket enthalten.

Ich würde den Vorteil als reinen Text selber anlegen (also ohne Effekte / Wirkung), und die improvisierten Waffen ebenfalls. Die Erleichterung, die der Char bekommt, einfach direkt in den Waffen im AT/PA Modifikator mit verrechnen und eintragen.

Wenn der Char dann mit einer solchen improvisierten Waffe kämpft, hat er automatisch die korrekten Werte.
(Achtung, Item darf dann nicht einfach an andere Chars übergeben werden)

**Comment by foschmitz** [comment]
Top, super vielen Dank das ist irre Hilfreich! Finde mich auch gerade erst insgesamt in Foundry ein, das DSA5 System und das GRW ist aber schoneinmal der absolute Hammer! Vielen Dank ich freue mich auf das Bestiarium, Kompendium und alle anderen Erweiterungen die da kommen!!!
