### ISSUE TITLE
Items not available in Version 9 - Build 238

### ISSUE THREAD

**Issue by FallenPatta** [Plushtoast/dsa5-foundryVTT#800]
Linux nodejs server

1) Update to foundry Version 9 - Build 238 (stable)
2) Update the system and Core Rule module
3) Restart server
4) Launch old or newly created world
5) Search for any item/weapon/etc.

It looks like the system is crashing while loading entities in the DSA5 Core Rules so some are available and some are missing.

Tried:
Reinstalling everything from scratch with no additional modules - did not work

**Comment by Plushtoast** [comment]
hm sounds more like a general foundry or network access issue.
A few moments ago a new version of foundry released. Maybe this helps, also try this:

![grafik](https://user-images.githubusercontent.com/44941845/148445069-ebd08bdd-1e82-48c3-b23f-87f04b28c95a.png)

**Comment by FallenPatta** [comment]
It was indeed just a cache issue. Thanks for the support.
