### ISSUE TITLE
Verbesserung Licht und Sicht Makro: Gegenstände einbeziehen

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#801]
**Is your feature request related to a problem? Please describe.**
Das Sicht und Licht Makro ist echt super. Mir sind in der Benutzung aber ein paar Ideen gekommen:

- [x] - Wenn ich als Spieler eine Fackel aktiviere, möchte ich auch gerne, dass dann die Fackel verbaucht wird. 
- [x] - Wenn möglich, dann wäre es cool das Licht auch zu aktivieren, wenn ich die Fackeln/Laternenöl direkt im Inventar einsetze dieses dann auch ein Licht für den Token aktiviert. Wenn dies umgesetzt wird, kann der hier drüber genannte Punkt ignoriert werden.
- [x] - Bei dem Zauber Flim Flam dasselbe. Wird der Zauber ausgesprochen wäre es cool, wenn ich über Effekt anwenden (selbst) dann das Licht des Tokens angepasst wird oder aber bei Effekt anwenden (Ziel) vielleicht sogar ein Lichttoken vom SL erzeugt werden kann.

Vermutlich gibt es noch weitere Ideen, mit fallen aber gerade keine mehr ein.

**Comment by Plushtoast** [comment]
- [x]  Macro nur von GM zu öffnen
- [x] active effects
