### ISSUE TITLE
DSA-spezifische Makros

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#808]
Zwar wirklich sehr einfach selber zu basteln, aber doch für viele Nutzer wahrscheinlich sinnvoll wären Makros zu wichtigen DSA-spezifischen Befehlen, besonders:

/packages - (Zeige verfügbare Ausrüstungspakete)
/conditions - (Zeige alle Zustände und Status)
/apps - (Füge Anwendungsgebiete hinzu)*
und ganz neu: öffne Spielermenü

*In der Beschreibung von /apps beim "?" gibt es hier noch einen Rechtschreibfehler: "deimen" statt "deinem".

**Comment by Plushtoast** [comment]
+ /ch (inklusive dropdown für talente)
