### ISSUE TITLE
Beil / Handaxt und Holzfälleraxt tauchen nicht als Waffen aus im Kampf-Tab

### ISSUE THREAD

**Issue by foschmitz** [Plushtoast/dsa5-foundryVTT#81]
Hi, ich versuche eine Holfzfällerin anzulegen, diese kämpft mit einer Holzfälleraxt 2h oder einem Beil. Was muss ich tun um die dort auch anzeigen zu lassen?

**Comment by mckee14** [comment]
Diese Items sind gemäss GRW keine Waffen, sondern Ausrüstung, daher kann damit nicht gekämpft werden.

Lege einfach eigene Einträge an für diese Objekte als Nahkampfwaffe. Wenn Du nicht sicher bist, wie das geht, steht es im Wiki beschrieben. Es hilft auch jeweils, bei den vorhandenen Waffen reinzuschauen und zu sehen, was wo eingetragen wird.

**Comment by Plushtoast** [comment]
Das ist korrekt. Aber ich frag nochmal Ulisses wie wir das handhaben sollen.

**Comment by mckee14** [comment]
Das Problem ist dann generell die Implementierung von improvisierten Waffen (19 + 20 zählen als Patzer, Gegener erhält +2 VW).
Items, die sowohl Ausrüstung und (i) Waffen sind, müssten auch an beiden Orten auf dem Sheet sichtbar werden, aber das gleiche Objekt referenzieren.

Wenn die Laute beim Kampf kaputt geht, dann passiert das ja auch mit der "normalen" Laute im Inventar.

**Comment by Plushtoast** [comment]
Werden das erstmal so lassen.
