### ISSUE TITLE
Bruchfaktor Verbesserungen

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#810]
Hi,
wenn ich die Regeln richtig verstehe, sollte der Bruchfaktor wie folgt abgeändert werden:

Bruchfaktor grundsätzlich nur bei bestätigten Patzern/Erfolge -> Also successLevel > 2 und nicht 1
Ebenso Bruchfaktor nur beim Parrieren von bestätigten Erfolgen -> dh der check auf "Halbe Verteidigung" muss auch durch einen successLevel Check ersetzt werden.

Bruchfaktor beim Parrieren nur wenn die Parade auch klappt, sonst parriere ich ja nicht -> prüfung auf den eigenen successLevel 

Pull Request vorschlag : https://github.com/Plushtoast/dsa5-foundryVTT/pull/811

**Comment by Plushtoast** [comment]
Ich schau mir das Mal an. Allerdings würde ich sagen eine misslungene Parade kann die Waffe genauso beschädigen. Sie ist halt unsanft an der falschen Stelle vom Angreifer getroffen worden und der hieb ging trotzdem durch.

**Comment by Qowy** [comment]
Ja das ist vermutlich auslegungssache. Die Regeln sind hier mit "#Wenn er einen Kritischen Treffer mit seiner Waffe pariert." nicht ganz klar ob der "Versuch Strafbar ist" ;)
Außerdem ein bestätigter Paradepatzer wird ja durch die < -2 abfrage trotzdem abgehandelt.

Eine gescheiterte Parade gegen einen Crit wird halt dann sehr Punishing, da unter umständen Waffe und Rüstung beschädigt wird.

Dann wäre die abfrage einfach ohne den "testData.successLevel > 0 &&" Teil

Evtl dafür config option? oder halt einfach anzeigen man muss ja nicht auf den bruchfaktor button drücken wenn man meint eine gescheiterte parade richtet nichts aus.

**Comment by Plushtoast** [comment]
Ich hab das bei uns so gemacht, dass man sich dann aussuchen kann, ob die Waffe oder die Rüstung beschädigt wird.
Aber aus dem Grund wie du es sagst. Es ist nicht 100% klar, wie es gedacht war.

**Comment by Plushtoast** [comment]
Ok, ich mach das rein. Allerdings ohne die Abfrage auf erfolgreiches Parieren.
Meiner Meinung nach kann fehlgeschlagenes Parieren auch bedeuten, dass man eben doch auch dem Angriff des Gegners ungünstig entgegen wirkt. Was zb. den Parier beschädigen kann oder eine Scharte in die Waffe schlägt, aber der Angriff trotzdem durchrutscht.
