### ISSUE TITLE
Verbesserungen Sichtautomatisierung

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#817]
Folgende unqualifizierten Vorschläge zur verbesserung der sichtautomatisierung.

- Dokumentation
  

- [x]  - Preset Tab: "Diese Werte sind die Sichtreichweite bei absoluter Dunkelheit und werden (falls genutzt) durch den Dunkelheitsfaktor modifiziert"

   - Hierzu gleich die Frage warum der Faktor und "link" an Dunkelheit in der Token konfiguration ist, wenn er doch eh global ist -> in die Presets verschieben?
-  

- [x] Wesen mit Dunkelsicht etc. sollten auch bei Dunkelheit = 0 nie mehr reichweite haben als normale Menschen. Also vermutlich Cap auf Sichreichweite (oder keine sicht) * Dunkelheitsfaktor. Sie bleiben dann halt sehr lange an dieser sichtweite bevor es kleiner wird.

- Das ganze ist irgendwie unintuitiv, wäre es nicht besser statt der Sichweite bei dunkelheit einzustellen was die maximalsichtweite ist? und dann nimmt diese anhand des dunkelheitsfaktors ab und dunkelsicht modifiziert da nur?

Vorschlag:

Einstellung Maximale sichtweite bei Tag: z.B. 20/10
Einstellung mod Dunkelsicht: z.B. 0.2
Einstellung mod Dunkelsicht 2: z.B. 0.4

Bei Dunkelheit 0 sehen alle  20
bei 0.5 sehen normale 10/5. Dunkelsicht subtrahiert vom Dunkelheiswert seinen mod. Für eine Elfe wird also mit Dunkelheit 0.3 gerechnet also Reichweite 14/7

Das bildet finde ich besser ab, dass es für diese ja weniger Dunkel ist, statt dass sie weiter sehen.

**Comment by Plushtoast** [comment]
Foundry hat bereits den umgedrehten Weg mit der Dunkelheit, statt Helligkeit gewählt. Den werde ich nicht umdrehen.

Aber mir schwebt da eher noch eine advanced Einstellung vor, die Sich an die Sichtschwellen, die im Meistermenü zu finden sind, koppeln.
Sprich bei Dunkelheitsschwelle gebrochen sieht keiner mehr was. Bei eins davor ist es linear Bereich x-y etc.

**Comment by Plushtoast** [comment]
Der Dunkelheitslink ist in diesem Menü, weil ich versucht habe die Funktion nach Häufigkeit der Click Wahrscheinlichkeit zu sortieren. Im Config Menü ist man quasi nie. Die automatische Dunkelheitsformel will man aber sehr wohl ab und an deaktivieren.

**Comment by Qowy** [comment]
Klingt alles gut, nur wie gesagt wäre es vllt am einfachsten, wenn Dunkelsicht den Dunkelheitswert modifiziert, statt die Basis Sichtweite. Dann ergibt sich der rest von selbst.

**Comment by Plushtoast** [comment]
Eher nicht, zu viel hin und her.

**Comment by Plushtoast** [comment]
Andererseits...
Dein Vorschlag erscheint mir aber schlecht zu den vorgegebenen Regelwertern an Sicht zu passen.
Vielleicht mach ich einfach beide Modi rein.

**Comment by Plushtoast** [comment]
Ok gibt jetzt beide Modi.
Ist tatsächlich nicht so schlecht.
