### ISSUE TITLE
Armor Zone Encumbrance calculation not working.

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#822]
Line 43 of armorzones.js is  if (this.type == "character"... but should be  if (actorData.type == "character" so this returns false and skips all your code:

which then has a copy paste error in line 57 where it is using "a.damageToolTip = EquipmentDamage.damageTooltip(a)". instead of armor.damageToolTip = EquipmentDamage.damageTooltip(armor)

Additionally the inbetween steps of lets say enc 2 and additional -1gs/-1INI do not seem to be applied. (the .mod of calcEncumbrance does not seem to be used?)

Enhancement -> Ignore Effect field of Armor when Zone Armor is enabled. (Might be to simple; is there armor with other effects than -1GS?)

I would do a pull request, but this is non public code :)

**Comment by Qowy** [comment]
Additionally the code at prepareDerivedData in actor-dsa5.js still does it's own Encumbrance cheks. 
Might be a good idea to disable that?

**Comment by Qowy** [comment]
> Enhancement -> Ignore Effect field of Armor when Zone Armor is enabled. (Might be to simple; is there armor with other effects than -1GS?)

This could probably solved by checking for `game.settings.get("dsa5-armory2", "enableArmorZones")`
in actor-dsa5.js _addGearAndAbilityModifiers 
in this if:

`if (compensation && i.data.type == "armor" && [game.i18n.localize('CHARAbbrev.INI').toLowerCase(), game.i18n.localize('CHARAbbrev.GS').toLowerCase()].includes(vals[1].toLowerCase())) {`

**Comment by Qowy** [comment]
I added a pull request to ignore the old calculation and to ignore armor GS and INI mali in case of zone armor

https://github.com/Plushtoast/dsa5-foundryVTT/pull/823

**Comment by Qowy** [comment]
Ok I fixed The -GS/INI somewhat for me.
However since `getArmorEncumbrance` is called in `prepareItems(sheetInfo)` it is too late for just editing `gearmodifer`
This I worked around by modifiying value/max directly but it feels a bit hacky.

Additionally this is too late to be recognized by the foundry variable for movement speed
So this would have also be set manually (haven't found the right variable yet)

It might be cleaner to move the whole code to `prepareDerivedData`
but that is for you to decide. But since a check wether armory2 is installed would be needed anyway (see above) 
the override of `getArmorEncumbrance` could be replaced by a simple

`if(amory2) { call the code vrom armory2 }` and the opposite for the `getArmorEncumbrance` call in `prepareItems(sheetInfo)`

Anyway this is my `replaceArmorEncumbranceCalculation()` code which would need to be slightly edited depending on the solution

```
static replaceArmorEncumbranceCalculation() {
        let totalEncumbrance = 0
        game.dsa5.entities.Actordsa5.prototype.getArmorEncumbrance = (actorData, wornArmors) => {
            if (actorData.type == "character" || (actorData.type == "npc" && game.settings.get("dsa5-armory2", "enableArmorZonesNPC"))) {

                const armorZones = duplicate(ArmorZones.armorZones)
                const factors = duplicate(ArmorZones.factors)
                const armorEncumbranceModifiers = [0]
                for (let armor of wornArmors) {
                    for (let key of Object.keys(armorZones)) {
                        if (armor.data.protection[key] != 0) {
                            totalEncumbrance += armor.data.protection[key] * factors[key]
                        }
                    }
                    const encMod = EquipmentDamage.armorEncumbranceModifier(armor)
                    armorEncumbranceModifiers.push(encMod)
                    armor.calculatedEncumbrance = Number(armor.data.encumbrance.value) + encMod
                    armor.damageToolTip = EquipmentDamage.damageTooltip(armor)
                }
                let encStruct = ArmorZones.calcEncumbrance(totalEncumbrance)
                totalEncumbrance = encStruct.enc + Math.max(...armorEncumbranceModifiers)
                if (encStruct.mod > 0) {
                    let shortCutGS = game.dsa5.config.knownShortcuts[game.i18n.localize('CHARAbbrev.GS').toLowerCase()]
                    let shortCutINI = game.dsa5.config.knownShortcuts[game.i18n.localize('CHARAbbrev.INI').toLowerCase()]
                    actorData.data[shortCutGS[0]][shortCutGS[1]][shortCutGS[2]] -= 1
                    actorData.data[shortCutINI[0]][shortCutINI[1]][shortCutINI[2]] -= 1
                    actorData.data.status.initiative.value -= 1
                    actorData.data.status.speed.max -= 1
                    actorData.itemModifiers[game.i18n.localize('CHARAbbrev.GS')] = {
                            value: -1,
                            sources: [game.i18n.localize('encumbrance')]
                    }
                    actorData.itemModifiers[game.i18n.localize('CHARAbbrev.INI')] = {
                        value: -1,
                        sources: [game.i18n.localize('initiative')]
                    }
                }
            } else {
                totalEncumbrance = wornArmors.reduce((sum, a) => {
                    a.calculatedEncumbrance = Number(a.data.encumbrance.value) + EquipmentDamage.armorEncumbranceModifier(a)
                    a.damageToolTip = EquipmentDamage.damageTooltip(a)
                    return sum += a.calculatedEncumbrance
                }, 0)
            }
            return Math.max(0, totalEncumbrance - game.dsa5.apps.SpecialabilityRulesDSA5.abilityStep(actorData, game.i18n.localize('LocalizedIDs.inuredToEncumbrance')))
        }
```

**Comment by Qowy** [comment]
Ok there now is an updated Pull request [Improve Zone Encumbrance](https://github.com/Plushtoast/dsa5-foundryVTT/pull/823)

~~The remaining issue is that replacement of functiuon prototypes is too late for the initial foundry initialization, i will think about this further.
But once the actor gets recalculated everything should work fine now.~~

Seems to be fixed by moving the code to registerInit()
~~Some testing might be prudent. Especially interplay with armor damage.~~
-> looks good

The necessary armorzone.js code i sent you personally

**Comment by Qowy** [comment]
Any particular reason why this is still not implemented?
I'm not too bothered by it, i have my own branch and just merge that after updates. But maybe more people want to benefit from it.

I can provide updated Pull Requests that work with the current code, if needed.

**Comment by Plushtoast** [comment]
I might have forgotten to push this to foundry but as i remember this is fixed a long time ago. Ill check later today

**Comment by Plushtoast** [comment]
Are you talking about the -1GS -1 INI thing?

The rest is done afaik. But this one is missing because I dared to do 10000 other things in the meantime.

**Comment by Qowy** [comment]
> The rest is done afaik. But this one is missing because I dared to do 10000 other things in the meantime.

Bold choice daring to do other stuff ;) 
Like I said I'm not bothered by it. 
I was just asking before I take a look at it again, in case it is right next in the pipeline or something. 

I will check again which parts are done. I think increased encumbrance with damaged armor is also missing.

**Comment by Plushtoast** [comment]
No that should already be part of the solution. But as far as I know there are also no rules damage & armor parts in DSA5

**Comment by Qowy** [comment]
Yes you are right while armor damage is never explicitly stated with zone armor in the rules, it seems to work correctly.

From what I can see it really should just be the correct Encumbrance calculation:

(You probably know all this already I am just updating the issue for the interested readers benefit :) )
Current (With zone armor):

Character with "Belastungsgewöhnung 1" equipps a an Armor with Chest Armor value 3 and Effect -1gs/-1ini

He correctly receives no Encumbrance, however the effect of -1gs etc is still applied, which is wrong (he is only at "15")
This could be fixed by simply removing the -1INI effect from the item as GM

now he equips armor 3 legguards and Armguards.
He is now at "39" and should receive 1 Encumbrance and -1INI/-1GS.
The Encumbrance is correctly removed by Belastungsgewöhnung but the -1INI/-1GS is missing.

I updated the attached pull request to the current foundry9 branch

The following is the code needed in armory2

```
        game.dsa5.entities.Actordsa5.prototype.getArmorEncumbranceZone = (actorData, wornArmors, itemModifiers) => {
            let totalEncumbrance = 0
            if (actorData.type == "character" || (actorData.type == "npc" && game.settings.get("dsa5-armory2", "enableArmorZonesNPC"))) {

                const armorZones = duplicate(ArmorZones.armorZones)
                const factors = duplicate(ArmorZones.factors)
                const armorEncumbranceModifiers = [0]
                for (let armor of wornArmors) {
                    for (let key of Object.keys(armorZones)) {
                        if (armor.data.protection[key] != 0) {
                            totalEncumbrance += armor.data.protection[key] * factors[key]
                        }
                    }
                    const encMod = EquipmentDamage.armorEncumbranceModifier(armor)
                    armorEncumbranceModifiers.push(encMod)
                    armor.calculatedEncumbrance = Number(armor.data.encumbrance.value) + encMod
                    armor.damageToolTip = EquipmentDamage.damageTooltip(armor)
                }
                if (ArmorZones.calcEncumbrance(totalEncumbrance).mod > 0) {
                    itemModifiers[game.i18n.localize('CHARAbbrev.GS')] = {
                            value: -1,
                            sources: [game.i18n.localize('Equipment.armor')]
                    }
                    itemModifiers[game.i18n.localize('CHARAbbrev.INI')] = {
                        value: -1,
                        sources: [game.i18n.localize('Equipment.armor')]
                    }
                }
            }
        }
```

**Comment by Plushtoast** [comment]
thanks for your help, this is included in the next update
