### ISSUE TITLE
Spezies / Rasse ist nicht auswählbar in Bibliothek

### ISSUE THREAD

**Issue by Falkenberg2010** [Plushtoast/dsa5-foundryVTT#83]
Wenn man versucht nach der Beschreibung einen neuen Charakter zu erstellen vorgeht und dann die Biblothek öffnet, gibt es kein Auswahlfeld für Rasse oder Spezies.

Ich denke aber, dass dies erst seit dem letzten Patch fehlt.

**Comment by mckee14** [comment]
Im Kompendium ist der Eintrag "Spezies", den anklicken und man bekommt die Auwahl angezeigt und kann sie auf den Charakter ziehen.

Die "Bibliothek" hat tatsächlich keinen Filter dafür und entsprechend werden die Einträge nicht angezeigt.
