### ISSUE TITLE
Armor items with -1 GS, -1 INI Effect marked as enchanted

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#830]
Items which have a -1 GS, -1 INI Effect (which as far as I know is necessary when not using zone armor) show up as enchanted

Maybe add a check to ignore this particular effect.

Or is this intentional?

**Comment by Plushtoast** [comment]
Intentional. The green background is to show that attributes are modified. The effect field allows a bunch of additional modifiers. No need to distinguish.

**Comment by Plushtoast** [comment]
Also der Hauptgrund für den farbigen Hintergrund war ein Hinweis, dass dieser Gegenstand die Stats zusätzlich beeinflusst. Insofern ist das im Moment das gewünschte Verhalten.
Ich denke das bleibt so.

**Comment by Qowy** [comment]
Ok das einzige ist wenn https://github.com/Plushtoast/dsa5-foundryVTT/pull/823 mal drin ist dass dann Ein Bestimmtes Rüstungsitem bei ZoneArmor nicht mehr beeinflusst. Da könnte man dann noch ne abfrage reinmachen, dass bei zone armor und item == armor kein enchantment effekt drübergelegtwird. Das wäre dann auch einfacherer code, der Pull Request kann dann also vermutlich zu.
