### ISSUE TITLE
AsP Cost of Sustained spells not included

### ISSUE THREAD

**Issue by Qowy** [Plushtoast/dsa5-foundryVTT#841]
~~effects that use data.aspModifier do not work (sice 0 evaluates to false in JS and gets replaced by null ...)
Additionally a switch case for "number" is missing~~

Additionally the cost calculation currently does not seem to include the first interval of a sustained spell.
This is important for failed spell costs which state : "Misslingt der Zauberspruch, muss der Zaubernde die Hälfte der so berechneten Astralpunkte ausgeben. Beim Misslingen der Probe werden zur Berechnung des AsP-Verlustes die Grundkosten + die Kosten für die erste Zeiteinheit herangezogen."

The easiest fix would probably be to just add the initial interval cost to `finalcost` in `rollSpell` (of course after all modifications are applied)
I can think of no instance where that would be wrong

**Comment by Plushtoast** [comment]
Why do you want to have a modifier of 0?

**Comment by Plushtoast** [comment]
Everythin which is not an array will be applied with the default means of Foundry. So adding a switch statement for numbers is probably not going to happen.

**Comment by Qowy** [comment]
It's not what I want it's how it is already implemented.
aspModifier is 0 by default (of the character not the effect) which fails the type check
Have you looked at the pull request?

actor-dsa.js initializes aspModifier as a number not array

```
                aspModifier: 0,
                kapModifier: 0,
```

At least for me it was not applied by default foundry means
~~Where would the code be for that?~~

I see it should be applied by `_applyAdd` in foundry code but for some reason this was not working for me. I will look again though.

**Comment by Qowy** [comment]
Go on nothing to see here :)

You are right this is working correctly with default foundry code. Which is weird because i was trying to get it to work for 30Minutes before looking at the code. Who knows what went wrong there 😕 

This only leaves the calculation issue, I will edit this accordingly

**Comment by Qowy** [comment]
https://github.com/Plushtoast/dsa5-foundryVTT/pull/842 seems to be working.
 Just wondering if there might be any Edge Cases

**Comment by Qowy** [comment]
Added a small fix to the PR that prevents costs from going below 1 (otherwise would be 0.5 at times)

`Kosten für das Aufrechterhalten eines Zauberspruchs pro (beim Zauberspruch festgelegten) Zeitintervall liegen jeweils eine Stufe unter den Kosten des eigentlichen Wirkens. Sollten durch Kosten senken die Grundkosten des Zauberspruchs geändert werden, ändern sich auch die Kosten entsprechend beim Aufrechterhalten. Die Kosten können nie unter 1 AsP pro Intervall fallen.`
