### ISSUE TITLE
Zaubererweiterungen: Selection & Infos

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#85]
Selection of Erweiterungen when rolling for a spell is barely visible if you are colorblind (like me).
It would help to change the selection color / saturation, or make it via checkboxes.

In the chat, you can see what Erweiterungen have been selected, but you don't get any more infos about it.
Maybe include the effect as expandable text, or make it a link to the item.

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/108476777-bb69d900-7292-11eb-8b75-190c1e091b95.png)
![grafik](https://user-images.githubusercontent.com/44941845/108476821-c7ee3180-7292-11eb-8f0c-91e1ae540f78.png)
 
Is it ok like this?

**Comment by mckee14** [comment]
Looks way better already, thx!

Plushtoast <notifications@github.com> schrieb am Fr., 19. Feb. 2021, 09:14:
