### ISSUE TITLE
Attributo wird auch auf abgeleitete Werte angerechnet

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#858]
Der Bonus der Attributo-Zauber wird auf abgeleitete Werte angewendet.
Im Regel-Wiki ist dies bei Anmerkung ausgeschlossen

**Comment by Plushtoast** [comment]
Die abgeleiteten Werte werden automatisch berechnet und es ist zu aufwendig das zu Ändern.
Das wird so bleiben. Foundry spezifische Umsetzung.

**Comment by Xardai** [comment]
Ok, dann wird der mMn schwache Attributo unfreiwillig etwas verstärkt
