### ISSUE TITLE
Profession Wildnisläuferin hinzufügen findet Nachteil/Vorteil/Sonderfertigkeit: Spezies Elf nicht

### ISSUE THREAD

**Issue by foschmitz** [Plushtoast/dsa5-foundryVTT#86]
Hi, ich versuche die Standardchars aus der Drachenritterbox hinzuzufügen. Die Gute Valariel hatte ich am nächsten als Wildnisläufering antizipiert. Beim Hinzufügen kommt allerdings der Fehler 

Folgende Einträge konnten nicht umgesetzt werden bzw in der Datenbank gefunden werden:
Wildnisläuferin hinzufügen findet Nachteil/Vorteil/Sonderfertigkeit

![image](https://user-images.githubusercontent.com/9117350/108378477-50be8c00-7205-11eb-82c6-7a65253d5819.png)

**Comment by Plushtoast** [comment]
Das ist kein Fehler. Die Meldungen sind nur für dich als Spieler, dass du was tun musst.
In den Büchern steht oft sehr viel Freitext in den Bedingungen. Die sind schwierig automatisch umzusetzen.
Wir haben darauf verzichtet, die Rasse automatisch hinzuzufügen.
Hier wird sich erstmal nichts ändern.

**Comment by foschmitz** [comment]
Alles klar, vielen Dank!

**Comment by Danii0206** [comment]
Ich bin gerade auch über diese Meldung gestolpert. Was genau erwartet das Programm von mir, das ich manuell machen soll?

**Comment by Plushtoast** [comment]
Sicher stellen, dass du die Rasse Elf hinzufügst, wenn du nach den Regeln spielen willst.
