### ISSUE TITLE
Negative Trefferpunkte machen Schaden

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#870]
**Describe the bug**
Wenn der Rüstungsschutz größer als der Schaden ist wird ein negativer Schaden angezeigt. Wenn dieser vom Meister verrechnet wird, wird der Schaden positiv Abgezogen

**To Reproduce**
Trefferpunkte: 2 - 4 (Rüstungsschutz) = -2 
Werden als 2 SP verrechnet 

**Expected behavior**
Sollte 0 sein

**Comment by Plushtoast** [comment]
Du hast vermutlich "Schaden anwenden als SP" angeklickt. Die Option für TP wird gar nicht angzeigt, wenn der Schaden <=0 ist.
SP bedeutet ignoriert Rüstung, was in deiner obigen Formel 2 - 0 = 2 SP ist und damit korrekt funktioniert.

**Comment by Xardai** [comment]
Ja da hast du wohl recht hab das wohl übersehen
