### ISSUE TITLE
Nekromanthäum - Untotenerschaffung fehlerhaft

### ISSUE THREAD

**Issue by Amovitam** [Plushtoast/dsa5-foundryVTT#871]
Das Erschaffen von Untoten über das Beschwörungstool im Spieler/Meister-Menü verrechnet die Boni der erhobenen Kreatur nicht.
Des Weiteren wird eine nicht untote Kreatur, die zum Zwecke der Erhebung in as Beschwörungstool gezogen wird, nach der Freigabe des GMs weder mit den aktualisierten Werten versehen, noch wird ihr der Untotenstatus verliehen.

**To Reproduce**
1. Gehe ins Meistermenü
2. Öffne das Beschwörungstool
3. Untote auswählen
3. Beschwörenden Charakter reinziehen
4. Zu erhebene Kreatur hineinziehen
5. Wurf ausführen
6. Vom GM freigeben lassen

**Expected behavior**
Eine vorgefertigte Untote Kreatur (z. B. Brandleiche) sollte erhoben werden und mit allen Boni der ausgewählten Verbesserungen ausgestattet und die Werte wie Eigenschaften etc. angepasst werden.
Eine nicht untote Kreatur, die zum Zwecke der Erhebung in das Beschwörungstool gezogen wird um erhoben zu werden, sollte nach der Erschaffung sowohl aktualisierte Werte, als auch den Kreaturentyp Untoter haben.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Safari 15.2

**Comment by Plushtoast** [comment]
Hm kann nicht so genau nachvollziehen was du meinst.

![grafik](https://user-images.githubusercontent.com/44941845/151656608-070e14a4-46b9-4140-bf70-c2f42cf900cb.png)

![grafik](https://user-images.githubusercontent.com/44941845/151656680-4f29ac25-4541-4f58-af72-ead0b2d908dd.png)

Scheint alles da zu sein.

Was noch nicht geht sind mehrere Stufen von Wesenszügen. 
Und Charaktere in Kreaturen umwandeln geht auch nicht (weil andere Datenstruktur). Es muss immer eine Kreatur (das Akteursheet Kreatur) als Quelle herhalten.
Das wird irgenwann nachgereicht.

**Comment by Amovitam** [comment]
Oh, dann scheint das ja tatsächlich an irgendetwas bei mir zu liegen 😮
Denn wenn ich das mache, werden weder die Werte der Kröte angepasst, noch das „untot“ hinzugefügt.
Sonderbar…ich werd das gleich nochmal in einer komplett neuen Welt nur mit dem Modul des Nekromanthäums installiert testen.
Könnte das evtl. ein reines Mac-Problem sein?

**Comment by Plushtoast** [comment]
Eher kein mac problem. Ist das DSA System auf 3.1.4?

**Comment by Plushtoast** [comment]
Die Kreatur wird auch dupliziert und unter Beschwörungen abgelegt. Du kannst sie dann aus dem Chat oder aus dem Bestätigungsfenster direkt auf die Karte ziehen.

**Comment by Amovitam** [comment]
> Die Kreatur wird auch dupliziert und unter Beschwörungen abgelegt. Du kannst sie dann aus dem Chat oder aus dem Bestätigungsfenster direkt auf die Karte ziehen.

Das erfolgt auch alles.
Die duplizierte Kreatur hat auch die zum Beispiel offensiven Verbesserungen als Statuseffekt hinterlegt.
Die Effekte bewirken nur keinerlei Veränderung der Werte und eben keine Änderung des Wesenstypes.

**Comment by Amovitam** [comment]
So, alles gut. Läuft jetzt. Nachdem es in einer neuen Welt nur mit Nekromanthäum funktioniert hat, habe ich nach und nach Module hinzugefügt. Es scheint an einem selbst erstelltem Shared-Item durch das Modul My Shared Content gelegen zu haben.
Bei Aktivierung dieses Moduls tritt der Fehler auf. Nach Löschung der Items funktionierte die Erhebung wieder einwandfrei, trotz aktiviertem My Shared Content.
Neu erstellte Items verursachen den Fehler nun nicht. Also scheint es so, dass irgendeins meiner Items einen Einfluss genommen hat.

**Comment by Amovitam** [comment]
Einen Fehler habe ich jedoch nun entdeckt, jetzt, wo alles funktioniert.
Die Lebensenergie von Untoten wird wohl falsch in der Berechnung priorisiert.
Ein Grimmwolf, mit 22 Lebenspunkten, sollte durch das Lebende-Leichen-Paket die Hälfte an LeP haben, was erstmal richtig berechnet wird. Wenn ich aber die Verbesserung "Höhere Lebensenergie" vergebe, wird die vor dem Leichenpakt verrechnet.
Das heißt 22 LeP + 10 LeP aus der Verbesserung = 32. Und dann wird erst die Hälfte der LeP durch das Leichenpaket berechnet, also 16 LeP.
Nach meiner Berechnung müsste es jedoch 22 LeP geteilt durch 2 (Da das Paket die LeP halbiert) sein, also 11 und dann addiert mit der Höheren Lebensenergie-Verbesserung, also 21.
