### ISSUE TITLE
Beschwörertool Zaubererweiterung Mächtiges Wesen hat keine Funktion

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#872]
**Describe the bug**
Trotz der Zauberererweiterung 'Mächtiges Wesen' kann ich die Erweiterungen jeweils nur einmal nutzen, im Beschwörertool

**Desktop (please complete the following information):**
Aktuellste Version Foundry + DSA Module

**Comment by Plushtoast** [comment]
Zaubererweiterungen bzw deren Funktionen zu automatisieren werden wohl eher nicht kommen.

**Comment by ghost** [comment]
Ich hätte da einen Vorschlag wie man das lösen kann. Du könntest einfach ein "2x" dazuschreiben das dann im Beschwörertool angezeigt wird.
