### ISSUE TITLE
Modifikatoren nicht mehr Deselektierbar seit Foundry Update 9.245

### ISSUE THREAD

**Issue by ghost** [Plushtoast/dsa5-foundryVTT#874]
**Describe the bug**
Hallo ich kann seit dem Foundry Update 9.245 Modifikatoren nicht mehr deselektieren. In der Version 9.242 funktioniert das noch.

**Comment by Plushtoast** [comment]
Sollte in 3.1.5 gehen

**Comment by ghost** [comment]
Naja jetzt ist alles wieder desektiererbar, aber man muss wieder alles Händisch selektieren. Das war glaube ich vorher anders und das fand ich besser und der Balken hat jetzt einen Blauen Hintergrund statt einem Grauen. Aber das ist nur mein Geschmack.

**Comment by Plushtoast** [comment]
Es war vorher nicht anders. Die Dinger werden unterschiedlich automatisch angehakelt je nachdem, was das System glaubt, dass am meisten Sinn macht. In den Settings gibt es auch noch einen Haken der diese Einstellungen leicht modifiziert. Und letztendlich merkt sich das System deine erste Einstellung für die folgenden Würfe (wird zwischen den Sessions gelöscht). Ist alles wie gehabt.

Die unterschiedliche Farbe war die Browsereinstellung, die jetzt auch das Problem erzeugt hat und überschrieben wird. Da hat Chrome etwas im letzten Update merkwürdig umgesetzt.

Kommentare an geschlossenen Tickets haben außerdem eine hohe Chance übersehen zu werden. Außerdem wären das andere Dinge für ein neues Ticket sowieso.
