### ISSUE TITLE
Szene "Turm im Nebelmoor" aus dem Drachenritter Modul lädt nicht mit aktiviertem FXMaster

### ISSUE THREAD

**Issue by janckoch** [Plushtoast/dsa5-foundryVTT#882]
**Describe the bug**
In einer frisch angelegten Welt mit aktiviertem und importiertem Drachenritter-Box Modul (+ empfohlenen Modulen wie FXMaster) führt das anzeigen der Szene "Turm im Nebelmoor" dazu, dass Foundry sich aufhängt. Die Map wird zwar angezeigt, allerdings bleibt der Ladebalken bei 100% stehen und es lässt sich nicht mehr mit der Foundry UI interagieren. Nach ein paar Sekunden meldet Chrome, dass die Seite nicht mehr reagiert. Weder im Log von foundry noch in der Developer Console tauchen verdächtige Fehlermeldungen auf. Wenn man FXMaster deaktiviert lädt die Szene ohne Probleme. Das ganze wurde auf mehreren Rechnern getestet.

Getestet auf:
Foundry v9 Build 249
DSA5 System 3.1.5
DSA Core Rules 3.1.0
Drachenritter Modul 2.5.0
FXMaster 2.2.4

**Comment by Alexander-HPA** [comment]
Da die Wettereffekte alle "verrückt" spielen, nehme ich mal an, dass die Parameter für die Wettereffekte nicht (mehr?) richtig an FXMaster übertragen werden. So habe ich auf allen Karten mit Wettereffekten den Bildschirm innerhalb kürzester so voll mit Vögeln/Raben/Nebel/Wolken/Regen, dass der Browser die Waffen streckt. Der "Turm im Nebelmoor" geht gar nicht mehr auf, bei allen anderen kann man - wenn man schnell und geduldig ist - noch was retten, indem man die Wetterparameter manuell fixt...

**Comment by Plushtoast** [comment]
Ja es funktioniert derzeit nur mit deaktiviertem FXmaster
