### ISSUE TITLE
[Content][Armory 3.1.0]Rapier hat falschen PA-Modifikator

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#883]
**Describe the bug**
Das Rapier hat den falschen PA-Modifikator von 1/0. Im Modul DSA-Core ist der Modifikator richtig mit 0/0 angegeben.

**Additional context**
Dankschön!

**Comment by Plushtoast** [comment]
Hm in meinem Armory PDF hat es 1/1 und die Zusatzbände gelten oder nicht?

**Comment by DerGreif** [comment]
Die Werte aus der Rüstkammer entsprechen denen aus der ersten Auflage des Grundregelwerks. Aber in der 2. und 3. Auflage des GRW wurden diese Werte entsprechend geändert, dort hat es AT/PA 1/0, also Parade-Modifikator von 0/0 (für Haupthand/Nebenhand). Der Fehler liegt hier mehr bei der DSA-Redax. Ich verstehe, wenn Du es lassen willst, Konsens scheint aber zu sein, dass die Werte aus der Rüstkammer ein Redax-Versehen waren und die neueren GRW Werte gelten sollen.

Wie stets: Ganz herzlichen Dank für all Deine Mühen!

**Comment by DerGreif** [comment]
Ergänzung: Im Regelwiki ist der AT/PA-Modifikator auch mit 1/0 angegeben, also mit einem PA-Modifikator von 0, obwohl dort auch Bezuf auf die Rüstkammer genommen wird.
