### ISSUE TITLE
Tintenbilder in dsa5-armory2-Modul anpassen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#891]
Das Item Tinte aus dem dsa5-core-Modul hat ein eigenes Tinten-Bild.
Die Tinten aus dsa5-armory2 haben dagegen einen Federkiel als Bild.

Es würde in meinen Augen Sinn machen, das Tinten-Bild durchgehend für die Tinte zu verwenden.

Es wäre super, wenn das im Zuge eines Updates angepasst werden könnte.

**Comment by Murm3lt13r** [comment]
pictures updated
