### ISSUE TITLE
Wiederholungsproben bei Fertigkeiten vorsehen

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#893]
Laut Regelwerk S.25 gibt es die sogenannte _Wiederholungsproben_. Sofern eine solche Probe zulässig ist, ist die nachfolgende Probe zusätzlich um 1 erschwert. Automatisch lässt sich das wohl kaum abbilden, aber beim Eingabefenster für eine Fertigkeitsprobe wäre es nett, wenn man die Anzahl der Fehlversuche eintragen könnte (ähnlich z.B. wie bei durchgeführten Paraden im Kampf).

Es gibt SF wie z.B. [Routinierte Zauberwiederholung](https://www.ulisses-regelwiki.de/RoutinierteZauberwiederholung.html), die bei magischen Fertigkeiten den Abzug von einem Punkt verhindert. Dies ließe sich ggf. automatisch berücksichtigen.

**Comment by Plushtoast** [comment]
Würde sagen, das Modifikatorfeld genügt hier völlig, weil wie du sagst sich das kaum automatisieren lässt.
