### ISSUE TITLE
"Alles migrieren" bei der Importfunktion

### ISSUE THREAD

**Issue by Albinosheep** [Plushtoast/dsa5-foundryVTT#894]
Mit Hilfe der [Importfunktion ](https://github.com/Plushtoast/dsa5-foundryVTT/wiki/de-Import-Funktion)kann man einen Akteur bisher vollständig aktualisieren, indem man alle Teilbereich (wie Zauber, Sonderfertigkeiten, Talente etc.) einzeln migriert.

Ich würde mir eine "alles migrieren" Funktion wünschen. Das hätte mir schon das ein oder andere Mal einige Nerven gespart. :-)

**Comment by Plushtoast** [comment]
duplicate of #649

**Comment by Albinosheep** [comment]
#649 schlägt ein Makro vor, alle Wesen zu migrieren. Das wäre natürlich eine tolle Erleichterung!
Mein Vorschlag sieht vor, in einem Actor alle Bereiche zu aktualisieren. Fasst man das bestehende und die beiden Vorschläge zusammen hätte man:

1. Einzelne Bereiche migireren.
2. Alle Bereiche eines Akteur migrieren.
3. Alle Bereiche aller Akteure migrieren.

Der 2. wäre natürlich nicht so wichtig, wenn es 1 und 3 schon gibt. Wenn es nicht viel Arbeit wäre, verdient es möglicherweise ja doch Beachtung.
