### ISSUE TITLE
Konflikt Modul DF Chat Enhancement vs. DSA: Verdoppelung des Chat-Textes und der Würfelwürfe (inkl. Animation)

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#896]
**Describe the bug**
Wenn DSA als Welt verwendet wird und gleichzeitig das Modul DF Chat Enhancement aktiv ist, dann verdoppelt sich der Chat-Text und die Würfelwürfe.

**To Reproduce**
1. neue DSA-Welt erstellen und Welt starten.
2. Modul DF Chat Enhancement aktivieren (alles andere deaktivieren)
3. Im Chat beliebigen Text eingeben
4. Im Chat /roll 1d6 eingeben
4. See error in Chatfenster

**Expected behavior**
Chat Text wird nicht verdoppelt.
Es wird nur ein Würfel geworfen (z.B. bei aktiven Modul "Dice so Nice!" werden auch zwei Würfel-Animationen gezeigt).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/87266660/152801508-0aaa73d3-8857-4dd6-9870-bc26d076080d.png)

**Versions:**
- Foundry Version: 9.249
- DSA/TDE version: 3.1.5
- Related modules version 3.6.0

**Comment by Plushtoast** [comment]
Alle chat module sind inkompatibel mit DSA.
