### ISSUE TITLE
Latest packs use type in module.json when it should be entity

### ISSUE THREAD

**Issue by Lambert-Behnke** [Plushtoast/dsa5-foundryVTT#897]
Description
The last couple of packs Gods 1 (Eng), and Compendium 1 (Eng) have the following style entries in the module.json

    "packs": [
        {
            "name": "godsspecialability",
            "label": "Sonderfertigkeiten",
            "system": "dsa5",
            "path": "./packs/godsspecialability.db",
            "type": "Item"
        },

That last **type** should be **entity**.

What that means is that Compendiums no longer show up in the right place, but in a new place called DEFAULT.

![CompendiumSidebar](https://user-images.githubusercontent.com/82769448/152968405-58e5704b-62f4-499d-b470-a6a8be358823.png)

Rest of my default group:
![Rest of Default](https://user-images.githubusercontent.com/82769448/152968881-af5372b8-eaa4-4ecd-a975-4609ca1f0b17.png)

**Expected behaviour**
If you use entity, which is a required field, the compendiums will appear back in the correct subgrouping like Actor, Item etc.

**Comment by Plushtoast** [comment]
Entity is deprecated by foundry and will disappear in the next foundry version entirely.
Your compendium folders module is doing the sorting here....not tde. So it should update

**Comment by Lambert-Behnke** [comment]
See, you learn something new every day.
Thank you and feel free to reject.
