### ISSUE TITLE
"Funktionslose" Items sichtbar gestalten

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#898]
Einige Zauber, Liturgien, Vor- und Nachteile usw. haben die Wirkung ja nicht mechanisch hinterlegt, weil deren Umsetzung einfach zu kompliziert bzw unmöglich ist.
Was auch ok ist  man kann sowas als GM/Spieler auch selbst nachrechnen/nachverfolgen.

Aber inzwischen ist man so dermaßen an die Automatisierung gewohnt, dass solche betroffenen Items schnell übersehen werden können (insbesondere, da manche Funktionen überhaupt nicht sichtbar sind, und nur durch testen herausgefunden werden können, ob es diese gibt oder nicht)

Darum würde ich vorschlagen ,  dass man schon im Namen (oder übersicht) des Items erkennen kann, ob dieser eine Funktion hinterlegt hat (grünes Lämpchen), oder ob der GM/Spieler in diesem Fall aktiv werden muss (rotes Lämpchen).

**Comment by vt-tom** [comment]
@Plushtoast wäre das nicht ähnlich umsetzbar wie die im neuen Patch verfügbaren "On use Effects"? also alles was einen Effekt hat bekommt im Namensfeld einen indikator?

**Comment by Plushtoast** [comment]
Ich weiß nicht...kann den Wunsch danach verstehen. Aber die Antwort ist wohl nein.
Da gerade viel mehr automatisiert wird, ist das irgendwie genau das Gegenteil von dem was ich für logisch betrachte.
Also Arbeit in die falsche Richtung.
