### ISSUE TITLE
Modifiers for RS

### ISSUE THREAD

**Issue by mckee14** [Plushtoast/dsa5-foundryVTT#90]
A possibility to temporarily modify the Rüstungsschutz would be nice. If you cast an Armatrutz, there is currently no direct way to add some RS to a character.

It could be implemented via the Status Page in the charsheet, and/or a (linked) field on the combat page.

**Comment by Plushtoast** [comment]
The solution for this will take some time,
As a workaround I suggest, you create a manual armor named "Armatrutz" and only equip it when the spell is active.

**Comment by mckee14** [comment]
I did that already. Not a big deal.

And let me know if you prefer feedback via discord for all these little
things.

Plushtoast <notifications@github.com> schrieb am Fr., 19. Feb. 2021, 12:15:

**Comment by Plushtoast** [comment]
No github is perfect. Discord might get lost, or disappear in the background noise.


Holen Sie sich Outlook für Android


Von: mckee14 <notifications@github.com>Gesendet: Freitag, 19. Februar 2021, 12:20An: Plushtoast/dsa5-foundryVTTCc: Plushtoast; CommentBetreff: Re: [Plushtoast/dsa5-foundryVTT] Modifiers for RS (#90)

I did that already. Not a big deal.



And let me know if you prefer feedback via discord for all these little

things.



Plushtoast <notifications@github.com> schrieb am Fr., 19. Feb. 2021, 12:15:
