### ISSUE TITLE
Resultat der Chatkommandos /pay und /getPaid vertauscht (?)

### ISSUE THREAD

**Issue by sirgawain111** [Plushtoast/dsa5-foundryVTT#900]
**Describe the bug**
Das Chatkommando /pay resultiert darin, dass die Chars die angegebene Summe erhalten, anstatt sie zu bezahlen.
Das Chatkommando /getPaid resultiert darin, dass die Chars die angegebene Summe bezahlen, anstatt sie zu erhalten.

**Expected behavior**
/pay: Den Chars wird Geld abgezogen
/getPaid: Den Chars wird Geld hinzugefügt

**Versions:**
- Foundry v9.249
- DSA/TDE version 3.1.5

**Comment by Daemon031** [comment]
Hier sind nach wie vor die Beschreibung im Foundry unter /help nicht ganz richtig beschrieben.
Das System ist ein wenig verwirrend aber ich erkläre es mal:

**/pay** -> bedeutet, dass man von SICH aus Geld ausbezahlt:
Gibt der Meister /pay ein zahlt der Meister die Spieler aus und einer der Spieler empfängt das Geld wenn er den Knopf drückt.
Gibt der Spieler /pay ein bezahlt er den genannten Betrag an den Meister. (Es erscheint kein Knopf)

Aktuell wird das **fälschlicherweise** angezeigt bei /pay
![Bild_2022-04-12_225424225](https://user-images.githubusercontent.com/103536459/163052856-bfd50c91-caee-45b1-89a0-8cc7733bfc19.png) 

<br>


**/getPaid** -> bedeutet, dass man BEZAHLT wird:
Gibt der Meister /getPaid ein wird Geld von den Spielern VERLANGT. Drückt ein Spieler den Knopf wird der Geldbetrag abgezogen.
Gibt der Spieler /getPaid ein wir der Geldbetrag dem Spieler ZUGEWIESEN. (Es erscheint kein Knopf)
![Bild_2022-04-12_225938046](https://user-images.githubusercontent.com/103536459/163053647-4e22d71c-4add-4772-8950-ff5ee3878d1c.png)

Das Problem ist, dass dem Meister UND den Spielern die gleiche Chatnachricht angezeigt werden. Dies müsste ja jeweils anders aussehen.
