### ISSUE TITLE
Statuseffekt "besiegt" / Totenkopf-Symbol

### ISSUE THREAD

**Issue by KnoepfchenFulla** [Plushtoast/dsa5-foundryVTT#905]
Gäbe es eine Möglichkeit, den Statuseffekt "besiegt" (also den Totenkopf) für Spieler anzuzeigen, selbst wenn anderen Statuseffekte an Tokens über die Systemeinstellungen verborgen worden sind? 

Ich möchte ungern, dass meine Spieler jederzeit sehen, wie viele Stufen Paralyse und Co ein Gegner hat oder unter wie vielen Stufen Schmerz ein Gefährte aktuell leidet, weil das oft zu unschönem Metagaming führt. Aber so ein Totenkopf für besiegte Gegner macht es für alle übersichtlicher, um zu überblicken, wer noch im Kampf ist und wer nicht, und das ganz ohne Metagaming-Gefahr.

**Comment by DerGreif** [comment]
Ich kenne das Problem. Wir haben das vorläufig durch ein Modul gelöst, das sich Health Estimate nennt. Eine fertige Lösung wäre natürlich super.
