### ISSUE TITLE
[Enhancement] Warnung bei AT wenn kein Ziel ausgewählt ist

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#906]
**Is your feature request related to a problem? Please describe.**
Es kommt immer wieder vor, dass die Spieler vergessen vor ihrer AT ein Ziel auszuwählen, was dazu führt, dass die ganzen schönen Automatisierunge, die daran geknüpft sind, nicht zur Geltung kommen. Die unterbricht - gerade im Kampf - den Spielfluss erheblich und zieht die Kämpfe unnötig in die Länge. Das kleine Feld "kein Ziel" oben rechts wird leider leicht übersehen.

**Describe the solution you'd like**
Bevor der Spieler eine AT würfelt, wird er durch ein Pop-Up gewarnt, wenn er kein Ziel gewählt hat. Es geht erst weiter, wenn er ein Ziel ausgewählt hat oder er den Button "weiter ohne Ziel" anklickt, falls dies bewusst geschehen ist. Screenshots wie das aussehen soll, reiche ich nach. 

**Additional context**
Toller Patch! Freue mich schon auf das Core-Update! :-)

**Comment by vt-tom** [comment]
Ich bin dagegen, denn wir haben auch kämpfe in denen die Spieler den Gegner nicht auf der Spieloberfläche haben (Landing Page) und wir recht klassisch kämpfen. Da wäre ein weiteres Fenster sehr störend. Ich weiß auch, dass ich nicht der einzige bin der das so macht.

Meiner Meinung nach sollte die Anzeige im Proben Fenster sowie der Hinweis des SLs nachdem es mehrfach vergessen wurde eigentlich ausreichen.

**Comment by DerGreif** [comment]
Mglw. ließe sich ja dieses Fenster optional in den Spielgrundeinstellungen gestalten, Bei uns ist es leider so, dass das nicht ausreichend ist. Das Fenster hat sich sehr bewährt.

Alternativ ließe sich evtl. abfragen, ob sich der attackierende Akteur in einem Konflikt befindet und nur dann wird das Fenster aktiviert.

**Comment by vt-tom** [comment]
Ja, darauf wollte ich mit meinem Kommentar auch hinaus. Wenn es umgesetzt wird, dann bitte optional, den sonst landet hier halt wieder n Ticket von mir dass es wieder weg soll und bevor die Entwickler denken wir trollen sie, sollte das nicht unerwähnt bleiben ;)

**Comment by mckee14** [comment]
Es beruhigt mich sehr, dass ich nicht der Einzige bin, der sich mit solchen Usern herumschlagen muss. Und die machen das nicht mal absichtlich oder weil sie doof sind, nur absolut keine Ahnung von Computern haben. Schon das Navigieren der GUI an sich ist Herausforderung…

 

Dennoch würde ich es den Spielern verweigern als Option, sonst klicke ich mir als SL die Finger wund. Also +1 für «nur Optional bitte».

**Comment by Plushtoast** [comment]
Das Angriffsfenster hat bereits eine Warnung, dass kein Ziel ausgewählt wurde, die deine Spieler in diesem Fall wohl dann schon erfolgreich ignoriert haben.
Ich werde auf keinen Fall 2x die gleiche Funktion einbauen. Außerdem denke ich, dass das extra fenster nichts weiter als nerviger Spam wird.

**Comment by DerGreif** [comment]
Leider ist die Warnung für meine Spieler nicht deutlich genug im Eifer des Gefechts. Daher haben wir das Problem dann mit dem Fenster gelöst. Spam wird es nicht, weil es nur aufpoppt wenn man im Kampfmodus eine AT machen will und kei Ziel ausgewählt hat. Hat man ein Ziel ausgewählt oder macht man etwas anderes wie PA oder Zauber oder Proben, poppt das Fenster gar nicht auf. Seither passiert das mit dem fehlenden Ziwel nicht mehr und die Kämpfe laufen deutlich flüssiger. 

Auch hier würde unser Programmierer gern den Code zur Verfügung stellen, vorausgesetzt, dass das nur der Zeitfaktor ist.

Aber auch hier gilt. Wir als Gruppe haben die Funktionalität, also insofern nicht weiter tragisch. Danke, dass Ihr Euch damit befasst habt!

@mckee14 Unser Programmierer hat das so programmiert, dass man da als GM nichts klicken muss, wenn die Spieler kein Ziel wählen, nur die Spieler selber.
