### ISSUE TITLE
[Enhancement] Selektive Regeneration

### ISSUE THREAD

**Issue by DerGreif** [Plushtoast/dsa5-foundryVTT#907]
**Is your feature request related to a problem? Please describe.**
Derzeit kann man alle Energien nur gemeinsam regenerieren. Es gibt aber Situationen, in denen die Regeneration nur einer Energie sinnvoll ist.

Beispiel 1:
Ein geheimer Phex-Geweihter der auch OOC den anderen Mitspielern als solcher nicht bekannt ist, möchte seine Karmaenergie vor den anderen versteckt regenerieren. Da dies grds. im Chat gepostet wird, müsste er seine gesamte Regeneration verdeckt würfeln, was ebenso verdächtig wäre. Oder die anderen Spieler sehen die KE-Regeneration.

Beispiel 2:
Wenn man unter dem Zustand Trance leidet, kann keine Astralenergie regeneriert werden. Dann wäre es sinnvoll, dass der Geweihte LE und KE separat von AE regenerieren kann. Oder der Meister unterbindet bei entsprechender Optionalregel zB die KE-Regeneration, weil sich der Geweihte nicht gottgefällig verhalten hat.

**Describe the solution you'd like**
Der Spieler kann auswählen, welche Energie er regeneriert und entsprechend auch zB eine Regeneration verdeckt würfeln und die andere nicht. Screenshots reiche ich wieder nach.

**Additional context**
Wie stets ein herzliches Dankeschön dafür, dass Ihr so viel Herzblut da reinlegt, uns Online-Gruppen ein möglichst bequemes Spiel zu ermöglichen!

**Comment by Plushtoast** [comment]
Das ist ein Edgecase den ich auch nicht abdecken werden. 
Müllt das GUI zu, braucht 1 von 1000.
Einfach normal mit W6 würfeln.

**Comment by DerGreif** [comment]
Unsere Gruppe braucht das regelmäßig - sowohl der Magier als auch der Phex-Geweihte. Das GUI wird dadurch auch nicht zugemüllt. Bei Gelegenheit liefere ich noch Screenshots nach. Wenn es hilft, unser Programmierer stellt den Code dafür auch gern zur Verfügung. 

Aber von userer Seite ist es natürlich nicht so wichtig, wir haben diese Funktionalität ja. Trotzdem Danke für die rasche Antwort!

**Comment by DerGreif** [comment]
Hallo, ich wollte nur nochmal - für den Fall, dass Ihr es vllt. doch noch einbauen wollt, hier den Code hinterlegen:

[code.txt](https://github.com/Plushtoast/dsa5-foundryVTT/files/8846680/code.txt)

Außerdem hier ein Screenshot, der zeigt dass das GUI nicht über Gebühr belastet wird. Alles, was hinzu kommt, sind die zwei Auswahllkästchen mit dem Haken:
![Selektive Regeneration](https://user-images.githubusercontent.com/83356688/172222770-4c6e7e00-fe62-4938-8c1f-313335468bbc.png)
