### ISSUE TITLE
[The Forge - Dice so nice] Fehler in the Forge mit Dice so nice und DSA

### ISSUE THREAD

**Issue by vt-tom** [Plushtoast/dsa5-foundryVTT#908]
**Describe the bug**
Wenn Dice so nice aktiv ist, wird seit Version 3.2.0 keine Probe mehr gewürfelt. Bei genauerer  Betrachtung fehlt die komplette Einstellung dafür in den Systemeinstellungen, was die Ursache für den Fehler in der Konsole sein kann.

Ich bin mir aber nicht sicher ob das Problem jetzt direkt vom System, the Forge oder Dice so nice verursacht wird.

**To Reproduce**
1. Geh ins Spiel bei the Forge
2. Würfel eine Probe

**Screenshots**
Settings links The Forge, rechts lokal.
![grafik](https://user-images.githubusercontent.com/80099175/155074693-b06a4ea1-cb87-47c0-b0b5-5b084e6d91c1.png)

Fehler Konsole
![grafik](https://user-images.githubusercontent.com/80099175/155075117-23470b76-13ba-49b2-8021-b8071d0a136e.png)

**Versions:**
- Foundry Version: 9.249
- DSA/TDE version: 3.2.0
- Related modules version:
- Dice so nice: 4.4.0

**Comment by Plushtoast** [comment]
Forge wird zunemehmen anstrengender mit den Extra Süppchen die die kochen.
Ich weiß gar nicht was das soll, das ist doch bescheuert.
