### ISSUE TITLE
Dice So Nice nicht kompatibel mit DSA 2.x/3.x auf Forge VTT

### ISSUE THREAD

**Issue by argentorum** [Plushtoast/dsa5-foundryVTT#909]
Nach dem (System)Update auf DSA 3.2.1 auf Forge VTT werden keine Würfelwürfe mehr ausgeführt, falls Dice So Nice aktiviert ist. (Nach Deaktivierung des Moduls funktionieren sie wieder)
Es wird eine Fehlermeldung geworfen und die Einstelloption für Dice So Nice taucht beim DSA System nicht auf. Dieser Verhalten konnte auf Forge VTT eingegrenzt werden, lokale Installationen sind nicht betroffen.

Einstellungen Forge vs. lokal:
https://cdn.discordapp.com/attachments/812254122022928384/945566107828367390/unknown.png

Fehlermeldung auf Forge:
https://cdn.discordapp.com/attachments/812254122022928384/945675818246500413/unknown.png

- Foundry Version v9
- DSA/TDE version 543.2.1
- Related modules version Dice So Nice 4.4.0

**Comment by argentorum** [comment]
Nachtrag: Das Issue konnte mit Foundry v8 und DSA 2.5.1 reproduziert werden. Forge Support ist ebenfalls kontaktiert.

**Comment by Plushtoast** [comment]
Momentan sehe ich keine andere Möglichkeit, als bei jedem Spieler separat folgendes Makro anzulegen und auszuführen nach jedem Login:
```
import (foundry.utils.getRoute('/modules/dice-so-nice/Utils.js')).then(module => {
            game.dsa5.apps.DiceSoNiceCustomization.initConfigs(module)
            game.dsa5.apps.DiceSoNiceCustomization.constructor.onConnect()
        })
```

**Comment by mckee14** [comment]
Das läuft bei mir sowohl lokal, als auch im Docker Container auf dem NAS hinter einem reverse proxy. Dürfte definitiv eine Forge Sache sein.

Was basteln die auch rum? Der Vorteil von Foundry ist doch gerade diese simple Paketverwaltung, da greift man nicht kreativ rein... ausser ich versteh das falsch, kann natürlich auch sein :)

**Comment by argentorum** [comment]
> Momentan sehe ich keine andere Möglichkeit, als bei jedem Spieler separat folgendes Makro anzulegen und auszuführen nach jedem Login:
> 
> ```
> import (foundry.utils.getRoute('/modules/dice-so-nice/Utils.js')).then(module => {
>             game.dsa5.apps.DiceSoNiceCustomization.initConfigs(module)
>             game.dsa5.apps.DiceSoNiceCustomization.constructor.onConnect()
>         })
> ```

Danke für den schnellen Workaround. Wir bleiben bei Forge ebenfalls an der Sache dran.

**Comment by argentorum** [comment]
Als Update für alle: Der Forge Support hat die Sache den hauseigenen Entwicklern übergeben und die schauen es sich mal an.

**Comment by Plushtoast** [comment]
Soll wohl gefixt sein auf Forge.
Bitte einmal bestätigen, dass ich das schließen kann.

**Comment by argentorum** [comment]
Ist jetzt von Forge gefixt und verifziert, danke für den schnellen Workaround und das Prüfen. Issue kann geschlossen werden.
