### ISSUE TITLE
Strukturpunkte für Waffen

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#913]
**Is your feature request related to a problem? Please describe.**
Das relativ neue kombinierte Bruchfaktor-Strukturpunktsystem ist der totale Hammer! Jedoch verfügen die in den Kompendien hinterlegte Waffen nicht standardmäßig über Strukturpunkte. Die kann man zwar problemlos selbst nachtragen, wenn man aber mal eben Standardgegner aus den Kompendien zieht oder die Helden Standardwaffen aufnehmen, muss man, sobald eine BF-Probe notwendig wird, daran denken dies vorher zu erledigen. Auch wird beim Migrieren der Ausrüstung, so man nicht die Waffe zuvor etwas umbenannt hat, der Strukturpunktewert wieder überschrieben. Spieler, die selber daran rumfummeln, um das zu beheben und im Gegensatz zum Meister nicht immer alle Details von Regelsystem und Foundryimplementierung auf dem Schirm haben, können auch ausversehen Werte, die nicht durch vier teilbar sind, eingeben und sich dann wundern, warum es nicht funktioniere.

**Describe the solution you'd like**
Da das System jetzt so schön da ist, wäre es toll, wenn die Waffen in den Kompendien auch standardmäßig einem funktionierenden Strukturpunktewert hinterlegt würden, um das Spiel dahingehend zu vereinfachen und zu beschleunigen. :)

**Comment by Plushtoast** [comment]
Erfordert leider erst ein update aller module
