### ISSUE TITLE
Effekt Änderungsart "addieren" gespiegelt

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#914]
Wenn man beispielsweise die Asp-Kosten reduzieren möchte, wegen SF Kraftfokus, dann werden beim Eintrag "-1" ein Punkt zu den Aspkosten addiert, und wenn man nur "1" schreibt, abgezogen.
![image](https://user-images.githubusercontent.com/82062265/155872840-a0190c9e-e80b-415a-a4e4-46e3a2116f02.png)
![image](https://user-images.githubusercontent.com/82062265/155872887-511cccaa-a13e-415f-bad2-8273d882ecc1.png)

**Comment by Plushtoast** [comment]
Ja das ist so beabsichtigt.

**Comment by Zonenpenner** [comment]
Wird ja sicherlich gute Gründe haben. Da diese aber für viele Nutzer sicherlich nicht intuitiv nachvollziehbar sind (mich eingeschlossen ;) ), könnte man dies eventuell in der Wiki unter "Selbst erstellte Effekte" erwähnen, um bastelnden Laien zu helfen.

**Comment by mckee14** [comment]
Jeder kann sich am wiki beteiligen. Einfach forken, anpassen und einen pull
request machen auf github :)

Zonenpenner ***@***.***> schrieb am So., 27. Feb. 2022, 10:12:

**Comment by Zonenpenner** [comment]
Achsooo, danke ich schau mir das an.

**Comment by Plushtoast** [comment]
Es ist doch nicht so beabsichtigt :)

**Comment by Zonenpenner** [comment]
:D Ich lösch mal meinen Wiki-Vorschlag....
