### ISSUE TITLE
Patzertabellen für Unbewaffnete

### ISSUE THREAD

**Issue by Danii0206** [Plushtoast/dsa5-foundryVTT#919]
Aktuell wird in den Patzertabellen nicht berücksichtigt, falls jemand unbewaffnet ist. Mir ist allein in der letzten Runde 2x passiert, dass ein unbewaffneter SC seine Waffe fallen lassen sollte.

Vorschlag: Bei Würfelpatzern im Chat neben der Standardtabelle auch die Variante für Unbewaffnete anbieten. ("Ist ein Kämpfer unbewaffnet, wird auf das Würfelergebnis 5 addiert, sollte es unter 7 bleiben.")

**Comment by Plushtoast** [comment]
Wie genau hast du das ausgewürfelt?
Bei normalen Waffenlosen Angriffen is das automatisch drin:
![grafik](https://user-images.githubusercontent.com/44941845/157499773-1cf7ac97-0139-403c-adba-284997b8ae25.png)

**Comment by Plushtoast** [comment]
Ah ne hab das Problem gefunden
