### ISSUE TITLE
Rüstungschutz größer als Trefferpunkte addiert Lebenspunte

### ISSUE THREAD

**Issue by foschmitz** [Plushtoast/dsa5-foundryVTT#93]
Ist der RS grösser als die TP werden bei "Schaden anwenden" Lebenspunkte hinzugefügt.
![trefferpunkte](https://user-images.githubusercontent.com/9117350/108534153-196ddf00-72da-11eb-92d8-7eadcc02a890.png)

**Comment by Plushtoast** [comment]
It s a feature not a bug
