### ISSUE TITLE
Andergaster/Nostrianer falsche Kampftechnik

### ISSUE THREAD

**Issue by Nellkir** [Plushtoast/dsa5-foundryVTT#931]
Der Andergaster hat fälschlicherweise die Kampftechnik Dolche, wo es natürlich Zweihandschwerter sein sollten :)

![image](https://user-images.githubusercontent.com/82062265/158060470-67b9fe11-6cd6-4077-8cf9-8d372ecd1a32.png)

**Comment by Nellkir** [comment]
vielleicht hat man sich da vom abgewandelten Crocodile Dundee Zitat etwas in die Irre führen lassen ^^

![image](https://user-images.githubusercontent.com/82062265/158060523-3e3618d0-69c3-429f-b039-cc0f0ce87df9.png)

**Comment by Plushtoast** [comment]
Duplicate of #878

**Comment by Plushtoast** [comment]
Duplicate of #903
