### ISSUE TITLE
Begegnungen Spieler verzögerung

### ISSUE THREAD

**Issue by Foseti** [Plushtoast/dsa5-foundryVTT#933]
Wäre es möglich einen einfachen Mechanik zum verzögern einer Aktion innerhalb einer Kamprunde zu machen.
Ideal wäre ein Button zum verzögern, welcher die Initiative für eine Runde reduziert damit man am ende der Liste steht.
Am ende der Runde wird der Wert wieder zurück gesetzt.

grüße
Foseti

**Comment by mckee14** [comment]
+1 dafür, das wäre mega!

In grossen Kämpfen mit Verzögerung verliert man total den Überblick, wer was schon gemacht hat und was noch zur Verfügung hat. Und dann muss man ewig viel hin und her klicken um den aktiven Kämpfer auszuwählen.



Gemäss Regeln darf man seine freie Aktion jederzeit ausführen und seine Aktion frühestens, wenn man gemäss INI an der Reihe ist. Man darf sie verzögern und ab diesem Moment darf man sie ebenfalls jederzeit ausführen.
Ein einfaches «Ans Ende Stellen» löst also nur einen Teil des Problems.

Ein Ansatz wäre, den Chars temporär tiefste INI zuzuweisen (1.00, 0.99 etc), so dass sie ans Ende rutschen – bei gleichzeitigem Verzögern aber ihre Reihenfolge zueinander behalten.
Ein zusätzliches Symbol im Encounter für «Aktion»: 
Ist ein Char aktiv und klickt «next», wird der Button durchgestrichen und der Char hat seine Aktion verbraucht. 
Ist ein Char an der Reihe und klickt auf den Button, rutscht er ans Ende und der Button wird optisch markiert als Hinweis, dass er die Aktion noch zur Verfügung hat. Gleichzeitig wird der nächste char gemäss INI aktiviert.
Klickt der GM auf den Button eines Chars, welcher Verzögert hatte, wird der Char vor den aktiven char verschoben, aktiviert und ist an der Reihe. «Next» verbraucht seine aktion und stellt seine ursprüngliche INI wieder her.

So ungefähr könnte das voll automatisiert werden.

Alternativ: Drag & Drop der Kampfteilnehmer erlauben, inkl. Möglichkeit die Standard Sortierung gemäss INI wieder herzustellen

**Comment by vt-tom** [comment]
Würde nicht ggf einfach ein marker in der INI Reihenfolge ausreichen: "Char verzögert" So sieht der SL und jeder andere, welcher Char ggf nochmal dran ist. Dann geht man die INI einfach weiter durch und derjenige der Verzögert hat sagt dann "jetzt will ich".

Das Verzögern könnte man entweder im Charbogen oder im Angriffsfenster (Taste b wenn man an der Reihe ist) unterbringen. Nach dem Klick gibt es n Marker im Combat Tracker (Vielleicht sogar der Status "Verzögert") der am Ende einer Runde wieder entfernt wird.

Ich glaube das wäre nutzen/aufwand technisch noch am ehesten umzusetzen und zu nutzen.

**Comment by mckee14** [comment]
Auch da muss eine Grafik angepasst und die Funktion hinzugefügt werden. Ich denke, Aufwand und Komplexität kann Plushtoast gut selber einschätzen, meist hat er ja noch viel bessere Implementierungen als meine Konzepte hergäben.

Dein Vorschlag löst quasi nur das Problem, dass man sich merken muss, wer verzögert. Es löst nicht das (grössere) Problem der Bedienung. Nur dafür macht der Aufwand aber imho wenig Sinn.

Wenn man sich das schon antut, sollte eine echte Verbesserung rausspringen.

In den meisten Kämpfen ist es händisch gut machbar. gerade letzte Woche hatten wir 6 chars und 12 moorleichen, etliche wollten verzögern. Ladezeiten, Zauberdauern... hab mir die vorderen Fingerglieder weggeklickt in dem kampf :)

**Comment by Plushtoast** [comment]
Ic hwürde eher zu Toms Vorschlag tendieren.

Wenn man da was umsortieren will, musste man gleich noch einiges mehr anpacken, sonst ist das für die meisten User viel zu umständlich in der Verwendung.

Also z.B.

- [ ] Marker
- [ ] Drag and Drop reorder (mit Reset im neuen Durchlauf)
- [ ] Und dann eher sowas wie das Modul Combat Carousel nur eben mit den Anforderungen für DSA

**Comment by mckee14** [comment]
Drag & Drop löst schon fast alles :)

Plushtoast ***@***.***> schrieb am Mi., 16. März 2022, 12:46:

**Comment by Nellkir** [comment]
Vote for Marker^^
