### ISSUE TITLE
Verpflichtung (Rondra/Boron) - Geweihter passt nicht

### ISSUE THREAD

**Issue by Falkenberg2010** [Plushtoast/dsa5-foundryVTT#936]
Im Regelwerk steht, dass er entweder Tempel oder Kirche zu wählen hat und nur die höchste Verpflichtung zählt (GRW 179).
![image](https://user-images.githubusercontent.com/79263830/159234067-620a352e-e987-4fd1-b987-86a92964c737.png)

Wenn man die Profession (beim Erschaffen) reinzieht bekommt er aber 2x20 AP abgezogen (1x für Tempel und 1x für Kirche)
![image](https://user-images.githubusercontent.com/79263830/159233181-12f266ab-14dd-4ed3-969a-5baf329b6900.png)
![image](https://user-images.githubusercontent.com/79263830/159233890-cd399d2d-ff16-4d6e-a2c8-330eeec3a987.png)

Habe es für einen Boron Geweihten auch mal an getestet, selbes Ergebnis.
Ich denke dies ist falsch, oder lege ich da die Regel falsch aus. (dürfte sich dann aber voraussichtlich auf alle Geweihten beziehen?)

**Comment by Plushtoast** [comment]
Duplicate of #382
