### ISSUE TITLE
Drachenritter Kampagne: Szene "Turm im Nebelmoor" führt zum "Freeze"

### ISSUE THREAD

**Issue by Pleff** [Plushtoast/dsa5-foundryVTT#940]
Beim Aktivieren der Szene Turm im Nebelmoor friert Foundry VTT komplett ein. Es ist nur noch ein Exit (Windows-Menü) möglich.

**To Reproduce**
Aktiviere die Szene "Turm im Nebelmoor"

**Expected behavior**
Die Szene sollte natürlich geladen werden und spielbar sein.

**Screenshots**

![Screenshot 2022-03-22 100613](https://user-images.githubusercontent.com/30285276/159445525-de724fec-0f17-4a55-83aa-febe5ddef604.png)

![Screenshot 2022-03-22 100704](https://user-images.githubusercontent.com/30285276/159445533-e8bf06ff-a660-4825-b214-328ad6783ce4.png)

**Versions:**
- Foundry Version = Version 9 - Build 255
- DSA/TDE version = 3.2.5
- Related modules version "Drachenritter Einsteigerbox" = 2.5.0

**Comment by Plushtoast** [comment]
Duplicate of #882
