### ISSUE TITLE
Pre generated actors with npc sheet

### ISSUE THREAD

**Issue by Trashloot** [Plushtoast/dsa5-foundryVTT#945]
**Is your feature request related to a problem? Please describe.**
I love the way merchants and treasures are implemented but it is really annoying that every pre generated actor uses the player character sheet. I would love to be able to turn a defeated orc or bandit in to a treasure so that my players can loot them. But that is currently only possible if i recreate all the pre gens with the npc sheet. 

**Describe the solution you'd like**
There are multiple ways to fix this. 

- You could allow to turn a character in to a merchant
- You could add a button to recreate a character as a npc (you can probably reuse most of the transformation stuff to make it work)
- You could recreate all pre gens as npcs (which would be a pain for you guys) 

**Describe alternatives you've considered**
Im currently forced to recreate every animal, enemy and friendly.

**Comment by Plushtoast** [comment]
Recreating an actor as a different type won't be an option. This will create a mess.
Enabling a loot or merchant option is possible.
