### ISSUE TITLE
Improve AP tracking. 

### ISSUE THREAD

**Issue by Trashloot** [Plushtoast/dsa5-foundryVTT#947]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use Foundry for my character management. But the way AP tracking is implemented makes this impossible.
When you don't use the "increase/decrease" buttons to level your attributes/skills/... you don't pay AP. Which is annoying when you are importing characters. Fine let's go slow and click all the buttons. When you click them to fast you pay AP multiple times for the same increase without increasing the "attribute score". But you can't easily fix this because you need the character sheet to not update fast enough when you are trying to revert the points.

There is also the issue that you can't really give someone a free skill increase. Let's say you let someone increase their flying from 13 -> 14 by editing the number directly so that it doesn't cost AP. Then the game doesn't realise that your score increased meaning that you only pay for the increase from 13 -> 14 while the skill improves from 14 -> 15

**Describe the solution you'd like**
I would love to have more control over the AP. It would be nice to be able to edit how many AP a character has expanded. I would also love the ability to update how many AP i spent on a individual skill or attribute because i like to give out free skill increase or cheaper training as a game reward. 
It would also be an easy fix for wrong AP values on your character. 

I would also love an update AP tracking algorithm. I implemented one for fun back in the day. 
I basically had a function which would translate how many AP a single level of whatever costed. I fed this function the target score and the AP Factor (Steigerungsfaktor) and it returned the AP cost. 

**Example for flying:**
Input 8,A -> 8 AP. 
The improvement chart A costs 1 AP per Level up to Level 12 and then by 1 per level. So we just multiply 8 with 1 and return the value. 

**Example for Intuition:**
Input 17,E -> 60 AP. 
The improvement chart E costs 15 AP per Level up to Level 14 and then increases by 15 per level. 17 is 3 levels above 14 so we multiply just calculate (Inputlevel-13)*15 and return the value.

**Now the value change function**
Every time a number changed i would simply calculate the AP cost of the current Skill/Attribute/Whatever using the function above and substract it from the currently expended amount of AP. Then i would change the value of the Skill/Attribute/Whatever and recalculate the AP cost which i would add to the currently expended amount of AP. 

That way i only needed one algorithm for Skills/Attributes/Whatever and i didn't care if the value was increased or decreased. Because i tracked the value before and after the value change it was impossible to pay multiple times and i didn't need to force the user to use any buttons for increasing or decreasing. The algorithm simply cared about the value being changed and auto applied itself every time.  

**Describe alternatives you've considered**
I would love to have a check mark which just disables automatic AP tracking in the mean time. That way my players could at least use the AP fields to track their AP values by hand. The current system is basically only usable if you are super careful. And when you need to fix something it is often faster to just recreate the character entirely if you don't recognise the mistake immediately.

**Comment by Plushtoast** [comment]
This will not be a character generator, never.
It's already too much work. See several mentions everywhere.
Also see the character calculator in the core modul.
And finally you can edit the AP sum in the attributes/eigenschaften tab

What seems to be an easy fix is not. And I am tired of explaining this.

And you can give your players free attribute points via Active effects. Those don't interfere with the calculation.

**Comment by Trashloot** [comment]
> This will not be a character generator, never. 

I totally understand that. But why isn't there an option to disable AP tracking entirely ? It seems to me like you could have saved yourself a bunch of explaining by not including AP tracking at all. In the current version you are basically implying that the tool is a character generator. Doesn't matter that you named it a character calculator instead.

**Comment by Plushtoast** [comment]
Yeah I know it's horrible.

**Comment by Plushtoast** [comment]
I think the delta tracking is brillant. No need to switch to another tool once the character is done. And the capabilities to create a character are also already damn good.
But this is also already the end of it.
