### ISSUE TITLE
Attribute Paths for Item piles

### ISSUE THREAD

**Issue by Trashloot** [Plushtoast/dsa5-foundryVTT#948]
**Is your feature request related to a problem? Please describe.**
Im trying to configure the Module Item Piles and i am unable to figure out where the money values are stored. 
Without this information the module treats gold coins like any other item and adds them as items. 

![image](https://user-images.githubusercontent.com/50813236/160123882-eda45d7c-8ae7-4563-827c-6e94b1b6264d.png)

**Describe the solution you'd like**
I don't want any custom support for the module. I just hope that you can give me the correct path. 

P.s. I also want to inform you that the module breaks your layout. But that's not really important. Just a FYI
![image](https://user-images.githubusercontent.com/50813236/160124185-15ac8d84-83c2-4ad7-a5eb-63c4582b25e2.png)

**Comment by Plushtoast** [comment]
My recommendation is to wait for the resolution of the other ticket about merchants you created.

Money in TDE is an item, not an attribute. So according to the looks of your screenshots (I dont know the module) it's probably impossible without modifications to the TDE system or the module.

**Comment by Plushtoast** [comment]
I dont know what you intend to do with this module but TDE has also with the merchant sheet "loot" available which sounds like they behave same way to me.

The master's workshop also includes the possibility to generate random loot.

**Comment by Trashloot** [comment]
As far as i know it should be possible. I basically need to know where the variable which counts money is stored. If configured correctly the module tracks money by excluding it from the regular items. 

The Merchant and Treasure Sheets from the TDE System are incredible. But the module offers 2 things which we really like. First of all players can request to trade with each other or npcs without them being set up as a merchant. 
![image](https://user-images.githubusercontent.com/50813236/160127067-235f2907-50f0-485d-b2c6-a988bbc32c31.png)

The second cool feature is the ability to drag any item on to the ground to create a treasure pile. This can be mimicked with the treasure sheet from the TDE system. But Item piles allows the players to create Treasure piles on their own. They can basically throw any item on to the ground making it a lootable pile. The pile also gets deleted when the item is picked up again. So it basically simplifies inventory management for players in a nice way. 
![image](https://user-images.githubusercontent.com/50813236/160128934-381b5acc-cfa1-4be1-9a39-690efd757f46.png)


But i can use most of this functionality without configuring the currencies. It would be nice if players could trade money by themselves but they could also just talk to each other.  This is the reason why i don't want to make to much trouble for you. If there is no simple "path" to the money variables then you can close this issue. :D 

And yeah im super hyped about the possible resolution of my other merchant issue. I love what you are doing with inventory management. 

P.s. (just me being curious) why is there an option to search through your skills but no way to search through your inventory ? Is it this much harder to implement it for the inventory ? (This is not a real request. CTRL+F does the trick xD)

**Comment by Trashloot** [comment]
P.p.s. Your treasure piles are way nicer than the item piles but you lack the option to split Money equally between all players :P. (Not a problem)

**Comment by Plushtoast** [comment]
I actually prefer the players robbing each other.
They can share afterwards...and they usually start doing it by themselves at some point.

**Comment by Plushtoast** [comment]
The money items are of type "money" and named "money-D", "money-S", "money-H", "money-K"
