### ISSUE TITLE
Unable to add "Wildnisläufer" to Actors

### ISSUE THREAD

**Issue by Trashloot** [Plushtoast/dsa5-foundryVTT#954]
![image](https://user-images.githubusercontent.com/50813236/160279943-6d945cd3-76d5-4ff0-89ee-f0817862ad3d.png)

When you try to add the profession to a character or npc you receive this message. Doesn't matter if the character is an elf or if you drag it on to an empty character sheet.

Edit: Ok it adds everything but doesn't close the window because of the error message.

**Comment by Plushtoast** [comment]
This is the intended behavior.
You ll have to get active yourself.
