### ISSUE TITLE
SL-Willkür funktioniert nicht für TP

### ISSUE THREAD

**Issue by Meckerdrache** [Plushtoast/dsa5-foundryVTT#956]
Das Ergebnis des bzw. der W6 für die Trefferpunkte bei einem Angriff lässt sich nicht über SL-Willkür ändern, es wird dann trotzdem das ursprünglich gewürfelte Ergebnis ausgegeben.

**Comment by Plushtoast** [comment]
Kannst du beschreiben unter welchen Umständen das passiert?
Funktioniert bei mir ganz normal.

Du editierst dabei nur den Würfel nicht den Bonusschaden zb 1d6+3
Kann es sein, dass du dadurch afu das gleiche Ergebnis gekommen bist?

**Comment by Meckerdrache** [comment]
Nein, das ist bei mir grundsätzlich so, dass ich z.B. von 6 auf 1 ändere und dann die TP trotzdem am Ende bei 10 statt 5 sind, sobald es im Chat erscheint. Beim W20 funktioniert es einwandfrei, aber bei den TP leider nicht. Soll ich nachher mal Screenshots machen?

**Comment by Plushtoast** [comment]
habs
