### ISSUE TITLE
(Eng) Power Focus (Staff Enchantment) Does not work

### ISSUE THREAD

**Issue by Lambert-Behnke** [Plushtoast/dsa5-foundryVTT#968]
When calculating the cost of spells, the system takes into account the Special Ability: Energy Control, but not the Staff Enchantment Power Focus. Both should work the same way, but Energy control is hard coded in the  **calculateEnergyCost** method, and so I cannot duplicate the effect of it in the Special Ability for Power Focus. 

Seeing that the player needs to have the staff in hand to receive the reduction, there should be an option on the casting page of spells to select whether the staff is in hand. A little like the options to select to reduce cost, or to highlight Spell Extensions (even though those don't seem to have actual effects yet). 

Difficult to give you a good screenshot for this.

**Foundry Version:** 9 - Build 255
**Dark System Version:** 3.2.5
**Dark Eye Core Rules:** 3.2.0

**Comment by Plushtoast** [comment]
My recommendation is add a manual effect to the character and disable or enable it whenver required.

There will not be another option on the casting page, but weapons will be able to contain apply effects to the enemy and apply effects to self. The latter one will be activated if equipped.
But...this will still require to modify the staff, since the staff kind of provides the bonus and not the ability...

**Comment by Lambert-Behnke** [comment]
What would the required effect text be on the Staff, or a special ability I can give the player?
I had hoped to copy the text from Energy Control, but that wasn't possible. 

-1 AE ?

**Comment by Plushtoast** [comment]
![grafik](https://user-images.githubusercontent.com/44941845/161576066-6696fb53-3aed-4be3-b6a5-5ee6eceb2d6f.png)

Not on the staff. This is currently not possible. Special ability is permanent. So best is manual effect like the one above (which can be disabled)

**Comment by Lambert-Behnke** [comment]
Cool,
That is all I need, feel free to close the ticket. This is better, it works automagically when the staff is equipped.

**Comment by Plushtoast** [comment]
Anyone reading this: add the effect to your mage's staff
