### ISSUE TITLE
Quickload (Crossbows) don't reduce reloading time

### ISSUE THREAD

**Issue by TheMarinx** [Plushtoast/dsa5-foundryVTT#969]
**Describe the bug**
Quickload (Crossbows) don't reduce reloading time for crossbows

**To Reproduce**
Drag special combat ability Quickload (Crossbow) from library to character sheet. 
Equiped crossbows reloading time is not reduced

**Expected behavior**
Equiped crossbows reloading time should be reduced by half.

**Solution**
Quickload (Crossbow) special combat ability have wrong name and it works fine if you rename it to Quickload (Crossbows)

(Just add an **s** at the end of the name)

This should be fixed in official library.

**Comment by Plushtoast** [comment]
Unfortunately we wont be able to fix this backwards.
