### ISSUE TITLE
[Content] Grundregelwerk - Fehlende Tabellen in Jounrnaleintrag zu Ausrüstung

### ISSUE THREAD

**Issue by karabiberym** [Plushtoast/dsa5-foundryVTT#976]
**Describe the bug**
leider fehlen im Grundregelwerk im Journaleintrag zu Ausrüstung viele Tabellen, welche in der PDF Version vorhanden sind.

**Screenshots**
![image](https://user-images.githubusercontent.com/8050096/162580027-d56f70ae-9433-4ec1-8d84-05254310e24b.png)

**Versions:**
- Foundry Version 9 - Build 255
- DSA/TDE version 3.2.5
- Related modules version 3.2.0

**Comment by Plushtoast** [comment]
Liegt daran dass die ganzen Gegenstände in der Bibliothek verfügbar sind (und komfortabel gesucht und per drag and drop den chars hinzugefügt werden können)
Falls du neu bist empfehle ich einen Blick ins Wiki oder in vttoms YouTube Channel

**Comment by karabiberym** [comment]
Der Journaleintrag sah im Vergleich zum Buch etwas leer aus, weshalb ich erst dachte, dass eventuell vergessen wurde die Tabellen einzutragen. :sweat_smile: 
Es stimmt zwar, dass man fast alle Items auch in der Bibliothek finden kann, allerdings müsste man genau wissen, nach was man suchen möchte. Ich finde es hat durchaus seinen Vorteil, wenn die Gegenstände bereits nach ihrem Themengebiet in Tabellen im Journal geordnet sind, da man so einen schnellen Überblick hat, welche Gegenstände es in einem Themengebiet gibt. Außerdem wäre es gerade für Neueinsteiger oder Leute, welche die Bücher gewohnt sind, etwas übersichtlicher.

Wenn ich zum Beispiel nach allen Musikinstrumenten suchen wollte, könnte ich einfach in der Tabelle nachsehen und hätte eine Übersicht über alle zugehörigen Gegenstände. Mit der Bibliothek müsste man allerdings alle Einträge ansehen.

Des Weiteren ist die Tabelle für die Fortbewegungsmittel weder im Journal zu finden, noch sind deren Einträge in der Bibliothek zu finden.

Aber ich kann auch sehr gut verstehen, wieso man dies nicht machen möchte, da es zusätzlicher Arbeitsaufwand ist,
den man für definitiv wichtigere Neuerungen und Verbesserungen aufwenden könnte.
Dennoch vielen Dank für deine schnelle Antwort :smile:

**Comment by Plushtoast** [comment]
Wenn du in der Bibliothek auf den Gehirnbutton clickst kommen noch zusätzliche Filtermöglichkeiten. Unter anderem müsste man da auch nach Musikinstrumenten filtern können.

**Comment by karabiberym** [comment]
Leider nicht, da die Musikinstrumente zu der Ausrüstungskategorie "Allgemein" gehören.
