### ISSUE TITLE
dsalist Icon wird nach dem Bearbeiten nicht mehr angezeigt

### ISSUE THREAD

**Issue by Nyhles** [Plushtoast/dsa5-foundryVTT#98]
**Describe the bug**
Nach dem Editieren eines Eintrags das das dsalist Icon (das Auge) enthält, z.B. die Tradition (Perainekirche) wird nach dem Abspeichern das Icon nicht mehr angezeigt.
Ich vermute das die Formatierung geändert wird, da auch unerwartete Zeilenumbrüche entstehen.

**To Reproduce**
1. Tradition (Perainekirche) öffnen
![dsalist Icon vorhanden](https://user-images.githubusercontent.com/79369393/108606201-febe6780-73b8-11eb-902e-f9d784cbed9f.png)
1. Beschreibungstext zum Editieren öffnen
2. Irgendeine Ändereung vornehmen, z.B. den ersten Buchstaben löschen und wieder einfügen
3. Abspeichern.
4. dsalist Icon ist verschwunden
![dsalist Icon nicht vorhanden](https://user-images.githubusercontent.com/79369393/108606205-067e0c00-73b9-11eb-9a14-af9608ca1b33.png)

**Expected behavior**
dsalist Icon nach dem Editieren behalten

**Comment by Plushtoast** [comment]
Editing predefined content is and will not be supported.

**Comment by Nyhles** [comment]
Is it possible to get the dsalist icon when manually creating content to show? Is there a special kind of formatting requiered or is it really only possible to show it in the predefined content?

**Comment by Plushtoast** [comment]
You can look at the html code and adapt from there.
But code explanation will also not be supported..
