### ISSUE TITLE
Zauber Ecliptifactus 

### ISSUE THREAD

**Issue by Lauta1988** [Plushtoast/dsa5-foundryVTT#980]
Der Zauber Ecliptifactus beschwört den Schatten des Zaubernden. 
Ist es möglich diesen Zauber in das Beschwörungsfenster zu integrieren ?
Derzeit nutze ich zusätzliche Token als Alternative

**Comment by Plushtoast** [comment]
Jup, den Zauber will ich mir noch vornehmen. Da er aber etwas komplizierter ist, wird das noch ein wenig dauern.

**Comment by Lauta1988** [comment]
Das freut mich zu hören. Durch die Qualitätsstufen habe ich doch immer wieder Probleme den Zauber als SL richtig darzustellen. Ich freue mich wenn es dafür irgendwann eine Lösung gibt. p.s gute Arbeit bisher und weiter so.
