### ISSUE TITLE
Sonderregeln Korspieß

### ISSUE THREAD

**Issue by Xardai** [Plushtoast/dsa5-foundryVTT#981]
**Is your feature request related to a problem? Please describe.**
Der Korspieß kann die Sonderfertigkeiten Aufspießen, Festnageln und Zu Fall bringen nutzen, auch wenn er keine Stangenwaffe ist.
Diese sind beim Angriffswurf nicht wählbar.

**Describe the solution you'd like**
Bei einem Angriff können die Manöver ausgewählt werden

**Comment by Plushtoast** [comment]
Du kannst die Sonderfertigkeiten auf dem Char so editieren, dass bei Kampftalente auch Stangenwaffen drin steht. Dann sollte es funktionieren.
Ich gehe derzeit nicht  davon aus, dass solche Sonderregeln automatisch umgesetzt werden.

**Comment by Xardai** [comment]
Die Lösung ist denk ich ausreichend. Danke
