### ISSUE TITLE
DSA Foundry am Tisch spielen

### ISSUE THREAD

**Issue by BunteDimensionen** [Plushtoast/dsa5-foundryVTT#982]
Wir spielen DSA Foundry mit zwei Rechnern (Spielleiter & Helden) und einem Touchscreen (TouchVTT) klassisch am Tisch.
Obwohl Foundry darauf ausgelegt ist, daß jeder Spieler sich mit seinem eigenen PC einloggt und mitspielt funktioniert das System auch sehr gut am Tisch. Bis auf ein wenige Ausnahmen:

Nur der eingeloggte Helden-Rechner kann mit Händler/Schatz interagieren.

Toll wäre wenn man die Ausgabefenster (Heldenblatt, Probenfenster, Chat) drehen könnte, damit nicht ein Teil der Gruppe die Schrift um 180° verdreht sieht. Vielleicht ein Menü in welchem man die Sitzpostionder Spieler am Anfang der Runde festlegen kann, damit sich die Fenster automatisch drehen oder am Fenster ein Drehknopf. Sonst bleibt leider stets ein Teil Gruppe etwas inaktiv, da die anderen Spieler vorlesen oder Knöpfe drücken.

**Comment by Plushtoast** [comment]
Ist euer Bildschirm zentral im Tisch gelegen? Oder wie is der positioniert?

Ich vermute ein einfacherer weg wäre es, den Bildschirm für alle sichtbar zu machen und dafür den bogen bei jedem Spieler am Handy.

**Comment by BunteDimensionen** [comment]
Der Bildschirm ist zentral im Tisch eingebaut.

Eine Handy/tablet-Lösung wäre optimal. Gibt es da eine gute Unterstützung?

**Comment by vt-tom** [comment]
Es gibt Module die aber leider nicht mehr weiter Entwickelt wurde. Teilweise funktionieren sie aber noch ganz gut:
Touch VTT
Mobile Improvements
Laptop Form Fix
Minimal UI

**Comment by BunteDimensionen** [comment]
Danke Tom, weiß aber nicht so recht wie mir diese Module helfen können.

**Comment by vt-tom** [comment]
Ich dachte ich werfe die mal in den Ring. Vielleicht hilft dir das ein oder anderen schon bei ein paar Problemen.

**Comment by BunteDimensionen** [comment]
Das ist nett von Dir!
Am meisten würde helfen:
Wenn man die Ausgabefenster (Heldenblatt, Probenfenster, Chat) drehen könnte, damit nicht ein Teil der Gruppe die Schrift um 180° verdreht sieht. Vielleicht ein Menü in welchem man die Sitzpostion der Spieler am Anfang der Runde festlegen kann, damit sich die Fenster automatisch drehen oder am Fenster ein Drehknopf. Sonst bleibt leider stets ein Teil Gruppe etwas inaktiv, da die anderen Spieler vorlesen oder Knöpfe drücken.

**Comment by mckee14** [comment]
Dreht doch einfach das touch display? Es gibt auch drehteller für TVs,
sowas kann man nutzen.

Alternativ kann man über eine Tastenkombi die Bildschirmausrichtung von
Windowsrechnern ändern.



BunteDimensionen ***@***.***> schrieb am So., 17. Apr. 2022,
21:53:

**Comment by BunteDimensionen** [comment]
Der Bildschirm ist im Tisch verbaut und wiegt 37 kg :-)
Die Tastenkombis muss ich testen.

**Comment by mckee14** [comment]
Du musst die Tastenkombinationen dafür in Windows aktivieren. Danach sind
es standardmässig Ctrl + Alt + Pfeiltaste hoch/runter/links/rechts.

BunteDimensionen ***@***.***> schrieb am So., 17. Apr. 2022,
22:53:

**Comment by BunteDimensionen** [comment]
Danke für den Tipp, dann schaue ich wo man die Tastenkombis aktiviert.

**Comment by Neon82** [comment]
Hi könntest du beschreiben wie du die Spieler ihre Steuerung an nur einem PC machen?? GM eigener Rechner ist klar. Hat der Spieleraccount dann rechte auf alle Spieler? 
Ich mache mir seit einiger Zeit Gedanken wie ich das umsetzten kann mit meiner Gruppe wie zurück an einen Tisch aber mit voller Foundry Unterstützung^^ (keiner aus der Gruppe will mehr drauf verzichten) wollte zuerst nen alten 37" Fernseher auf den Tisch legen und nutzen, kam jetzt aber auf die Idee nen Beamer dafür zu verwenden. Nur die Eingabe Steuerung der Spieler macht mir noch Kopf schmerzen. 
Idealer weise wäre es die Spieler könnten auf nem Tablet ihren Heldenblatt, Probenfenster, Chat nur darauf sehen. (Tablet weil das doch weniger Platz als ein Laptop verbraucht UND das Grundfeeling mit nur nem Spielerbogen vor sich doch schöner ist)
funktioniert erstmal ganz gut nur das anvisieren der ziele klappt so noch nicht, aud dem Spielerbogen vom Tablet kann kein angriff/Zauber/Probe gegen ein zielgewürfelt werden wenn man der Spieler es nicht selbst anvisiert.

**Comment by BunteDimensionen** [comment]
Hi,
Hardware: 1 Rechner für den GM und ein Rechner für die Helden. Der Helden-Rechner ist an den Touch-Bildschirm und das BT-Soundsystem angeschlossen. Der Helden-Rechner hat die Rechte für alle Spieler.

**Comment by BunteDimensionen** [comment]
Habe gestern zum ersten Mal mit dem Update 3.4.2. gespielt.
Der neue Combat-Tracker ist klasse, vor allem das man mit dem + bei der Angriffsprobe das Ziel hinzufügen kann ist sehr hilfreich
Dieses + würde ich mir beim Händler/Schatz wünschen, mit welchem die Helden auswählen kann die sich im Meister Menü unter Charaktere befinden. Das man jetzt andere Helden auf den Händler schieben kann, obwohl nur einer angemeldet ist eine tolle Verbesserung.

**Comment by BunteDimensionen** [comment]
Gib es eine Möglichkeit die Chatbefehle "pay" und "getPaid" auf einzelne Helden zu legen?

**Comment by Plushtoast** [comment]
Hab ich das nicht schon ins meistermenue auf die letzte Anfrage hin eingebaut?

**Comment by BunteDimensionen** [comment]
Doch das hast Du ;-) Habe ich nicht mehr auf dem Schirm gehabt.
Gibt es einen Journaleintrag um Helden Geld/AP zu geben?
