### ISSUE TITLE
Größe von Kreatur Tokens lässt sich nicht ändern

### ISSUE THREAD

**Issue by GMMarkus** [Plushtoast/dsa5-foundryVTT#988]
**Describe the bug**
Erstellt man im Akteurverzeichnis eine Kreatur und stellt bei dieser für die Größe des tokens Werte ein (z.B. Breite 1 Höhe 1 Skalierung 1,8) und erzeugt dann einen Akteur in einer Szene, so werden diese Werte überschrieben.
Für Normale Kreaturen mit: Breite 1 Höhe 1 Skalierung 1
Für Große Kreaturen mit: Breite 2 Höhe 2 Salierung 1
Für Riesige Kreaturen mit: Breite 4 Höhe 4 Skalierung 1

**To Reproduce**
siehe oben

**Expected behavior**
Die Größeneinstellung des Akteurs werden beim Neuerzeugen eines Akteurs in einer Szene verwendet.

**Screenshots**

**Versions:**
- Foundry   Version 9 Build 249
- DSA/TDE   3.3.0

**Additional context**

**Comment by Plushtoast** [comment]
Wenn du die automatische Tokengröße nicht verwenden willst, kannst du diese hier am Prototypetoken deaktivieren:

![grafik](https://user-images.githubusercontent.com/44941845/163885104-ca63cfb1-4f4d-4bf8-b7e7-6b88055c37dd.png)

**Comment by GMMarkus** [comment]
Danke!
