### ISSUE TITLE
Der (erfolgreiche) Einsatz eines Effekte, die z.B. durch den Einsatz einer Waffe ausgelöst werden, wird markiert.

### ISSUE THREAD

**Issue by UralterMannII** [Plushtoast/dsa5-foundryVTT#989]
**Is your feature request related to a problem? Please describe.**
Auch im FoundryVTT-Universum scheint es Latenz zu geben. U.a. passiert es, daß Spieler auf den Button "Effekt(Selbst)" oder "Effekte(Ziel)" mit dem Kommentar "da passiert nichts" mehrmals klicken und ich (als Spielleiter) dann aufpassen muss, dass die Effekte nicht "1000mal" angewandt wurden...grml...und dann auch noch "aufräumen" muss...GRML....

**Describe the solution you'd like**
Nach dem ersten Klick werden beiden Buttons deaktiviert, sodaß mehrmaliges anklicken (absichtliches oder auch unabsichtliches) nicht möglich ist.

**Describe alternatives you've considered**
Ähnlich wie beim Anwenden der TP auf sich selber für jeden Klick auf den Button ein "Hacken" neben dem Button anzeigen (als Clientseitiges Skriptbestandteil und nicht nach dem Roundtrip zum Server). Dann ist 1. dem Spieler klar, was/dass er angeklickt hat und 2. auch sichbar wie oft das passiert ist...

**Additional context**
Buttons, auf die ich mich beziehe, die - in diesem Fall - nach einem erfolgreichen Angriff mit einer Waffe mit Effekt erscheinen:
![grafik](https://user-images.githubusercontent.com/87266660/164005500-1310bf29-b3d0-473d-8c6c-7bf919ee05fd.png)

**Comment by Plushtoast** [comment]
Also ausblenden wird nicht so gut sein, da man hier auch das Ziel im Target haben muss und das bei z.b. Zaubern nicht bereits vor dem Würfeln der Fall sein muss.
Wenn man dann klickt und das falsche Ziel hatte, fehlt der Button.
Haken geht aber.

**Comment by UralterMannII** [comment]
Ich verstehen: Spieler klick sich selber an...oh Sorry Meister...jetzt aber richtiges Ziel (inkl. "Aufräumen" beim falschen Ziel).

Mehrere Haken möglich (für jeden Klick)?

**Comment by Plushtoast** [comment]
Ich deaktiviere den Button für 1 oder 2 sek

**Comment by UralterMannII** [comment]
Wäre auch eine "Textveränderung" gleichzeitig möglich, solange der Button "deaktivert" ist ... z.B. "...in Anwendung...", "...bitte warten...", "...sende..." etc.. Und danach wieder der "alte" Text?...dann ist auch klar, dass es nicht ein "Fehler" ist, sondern, dass hier auch vom FoundryVTT was gemacht wird...
