### ISSUE TITLE
Anvisieren von Zielen (sichtbar für Token), via Characktersheet

### ISSUE THREAD

**Issue by Neon82** [Plushtoast/dsa5-foundryVTT#991]
Ich teste grad wie ich nur die Karte via Beamer auf den Tisch projiziere (Monitor/TV wäre das gleiche Prinzip) und meine Spieler via Tablet nur ihren Charakterbogen offen haben um Proben/Angriffe etc darüber nutzen. sämtliche Bewegungen sagen sie an und ich als GM bewegen die Token dann bzw Selektiere die Ziele. 
Selektiere ich die Ziele aktuell, kann man der Spieler dennoch nicht das ziel angreifen da er es nicht selbst anvisiert hat. hier wäre es gut wenn man eine Auswahl der möglichen anvisierbaren Ziele hätte.

**Comment by Plushtoast** [comment]
Ich glaub bevor wir an die Tischumsetzung gehen, müssen erstmal noch mehr Ideen gesammelt und abgewogen werden.
