### ISSUE TITLE
Traditionsartefaktsonderfertigkeiten speziefischer Traditionen nur schwer auffindbar

### ISSUE THREAD

**Issue by Zonenpenner** [Plushtoast/dsa5-foundryVTT#997]
**Is your feature request related to a problem? Please describe.**
Versucht man herauszufinden, welche Traditionsartefaktsonderfertigkeiten nun welchem Zauberer oder Geweihtem zur Verfügung stehen, hat man ein Problem, Da es keine geeigneten Filtermöglichkeiten gibt.

**Describe the solution you'd like**
Filtermöglichkeiten für das oben genannte Problem

**Describe alternatives you've considered**
Wären in den Journal-Regelbänden an den entsprechenden Stellen wo im Orginal die Sfs / Listen oder was auch immer stehen, die Links zu den entsprechenden Items, wäre das nicht so ein großes Problem.

**Additional context**
Auf ähnliche Probleme stößt man, wenn man versucht SFs für ein spezifisches Talent oder eine Kampffertigkeit zu finden.

**Comment by Plushtoast** [comment]
Ab v10 werden alle sonderfertigkeiten erstmal das passende bild haben.
ein extra feld für die zuordnung zur waffe ist derzeit nicht vorgesehen
